### ISSUE TITLE
US Phone company mail servers are reporting email sent with MailKit contains bare CR

### ISSUE THREAD

**Issue by Saurbaum** [jstedfast/MimeKit#1004]
**Describe the bug**
Phone company mail servers are reporting email sent with MailKit contains bare CR
552 5.2.0 Message contains bare CR and is violating 822.bis section 2.3

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET 4.5
 - MailKit Version: 4.2.0

**To Reproduce**
I personally have not managed to reproduce this using any of the mail servers I have access to but my protocol log looks the same as the logs I was sent.

I'm filling in my message and checking in notepad++ that it looks like this
![image](https://github.com/jstedfast/MailKit/assets/7288848/0e3b85ee-e46e-45e4-ba7b-9b932fa0f61c)

and when I check the protocol log I see this which definitely looks like CR without a trailing LF
![image](https://github.com/jstedfast/MailKit/assets/7288848/48abf9e9-f09c-47c9-ab7c-2ebf36a7aa21)

**Protocol Logs**
[SMTP Protocol Log Filename.txt](https://github.com/jstedfast/MailKit/files/14220225/SMTP.Protocol.Log.Filename.txt)

**Additional context**
This appears to be specific to mail recipients using xxxxxxxxxx.vtext (where xxx.. is their phone number and .vtext is for Verizon phones) and when the same user changes to a normal email address this appears to work.

There has been a suggestion that the major phone carriers (ATT,Verizon) have tightened up the rules for message sending but I'm on the wrong side of the Atlantic to be able to check this directly.

**Comment by jstedfast** [comment]
Not sure if the above commit fixes this (sorta seems like it shouldn't?), but it's the only issue I could find.

**Comment by jstedfast** [comment]
Ok, so this is likely to either be a bug in MimeKit's Unix2DosFilter -or- MailKit's SmtpDataFilter.

Not sure which (if either) the bug exists in :-\

If it's not in either of those, not sure where it could be...

**Comment by jstedfast** [comment]
Would it be possible to attach the original text/plain and text/html content files? Those might help me diagnose this a bit.

**Comment by Saurbaum** [comment]
I'll see what I can dig out on Monday when I'm in the office.

**Comment by Saurbaum** [comment]
Welp this is utterly weird. Problem is definitely my end and not in [Mail/Mime]Kit.

If I inspect the strings in the debugger they are showing CRLF as expected. As soon as I dump them out to a file they revel their true colours.

**Comment by jstedfast** [comment]
But that still doesn't explain why carriers are saying your emails contain bare carriage returns right? Or am I confused?

**Comment by Saurbaum** [comment]
It seems I had in the HTML formatting some lines ending in LFCR. That seemingly would be processed into
<some html>LF
CR

And I think looking at the way it would convert the HTML into a plain text version it would end up with a series of LFCR at the start of the message which the viewer in Visual Studio was than trying to make human readable and not showing the actual data.

So the email message absolutely does have a bare CR in it because its companion LF is on the previous line. Making it harder to spot in my data was that when you have a chain of several together they look much more normal.
LF
CRLF
CRLF
CR
