### ISSUE TITLE
HTML base64 to CID conversion  

### ISSUE THREAD

**Issue by NivineZakhari** [jstedfast/MimeKit#1010]
**Is your feature request related to a problem? Please describe.**
Some email clients still do not handle base64 images well in HTML, so being able to convert to CID would help.

**Describe the solution you'd like**
HTML Message base64 to CID image handling

**Describe alternatives you've considered**
Force plain text format or CDN for some recipients 

**Additional context**
This would help standardize how messages are handled for recipients unable to process base64 images

**Comment by jstedfast** [comment]
This doesn't really make sense to have as part of the MimeKit API. It would make more sense to implement this as a tool.
