### ISSUE TITLE
broken messageid

### ISSUE THREAD

**Issue by RobiGoBH** [jstedfast/MimeKit#102]
I have found a very interesting message, when I get the messageid from message header, I have it, but when I download the whole message, the message-id is null....

**Comment by jstedfast** [comment]
Can you paste the raw Message-Id header?

**Comment by RobiGoBH** [comment]
Return-Path: <do_not_reply@holidayextras.com>
From: "Holiday Extras" <do_not_reply@holidayextras.com>
To: <ADMIN@LOVEHOLIDAYS.COM>
Subject: Airport parking confirmation - M6J1RB2
Date: Wed, 18 Feb 2015 20:33:33 -0000
Message-ID: <njzifx.9stqh0@>
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_574F_01D04C50.67E8A960"
X-Mailer: Microsoft Outlook 14.0
Thread-Index: AQIdOY53R0vE5tZKkaw8Q7DeC7CQZQ==
X-OlkEid: AE24482F429F9FED1522BA4284BEE4B93E04FC5C

This is a multipart message in MIME format.

------=_NextPart_000_574F_01D04C50.67E8A960
Content-Type: text/plain;
	charset="utf-8"
Content-Transfer-Encoding: 8bit
.....
.....
.....

**Comment by jstedfast** [comment]
This should be fixed now (I added unit tests which confirm the fix)
