### ISSUE TITLE
Will the order of the `MimeMessage.Attachments` (i.e., `MimeMessage.EnumerateMimeParts`) enumeration be permanent?

### ISSUE THREAD

**Issue by fyodorklimenko** [jstedfast/MimeKit#1021]
Dear Mr. Stedfast,
Thank you for your effort and the fantastic library!

I want to use the index of the `MimeMessage.Attachments` ([src](https://github.com/jstedfast/MimeKit/blob/4.4.0/MimeKit/MimeMessage.cs#L1113)) element as a unique identifier for attachments within the scope of a single MIME message.

As a result, a change in the `EnumerateMimeParts` method ([src](https://github.com/jstedfast/MimeKit/blob/4.4.0/MimeKit/MimeMessage.cs#L1070-L1085)) may break the logic of my project.

Can I be sure that the enumeration of attachments will ALWAYS be from top to bottom?
Is the order of the enumeration a part of the method contract?

**Comment by jstedfast** [comment]
Yes, the MimeMessage.Attachments implementation will always use a depth-first approach.
