### ISSUE TITLE
Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

### ISSUE THREAD

**Issue by jacdy** [jstedfast/MimeKit#1027]
**Describe the bug**
Since upgrading to the latest version with nuget I keep getting the error below

Could not load file or assembly 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

at MimeKit.Header.Unfold(String text)
at  MimeKit.Header.SetValue(FormatOptions format, Encoding encoding, String value)

**Platform (please complete the following information):**
 - OS:  Windows and MacOS
 - .NET Runtime:  Mono
 - .NET Framework:.NET 4.7.2
 - MimeKit Version: 4.5.0

**Comment by jstedfast** [comment]
You'll find your answer here: https://stackoverflow.com/a/67973309/87117
