### ISSUE TITLE
MimeKit is parsing address as `GroupAddress` instead of `MailboxAddress`

### ISSUE THREAD

**Issue by Sharpiro** [jstedfast/MimeKit#1042]
**Describe the bug**

MimeKit is parsing the following as a `GroupAddress` instead of a `MailboxAddress`:

```
From: First Last [COMPANY/ AREA:] <user@email.com>
```

I think it is not liking the colon in the brackets, though Outlook sees this as a valid format.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: net core 8
 - MimeKit Version: 4.6.0

**To Reproduce**

- `MimeMessage.Load(emlStream)`
- Check from address

**Expected behavior**

MimeKit should parse the address as a `MailboxAddress`

**Comment by jstedfast** [comment]
The problem is that syntactically, it *is* a GroupAddress. Bare colons aren't allowed in the name component of a mailbox address according to the specifications. I'm not sure I can "fix" this without breaking support for group addresses :(

**Comment by Sharpiro** [comment]
I see.  If the format is indeed invalid I can just handle this at a higher level.  Thanks.
