### ISSUE TITLE
Mimekit 3.3+ Japanese CP encoding regression?

### ISSUE THREAD

**Issue by ZeldoRica** [jstedfast/MimeKit#1047]
When decoding the following using MimeMessage.Load
```
Date: Mon, 17 Jun 2024 09:13:07 +0900
MIME-Version: 1.0
Content-Type: text/plain; charset=ISO-2022-JP
Content-Transfer-Encoding: 7bit

[ESC]$B>'[ESC](B3895 
```
(replace [ESC] with 27)

Mimekit 3.3 decodes the text body as
唱3895

Mimekit 3.4 and all versions above, including latest decodes it as
\x1b$B>'\x1b(B3895

This happens on dotnet 8 core on MacOS

Any idea where the problem lies?
Thanks

**Comment by jstedfast** [comment]
I found this in the MimeKit v3.4 release notes:

* Don't call Encoding.RegisterProvider() anymore. Rely on developers doing this themselves in their application startup logic.

There's 2 things you need to do:

1. Make sure that your app adds a PackageReference to [System.Text.Encoding.CodePages](https://www.nuget.org/packages/System.Text.Encoding.CodePages/)
2. Call `System.Text.Encoding.RegisterProvider (System.Text.CodePagesEncodingProvider.Instance);` at program startup

That should fix the issue.
