### ISSUE TITLE
message/rfc822 attachment with blank Content-Transfer-Encoding header causes attachment to become corrupted when loaded and prepared by mimekit

### ISSUE THREAD

**Issue by The-Nutty** [jstedfast/MimeKit#1049]
**Describe the bug**

**Platform (please complete the following information):**
 - OS: Windows, Linux
 - .NET Runtime: NET8
 - .NET Framework: NET8
 - MimeKit Version: 4.1.0 and 4.6.0 tested

**To Reproduce**
1. In a new .NET console app with Mimekit installed, paste the following
```csharp
var msg = MimeMessage.Load("demo.eml");
msg.Prepare(EncodingConstraint.None);

msg.WriteTo("output.eml");
```
With [demo.eml](https://github.com/user-attachments/files/15989327/demo.eml.zip) set to copy to output directory.

2. Run the script and it will generate [output.eml](https://github.com/user-attachments/files/15989335/output.eml.zip)
3. Open both in a message viewer (IE outlook): demo.eml will work fine with the attached email text being readable "A medium-severity alert has been triggered....." output.eml the attachment will instead show "--=3D-th9mpsHWlvyU5398Ajg2gQ=3D=3D
Content-Type: multipart/alternative; boundary=3D"=3D-opcn9iLL5vM98wIjSIhg+Q=
=3D=3D"

--=3D-opcn9iLL5vM98wIjSIhg+Q=3D=3D
......."

**Expected behaviour**
The attachment should not be corrupted when loaded, prepared and saved by mimekit.

**Additional context**
This seems to only occur when time message/rfc822 header has a `Content-Transfer-Encoding:` header, this does not happen with either `Content-Transfer-Encoding: quoted-printable` or a no Content-Transfer-Encoding at all.

**Comment by jstedfast** [comment]
My gut instinct is that this is where things are going wrong:

https://github.com/jstedfast/MimeKit/blob/master/MimeKit/ParserOptions.cs#L358-L383

Technically, what is likely going wrong is the `IsEncoded()` logic here: https://github.com/jstedfast/MimeKit/blob/master/MimeKit/ParserOptions.cs#L282-L294

but the first link I pasted contains the "justification" for said logic and why it's being used at all.

2 possible fixes that might work:

1. Modify `IsEncoded(ContentEncoding encoding)` to add `ContentEncoding.Default` to the list of values that `return false`
2. Modify `IsEncoded(IList<Header> headers)` to `return false` if the TryParse() fails

**Comment by jstedfast** [comment]
I'll want to add unit tests for this (for both MimeParser and ExperimentalMimeParser) before I call this "complete", but in the meantime, I figured I'd push those potential fixes and you'll be able to test the nuget package (that will get pushed to [myget.org](https://www.myget.org/feed/mimekit/package/nuget/MimeKit)) when the CI/CD pipeline finishes pushing out a new build/package.

**Comment by The-Nutty** [comment]
Brilliant, thanks for your help really appreciate the quick response.

**Comment by jstedfast** [comment]
Just added some unit tests and it seems like it works.
