### ISSUE TITLE
"|" and English cannot be correctly transcoded together

### ISSUE THREAD

**Issue by Krisxxxxx** [jstedfast/MimeKit#1051]
**Describe the bug**
 The subject cannot be correctly encoded when using pipeline symbols and English together.

**Platform (please complete the following information):**
 - OS: 
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: .net 6.0
 - MimeKit Version: 4.6.0.0

**To Reproduce**
For example:
Subject is "直播预告 | Viventis LS2 Live 光片显微镜发布会", The result of transcoding is “=?utf-8?b?55u05pKt6aKE5ZGK?= | Viventis LS2 Live =?utf-8?b?5YWJ54mH5pi+5b6u6ZWc5Y+R5biD5Lya?=”

**Comment by jstedfast** [comment]
I don't see the problem?

**Comment by Krisxxxxx** [comment]
> I don't see the problem?

**' | Viventis LS2 Live '** not transcoded.

**Comment by jstedfast** [comment]
it's not supposed to be

**Comment by Krisxxxxx** [comment]
> it's not supposed to be

so this is a result that meets expectations?

**Comment by jstedfast** [comment]
Yes.
