### ISSUE TITLE
GetMimeType(byte[] data) returns "audio/x-wav" for a .webp file instead of "image/webp"

### ISSUE THREAD

**Issue by kiwidyne** [jstedfast/MimeKit#1075]
**Describe the bug**
When getting the contents of a .webp file from Google's webp gallery (specifically https://www.gstatic.com/webp/gallery/1.webp - although many other webp files caused the same behavior), putting the contents into a byte array (`byte[]`), and then calling `.GetMimeType(byte[] data)`, the Mime type returned is "audio/x-wav" instead of "image/webp".

Windows 11 Pro (x64)
CoreCLR
.Net 8
MimeKit Version: 4.7.1

**Comment by jstedfast** [comment]
MimeKit doesn't have a `GetMimeType(byte[] data)` method. You are probably using some other MimeType library perhaps?

**Comment by kiwidyne** [comment]
Ugh. This is what I get for being tired. My apologies.

**Comment by kiwidyne** [comment]
OK, not as tired as I thought. I am not the original author of the code utilizing this. It *is* leveraging MimeKit, but it is also utilizing Winista.MimeDetect, which _also_ has a class named `MimeTypes`, which contains the function I referenced in the bug report, hence my confusion. Again, sorry for the mixup.
