### ISSUE TITLE
Wrong encoded-word token

### ISSUE THREAD

**Issue by wahtherewahhere** [jstedfast/MimeKit#1079]
Hi,

There is an encoded-word-token bug that causes the failure of sending emails.

It needs to be capital Q and B in following codes:
https://github.com/jstedfast/MimeKit/blob/4.7.1/MimeKit/Utils/Rfc2047.cs#L1074
https://github.com/jstedfast/MimeKit/blob/4.7.1/MimeKit/Utils/Rfc2047.cs#L1077

Thanks

**Comment by jstedfast** [comment]
What makes you think that?

**Comment by wahtherewahhere** [comment]
I sent mail to M365 and get bad format with lower case.

**Comment by jstedfast** [comment]
Can you provide me with logs?
