### ISSUE TITLE
MimeKit for HttpWebRequest, server-2-server

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#109]
Howdy, I am currently implementing a "WebService API", for posting data from one server to another, and "application/x-www-form-urlencoded" Content-Type is a relative easy thing to implement, but obviously "multipart/form-data" is "harder" to say the least. Besides, I also want to implement support for Signing messages and Encryption of messages.

So my question is, would MimeKit be a nice alternative for creating my messages, or would I struggle due to that MimeKit is not really built for that type of job ...?
Would MimeKit be a nice fit for implementing a WebService API ...?

For the record, I do not intend to send XML, and hence WSDL and such becomes a no-no, but instead pass on my own format for the most parts (Hyperlisp, JSON'ish like format), in addition to of course being able to transmit "any data", in addition to files and such, both Signed if possible, in addition to Encrypted ...

**Comment by jstedfast** [comment]
MimeKit is mostly focused on MIME in the form of email, but it can easily be used to construct and serialize multipart Content-Type data.

for example, you could do:

```csharp
var data = GetRawUrlEncodedData ();
var multipart = new Multipart ("form-data");
var urlencoded = new MimePart ("application", "x-www-form-urlencoded") {
    ContentObject = new ContentObject (new MemoryStream (data, false)),
};

multipart.Add (urlencoded);

multipart.WriteTo (httpStream);
```

The trickier part is parsing responses because if you use something like HttpWebResponse's response stream does not contain the headers. Instead, it has only the multipart content and you have to get the Content-Type header from the response.ContentType string property.

Luckily I have an [answer posted to the FAQ about this](https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#how-would-i-parse-multipartform-data-from-an-http-web-request).

Hope that helps you decide and good luck whether MimeKit works out for your needs or not.

**Comment by polterguy** [comment]
Thx, that was what I thought. I'll have to do some research then, to figure out if it fits the glove. I've used it before for email, at which it works perfectly for BTW. Thx for the great work :)

**Comment by polterguy** [comment]
One thing that pussles me, which I haven't found an answer to. Does MimeKit take care of its underlaying streams automatically? For instance, in the above example, you've got a MemoryStream. Will MimeKit dispose these streams automatically ...?

I cannot see in the source that Multipart for instance implements IDisposable. What would happen to the above stream in your ContentObject? Would it leak ...?

**Comment by jstedfast** [comment]
Well, a MemoryStream doesn't actually do anything on Dispose() because all it has is a byte[] and you can't dispose a byte[]. But yes, if you were to use a FileStream or something, you should really keep a reference to it so that you can dispose of it yourself when you no longer need it.

**Comment by polterguy** [comment]
PS!
In case you're interested in seeing how I use MimeKit to create a WebService API, with support for compound objects, signed and encrypted invocations, capable of passing executable code from a client to a server, here's a little video demonstrating the concepts; https://www.youtube.com/watch?v=BRGP3dcj7cI

The code is pf.lambda/Hyperlisp, which is my own language, built upon the ability to directly modify the execution tree, instead of having to go through "code" or "syntax", but I think you'll understand it pretty easy, since it's for all practical concerns just a "tree structure wrapper" around your precious baby; MimeKit ... :)

Anyway, I'd love to have your feedback on whether or not I seem to be heading in the right direction ... :)

PS!
The video is "unlisted", and the code you see in it is not yet released ... (but in GitHub)

Thx

PS!
I am not sure, but I think you still benefit from disposing a MemoryStream, since it will set the byte[] to null (I think), which will free memory faster than if you just wait for the GC to kick in ...
But I am not 100% sure about this ... :)

**Comment by jstedfast** [comment]
Thanks for posting. Looks pretty cool.

I've got a question for you, though, which is: is there value in having PGP encryption if you already have an SSL/TLS connection? Granted, SSL doesn't sign (I don't think?), so I can see the value of PGP signatures... just not sure if I understand what value the encryption has (unless you are working in a non-SSL-enabled web service).

I guess by using PGP, your software running on either end has more control and assurances that things were encrypted and by whom (which may be the most important bit), because with SSL, the HTTP server would do the decryption and would not pass that info along to your app. Perhaps that's the value?

Also cool that you are using Mono on Linux :-)

I do most of my MimeKit development on Mono. I only make releases from Windows/Visual Studio because I include Windows Phone 8.1 builds.

**Comment by polterguy** [comment]
Thank you :)

Well, as you said, it's easy to see the value of signing a message, since then you have a guarantee of that only the server with access to the private key created that message.

SSL on the other hand, as an alternative to PGP, is basically _useless_. The reason for that, can be summed up with five words; "Man In The Middle Attack". If SSL was enough for encryption, then we wouldn't have to encrypt our emails either, one can argue, since both POP3 and SMTP supports SSL and TLS. I realize that's not entirely true though, since PGP encryption works from "end to end", and the SMTP and POP3 server(s) might not necessarily be the final client reading the email, but it anyway shows my point, to some extent. However, keep on reading, the good parts are below ... ;)

In addition, with PGP encrypted Web Services invocations, one can easily create what I like to refer to as the _"Hammer Protocol"_, which is basically the Onion routing principles for Web Services. This would allow me to create a Web Service invocation, sign and encrypt it for its final destination(s), then encrypt and sign it _again_ for an intermediate destination, serving as my "Onion router", and repeat this process 3-5 times. Then pass on my message to the destination I encrypted my message to the last time. When that destination receives my message, it will decrypt it, wait for a random amount of time, before it re-transmits the results of that decryption operation to the destination found inside the encrypted original outer message. This decrypted message is still an encrypted message though, but everything in it is different, since unwrapping the original encrypted message produced a "completely different encrypted message".

With the above scenario, I could have a Web Service invocation, using the Hammer/Onion (think Tor) routing principles to completely hide who is communicating with who, how many other server end-points the server is communicating with, and basically render all intelligence operations completely useless.

Trying to map out which parts of the networks talks with which other parts, would become literally _impossible_. All servers that are _"friends"_ with other servers, and how many _"friends"_ one server has, would be hidden behind a completely opaque cloud of PGP, Encryption, PGP Signatures, Onion routing and Triple/Quadruple/Quintuple wrapped encrypted MIME messages.

My server could send out a tiny small HTTP request to another server, which again re-transmits that message to 100 other servers, over a time period of 5 hours, where each recipient of that message re-transmits the message again to 100 more servers. This way, I am able to transmit a message to 10.000 servers, and any surveillance attempts, trying to figure out with where the message came from, will be _impossible_, and apparently my little server was just ending _one_ message, to _one_ server, and hence cannot in any ways be a suspect in regards to where this message originated.

If you like seeing in analogies, then think of the web as a Holistic Brain, where each individual neuron is just a part of a larger whole, having _oneness_ emerge as a naturalistic principle. Just like one individual neuron in your brain has no idea why or what it is firing, when it is firing, one individual server in this network, would have absolutely no idea what it is transmitting, and to whom it is transmitting it to.

The final point about encryption, is difficult to understand without understanding a couple of USPs about Hyperlisp and pf.lambda, which is a "programming language" I realized as a consequence of inadequate abilities to _"orchestrate"_ _"code"_ and pieces of logic together with _"data"_. Hyperlisp can be perceived as a "better JSON", which is a key/value/children tree node-structure, with the capability to transmit type-information for individual values. Think about it like another version of BSON (Binary JSON). But Hyperlisp is much easier to _"read"_ for humans.

Hyperlisp again, translates perfectly to _"pf.lambda"_, which is an _"execution structure"_ for computers, with some pretty unique abilities. To completely explain pf.lambda, would require much more space than I've got room for here, but to sum it up, such that you understand the main USP in regards to encryption, realize that I can create a piece of Hyperlisp "excutable piece of code", then sign it and encrypt it, for then to transmit it to another server. This other server could then store that piece of "code", and use it to invoke Web Services other places. This allows me to serialize and transmit pieces of "code" to other parties, where the party receiving my code, has absolutely no idea what the code does, and this code could include passwords to a database for that matter, for then to every time the other party wish to use this code, transmit it to a third party, and then have that third party execute that piece of code, after verifying the signature, and decrypting the message, and return the results back to the server that invoked that Web Service.

With the above scenario, I can create a "serialized callback invocation" for another server, that can be invoked any time the other party needs to invoke it, to retrieve some piece of data, either from my server, or a third party server. And this "code" could contain proprietary logic, secret keys and passwords, in addition to other parameters serialized in other parts of the MIME message. So I can have this piece of Hyperlisp, which I know if I transmit it to "weather-data.com", adding a "begin" and "end" date in another MIME entity, will return the weather results for the period I requested. Since this encrypted code, is signed by an authority that "weather-data.com" trusts, the servers at "weather-data.com" can execute this code, trusting that it won't explode the server, or send the root password to "Cosa Nostra" ...

The above scenario, is why it is so important for me that MIME is a "tree structure", as you say on your front-page here at GitHub, because with that tree-structure, I can double-encrypt, triple-encrypt, and serialize encrypted MIME messages on disc, only to allow a specific party decrypt it, when the time comes for this decryption process to happen.

To quote Alan Kay; _"Think in terms of Biology, and not in terms of Computers. Then it all makes sense"_ ... ;)

**Comment by polterguy** [comment]
BTW, I took the liberty of more nicely format my thoughts here; http://magixilluminate.com/2015/03/29/introducing-the-hammer-protocol-onion-routing-for-web-service/

... :)

**Comment by jstedfast** [comment]
Will do, and thanks for the explanation - I think I understand the value of it now :-)

**Comment by polterguy** [comment]
Howdy, here's an example of how to safely allow a Web Service to execute arbitrary code passed in from its caller; http://magixilluminate.com/2015/03/31/creating-web-services-that-executes-code-given-as-parameters-safely/

The reason why this works, is because of MimeKit, PGP and pgp-signatures, combined with that I am able to have a "white-list" of legal keywords, within my Web Service, that only allows for a "safe list" of keywords/methods to be invoked.

Sorry if this is off topic, but I just wanted you to know that there's literally an infinite amount of use-cases for using MimeKit for Web Services :)

With this approach, I am able to allow my Web Services to *safely* execute _code_ given from its consumers. This in turn, can sometimes reduce the number of round-trips between my Web Service, and its consumers, by orders of magnitudes. In addition to all the other obvious benefits.

_Semantic Web_ anyone ...? ;)

And that's (one of) the reasons why I love MimeKit :+1: )

**Comment by jstedfast** [comment]
Cool :-)
