### ISSUE TITLE
Make it easier to swap from System.Net.Mail

### ISSUE THREAD

**Issue by lonix1** [jstedfast/MimeKit#1091]
**Is your feature request related to a problem? Please describe.**
When moving from the framework' `System.Net.Mail` to `MimeKit` we had many instances of [this](https://github.com/dotnet/runtime/blob/e476b43b5cb42eb44ce23b1c7b793aa361624cf6/src/libraries/System.Net.Mail/src/System/Net/Mail/MailAddress.cs#L94):
```cs
if (MailAddress.TryCreate(address, name, out var mailAddress)) { /* ... */ }
```
The closest we found in MimeKit was [this](https://github.com/jstedfast/MimeKit/blob/af2d2616fb9dbd4e6d759a00b8767bdae447b856/MimeKit/MailboxAddress.cs#L788):
```cs
if (MailboxAddress.TryParse(address, out var mailboxAddress)) { /* ... */ }
```

**Describe the solution you'd like**
The framework docs recommend to convert to MailKit. So it would be nice if there were some overloads for the above case, e.g.
```cs
if (MailboxAddress.TryParse(address, name, out var mailboxAddress)) { /* ... */ }
```

**Describe alternatives you've considered**
It's not too hard to adapt to the MailKit way. So it's not a real issue, just one of convenience.

We've already moved on, so this feature request is just some feedback / and for future new users. Please close if out of scope.

**Comment by jstedfast** [comment]
Compatibility with System.Net.Mail isn't a high priority, honestly.

The solution I'd suggest is something like this:

```csharp
if (MailboxAddress.TryParse (address, out var mailboxAddress)) {
    mailboxAddress.Name = name;

    /* ... */
}
```

I'm going to close as WONTFIX, but I might reconsider if there ever gets to be a lot of demand.
