### ISSUE TITLE
Event and contact data from "winmail.dat" TNEF files?

### ISSUE THREAD

**Issue by jbrockerville** [jstedfast/MimeKit#1108]
I need to parse event and contact data from Outlook emails that are delivered with "winmail.dat" (TNEF) attachments. I can get message bodies and images from the TNEF with MimeKit, but I don't see any of the event or contact data. I know it's there. I can see it in Outlook, a hex editor, and [tnefparse](https://pypi.org/project/tnefparse/). Can MK get *that* data? If so, please direct me to an example. Thanks!

Edit: I think I am referring MAPI properties.

**Comment by jstedfast** [comment]
Yes, you can extract every MAPI property from the TNEF. Look at https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Tnef/TnefPart.cs#L260 to see how.

What you want may already be mapped from TNEF into a MIME property. You'll have to look at which properties get mapped to see.

**Comment by jbrockerville** [comment]
Amazing! Thank you for the quick reply!

What I want is not already mapped unfortunately. No worries. There's enough code here to get started on my own sniffer. However, taking [ConvertToMessage](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Tnef/TnefPart.cs#L755) as inspiration for good practices, I found that [GetCodePage](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Utils/CharsetUtils.cs#L292) is not publicly visible to use. Seems I have to pass in a default of `0` or roll my own code-page getter for `TnefReader`. Consider making it public or is there some alternative I missed?

**Comment by jbrockerville** [comment]
Yeah, that's what I did for now, but I thought maybe revealing your helper with it's aliases and whatnot might be a nice in the future. ;)

**Comment by jstedfast** [comment]
Actually, a way that should already work is to just use `tnefPart.ContentType.CharsetEncoding?.CodePage ?? 0`

In fact, I should probably update the COnvertToMessage code to use the same logic (it was probably written before I added the ContentType.CharsetEncoding property)

**Comment by jbrockerville** [comment]
I'm obviously doing some TNEF work. I hope keeping my questions contained to this thread is ok...

I'm not sure if this is a bug or I just didn't see how to do this properly based on examples and docs. TNEF files appear to be read on a forward-only stream pointing basis. Cool. I've just hit a multi-valued property. I assumed we'd read the value with `ReadValue` (or whatever object specific method) and then call `ReadNextValue` in a while-loop until it returned false and we break out (like reading attributes and properties). However, that's not what happens when I code that. That logic throws because both methods advance the stream and we invariably get the exception in the read call. Was that intentional? I guess you could do a for-loop using `ValueCount` instead, but just the way in which some of the other methods are used kinda strongly imply the while-loop usage. Basically, I had to stumble along sample data and fail at this bit and dig into the source to use it the way you intended. Not the end of the world certainly. This library is amazing, but maybe add a full TNEF reading example or some simple documentation on how to deal with, say, a multi-valued property and an object property?

**Comment by jbrockerville** [comment]
Hold up. A for-loop doesn't work either.

Referencing [ReadValue](https://github.com/jstedfast/MimeKit/blob/9c2659fec48be15ec790fd2b5b528b198d6f084f/MimeKit/Tnef/TnefPropertyReader.cs#L904)...
```cs
			if (valueIndex >= valueCount || reader.StreamOffset > RawValueStreamOffset)
				throw new InvalidOperationException ();
```

Using a while-loop with `ReadNextValue` *and* `ReadValue` causes the exception via `valueIndex >= valueCount`. Using a for-loop with only `ReadValue` causes the exceptions via `reader.StreamOffset > RawValueStreamOffset`.

How do we read a multi-value property or bug?

**Comment by jbrockerville** [comment]
I hacked around it by decrementing `valueIndex` via reflection after calling `ReadNextValue` to advance the stream.

**Comment by jstedfast** [comment]
I'll be honest, the TNEF code isn't very robust because I have a complete lack of test cases (no one is ever willing to share files they are parsing and the number of files available in the public domain is all I have and that was like 5).

It sounds to me like you are probably hitting a bug.

**Comment by jstedfast** [comment]
FWIW, I tried to model MimeKit's TNEF APIs after Microsoft's Exchange API:

ReadNextValue: https://learn.microsoft.com/en-us/previous-versions/office/exchange-server-api/aa565832(v=exchg.150)
ReadValue: https://learn.microsoft.com/en-us/previous-versions/office/exchange-server-api/aa580577(v=exchg.150)

Based on their docs, I would *assume* that the proper way to get the values would be something like this:

```csharp
if (propertyReader.IsMultiValuedProperty) {
    for (int i = 0; i < propertyReader.ValueCount; i++)
        propertyReader.ReadValue();
}
```

**Comment by jstedfast** [comment]
I take back my previous assumption now that I've been looking at ReadNextProperty().

**Comment by jstedfast** [comment]
I've been discovering that a ton of my assumptions about how the Microsoft.Exchange.Data.ContentTypes.Tnef API worked was wrong.

Anyway, as of a month ago, I now work for Microsoft on their Exchange MIME parser and my team also maintains the TNEF API.

This will be en eye opening experience.

**Comment by jbrockerville** [comment]
Congratulations on the new gig! Hopefully some of that eye opening experience will make its way into MimeKit. Nevertheless, enough of it was right for me to parse everything out of all the tag, lid, and named properties I found.
