### ISSUE TITLE
MimePart, ContentType and the Header property

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#114]
Sorry to be "bombarding" you with issues, but I figure you're probably happy to get feedback :)

One peculiarity about the Headers property on MimePart, is that you can set any header you wish through its "Add" method, _except_ "Content-Type". If i try to set Content-Type through the Headers property, then I end up getting _two_ Content-Type headers.

This makes it so that I must parse the headers first, store them, have a reference to my Content-Type header, for then to instantiate my MimePart object with the stored Content-Type, and then set the other headers.

The above works perfectly fine of course, but it makes it such that my code, while consuming MimeKit becomes "less beautiful", more complex, and less readable.

The way I'd expect it to work, is such that if you add a header through Headers.Add, then if it is a "Content-Type" field, it would overwrite the existing "Content-Type", which would first of all probably be more intuitive, in addition to allowing for my code while consuming MimeKit become much more readable ...

To illustrate with some code;

```csharp
// creating root Multipart to hold all [args] and [files]
Multipart root = new Multipart (ContentType.Parse (request.ContentType).MediaSubtype);

// looping through each [args], building the correct MimePart according to type
foreach (var idxArg in XUtil.Iterate<Node> (node ["args"], context)) {

    // we have to parse the headers first to find "Content-Type" before we instantiate MimePart
    HeaderList headers = new HeaderList ();

    // defaulting "Content-Type" to "text/plain"
    ContentType contentType = new ContentType ("text", "plain");
    foreach (var idxHeader in idxArg.Children) {
        if (idxHeader.Name == "Content-Type")
            contentType = ContentType.Parse (XUtil.Single<string> (idxHeader.Value, idxHeader, context));
        else
            headers.Add (idxHeader.Name, XUtil.Single<string> (idxHeader.Value, idxHeader, context));
    }

    // creating MimePart and adding headers we previously created
    MimePart part = new MimePart (contentType);
    foreach (var idxHeader in headers) {
        part.Headers.Add (idxHeader);
    }

    // creating our ContentObject for our MimePart and adding MimePart to root Multipart
    MemoryStream stream = new MemoryStream (
        idxArg.Value is byte[] ? 
            (byte[])idxArg.Value : 
            Encoding.UTF8.GetBytes (XUtil.Single<string> (idxArg.Value, idxArg, context)));
    part.ContentObject = new ContentObject (stream);
    root.Add (part);
}

// writing multipart to request stream, for then to return response
root.WriteTo (request.GetRequestStream ());
return (HttpWebResponse)request.GetResponse ();
```

If I could set "Content-Type" through the Headers collection, then I'd save roughly 5 lines of code, since I then could create my MimePart first, for _then_ to loop through the headers, ending up in making my code more readable, in addition to that it "feels" like a bug, that you cannot set "Content-Type" as a "Header" ...

Thoughts ...?

Not a "biggie" per se, but I thought you'd want to know :)

PS!
The "Node" and XUtil.Iterate + Single can be thought of like "BSON DOM" (although it's not, but for clarity to understand what the above does)

**Comment by jstedfast** [comment]
I think you end up getting 2 copies of the Content-Type header because `HeaderList.Add()` allows adding multiple copies of the same header (needed for things like Received, To, Cc, etc).

If you use `part.Headers.Replace (idxHeader);` instead, it should work as expected.

Replace() works as an Add() in cases where the header does not yet exist.

**Comment by polterguy** [comment]
Ahh, great. Thx :)
