### ISSUE TITLE
Add more immutability-friendly APIs

### ISSUE THREAD

**Issue by knocte** [jstedfast/MimeKit#116]
When using MimeKit & MailKit from F#, some things look weird, because of how F# programs you to think in immutability all around.

For example, I would prefer that MimeMessage ctor not be parameterless, and accept subject, body, and arrays for From & To parameters (to avoid using the setters of properties).

This way an F# developer could use this API without the need of using the *evil* assignment operator that we're now allergic to :-)

Would you be willing to add such a constructor? If the answer is "Yes, patches welcome", I'll happily do it when I've some time in my hands.

Thanks

**Comment by jstedfast** [comment]
Someone actually did this for classes like MimePart, TextPart, etc.

I'd be willing to have this type of API available for MimeMessage as well.

Give me a proposal and/or PR and we can work out the details.

**Comment by knocte** [comment]
Thanks, will do.
