### ISSUE TITLE
Not supported plain text format=flowed

### ISSUE THREAD

**Issue by msa48** [jstedfast/MimeKit#125]
The mail text/plain can be in flowed format described in rfc3676 https://tools.ietf.org/html/rfc3676

flowed sample:

```
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit

this is a very very very very 
long line.
```

in reciever client is could be
```
this is a very very very very long line.
```

Note the **space** at the end of the first line. This means that the next line is a continuation of the current paragraph.

not flowed sample:
```
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

this is a very very very very
long line.
```
in reciever client is could be
```
this is a very very very very
long line.
```
the format specifier and **space** at the end of line is out

**Comment by jstedfast** [comment]
Yea, I know about format=flowed.

Is this a feature request?

**Comment by msa48** [comment]
Yes, let it be feature request.

**Comment by jstedfast** [comment]
I've started working on this as part of a large TextConverter feature patch to convert between various text formats.

**Comment by jstedfast** [comment]
If you are interested, you could try the `text-converter` branch: https://github.com/jstedfast/MimeKit/tree/text-converter

I would probably recommend downloading the zip instead of doing a git checkout since I've been doing force pushes occasionally to sync back up with the master branch.

**Comment by msa48** [comment]
FlowedToText is work

FlowedToHtml crashed
System.ArgumentOutOfRangeException was unhandled by user code
  HResult=-2146233086
  Message=Заданный аргумент находится вне диапазона допустимых значений.
Имя параметра: count
  Source=MimeKitLite
  ParamName=count
  StackTrace:
       в MimeKit.Text.HtmlWriter.ValidateArguments(Char[] buffer, Int32 index, Int32 count)
       в MimeKit.Text.HtmlWriter.WriteText(Char[] buffer, Int32 index, Int32 count)
       в MimeKit.Text.FlowedToHtml.WriteText(HtmlWriter htmlWriter, String text)
       в MimeKit.Text.FlowedToHtml.WriteParagraph(HtmlWriter htmlWriter, IList`1 stack, Int32& currentQuoteDepth, StringBuilder para, Int32 quoteDepth)
       в MimeKit.Text.FlowedToHtml.Convert(TextReader reader, TextWriter writer)
       в MimeKit.Text.TextConverter.Convert(String text)

**Comment by jstedfast** [comment]
Can you give me a test case? This doesn't happen in the unit tests...

**Comment by jstedfast** [comment]
Never mind, I think I figured it out and fixed it. Could you let me know if the commit fixes it?

**Comment by msa48** [comment]
Yes. Now it is not crashed.
But I notice one issue and one thign that is not good (for my opinion).
I hope the Russian text blocks are not a problem. All the matter in space)

First: I have large text in format=flowed in content-type. But some section not flowed. After FlowedToText ot FlowedToHtml it lost one space in line start. Examlpe:
TextPart.Text (raw)
```
*/Преимущества работы с нами
/*

  * Лояльная стоимость. Вы публикуете статью в полноценных европейских
    изданиях практически по цене публикации в изданиях своей страны.
  * Отправка заказными бандеролями в любой населенный пункт России,
    Украины, Казахстана, других стран СНГ, Европы - в любую точку мира
```
After convert
```
*/Преимущества работы с нами
/*

 * Лояльная стоимость. Вы публикуете статью в полноценных европейских
   изданиях практически по цене публикации в изданиях своей страны.
 * Отправка заказными бандеролями в любой населенный пункт России,
   Украины, Казахстана, других стран СНГ, Европы - в любую точку мира
```


Second for FlowedToHtml:
in one side It is good that the `\r\n`prefix in start and postfix in end is delete, but in secod side it is not good, that between section its completely removed.

The text begin not well structed and it is begin very hard to read

**Comment by jstedfast** [comment]
According to the rfc, this is the correct behavior:

```
If the first character of a line is a space, the line has been
space-stuffed (see Section 4.4).  Logically, this leading space is
deleted before examining the line further (that is, before checking
for flowed).
```

**Comment by jstedfast** [comment]
> Second for FlowedToHtml:
> in one side It is good that the \r\nprefix in start and postfix in end is delete, but in secod side it is not good, that between section its completely removed.
> 
> The text begin not well structed and it is begin very hard to read

I have no idea what you are trying to say here.

**Comment by msa48** [comment]
> According to the rfc, this is the correct behavior:

I re-read rfc, and yes, you are right.

> I have no idea what you are trying to say here.

I will attach screenshots to illustrate it

original-html
![original-html](https://cloud.githubusercontent.com/assets/8330846/7540235/88cbe958-f5b5-11e4-820c-67b8c664e8da.png)
flowed-to-text (look good)
![flowed-to-text](https://cloud.githubusercontent.com/assets/8330846/7540237/8df2a9bc-f5b5-11e4-93e9-7a331c818c8b.png)
flowed-to-html (looks like a big monolithic text)
![flowed-to-html](https://cloud.githubusercontent.com/assets/8330846/7540240/9212bcd0-f5b5-11e4-8712-897f8b1f0051.png)

**Comment by jstedfast** [comment]
Ah, thanks. I've modified FlowedToHtml to output &lt;br/&gt;'s for blank lines now, so this should look better if you update and try again.

**Comment by msa48** [comment]
TextToHtml.cs line 220 htmlWriter.WriteText (content, startIndex, match.StartIndex - startIndex);

**Comment by jstedfast** [comment]
Fixed.

**Comment by msa48** [comment]
Nothing else suspicious, I do not see.
Great work!

**Comment by jstedfast** [comment]
this has been merged to master now
