### ISSUE TITLE
api to modify email data?

### ISSUE THREAD

**Issue by deostroll** [jstedfast/MimeKit#128]
what api is available that allows me to modify email data?

**Comment by jstedfast** [comment]
Awhole lot of APIs allow you to change email data. What data do you want to change, specifically?

**Comment by deostroll** [comment]
Say I have a text whose Content-Disposition is inline and it is base 64 encoded. This is part of an email message which is a multipart mime.

```csharp
MimeMessage email = MimeMessage.Load(stream);
Email = email;
MimePart calendarPart = null;
foreach (var item in email.BodyParts)
{
	if (item.ContentType.MimeType == "text/calendar")
	{
		calendarPart = item;
		break;
	}
}
```

I examine the ```calendarPart``` object by writing that to a stream first...

```c#
MemoryStream ms = new MemoryStream();
calendarPart.ContentObject.WriteTo(ms);
bool isValid = ValidateCalendar(ms);
```
Somehow the ```WriteTo()``` gives me decoded data to work with. If ```isValid``` turns out to be false for some reason...I have to fix that...insert a few lines into that ```MimePart``` so to speak...

But how to do that?

**Comment by jstedfast** [comment]
Since calendarPart is an instance of TextPart, you can use the Text property to get and/or set the Text of the part.

You could also create your own `ContentObject` and set that on the calendarPart.
