### ISSUE TITLE
Getting actual sender from a forwarded mail

### ISSUE THREAD

**Issue by nlvraghavendra** [jstedfast/MimeKit#132]
Hi Jeff,

Thanks for porting the code to .NET 2.0. I had couple of issues in that build (Linq references, parameterless constructor defined in the new CancellationToken.cs)  but I got over it now.

So my real requirement is - if an mail is forwarded by a user, I would like to parse that email and find the actual sender and the actual date when the mail was sent to the previous user. If possible, I would like to get all the senders/receivers information in the entire mail chain.

Is it possible?

**Comment by jstedfast** [comment]
I'm not 100% clear on what you are asking. It might help if you provided a sample forwarded message and then told me the info you wanted to get in an example.

**Comment by nlvraghavendra** [comment]
Hi Jeff,

Please consider the below email - 

*******************************************************************************************************************************

Hi John,

There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. 

Thanks & Regards
IT Department
Peter

From: John Paul 
Sent: Tuesday, April 26, 2015 5:32 PM
To: Peter Moore
Cc: Bruce Willis
Subject: RE: Discussion on samples

Hi Peter,

It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Regards
John


From: Samuel Jackson 
Sent: Tuesday, April 25, 2015 11:29 AM
To: John Paul
Cc: Robert Brown
Subject: Discussion on samples

Team,

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Thanks
Samuel

*******************************************************************************************************************************

So the email chain is like this - 

Samuel to John on April 25, 2015 11:29 AM
John fowarded it to Peter on  April 26, 2015 5:32 PM
Peter replied to John today

If I've the email sent by Peter to John today, can I parse the email and get the chain so that I can get the previous user who sent the mail in the chain and also the date on which he sent it?

**Comment by jstedfast** [comment]
You'd have to write your own parser to get that information. That's out of the scope of MimeKit which does not parse the *content* of messages, but rather just parses the MIME structure and headers.

Also, FWIW, the format of that message is not very standard so unless you only have to parse messages from only 1 particular mail client program, it'll probably be impossible to implement.

**Comment by nlvraghavendra** [comment]
That's true. I just went through the MIME structure. So there are no attributes that preserves this information. Thanks for your response.

**Comment by jstedfast** [comment]
If you have all of the original messages, you can use the `References` header to figure out the chain of messages and then use those message-ids to locate the original messages in that chain and then parse them for the list of addresses.

**Comment by jstedfast** [comment]
BTW, the build errors should be fixed now. It built for .NET 2.0 just fine on Mono on Mac, but I guess that's because Mono doesn't actually support .NET 2.0 anymore, it just aliases it to 3.5 or something.

**Comment by nlvraghavendra** [comment]
Cool. Also, I write a simple body parser specifically targeting outlook
clients and our exact use case. Thanks for your suggestions.
