### ISSUE TITLE
The HTMLBody is not diplaying all of the inline attachments

### ISSUE THREAD

**Issue by LeeBear35** [jstedfast/MimeKit#133]
I have a number of emails where the HTMLBody should contain an image, but it does not. I have an email sample that I can supply. I will check into the code and see if I can find the cause as well.

**Comment by jstedfast** [comment]
The MimeMessage.HtmlBody HTML text does not actually include embedded images, it's just the HTML text.

Most likely, the message does not use image tags with http:// URLs, but rather uses cid: URLs that refer to other MIME parts that you will need to feed to your HTML renderer yourself.

Take a look at the MessageReader sample for an idea how to do this.

**Comment by LeeBear35** [comment]
Jeffery,
Thank you for the information and pointing me to the MessageReader. I personally wanted to avoid creating files, so I used the following code.

      StringBuilder rValue = new StringBuilder();
      rValue.Append(mimemessage.HtmlBody);
      foreach (MimeKit.MimePart part in this.m_msg.BodyParts)
      {
        if (!part.IsAttachment && part.ContentId != null)
        {
          using (System.IO.Stream stream = new System.IO.MemoryStream())
          {
            part.ContentObject.WriteTo(stream);
            stream.Flush();
            stream.Seek(0, System.IO.SeekOrigin.Begin);
            using (System.IO.StreamReader sr = new System.IO.StreamReader(stream))
            {
              String cid = String.Format("src=\"cid:{0}", part.ContentId);
              String data = String.Format("src=\"data:{0}/{1};{2},{3}", part.ContentType.MediaType, part.ContentType.MediaSubtype, part.ContentTransferEncoding, sr.ReadToEnd());
              rValue.Replace(cid, data);
            }
          }
        }
      }

Thank you for good solid code!


Leland Carpenter ♦ Sr. Software Engineer ♦ PRGX USA, Inc.
4904 Hickory Way ♦ Johnsburg, IL 60051-8967
O: 815.307.7634 ♦ Lee.Carpenter@prgx.com<mailto:Lee.Carpenter@prgx.com>
[cid:image001.jpg@01D08349.7495F3E0]

**Comment by bryanvam** [comment]
is it possible to update this code? ContentTransferEncoding doesnt seem to exist anymore

**Comment by jstedfast** [comment]
@bryanvam `ContentTransferEncoding` still exists on `MimePart`. If you are using `var` in the foreach statement, though, you will get back `MimeEntity` which is a base class of `MimePart` because BodyParts is `IEnumerable<MimeEntity>`.

**Comment by bryanvam** [comment]
that was it. many thanks
