### ISSUE TITLE
Extracting embedded images

### ISSUE THREAD

**Issue by nlvraghavendra** [jstedfast/MimeKit#134]
I'm trying to extract the embedded images and save it (in SharePoint library). 

I tried this code - 

```csharp
ContentObject embObject = embeddedObjects[key];
Stream objectStream = new MemoryStream();
embObject.DecodeTo(objectStream);
byte[] attachmentArray = new byte[objectStream.Length];
objectStream.Read(attachmentArray, 0, (int)objectStream.Length);
```
and also this code - 

```csharp
ContentObject embObject = embeddedObjects[key];
Stream objectStream = new MemoryStream();
embObject.DecodeTo(objectStream);
byte[] attachmentArray = new byte[objectStream.Length];
objectStream.Read(attachmentArray, 0, (int)objectStream.Length);
```

But it seems the images are broken/invalid after I save it. Let me know if this is the correct way to do it. If yes, I need to troubleshoot the saving part.

**Comment by nlvraghavendra** [comment]
Okay. I've fixed the issue. I believe the `objectStream.Read()` is the culprit here and it is not retaining the encoding. I passed the stream as-is and the image got saved correctly.

**Comment by jstedfast** [comment]
The problem is that after you decode the embObject into objectStream, you are forgetting to seek back to the beginning of objectStream before you read from it.

The code should look like this:

```csharp
ContentObject embObject = embeddedObjects[key];
Stream objectStream = new MemoryStream();
embObject.DecodeTo(objectStream);
objectStream.Position = 0;
byte[] attachmentArray = new byte[objectStream.Length];
objectStream.Read(attachmentArray, 0, (int)objectStream.Length);
```

**Comment by nlvraghavendra** [comment]
But if that is the case, I should not be able to read anything from the stream since the position will be at the end. I was able to read the stream and fill the byte array. When I checked the actual size of the image and the byte array size it was mismatching too. So I thought it could be an encoding issue. Thanks for your response anyway.

**Comment by jstedfast** [comment]
There's no way your previous code was reading *anything* into the byte array because `embObject.DecodeTo(Stream)` does not rewind the stream.

**Comment by mike-nelson** [comment]
Hi guys, I have code that extracts inline images successfully. I am converting them to base64 and it is working great. 

		private string PopulateInlineImages(MimeMessage newMessage, string bodyHtml) {
			// encode as base64 for easier downloading/storage 
			if (bodyHtml != null) {
				foreach (MimePart att in newMessage.BodyParts) {
					if (att.ContentId != null && att.ContentObject != null && att.ContentType.MediaType == "image" && (bodyHtml.IndexOf("cid:" + att.ContentId) > -1)) {
						byte[] b;
						using (var mem = new MemoryStream()) {
							att.ContentObject.DecodeTo(mem);
							b = mem.ToArray();
						}
						string imageBase64 = "data:" + att.ContentType.MimeType + ";base64," + System.Convert.ToBase64String(b);
						bodyHtml = bodyHtml.Replace("cid:" + att.ContentId, imageBase64);
					}
				}
			}
			return bodyHtml;
		}


(This could be a helper method you would consider including in mailkit as it is a useful feature and did take me a while to crack it. I am not sure if that the conversion to base64 is necessary - now that I see how you did it Raghavendra, I realise I could possibly use the source charset as a data URL - the conversion to base64 could be wasting cpu cycles/memory - what do you think Jeffrey?)

**Comment by jstedfast** [comment]
You realistically need to convert to base64 unless you can be sure that it does not contain any bytes outside of the allowable set of characters allowed in an HTML attribute value.

**Comment by mike-nelson** [comment]
Cool. Thanks!

Mike Nelson // CEO // beweb
p. 09 3077042 // m. 027 4403757

**Comment by cyroul82** [comment]
@mike-nelson 
 
A big thanks for your method, it saved me a lot of time... agree with you, it would be very great to include in mailkit as it is a useful feature. @jstedfast (Thank you for your great work by the way )

**Comment by mike-nelson** [comment]
Yes extracting embedded images is an essential feature. 
@Jeffrey- just paste my code in!

Cheers
Mike

Mike Nelson // CEO (and Developer) // Beweb // +64 9 3077042 // +64 27 4403757
Developers of Speaking Email for iOS or Android - Finalist in NZ Hi-Tech Awards 2017

**Comment by gyself** [comment]
@mike-nelson , mailclients like outlook & gmail don't decode base64 images.
How would you proceed with that?

Rgds
Frederik

**Comment by mike-nelson** [comment]
@gyself - I didn't know that but I see this as useful for display of an email in a browser. It will work no matter what mail server the email was sent from. It may not be useful for composing an HTML email to be sent however.

**Comment by gyself** [comment]
@jstedfast, do you have a sollution to this?
For example, I retrieve an email (with embedded image) in my asp.net application using mailkit and store it in mydatabase. Afterwards if I forward the email (from my web application) to a gmail address, what should be done to show the embedded images?

**Comment by jstedfast** [comment]
Why not store the entire message so you can forward the complete message rather than trying to piece things back together?

I don't know enough about what you are doing to make any other suggestions.

**Comment by gyself** [comment]
That's what I am doing @jstedfast.
Problem is that in gmail (and also outlook) the embedded image is gone.:
![image](https://user-images.githubusercontent.com/20824258/43218843-e62aef12-9045-11e8-87a8-0d3b85897bdf.png)

while on my iphone I can perfectly see the embedded image:
![image](https://user-images.githubusercontent.com/20824258/43218822-d0a2e9b0-9045-11e8-80f6-72064aadfbc2.png)

**Comment by jstedfast** [comment]
Then that seems like a bug in GMail, no?

**Comment by vesnaveen** [comment]
Its not working in gmail
