### ISSUE TITLE
headers with ISO-2022-JP charset using quoted-printable encoding (but i believe it should be base64)

### ISSUE THREAD

**Issue by amaclaren** [jstedfast/MimeKit#139]
When the IS-2022-JP charset is specified for the subject header, it gets encoded using quoted-printable.  I think the spec for it says it should be encoded using base64 - https://tools.ietf.org/html/rfc1468  under 'MIME Considerations'

i'm pretty new to constructing MIME, but we are coming from a system using the C ATL CMimeMessage class, and extending it to use base64 encoding in this specific case for the subject.

**Comment by jstedfast** [comment]
MimeKit decides which encoding to use based on efficiency. Either encoding is fine for any charset data. I don't know why they recommend base64 since that just bloats the size of the headers unnecessarily.

Do you have some sample code that illustrates this "problem"?

**Comment by amaclaren** [comment]
I didn't see any actual issues - just the inconsistency with the spec, and I wasn't sure if there would be any email clients or anything that would have issues.
