### ISSUE TITLE
Header Only Parsing - HeaderList.Load

### ISSUE THREAD

**Issue by nitinag** [jstedfast/MimeKit#142]
We're using HeaderList.Load to pass in a string (via memory stream bytes) of only headers (not the full message).

Failed input cases:
"Header-1: Test";
"Header-2: Test\r\n";
"Header-1: Test\r\nHeader-2: Test\r\n";
"Header-1: Test\r\nHeader-2: Test\r\n";

Success input cases:
"Header-1: Test\r\nHeader-2: Test\r\n";
"Header-1: Test\r\n\r\n";

Including two CRLFs after input to emulate a full message is what we do right now and it always works, but thought I'd point this test case out and see if it made sense to support header only input with any CRLF sequence, including none at the end.

Side note: Exposing Header.RawField and Header.RawValue was very useful for us.

Thanks for making MimeKit. Looking forward to taking advantage of increased performance and modern/complete interface it offers as we begin to use it more.

**Comment by jstedfast** [comment]
This should work as expected now.
