### ISSUE TITLE
S/MIME encrypt and decrypt with PEM formatted certs?

### ISSUE THREAD

**Issue by Hobby-Student** [jstedfast/MimeKit#145]
Hey,

first of all: thanks for this very useful library! Awesome.

Since a few days, I try to use .NET with S/MIME encryption. Today I tried MimeKit and it's so damn easy :)

I can encrypt an decrypt with a ".pfx" (PKCS #12) certificate. To encrypt and decrypt, I use the peace of code, found in issue #38 and TemporarySecureMimeContext(). WORKS

But in my special case I need to encrypt with some public keys in PEM format (-----BEGIN PUBLIC KEY----- ......... -----END PUBLIC KEY-----) and decrypt with the private key (-----BEGIN PRIVATE KEY----- ....... -----END PRIVATE KEY-----).
Think of: Encrypt for 2 recipients and the sender with public key, then try to decrypt with senders private key.

FOR TEST PURPOSES, THE PRIVATE KEY IS UNENCRYPTED!

This is what I'v done so far:
```cs
System.Security.Cryptography.X509Certificates.X509Certificate2 priv2 = new System.Security.Cryptography.X509Certificates.X509Certificate2();
priv2.Import(@"path\to\PEM-public-key");
priv2.PrivateKey = rsa; // <- RSACryptoServiceProvider from PEM private key

var keyPair = Org.BouncyCastle.Security.DotNetUtilities.GetKeyPair(priv2.PrivateKey);
var certificate = Org.BouncyCastle.Security.DotNetUtilities.FromX509Certificate(priv2);
var privateKey = keyPair.Private;
```

I tried to do
```cs
X509CertificateRecord rc = new X509CertificateRecord(certificate, privateKey);
```

In debug mode, I see, that public key and private key are there and merged, but not as (BouncyCastle) X509Certificate.
So the question is:

How do I get this to import into the SecureMimeContext and decrypt without ".pfx" (PKCS #12) file?
How do I encrypt with just the public key and not a ".pfx" (PKCS #12) file?

Thanks in advance

**Comment by jstedfast** [comment]
`TemporarySecureMimeContext` doesn't use `X509CertificateRecord`, so I'm not sure what you were trying to do with it.

An X509CertificateRecord is an object that is simply used for reading and writing certificate records to a database which you aren't doing.

You could just copy the `TemporarySecureMimeContext` and add your own Import() method to load the certificate and keys from a PEM file:

```csharp
public void ImportPemCertificate (X509Certificate certificate, AsymmetricKeyParameter privateKey)
{
    certificates.Add (certificate);
    keys[certificate] = privateKey;
}
```

And you could create your context like this:

```csharp
private SecureMimeContext CreateSecureMimeContext ()
{
    X509Certificate2 priv2 = new X509Certificate2();
    priv2.Import(@"path\to\PEM-public-key");
    priv2.PrivateKey = rsa; // <- RSACryptoServiceProvider from PEM private key

    var keyPair = Org.BouncyCastle.Security.DotNetUtilities.GetKeyPair(priv2.PrivateKey);
    var certificate = Org.BouncyCastle.Security.DotNetUtilities.FromX509Certificate(priv2);
    var privateKey = keyPair.Private;

    var secureMimeContext = new MyTemporarySecureMimeContext ();    
    secureMimeContext.Import (certificate, privateKey);

    return secureMimeContext;
}
```

**Comment by Hobby-Student** [comment]
@jstedfast you pointed me into the right direction! Thanks for your amazingly fast answer! Have a look at my solution. Perhaps you want to include it in MimeKit (I did it quick'n'dirty just for testing purpose. Import(string filename, string filename) and then parse inside could be a better solution)

For people having the same needs:

Extended with
```cs
public void Import (X509Certificate certificate, AsymmetricKeyParameter key)
{
	if (certificate == null)
		throw new ArgumentNullException("certificate");

	if (key == null)
		throw new ArgumentNullException("key");

	certificates.Add(certificate);
	keys.Add(certificate, key);
}
```

creating TemporarySecureMimeContext (encrypt)
```cs
private SecureMimeContext CreateSecureMimeContext_Encrypt(string certificateFilename)
{
	System.Security.Cryptography.X509Certificates.X509Certificate2 pub1 = new System.Security.Cryptography.X509Certificates.X509Certificate2();
	pub1.Import(certificateFilename);

	Org.BouncyCastle.X509.X509Certificate certificate = Org.BouncyCastle.Security.DotNetUtilities.FromX509Certificate(pub1);

	var secureMimeContext = new MyTemporarySecureMimeContext();
	secureMimeContext.Import(certificate);

	return secureMimeContext;
}
```

creating TemporarySecureMimeContext (decrypt)
```cs
private SecureMimeContext CreateSecureMimeContext_Decrypt(string certificateFilename, string keyFilename)
{
	StreamReader key_read = File.OpenText(keyFilename);
	String key_string = key_read.ReadToEnd().Trim();

	Org.BouncyCastle.OpenSsl.PemReader pemO = new Org.BouncyCastle.OpenSsl.PemReader(new StringReader(key_string));

	Org.BouncyCastle.Crypto.Parameters.RsaPrivateCrtKeyParameters keyParams = (Org.BouncyCastle.Crypto.Parameters.RsaPrivateCrtKeyParameters)pemO.ReadObject();

	RSACryptoServiceProvider rsa = new RSACryptoServiceProvider();
	RSAParameters rsa_params = ToRSAParameters(keyParams); // ToRSAParameters(RsaPrivateCrtKeyParameters privKey)  found on stackoverflow
	rsa.ImportParameters(rsa_params);

	System.Security.Cryptography.X509Certificates.X509Certificate2 priv2 = new System.Security.Cryptography.X509Certificates.X509Certificate2();
	priv2.Import(certificateFilename);
	priv2.PrivateKey = rsa;

	Org.BouncyCastle.Crypto.AsymmetricCipherKeyPair keyPair = Org.BouncyCastle.Security.DotNetUtilities.GetKeyPair(priv2.PrivateKey);
	Org.BouncyCastle.X509.X509Certificate certificate = Org.BouncyCastle.Security.DotNetUtilities.FromX509Certificate(priv2);
	Org.BouncyCastle.Crypto.AsymmetricKeyParameter privateKey = keyPair.Private;

	var secureMimeContext = new MyTemporarySecureMimeContext();
	secureMimeContext.Import(certificate, privateKey);

	return secureMimeContext;
}
```

Now my problem is solved. S/MIME encrypting with public key and decrypt with private key
