### ISSUE TITLE
Conversion for X509Certificate2 [Question]

### ISSUE THREAD

**Issue by Nekeniehl** [jstedfast/MimeKit#149]
I found somewhere in StackOverflow a method to convert from X509Certificate2 to (BountyCastle)X509Certificate, which is necessary for the CmsRecipient parameter in  ApplicationPkcs7Mime.SignAndEncrypt method from, but if I understand how encryption works, the private key is never available so, the TryGetCertificateAndPrivateKey would never work (actually tested) Is there another method or way to make that conversion?

The thread on SO (http://stackoverflow.com/questions/30983883/sign-and-encrypt-on-mimekit)

**Comment by jstedfast** [comment]
You don't need a private key for CmsRecipient, you only need it for signing.

**Comment by Nekeniehl** [comment]
That's what I understood, but for the calling of ApplicationPkcs7Mime.SignAndEncrypt(ctx, signer, colle, mimeMessage.Body); where the param colle is a CmsRecipientCollection, I have to add a CmsRecipient which it has the parameter BountyCastle X509Certificatem that is the reason I need that conversion from X509Certificate2 to the BountyCastle one.

**Comment by jstedfast** [comment]
You can use BouncyCastle's DotNetUtils.FromCertificate2() or whatever the method name is - that's all you need.

**Comment by Nekeniehl** [comment]
Ok, understood, I thought it was MimeKit related and not Bouncy, thanks for your help.

**Comment by jstedfast** [comment]
I've added CmsRecipient .ctor's that take X509Certificate2 instead of Org.BouncyCastle.X509.X509Certifcate, but I probably won't make a new release for a few weeks.

**Comment by Nekeniehl** [comment]
Great, thanks for the support!

**Comment by jstedfast** [comment]
no prob, I'm always trying to make it easier to use.
