### ISSUE TITLE
eml include msg file .

### ISSUE THREAD

**Issue by angleafro** [jstedfast/MimeKit#152]
Hi jeff, I alway thanks for your effort.

Now I have a strange Problem.
I don't think this an error, but I don't know how to say the issue.

I have an email that i opened with Outlook 2010 than every thing is Ok but have an MSG(Outlook format) file. 

When I try to parse the email With MimeKit then the msg file is gone.

Here is my tested code.

private void btnDoParse_Click(object sender, EventArgs e)
        {
            string strFilePath = string.Empty;
            string outDirPath = string.Empty;
            try
            {
                strFilePath = this.txtFilePath.Text;
                outDirPath = this.txtOutputDirPath.Text;
                MimeMessage mime = MimeMessage.Load(strFilePath);
                this.lstResult.Items.Clear();
                InternetAddressList lstFrom = mime.From;
                InternetAddressList lstTo = mime.To;
                //Subject
                string strSubject = mime.Subject;

                this.lstResult.Items.Add(String.Format("{0}\t{1}", "Subject", strSubject));
                //From
                foreach (InternetAddress item in lstFrom)
                {
                    this.lstResult.Items.Add(String.Format("{0}\t{1}","From", item.ToString()));
                }
                //To
                foreach (InternetAddress item in lstTo)
                {
                    this.lstResult.Items.Add(String.Format("{0}\t{1}", "To", item.ToString()));
                }
                //Boy
                string strTextBody = mime.TextBody;
                this.lstResult.Items.Add(String.Format("{0}\t{1}", "TextBody", strTextBody));
                string strHtmlBody = mime.HtmlBody;
                this.lstResult.Items.Add(String.Format("{0}\t{1}", "HtmlBody", strHtmlBody));

                foreach (var attachment in mime.Attachments.OfType<MimePart>())
                {
                    string strFileName = attachment.FileName;

                    RmInvalidChars(ref strFileName);
                    this.lstResult.Items.Add(String.Format("{0}\t{1}", "attachment", strFileName));
                    string filePath = String.Format("{0}\\{1}", outDirPath, strFileName);
                    using (var stream = File.Create(filePath))
                    {
                        attachment.ContentObject.DecodeTo(stream);
                        stream.Close();
                    }
                }

                //foreach (MimePart attachment in mime.Attachments)
                //{
                //    using (var cancel = new System.Threading.CancellationTokenSource())
                //    {
                //        this.lstResult.Items.Add(String.Format("{0}\t{1}", "attachment", attachment.FileName));
                //        string filePath = String.Format("{0}\\{1}",outDirPath,attachment.FileName);
                //        using (var stream = File.Create(filePath))
                //        {
                //            attachment.ContentObject.DecodeTo(stream, cancel.Token);
                //            stream.Close();
                //        }
                //    }
                //}
            }
            catch (Exception ex)
            {
                //Utilities.gLogWriter.UpdateLog(String.Format("Error => Source : {0} , Message : {1} ).", ex.TargetSite, ex.Message));
                System.Diagnostics.Debug.Print(String.Format("File({2}) Error => Source : {0} , M1essage : {1} ).", ex.TargetSite, ex.Message, strFilePath));
                MessageBox.Show(this, ex.Message, this.Name, MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

And I already Sent the email to you.

Thanks.

**Comment by jstedfast** [comment]
What's the problem? It sounds like you're saying that the msg file gets deleted after you parse it? If that's the case, I don't know what it could be because MimeKit does not have any code to delete files.
