### ISSUE TITLE
Strange ComputeContentMd5 function

### ISSUE THREAD

**Issue by msa48** [jstedfast/MimeKit#153]
Can you help with this function? 

if a have base64 coded file stream in MimePart content. 
What is result md5 for?
1. for encoded part content
2. for decoded file stream content
3. something else

and if is rigth answer is 2, then resulting md5 is wrong. It is not equals md5 of file from other sources

```C#
var mstream = new MemoryStream();
part.ContentObject.DecodeTo(mstream);
mstream.Position = 0;
string hash = "";
using (var md5 = System.Security.Cryptography.MD5.Create())
    hash = md5.ComputeHash(mstream).Aggregate<byte, string>("", (a, inp) => a + inp.ToString("x2"));
```
```C#
hash != part.ComputeContentMd5();
```
```C#
public string ComputeContentMd5 ()
		{
			if (ContentObject == null)
				throw new InvalidOperationException ("Cannot compute Md5 checksum without a ContentObject.");

			using (var stream = ContentObject.Open ()) {
				byte[] checksum;

				using (var filtered = new FilteredStream (stream)) {
					if (ContentType.Matches ("text", "*"))
						filtered.Add (new Unix2DosFilter ());

					using (var md5 = new MD5 ())
						checksum = md5.ComputeHash (filtered);
				}

				var base64 = new Base64Encoder (true);
				var digest = new byte[base64.EstimateOutputLength (checksum.Length)];
				int n = base64.Flush (checksum, 0, checksum.Length, digest);

				return Encoding.ASCII.GetString (digest, 0, n);
			}
		}
```

**Comment by jstedfast** [comment]
Your code is hex-encoding the 16 bytes of the md5 hash while MimeKit base64 encodes the bytes.

If you read the Content-MD5 specification, it says to base64 (not hex encode) the md5sum.

**Comment by jstedfast** [comment]
https://tools.ietf.org/html/rfc1864#section-2

**Comment by msa48** [comment]
thanks

**Comment by jstedfast** [comment]
FWIW, Content-Md5 is likely a waste of effort since very few (if any?) real-world mail clients actually support it and/or do anything with it. I've never actually seen any clients make use of it for sure.
