### ISSUE TITLE
MimeMessage.WriteTo overrides existing characters instead of replacing the file

### ISSUE THREAD

**Issue by Suchiman** [jstedfast/MimeKit#154]
The [WriteTo](https://github.com/jstedfast/MimeKit/blob/f94934018bc1ffd847500cdc1e37434aa567ed82/MimeKit/MimeMessage.cs#L1152) method uses [File.OpenWrite](https://msdn.microsoft.com/en-US/library/system.io.file.openwrite(v=vs.110).aspx) (see remarks) which will not replace the existing file and neither append to it but instead replace as much characters as have been written.

The Output file will therefore likely become invalid which doesn't seems desired and caused some confusion for me because i was wondering why the output file still contained 2 MimeEntities while i did in fact remove one :boom:

**Comment by jstedfast** [comment]
Thanks. I've fixed this in git master now.
