### ISSUE TITLE
MimeParser MimeFormat.Mbox does not expose "From " line for a message.WriteTo call

### ISSUE THREAD

**Issue by tbiggins** [jstedfast/MimeKit#155]
Assuming a message like this in an .mbox file:
------------begin-----------
From MAILER-DAEMON Fri Jul  8 12:08:34 2011
From: Author <author@example.com>
To: Recipient <recipient@example.com>
Subject: Sample message 1

This is the body.
-------------end-----------------
if we invoke these lines
`var parser = new MimeParser(stream, MimeFormat.Mbox);`
`var exportStream = new MemoryStream();`
`while (!parser.IsEndOfStream)`
`            {`
`                var message = parser.ParseMessage();`
`                message.WriteTo(exportStream);`
`            }`
message.WriteTo() does not capture the first line:
From MAILER-DAEMON Fri Jul  8 12:08:34 2011
and there is seemingly no other property on the message object that includes that line either - so there is no obvious way to write the "From MAILER-DAEMON[...]" line to a new .mbox file

**Comment by tbiggins** [comment]
Also note: I posted a similar (but perhaps more cryptic) question here:
http://stackoverflow.com/questions/31567872/mimekit-parse-filtered-mbox-results-to-new-mbox

**Comment by tbiggins** [comment]
Nevermind - found the solution - RTFM. 
`var topLine = parser.MboxMarker;`
`MemoryStream mStream =`
`   new MemoryStream(ASCIIEncoding.Default.GetBytes(topLine));`
`            mStream.WriteTo(exportStream);`
`            mStream.Dispose();`

**Comment by jstedfast** [comment]
Glad you figured it out :-)
