### ISSUE TITLE
Question about reading Mime as a stream

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MimeKit#156]
Hi,

I'm trying to read a Mime message directly from a database record as a stream.
I do it like this:

var mimeMessage = MimeMessage.Load(Mime);

The mime is read from a database record through a custom class that I've written to be able to read the varbinary(max) field from a ms sql database as a stream.

This wrapper implements all the read methods from the stream interface like this:

internal class VarbinaryMaxReader : Stream
{
etc...
}

But when I try to pass this object to the MimeMessage.Load method it always fails with the message that I can't parse the headers.

When I first copy the complete stream to a memorystream and then pass this one to the MimeMessage.Load(Mime) method it all works without any problems.

What Stream methods is the Load message expecting? What am I missing in my wrapper?

Greetings,
Kees van Spelde

    internal class VarbinaryMaxReader : Stream
    {
        #region Fields
        /// <summary>
        /// Een SqlDataReader object
        /// </summary>
        private readonly SqlDataReader _sqlDataReader;

        /// <summary>
        /// Wordt gebruikt om bij te houden waar we zijn gebleven met het lezen van een VARBINARY(MAX) 
        /// veld in de database
        /// </summary>
        private long _dataOffset;

        /// <summary>
        /// De lengte van de stream
        /// </summary>
        private readonly long _length;
        #endregion

        #region Constructors
        /// <summary>
        /// Retourneerd een stream naar data in de database d.m.v. een stored procedure
        /// </summary>
        /// <param name="connectionString"></param>
        /// <param name="sqlTimeout">De timeout periode in seconden voor een <see cref="SqlCommand"/> object</param>
        /// <param name="storedProcedure">De stored procedure welke gebruikt moet worden om uit de database te lezen</param>
        /// <param name="parameterCollection">Een lijst met stored procedure parameters, of null wanneer niet nodig</param>
        /// <param name="length">De lengte van de stream</param>
        internal VarbinaryMaxReader(string connectionString,
                                   int sqlTimeout,
                                   string storedProcedure,
                                   IEnumerable<ParameterCollectionValue> parameterCollection,
                                   long length)
        {
            _length = length;

            var sqlConnection = new SqlConnection {ConnectionString = connectionString};
            sqlConnection.Open();

            // ReSharper disable once UseObjectOrCollectionInitializer
            using (var sqlCommand = new SqlCommand(storedProcedure, sqlConnection))
            {
                sqlCommand.CommandType = CommandType.StoredProcedure;
                sqlCommand.CommandTimeout = sqlTimeout;
                ParameterCollection.FillParameters(sqlCommand, parameterCollection);

                _sqlDataReader = sqlCommand.ExecuteReader(
                    CommandBehavior.SequentialAccess |
                    CommandBehavior.SingleResult |
                    CommandBehavior.SingleRow |
                    CommandBehavior.CloseConnection);

                _sqlDataReader.Read();
            }
        }

        /// <summary>
        /// Retourneerd een stream naar data in de database d.m.v. een query
        /// </summary>
        /// <param name="connectionString"></param>
        /// <param name="sqlTimeout">De timeout periode in seconden voor een <see cref="SqlCommand"/> object</param>
        /// <param name="query">De query welke gebruikt moet worden om uit de database te lezen</param>
        /// <param name="length">De lengte van de stream</param>
        internal VarbinaryMaxReader(string connectionString,
                                   int sqlTimeout,
                                   string query,
                                   long length)
        {
            _length = length;

            var sqlConnection = new SqlConnection { ConnectionString = connectionString };
            sqlConnection.Open();

            // ReSharper disable once UseObjectOrCollectionInitializer
            using (var sqlCommand = new SqlCommand(query, sqlConnection))
            {
                sqlCommand.CommandTimeout = sqlTimeout;

                _sqlDataReader = sqlCommand.ExecuteReader(
                    CommandBehavior.SequentialAccess |
                    CommandBehavior.SingleResult |
                    CommandBehavior.SingleRow |
                    CommandBehavior.CloseConnection);

                _sqlDataReader.Read();
            }
        }
        #endregion

        #region Read
        /// <summary>
        /// Deze methode wordt aangeroepen wanneer we vanuit de <see cref="Stream"/> lezen
        /// </summary>
        /// <param name="buffer">De buffer waarin we een deel van de stream van gaan laden</param>
        /// <param name="offset">De offset positie waar we beginnen met lezen</param>
        /// <param name="count">Aantal bytes dat we gaan lezen</param>
        /// <returns>Aantal gelezen bytes</returns>
        public override int Read(byte[] buffer, int offset, int count)
        {
            var bytesRead = _sqlDataReader.GetBytes(0, _dataOffset, buffer, 0, count);
            _dataOffset += bytesRead;
            return (int) bytesRead;
        }
        #endregion
        
        #region CanRead
        /// <summary>
        /// Retourneerd altijd een true omdat dit een readonly stream is
        /// </summary>
        public override bool CanRead
        {
            get { return true; }
        }
        #endregion

        #region CanSeek
        /// <summary>
        /// Retourneerd altijd een false
        /// </summary>
        public override bool CanSeek
        {
            get { return false; }
        }
        #endregion

        #region CanWrite
        /// <summary>
        /// Retourneerd altijd een false omdat dit een readonly stream is
        /// </summary>
        public override bool CanWrite
        {
            get { return false; }
        }
        #endregion

        #region Length
        /// <summary>
        /// Retourneerd de lengte van de stream
        /// </summary>
        public override long Length
        {
            get { return _length; }
        }
        #endregion

        #region Seek
        /// <summary>
        /// Deze methode is NIET geimplementeerd
        /// </summary>
        public override long Seek(long offset, SeekOrigin origin)
        {
            switch (origin)
            {
                case SeekOrigin.Begin:
                    _dataOffset = offset;
                    break;

                case SeekOrigin.Current:
                    if (_dataOffset + offset > Length)
                        throw new ArgumentOutOfRangeException("offset");

                    _dataOffset += offset;
                    break;

                case SeekOrigin.End:
                    if (_dataOffset - offset > 0)
                        throw new ArgumentOutOfRangeException("offset");

                    _dataOffset -= offset;
                    break;
            }

            return _dataOffset;
        }
        #endregion

        #region Position
        /// <summary>
        /// Deze methode is NIET geimplementeerd
        /// </summary>
        public override long Position
        {
            get { return _dataOffset; }
            set { _dataOffset = value; }
        }
        #endregion

        #region Unimplemented methods
        /// <summary>
        /// Deze methode is NIET geimplementeerd (readonly stream)
        /// </summary>
        /// <param name="buffer"></param>
        /// <param name="offset"></param>
        /// <param name="count"></param>
        public override void Write(byte[] buffer, int offset, int count)
        {
            throw new NotSupportedException();
        }
        
        /// <summary>
        /// Deze methode is NIET geimplementeerd
        /// </summary>
        public override void Flush()
        {
            throw new NotSupportedException();
        }

        /// <summary>
        /// Deze methode is NIET geimplementeerd
        /// </summary>
        public override void SetLength(long value)
        {
            throw new NotSupportedException();
        }
        #endregion
    }

**Comment by jstedfast** [comment]
You should just be able to implement Read() and CanRead (as you've done).

MimeParser reads chunks of data in 4096 byte increments, perhaps when you are copying it to a memory stream, you are copying 16k instead of 4k and maybe that makes a difference? (by default, Stream.CopyTo() uses a 16k buffer)

The only places that throw an error about not being able to parse the headers is if the stream begins with junk data *or* if the header block of the message or any of its parts is truncated.

Perhaps the problem is that you are disposing the sqlCommand? Maybe try keeping it open until the stream is disposed?

**Comment by Sicos1977** [comment]
Found it... it was a bug in my wrapper in the read method

public override int Read(byte[] buffer, int offset, int count)

var bytesRead = _sqlDataReader.GetBytes(0, _dataOffset, buffer, 0, count);

MimeKit was passing an offset of 128 to the Read method. In my wrapper I ignored the offset and this way it resulted in the "Could not parse headers" exception

This line fixed it.
var bytesRead = _sqlDataReader.GetBytes(0, _dataOffset, offset, 0, count);

Thanks for your help anyway and keep up the good work with Mime and Mailkit

Greetings,
Kees van Spelde

**Comment by jstedfast** [comment]
Ah, gotcha. That makes a whole lot of sense!
