### ISSUE TITLE
DKIM signature not built correctly

### ISSUE THREAD

**Issue by henning-krause** [jstedfast/MimeKit#157]
Given this DKIM-Header:

DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=xq; d=<redacted>;
 h=Date:From:Reply-To:To:Message-Id:Subject:MIME-Version:Content-Type:Content-Transfer-Encoding:List-Unsubscribe; i=<redacted;
 bh=wMgz6i+78bq2sDaMiYUhTCGmojY=;
 b=HxJYp3S/fkVKbR08nmDSALxVAXSJ2H0Il/115QOsS54qBtc6h4olwlieDAe+NooqSAwF+NaTiul0
   kbXA/voomphg+92AITyvPvCLYsOeKx1Bat3fpsOXmxZ0It2W0mPHZs4elVt8XnQaubegknN5QNmd
   CHXFBYpqPHui37PiDds=

MimeKit can not sucessfully calculate the header hash, because the Content-* headers are missing in the Header collection.

The MIME parsing engine filters them out:

    internal MimeMessage (ParserOptions options, IEnumerable<Header> headers) {
    // ...

    // add all of our message headers...
    	foreach (var header in headers) {
     		if (header.Field.StartsWith ("Content-", StringComparison.OrdinalIgnoreCase))
    			continue;
    
    		Headers.Add (header);
    	}
    }

**Comment by jstedfast** [comment]
Thanks. This should be fixed now.
