### ISSUE TITLE
Validating DKIM-Messages, possible bug in header serialization

### ISSUE THREAD

**Issue by henning-krause** [jstedfast/MimeKit#158]
Class MimeMessage:

Method DkimWriteHeaderRelaxed contains this code at the end of the method:

    stream.Write (options.NewLineBytes, 0, options.NewLineBytes.Length);

This method is called after all other Headers have been serialized.

https://tools.ietf.org/html/rfc6376#section-3.7 states:

2.  The DKIM-Signature header field that exists (verifying) or will
       be inserted (signing) in the message, with the value of the "b="
       tag (including all surrounding whitespace) deleted (i.e., treated
       as the empty string), canonicalized using the header
       canonicalization algorithm specified in the "c=" tag, and without
       a trailing CRLF.

It states that no trailing CRLF should be appended to the Header.

**Comment by jstedfast** [comment]
Do you have a test case? The test cases I have all pass with the current logic.

**Comment by jstedfast** [comment]
Looks like I don't actually have a test case for this one in my unit tests. It passes either way. Could you get a test case for me? I am hoping to make a new release tomorrow and it'd be nice if I could fix this (if there is a bug) before I make a new release.

Thanks.

**Comment by jstedfast** [comment]
Never mind. Once I added an assert to my GMail test-case to make sure that Verify() returned true, it failed w/o changing the code to ignore the CRLF in the DKIM-Signature header.

Fixed in https://github.com/jstedfast/MimeKit/commit/54f550c5befc3e139ba239a46e668f67ae355238

Thanks!
