### ISSUE TITLE
vb 2010

### ISSUE THREAD

**Issue by tmcginnis3** [jstedfast/MimeKit#164]
Is there an easy way to use mimekit in vs 2010 express? adding the reference to the dll's is not sufficient and 2010 does not include the package installer.

**Comment by jstedfast** [comment]
It should be sufficient to reference the dll's, if it's not, then I have no idea what the problem is. You might have better luck asking on stackoveflow.com because I'm not familiar with vb 2010.

Sorry I couldn't be more helpful.

**Comment by LeeBear35** [comment]
Since you do not have NUGET Package Manager, you should check https://docs.nuget.org/consume/installing-nuget about installing the package manager for vs2010.

You are likely missing the dependency BouncyCastle.

**Comment by jstedfast** [comment]
Also, it may be worth installing VS2015 Community Edition over VS2010 Express.
