### ISSUE TITLE
DKIM-Signature with trailing semi-colon

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#166]
ParseDkimSignature throws a format exception if the DKIM-Signature tag-list ends with a semi-colon.

The semi-colon is optional at the end of the tag-list, see https://tools.ietf.org/html/rfc6376#section-3.2

Example DKIM-Signature with a trailing semi-colon: https://tools.ietf.org/html/rfc6376#appendix-A.2

**Comment by jstedfast** [comment]
fixed

**Comment by breedbekkikker** [comment]
Thanks for your prompt response!

Now that ParseDkimSignature continues while using a DKIM-Signature with a trailing semi-colon, GetSignedDkimSignatureHeader throws a format exception stating that the "signature parameter is not at the end".
When using a DKIM-Signature with a trailing semi-colon, GetSignedDkimSignatureHeader should return the DKIM-Signature without the b= signature tag value but WITH the trailing semi-colon.
Additionally, RFC does not state that the b= signature tag must be at end (although this would probably be the case in most implementations).
