### ISSUE TITLE
DKIM-Signature without a signed From header

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#167]
If the "h=" tag does not include the From header field, the Verifier MUST ignore the DKIM-Signature header field and return PERMFAIL (From field not signed). See https://tools.ietf.org/html/rfc6376#section-6.1.1

One might expect that ValidateDkimSignatureParameters would throw a format exception if the DKIM-Signature "h=" tag does not include a From header field.

**Comment by jstedfast** [comment]
fixed
