### ISSUE TITLE
DKIM relaxed header canonicalization

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#171]
DKIM header hash validation fails with relaxed header canonicalization of a multiline header that has FWS with WSP before CRLF.

For example, consider the following original header:

Name:[WSP]example[WSP][CRLF][WSP]value[CRLF]

The header should be after relaxed canonicalization:

name:[SP]example[SP]value[CRLF]

**Comment by jstedfast** [comment]
Can you write a unit test for me?

**Comment by jstedfast** [comment]
BTW, your example is wrong:

```
   o  Delete any WSP characters remaining before and after the colon
      separating the header field name from the header field value.  The
      colon separator MUST be retained.
```

This means that your example should end up as:

name:example[SP]value[CRLF]

**Comment by breedbekkikker** [comment]
Thanks, I agree with your correction of the example.

I will follow up on the unit test.
