### ISSUE TITLE
DKIM relaxed body canonicalization

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#172]
DKIM body hash validation with relaxed canonicalization fails if:

- the original body has WSP before CRLF (excluding the last line), or
- the original body has multiple sequences of WSP within a line, or
- the original body is non-empty and ends with multiple CRLF

See https://tools.ietf.org/html/rfc6376#section-3.4.4

This can be tested easily by modifying the gmail.msg test data file.

**Comment by jstedfast** [comment]
According to my unit tests, the relaxed body canonicalization logic is correct.

**Comment by jstedfast** [comment]
Never mind, the problem was not the canonicalization logic, but rather that the logic to push the data through the canonicalization filter was bypassing the filter and writing directly to the hash stream.
