### ISSUE TITLE
Building MimeKit.Net45.sln in VS2015 Enterprise fails

### ISSUE THREAD

**Issue by surekqomi** [jstedfast/MimeKit#176]
Hi,

Following the instructions on the github page, I forked the MimeKit repo and opened the MimeKit.Net45 solution to build MimeKit. This fails with an error "Couldn't find the required information in the lock file. Make sure you have .NETFramework,Version=v4.5 mentioned in your targets." I've narrowed it down to the MimeKit project itself, as the linked BouncyCastle and Mono.Data.Sqlite projects both build cleanly. Since it seems that the build is being done by MSBuild rather than VS itself I'm at a loss to work around or fix this problem.

**Comment by jstedfast** [comment]
It builds fine for me in Visual Studio 2013 Professional and 2015 Community Edition

**Comment by surekqomi** [comment]
Just a follow-up: I built the project using an old copy of VS2013 Premium and it builds correctly, so the issue must then be with VS2015 Enterprise. I'll apply your change above and report back.

**Comment by surekqomi** [comment]
OK, applied the above change, but VS still breaks the build with the above error. I'll fall back to VS2013 for the time being.

**Comment by jstedfast** [comment]
I have no idea what the problem could be :(

**Comment by jstedfast** [comment]
Try deleting MimeKit.CoreFX.xproj in the MimeKit directory

**Comment by msa48** [comment]
Hello.
Delete two files project.json and project.lock.json and build will be success.
It maybe some bag in VS2015, but this files need for asp.net mvc projects.

**Comment by surekqomi** [comment]
I've deleted the MimeKit.CoreFX.xproj file, but this does not remove the error, and the build still breaks. Next I deleted the project.json and project.lock.json files, which changes the error being reported to "Error occurred while restoring NuGet packages: Could not find file 'C:\git\MimeKit\MimeKit\project.json'." Interrestingly enough, in this last case the libraries do get built, despite the error.

**Comment by jstedfast** [comment]
FWIW, I've moved those files out of the MimeKit directory so they shouldn't cause problems anymore
