### ISSUE TITLE
Add MultipartReport type

### ISSUE THREAD

**Issue by msa48** [jstedfast/MimeKit#177]
It's a feature request.

Please, add new class `MultipartReport` inherited from `Multipart`. This will simplify the work with a mime content-type multipart/report by the Visitor pattern, as is well known that the following subsidiaries parts connected to each other, and allow them to process more accurately. 

I may prepare pull request, but i don't have Xamarin and can not make changes in projects of that type

**Comment by jstedfast** [comment]
I don't want to add a new class for every single possible mime-type and there is no special feature that multipart/report needs, so it'd just be an empty subclass with no additional logic which means adding it is pointless.

Just override VisitMultipart() and handle the mime-type there.
