### ISSUE TITLE
DKIM-Signature header, Signature Timestamp "t=" not correct

### ISSUE THREAD

**Issue by AldeaAlexandra** [jstedfast/MimeKit#180]
Issue : 
The signature timestamp from the DKIM-Signature header , generated after Sign-ing a MimeMessage with a DkimSigner is computed based on local machine time (DateTime.Now), and not on UTC time zone, as specified in RFC6376. 

I encountered this problem while testing my DKIM signed emails, sent to a Postfix mail server installed on a Fedora virtual machine, with opendkim mail filter, and got an error from opendkim : "signature timestamp in the future".
The problem is in MimeMessage.cs , line 1432. 

Could the problem be fixed?

**Comment by jstedfast** [comment]
Thanks for the bug report!

**Comment by jstedfast** [comment]
I've released MimeKit 1.2.14 to NuGet with the fix for this bug.

**Comment by breedbekkikker** [comment]
Great! Thanks a lot!
