### ISSUE TITLE
DKIM body hash with multipart/related

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#181]
When using Gmail's web interface to send an email with an inline image (copied from clipboard), the mime message is multipart/related. The first body part contains a multipart/alternative section. The boundary following the last body part of the multipart/alternative section and the boundary of the next body part of the multipart/related section are separated by a single CRLF. E.g.:

`--e89a8f647253643e8f052238e631--`
`--e89a8f647253643e93052238e632`
 
However, when using the DKIM Verify function to verify the Gmail message, the body hash is calculated over a body with an additional CRLF between these two boundaries. This results in falsifying these kind of Gmail messages.

**Comment by jstedfast** [comment]
I've released MimeKit 1.2.14 to NuGet with the fix for this bug.

**Comment by breedbekkikker** [comment]
Great! Thanks a lot!
