### ISSUE TITLE
Google IMAP Garbage lines before header

### ISSUE THREAD

**Issue by sbukhtiyarov** [jstedfast/MimeKit#182]
I observe next behaviour when iterate with Google IMAP for one of mailboxes.
FETCH result contain some garbage lines before start normal headers.
Examples: 
---
* 243 FETCH (UID 13942 MODSEQ (1) BODY[] {1889}
User: r-MX001.ip.xxxxx.xx> for
 xxxx@xxx.xx; Sun, 24 Jun 2007 23:18:59 -0400 (EDT)
Received: from ns1.xxxx.xx ([0.0.0.0.])
---
* 243 FETCH .....
align=3D=22center=22 border=3D=220=22 cellpadding: 00000000
X-Mozilla-Keys:                                                                                 
Received: from ns1.xxxx.xx ([0.0.0.0.])

Probably source of this problem in incorrect import operation to Google account. But it was ago.
Results is a MimeParser throw System.FormatException: Failed to parse message headers.

One of the solutions skip lines like this while no any header was detetected. 
StepHeaders have similar cheking for "From lines"

**Comment by jstedfast** [comment]
This is unfixable in any real capacity. I would recommend using ImapFolder.GetStream() and then writing your own logic to fixup the message stream before passing it to the MimeParser.
