### ISSUE TITLE
Parsing outlook .msg

### ISSUE THREAD

**Issue by dannylindquist** [jstedfast/MimeKit#183]
I just stumbled upon Mimekit and its awesome, but I am having trouble understanding the original parsing example. I realize that outlook's MSG file is not in any way MIME, but it appears you are parsing a .msg file in the example in the README.

Does MimeKit have this capability, or am I just misunderstood by the context of the example.

I have attempted to parse a .msg following the streaming example with no luck. 
```
var stream = File.OpenRead(@"C:\outlookmessage.msg");
var parser = new MimeParser(stream);
var msg = parser.ParseMessage();
```
Thank you for all your time and effort you have put into this project.

**Comment by jstedfast** [comment]
MimeKit cannot parse the proprietary Outlook message format (I can never remember if Outlook's special format uses .eml or .msg as the extension).

In my example, it is parsing a MIME message file. I just happened to give it a .msg file extension.

(Note: I use Mac OS X and not Windows, so neither file extension has any meaning)

**Comment by Sicos1977** [comment]
Use this if you want to parse Outlook MSG files. https://github.com/Sicos1977/MSGReader
