### ISSUE TITLE
MimeMessage.Headers Doesn't Include All Message Headers

### ISSUE THREAD

**Issue by nitinag** [jstedfast/MimeKit#185]
I would expect **MimeMessage.Headers** to return all the actual headers of the message (in the same order as the message). However, it separates out the Content-Type header (Content-*) onto MimeMessage.Body.Headers, which breaks this assumption. This leads to bugs like https://github.com/jstedfast/MimeKit/issues/157 among others. I understand why having it there on MimeMessage.Body makes sense, but why not also ensure MimeMessage.Headers matches the actual message headers count thus keeping that assumption as well?

As a workaround, currently one can separately use HeaderList.Load when they need the full headers of the message, which would keep that MimeMessage.Headers expectation intact, but it seems like the library should keep that expectation by default?

**Comment by jstedfast** [comment]
Content-* headers are not message headers, they are MIME part headers - hence one of the reasons for the split.

Another reason for the split is the ability to swap out top-level MIME parts in the message. If the Content-* headers are in the MimeMessage.Headers, then it's not nearly as trivial to do.

Once you understand that there is a split, is it really that hard to find what you are looking for?

**Comment by nitinag** [comment]
Could the documentation at http://www.mimekit.net/docs/html/P_MimeKit_MimeMessage_Headers.htm be updated to include this explanation?

Coming from another library, I wasn't expecting this so it took some time to find out MimeMessage.Headers.Count didn't match the actual header count on the message. I do understnard why it was done and why it's better. It'd still be nice if they were kept in sync. Maybe the top level is editable via Body.Headers, but read-only displayed in the MimeMessage.Headers as well? Regardless, now that i Know, it's easy enough for me to combine the message headers with the top level mime headers myself when this is necessary. Having that on the docs for that property may save someone else some time in the future.
