### ISSUE TITLE
DkimHashStream ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#188]
A System.ArgumentOutOfRangeException occurs at MimeKit.Cryptography.DkimHashStream.ValidateArguments when calculating the DKIM body hash during verification. It concerns a 4096 bytes buffer where the last three bytes are [CR][LF][CR] and the first byte of the next 4096 bytes buffer is [LF].

See attached file for an example. Both relaxed and simple body canonicalization methods are affected.

[message.txt](https://github.com/jstedfast/MimeKit/files/36877/message.txt)

**Comment by jstedfast** [comment]
I've released MimeKit 1.2.15 to nuget.org with a fix for this.

**Comment by breedbekkikker** [comment]
Thanks! It's working fine now.
