### ISSUE TITLE
Wrong encoding in mail subject.

### ISSUE THREAD

**Issue by AntonGordienko** [jstedfast/MimeKit#191]
Hey, Jeffrey.
I have a message from yahoo. And its subject looked wrong:

Original subject:
"Новая попытка входа вFindo"

Subject from MimeKit:
"????? ??????? ????? ?Findo"

Header:
Subject: <D0><9D><D0><BE><D0><B2><D0><B0><D1><8F> <D0><BF><D0><BE><D0><BF><D1><8B><D1><82><D0><BA><D0><B0> <D0><B2><D1><85><D0><BE><D0><B4><D0><B0> <D0><B2>Findo

Is it possible to fix? Or this mail has wrong format?

**Comment by jstedfast** [comment]
There are 2 ways you can work around this broken email subject (it's not allowed to use raw 8-bit text in headers).

The first is to decode an individual message header again, but with a specified charset encoding to use when unencoded 8-bit text is encountered:

```csharp
Header subject;

if (message.Headers.TryGetValue (HeaderId.Subject, out subject)) {
    var text = subject.GetValue (Encoding.GetEncoding ("whatever"));
}
```

The second option, is to set a default fallback charset encoding on the parser options:

```csharp
var options = ParserOptions.Default.Clone ();
options.CharsetEncoding = Encoding.GetEncoding ("whatever");

var message = MimeMessage.Load (options, stream);
```

**Comment by l1brain** [comment]
@jstedfast hello !
I have simmilar issue and not quiet understand hot to resolve it. Can you please, describe solution more detailed?

**Comment by jstedfast** [comment]
Well, you first need to guess what charset the Subject string is in, because if MimeKit/MailKit decoded it and it doesn't "look right" to you, then it means that the client that generated the message did not correctly tag the Subject with the correct charset.

Once you decide what charset you want to try using (let's say you think it is "gb2312"), you can then do:

```csharp
if (message.Headers.TryGetValue (HeaderId.Subject, out Header header)) {
    string subject = header.GetValue (Encoding.GetEncoding ("gb2312"));
}
```

That's as detailed a description as there is.

**Comment by l1brain** [comment]
@jstedfast thank you for your reply! But my problem was with appsetting.json that convert cyrillic symbols to ????????????? ...
