### ISSUE TITLE
How to treat eml attachments

### ISSUE THREAD

**Issue by SlyJay** [jstedfast/MimeKit#193]
Hi,
we are using Mimekit to parse some eml files but since some of them have attachments in .eml format we are trying to figure out how to treat them.

One idea is to treat them as standard attachments but they are parsed as MessagePart (not MimePart) and we cannot find the stream or byte content to convert them into a file.

Are we missing something? 

Thanks in advance for your help.

Sly

**Comment by jstedfast** [comment]
`MessagePart` has a `Message` property which contains the pre-parsed MimeMessage content.

To write the content to a file, you can just do:

```csharp
MessagePart part = ...;

part.Message.WriteTo ("filename.eml");
```

**Comment by 1591mv** [comment]
if i am sending a email like an attachment through another email , then Mimekit is not reading that attached email as an attachment, what should i do.

**Comment by jstedfast** [comment]
You need to set the Content-Disposition header to “attachment”

**Comment by 1591mv** [comment]
but index(on that attached email is coming as body part ) may be variant , that may be index dependency that not that correct thing , i think

**Comment by jstedfast** [comment]
MimePart.ContentDisposition = new ContentDisposition (“attachment”);
