### ISSUE TITLE
GnuPGContext won't find my public certificate (Mac OS X, GPGTools)

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#194]
Howdy,

I've installed GPGTools on my MacBook Air, and subclassed GnuPGContext, supplying my password in the GetPasswordForKey method, but when I invoke MultipartEncrypted.Encrypt, it throws an exception saying; "MimeKit.Cryptography.PublicKeyNotFoundException
The public key could not be found."

Stack trace is; 
at MimeKit.Cryptography.OpenPgpContext.GetPublicKey (MimeKit.MailboxAddress mailbox) [0x000ea] in <filename unknown>:0 
  at MimeKit.Cryptography.OpenPgpContext.GetPublicKeys (IEnumerable`1 mailboxes) [0x00024] in <filename unknown>:0 
  at MimeKit.Cryptography.OpenPgpContext.Encrypt (IEnumerable`1 recipients, System.IO.Stream content) [0x0001c] in <filename unknown>:0 
  at MimeKit.Cryptography.MultipartEncrypted.Encrypt (MimeKit.Cryptography.OpenPgpContext ctx, IEnumerable`1 recipients, MimeKit.MimeEntity entity) [0x0009a] in <filename unknown>:0 

I have triple checked in GPG Keychain from GPGTools that the email address is correct. I have even tried multiple emails, both that are imported from Keychain server, and locally created, but regardless of what I do, it seems to choke ...

I installed GPGTools with all default settings, and from a Terminal window "gpg" is a recognized command, and starts the gpg process from GnuPG.

Suggestions ...?

PS,
Code is exact replica (more or less) of your sample code of how to encrypt message using PGP in a GnuPG subclassed context from your README.md file ...

**Comment by jstedfast** [comment]
I wonder if GPGTools puts the keyrings in a different place than gpg does when installing it via homebrew.

**Comment by jstedfast** [comment]
Looks like it's stored in the same place, so that's not the problem.

Does the email address you are trying to encrypt to exist in your keyring?

**Comment by jstedfast** [comment]
BTW, which target framework are you using? Are you using the PCL? Or .NET 4.5? If you are using nuget, you can check your packages.config to be sure.

**Comment by polterguy** [comment]
Hi Jeff, and thanx for blistering fast answers, as usual :)

The email I am sending to, and also using to encrypt my message, is the same, and it exist in my GPG Keychain, when I look in the GUI for GPG Keychain. I am using .NET 4.5

  <package id="MailKit" version="1.2.15" targetFramework="net45" />
  <package id="MimeKit" version="1.2.16.0" targetFramework="net45" />


(from my packages.config file)

**Comment by polterguy** [comment]
BTW, it's a web app, running (I presume) in xsp4 (Xamarin) ...

**Comment by jstedfast** [comment]
Okay... and I assume that the  key has not been revoked. Does it have an expiration date?

In GPGTools' Keyring app, you can right-click on a key and show details.

On the "Key" tab (the main tab), what are the values of Validity and Capabilities?

On the "Subkeys" tab, what is the value of Capabilities?

I'm not entirely sure how to read these values, but I *think* the subkey Capability value should be "e" (for "supports encryption").

**Comment by jstedfast** [comment]
(I ask about the expiration date because I am wondering if my logic to calculate expiration is wrong)

**Comment by polterguy** [comment]
Expires; 8 December 2019 at 12:19
Validity; Ultimate   (I created it locally)
Capabilities; "e"

PS,
I am in Norway, might there be some Localization issues when calculating dates ...?

**Comment by jstedfast** [comment]
Thanks, I'm thinking the expiration date calculation might be the culprit. Everything else matches what my keys look like.

**Comment by jstedfast** [comment]
Darn >= instead of <= ;-)

**Comment by polterguy** [comment]
Norway use "15 February 2015" for user displayed dates where US use "February 15, 2015", etc ...
Don't know if that's the issue, but hopefully it may help ...

PS!
You saw my comment about this being a Web App, running on xsp4 ...?

Let me know if you need anymore to go on :)

**Comment by polterguy** [comment]
Hahahahahahaha :D

ROFLMAO ...!!

Well, glad to please :)

Thx, when will this be out in nuget?

**Comment by jstedfast** [comment]
https://www.nuget.org/packages/MimeKit/1.2.17.3

I normally don't post to nuget this fast, but I wanted to release a stable (non-prerelease) nuget with the fixes I had done recently anyway :-)

**Comment by polterguy** [comment]
Thx, you're a champion!! :)

**Comment by polterguy** [comment]
The Eagle has landed Houston!! :dancer:

**Comment by jstedfast** [comment]
Fixed in the MimeKit 1.2.18 nuget :)
