### ISSUE TITLE
Default Content-Disposition/filename for PGP Signature attachments

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#195]
Howdy,

Don't know if this doesn't even make sense, but when you sign a message using a PGP public certificate, shouldn't MimeKit by default produce some sort of "sane filename" for the Content-Disposition header ...?

I vaguely remember that when I used MimeKit some months ago, it would create a "sane filename" for my S/MIME signature files. Shouldn't it do the same for PGP signatures?

Header of PGP signature entity today is; 
Content-Type: application/pgp-signature
Content-Disposition: attachment
Content-Transfer-Encoding: 7bit

I'd expect it to have something like;
Content-Type: application/pgp-signature
Content-Disposition: attachment; filename=signature.pgp (something ...)
Content-Transfer-Encoding: 7bit

Maybe this doesn't make sense at all, and that I am just assuming something that shouldn't be a feature, but I think it makes sense, or ...?

**Comment by jstedfast** [comment]
Yea, it makes sense :)

Done!

**Comment by polterguy** [comment]
Thx :)

**Comment by jstedfast** [comment]
The MimeKit 1.2.18 nuget I just released sets this field.
