### ISSUE TITLE
Get all headers not handled by properties

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#196]
Howdy, sorry if this is a dumb question, but is there any standard ways of retrieving all headers that are not handled by properties from MimeMessage?

For instance, I do not want to retrieve stuff like "Resent-From", because there's a property for it, but I would like to retrieve "X-Facebook-Notify" (which is a Facebook extension header)

That way I can in my logic add everything that's not in your list of properties into some "additional headers bag" in my code. Preserving all headers, while separating the extension headers from the standardised headers ...

I know I could of course create a gigantic switch, having "continue" statement for every single header there exist a property for, it just "feels wrong" I presume ...?

And I am thinking there should possibly either be some support method in some utility class there, which I don't know about, or some method on MimeMessage called "GetNonStdHeaders" (or something equivalent), returning only the headers MimeMessage does not wrap in properties ...?

If I need to create a "humongous switch", which headers should I then ignore ...?
It is not always intuitively understood which property maps to which header, and how the header is written in the spec ...

**Comment by jstedfast** [comment]
Right now, the only solution is a switch statement.

The current list of headers that have a MimeMessage property are:

```
HeaderId.Bcc
HeaderId.Cc
HeaderId.Date
HeaderId.From
HeaderId.Importance
HeaderId.InReplyTo
HeaderId.MessageId
HeaderId.MimeVersion
HeaderId.Priority
HeaderId.References
HeaderId.ReplyTo
HeaderId.ResentBcc
HeaderId.ResentCc
HeaderId.ResentDate
HeaderId.ResentFrom
HeaderId.MessageId
HeaderId.ResentReplyTo
HeaderId.ResentSender
HeaderId.ResentTo
HeaderId.Sender
HeaderId.Subject
HeaderId.To
HeaderId.XPriority
```

And of course, for mime parts:

```
HeaderId.ContentType
HeaderId.ContentDisposition
HeaderId.ContentTransferEncoding
HeaderId.ContentDuration
HeaderId.ContentLocation
HeaderId.ContentLanguage
HeaderId.ContentMd5
HeaderId.ContentId
```

I'm not sure it makes sense to have an API to get all headers that don't have a property mapping as I don't think many developers would find that useful.

**Comment by polterguy** [comment]
Thx, you're of course right I presume. My reasons for asking, was thinking you might extend the properties in the future, creating redundant results for my code, if I create a "switch" logic ...

Thx for the list :)

PS!
To exclude these headers correctly, all I have to do is to transform each capital letter to "-" plus letter, right ...?

Such that "ContentLocation" property becomes "Content-Location", "ContentMd5" becomes "Content-Md5", "Bcc" becomes (only) "Bcc", etc, right ...?

**Comment by polterguy** [comment]
BTW, cannot help realising there's no XPriority on MimeMessage ...?
Was that a typo, or am I missing something obvious here ...?

**Comment by jstedfast** [comment]
The XPriority property is merged with the Priority value, basically if the message has XPriority header exists but the Priority header does not, the XPriority value is used by the Priority property.

You can filter the headers by matching those enum values against the Header.Id property, that should be a lot faster than comparing strings. Each Header also has a Name property, so you don't need to convert the HeaderId enum directly to a string.

If you do need to convert a HeaderId enum value to a string, there's an extension method called ToHeaderName() that I put on HeaderId enums.

**Comment by polterguy** [comment]
Hmm, I think I understood most of that, here's my code now;

```csharp
            var _excludedHeaders = new List<HeaderId> (new HeaderId [] {
                HeaderId.Bcc, HeaderId.Cc, HeaderId.Date, HeaderId.From, HeaderId.Importance, HeaderId.InReplyTo, HeaderId.MessageId, 
                HeaderId.MimeVersion, HeaderId.Priority, HeaderId.References, HeaderId.ReplyTo, HeaderId.ResentBcc, HeaderId.ResentCc, 
                HeaderId.ResentDate, HeaderId.ResentFrom, HeaderId.ResentReplyTo, HeaderId.ResentSender, HeaderId.ResentTo, 
                HeaderId.Sender, HeaderId.Subject, HeaderId.To, HeaderId.XPriority});

            foreach (var idxHeader in message.Headers.Where (ix => _excludedHeaders.IndexOf (ix.Id) == -1)) {

                // Retrieving currently iterated header, adding into my own structure here ...
                mNode.FindOrCreate ("x-headers").Add (idxHeader.Field, idxHeader.Value);
            }
```

I couldn't find any "Name" property on the Header class though, but it seems as what you're meaning is the "Field" property ...?

**Comment by jstedfast** [comment]
Sorry, you're correct - it's called "Field". It's still morning here :)

**Comment by polterguy** [comment]
No probs :)
