### ISSUE TITLE
Add a MailboxAddress.Parse method that returns a MailboxAddress instead of InternetAddress ?

### ISSUE THREAD

**Issue by superlogical** [jstedfast/MimeKit#197]

**Comment by jstedfast** [comment]
The Parse() method is on the InternetAddress class (which is the base class for MailboxAddress).

You can just cast the result to MailboxAddress.

**Comment by superlogical** [comment]
I guess it would be nice if you didn't have to cast the result though.

**Comment by jstedfast** [comment]
Implemented.

**Comment by superlogical** [comment]
Wow thanks!!!

**Comment by jstedfast** [comment]
MimeKit 1.2.18 just released to nuget supports this. I'll be making another 1.3.0-beta in the next few days (if you need dnxcore50)
