### ISSUE TITLE
Improvement suggestion for examples

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#199]
In your examples, where you describe how to traverse MimeEnities, you should probably wrap a "using" statement around your MimeIterator, since it implements IDisposable.

What I mean;
```csharp
using (var iter = new MimeIterator (message)) {

   // collect our list of attachments and their parent multiparts
   while (iter.MoveNext ()) {
       var multipart = iter.Parent as Multipart;
       var part = iter.Current as MimePart;

       if (multipart != null && part != null && part.IsAttachment) {
           // keep track of each attachment's parent multipart
           multiparts.Add (multipart);
           attachments.Add (part);
       }
   }
}
```

Also, it would create more beautiful client code, and be more intuitive to use the library, if you created a wrapper that returns an IEnumerable&lt;MimeEntity&gt; since "foreach" automatically calls Dispose on IDisposable object (ref; http://stackoverflow.com/questions/4982396/does-foreach-automatically-call-dispose)

This way your example could change to;

```csharp
// Iterate returns object of type IEnumerable<MimeEntity>, 
// which wraps the IEnumerator<MimeEntity> class
foreach (var part in MimeIterator.Iterate (message)) {
       var multipart = iter.Parent as Multipart;

       if (multipart != null && part != null && part.IsAttachment) {
           // keep track of each attachment's parent multipart
           multiparts.Add (multipart);
           attachments.Add (part);
       }
}
```

That way you turn 10 lines of relatively unintuitive code, into 7 lines of much easier to understand code, and the library becomes easier to understand, especially for "noobs" ...

I could write this piece for you if you wish ...?

**Comment by polterguy** [comment]
BTW, as I took a cigarette, and had some neurons firing up, I realised the best solution would probably be to implement IEnumerable&lt;MimeEntity&gt; on MimeMessage ...?

**Comment by jstedfast** [comment]
MimeMessage has a `BodyParts` property that iterates over all of the MimeEntity's in the message.

The MimeIterator is more for being able to figure out the parent of each entity as opposed to getting a "flat list".

I must have made the iterator disposable after writing up the sample. I'll fix that up, thanks!

**Comment by polterguy** [comment]
Ahh, so "BodyParts" retrieves ALL MimeEntities in the message, meaning if I don't care about the parent, I can exchange my MimeIterator usage with "BodyParts" ...?

**Comment by jstedfast** [comment]
Yep!

**Comment by polterguy** [comment]
BTW,

Still think you should have an IEnumerable&lt;MimeEntity&gt; wrapper to ease usage of MimeIterator.

Possibly a private static method on MimeIterator, returning an IEnumerable&lt;MimeEntity&gt; object of some sort, which means consumer wouldn't have to fiddle with "MoveNext()", etc, but could simply use a "foreach" ...

Not that it matters for me, since I think I'm going to have to go "all in" and recursively create my own iteration process, starting from MimeMessage.Body, and recursively iterate everything, but I think for those who needs it, having the IEnumerable instance would be easier to understand, consume, and create cleaner client code :)
