### ISSUE TITLE
Question; Where is ApplicationPgpSignature MimeEntity when using MultipartEncrypted.Decrypt on a signed and encrypted message?

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#201]
If I create a MimeMessage and I sign it with my private key, from my GnuPG Context, for then to retrieve the message, then I get returned a MultipartSigned entity, where I have two items. One which is my "content body item", the other which is the ApplicationPgpSignature used for signing the message.

If I however use "MultipartEncrypted.SignAndEncrypt" when creating my message, for then to use MultipartEncrypted.Decrypt, and I use the overload which takes an "out DigitalSignatureCollection" argument, then it returns only a TextPart, and there is no ApplicationPgpSignature when I retrieve my message. Where did the "ApplicationPgpSignature" MimeEntity end up?

I guess I would assume that when you use "SignAndEncrypt", it would first sign it, creating TWO MimeEntities, for then to encrypt the message, resulting in that I would end up with the same result after decrypting my message as I would when starting out with a message that is only signed ...?

BTW, sorry for hammering you with questions, I just really want to get this right, which requires me having a relatively deep understanding of the underpinnings of your library. PS, all my creations are FOSS too ... ;)

**Comment by jstedfast** [comment]
With PGP, you can sign and encrypt with a single operation, such that the signature gets embedded in the encrypted data.

With S/MIME, what you'd do is create a `multipart/signed` and then encrypt that multipart entity (which I think is what you were expecting to happen for PGP).

You could do the same with PGP as well, but MultipartEncrypted.SignAndEncrypt() uses the PGP feature that allows you to do both in a single pass.

So what you want to do, when you decrypt a `multipart/encrypted`, is to use the Decrypt() method that outputs a DigitalSignatureCollection in case it was both signed and encrypted.

Hope that helps.

**Comment by polterguy** [comment]
Thx, it does. I think I was expecting it to work such as you explained for S/MIME ... :)
