### ISSUE TITLE
Question; Speed of signature creation

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#205]
Howdy, this might have a natural answer, still I have to throw it out there ...

When I encrypt a message, the encryption process is literally "instantaneous" (fraction of a second), while when I sign the same message, it takes at least one order of magnitude more time (1-2 seconds)

The same result can be seen when both signing and encrypting ...

Is this due to that signing a message simply is that much more consuming from an algorithmical point of view, or might this point to an underlaying problem in Bouncy Castle or MimeKit ...?

Logically I would expect encryption to be more "costy" in regards to CPU, but according to what I see when I use these features, signing seems to be at least one order of magnitude more costy when it comes to CPU resources and time ...?

BTW, this is using PGP and GnuPGContext ...

**Comment by jstedfast** [comment]
Honestly I don't know... it would probably be a question for the Bouncy Castle devs.

**Comment by polterguy** [comment]
Thx ... :)
