### ISSUE TITLE
MailboxAddress ToString method only allows encoding using FormatOptions.Default

### ISSUE THREAD

**Issue by superlogical** [jstedfast/MimeKit#208]
see:
https://github.com/jstedfast/MimeKit/blob/master/MimeKit/MailboxAddress.cs#L306

If I try and set the NewLineFormat to Unix it throws:
````csharp
FormatOptions.Default.NewLineFormat = NewLineFormat.Unix;
````

So wondering how I can encode the address with custom FormatOptions. (I'm sending email to Mailgun via HTTP, and I don't think the like DOS style line endings)

**Comment by jstedfast** [comment]
HTTP uses DOS line endings, but I've added a new ToSTring() method that takes a FormatOptions anyway.

**Comment by superlogical** [comment]
Oh didn't know about DOS + Http :)

**Comment by jstedfast** [comment]
FWIW, *all* internet protocols use DOS line endings (e.g. CRLF)

**Comment by jstedfast** [comment]
MimeKit 1.2.18 just released to nuget supports this. I'll be making another 1.3.0-beta in the next few days (if you need dnxcore50)
