### ISSUE TITLE
Content-Disposition did not return a filename

### ISSUE THREAD

**Issue by LeeBear35** [jstedfast/MimeKit#209]
Jeffrey,
You have been busy lately...Hate to add to the list, I encountered and email where the content disposition did not parse out the file name. Here is the header section in question, and the file name wraps, so I do not know if that is the issue. Let me know if you need the email.

------=_NextPart_1426158829-611019761-1491144587
Content-Type: application/octet-stream
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=GALAXY data for PMR as at  
 17.04.13.zip

UEsDBBQAAAAI....

Thank you for this product and the support!

**Comment by jstedfast** [comment]
Is the blank line there in the real email? or is that some sort of c&p error?

**Comment by jstedfast** [comment]
Is it just not getting the "full" filename? or is it not getting any filename at all? My unit tests suggest it works, or at the very least in your case, would get a filename value of "GALAXY data for PMR as at".

**Comment by jstedfast** [comment]
FWIW, parameter values are required to be quoted if they contain spaces, semi-colons, quotes, or any a number of other characters.

**Comment by jstedfast** [comment]
FWIW, this works:

```
Content-Type: application/octet-stream
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=GALAXY data for PMR as at
 17.04.13.zip

UEsDBBQAAAAI....
```

(notice that the wrapped line begins with a space, which is how the parser knows that it is a wrapped header)

This does not:

```
Content-Type: application/octet-stream
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=GALAXY data for PMR as at

17.04.13.zip

UEsDBBQAAAAI....
```

This second example cannot be made to work. There's no way to determine that the line beginning with `17.04.13.zip` isn't meant to be the content.

**Comment by LeeBear35** [comment]
The text is "at \r\n 17.04.13.zip" The header shows the full Content Disposition header, but the file name is not being set.
? a.Headers
{MimeKit.HeaderList}
    Changed: {Method = {Void HeadersChanged(System.Object, MimeKit.HeaderListChangedEventArgs)}}
    Count: 3
    headers: Count = 3
    IsReadOnly: false
    Options: {MimeKit.ParserOptions}
    Suppress: false
    table: Count = 3
? a.Headers[0]
{Content-Type: application/octet-stream}
    Changed: {Method = {Void HeaderChanged(System.Object, System.EventArgs)}}
    Field: "Content-Type"
    Id: ContentType
    Offset: 3069
    Options: {MimeKit.ParserOptions}
    rawField: {byte[12]}
    RawField: {byte[12]}
    RawValue: {byte[27]}
    rawValue: {byte[27]}
    textValue: "application/octet-stream"
    Value: "application/octet-stream"
? a.Headers[1]
{Content-Transfer-Encoding: base64}
    Changed: {Method = {Void HeaderChanged(System.Object, System.EventArgs)}}
    Field: "Content-Transfer-Encoding"
    Id: ContentTransferEncoding
    Offset: 11008
    Options: {MimeKit.ParserOptions}
    rawField: {byte[25]}
    RawField: {byte[25]}
    RawValue: {byte[9]}
    rawValue: {byte[9]}
    textValue: "base64"
    Value: "base64"
? a.Headers[2]
{Content-Disposition: attachment; filename=GALAXY data for PMR as at   17.04.13.zip}
    Changed: {Method = {Void HeaderChanged(System.Object, System.EventArgs)}}
    Field: "Content-Disposition"
    Id: ContentDisposition
    Offset: 11043
    Options: {MimeKit.ParserOptions}
    rawField: {byte[19]}
    RawField: {byte[19]}
    RawValue: {byte[66]}
    rawValue: {byte[66]}
    textValue: "attachment; filename=GALAXY data for PMR as at   17.04.13.zip"
    Value: "attachment; filename=GALAXY data for PMR as at   17.04.13.zip"


I uploaded the attachment ToString() dumped to a file and the Email renamed as text.
[jeffery.txt](https://github.com/jstedfast/MimeKit/files/62861/jeffery.txt)
[email.txt](https://github.com/jstedfast/MimeKit/files/62863/email.txt)

**Comment by jstedfast** [comment]
Are you using the latest version? It should work (and I have a unit test that tests this particular work-around for broken mailers).

I also test it using:

```csharp
var part = (MimePart) MimeEntity.Load (...);
Console.WriteLine ("FileName = {0}", part.FileName);
```

That worked for me using the first example in my comment above.

**Comment by LeeBear35** [comment]
Thank you it was a version issue, I should have checked that.

**Comment by jstedfast** [comment]
no prob, glad it is all working now for you :)
