### ISSUE TITLE
AttachmentCollection.Add (string fileName, ContentType contentType) missing in CoreFX

### ISSUE THREAD

**Issue by BTXAndy** [jstedfast/MimeKit#211]
What's the reason for this?

**Comment by jstedfast** [comment]
I think when I originally started doing the port, I couldn't get it to build when using File.Open.

In any event, it seems to build just fine now, so I've added those API's back.

**Comment by BTXAndy** [comment]
Great thanks!

**Comment by jstedfast** [comment]
I've just published MimeKit 1.3.0-beta4 with this change.
