### ISSUE TITLE
Bringing MimeKit to weird places ... :)

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#212]
In this blog/video I demonstrate how I am using MimeKit for cryptographically secure web service invocations, passing back and forth GPG encrypted and signed MIME messages, being able to create "lambda Web Services", where I pass code from the client to the web service end-point, in a secure manner, and execute Hyperlisp on the server, which is created on the client.

https://phosphorusfive.wordpress.com/2015/12/24/cryptographically-secure-lambda-web-services/

Thought you'd probably be interested in seeing your baby FLYY!! ;)

BTW, you're mentioned in the "About" page of the system installation, at the very top, for all your great support and help :)

Merry X-Mas

**Comment by jstedfast** [comment]
Awesome :)

And Merry Christmas to you, too!
