### ISSUE TITLE
DKIM body hash verification fails

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#213]
Body hash verification fails for some emails which are coming directly from Google servers (signed by Gmail). These are multipart/mixed emails which consist of two mime body parts. The second part is an attachment and the first part is a text/plain part where the mime body part content is null:

Example:
----_com.android.email_0000000000000000
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64
[CR][LF]
----_com.android.email_0000000000000000

MimeKit, while re-assembling the original message body, apparently adds an additional CRLF before the second mime body part, and then calculates the body hash:

Example:
----_com.android.email_0000000000000000
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64
[CR][LF]
[CR][LF]
----_com.android.email_0000000000000000

**Comment by breedbekkikker** [comment]
Thanks, the fix is working fine.

**Comment by jstedfast** [comment]
Good to know :)
