### ISSUE TITLE
Here's another example, more traditional though

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#214]
Showing how I am using MimeKit to send and receive encrypted emails through GMail ...
After about 10 minutes, you can see how I am using MimeKit.

I *phreaking love* MimeKit Jeff!! :)
You've done a marvelous job ... ;)

In fact, I'm even using it to store my password file locally, as a MIME message ... :)

Hope you like it, you're heavily mentioned in the credits part of the system :)

**Comment by jstedfast** [comment]
Glad you are able to make such use of it :)

Do you have a link?
