### ISSUE TITLE
ContentID not populated for attachment

### ISSUE THREAD

**Issue by LeeBear35** [jstedfast/MimeKit#215]
Jeffrey,
The ContentID on the MimeEntity contains the four headers below, but the ContentID is returning null. I was able to work around the issue by getting the header directly.

------=_NextPart_1204600578-302355983-1774213606
Content-Type: image/jpeg
Content-ID: image001.jpg@01CF3E97.1902EE40
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename=image001.jpg

**Comment by jstedfast** [comment]
The problem is that the Content-Id value is supposed to be enclosed in <>'s
