### ISSUE TITLE
DKIM body hash fails for multipart messages without closing boundary

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#218]
MimeKit always adds the closing boundary when reserializing a multipart message, even if the original message body does not contain the closing boundary. Some signed email therefore actually fails DKIM body hash validation.

**Comment by jstedfast** [comment]
Would you be willing to generate a sample message for this issue so that I can add it to my unit tests?

I was actually thinking about this potential issue the other day.

I think what I'll have to do is have the parser set a flag on the Multipart to specify whether an end boundary should be used.

**Comment by jstedfast** [comment]
FWIW, I think S/MIME and PGP/MIME will also be affected by this.

**Comment by breedbekkikker** [comment]
Here is a sample message signed by Gmail which you might want to include in your unit tests.
[email.txt](https://github.com/jstedfast/MimeKit/files/85955/email.txt)

**Comment by jstedfast** [comment]
Awesome, thank you :)

**Comment by jstedfast** [comment]
This should also be fixed in MimeKit 1.2.20
