### ISSUE TITLE
Crash with version with new optimized OrdinalIgnoreCase string comparer

### ISSUE THREAD

**Issue by fcouste** [jstedfast/MimeKit#219]
Hi,

Since last update with the MimeUtils.OrdinalIgnoreCase comparer, i crash in OrdinalIgnoreCase.GetHashCode on return line.
I don't know why, but if i replace with the original StringComparer.OrdinalIgnoreCase all works fine.
Any idea ?

Thanks.

**Comment by jstedfast** [comment]
Is this on Mono or Microsoft's .NET runtime?

**Comment by fcouste** [comment]
On Microsoft .Net.

De : Jeffrey Stedfast [mailto:notifications@github.com]
Envoyé : vendredi 15 janvier 2016 13:05
À : jstedfast/MimeKit <MimeKit@noreply.github.com>
Cc : Frédérick Couste <frederick.couste@metafactory.fr>
Objet : Re: [MimeKit] Crash with version with new optimized OrdinalIgnoreCase string comparer (#219)


Is this on Mono or Microsoft's .NET runtime?

**Comment by fcouste** [comment]
Ok, i found the problem. My project has option "check for arithmetic overflow"  (/Checked) and gethashcode doesn't have the mark "unchecked".

Problem solved with the correction :

    unsafe
			{
				unchecked //Here to disable overflow check
				{
					fixed (char* src = obj)
					{
						int hash1 = 5381;
						int hash2 = hash1;
						char* s = src;
						int c;

						while ((c = s[0]) != 0)
						{
							hash1 = ((hash1 << 5) + hash1) ^ ToUpper(c);

							if ((c = s[1]) == 0)
								break;

							hash2 = ((hash2 << 5) + hash2) ^ ToUpper(c);
							s += 2;
						}

						return hash1 + (hash2 * 1566083941);
					}
				}
			}

But with this Check Overflow option, other functions not protected crash. So, i have to correct all unsafe functions like this, or change project setting to remove this security check.

**Comment by jstedfast** [comment]
This should be fixed now, thanks.
