### ISSUE TITLE
DKIM body hash mimepart with only newline

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#221]
DKIM body hash calculation fails when there is a mimepart with only a newline as content.

Example:
 ----_com.android.email_0000000000000000
 Content-Type: text/plain; charset=utf-8
 Content-Transfer-Encoding: base64
 [CR][LF]
 [CR][LF]
 ----_com.android.email_0000000000000000--

The body hash is calculated over:
 ----_com.android.email_0000000000000000
 Content-Type: text/plain; charset=utf-8
 Content-Transfer-Encoding: base64
 [CR][LF]
 ----_com.android.email_0000000000000000--

While there have been several issues before with reserialization of mimeparts, I was wondering why you do not chose for DKIM to use the raw body and perform the canonicalization on that. Thus using the body as-is without all the hassle of breaking the body up into the mimeparts and then reserialize them to get the original body. Imho this would make body hash calculation more simple with less chance for errors.

**Comment by jstedfast** [comment]
I don't have the raw body, I only have the MIME tree structure and *have* to reserialize.

**Comment by jstedfast** [comment]
This issue should already be fixed in git master, but I have not made a release yet.

**Comment by jstedfast** [comment]
isn't this the same bug as #213 ?

**Comment by jstedfast** [comment]
never mind, I see the difference. I'll test it out and make sure this works.

**Comment by jstedfast** [comment]
This is fixed now.

**Comment by breedbekkikker** [comment]
Thank you very much for your prompt response/fix.

**Comment by jstedfast** [comment]
No prob. Thanks for submitting these bug reports, they are very helpful in ironing out the kinks.

FWIW, this re-serialization logic needs to work for S/MIME and OpenPGP as well, and there's no way I could just stream the complete raw messages through a filter to verify those signatures since it they only apply to subsections of the message.

**Comment by jstedfast** [comment]
I pushed MimeKit 1.2.20 to nuget last night with this fix.
