### ISSUE TITLE
Funny errors after upgrading to 1.2.20 ...

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#222]
Howdy,

I get funny errors when updating to the latest version, 1.2.20. First of all, it won't find the new Import methods on the "PgpSecret/Public-KeyRing" overloads on OpenPGPContext. Secondly, it comes with a warning during compilation that says; "CSC:  warning CS1701: Assuming assembly reference `MimeKit, Version=1.2.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814' matches assembly `MimeKit, Version=1.3.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'. You may need to supply runtime policy"

I've tried to do a clean, removing packages, and adding them again, with no success ...?

**Comment by polterguy** [comment]
For some reasons, my References in my project says in Properties that it is using 1.3.0.0, while my Packages is including 1.2.20. I've tried to delete bin folders, obj folders, removing packages and refetching them, etc, etc, etc, but nothing seems to work ...?

**Comment by jstedfast** [comment]
Somehow the 1.2.20 packages are including the 1.3.0 assembly version. I'll release new nugets with a fix.

**Comment by jstedfast** [comment]
This issue should be fixed now with the MimeKit 1.2.20.2 package. Sorry about that...

**Comment by polterguy** [comment]
No problem :)

**Comment by polterguy** [comment]
Works now :)
