### ISSUE TITLE
Conflict with versions

### ISSUE THREAD

**Issue by shapemetrics** [jstedfast/MimeKit#223]
1.2.20.2 has a conflict of versions. THe message in VS 2015 

"C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed."

The verbose message leaves the message below. Only the new version seems to cause this. It looks like two parts are signed with different versions. 

This reference is not "CopyLocal" because it conflicted with another reference with the same name and lost the conflict.
1>      The ImageRuntimeVersion for this reference is "v4.0.30319".
1>  There was a conflict between "MimeKit, Version=1.2.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814" and "MimeKit, Version=1.3.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814".
1>      "MimeKit, Version=1.2.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814" was chosen because it was primary and "MimeKit, Version=1.3.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814" was not.
1>      References which depend on "MimeKit, Version=1.2.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814" [C:\Users\user\Dropbox\packages\MimeKit.1.2.20.2\lib\net45\MimeKit.dll].

**Comment by jstedfast** [comment]
Clean your build and build again.

You probably installed MimeKit 1.2.20 which versioned MimeKit as 1.3.0 by accident. I published 1.2.20.2 to fix that.

**Comment by shapemetrics** [comment]
Actually it looks like Mailkit references that version explicitly. I was unable to uninstall MimeKit due to the dependency for mailkit. Once I install Mailkit it installs mimekit with a different version.

**Comment by jstedfast** [comment]
Argh. Okay. I'll make a new MailKit package tonight.

**Comment by shapemetrics** [comment]
I updated to the new version but the config for the nuget says to use the lowest available and still says 1.3.0 in the error just as above for the version.

**Comment by jstedfast** [comment]
I'll need more information then, because I can't reproduce the problem locally.

**Comment by jstedfast** [comment]
Never mind, I found the error in my logs. You can ignore it, it chooses MimeKit 1.2.0, so you are fine.

I have no idea where it's getting MimeKit 1.3.0 from because AssemblyInfo.cs has 1.2.0 in it, not 1.3.0.

**Comment by shapemetrics** [comment]
I am removing all references. Cleaning project now.

**Comment by shapemetrics** [comment]
Installing newest versions of mimekit 1.2.20.2 and mailkit 1.2.18 about to compile

**Comment by shapemetrics** [comment]
Resulting error message: is the same as above. It looks to be an error with the msbuild file.

**Comment by shapemetrics** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	

I am looking at it still

**Comment by jstedfast** [comment]
I fixed it locally in my sample project by fixing app.config which had a redirect to 1.3.0

**Comment by shapemetrics** [comment]
That corrected it on my side also. Thank you for that. Awesome app also. :)

**Comment by jstedfast** [comment]
Phew, glad that worked :)

**Comment by shapemetrics** [comment]
Donated a little something for your troubles.

**Comment by jstedfast** [comment]
Wow, thanks!
