### ISSUE TITLE
Removing keypairs from OpenPGPContext

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#225]
Howdy,
I've got this issue when trying to remove keys from the SecretKeyRingBundle property of the GnuPGContext, which is a problem inherited from OpenPGPContext. I've surfed through your otherwise brilliant code, and realised I could implement a private method on my own GnuPGContext class, to access the protected method(s); SaveSecretKeyRingBundle and SavePublicKeyRingBundle

Which is awesome, since it allows me to save the internally used SecretKeyRingBundle, among other things.

The problem I am stuck with now though, is that I cannot seem to find another way to remove keys from this SecretKeyRingBundle property, besides this one from BC; PgpSecretKeyRingBundle.RemoveSecretKeyRing

This method seems to be immutable, returning a NEW PgpSecretKeyRingBundle, with the key you wish to remove removed, while not tampering with the original PgpSecretKeyRingBundle.

Since SecretKeyRingBundle has a private setter (of course, which makes sense), I cannot seem to be able to update SecretKeyRingBundle to the value returned from PgpSecretKeyRingBundle.RemoveSecretKeyRing.

And since I cannot find any methods internally in MimeKit that allows me to remove keys (secret nor public), I am not sure how to be able to remove keys, without duplicating most of the entire OpenPGPContext class in my own code ...?

Would it be feasible to create some sort of support for actually setting the SecretKeyRingBundle property of the OpenPGPContext instance, for instance, such that I can somehow delete keys from my own storage ...?

Alternatively create delete keypair methods internally in OpenPGContext ...?

This way, I can in entirety manage my own keys, and since this is a web app, doing it from GnuPG or GPGTools is of course practically impossible ...

**Comment by jstedfast** [comment]
The PublicKeyRingBundle and SecretKeyRingBundle are public properties with protected setters, not private.

But yea, BouncyCastle's KeyRingBundle APIs seem to be immutable and return new Bundle objects when you add or remove keyrings.

**Comment by jstedfast** [comment]
https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Cryptography/OpenPgpContext.cs#L218

**Comment by polterguy** [comment]
NICE! Sorry, posted too fast. Thx :D
