### ISSUE TITLE
message/rfc822 parts

### ISSUE THREAD

**Issue by madu2003** [jstedfast/MimeKit#226]
Hi ,

I am having problems on how to download Outlook item files. These are basically message/rfc822 parts. In the HtmlPreviewVisitor.cs they are treated as 

		protected override void VisitMessagePart (MessagePart entity)
		{
			// treat message/rfc822 parts as attachments
			attachments.Add (entity);
		}

But how do I save these outlook item files (with .eml extensions) in the files system ?

**Comment by jstedfast** [comment]
`MessagePart`s have a `Message` property which is a `MimeMesage`. You can save the message using any of the `WriteTo()` methods. For example:

```csharp
protected override void VisitMessagePart (MessagePart entity)
{
    entity.Message.WriteTo (filename);
}
```
