### ISSUE TITLE
DKIM fails: loading MimeMessage changes message

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#227]
DKIM Sign and Verify functions lead to incorrect results because MimeKit changes the headers and body in several cases. (The examples are taken from the jwz.mbox.txt file.)

### 1. CRLF is added

For example: an email message with Content-Type multipart/report with a message/rfc822 mimepart:

Original:

```
--A41C7.838631588=_/mm1[CRLF]
Content-Type: message/rfc822[CRLF]
[CRLF]
[headers][CRLF]
[CRLF]
unsubscribe[CRLF]
--A41C7.838631588=_/mm1--[CRLF]
```

After loading:

```
--A41C7.838631588=_/mm1[CRLF]
Content-Type: message/rfc822[CRLF]
[CRLF]
[headers][CRLF]
[CRLF]
unsubscribe[CRLF]
[CRLF]
--A41C7.838631588=_/mm1--[CRLF]
```

BTW, this also occurs in a message like this (even though DKIM is not affected due to body canonicalization):

Original message:

```
From: test@test.test[CRLF]
[CRLF]
test
```

After loading:

```
From: test@test.test[CRLF]
[CRLF]
test[CRLF]
```

### 2. MIME-Version value changes

Original message header:

`MIME-Version: RFC-XXXX[CRLF]`

After loading:

`MIME-Version: 1.0[CRLF]`

### 3. MIME-Version header is added

Original mimemessage part:

```
--Alternative.Boundary.keAvi9O0M2U=8U4XMt[CRLF]
Content-type: message/external-body;[CRLF]
	access-type="X-HTTP";[CRLF]
	host="info.cern.ch";[CRLF]
	port="2784";[CRLF]
	path="/hypertext/WWW/TheProject.html"[CRLF]
Content-Description: Object of type 'message/external-body;[CRLF]
[CRLF]
Content-type: text/X-HTML[CRLF]
[CRLF]
[CRLF]
[CRLF]
[CRLF]
--Alternative.Boundary.keAvi9O0M2U=8U4XMt[CRLF]

```
After loading:

```
--Alternative.Boundary.keAvi9O0M2U=8U4XMt[CRLF]
Content-type: message/external-body;[CRLF]
	access-type="X-HTTP";[CRLF]
	host="info.cern.ch";[CRLF]
	port="2784";[CRLF]
	path="/hypertext/WWW/TheProject.html"[CRLF]
Content-Description: Object of type 'message/external-body;[CRLF]
[CRLF]
Content-type: text/X-HTML[CRLF]
MIME-Version: 1.0[CRLF]
[CRLF]
[CRLF]
[CRLF]
[CRLF]
--Alternative.Boundary.keAvi9O0M2U=8U4XMt[CRLF]
```

This also occurs in the email message headers:

Original email message headers:

```
From: nsb@thumper.bellcore.com[CRLF]
Date: Fri, 29 Nov 91 07:13:39 EST[CRLF]
Subject: GIF image (1/3)[CRLF]
Content-type:  message/partial; number=1; total=3; id=foobar[CRLF]
```

After loading:

```
From: nsb@thumper.bellcore.com[CRLF]
Date: Fri, 29 Nov 91 07:13:39 EST[CRLF]
Subject: GIF image (1/3)[CRLF]
Content-type:  message/partial; number=1; total=3; id=foobar[CRLF]
MIME-Version: 1.0
```

**Comment by jstedfast** [comment]
FWIW, I'd prefer separate issue reports per bug so that it is easier to track. In my experience, reporting multiple bugs in the same report ends up causing confusion.

That said, these should all be fixed now.

**Comment by breedbekkikker** [comment]
Thanks a lot!
