### ISSUE TITLE
CRLF is added when loading MimeMessage

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#228]
Message body is changed by MimeKit; DKIM Sign and Verify functions are affected. (The example is taken from the jwz.mbox.txt file.)

Original message and the message after loading are attached. 

The CRLF's on lines 43, 55, 64 and 72 in after_load.txt  are added.

[original.txt](https://github.com/jstedfast/MimeKit/files/119314/original.txt)
[after_load.txt](https://github.com/jstedfast/MimeKit/files/119315/after_load.txt)

**Comment by breedbekkikker** [comment]
Thanks!

**Comment by jstedfast** [comment]
I just released MimeKit 1.2.21 with these fixes to nuget.org
