### ISSUE TITLE
Message body is lost if the headers are not properly terminated

### ISSUE THREAD

**Issue by breedbekkikker** [jstedfast/MimeKit#229]
Message body is changed by MimeKit. (The example is taken from the jwz.mbox.txt file.)

Original message and the message after loading are attached. 

Lines 22 and 31-42 from original.txt are not present anymore in after_load.txt.

[original.txt](https://github.com/jstedfast/MimeKit/files/119337/original.txt)
[after_load.txt](https://github.com/jstedfast/MimeKit/files/119338/after_load.txt)

**Comment by jstedfast** [comment]
This is going to be a real pain to fix and I'm honestly tempted to close this as WONTFIX because really the message is garbage that the parser did its best to deal with :-\

**Comment by breedbekkikker** [comment]
Yes I understand this would be quite some work to deal with. 

I hope you don't mind me opening issues for these kind of findings anyway... Thanks!

**Comment by jstedfast** [comment]
I don't mind :-)

I actually prefer they get reported.
