### ISSUE TITLE
How to get attachments from winmail.dat file?

### ISSUE THREAD

**Issue by DevinvN** [jstedfast/MimeKit#234]
I read in #50 that MimeKit supports retrieving attachments from a winmail.dat file, and was wondering how this is done. Is there any example for this?

**Comment by jstedfast** [comment]
The first thing you'll need to do is locate the tnef attachment itself (which will be contained by a `TnefPart`), which will probably look something like this:

```csharp
foreach (var tnef in message.BodyParts.OfType (TnefPart)) {
    foreach (var attachment in tnef.ExtractAttachments ()) {
        // do your thing.
    }
}
```

See Also:
http://www.mimekit.net/docs/html/M_MimeKit_Tnef_TnefPart_ExtractAttachments.htm
http://www.mimekit.net/docs/html/T_MimeKit_Tnef_TnefPart.htm

**Comment by nadeemkhoury** [comment]
Hi, 
I'm getting "Attempted to read past the end of the stream exception when trying to ExtractAttachments.  I tried several MimeMessages. It locates the TnefPart successfully, but when Extracting attachments or converting to message using ConvertToMessage method it throws the same exception. Any help please ?

**Comment by jstedfast** [comment]
I'll need a lot more information. This works reliably in the unit tests so I don't know what could be causing your issue unless your tnef attachments are corrupt/truncated.

**Comment by dave0292** [comment]
What about if one of the inner attachments from the winmail.dat is an attached "msg" email file? Im not being able to cast it as another TnefPart, neither a rfc822 MessagePart so im not being able to extract the attachments from there.

**Comment by jstedfast** [comment]
@dave0292 can you get me a test case?

**Comment by dave0292** [comment]
I need to modify the content and name of some attachments, but when the TNEF forma is used in Outlook I can not access to the files that are inside a msg attachment and modify them. The reason is why TnefPart does not support writing to the content?

**Comment by jstedfast** [comment]
I haven't implemented writing because it's just a complex data format that didn't seem like it'd be worth the effort. I figure far more people want to extract stuff than encode it.

**Comment by dave0292** [comment]
That's what I thought when I did not find any TnefWriter class and after modifying the content of some TnefParts but not seeing any changes in the message. Thanks for confirming it, you have done an amazing work with the library.
