### ISSUE TITLE
Merge/internalize custom BouncyCastle

### ISSUE THREAD

**Issue by dnauck** [jstedfast/MimeKit#235]
Follow up to issue: jstedfast/MailKit#317

I was wrong with the last issue, the problem is MimeKit, not MailKit.

I'm using the .NET 4.5 profile and your nuget package packs a custom build of BouncyCastle with it.

See: https://github.com/jstedfast/MimeKit/blob/master/nuget/MimeKit.nuspec#L106

This will add your custom BouncyCastle assembly to my project every time on a `nuget` and/or `paket` operation and breaks my build (as there're now 2 reference to the "same" assembly).

So please:

* internalize your bouncy castle build
* or just reference the official BouncyCastle nuget package for .net4.x (as you do with `Portable.BouncyCastle` on the portable profiles)

**Comment by jstedfast** [comment]
That's the plan, but BouncyCastle has not yet released 1.8.x as a nuget package so I can't do that until they do.

https://www.nuget.org/packages/BouncyCastle/

The latest version on nuget.org is 1.7.1

**Comment by dnauck** [comment]
Hi,

nuget.org was updated to version 1.8.1

It would be nice if you could switch to it soon.

Thank you very much.

**Comment by jstedfast** [comment]
I've updated the github repo to use the nugets. Sadly the Android and iOS versions are still not included with the official BouncyCastle nuget :(
