### ISSUE TITLE
Conflict with dnx core 5.0 backgroundworker

### ISSUE THREAD

**Issue by masoudnoursaid** [jstedfast/MimeKit#240]
HI 

I am using mimekit 1.3.0-beta7 in a nuget package manager for send an email by attachment.

then I use sender package in another project that use dnx core 5.0. in this project I use background worker. after add emailer to this project I get error in use back ground worker . 

can you help me for solve this issue.

![2016-05-07_20-26-59](https://cloud.githubusercontent.com/assets/16714655/15093309/19df16d8-1499-11e6-9d4c-4e632144abdd.jpg)

**Comment by jstedfast** [comment]
Well, based on your screenshot, it looks like BackgroundWorker doesn't exist for DNX Core 5.0 so you should go report a problem with their packages.

I don't see what this has to do with MailKit.
