### ISSUE TITLE
Amazone SES exceptions

### ISSUE THREAD

**Issue by jbarbara** [jstedfast/MimeKit#241]
When using Amazon SES it will throw an exception using sendraw with a new MimeKit message, if there are only Bcc addresses.

SES(maybe others?) doesn't like a blank 'To' header, if I manually remove that header after MimeKit message creation it works.

Fix: make default constructor NOT add 'To' header by default, only when To addresses are added.

**Comment by jstedfast** [comment]
Fixed.
