### ISSUE TITLE
Building Messages with Attached Messages

### ISSUE THREAD

**Issue by aluitink** [jstedfast/MimeKit#243]
Hi, I'm using MimeKit to build MIME messages from another dataset.

I need to be able to create a message with multiple levels of attached messages and attachments.

Can you provide me with an example for adding a MimeMessage as an attachment to another MimeMessage?

Thank you!

**Comment by aluitink** [comment]
It kind of appears the only way to attach a message to another message is to generate the sub message as a MimeMessage and stream the data into a MimePart's ContentObject.

Is there a less memory intensive way to accomplish this? Ideally you would build up the object hierarchy and attach streams for large parts, then output it to a stream. I'm afraid if I happen across a large message I'd have to put it into a string to add it as an attachment.

**Comment by jstedfast** [comment]
I have to run so I can't provide a more in-depth response atm, but take a look at `MessagePart` (which is a `MimeEntity` subclass specifically designed to contain `MimeMessage` objects and represents a `message/rfc822`.

**Comment by jstedfast** [comment]
Another thing you may find useful (although in general I think you are being overly concerned with memory usage which I'm 99% sure you will not find to be an issue in practice) is that the `persistent` argument that you'll find in the `MimeMessage.Load()` and the `MimeEntity.Load()` overloads can be used to tell the parser not to load the content into memory.

This means that you can do something like this:

```csharp
using (var stream = File.OpenRead ("attached-message.eml")) {
    var attachedMessage = MimeMessage.Load (stream, true);
    var rfc822 = new MessagePart { Message = attachedMessage };
    var multipart = new Multipart ("mixed");
    var message = new MimeMessage ();

    multipart.Add (new TextPart ("plain") { Text = "This is the message body..." };
    multipart.Add (rfc822);

    message.Body = multipart;

    message.WriteTo ("message.eml");

    // or...

    smtpClient.Send (message);
}
```

**Comment by aluitink** [comment]
This is helpful! I'm concerned about memory because I'll be converting
40+TB of mail to MimeFormat and there is no telling how large the
bodies/attachments will be.

Thank you for being so quick to respond! I believe we have spoke once on a
Reddit post regarding writing an NNTP client.

**Comment by jstedfast** [comment]
No prob. And yea, I do recall talking to you about an NNTP client on reddit :)
