### ISSUE TITLE
Reading TNEF APPTIME is not correct

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MimeKit#245]
Hi... just found a little bug. The way you read apptime and systime in your tnef reader should be like this.
You now read apptime and systime as dates from 1-1-1601 and that is only for the systime and not for apptime. 

APPTIME: 8 bytes; a 64-bit floating point number in which the whole number part represents the number of days since December 30, 1899, and the fractional part represents the fraction of a day since midnight

                    case PropertyType.PT_APPTIME:
                        var oaDate = BitConverter.ToDouble(Data, 0);
                        return DateTime.FromOADate(oaDate);
                        
                    case PropertyType.PT_SYSTIME:
                        var fileTime = BitConverter.ToInt64(Data, 0);
                        return DateTime.FromFileTime(fileTime);

**Comment by jstedfast** [comment]
Thanks!
