### ISSUE TITLE
I found a bug with message mail validation

### ISSUE THREAD

**Issue by adam-prohack** [jstedfast/MimeKit#246]
Message in format "example@" is valid for sender, but I thing that this format is incorrect.

**Comment by jstedfast** [comment]
I don't understand what you mean. Can you give me an example? Is this when parsing? Or writing stuff out? Or what?

**Comment by jstedfast** [comment]
Any update? MimeKit does not have an email address validator, so I really have no idea what you mean.

**Comment by jstedfast** [comment]
I'm going to close this until you can explain the issue
