### ISSUE TITLE
fetch list of email id

### ISSUE THREAD

**Issue by hiteshamipara** [jstedfast/MimeKit#247]
when compose mail than get list of email id in To , Cc, Bcc field which will save on contact or resently use for sending mail.

so how to get email list using Mimikit.

i can use InternetAddressList and MailBoxAddress but it will not work for me.

so how can solve this.

**Comment by jstedfast** [comment]
```csharp
foreach (var mailbox in message.To.Mailboxes) {
    Console.WriteLine ("email id = {0}", mailbox.Address);
}
