### ISSUE TITLE
Problem saving PDF file

### ISSUE THREAD

**Issue by XanatekJustin** [jstedfast/MimeKit#249]
I have a MIME file (not an e-mail) that has a multipart body to it. One of the parts is xml while the other is Application\PDF. When trying to save the PDF, it will not open. I am probably just not doing it correctly (as a file saves, but Adobe says that the file is corrupt when trying to open it). 

I am using the following code: (NOTE: In this snippet, I am simply retrieving the information from the file and then saving it to a database. I later extract the data from the database and create the file. I know it is not the saving to/from the DB that is the problem as that has been thoroughly tested. It is in this method that is causing my problem.)

            foreach (var part in _mimeMessage.BodyParts)
            {
                if (part is MimePart)
                {
                    var p = part as MimePart;

                    if (p.ContentId == name)
                    {
                        using (var stream = new System.IO.MemoryStream())
                        {
                            p.ContentObject.WriteTo(stream);

                            return stream.ToArray();
                        }
                    }
                }
            }

Is there something I am missing in doing this?

**Comment by jstedfast** [comment]
Use `p.ContentObject.DecodeTo(stream);`

**Comment by XanatekJustin** [comment]
I swapped that in there and tested again. It is still doing the same thing. It will create it, but Adobe is not able to read it.

**Comment by jstedfast** [comment]
Then the attachment data is corrupt.

**Comment by XanatekJustin** [comment]
Unfortunately, I know it's not. I used a different Mime parser in the past, and it was able to work with the particular attachments. I wanted to switch to Mimekit because the other was not handling all attachments properly, but this one it was. 

Would it help if I uploaded the file I am working with? I am not sure where. It could be just that I do not have a proper understanding of the files I am working with also.

**Comment by jstedfast** [comment]
Sure. You can copy & paste it into [Gist](https://gist.github.com) and then send me the link.

**Comment by XanatekJustin** [comment]
https://gist.github.com/XanatekJustin/15b14119d369b469dbe389010f0174e7

If that doesn't work, let me know. I made it private, but I could make it public for you to view as well.

**Comment by jstedfast** [comment]
Somehow your PDF attachment is encoded using base64 twice, so you'll need to decode it twice.

```csharp
foreach (var attachment in message.BodyParts.OfType<MimePart> ()) {
    if (attachment.ContentId != "ClaimActivity1.PDF")
        continue;

    using (var stream = File.Create (attachment.ContentId)) {
        using (var filtered = new FilteredStream (stream)) {
            filtered.Add (DecoderFilter.Create ("base64"));
            attachment.ContentObject.DecodeTo (filtered);
        }
    }
}
```

**Comment by XanatekJustin** [comment]
That was exactly what I needed. Thank you for the help. I could not figure out how to get that decoded properly. I knew there had to be a way. 

Again - thank you very much!
