### ISSUE TITLE
Improvement: Make AddSecureMimeCapabilities in SecureMimeContext.cs protected virtual

### ISSUE THREAD

**Issue by Tornhoof** [jstedfast/MimeKit#254]
Hello,
I'm trying to handle a buggy smime client (not-email related) who can't handle sMIMECapabilities attributes in the signature, so currently I'm deriving from the SecureMimeContext and replacing the Sign methods with an implementation which does not call AddSecureMimeCapabilities.
It would be great if you would make that method protected virtual, so I can disable adding this default attribute. I know the rfc recommends addding this attribute, but it does say so for other attributes which are not in by default (e.g SigningTime).

**Comment by jstedfast** [comment]
How does it not support this????? WTF?

**Comment by jstedfast** [comment]
I've been thinking this over and I don't think I'm going to add this, it just feels like a hack.
