### ISSUE TITLE
Additional Constructor for DkimSigner to accept key as a stream

### ISSUE THREAD

**Issue by j055** [jstedfast/MimeKit#255]
Hi

It would be nice to have a another constructor for the DkimSigner to allow a stream:

```public DkimSigner (Stream key, string domain, string selector)```

I'd like to be able to load the key file from some cloud storage location without the need to implement the code to create the AsymmetricKeyParameter.

Does that sound reasonable?
Many thanks
Andrew

**Comment by jstedfast** [comment]
Seems reasonable.
