### ISSUE TITLE
Use better alternatives to subtype parameter for TextPart

### ISSUE THREAD

**Issue by ssg** [jstedfast/MimeKit#256]
As a first time user of the API I'm caught by surprise about the `subtype` field of `TextPart` when composing email. I had to find the documentation about it to understand what I need to pass. That parameter is a string which:

1. Prevents discovery of available/supported types using IntelliSense
2. Prone to typos hence hard to detect errors, only discoverable very late in the game.
3. Assumes that the developer is knowledgeable about correct representation of MIME types.

I would be much more comfortable with specific classes like `HtmlPart`, `PlaintextPart` that just calls `TextPart` with correct the value. That would be backwards compatible and anyone who wants a custom MIME type could still use a `TextPart` constructor.

Another approach would be using `ContentType`s throughout the code instead of strings anywhere. So we could use `ContentType.TextPlain` (or `TextContentType.Plain`, to narrow down options) instead of "plain" and use a new ContentType instance whenever a custom MIME type is needed. That would reduce construction overhead of `ContentType`s for MIME entries since they would be shared. And they would be easily discoverable, prevent typos etc. But backwards compatibility would be a problem.

Any of these improvements in the library would make whole onboarding experience much smoother and reduce the maintenance cost for the code using it.

**Comment by jstedfast** [comment]
In general, I would probably recommend using `BodyBuilder` to construct messages unless you understand the various MIME types.

I do agree, however, that strings are generally the wrong approach for these sorts of things, but in this particular case it's hard not to use strings due to the fact that the subtype can be just about anything (when considering x-* types, especially).

I'm not sure if it would make sense to add `TextHtml` and `TextPlain` classes (convention has been to use the mime-type as the class name) or not since the only value it would provide is not having to pass a subtype string argument.

What if I just expand the API docs to mention "plain" and "html" as being the most common values?

**Comment by ssg** [comment]
My scenario is: "Compose email to single recipient with single HTML content". BodyBuilder seemed more suited to complicated building operations. That's why I resorted to creating a TextPart. I'll check BodyBuilder out again.

If Intellisense shows "plain" and "html" as common values for subtype it would definitely be an improvement. It wouldn't solve typos, detecting issues during runtime etc. It's your call, I'm unaware of potential side-effects since I don't know the ecosystem. :)

**Comment by jstedfast** [comment]
> My scenario is: "Compose email to single recipient with single HTML content".

Ah, okay. In that case you probably made the right choice.

What I've done is to improve the docs for the .ctors that take a string subtype argument (complete with a web link to the list of registered text/* mime-types) as well as adding a new .ctor that takes a `TextFormat` enum argument with the common values.

**Comment by jstedfast** [comment]
I think that should make us both happy?

**Comment by ssg** [comment]
Yeah certainly. I appreciate any improvement. A little reminder though: enums have miniscule conversion overhead to text values. Separate classes for separate types don't have that problem. It's all good though. Thanks for responding so quickly to this, good luck!
