### ISSUE TITLE
Spurious newline in body parsing certain messages

### ISSUE THREAD

**Issue by duncansmart** [jstedfast/MimeKit#259]
For the attached email, using v1.4.0 `MimeMessage.Load()` and then reading the `HtmlBody` results in an unexpected newline appearing in the body.

If you see at line 192:

	r><tr valign=3D"top">=0D=0A				<td>SERVER_NAME</td><td>example-ab=
	cd.azurewebsites.net</td>=0D=0A			</tr><tr valign=3D"top">=0D=0A	=

Results in:

                </tr><tr valign="top">
                    <td>SERVER_NAME</td><td>example-ab
    cd.azurewebsites.net</td>
                </tr><tr valign="top">

Not there should NOT be a newline `\n` in `example-abcd.azurewebsites.net`.

This is VERY difficult to repro because adding or removing a SINGLE character at any point before line 192 results in the bug disappearing! This suggests it's due to the wrap being at some sort of buffer boundary.

Even if I switch the `Content-Type` to `text/plain` and inspect the `TextBody` it's the same issue.

FYI: the code I'm using:

    var mimeMsg = MimeMessage.Load(@"..\..\MimeKitNewlineBodyBug.eml.txt");
    var lines = mimeMsg.HtmlBody.Split(new[] { "\r\n" }, StringSplitOptions.None);
    Console.WriteLine(lines[161]);
    if (!lines[161].Contains("example-abcd.azurewebsites.net"))
    {
        Console.WriteLine();
        Console.WriteLine("FAIL: didn't see \"example-abcd.azurewebsites.net\"");
    }

[MimeKitNewlineBodyBug.eml.txt](https://github.com/jstedfast/MimeKit/files/365729/MimeKitNewlineBodyBug.eml.txt)

**Comment by duncansmart** [comment]
Looking at your very last commit f1a582b - could be fixed by this?!

**Comment by jstedfast** [comment]
Yes, I'm pretty sure that patch fixes this. Could you verify?

**Comment by duncansmart** [comment]
Yep, just cloned and built f1a582b and ran the test, and it now works! Thanks! Looking forward to you updating the nuget :-)

**Comment by jstedfast** [comment]
I'll be making a new release this weekend (likely on Saturday).

**Comment by jstedfast** [comment]
I've released MimeKit 1.4.1 with a fix for this to nuget.org
