### ISSUE TITLE
header encoding issue

### ISSUE THREAD

**Issue by unosbaghaie** [jstedfast/MimeKit#260]
using this code in c# 

`var message = new MimeMessage();
...
 message.Headers.Add("List-Unsubscribe", string.Format("<mailto:info@myDomain.com?subject=unsubscribe>,<http://myDomain.com/Unsubscribe/unsubscribeNewsletter?email={0}&userId={1}>", email, UserId));`

I generate a header and add it to message 

then in gmail I see the below text when I see the original .

`List-Unsubscribe: 
 =?us-ascii?q?=3Cmailto=3Ainfo=40myDomain=2Ecom=3Fsubject=3Dunsubscribe=3E=2C=3Chttp=3A=2F=2FmyDoma?=
 =?us-ascii?q?in=2Ecom=2FUnsubscribe=2FunsubscribeNewsletter=3Femail=3Dunos=2Ebm65=40gmai?=
 =?us-ascii?q?l=2Ecom&userId=3D16=3E?=`

 I saw the original code of some providers is something like 

`List-Unsubscribe: <mailto:unsubscribe345345345@sendSth.com?body=unsubscribe>, <http://track.domain.com/link/c/xNDQzMDYmYz1mNHc0JmU9MTkyOCZi=.D_Ws3vz_wkc9W2P7>`

Is my original code correct ?
If not, is this related to encoding? 

By the way, when I want to send the message I use 

` message.Body.Prepare(EncodingConstraint.EightBit);`

Thank you

**Comment by jstedfast** [comment]
Why is this wrong? MimeKit encodes the header because it's too long to fit on a single line and cannot be folded without breaking in the middle of a word token.

This is not related to message.Body.Prepare().

**Comment by jstedfast** [comment]
Note: if you put a space after the comma, it likely won't encode the first url. The second url will depend on the length of the email and userId strings, but most likely they'll be long enough to make the second url over 77 characters (lines are supposed to wrap at 78 characters, but wrapped lines have to start with a whitespace, meaning there are only 77 characters of usable space per line).

**Comment by unosbaghaie** [comment]
It wasn't appeared in gmail menu, which I thought it is related to encoding, but after some search I got it is because of reputation in gmail and it will be appeared when gmail is sure our reputation is okey 

Thanks man
