### ISSUE TITLE
Failed to Parse Message Headers

### ISSUE THREAD

**Issue by Beatsleigher** [jstedfast/MimeKit#261]
Hey there,

We're currently having issues with MimeKit parsing e-mails.
We're using MimeKit to parse the e-mails so they can be indexed with Lucene.

These are the logs we're getting:
[MailProcessor] [4:00 PM] [Info] Beginning to process, and index e-mails...
[MailProcessor] [4:00 PM] [Info] Beginning indexing of emails...
[MailProcessor] [4:18 PM] [Info] Indexing email 0 of 161 (0%)
[MailProcessor] [4:18 PM] [Error] An exception has occurred while processing the e-mails!
[MailProcessor] [4:18 PM] [Error] Error details:
[MailProcessor] [4:18 PM] [Error] 	Failed to parse message headers.

[MailProcessor] [4:18 PM] [Error] 	  at MimeKit.MimeParser.ParseMessage (System.Byte* inbuf) [0x00077] in <filename unknown>:0 
[MailProcessor] [4:18 PM] [Error] 	  at MimeKit.MimeParser.ParseMessage (CancellationToken cancellationToken) [0x00023] in <filename unknown>:0 
[MailProcessor] [4:18 PM] [Error] 	  at MimeKit.MimeMessage.Load (MimeKit.ParserOptions options, System.IO.Stream stream, Boolean persistent, CancellationToken cancellationToken) [0x00025] in <filename unknown>:0 
[MailProcessor] [4:18 PM] [Error] 	  at MimeKit.MimeMessage.Load (MimeKit.ParserOptions options, System.IO.Stream stream, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
[MailProcessor] [4:18 PM] [Error] 	  at De.Nwt.MailArchive.MailProcessor.DirectoryDeamon+<ProcessMailsAsync>c__async1.<>m__0 () [0x0012f] in /Users/simoncahill/Projects/MailArchive/MailProcessor/Src/Classes/DirectoryDeamon.cs:348 
[MailProcessor] [4:18 PM] [Error] The error occurred in the method ParseMessage

The email files have been taken directly from our email server, so they should have the correct formatting (they also contain MIME-Version, etc).

I'll send you the e-mail in question via e-mail (I'm guessing jeff@xamarin.com is still valid?)

Any help with this issue would be much appreciated!

**Comment by jstedfast** [comment]
I was unable to reproduce the error based on the message you sent to me via email. The exception you got typically only happens when an EOF is reached before it finds a blank line terminating the header block.

You might just need to update your MimeKit to the latest version or something.

**Comment by Beatsleigher** [comment]
I'm using the latest version, pulled it from NuGet.
The error, however, still persists.

**Comment by jstedfast** [comment]
Does this mean that perhaps the file is incomplete when MimeKit goes to parse it in your case?

**Comment by totszwai** [comment]
I am getting the same issue.
The signed and encrypted email was sent from Mac Mail.

The raw header looks like this, with my email address removed.

`
Return-Path: <hello@world.com>
X-Original-To: hello@world.com
Delivered-To: hello@world.com
Received: from mail.world.com (blah.world.com [192.168.105.100])
	by sup.world.com (Postfix) with ESMTP id EDAAC1E2985
	for <hello@world.com>; Fri, 11 Nov 2016 15:05:22 -0500 (EST)
Received: from localhost (localhost.localdomain [127.0.0.1])
	by mail.world.com (Postfix) with ESMTP id EB04D60F58
	for <hello@world.com>; Fri, 11 Nov 2016 15:05:22 -0500 (EST)
X-Virus-Scanned: amavisd-new at world.com
X-Spam-Flag: NO
X-Spam-Score: -14.898
X-Spam-Level:
X-Spam-Status: No, score=-14.898 tagged_above=-999 required=6
	tests=[AM.WBL=-10, ALL_TRUSTED=-1, ENCRYPTED_MESSAGE=-1,
	RP_MATCHES_RCVD=-2.899, TVD_SPACE_RATIO=0.001] autolearn=unavailable
Received: from mail.world.com ([192.168.105.100])
	by localhost (mail.world.com [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id 65dRvkGnE1tI for <hello@world.com>;
	Fri, 11 Nov 2016 15:05:22 -0500 (EST)
Received: from hello@world.com (hello@world.com [192.168.6.71])
	(using TLSv1 with cipher DHE-RSA-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by mail.carillon.ca (Postfix) with ESMTPSA id B5E0260F54
	for <hello@world.com>; Fri, 11 Nov 2016 15:05:22 -0500 (EST)
From: hello <hello@world.com>
Content-Type: application/pkcs7-mime; name=smime.p7m; smime-type=enveloped-data
Content-Transfer-Encoding: base64
Subject: ksdhkshj
Message-Id: <5585C7E0-6978-4B36-81B6-E8F6297572F0@world.com>
Date: Fri, 11 Nov 2016 15:05:21 -0500
To: hello <hello@world.com>
Mime-Version: 1.0 (Mac OS X Mail 9.3 \(3124\))
Content-Disposition: attachment; filename=smime.p7m
X-Mailer: Apple Mail (2.3124)

MIAGCSqGSIb3DQEHA6CAMIACAQAxggG8MIIBuAIBADCBnzCBiDELMAkGA1UEBhMCVVMxJzAlBgNV
BAoTHkNhcmlsbG9uIEZlZGVyYWwgU2VydmljZXMgSW5jLjEiMCAGA1UECxMZQ2VydGlmaWNhdGlv
biBBdXRob3JpdGllczEsMCoGA1UEAxMjQ2FyaWxsb24gRmVkZXJhbCBTZXJ2aWNlcyBQSVYtSSBD
...
...
mUbcx7WvBBhBrBKFXv6jRSqC4KsQ2WklUctlWl8ON0gEMM9Tu8md44tjI32SCJEK2x5CcxcCTgNX
VdTdvJx4gnzS5gH+T9tdiWnlHeyC7UzGKQQIWLgNHS2HpxYECKEdKMu4quQpAAAAAAAAAAAAAA==

`

**Comment by totszwai** [comment]
Actually, it failed the exact same way for encrypted and not signed message.

**Comment by jstedfast** [comment]
It's not failing for me. Are you sure you have reset the stream to the beginning of the stream before parsing it?

**Comment by MeiRose** [comment]
Hi, I have gotten this same error message "Failed to parse message headers.".  I used MIMEKIT in my windows service.  However if I use it as a console application, it works fine.  Please advice.

**Comment by jstedfast** [comment]
@MeiRose make sure to reset the stream (i.e. `stream.Position = 0;`) before passing to MimeKit's parser.
