### ISSUE TITLE
wrong certificate selected by WindowsSecureMimeContext in mailkit 1.4.1

### ISSUE THREAD

**Issue by doreille** [jstedfast/MimeKit#262]
WindowsSecureMimeContext don't select the right certificate from the Windows store. 

Fixed by replacing at the lines 265 and  373
if (address.Equals (mailbox.Address, StringComparison.InvariantCultureIgnoreCase))
by
if (!address.Equals (mailbox.Address, StringComparison.InvariantCultureIgnoreCase))

**Comment by jstedfast** [comment]
Oops! Thanks for reporting this!

**Comment by jstedfast** [comment]
1.4.2 packages have been released
