### ISSUE TITLE
Does NTLM authentication mechanisms works correctly?

### ISSUE THREAD

**Issue by SuhovDE** [jstedfast/MimeKit#263]
Hello,

I tried to get email using Pop3Client, but received the following exception:

> MailKit.Net.Pop3.Pop3CommandException POP3 server did not respond with a +OK response to the STAT command.  

POP3 log contains the following lines:
```
Connected to pop://xxx.xxx.xxx.xxx:110/
S: +OK Microsoft Exchange Server 2003 POP3 server version 6.5.7638.1 (domain.net) ready.
C: CAPA
S: +OK Capability list follows
S: TOP
S: USER
S: PIPELINING
S: EXPIRE NEVER
S: UIDL
S: SASL NTLM
S: .
C: AUTH NTLM
S: +OK
C: CAPA
S: -ERR Logon failure: unknown user name or bad password.
C: STAT
S: -ERR Command is not valid in this state.
C: QUIT
S: +OK Microsoft Exchange Server 2003 POP3 server version 6.5.7638.1 signing off.
```
Is it correct that client send CAPA as answer for +OK? I thought, that it should send Base 64 encoded Type 1 message instead.

FYI: After I cleared AuthenticationMechanisms property, the client was authenticated correctly, but using USER Mechanisms.

**Comment by jstedfast** [comment]
That should not happen.

Can you refile this under MailKit? This bug doesn't really belong under MimeKit (which is just a MIME parser).

Thanks.

**Comment by SuhovDE** [comment]
Yes, sorry. I have created the same issue ticket for MailKit

**Comment by jstedfast** [comment]
Thanks :)
