### ISSUE TITLE
Is it possible to decrypt, decompress and save the content of an ApplicationPkcs7Mime without loading into memory?

### ISSUE THREAD

**Issue by jseekamp** [jstedfast/MimeKit#265]
I have a 1.4GB mime message that is encrypted and compressed. Is it possible to use mimekit to stream the content to disk without loading the entire thing into memory?

My really quick an dirty code looks like this. Eventually I will use the MimeIterator to iterate through parts. This seems to load the decompressed data into memory.

```
var decrypted = context.Decrypt(part.ContentObject.Stream) as ApplicationPkcs7Mime;
var multipartSigned = context.Decompress(decrypted.ContentObject.Stream) as MultipartSigned;
var content = multipartSigned[0] as MimePart;

using (var contentStream = new FileStream(Path.Combine(Path.GetDirectoryName(path), content.FileName), FileMode.Create))
{
	content.ContentObject.Stream.CopyTo(contentStream);
}
```

**Comment by jstedfast** [comment]
To answer your question quickly: no, it's not possible.

But I also feel obligated to inform you that your code is broken :(

1. In general, don't use the `context` directly
2. Don't directly use `part.ContentObject.Stream` - you have no idea whether it is (base64 / quoted-printable / uuencode) encoded or not. Use the `Open()` method or the `DecodeTo()` method, both will apply on-demand decoding of the content stream.

Of course, if you follow rule 1, you won't need to follow rule 2 to do decompress/decrypt stuff.

`part` should already be an `ApplicationPkcs7Mime` object, so just cast to that and then use the `Decrypt()` method on that.

Likewise, when decompressing, just use `decrypted.Decompress(context)`.

Then, once you get the `content` of the `MultipartSigned`, you want to `DecodeTo()` method.

Your code should look like this:

```csharp
var decrypted = part.Decrypt (context) as ApplicationPkcs7Mime;
var multipartSigned = decrypted.Decompress (context) as MultipartSigned;
var content = multipartSigned[0] as MimePart;

using (var contentStream = new FileStream(Path.Combine(Path.GetDirectoryName(path), content.FileName), FileMode.Create))
{
    content.ContentObject.DecodeTo(contentStream);
}
```

**Comment by jstedfast** [comment]
I guess you might have been trying to bypass ApplicationPkcs7Mime's logic that decodes into a memory stream first...

In that case, maybe this would be an improvement:

```csharp
using (var encryptedStream = part.ContentObject.Open ()) {
    var pkcs7 = context.Decrypt (encryptedStream);

    using (var decryptedContent = File.Create (File.GetTempFileName ())) {
        pkcs7.ContentObject.DecodeTo (decryptedContent);
        decryptedContent.Seek (SeekOffset.Origin, 0);

        signed = context.Decompress (decryptedContent) as MultipartSigned;
        var content = signed[0] as MimePart;

        using (var stream = File.Create (...))
            content.ContentObject.DecodeTo (stream);
    }

**Comment by jstedfast** [comment]
FWIW, I've taken a quick look at the BouncyCastle API's and I'm not sure there's a straight-forward way of getting back a stream from them that is decrypted/decompressed on-the-fly.

I looked because I thought, well, maybe I could add `context` methods like `DecompressTo (Stream input, Stream output)` and `DecryptTo (Stream input, Stream output)`, but that doesn't seem to be as trivial as I had hoped.

**Comment by jseekamp** [comment]
I was looking at the same and found which returns a stream `Org.BouncyCastle.Cms.RecipientInformation.GetContentStream(ICipherParameters key)`

MimeKit currently calls `Org.BouncyCastle.Cms.RecipientInformatin.GetContent(ICyperParameters key)` which returns a byte array.

For decompression there is `Org.BouncyCastle.Cms.CmsCompressedDataParser.GetContent()` which also returns a stream.

Am I missing something?

**Comment by jseekamp** [comment]
I was able to relieve the memory pressure by adding the following to `SecureMimeContext.cs`:

```
public override void DecryptTo(Stream encryptedData, Stream decryptionStream)
{
    if (encryptedData == null)
        throw new ArgumentNullException(nameof(encryptedData));

    if (decryptionStream == null)
        throw new ArgumentNullException(nameof(decryptionStream));

    var parser = new CmsEnvelopedDataParser(encryptedData);
    var recipients = parser.GetRecipientInfos();
    var algorithm = parser.EncryptionAlgorithmID;
    AsymmetricKeyParameter key;

    foreach (RecipientInformation recipient in recipients.GetRecipients ()) {
        if ((key = GetPrivateKey (recipient.RecipientID)) == null)
            continue;

        var content = recipient.GetContentStream(key);

        content.ContentStream.CopyTo(decryptionStream);
    }
}
```

```
public void DecompressTo(Stream compressedData, Stream decompressedStream)
{
    if (compressedData == null)
        throw new ArgumentNullException(nameof(compressedData));

    if (decompressedStream == null)
        throw new ArgumentNullException(nameof(decompressedStream));

    var parser = new CmsCompressedDataParser(compressedData);

    parser.GetContent().ContentStream.CopyTo(decompressedStream);
}
```

and then the following to `ApplicationPkcsMime.cs`:

```
public void DecryptTo(SecureMimeContext ctx, Stream output)
{
    if (ctx == null)
        throw new ArgumentNullException(nameof(ctx));

    if (SecureMimeType != SecureMimeType.EnvelopedData)
        throw new InvalidOperationException();

    ctx.DecryptTo(ContentObject.Stream, output);
}
```

```
public void DecompressTo(SecureMimeContext ctx, Stream output)
{
    if (ctx == null)
    throw new ArgumentNullException(nameof(ctx));

    if (SecureMimeType != SecureMimeType.CompressedData)
         throw new InvalidOperationException();
 
    ctx.DecompressTo(ContentObject.Stream, output);
}
```

The problem is that I can't properly call the code below without pulling into memory again:
```
using (var memory = new MemoryBlockStream ()) {
    ContentObject.DecodeTo (memory);
    memory.Position = 0;
}
```
Any ideas?

**Comment by jstedfast** [comment]
I saw Org.BouncyCastle.Cms.RecipientInformation.GetContentStream(ICipherParameters key), but I thought it effectively returned a memory based stream?

Anyway... Added DecryptTo() and DecompressTo() methods to SecureMimeContext, but it's not worth adding the ApplicationPkcs7Mime versions because they are meant to deal with MimeEntities.

> The problem is that I can't properly call the code below without pulling into memory again:

I don't understand what you are trying to do... where are you at, exactly?

**Comment by jstedfast** [comment]
With the changes I've just committed to master, your code should look like this:

```csharp
using (var messageStream = File.Open (...)) {
    var message = MimeMessage.Load (messageStream, true);

    var part = LocatePart (message);

    using (var encrypted = part.ContentObject.Open ()) {
        using (var decrypted = File.Create (File.GetTempFileName ())) {
            context.DecryptTo (encrypted, decrypted);
            decrypted.Seek (SeekOffset.Origin, 0);

            var pkcs7 = MimeEntity.Load (decrypted, true) as ApplicationPkcs7Mime;

            using (var decompressed = File.Create (File.GetTempFileName ())) {
                using (var compressed = pkcs7.ContentObject.Open ()) {
                    context.DecompressTo (compressed, decompressed);
                    decompressed.Seek (SeekOffset.Origin, 0);
                }

                var signed = MimeEntity.Load (decompressed, true) as MultipartSigned;
                var content = signed[0] as MimePart;

                using (var stream = File.Create (...))
                    content.ContentObject.DecodeTo (stream);
            }
        }
    }
}
```
