### ISSUE TITLE
Make the domain available on MailBoxAddress

### ISSUE THREAD

**Issue by SeanFarrow** [jstedfast/MimeKit#266]
Hi,

It would be nice to have the domain available as a property on the MailBoxAddress class.
I'm converting some code from System.Net.MailAddress that uses the host property and I can't see an equivalent--that doesn't mean there isn't one!
Any help appreciated.
Cheers
Sean.

**Comment by jstedfast** [comment]
You can just `mailbox.Address.Substring (mailbox.Address.IndexOf ('@') + 1)`

**Comment by jstedfast** [comment]
After giving this some thought (having thought about it numerous times before), I think I'm going to pass on this feature. I don't think it's something that's really needed.
