### ISSUE TITLE
Inefficient encoding of attachment names or forcing an encoding

### ISSUE THREAD

**Issue by eriknuds** [jstedfast/MimeKit#269]
Hi,

if I have the following attachment name: Test Å!@#$#^%&^(&(){}(9).jpg
...then this could have been efficiently encoded as:

```
Content-Type: image/jpeg;
	name="=?utf-8?B?VGVzdCDDhSFAIyQjXiUmXigmKCl7fSg5KS5qcGc=?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="=?utf-8?B?VGVzdCDDhSFAIyQjXiUmXigmKCl7fSg5KS5qcGc=?="
```

yet MailKit encodes this as:

```
Content-Type: image/jpeg;
	name*0*="iso-8859-1''Test%20%C5!%40#$#^%25&^%28&%28";
	name*1*="%29{}%289%29%281%29.jpg"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename*0*="iso-8859-1''Test%20%C5!%40#$#^%25&^%28&%28";
	filename*1*="%29{}%289%29%281%29.jpg"
```

Is there a way to make MailKit select the more efficient encoding? And is there a way to force the ?utf-8?B? style encoding without parameter continuation (just normal header folding I guess) - as this seem to be more universially recognized?

**Comment by jstedfast** [comment]
The way that MimeKit/MailKit encode parameter values is the correct way according to the specifications: https://tools.ietf.org/html/rfc2231

The way that you are asking about is incorrect although MimeKit handles decoding them.

**Comment by jstedfast** [comment]
That said, you can use the following method to force MimeKit to use the non-standard encoding method instead: http://www.mimekit.org/docs/html/P_MimeKit_Parameter_EncodingMethod.htm

**Comment by eriknuds** [comment]
Ok, thanks:-)

Btw I realized MailKit was encoding the mime correctly, but the first example is/was also valid mime I believe and slightly more efficient in number of bytes and it seems more widely supported by older software than the parameter continuation, that's why I asked.

And thanks again for the info;-)

**Comment by jstedfast** [comment]
The `=?utf-8?b?...?=` method is actually invalid, but it *is* widely used.

FWIW, I just remembered that you can also just use a custom `FormatOptions` with the ParameterEncoding set to your preferred encoding method instead of setting it for each parameter.

**Comment by eriknuds** [comment]
Nice, thanks:-)

**Comment by eriknuds** [comment]
Btw, adding a content-description header to my attachment mime part headers solved my original file name display problem, so I won't have to use a non standard encoding to make clients ablte to read the file name parameter of the other headers anyway, they will use the content-description instead:-)

**Comment by jstedfast** [comment]
Oh, interesting... I did not know that. Be careful, though, that might only be true for some clients.

**Comment by eriknuds** [comment]
Yes, thunderbird and gmail web are examples of this behavior, If a client depends only on the filename parameters and are not falling back to the content-description header value when they can't find this parameter it better understand the proper parameter encoding used by MailKit and also look for "filename*" parameters ;-)
