### ISSUE TITLE
.NET 3.5 Thread Immediate Cancellation

### ISSUE THREAD

**Issue by OmegaAphex** [jstedfast/MimeKit#270]
I am currently using Polly in a .NET 3.5 framework environment. I am finding it difficult to find a way to immediately cancel the retry policy. As .NET 3.5 does not support cancellation tokens, how can this be done?

**Comment by jstedfast** [comment]
You can't. MimeKit for .NET 3.5 provides its own CancellationToken, but it is a dummy implementation so that I didn't need to rewrite the entire API for .NET 3.5.

**Comment by OmegaAphex** [comment]
Thanks for the information.
