### ISSUE TITLE
Ensure headers are always base64/quoted-printable

### ISSUE THREAD

**Issue by ibetin** [jstedfast/MimeKit#274]
I read in some other issue that MimeKit selects transfer encoding based on resulting length.
But in the code I can't find any filters applied to the headers except end of line ones.

Can you please point me in direction where to look for relevant code? I need to ensure some headers are quoted-printable.

Also this is a feature request - explicit setting of transfer encoding for headers

**Comment by jstedfast** [comment]
https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Utils/Rfc2047.cs#L941

I don't really see the advantage of what you are proposing. Every modern mail client can handle both base64 and the quoted-printable encoding.

**Comment by ibetin** [comment]
Thank you for response

It's for creating service headers for specific email parsing software, not for modern email clients. Enterprise legacy migration

**Comment by jstedfast** [comment]
Ah, well, good luck :)

If you have any other questions about the code, feel free to ask away and I'll do my best to answer them.
