### ISSUE TITLE
Parsing From header with iso-8859-1 problem

### ISSUE THREAD

**Issue by mmalbergier** [jstedfast/MimeKit#277]
I have a message with the following header:

`From: =?iso-8859-1?Q?Distribuidora_Celentano;_R=EDo_grande.?= <riogrande@celentanogrxxx.com.ar>`

When I inspect the From property of the parsed Mime Message I get

`Address = "=?iso-8859-1?Q?Distribuidora_Celentano"`

If I inspect the Headers, I get:

`Value = "Distribuidora Celentano; Río grande. <riogrande@celentanogrxxx.com.ar>"`

Is there something I'm missing or there is a problem with the parsing?

**Comment by jstedfast** [comment]
That's a malformed address. The ';' is a special character that ends an rfc822 group address and must be used within a quoted string (or encoded) to use in the name part of an email address:

```
     specials    =  "(" / ")" / "<" / ">" / "@"  ; Must be in quoted-
                 /  "," / ";" / ":" / "\" / <">  ;  string, to use
                 /  "." / "[" / "]"              ;  within a word.
```

**Comment by mmalbergier** [comment]
I see that the SMTP that is sending this email encodes the header in a wrong way. But, when you parse it, is it correct that the parsed address is `"=?iso-8859-1?Q?Distribuidora_Celentano"`?

**Comment by jstedfast** [comment]
Yes, that's syntactically what it should be interpreted as.
