### ISSUE TITLE
Could I know how to forwar an email? I mean that I want to add some text info based on the last email. Thanks ahead!

### ISSUE THREAD

**Issue by RonLiang** [jstedfast/MimeKit#279]
![image](https://cloud.githubusercontent.com/assets/24208866/22148999/487d26b4-df4c-11e6-84d6-5af83219d5f0.png)
 
I want to add an old email to a new email. But I find that the old info will apeare in the attachments.

**Comment by jstedfast** [comment]
I don't understand what you want. Do you have an example?

**Comment by RonLiang** [comment]
It looks like this:

A sent me an email. And I need to reply this email now. So I want to add A's email into the body of my email. Is there any way to implement this. will it work if I add A's message to body like below:

var msgPart = new MessagePart();
msgPart .Message = AMsg;   //AMsg is A's MimeMessage

var plainText = new TextPart("plain");
plainText.Text = "Hi Jon, Please find the file in the attachment."

var  mulPart = new Multipart();
mulPart.Add(plainText);
mulPart.Add(msgPart);

var message = new MimeMessage ();
message .body = mulPart;

**Comment by jstedfast** [comment]
What's wrong with what you have?

**Comment by jstedfast** [comment]
If you want to embed the text of the message, you'll have to find your own way of doing that. You can't use a MessagePart for that.

**Comment by RonLiang** [comment]
Ok, thanks for your answer. I would have a try.

**Comment by jstedfast** [comment]
FWIW, you'll need to read the portion of the message that you want to embed into the message body as text and then append it into a `TextPart` that represents the body of your message.

**Comment by RonLiang** [comment]
/*
 * DrawShapes.java. first and last name: Nickname: SU login name: Date of last
 * modification: 1/11/2017 Purpose: Draw shapes
 */
package DrawShapes.Homework5;

import java.util.Scanner;

/**
 * this class implements the simple methods to draw triangle shape.
 */

public class DrawShapes {
    public static int readSize(final Scanner keyboard) {
        int iSize = 0;

        try {
            System.out.print("Enter the size: ");
            iSize = Integer.parseInt(keyboard.next());

        } catch (Exception ex) {
            System.out.println("Enter the wrong size.");
        }
        return iSize;
    }

    public static double areaOfTriangle(final int iHeight) {
        return (iHeight * 2 - 1) * iHeight / 2.0;
    }

    public static void drawLine(final int iWidth, final char cSymbol) {
        for (int i = 1; i <= iWidth; i++) {
            System.out.print(cSymbol);
        }
    }

    public static void displayMenu() {
        System.out.println("Pick your shape!\n");
        System.out.println("1. Triangle");
        System.out.println("2. Upside Down Triangle");
        System.out.println("3. Diamond");
        System.out.println("4. Hourglass");
        System.out.println("5. Rocket");
        System.out.println("6. Quit");
        System.out.println("\n");
    }

    public static int readChoice(final Scanner keyboard) {
        int iChoice = 0;
        boolean bChoiceRight = false;

        try {
            while (false == bChoiceRight) {
                System.out.print("Enter your choice: ");
                iChoice = Integer.valueOf(keyboard.next());

                if (0 < iChoice && iChoice < 7) {
                    bChoiceRight = true;
                } else {
                    System.out.println("Enter your choice (1-6): ");
                }
            }

        } catch (Exception ex) {
            System.out.println("input error.");
        }
        return iChoice;
    }

    public static double drawTriangle(final Scanner keyboard) {
        int iSize = 0;

        try {
            iSize = readSize(keyboard);
            drawTriangle(iSize, '*');

        } catch (Exception ex) {
            System.out.println("Draw Triangle failed.");
        }

        return areaOfTriangle(iSize);
    }

    public static void drawTriangle(final int iHeight, final char cSymbol) {
        int iBeginPosition = iHeight;
        for (int i = 1; i <= iHeight; i++) {
            drawLine(iBeginPosition - 1, ' ');
            drawLine(i * 2 - 1, cSymbol);
            System.out.print("\n");
            iBeginPosition -= 1;
        }
    }

    public static double drawUpsideDownTriangle(final Scanner keyboard) {
        int iSize = 0;

        try {
            iSize = readSize(keyboard);
            drawUpsideDownTriangle(iSize, '*');

        } catch (Exception ex) {
            System.out.println("Draw Upside Down Triangle failed.");
        }

        return areaOfTriangle(iSize);
    }

    public static void drawUpsideDownTriangle(final int iHeight, final char cSymbol) {
        int iBeginPosition = 1;
        for (int i = iHeight; i >= 1; i--) {
            drawLine(iBeginPosition - 1, ' ');
            drawLine(i * 2 - 1, cSymbol);
            System.out.print("\n");
            iBeginPosition += 1;
        }
    }

    public static double drawDiamond(final Scanner keyboard) {
        int iSize = 0;

        try {
            iSize = readSize(keyboard);
            drawTriangle(iSize, '*');
            drawUpsideDownTriangle(iSize, '*');

        } catch (Exception ex) {
            System.out.println("Draw Diamond failed.");
        }

        return areaOfTriangle(iSize) * 2;
    }

    public static double drawHourglass(final Scanner keyboard) {
        int iSize = 0;

        try {
            iSize = readSize(keyboard);
            drawUpsideDownTriangle(iSize, '*');
            drawTriangle(iSize, '*');

        } catch (Exception ex) {
            System.out.println("Draw Hourglass failed.");
        }

        return areaOfTriangle(iSize) * 2;
    }

    public static double drawRocket(final Scanner keyboard) {
        int iSize = 0;
        int iSquareSize = 0;

        try {
            iSize = readSize(keyboard);
            iSquareSize = iSize * 2 - 1;
            drawTriangle(iSize, '*');
            drawSquare(iSquareSize, '*');
            drawLine(iSquareSize / 2, '/');
            drawLine(iSquareSize - (iSquareSize / 2), '\\');
            System.out.println("\n");

        } catch (Exception ex) {
            System.out.println("Draw Rocket failed.");
        }

        return areaOfTriangle(iSize) + iSquareSize * iSquareSize;
    }

    public static void drawSquare(final int iHeight, final char cSymbol) {
        if (iHeight < 2) {
            return;
        }

        drawLine(iHeight, cSymbol);
        System.out.print("\n");
        for (int i = 2; i < iHeight; i++) {
            System.out.print(cSymbol);
            drawLine(iHeight - 2, ' ');
            System.out.print(cSymbol);
            System.out.print("\n");
        }
        drawLine(iHeight, cSymbol);
        System.out.print("\n");
    }

    public static void sayBye() {
        System.out.println("Bye");
    }

    public static void pause(final Scanner keyboard) {

        try {
            System.out.print("Enter any key to continue.");
            keyboard.next();
        } catch (Exception ex) {
            System.out.print("Input Error.");
        }
    }

    public static void main(final String[] args) {
        Scanner keyboard = new Scanner(System.in);
        int iChoice;
        double dArea = 0;
        do {
            displayMenu();
            iChoice = 0;
            iChoice = readChoice(keyboard);
            switch (iChoice) {
            case 1:
                dArea = drawTriangle(keyboard);
                break;
            case 2:
                dArea = drawUpsideDownTriangle(keyboard);
                break;
            case 3:
                dArea = drawDiamond(keyboard);
                break;
            case 4:
                dArea = drawHourglass(keyboard);
                break;
            case 5:
                dArea = drawRocket(keyboard);
                break;
            case 6:
                sayBye();
            }

            if (iChoice != 6) {
                System.out.println("\nArea is : " + dArea);
                pause(keyboard);
            }
        } while (iChoice != 6);
    }

}

**Comment by RonLiang** [comment]
/*
 * COPYRIGHT. HSBC HOLDINGS PLC 2017. ALL RIGHTS RESERVED.
 *
 * This software is only to be used for the purpose for which it has been
 * provided. No part of it is to be reproduced, disassembled, transmitted,
 * stored in a retrieval system nor translated in any human or computer
 * language in any way or for any other purposes whatsoever without the prior
 * written consent of HSBC Holdings plc.
 */
package Creature.Homework5;

import java.util.Scanner;

/**
 * <p>
 * <b> TODO : Insert description of the class's responsibility/role. </b>
 * </p>
 */

public class Creature {
    private String sType;
    private String sName;
    private String sWeapon;
    private String sLine;
    private double dLifeLevel;

    public Creature() {
        this.sType = "creature";
        this.sName = "N/A";
        this.sWeapon = "N/A";
        this.setsLine("N/A");
        this.dLifeLevel = 50;
    }

    public Creature(final String sType, final String sName, final String sWeapon, final String sLine) {
        this.sType = sType;
        this.sName = sName;
        this.sWeapon = sWeapon;
        this.setsLine(sLine);
        this.dLifeLevel = 100;
    }

    public void readInput() {
        try {
            Scanner sInput = new Scanner(System.in);

            System.out.print("Please Input the Creatrue Type: ");
            this.sType = sInput.next();

            System.out.print("Please Input the Creatrue sName: ");
            this.sName = sInput.next();

            System.out.print("Please Input the Creatrue sWeapon: ");
            this.sWeapon = sInput.next();

            System.out.print("Please Input the text Creatrue says: ");
            this.setsLine(sInput.next());

            System.out.print("Please Input the Creatrue LifeLevel: ");
            this.dLifeLevel = Integer.parseInt(sInput.next());

            sInput.close();
        } catch (Exception ex) {
            System.out.print("Input Creature info error.");
        }
    }

    public void writeOutput() {
        System.out.print("Type: " + this.sType);
        System.out.print("Name: " + this.sName);
        System.out.print("Weapon: " + this.sWeapon);
        System.out.println("LifeLevel: " + this.dLifeLevel);
    }

    /**
     * @return the sType
     */
    public String getsType() {
        return this.sType;
    }

    /**
     * @param sType
     *            the sType to set
     */
    public void setsType(final String sType) {
        this.sType = sType;
    }

    /**
     * @return the sName
     */
    public String getsName() {
        return this.sName;
    }

    /**
     * @param sName
     *            the sName to set
     */
    public void setsName(final String sName) {
        this.sType = sName;
    }

    /**
     * @return the sWeapon
     */
    public String getsWeapon() {
        return this.sWeapon;
    }

    /**
     * @param sWeapon
     *            the sWeapon to set
     */
    public void setsWeapon(final String sWeapon) {
        this.sType = sWeapon;
    }

    /**
     * @return the sLine
     */
    public String getsLine() {
        return this.sLine;
    }

    /**
     * @param sLine
     *            the sLine to set
     */
    public void setsLine(final String sLine) {
        this.sLine = sLine;
    }

    /**
     * @return the dLifeLevel
     */
    public double getdLifeLevel() {
        return this.dLifeLevel;
    }

    /**
     * @param dLifeLevel
     *            the dLifeLevel to set
     */
    public void setdLifeLevel(final double dLifeLevel) {
        this.dLifeLevel = dLifeLevel;
    }

    public void speak() {
        if (this.isAlive()) {
            System.out.println(this.sName + ": " + this.sLine);
        }
    }

    public void die() {
        this.dLifeLevel = 0;
        this.sLine = "";
    }

    public boolean isAlive() {
        return this.dLifeLevel > 0;
    }

    public void updateLifeLevel(final double dLifeLevel) {

        if (dLifeLevel > 0) {
            this.dLifeLevel = dLifeLevel;
        } else {
            this.dLifeLevel = 0;
        }
    }

    public boolean equals(final Creature oCreature) {
        if (this.sType.equalsIgnoreCase(oCreature.sType) && this.sName.equalsIgnoreCase(oCreature.sName)
            && this.sWeapon.equalsIgnoreCase(oCreature.sWeapon) && this.sLine.equalsIgnoreCase(oCreature.sLine)
            && this.dLifeLevel == oCreature.dLifeLevel) {
            return true;
        } else {
            return false;
        }
    }
}









/*
 * COPYRIGHT. HSBC HOLDINGS PLC 2017. ALL RIGHTS RESERVED.
 *
 * This software is only to be used for the purpose for which it has been
 * provided. No part of it is to be reproduced, disassembled, transmitted,
 * stored in a retrieval system nor translated in any human or computer
 * language in any way or for any other purposes whatsoever without the prior
 * written consent of HSBC Holdings plc.
 */
package Creature.Homework5;

/**
 * <p>
 * <b> TODO : Insert description of the class's responsibility/role. </b>
 * </p>
 */
public class CreatureTest {
    public static void main(final String[] args) {
        Creature oCreature1 = new Creature();
        oCreature1.readInput();
        Creature oCreature2 = new Creature("Elf", "Skittler", "MAGICBOW", "My arrow flies true!");
        Creature oCreature3 = new Creature("Goblin", "Gul", "BLUDGEON", "Gllaaaassshhssh!");

        oCreature1.writeOutput();
        oCreature2.writeOutput();
        oCreature3.writeOutput();

        oCreature1.speak();
        oCreature2.speak();
        oCreature3.speak();

        oCreature1.updateLifeLevel(12);
        oCreature2.updateLifeLevel(100);
        oCreature3.updateLifeLevel(67);

        oCreature1.writeOutput();
        oCreature2.writeOutput();
        oCreature3.writeOutput();

        oCreature1.die();
        oCreature1.speak();


    }
}
