### ISSUE TITLE
Specify RFC2047 encoding for parameters when creating a MimePart

### ISSUE THREAD

**Issue by jhumphries83** [jstedfast/MimeKit#281]
Im creating a new MimePart using the constructor that takes a ContentType object.  

The ContentType that I am providing has a long filename (over 100 chars).  

The parameter is being split across several lines according to RFC2231, however I do not want this to happen as it seems that both Lotus Notes and Microsoft Outlook do not support this.  Is it possible to choose RFC2047 style encoding for parameters when creating a new MimePart? - I do not see a way to specify this.

**Comment by jstedfast** [comment]
Please see the FAQ: https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#UntitledAttachments
