### ISSUE TITLE
how to release the local attachment file after I sent an MimeMessage?

### ISSUE THREAD

**Issue by RonLiang** [jstedfast/MimeKit#284]
Just as the title said, how I should release the local attachment file resource after I sent the MimeMessage in which the attachment file included.

I need to delete this attachment file after sending the MimeMessage. But I can't delete it.  it is said that another process is using this file. I think the reason is MimeMessage object doesn't release this file resource        after being sent.

**Comment by jstedfast** [comment]
You either have to dispose the stream after calling SmtpClient.Send() or else you could copy it to a MemoryStream and give the MemoryStream to the MimeMessage attachment instead.

**Comment by RonLiang** [comment]
Thanks so much.
