### ISSUE TITLE
MimeKit.Header is lost after the Mimemessage is sent.

### ISSUE THREAD

**Issue by RonLiang** [jstedfast/MimeKit#289]
I set the a "Keywords" header as "OurRef:1234567" in Mimemessage before I send it.

But when I receive it in my inbox folder, this "Keywords" header is missing.

**Comment by jstedfast** [comment]
Your server is probably removing it.

You can verify this by following the instructions on getting a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) for sending the message via SMTP.

**Comment by RonLiang** [comment]
Thanks. Maybe I should put the tag in the mail body.

**Comment by RonLiang** [comment]
#include<stdio.h>
#include<math.h>

void divisibility(int number,int *seven,int *eleven,int *thirteen)
{
	char szTemp[256]="";
	if (NULL!= seven && 0==number%(*seven))
	{
	     sprintf(szTemp,"Divisibility by %d: YES \n",*seven);
	     printf(szTemp);
	}
	else
	{
	     sprintf(szTemp,"Divisibility by %d: NO \n",*seven);
	     printf(szTemp);
	}

	if (NULL!= eleven && 0==number%(*eleven))
	{
	     sprintf(szTemp,"Divisibility by %d: YES \n",*eleven);
	     printf(szTemp);
	}
	else
	{
	     sprintf(szTemp,"Divisibility by %d: NO \n",*eleven);
	     printf(szTemp);
	}

	if (NULL!= thirteen && 0==number%(*thirteen))
	{
	     sprintf(szTemp,"Divisibility by %d: YES \n",*thirteen);
	     printf(szTemp);
	}
	else
	{
	     sprintf(szTemp,"Divisibility by %d: NO \n",*thirteen);
	     printf(szTemp);
	}
}

int is_prime(int number)
{
	int i, iTemp;
	if(number==0 || number==1)
	{
		return 0;
	}

	iTemp=sqrt((double)number);

	for(i=2;i<=iTemp;i++)
	{
		if(0==number%i)
		{
			return 0;
		}
	}

	return 1;
}

int main(void)
{
	char szTemp[256]="";
	int n=1,iSeven=7,iEleven=11,iThirteen=13;

	printf("Enter a number: ");
	scanf("%d",&n);

	printf("Facts for your number: \n");
	divisibility(n,&iSeven,&iEleven,&iThirteen);

	sprintf(szTemp,"Is Prime: %s \n",1==is_prime(n)?"YES":"NO");
	printf(szTemp);

	return 0;
}
