### ISSUE TITLE
Missing MIME-Version Header

### ISSUE THREAD

**Issue by davidpleasant** [jstedfast/MimeKit#290]
Hi.

We converted from using System.Net.Mail.MailMessage to using MimeMessages.  We used MimeMessage.CreateFromMailMessage(message) and the behaviour we get from sending this seems different from using the original MailMessage send.  The MIME-Version header seems to be excluded.

**Comment by jstedfast** [comment]
Looks like a bug. You can work around it by setting the MimeMessage.MimeVersion property on the MimeMessage.

**Comment by jstedfast** [comment]
Fixed!

**Comment by jstedfast** [comment]
I plan to make a release this weekend with this fix.

**Comment by jstedfast** [comment]
MimeKit 1.14 was released with this fix

**Comment by davidpleasant** [comment]
Thanks!  I grabbed it this morning!

Sent from my iPhone

On Apr 10, 2017, at 5:48 PM, Jeffrey Stedfast <notifications@github.com<mailto:notifications@github.com>> wrote:


MimeKit 1.14 was released with this fix
