### ISSUE TITLE
Mime Header 'filename' parameter splitting causes issues in Outlook and Thunderbird

### ISSUE THREAD

**Issue by nosider** [jstedfast/MimeKit#291]
Hi,

We came up against an issue, where very long file-names for attachments would be (rightfully so as per RFC2231) split onto multiple lines, but some very popular email clients would fail to recognise the split, and would display only a portion of the file-name. 

```
Content-Type: application/x-custom-type;
    name*0=some_really_long_filename_that_goes_beyond_the_78_character_limit_of;
    name*1=mime_line.pdf
Content-Disposition: attachment;
    filename*0=some_really_long_filename_that_goes_beyond_the_78_character_limit;
    filename*1=_of_mine_line.pdf	 
```

Checking the code, it seems there is no way to specify a larger MaxLineLength when MimeKit renders MIME parameters. Looking at how the .Net default Smtp client handles this issue - it doesn't - instead it will ignore the max line length in the RFC and will simply write the full file-name in a single line, without any wrapping.

To try and work around this issue in email clients, we were hoping to adjust the `FormatOptions.MaxLineLength` property to avoid this problem for users, but it seems that the value is a read-only property that returns a constant.

Is it possible to make that MaxLineLength adjustable? If not, it possible to make a separate adjustable MaxLineLength property which will only be used when rendering MIME Header parameters?

Cheers :)

**Comment by jstedfast** [comment]
See the FAQ :)

https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#UntitledAttachments

**Comment by nosider** [comment]
@jstedfast 

Thank you for such a quick response. 

The issue we are trying to get around is not to do with encoding, but with maximum line length. Will changing the encoding also stop parameters being split into multiple lines? I will give it a try in either case,

Thank you!

**Comment by jstedfast** [comment]
Yes, it'll prevent the splitting into multiple lines. The default encoding used (defined in rfc2231) is what causes the filename value to be split across multiple lines.

**Comment by tadassukys** [comment]
Faced with the same problem. MimeKit 1.16.1.0. Trying both methods as described here https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#UntitledAttachments and it only works if explicitly set `EncodingMethod `to a `Parameter..` .

I'd like to share my snippets.

Say I have an attachment with long file name
 `0ce5268f-343f-44d0-8b2a-279662b23f9d-be3f7b2c-ee51-4573-9a94-5239bece611a.PDF`
then if
a) pass options to `MimeMessage.WriteTo()`:
```
var options = FormatOptions.Default.Clone();
options.ParameterEncodingMethod = ParameterEncodingMethod.Rfc2047;
mimeMessage.WriteTo(options, stream);
```
it doesn't work as expected and produced result is:
`--=-vb3G5zqwXgw/XSs7VqQ72Q==
Content-Type: application/pdf;
	name*0=0ce5268f-343f-44d0-8b2a-279662b23f9d-be3f7b2c-ee51-4573-9a94-5239bec;
	name*1=e611a.PDF
Content-Disposition: attachment;
	filename*0=0ce5268f-343f-44d0-8b2a-279662b23f9d-be3f7b2c-ee51-4573-9a94-523;
	filename*1=9bece611a.PDF
Content-Transfer-Encoding: base64`
Outlook shows "Untitled attachment 00004.pdf".

**Is that an issue in the library?**

b) set `Parameter.EncodingMethod` value `ParameterEncodingMethod.Rfc2047` 

like here            
```
foreach (var bodyPart in mimeMessage.BodyParts)
           {
                if (bodyPart.ContentDisposition == null)
                {
                    continue;
                }

                foreach (var p in bodyPart.ContentDisposition.Parameters)
                {
                    p.EncodingMethod = ParameterEncodingMethod.Rfc2047;
                }
}
mimeMessage.WriteTo(stream);
```

Outcome is:
```
--=-vb3G5zqwXgw/XSs7VqQ72Q==
Content-Type: application/pdf;
	name*0=0ce5268f-343f-44d0-8b2a-279662b23f9d-be3f7b2c-ee51-4573-9a94-5239bec;
	name*1=e611a.PDF
Content-Disposition: attachment; filename="=?us-ascii?q?0ce5268f-343f-44d?=
	=?us-ascii?q?0-8b2a-279662b23f9d-be3f7b2c-ee51-4573-9a94-5239bece611a=2EPD?=
	=?us-ascii?q?F?="
Content-Transfer-Encoding: base64
```
and that's good results, Outlook shows file name correctly.
