### ISSUE TITLE
Load winmail.dat directly from file?

### ISSUE THREAD

**Issue by Broda** [jstedfast/MimeKit#297]
Is there a way to load the winmail.dat directly from a file instead of as part of a message? I've tried the following:

`MimePart winmail = (MimePart)MimeEntity.Load(path_to_winmail_file);`

But I get the following error:

> System.FormatException: 'Failed to parse entity headers.'

All I'm trying to do is take the winmail.dat file and extract all attachments to the file system. The extraction is straightforward once I get it loading successfully.

**Comment by jstedfast** [comment]
You can use the MimeKit.Tnef.TnefReader directly, but it's pretty low-level and not easy to provide a simple "here's how you can use it" explanation here (plus I'm in a bit of a rush atm), so I'll instead tell you how you can cheat to get the same effect you want (probably):

```csharp
var tnef = new TnefPart { ContentObject = new ContentCobject (File.OpenRead (path_to_winmail_file)) };
```

Now you've got a TnefPart that you can use the handy methods on to extract the attachments or convert the content into a MimeMessage (ms-tnef is more of a message encapsulation format).

Hope that helps.
