### ISSUE TITLE
Parsing Addresses with international characters

### ISSUE THREAD

**Issue by LeeBear35** [jstedfast/MimeKit#300]
Below I have the **From** header, and the collection after it is parsed. The one address is becoming two entries and they are being encoded.

```
HDR From: Bérard, Mélanie  <mberard@can.ca>
	From_0: =?iso-8859-1?Q?B=E9rard
	Domain: 
	From_1: "=20M=E9lanie=20?=" <mberard@can.ca>
	Domain: can.ca
```

Another example of the CC header, and it shows an inconsistency:
```
HDR CC: <Séguin>, "André"    <aseguin@can.ca>,  "Lee Masoud"  <lee.masoud@div.com>,  "Taline  Bahlawanian"  <taline.bahlawanian@onde.com>,   "Alain Bérubé"    <aberube@comm.com>,  "Ves - Hugues Philibert"   <hphilibert@ves.ca>,  "Nicolas Bergeron"  <nbergeron@ves.ca>,  "R  Goldenberg"  <rgoldenberg@comm.com>
	CC_0: "=?iso-8859-1?Q?" <S=E9guin>
	Domain: 
	CC_1: "=20Andr=E9=20=20?=" <aseguin@can.ca>
	Domain: can.ca
	CC_2: "Lee Masoud" <lee.masoud@div.com>
	Domain: div.com
	CC_3: "Taline  Bahlawanian" <taline.bahlawanian@onde.com>
	Domain: onde.com
	CC_4: " Alain Bérubé  " <aberube@comm.com>
	Domain: comm.com
	CC_5: "Ves - Hugues Philibert" <hphilibert@ves.ca>
	Domain: ves.ca
	CC_6: "Nicolas Bergeron" <nbergeron@ves.ca>
	Domain: ves.ca
	CC_7: "R  Goldenberg" <rgoldenberg@comm.com>
	Domain: comm.com
```

**Comment by LeeBear35** [comment]
I will get the latest, When I reported I posted from the MimeKit Headers which when I looked at things through me off the actual file headers are:

From:  =?iso-8859-1?Q?B=E9rard,=20M=E9lanie=20?= <mberard@can.ca>
Cc:  =?iso-8859-1?Q?<S=E9guin>,=20"Andr=E9"=20=20?= 
 <aseguin@can.ca>,  "Lee Masoud"  <lee.masoud@div.com>,  "Taline 
 Bahlawanian"  <taline.bahlawanian@londe.com>, 
 =?iso-8859-1?Q?=20"Alain=20B=E9rub=E9"=20=20?= 
 <aberube@comml.com>,  "Ves - Hugues Philibert"  
 <hphilibert@ves.ca>,  "Nicolas Bergeron"  <nbergeron@ves.ca>,  "R
  Goldenberg"  <rgoldenberg@comm.com>

They may not be needed, but thought I would relay them anyhow.

**Comment by jstedfast** [comment]
I think my fix will still work, but I'll test it later tonight to be sure.
