### ISSUE TITLE
Address not parsing correctly

### ISSUE THREAD

**Issue by LeeBear35** [jstedfast/MimeKit#301]
Here is an **From** header that for all intense and purposes should parse correctly, but does not, likely due to the ampersand in the name portion of the the entry, but it is within quotes so it should be handled correctly.

HDR From: "dennisbernard500@" <aol.com dennisbernard500@aol.com>

**Comment by jstedfast** [comment]
I think the problem is actually the malformed addr-spec token between the `<>`'s :)

**Comment by M0ns1gn0r** [comment]
On version 0.10.0 the following used to parse correctly, but fails on 0.14.1:

    'new MailboxAddress("John Smith <john@smith.com>")' threw an exception of type 'MimeKit.ParseException'
    Data: {System.Collections.ListDictionaryInternal}
    ErrorIndex: 5
    HResult: -2146233033
    HelpLink: null
    InnerException: null
    Message: "Invalid addr-spec token at offset 0"
    Source: "MimeKit"
    StackTrace: "   at MimeKit.InternetAddress.TryParseAddrspec(Byte[] text, Int32& index, Int32 endIndex, Byte[] sentinels, Boolean throwOnError, String& addrspec, Int32& at)\r\n   at MimeKit.MailboxAddress.set_Address(String value)\r\n   at MimeKit.MailboxAddress..ctor(Encoding encoding, String name, String address)\r\n   at MimeKit.MailboxAddress..ctor(String address)"
    TargetSite: {Boolean TryParseAddrspec(Byte[], Int32 ByRef, Int32, Byte[], Boolean, System.String ByRef, Int32 ByRef)}
    TokenIndex: 0

**Comment by jstedfast** [comment]
No, that never parsed correctly. Instead, MimeKit pre 1.14, did not pare any string you gave to it in a MailboxAddress constructor.

You were never supposed to feed a MailboxAddress constructor with an unparsed email address.

This is how you were supposed to use it:

```csharp
new MailboxAddress ("John Smith", "john@smith.com");

// or

new MailboxAddress ("john@smith.com");
```

The `address` parameter to the MailboxAddress constructors is only ever meant to take an actual *address*, not the name too.

**Comment by jstedfast** [comment]
If you want to take a raw, unparsed, email address as it might appear in a message and get a MailboxAddress from it, you need to use `MailboxAddress.Parse()`:

```csharp
MailboxAddress.Parse ("John Smith <john@smith.com>")
```

**Comment by jstedfast** [comment]
I've just updated the documentation to make this clear because it didn't really explain this previously.
