### ISSUE TITLE
Working with the NULL Sender Address

### ISSUE THREAD

**Issue by jhumphries83** [jstedfast/MimeKit#302]
Hi,

A quick question - how should I be working with the NULL Sender address in MimeKit?

Back in v1.10 I was able to create an instance of the NULL Sender address like this:
```
public static MailboxAddress NullMailboxAddress
{
     get { return new MailboxAddress(string.Empty, string.Empty); }
}
``` 
However, in v1.16 I receive a ArgumentException when doing this.

I want so be able to send a DSN from the NULL Sender by doing something like this:

```
smtpClient.Send(bounceMessage, EmailAddress.NullMailboxAddress, bounceMessage.To.Mailboxes);
```

Thanks!

**Comment by jhumphries83** [comment]
I should also mention that I've tried:
```
return new MailboxAddress(string.Empty, "<>");
```
but that throws a ParseException

**Comment by jstedfast** [comment]
SMTP requires a sender address. You don't have to add it to the message, though.

**Comment by jstedfast** [comment]
never mind, I guess it is allowed.

**Comment by jhumphries83** [comment]
Hi,  Thanks for fixing that so quickly - I'm able to create an instance of the MailboxAddress with an empty address now, but when I call MailKit.Net.Smtp.SmtpClient.Send I'm getting the exception "Index was outside the bounds of the array" at MimeKit.InternetAddress.TryParseLocalPart.

**Comment by jstedfast** [comment]
It should work now.

**Comment by jhumphries83** [comment]
Thanks for getting this sorted so quickly.  Do you have a plan for the next release date yet?

**Comment by jstedfast** [comment]
End of May I guess. I've been really busy and don't have time to make a release right now.
