### ISSUE TITLE
Initialize a message with a winmail.dat file

### ISSUE THREAD

**Issue by mrjack88** [jstedfast/MimeKit#303]
Sorry for the NOOB question. I want to parse a winmail.dat file and get all its content, but i don't know how to instantiate it. I have tried the following:
```
FileStream stream = new FileStream("D\\winmail.dat", FileMode.Open, FileAccess.Read, FileShare.Read);
var message = MimeMessage.Load (stream);
```

but i throws 'System.FormatException'
failed to parse message headers.

Any help would be appreciated.

**Comment by jstedfast** [comment]
MimeMessage.Load() is for loading MIME messages, not TNEF messages.

You need to use the tools in the MimeKit.Tnef namespace (such as the `TnefReader`).

It is, however, fairly low level.

Easiest solution is to just do this:

```csharp
using (var stream = File.OpenRead ("D\\winmail.dat")) {
    var tnef = new TnefPart () { ContentObject = new ContentObject (stream) };
    var message = tnef.ConvertToMessage ();
}
```
