### ISSUE TITLE
Invalid tag name in HtmlWriter.ValidateTagName method

### ISSUE THREAD

**Issue by wfouche1** [jstedfast/MimeKit#305]
Hi,

We're using the Visitors pattern to parse e-mails. However an exception is thrown due to an Unkown html tag. This tag "o:p" seems to be specific to e-mail created using outlook or word. http://stackoverflow.com/questions/7808968/what-do-op-elements-do-anyway 
1. What is the best to way to handle "HtmlTagId.Unknown"? Ideally I don't want to use the DeleteTag method.
2. Can you please add support for the "o:p" tags?

Thanks

W

**Comment by jstedfast** [comment]
Are you trying to use HtmlWriter.WriteStartTag() using HtmlTagId.Unknown? Why aren't you using the string itself?
