### ISSUE TITLE
Malformed subject after casting from MailMessage to MimeMessage

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MimeKit#306]
Hi,

I got some strange behavior when casting a MailMessage to a MimeMessage like this.

```
        public string WriteMessage(Email email, MailMessage message)
        {
            var mimeMessage = (MimeMessage) message;
            mimeMessage.Date = email.SendDate;
            return WriteMessage(mimeMessage);
        }
```

The subject gets UTF8 encoded,

![image](https://cloud.githubusercontent.com/assets/6692947/26234844/d0f5faa2-3c67-11e7-9b9a-613dc41a0494.png)

When I open this message in Outlook the subject looks like this

![image](https://cloud.githubusercontent.com/assets/6692947/26234913/2f1f2f0e-3c68-11e7-89f6-4244855ca841.png)

At the moment I just fixed it like this
`mimeMessage.Subject = message.Subject;`

**Comment by jstedfast** [comment]
Is this after you sent the message via System.Net.Mail.SmtpClient?

I highly recommend avoiding this method. It will likely never be perfect - it's intent is only as a temporary solution for developers porting to MailKit, not intended as a real solution for production.

**Comment by Sicos1977** [comment]
Well I just used it for the thing you mentioned... porting to MailKit. At the moment it was to much work to rewrite a lot of code and so I took the easy way.... casting :-).

But to answer your question. I had the problem before sending it.
