### ISSUE TITLE
Attachment names with special characters are broken when converted from TNEF

### ISSUE THREAD

**Issue by JamMail** [jstedfast/MimeKit#307]
Hello,

I am currently trying to convert TNEF Parts to MIME and can't find a way to get around this problem.

**The test case:**
I have send an mail containing an attachment with name "AttÄÖÜMent.txt" via exchange to an internal account and saved it directly after the exchange receives it. I noticed the attachment is broken after processing it with our software, which happens after saving the raw TNEF. (the TNEF part of said mail as well of the used attachment is attached in the TnefAttachmentEncodingIssueExamples.zip archive.
[TnefAttachmentEncodingIssueExamples.zip](https://github.com/jstedfast/MimeKit/files/1021567/TnefAttachmentEncodingIssueExamples.zip)

After parsing the TNEF part and adding the attachment to a MIME mail the attachment looks like this:

```
Content-Type: text/plain; name*="iso-8859-1''Att%C4%D6%DCMent.txt"
Content-Disposition: attachment; filename*="iso-8859-1''Att%C4%D6%DCMent.txt";
	creation-date="Mon, 22 May 2017 15:19:06 +0200";
	modification-date="Mon, 22 May 2017 15:19:06 +0200"
Content-Transfer-Encoding: 7bit
```

This does not happen if I create a normal MIME mail with such an attachment and parse it with MimeKit.
In a normal MIME mail parsed and written with MimeKit it looks like this:

```
Content-type: text/plain; charset=iso-8859-1;
 name="=?iso-8859-1?B?QXR0xNbcTWVudC50eHQ=?="
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
 filename="=?iso-8859-1?B?QXR0xNbcTWVudC50eHQ=?="
Content-Description: =?iso-8859-1?B?QXR0xNbcTWVudC50eHQ=?=
```

The easiest way to reproduce this issue is to parse the attached tnef with a TnefPart and either calling TnefPart.ExtractAttachments() or TnefPart.ConvertToMessage().

Is there anything I can do to avoid this behaviour or is this an code issue?

Thanks a lot for any advice / help.

**Comment by jstedfast** [comment]
What you are seeing is perfectly valid. It's not broken at all.

Se the FAQ for more information: https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#UntitledAttachments

**Comment by JamMail** [comment]
Thanks a lot for pointing me in the right direction and for this comprehensive parsing library.

**Comment by jstedfast** [comment]
You're welcome :)
