### ISSUE TITLE
Failed to find mbox From marker

### ISSUE THREAD

**Issue by manolod** [jstedfast/MimeKit#308]
Using the Unix  MBOX Parser, there is one message that the parser cannot read and it throws the following error "Failed to find mbox From marker".
It then loops forever on this message because the following function does not process the error state:
unsafe MimeParserState Step (byte* inbuf) 

We need a way to "resynchronize" and try to move to the next message.

`MimeParser parser = new MimeParser(streamReader, MimeFormat.Mbox);

int numberMails = 0;
while (!parser.IsEndOfStream)
{
    try
    {
        var message = parser.ParseMessage();
        numberMails++;
        System.Console.WriteLine(numberMails);
    }
    catch
   {
   }
}`

**Comment by manolod** [comment]
additional note.
The body contains "From 49.5$"
I believe that the parser gets unsynchronized because of this. It thinks that it is the beginning of a new message.

**Comment by jstedfast** [comment]
The `Step()` method processes the Error state just fine. In the error state, it just returns error. That's what it's supposed to do.

All callers of the `Step()` method that I can see check the returned state for error.

Your mbox is malformed, there's nothing the parser can do about that.

**Comment by manolod** [comment]
You're closing too quickly, but afterall it's your project, I accept it.

The mbox is not malformed. I have 7 mailboxes  with this error.

The one I'm debugging has 120 000 mails. It's failing around mail  78 000.
Only one of the mail is malformed and is causing the parser to fail to process  the remaining mails.

The parser is looping forever on the corrupted mail. Because on the next loop, the pointer remains at the same position and immediately returns with the error state without doing any action.

This is clearly a corrupted message (and not a corrupted mbox) and is causing a bug in the parser wich loops forever on this mail.
And if you want my opinion, it's not a corrupted mail, it's a mail exported from Google Vault which contains "from :" in the body and the parser interprets it as the beginning of the next mail and of course doesn't find the header.

Thank you however for closing the door and refusing assistance.

**Comment by jstedfast** [comment]
It sounds to me like you are catching a FormatException and then trying to resume calling parser.GetMessage()? The parser was not designed to handle that. I suppose if you want to try doing that, edit ParseMessage() and add:

```csharp
if (state == MimeParserState.Error)
    state = MimeParserState.Initialized;
```

Let me know how that works.

Also: by definition, if you have a corrupted message in the mbox, you have a corrupted mbox.

This should be obvious, but even if you could just reset the parser state to "Initialized" (I think that's what you'd need), you'd still end up getting truncated message(s).

**Comment by jstedfast** [comment]
The idea should instead be for you to parse until you get an exception, use `MimeParser.MboxMarkerOffset` and `MimeParser.Position` to save state, fix the mbox, set the new fixed stream on the parser, and then resume parsing where things left off before you got the exception.

**Comment by manolod** [comment]
Added this function:
` public void GoToNextMessage()
        {
            int nread = stream.Read(input,0 , 4096);
            state = MimeParserState.Initialized;
        }   `

And called it in the catch
` while (!parser.IsEndOfStream)
            {
                try
                {
                    var message = parser.ParseMessage();
                    numberMails++;
                    //if ( numberMails == 78364)
                    //{
                    
                    //}
                    System.Console.WriteLine(numberMails);
                }
                catch (Exception exc)
                {
                    parser.GoToNextMessage();
                }
            }`

**Comment by jstedfast** [comment]
You can use `<backtick><backtick><backtick>csharp` to start a csharp code section in markdown and `<backtick><backtick><backtick>` to end it.

**Comment by jstedfast** [comment]
Your GoToNextMessage() is broken - what if 4096 bytes will read past the start of the next message? Then you lose an entire message.

**Comment by jstedfast** [comment]
fwiw, this is more how I imagined you would work around problems like the one you are hitting:

```csharp
using (var stream = File.OpenRead ("Inbox")) {
    var parser = new MimeParser (stream, MimeFormat.Mbox);
    while (!parser.IsEndOfStream) {
        try {
            var message = parser.GetMessage ();
        } catch {
            stream.Position = parser.Position;
            parser.SetStream (stream, MimeFormat.Mbox);
        }
    }
}
```

**Comment by jstedfast** [comment]
Did either of my solutions work for you?

**Comment by magnushammar** [comment]
I tried that last solution on a mbox straight out of Google Takeout and it works (in the sense that it continues parsing messages). I can live with loosing a few messages.

Thank you for an awesome library.
