### ISSUE TITLE
Loading into a MimeMessage with encoding from a stream

### ISSUE THREAD

**Issue by Dafnafrank** [jstedfast/MimeKit#309]
Hi,
We are having some encoding issues.
Is there a way to create a Mime Message from a stream and providing encoding (as "windows-1255").

**Comment by jstedfast** [comment]
Yes:

```csharp
var options = ParserOptions.Default.Clone ();
options.CharsetEncoding = Encoding.GetEnclding ("windows-1255");

var message = MimeMessage.Load (options, stream);
```

For more about ParserOptions.CharsetEncoding, see http://www.mimekit.net/docs/html/P_MimeKit_ParserOptions_CharsetEncoding.htm
