### ISSUE TITLE
S/MIME verification - are CAs checked to be trusted?

### ISSUE THREAD

**Issue by Compufreak345** [jstedfast/MimeKit#312]
Hi,

I have implemented S/MIME verification like in the example that is provided in the readme.

```
if (entity is MultipartSigned) {
    var signed = (MultipartSigned) entity;

    foreach (var signature in signed.Verify ()) {
        try {
            bool valid = signature.Verify ();

            // If valid is true, then it signifies that the signed content has not been
            // modified since this particular signer signed the content.
            //
            // However, if it is false, then it indicates that the signed content has
            // been modified.
        } catch (DigitalSignatureVerifyException) {
            // There was an error verifying the signature.
        }
    }
}
```

I am currently trying to find out how this verification works and I would relly appreciate if you could bring some light into this. 

Is the method checking if the certificate comes from a trusted certificate authority or does it just check if the content is correctly signed?
If it checks the CAs, does it use the configuration of the OS or does it use another repository for this?

Thanks & best regards,
Compu

**Comment by jstedfast** [comment]
It checks both that the signature is valid *and* that the certificate is trusted by checking the certificate chain.

It does not contact any CA's over the network. It relies on you properly keeping your certificate database(s) up-to-date.

**Comment by Compufreak345** [comment]
Thanks for the explanation - I'm still confused regarding the certificate database. I think you are referring to the database that needs to be registered with 
`CryptographyContext.Register (typeof (MySecureMimeContext));`

I set mine up to use an in-memory database, which is empty by default. But I still get true returned when I call signature.Verify - I'm not sure why this happens without any certificates set up. 

This is the code for setting up the context:
```
class AclSecureMimeContext : DefaultSecureMimeContext
  {
    public AclSecureMimeContext() : base(OpenDatabase(":memory:"))
    {
    }

    static IX509CertificateDatabase OpenDatabase(string fileName)
    {
      var builder = new SQLiteConnectionStringBuilder();
      builder.DateTimeFormat = SQLiteDateFormats.Ticks;
      builder.DataSource = fileName;
      if (fileName != ":memory:")
        if (!File.Exists(fileName))
          SQLiteConnection.CreateFile(fileName);

      var sqlite = new SQLiteConnection(builder.ConnectionString);
      sqlite.Open();
      
      return new SqliteCertificateDatabase(sqlite, "password");
    }
  }
```

**Comment by jstedfast** [comment]
Then I don't know... it shouldn't. Perhaps a bug in BouncyCastle's validation logic?

**Comment by jstedfast** [comment]
I would expect it to fail since you do not have a trusted root certificate in your database, however, S/MIME messages often contain at least the intermediate certificates (and *can* contain the root certificate).

**Comment by jstedfast** [comment]
Perhaps you can debug this a bit for me? Set a breakpoint in DefaultSecureMimeContext.cs in the following method:

```csharp
protected override Org.BouncyCastle.Utilities.Collections.HashSet GetTrustedAnchors ()
{
	var anchors = new Org.BouncyCastle.Utilities.Collections.HashSet ();
	var selector = new X509CertStoreSelector ();
	var keyUsage = new bool[9];

	keyUsage[(int) X509KeyUsageBits.KeyCertSign] = true;
	selector.KeyUsage = keyUsage;

	foreach (var record in dbase.Find (selector, true, X509CertificateRecordFields.Certificate)) {
		anchors.Add (new TrustAnchor (record.Certificate, null));
	}

	return anchors;
}
```

I want to know what anchors are getting added to that hash set. There *should* be none in your case afaik.

If there are anchors being added, then that is likely the problem.

**Comment by Compufreak345** [comment]
There are no anchors added:
![image](https://user-images.githubusercontent.com/10026694/27578799-73cdde80-5b25-11e7-98f9-18c9a4073700.png)

I'll try to dig a bit deeper into the verification process as I set it up for debugging now.

**Comment by Compufreak345** [comment]
Update:
There seems to be an exception about the empty anchors that gets swallowed , leading to the process returning true:
![image](https://user-images.githubusercontent.com/10026694/27578962-1cc2a25a-5b26-11e7-97eb-c19c341cd33b.png)

![image](https://user-images.githubusercontent.com/10026694/27578997-45482c5e-5b26-11e7-8dc9-ebc9cc6e83a9.png)

![image](https://user-images.githubusercontent.com/10026694/27579034-69bf4342-5b26-11e7-8896-c029481ce70e.png)

![image](https://user-images.githubusercontent.com/10026694/27579070-8bde07a6-5b26-11e7-8115-7ece92bc7687.png)

![image](https://user-images.githubusercontent.com/10026694/27579101-a509c2ec-5b26-11e7-9382-53554f7a9381.png)

I'd guess the value of certificate.ChainExceptions needs to be checked somewhere in the process.

**Comment by jstedfast** [comment]
Yea, that was the intention... I'll take a look. Thanks for digging into this for me.

**Comment by jstedfast** [comment]
Can you try the following patch?

```
diff --git a/MimeKit/Cryptography/SecureMimeDigitalSignature.cs b/MimeKit/Cryptography/SecureMimeDigitalSignature.cs
index f4028bf3..a7ef0e06 100644
--- a/MimeKit/Cryptography/SecureMimeDigitalSignature.cs
+++ b/MimeKit/Cryptography/SecureMimeDigitalSignature.cs
@@ -168,6 +168,12 @@ namespace MimeKit.Cryptography {
                                throw vex;
                        }
 
+                       if (ChainException != null) {
+                               var message = string.Format ("Failed to verify digital signature: {0}", ChainException.M
essage);
+                               vex = new DigitalSignatureVerifyException (message, ChainException);
+                               throw vex;
+                       }
+
                        try {
                                var certificate = ((SecureMimeDigitalCertificate) SignerCertificate).Certificate;
                                valid = SignerInfo.Verify (certificate);

```

**Comment by jstedfast** [comment]
I've committed the above patch, but I have to warn you that I had to set `parameters.EnableRevocation = false` due to the fact that it's *very* likely users of this library will not have CRLs in their database (the unit tests certainly don't and so they all fail w/o that change).

**Comment by jstedfast** [comment]
At some point I guess I'll have to implement something similar to the auto-fetching logic for PGP keys in the `OpenPgpContext` context and make it such that the `SecureMimeContext` auto-fetches CRLs from the web so that it can properly enable revocation checks.

**Comment by jstedfast** [comment]
Hmmm, the following docs seem to suggest that revocation is only checked when the root certificate is self-signed: https://technet.microsoft.com/en-us/library/ee619754(v=ws.10).aspx

Perhaps I can generate a CRL for my self-signed certs used in my unit tests...

**Comment by jstedfast** [comment]
Sorry if I end up spamming you with my comments here, but I'm mostly taking notes for myself to think about later.

The following link has info about how to create CRLs using openssl which I could add to my `gencerts.sh` script that generates the certificates for my unit tests:
https://jamielinux.com/docs/openssl-certificate-authority/certificate-revocation-lists.html

Here is some info about Online Certificate Status Protocol (OCSP):
https://jamielinux.com/docs/openssl-certificate-authority/online-certificate-status-protocol.html
