### ISSUE TITLE
How to check if PGP/MIME signed & encrypted message is signed?

### ISSUE THREAD

**Issue by Compufreak345** [jstedfast/MimeKit#314]
Hi,

I sent a PGP/MIME signed & encrypted message using this code:
```
using (AclGnuPGContext ctxt = new AclGnuPGContext("<password>"))
            message.Body = MultipartEncrypted.SignAndEncrypt(ctxt, message.From.Mailboxes.First(), DigestAlgorithm.Sha1, EncryptionAlgorithm.Aes256,  message.To.Mailboxes, message.Body);
```

Afterwards I try to receive this E-mail, verify the signature and decrypt it. Unfortunately, I can decrypt it - but I am not able to verify the signature as it is not of type MultipartSigned. Any ideas how I can verify the signature? First checking for MultipartSigned and afterwards checking for MultipartEncrypted doesn't work either.

```
var message = client.GetMessage(i);
          if (message.Body is MultipartEncrypted encrypted)
          {
            message.Body = encrypted.Decrypt();
          }
          if (message.Body is MultipartSigned multipartSigned)
          { // This code is not reached.
            var signed = CheckSignature(message.Body);
          }
```

Thanks & best regards,
Compu

P.S.: I'll come back to the S/MIME issue - but currently my head is wrapped around this PGP-stuff :>

**Comment by jstedfast** [comment]
When you call the Decrypt() method, you need to call the version that has an `out DigitalSignatureCollection`

http://www.mimekit.net/docs/html/M_MimeKit_Cryptography_MultipartEncrypted_Decrypt_1.htm
