### ISSUE TITLE
Error sending email through SmtpClient to an Office 365 server

### ISSUE THREAD

**Issue by robsonfelix** [jstedfast/MimeKit#316]
I keep receiving the exception bellow...

> System.NotSupportedException: No compatible authentication mechanisms found.

However I am able to successfully send the same message using System.Net.SmptClient with the same parameters. I am trying with the same contents (from, to, subject and header) and all of them are plain-text.

I already tried to understand how this is not working by reading the trace files for the socket on both cases. What I see is that when the credentials are being sent, something seems to be different. Probably due to the authentication mechanism used at first on Authenticate. I see that on both cases the "Microsoft Unified Security Protocol Provider" is chosen. I see on the bytes being send that the header is the same and rest of the bytes are the same - after the 1st LF til the end.

I **am** able to send messages to other server types (including gmail) but not Office 365. I can successfully use MailKit for reading messages with Office 365 but not SMTP.

I tried to change parameters such as StartTls, Ssl, etc, but nothing happens.

I am going nuts here trying to figure out what is going on... Thoughts?

My code snippets are:

**System.Net.SmptClient**

`RemoteCertificateValidationCallback certificateValidation = (sender, cert, chain, sslPolicyErrors) => true;

ServicePointManager.ServerCertificateValidationCallback += certificateValidation;

var client = new System.Net.Mail.SmtpClient(_host, _port);
client.Credentials = new NetworkCredential(_user, _pwd);
client.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
client.EnableSsl = true;
client.ServicePoint.Expect100Continue = false;
client.Send(_user, _to, _subject, _body);

ServicePointManager.ServerCertificateValidationCallback -= certificateValidation;`

**MailKit**

`RemoteCertificateValidationCallback certificateValidation = (sender, cert, chain, sslPolicyErrors) => true;

var logger = new ProtocolLogger(@"smtp.log");
var client = new MailKit.Net.Smtp.SmtpClient(logger);
client.CheckCertificateRevocation = false;
client.ServerCertificateValidationCallback += certificateValidation;
client.Connect(_host, _port, MailKit.Security.SecureSocketOptions.StartTls);
client.AuthenticationMechanisms.Remove("XOAUTH2");
client.Authenticate(Encoding.ASCII, new NetworkCredential(_user, _pwd));
client.Send(email);
client.Disconnect(true);

ServicePointManager.ServerCertificateValidationCallback -= certificateValidation;`

**Comment by generik0** [comment]
You closed the issue? no update? What was the issue?
