### ISSUE TITLE
SMTPClient is not closing file streams passed to it in the MimePart object

### ISSUE THREAD

**Issue by shancockdc** [jstedfast/MimeKit#317]
I've written a Windows service that checks a database for messages and attachment urls that need to be sent. When the email is sent, the files that are used as attachments are locked indefinitely by the service. As you can see below, I've followed the examples and I'm passing in a stream to the ContentObject. It appears that MimeKit isn't closing this stream when it's done with it, leaving the file locked. 

`
foreach (DataRow attachmentRow in attachmentsDataTable.Rows)
                            { 
                                // Create an attachment for the file located at path
                                String path = attachmentRow["AttachmentUNCPath"].ToString();
                                MimePart attachment = new MimePart(attachmentRow["MediaType"].ToString(), attachmentRow["MediaSubtype"].ToString())
                                {
                                    ContentObject = new ContentObject(File.OpenRead(path), ContentEncoding.Default),
                                    ContentDisposition = new ContentDisposition(ContentDisposition.Attachment),
                                    ContentTransferEncoding = ContentEncoding.Base64,
                                    FileName = Path.GetFileName(path)
                                };
                                multipart.Add(attachment);
                                
                            }
`

**Comment by jstedfast** [comment]
You need to dispose that stream because MimeKit has no idea when it is safe to do so.

I would recommend using a MemoryStream or a MimeKit.IO.MemoryBlockStream so that you don't have to dispose.

**Comment by shancockdc** [comment]
Won’t that cause a memory leak if the MemeoryStream or MemoryBlockStream is not closed? Isn’t it just holding memory instead of a file handle indefinitely?

Thanks,
Scott

**Comment by jstedfast** [comment]
MemoryStream *might* depending on the implementation I suppose (i.e. if it uses a native memory allocator instead of `new byte[size]`), but MemoryBlockStream will not leak.

MemoryBlockStream is also more efficient than MemoryStream since resizing it never needs to clone the existing content buffer.
