### ISSUE TITLE
Sharing violation on pubring.gpg

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#318]
Exception:

> And error of type 'System.IO.IOException' occurred, message from server was; 'Sharing violation on path /Users/thomashansen/.gnupg/pubring.gpg'

I was of the impression that your operations on GnuPG was atomic, and didn't need thread safety guards ...?

Is this correct? If so, I assume the above is simply a bug ...?
If not, I'll need to implement my own locking, which is no big deal, but I'd still love to know if it's a bug in my code or in MimeKit ...

PS!
Yup, we're obviously talking about `OpenPgpContext`, and highly likely its `Import` method.
Since this happens in a worker thread, I haven't been able to pin down where it happens, which I could if you need it - But my assumption is that it happens during import of public PGP keys, since I have logic that will do that in my "POP3 fetcher thread", and it's actually the only thing I do in regards to GnuPG in these threads ...
I could send you my code if you wish ...?

Thx,

Thomas

**Comment by jstedfast** [comment]
Unfortunately there's no way to do atomic file operations on files in .NET that I know of :(

Importing from multiple threads is probably not a good idea in general.

**Comment by polterguy** [comment]
Do you have any suggestions ...?
Obviously a slim reader/writer lock should fix the problem, right ...?

**Comment by jstedfast** [comment]
yea, that should work

**Comment by polterguy** [comment]
I'm going to close this ... :)
