### ISSUE TITLE
Bouncy Castle meta information removal request

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#319]
There's this principle in security that one should never give away information about the implementation used to secure a system, which brings me to the PGP message created by MimeKit, which includes not only the fact that Bouncy Castle was used to encrypt the message, but even its versioning number.

Would it be possible to remove this, and make the PGP encrypted messages completely anonymous?

PS!
The above reasoning is the reasons why among other things the HTTP standard explicitly encourages implementers to not give away versioning numbers of the software used to handle the HTTP request ...

**Comment by jstedfast** [comment]
Yea, it's something I've pondered in the past as well. I'm pretty sure I saw a way to do this in the BC API, but just kept getting sidetracked :)

**Comment by polterguy** [comment]
While we're at it, the default created MIME ID for messages also tends to _"give away"_ some relatively private type of information. Example `0VUOEYEBW1U4.QRV7QH36T0Y33@Thomass-MacBook-Air.local`.

Not even sure if I could explicitly set it myself, as in if it's got a setter property - But especially for encrypted emails, the above is giving away a lot of information ...

Thx,

Can't wait to get my hands on your new stuff :D

.t

**Comment by jstedfast** [comment]
It looks like there's no way to avoid writing out a `Version:` header :(

ArmoredOutputStream.ResetHeaders() will clear all headers and then add back the `Version:` header.

The only thing I can think of is to disguise it as GnuPG or something?

**Comment by jstedfast** [comment]
Ah, you can do: `message.MessageId = MimeUtils.GenerateMessageId ("my-domain.com");

By default it uses your local hostname because that's the suggestion made by the specs.

**Comment by jstedfast** [comment]
Trying to figure out whether I should have an API for enumerating `PgpPublicKey`s or `PgpPublicKeyRing`s. A key *ring* is a collection of keys owned by a single user, whereas a *key* is just a single key owned by that user.

**Comment by polterguy** [comment]
Weird that you can't remove the PGP BC info. Do you know if this is mentioned as a criteria in OpenPGP or something? I'd suspect it would be considered a bad thing to do ...?

Regarding key rings versus keys, I wouldn't know. Normally I'd think people are looking for a specific key, and not a keyring ...?
At least that's what I am doing ...

About the MIME ID, am I too paranoid when I say I want to try to hide the local hostname? What alternatives could I use here, that still would be considered a "valid MIME ID" you think ...?

**Comment by jstedfast** [comment]
I don't think it matters that much since it's only the internal hostname of your machine, but I suppose it depends on what you name your machine (e.g. if you name it something sensitive, that might not be good).

I've added APIs to enumerate both keyrings and keys.

**Comment by polterguy** [comment]
You're the champ! :)

**Comment by polterguy** [comment]
Pst, ready to release, only awaiting your NuGet package ... :)

For the record, this stuff is built with your baby ... ;)

https://gaiasoul.com/2017/08/07/sephia-five-military-grade-cryptography/

**Comment by jstedfast** [comment]
Sorry about that. Just released 1.18.0 to nuget :)

**Comment by polterguy** [comment]
Thx mate, did you read the link I sent you ...? :)

**Comment by jstedfast** [comment]
One thing that I've noticed that Outlook does is it'll warn you if the message you are reading was sent by someone you've never received email from before (or received very few emails from).

But an improvement on this feature might be to say "this email address looks similar to another email address in your address book, it may be a phishing email". I haven't really delved into fuzzy matching algorithms, but I think this would be one area that might be useful. Just figured I'd mention it since it seems to align with what Sephia 5 is all about.

One of the problems I have with GMail is that it seems to collect every address that I've ever had contact with into my addressbook, and so when I go to type an address, if johndooe@gmail.com has sent me an email and I want to send an email to johndoe@gmail.com, it might autocomplete to johndooe instead of johndoe, exacerbating the "oops, sent it to the wrong person" catastrophe.

**Comment by polterguy** [comment]
Interesting suggestions all of them. Your final point, I largely have a fix for, though not entirely. Yet still "good enough" I think, which is to create some better sorting when searching for contacts, according to volume, and/or last sent/received ...

**Comment by polterguy** [comment]
```

/*
 * Opening connection, and performing the search.
 *
 * Notice, this query will select the 5 top contacts whom you have 
 * previously received emails from, starting out with the given query, 
 * in the name or email, in addition to that it will sort according to 
 * whom you last received an email from, and exclude contacts that have
 * been explicitly marked as spam senders.
 *
 * Which further will reduce the risk of sending an email to the wrong 
 * contact, since it is more likely that you would want to send an email 
 * to a person whom you have recently received an email from.
 *
 * Credits goes to my lawyer, and Jeffrey Steadfast, who proposed this 
 * little trick.
 */
p5.mysql.connect:[sephia]
  p5.mysql.select:@"select c.name, c.email from contacts c
inner join emails e on e.sender = c.id
inner join (select sender, MAX(date) maxDate from emails group by sender) e2 on e.sender = e2.sender and e.date = e2.maxDate
where (c.name like @query or c.email like @query) and (c.spam is null or c.spam = 0)
order by e.date desc
limit 5"
    @query:"{0}%"
      :x:/@get-widget-property/*/*?value
```

Basically, it will select the top five contacts, whom sent you an email, sorted according to who sent you an email most recently, excluding "spam" contacts, having the name or email starting out with whatever you type into the search query text box.

Pretty nifty if you ask me ...

Thx mate :)

.t

**Comment by jstedfast** [comment]
Cool! That would definitely be useful :)

**Comment by jstedfast** [comment]
What should we do about this? I'd like to get this resolved before making the 1.18.1 release if we can, but that probably means either giving up on it or else setting it to some other hard-coded value that disguises the real version details.

**Comment by polterguy** [comment]
Hmm, I don't know. To be honest with you, I have seriously considered forking BC, optionally creating wrappers around it, using the original base as a foundation. There are other arguments in favour of doing such a thing too, such as that the code is not very intuitive, and highly _"C# 1.0'ish"_.

Such an act (of arguably desperation), would solve it though.

Have you tried speaking to the devs of BC ...?

**Comment by jstedfast** [comment]
Hah, looks like Peter Dettman actually fixed it. Now I mostly just need him to make a new release...

**Comment by polterguy** [comment]
Awesome!! Seems like I owe a lot of peeples out there some serious flowers!! :D

**Comment by jstedfast** [comment]
Potential bug in his fix: https://github.com/bcgit/bc-csharp/commit/53a508e381f21061c8c6f49f8c19c703faab2a38 (mostly documenting this for myself so I can find my comment again, hah!)

I just did a bit of testing and it seems that even w/o a new release of bc-csharp, I can set the "Version" header to `null` and what we get is:


```
-----BEGIN PGP MESSAGE-----
Version: 

.......
```

So it kinda sorta already works, but there's just an empty Version: header in the armored output.

I think we can accept that for now until Peter releases a new nuget (at which point I'll update my nuget references and we'll get no Version: header at all).

**Comment by polterguy** [comment]
Nifty!!
Still not entirely happy with the fact that it shows an empty _"Version:"_ bugger, since arguably, it is _"giving away information"_, that could be used to deduct which PGP lib is being used. But obviously it's better than having not only the _"BC"_ parts, but even the **freakin' version number** of BC.

Besides, agree. Important to get it out, for then later to update when we've got the real goods.

**Comment by jstedfast** [comment]
Looks like Oren Novotny has made a release of BouncyCastle.Portable with the fix, so I'm updating MimeKit.Portable, MimeKit.WindowsUniversal81 and MimeKit.NetStandard to use that instead.

Not sure if you are using the .netstandard1.3 version of MimeKit or the old-school .net45 version.

**Comment by polterguy** [comment]
Hmm, what's the different ...?

(I think I am using .net45)

**Comment by jstedfast** [comment]
.netstandard is the newer .NET Core stuff that Microsoft is pushing for use with ASP.NET

**Comment by polterguy** [comment]
My stuff is built on WebForms, hence it probably wouldn't work, without a __massive__ rewrite, which I don't see the point in.

> "Microsoft keeps on pushing, and I keep on rejecting" ... ;)

**Comment by polterguy** [comment]
[Funny link](https://www.youtube.com/watch?v=hCDAfa-NI-M) ... :D
