### ISSUE TITLE
Removal of trailing SP character in lines

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#320]
It's normally common courtesy to create a signature like the following.

--SP
Some signature here ...

**Notice the trailing SP character `" "`, before the CR/LF sequence** which starts the signature.

However, when I send unencrypted emails, this last trailing SP character seems to be removed. Am I doing something wrong here? Might it be that I encode my text parts incorrectly ...?

When I encrypt my message, the SP is preserved. My guess is that I am not using the correct Content-Transfer-Encoding or something ...?

Suggestions ...?

**Comment by polterguy** [comment]
PS!
Sorry for bugging you so much ...

**Comment by jstedfast** [comment]
MimeKit runs the message text through a filter that strips trailing whitespace based on the recommendation of the PGP/MIME specification.

What you might be able to do is to set the ContentTransferEncoding to QuotedPrintable or something. That should prevent that space from being stripped.
