### ISSUE TITLE
MimeKit vs. MimeKit Lite

### ISSUE THREAD

**Issue by k3davis** [jstedfast/MimeKit#321]
Hi there,

I can't locate any doc or FAQ entry etc. that explains the difference between these two builds. Perhaps I'm just missing it. Can someone explain the essential difference?

Thanks.

**Comment by jstedfast** [comment]
MimeKit Lite is a subset of MimeKit that does not include crypto support (e.g. S/MIME, PGP, and DKIM)

Hope that helps.
