### ISSUE TITLE
TemporarySecureMimeContext never looks at SecureMailboxAddress.Fingerprint when signing/encrypting

### ISSUE THREAD

**Issue by logicmediadk** [jstedfast/MimeKit#322]
When using SecureMailboxAddress along with the TemporarySecureMimeContext the fingerprint of the SecureMailboxAddress is ignored - the code only looks at the email address of the certificate.

**Comment by jstedfast** [comment]
Thanks!

**Comment by logicmediadk** [comment]
It works, thanks for the fast fix!
