### ISSUE TITLE
how to get ContentObject from MultipartReport object?

### ISSUE THREAD

**Issue by gunnicus** [jstedfast/MimeKit#324]
Hi, I have a message like this:

Content-Type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha1; boundary="boundaryOEJ6Ag=="

--boundaryOEJ6Ag==
Content-Type: multipart/report; report-type=disposition-notification; boundary="MDNBoundary"

--MDNBoundary
Content-Type: text/plain

The incoming message from AS2MSHLOCAL to AS2MSHLOCAL with Id <4a51cf4f-a3b1-4ec0-ab8a-d9df0daa87a1@cede98bd-3d3a-478a-8313-90839676791c> was received successfully. This is not a guarantee that the message has been processed by the receiving translator.

--MDNBoundary
Content-Type: message/disposition-notification

Original-Recipient: rfc822;AS2MSHLOCAL
Final-Recipient: rfc822;AS2MSHLOCAL
Original-Message-ID: <4a51cf4f-a3b1-4ec0-ab8a-d9df0daa87a1@cede98bd-3d3a-478a-8313-90839676791c>
Disposition: automatic-action/MDN-sent-automatically; processed
Received-Content-MIC: bjmVvydYlwhcV6hR1/SLhGoNst4=, sha1

--MDNBoundary--

--boundaryOEJ6Ag==
Content-Type: application/pkcs7-signature;  	name="smime.p7s"
Content-Disposition: attachment; filename="smime.p7s"
Content-Transfer-Encoding: base64

MIIFMwYJKoZIhvcNAQcCoIIFJDCCBSACAQExCzAJBgUrDgMCGgUAMAsGCSqGSIb3DQEHAaCCAzUw
ggMxMIICHaADAgECAhAtc9TXB/Brj03CCdAHoxznMAkGBSsOAwIdBQAwLDEqMCgGA1UEAxMhT2Jh
biBFbnRlcnByaXNlIE1lc3NhZ2luZyBSb290IENBMB4XDTE0MDEwNjA2NDc0MVoXDTM5MTIzMTIz
NTk1OVowIjEgMB4GA1UEAxMXc21hcnRzdHJlYW0ub2Jhbi5jb20uYXUwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQC2lAQv+a7GEdLsWHpxjXF/VKziAIL/Nda7U7kdXnbqdIPoOIOlKbai
XKszvnllP12itHTJ4NZTrsD7pD/FlDJhgz/3eyW3ZBE2nHOWs1Aprz7D3nvXlSQaE6tuHqCdbHrB
W0L6HESUxJ4+KyOXWjs7X8DYoCRWB61t+sT3wBhJYe4J30TQimBn4cJdKDRJPmizs7bBdyfMoV71
a5RY511wOf0XasAkyscerw/qJkqcLXefzmvtjVlZCqGAoEhggZEfMqQsff+gyvBZvGFy1oO/8XBP
LDO87+IDX/i4qqqCQs0rIrtCuTSVTiQcGTbfHM+7Kr4z/STivy6+FZoZvYRJAgMBAAGjYTBfMF0G
A1UdAQRWMFSAEBZPh8WYDrd1nr2ACUebn5ihLjAsMSowKAYDVQQDEyFPYmFuIEVudGVycHJpc2Ug
TWVzc2FnaW5nIFJvb3QgQ0GCEOwS5ael9eCnRfaJQdczRlEwCQYFKw4DAh0FAAOCAQEAX8Eld+3I
UPhgMfdh5Zhx5jXyq4Mshc1MazyX0BGyEpdVnx+DrUOOfJ8/qhPPuWnxQ6VPpJYiMgj3nX+ddGDm
8qjA+mxg1ilQRliwjZoXMG5ms/Rpnz2n+y32fJvI4qqYNTQrw0oq3+XkRih+WLyTE3QZfwcvc8LX
KqgccM+eEL+bSg9DvmBnQMrq3UoSeADgnVgdUJkGGIuIzKzSVXAtm0UOPQCLv/5dnusnmWXRXqqD
tjbVBaW13mz0MXXGyVx6Jn9BTVQwWXJ7wGsXeMQV/c6ztbr0a6DViZO6Vq5QQHPBUZZXohO3Zke7
mYu1dkNtOiKyQjs3wVVKAWEhYyHDyzGCAcYwggHCAgEBMEAwLDEqMCgGA1UEAxMhT2JhbiBFbnRl
cnByaXNlIE1lc3NhZ2luZyBSb290IENBAhAtc9TXB/Brj03CCdAHoxznMAkGBSsOAwIaBQCgXTAY
BgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xNzA2MjgxMzI1NTJaMCMG
CSqGSIb3DQEJBDEWBBQCW/TGIHItHL6bhaxse1UOH2kUmDANBgkqhkiG9w0BAQEFAASCAQA8EuVF
cma2I+1Fj62jTL4sUEBdcCluoBEp0Or2SndovFlgS5MPq/jf6sy+JF7mxhIphzWhdsnCha4wwLJg
xEo8pdSC2vV19GmLNn0NfYkYrr8Pgdxrzj9TNiTCNht5mbgr1kzGEtyXDCHia5w4i5MCPXxcuecZ
JaVdmWzn35RssvyZqGI+ZV3RS+NkWh0hauh2Oj4IgO5CaPXHjjp7iO8hkY3fIWm1hE2Q4f+nKqh3
VhruK4cJIbTQZ7zNCotDkFtFW2dIzFpfEILsi7o35Yd6inBsMQLYGTrZ7gCu/owiMAnNBGrDpiz+
6NYQ71enzwS7v+9Tt6sgRG1AOEJNEwFV

--boundaryOEJ6Ag==--

The problem is that how can I get the raw content of the first part? I can get a MultipartReport object from the first part, but that object doesn't have ContentObject property.

**Comment by jstedfast** [comment]
A `Multipart` isn't supposed to have a `ContentObject`, it has child parts. You have to access the first  child of the `MultipartReport`, cast it to a `MimePart` and then access its `ContentObject`.
