### ISSUE TITLE
Feature request: "HasValidRecipientCertificate" and "HasValidSignerCertificate" on SecureMimeContext

### ISSUE THREAD

**Issue by Nikkelmann** [jstedfast/MimeKit#325]
I have at case where I need to send a mail to multiple recipients where some do not have certificates.
In this case I will create two MimeMessages, one that is signed and encrypted and one that is not.
For this to work I need to know which recipient emails have a valid recipient certificate and which "from" emails have a valid signer certificate.

Having
```
public bool HasValidRecipientCertificate(MailboxAddress)
public bool HasValidSignerCertificate(MailboxAddress)
```
on SecureMimeContext would solve this.

**Comment by jstedfast** [comment]
Seems like a reasonable request... I'll look into adding API for this.

Thanks!
