### ISSUE TITLE
Adding custom x-header is adding garbeled value

### ISSUE THREAD

**Issue by nigash** [jstedfast/MimeKit#326]
Hi, i am reading Message-ID of a message and adding new x-header with value of MessageID.
new x-header added has garbled value. its not happening for all messages but few.

strMsgId = "<" + MimeMessage.MessageId + ">";
                if (strMsgId != null)
                {
                    MimeMessage.Headers.Add("X-MsgID", strMsgId.ToString());
                }

its reading message id correctly. In debug mode i see X-MsgID added correctly, but when i save data as eml file.
header X-MsgID is contains characters like 
 =?us-ascii?q?=

**Comment by jstedfast** [comment]
that value has been encoded as per the rules defined in rfc2047

if you parse said message using a MIME-compliant library, it will decode the value and you'll get back the original value.

**Comment by nigash** [comment]
i open the message in outlook and it doesn't show the value correctly.

**Comment by jstedfast** [comment]
Outlook is a mail client and not a mime library. The header only gets encoded if it is too long to fit on a single line.

**Comment by nigash** [comment]
is it an option to not encode the header?

**Comment by jstedfast** [comment]
Why is it important that this not get encoded?

**Comment by nigash** [comment]
we have multiple system working on these headers. one of them will add the header (using MimeKit) all the other downstream systems will read this header along with there regular processing. These downstream system will read the encoded header. There will be mismatch in the repository, which will cause failure in validations.

**Comment by jstedfast** [comment]
Can you add logic to properly decode the values in the downstream versions?
