### ISSUE TITLE
Handling of = by base64 decoder at 4096 byte boundaries

### ISSUE THREAD

**Issue by atesti** [jstedfast/MimeKit#327]
Hi!

I am trying to understand how exactly Base64Decoder.Decode works. As far as I see it, FilterStream lets it decode 4096 bytes at a time and each = decodes as 0 and after the buffer is decoded a second pass is run backwards, ignoring characters like space or newline, scanning and counting = characters.

This second pass runs for each 4096 byte input buffer.

It tries to chop away bytes from the output.

What happens if the Reader passes another 4096 block right between more than one = character? outptr cannot be decremented below output.

Wouldn't the library then decode one byte too many?

Also why does this function even store npad as class member and why is it able to use npad in the first pass? Can = appear anywhere in base64 documents (not by standard, but in real life?) What's the best decoding for that? Ignore? Or drop one byte per = anywhere?

I hope I did not misunderstand anything.

**Comment by atesti** [comment]
I think I got it, you can close it, sorry:

The block containing padding is not full yet with 4 input characters whenever the block boundary happens and no data has been put into the ouput buffer yet in that case. Therefore outptr can always be decremented and there is no problem.

**Comment by jstedfast** [comment]
Cool, glad you figured it out :)
