### ISSUE TITLE
Watch MimeKit go into warp!! :)

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#328]
Howdy, this isn't an issue request per se, but I remember we had a discussion some years ago, about what MIME and MimeKit really could be utilised for. And since I believe I have brought it pretty way out of its box, I think you'd like to see this.

Basically, I have created a PGP cryptographically secured _"AppStore"_ (I refer to it as the _"Bazar"_). This Bazar will run on a micro web operating system, allowing the user to install apps into his micro web OS, on the run, without even restarting the server process (built in Hyperlambda).

### Why is this interesting to you?

Because I am verifying that the app's zip file, has been cryptographically signed, with a trusted PGP key, before I allow for it to be installed. Then the appstore's _"database"_, is a simple static file, on the web, which is downloaded as the app store is being initialised.

This prevents man in the middle attacks, and a whole range of other security issues, allowing for malicious code to be installed into my users' micro web OS. Giving my users a cryptographically secure guarantee, of that the app is safe and secure to install.

The actual MIME message, which contains the app, is actually just an application/zip MIME entity, which is cryptographically signed, with a PGP key, which is found in the web os' "trusted app distributor's" configuration file, allowing anyone to easily setup their own Bazar, by forking mine, adding their own PGP key's fingerprint, having a secure app distribution mechanism, as long as they can host and edit a single "app database" file online, which could in theory be stored at DropBox, Google Disc, WordPress, or your GitHub repository for that matter. Allowing for a distributor to later, add to this app database, by simply adding a new "app entry" into his file, which he is storing online somewhere.

Here is a screenshot of the actual Bazar, and how it looks like when the user is installing an app.

![alt Sephie Five installation process](https://phosphorusfive.files.wordpress.com/2017/08/screen-shot-2017-08-17-at-20-40-10.png)

[Here is the code](https://github.com/polterguy/phosphorusfive/tree/master/core/p5.webapp/bazar) for the actual Bazar.

And [here is the code for the micro web operating system](https://github.com/polterguy/phosphorusfive/tree/master/core/p5.webapp/desktop).

As the user is visiting his Bazar, from within his own micro web os, the [following file](https://raw.githubusercontent.com/polterguy/phosphorusfive/master/core/p5.webapp/bazar/configuration/apps.hl) is being downloaded, and becomes the available apps on my user's web server, that my users can install themselves, on their own web server.

However, it allows for multiple _"Bazar declaration files"_, allowing for aggregating multiple Bazars together into one, kind of like apt-get, and it also allows the web OS to have multiple _"trusted app distributors"_, by allowing him to add multiple PGP fingerprints to his list of trustees.

It's not entirely done quite yet, but I think the use-case for MIME, PGP and MimeKit is quite flabbergastingly cool to be honest with you. For the record, I de-serialise the MIME envelope, as it's downloaded, directly into a temp folder, without loading it into memory, to conserve memory on the server. Allowing for the server to download humongously large apps, without even having to do as much as a reboot of the web-server process.

[Here is a video](https://www.youtube.com/watch?v=_nFebKPjA3Y) demonstrating it in practice.

The only app I've got so far, is [Sephia Five](https://github.com/polterguy/sephia-five), which is another kick-ass cool example of MimeKit I think myself.

Sorry for this shameless plug, but I think you'd be interested in seeing use-cases of MimeKit out there ... :)

PS!
Did you have a changelog somewhere for the feature list you created in regards to convenience PGP methods somewhere ...?
Eager to get started ...!! ;)

**Comment by polterguy** [comment]
I'll soon be releasing this to the mass market, hope there's no holes in MimeKit ... ;)

[viddi](https://www.youtube.com/watch?v=KTgkZoZq1l0)

**Comment by polterguy** [comment]
Great, thx mate :)

**Comment by jstedfast** [comment]
No prob :)

**Comment by polterguy** [comment]
Did you see the viddi ...? :)

**Comment by jstedfast** [comment]
Yea, the paypal integration is a nice touch btw :)

**Comment by polterguy** [comment]
If we're serious about creating stuff that facilitates for change, it's important we bring _"balance to the force"_, by ending the war between _"free software"_ and _"proprietary software"_ ... :D
