### ISSUE TITLE
SQLite dependency causes version problems

### ISSUE THREAD

**Issue by fubar-coder** [jstedfast/MimeKit#33]
The SQLite dependency causes problems for us because of versioning issues. Please place the SQLite stuff in a separate library (e.g. MimeKit.CertStore.SQLite.dll) and just use an interface in the core library (e.g. MimeKit.dll, ICertStore). This would have the nice side effect to allow custom certificate stores.

**Comment by kae36** [comment]
Is there a link to the issue that was opened that could be added in the comments?

**Comment by jstedfast** [comment]
https://github.com/jstedfast/MimeKit/pull/48 and https://github.com/jstedfast/MimeKit/pull/52
