### ISSUE TITLE
Clarification on MailboxAddress.TryParse

### ISSUE THREAD

**Issue by LeeBear35** [jstedfast/MimeKit#331]
In some testing I confirmed that an address can have only the "local" part without the domain information, so it is not a valid Internet Address. My test:

      MimeKit.MailboxAddress mkMailBox = default(MimeKit.MailboxAddress);
      bool actual = MimeKit.MailboxAddress.TryParse("bounty", out mkMailBox);

      Console.WriteLine(mkMailBox);
      Console.WriteLine("Address {0}", mkMailBox.Address);
      Console.WriteLine("Name {0}", mkMailBox.Name);
      Assert.IsTrue(actual, string.Format("Extracted {0}", mkMailBox));

Results:
bounty
Address bounty
Name

I would have expected parsing would have returned False since the domain information is missing.

**Comment by jstedfast** [comment]
It's accepted because of historical use on Unix systems where you could send a message to a local user w/o specifying a domain.

You can override this behavior by using a ParserOptions with the AllowAddressWithoutDomains set to false.

http://www.mimekit.net/docs/html/P_MimeKit_ParserOptions_AllowAddressesWithoutDomain.htm

**Comment by nitinag** [comment]
You can also use just postmaster without a domain - SMTP RFC 5321
> The reserved mailbox name "postmaster" may be used in a RCPT
> command without domain qualification (see Section 4.1.1.3) and
> MUST be accepted if so used.
> https://tools.ietf.org/html/rfc5321#section-2.3.5

**Comment by EvanMulawski** [comment]
@jstedfast Even when specifying that parser option, it still returns true for addresses without a domain. Is this a bug (v2.0.1)?

![image](https://user-images.githubusercontent.com/1044791/36067192-647c9f60-0e86-11e8-881d-9a7230ac8b9b.png)

**Comment by jjxtra** [comment]
It's been a bug for over a year now, has not been fixed, not sure why this issue was closed...

**Comment by jjxtra** [comment]
Until it is fixed, this regex works pretty well:
```
(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
```
