### ISSUE TITLE
Allow MultipartEncrypted.Encrypt to work without a OpenPgpContext

### ISSUE THREAD

**Issue by realityexists** [jstedfast/MimeKit#332]
When I try to encrypt a MimeMessage using the following code
```message.Body = MultipartEncrypted.Encrypt(toPublicKeys, message.Body);```
it throws an exception:
```
System.NotSupportedException: You need to subclass MimeKit.Cryptography.OpenPgpContext or MimeKit.Cryptography.GnuPGContext and then register it with MimeKit.Cryptography.CryptographyContext.Register().
   at MimeKit.Cryptography.CryptographyContext.Create(String protocol)
   at MimeKit.Cryptography.MultipartEncrypted.Encrypt(IEnumerable`1 recipients, MimeEntity entity)
```

However it works if I pass in a "dummy" context:
```message.Body = MultipartEncrypted.Encrypt(new EncryptPgpContext(), toPublicKeys, message.Body);```

where `EncryptPgpContext` is simply:
```
    public class EncryptPgpContext : OpenPgpContext
    {
        protected override string GetPasswordForKey(PgpSecretKey key)
        {
            throw new NotImplementedException("No need for a password just to encrypt!");
        }
    }
```

It seems that I don't need to call `CryptographyContext.Register()`, contrary to the exception message. Could MimeKit handle this internally to simplify the API for the user code? That is, if no context is registered and the user is only trying to encrypt then create just go ahead and encrypt with the default settings provided by a dummy context like this instead of throwing an exception.

**Comment by jstedfast** [comment]
I'm not sure how that works because it still needs to do public key lookups and OpenPgpContext can't do any type of key lookups since it doesn't know where to find the keys.

**Comment by realityexists** [comment]
I should clarify that `toPublicKeys` is an `IEnumerable<PgpPublicKey>` here. Perhaps the overload that takes `IEnumerable<MailboxAddress>` still needs a context.

**Comment by jstedfast** [comment]
Ah, ok, I was thinking you were passing in mailboxes which is the standard API that people use.

You found the *1* case out of dozens that works with a dummy context :)

**Comment by realityexists** [comment]
OK then, I'll consider myself lucky. :) Thanks for 2 great libraries, by the way! They've saved me a lot of work.
