### ISSUE TITLE
Yahoo Subject Encoding issue

### ISSUE THREAD

**Issue by sbalant** [jstedfast/MimeKit#335]
I send an email and the subject contains some accents : "Découvrez l'agenda data digital marketing de la rentrée !"
All the email clients read the subject except **yahoo**

Original message : 
Subject: =?iso-8859-1?q?D=E9couvrez?= l'agenda data - digital marketing
 de la =?iso-8859-1?q?rentr=E9e?=

Result in the yahoo mailbox :
Découvrezrentrée 

I've got this error when at least 2 words of the subject have an accent.

Can you add an option to encode all the characters of the subject ?

Thanks

**Comment by jstedfast** [comment]
Have you tried submitting a bug report to Yahoo?

It's pretty clearly a bug in their software.
