### ISSUE TITLE
Dot-stuff

### ISSUE THREAD

**Issue by burakcakirel** [jstedfast/MimeKit#338]
I'm signing multipart mail with DKIM.
When using ToString or WriteTo method, output of email contains dot sign at the first line (line 17).
Here is the mail:
[email_in.txt](https://github.com/jstedfast/MimeKit/files/1295807/email_in.txt)
[email_out.txt](https://github.com/jstedfast/MimeKit/files/1295808/email_out.txt)

So, when I check the email on mail client, it can't be displayed properly.

**Comment by jstedfast** [comment]
I don't see anything wrong. It is perfectly legal for a dot to appear at the start of a line.

dot-stuffing only needs to be done when sending a message over SMTP (in cases where the DATA command is used as opposed to the BDAT command) and the reverse needs to be done when downloading message from POP3, but saving a message to disk does not need to dot-stuff the message.

**Comment by burakcakirel** [comment]
Sorry, I think my question was not clear.

My purpose of using this library is that only signing emails with DKIM and sending this signed emails via SMTP. 

I try to sent this email with DKIM headers (email_out.txt) via SMTP, so I think this is the reason that mail client can't be displayed properly.

In that case, it should stuff a dot to every line starts with a dot, shouldn't it or what should I do to stuff a dot when signing email with DKIM?

**Comment by jstedfast** [comment]
You don't dot-stuff before DKIM signing, you need to dot-stuff after DKIM signing.

So basically, if email_out.txt is the DKIM signed message, you'll need to dot-stuff that text data as you push it to an SMTP server.

Hope that helps.
