### ISSUE TITLE
EML with smime.p7m not returning the attachment

### ISSUE THREAD

**Issue by LeeBear35** [jstedfast/MimeKit#340]
When using the parsed email I have a call to get all the body parts display a list of attachments using:
foreach (MimeKit.MimeEntity a in this.m_msg.BodyParts)

For the email with the smime.p7m attachment it only reports back one body part, so it is excluding the smime.p7m attachment. From what I can see the message is coded correctly unless the boundary header for the attachment is causing the issue. Because of security reasons I had to remove the specific information and placed comment blocks for the parts removed. You should be able to put your own data in those sections an recreate the issue.

*****************
**email headers**
*****************
Content-Type: multipart/mixed; 
 boundary="----=_NextPart_534107383-199019745-275921289"
**To Header was here**

------=_NextPart_534107383-199019745-275921289
Content-Type: multipart/related; 
 boundary=----=_NextPart_292834222-1065845386-185965810

------=_NextPart_292834222-1065845386-185965810
Content-Type: multipart/alternative; 
 boundary=----=_NextPart_1035112134-907314731-1666610832

------=_NextPart_1035112134-907314731-1666610832
Content-Type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable

**********************
**valid HTML message**
**********************

------=_NextPart_1035112134-907314731-1666610832--

------=_NextPart_292834222-1065845386-185965810--

------=_NextPart_534107383-199019745-275921289
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7m"
Content-Type: multipart/signed; 
 boundary=----=_NextPart_1214402795-1129390199-1308539742

****************************
**valid attachment message**
****************************

------=_NextPart_534107383-199019745-275921289--

Also if it helps:
? this.m_msg.Attachments
{System.Linq.Enumerable.WhereEnumerableIterator<MimeKit.MimeEntity>}
    Current: null
    System.Collections.IEnumerator.Current: null
    current: null
    enumerator: null
    predicate: {Method = {Boolean <get_Attachments>b__100_0(MimeKit.MimeEntity)}}
    source: {MimeKit.MimeMessage.<EnumerateMimeParts>d__96}
    state: 0
    threadId: 9
    Results View: Expanding the Results View will enumerate the IEnumerable

**Comment by jstedfast** [comment]
BodyParts only returns leaf parts, not multiparts and the smime.p7m part is a multipart/signed.

Really, it's just malformed MIME because it states that the multipart is an attachment which it cannot be (multiparts can't be attachments - that literally doesn't make any sense).

**Comment by LeeBear35** [comment]
Thank Jeff, that is along the lines of what I expected.

Subject: Re: [jstedfast/MimeKit] EML with smime.p7m not returning the attachment (#340)


BodyParts only returns leaf parts, not multiparts and the smime.p7m part is a multipart/signed.

Really, it's just malformed MIME because it states that the multipart is an attachment which it cannot be (multiparts can't be attachments - that literally doesn't make any sense).

**Comment by jstedfast** [comment]
no prob :)
