### ISSUE TITLE
Missing informations in SecureMimeDigitalSignature

### ISSUE THREAD

**Issue by apatenotre** [jstedfast/MimeKit#341]
Hi,

I am currently trying to get the signature algorithm out of a signed message. I tried to use the DigestAlgorithm field from the SecureMimeDigitalSignature object returned by the Verify method of a MultipartSigned, but the field is empty. 
![image](https://user-images.githubusercontent.com/20488504/30808677-5ea1398c-a1ff-11e7-9b86-92a844937f50.png)

Actually this field is never updated in a S/MIME context
![image](https://user-images.githubusercontent.com/20488504/30808714-7b8e111e-a1ff-11e7-96ae-1d72ac41deb5.png)

Is this on purpose ? If yes, how can I get the signature algorithm ?

Thanks,
Adrien

**Comment by jstedfast** [comment]
It wasn't on purpose, just overlooked.

**Comment by jstedfast** [comment]
Thanks for reporting this :)

**Comment by apatenotre** [comment]
Thanks for you fast reply and commit !
Adrien
