### ISSUE TITLE
Possible issue with QuotedPrintable and explicit charset

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#343]
Howdy, I have an email that looks like the following ...

```
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
```

Below is a snippet of some of its content ...

```
Dette er en bekreftelse p=E5 at din epost er mottatt
```

The `=E5` parts are supposed to look like this `å`. However it doesn't ...?

I am using the following code to decode it ...

```
            // Creating a stream to decode our entity to.
            using (MemoryStream stream = new MemoryStream ()) {

                // Decoding content to memory.
                part.ContentObject.DecodeTo (stream);

                // Resetting position and setting up a buffer object to hold content.
                stream.Position = 0;
                object buffer = null;

                // Checking how to handle content, which can be either binary or text.
                if (HandlePartAsText (part)) {

                    // Content is text of some kind, decoding to text through StringReader.
                    StreamReader reader = new StreamReader (stream);
                    buffer = reader.ReadToEnd ();

                } else {

                    // Content is binary, simply returning byte[] value raw.
                    buffer = stream.ToArray ();
                }

                // Putting content into return node for MimeEntity.
                entityNode.Add ("content", buffer);
            }
```

Do I need to check it's chartype, and parse it explicitly using the specified encoding myself?
I thought MimeKit took care of this automatically for me ...?

**Comment by jstedfast** [comment]
If you are going to decode it like that, keep in mind that the decoded byte stream will be in the iso-8859-1 encoding and not UTF-8 (which is what I think StreamReader assumes by default).

I'm pretty sure that StreamReader can take a System.Text.Encoding argument (or at least has an Encoding property).

The other option is to use TextPart.Text which does the decoding and charset conversion for you.

**Comment by jstedfast** [comment]
Oh, and to get the proper charset, you can do:

```csharp
var charset = part.ContentType.Charset ?? "iso-8859-1";
var encoding = Encoding.GetEncoding (charset);
```

Or something like that... to see how TextPart.Text does it, see here: https://github.com/jstedfast/MimeKit/blob/master/MimeKit/TextPart.cs#L299

That might be a little more robust than the snippet I pasted above ;-)

**Comment by polterguy** [comment]
Gr8 :)
So, which parts can I expect to be `TextPart`s ...?

Thx ...

**Comment by polterguy** [comment]
Would this work ...?

```
private void ProcessMimePartInline (MimePart part, Node entityNode)
{
    var txtPart = part as TextPart;
    if (txtPart != null) {

        // Part is text part.
        entityNode.Add("content", txtPart.Text);

    } else {

		// Creating a stream to decode our entity to.
		using (MemoryStream stream = new MemoryStream()) {

			// Decoding content to memory.
			part.ContentObject.DecodeTo(stream);

			// Resetting position and setting up a buffer object to hold content.
			stream.Position = 0;

			// Putting content into return node for MimeEntity.
			entityNode.Add("content", stream.ToArray ());
		}
	}
}
```

**Comment by jstedfast** [comment]
Yea, that looks like it should work

**Comment by polterguy** [comment]
Thx mate, just ran it through my inbox, and it seems to be working :)
