### ISSUE TITLE
How to get Sender IP Address using MimeKit

### ISSUE THREAD

**Issue by createanaccount43** [jstedfast/MimeKit#347]
Hello,

Is there are simple way to get the IP address of the sender from EML files using MimeKit Parser?

Thanks

**Comment by jstedfast** [comment]
You'll likely want to look in the last `Received:` header. Typically these headers will be in the form:

`Received: from {senderHostName} ({senderIPAddress}) by ...`

A quick hack might be to make sure the header value starts with "from " (after eating any leading whitespace) and then scanning for the first '(' character.

If you want to see a more robust solution to parsing these Received headers, see the logic starting at https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Header.cs#L484 and ending at https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Header.cs#L666

At some point I might try to use `Header` subclasses for various types of header types (Message-Id, Address, Received, etc), but for now, it's all buried in Header.cs and not publicly exposed anywhere.

Hope that helps.
