### ISSUE TITLE
"End of stream" problem while trying to parse eml file

### ISSUE THREAD

**Issue by humbledeveloper43** [jstedfast/MimeKit#348]
Hello,

I'm having issues with some mails. Exception is similar one with issue #261 which is "Failed to Parse Message Headers".

I've tried your suggestion: 

```
using (FileStream stream = new FileStream (@"mbox.txt", FileMode.Open)) {
    MimeParser parser = new MimeParser (stream, MimeFormat.Mbox);
    MimeMessage current = null;

    while (!parser.IsEndOfStream) {
        try {
            current = parser.ParseMessage ();
        } catch (FormatException e) {
            // Reset parser state and continue parsing from the current parser position
            stream.Position = parser.Position;
            parser.SetStream (stream, MimeFormat.Entity); // Also tried other MimeFormats too.
            continue;
        }
    }
}
```

But no success. I've checked mail content and it doesnt has any mail body. Only Headers and from to cc etc. headers. But I can open it with Outlook.

How can I solve the parsing problem?

Thanks

**Comment by humbledeveloper43** [comment]
An update: I've printed stream position to understand which part of the email is causing problem. It prints 3538 character as stream position on exception. But I've checked the email and it has total 3476 character. How can it be?

**Comment by humbledeveloper43** [comment]
Hello again,
Sublime Text showed wrong information. I've checked with NotePad++ and now it has 3538 character.

I've checked last two characters which are **0x0a 0x0d** (3537. and 3538. characters)
Can these characters cause problem?

**Comment by humbledeveloper43** [comment]
I've tried to delete those characters to see if they are causing trouble, but now this time it gave same exception with position 3536. So I think they dont have problem with parsing.

Still researching a solution..

**Comment by jstedfast** [comment]
The `stream.Position` property is not likely to be useful since the parser buffers blocks of 4K at a time, so it might be more helpful to check the `parser.Position` instead

**Comment by jstedfast** [comment]
Ok, so the problem is that if the last message in an mbox does not contain a message body (like yours), it will throw "End of stream".

I've just modified the code such that it doesn't throw anymore.

Could you grab the latest source code and test that it solves your problem and let me know how it works? I'm planning to make a release this week(end), so try to get back to me as soon as possible.

**Comment by humbledeveloper43** [comment]
Can you give me compiled nuget package for testing?

**Comment by jstedfast** [comment]
I'm not on a Windows machine right now, so no :(

**Comment by humbledeveloper43** [comment]
I'm working with dotnet core. So which class library project should I compile?

**Comment by jstedfast** [comment]
You'll want the MimeKit.NetStandard.csproj

**Comment by humbledeveloper43** [comment]
I've successfully compiled MimeKit.NetStandard.csproj project and added as reference to my project.

I'm trying to parse same message but this time I get "Failed to parse message headers." 

(MimeParser.cs: line 1535)

**Comment by jstedfast** [comment]
Do you have an mbox or just a message file?

An mbox starts with "From ..." (i.e. "From" + SPACE + more text)

**Comment by jstedfast** [comment]
Is there any way you could email me this message so I can test it?

**Comment by jstedfast** [comment]
Looking at the parser logic, the only way this can happen is if you have invalid headers and the parser is bailing because it thinks you gave it something that isn't a MIME message.

**Comment by jstedfast** [comment]
BTW, you want to use MimeFormat.Entity for .eml files.

**Comment by jstedfast** [comment]
If it helps, the part of the header that will be invalid is the field name (not the value).

**Comment by humbledeveloper43** [comment]
Well I'm already using MimeFormat.Entity to parse .eml files. 

I've found that the last character must be **0x0A** 

For my example, the file was ending with **0x0A 0x0D** 

When I add **0x0A** as last character using a Hex editor to the file it parsed without any problem.

**Comment by jstedfast** [comment]
Not really, that just terminates the header block.

**Comment by jstedfast** [comment]
Just send me the message and I can probably have it fixed in a matter of minutes :)

**Comment by humbledeveloper43** [comment]
I sent a mail to jestedfa@microsoft.com which contains sample mail message that you want to see.

**Comment by jstedfast** [comment]
It works fine for me. Are you sure that it's just:

```
Content-Type: text/plain
MIME-Version: 1.0

```

I've tried with and without the blank line after the Mime-Version header and still no exception being thrown.

**Comment by humbledeveloper43** [comment]
e.g. can you get the subject of mail? In my code it throws `FormatException`,  and then I'm catching this error like this:

```
catch (FormatException e) {
            // Reset parser state and continue parsing from the current parser position
            stream.Position = parser.Position;
            parser.SetStream (stream, MimeFormat.Entity); // Also tried other MimeFormats too.
            continue;
        }
```
And then it leaves the while and `message` object seems empty. `From, To, Cc, Subject` and the other properties are empty or has default values. But in the eml file that fields are not empty.

**Comment by jstedfast** [comment]
The attachment that you sent to me was only the 2 headers I pasted above. Maybe you sent me the wrong file?

**Comment by humbledeveloper43** [comment]
I resent the mail.

**Comment by jstedfast** [comment]
Ok, just got it. Thanks. I can reproduce what you are seeing.

I've already traced the problem to https://github.com/jstedfast/MimeKit/blob/master/MimeKit/MimeParser.cs#L896

As you can tell from the comment in the code, the problem is that the headers aren't properly terminated (which is why when you add another newline character, it works).

**Comment by humbledeveloper43** [comment]
Great. So how can we solve it :) Are you going to update the library to have a maybe optional paramater on parsing for fixing header termination problem? Or something else?

**Comment by jstedfast** [comment]
`parser.ParseHeaders()` essentially already worked with that input so I just took out the `if (!headersOnly)` logic and just made it always fail gracefully rather than just when `ParseHeaders()` was called.

**Comment by bogdansantaGam** [comment]
Hi, i have same  a similar issue 

The library crashes when try to load an memorystream/filestream 
MimeMessage.Load(stream);,
 throw error end of stream error in aws lambda function
It works fine in .net core console app...

**Comment by jstedfast** [comment]
@bogdansantaGam that typically means you forgot to rewind the stream before trying to parse it.

In other words, you're doing something like this:

```csharp
using (var memory = new MemoryStream ()) {
    memory.Write (buffer, 0, buffer.Length);

    var message = MimeMessage.Load (memory);
}
```

What you *need* to do is rewind the stream (aka `memory.Position = 0;`) like this:

```csharp
using (var memory = new MemoryStream ()) {
    memory.Write (buffer, 0, buffer.Length);
    memory.Position = 0;

    var message = MimeMessage.Load (memory);
}
```

**Comment by bogdansantaGam** [comment]
Hi, 
@jstedfast i dit rewind the stream to position=0  but  is not working. 
  using (MemoryStream mem = new MemoryStream())
                {
                    var bytes = Encoding.UTF8.GetBytes(emailText);
                    mem.Write(bytes, 0, bytes.Length);
                    mem.Position = 0;
                    var message = MimeMessage.Load(mem);
....
}

**Comment by jstedfast** [comment]
I would have to see the content of the stream to provide any further help...

Are you sure there's a MIME message in that stream?

**Comment by bogdansantaGam** [comment]
> I would have to see the content of the stream to provide any further help...
> 
> Are you sure there's a MIME message in that stream?
 Ty for assistance, aws lambda sadly are a pain in the *** to debug , beside loading the  eml   files ,i 'managed' to load the folder link also... thus making a invalid stream 

Initial i  thought is a problem how the library manage te memory stream.... since i used other library that  "worked" but apparently only hide the error when loading links

Thx again
