### ISSUE TITLE
Attach blob files

### ISSUE THREAD

**Issue by fatjoni** [jstedfast/MimeKit#350]
Hi,

I save the files on database and i am wandering if there is a way to attach stream files in an email.

Thank you very much

**Comment by jstedfast** [comment]
Well, considering the way to set the content on a MimePart is via streams, I would say yes...

**Comment by fatjoni** [comment]
Can you give me an example @jstedfast please?
Thank you :)

**Comment by jstedfast** [comment]
From the README:

https://github.com/jstedfast/MimeKit/blob/master/README.md#creating-a-message-with-attachments

From the FAQ (for the people who missed it the first time in the README):

https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#CreateAttachments

**Comment by jstedfast** [comment]
FWIW, it's also documented in the following locations:

http://www.mimekit.net/docs/html/Creating-Messages.htm
http://www.mimekit.net/docs/html/Frequently-Asked-Questions.htm#CreateAttachments

I don't know how to make it easier to find... please help me before I go insane answering this very same question day after day.

**Comment by fatjoni** [comment]
Thank you very much and pardon :D
