### ISSUE TITLE
How can I remove the boundary at the end of the file/stream?

### ISSUE THREAD

**Issue by Faniedt** [jstedfast/MimeKit#352]
I'm trying to get the binary data from a multipart response.  Below is my code I'm using.

```
using (HttpWebResponse response = request.GetResponse() as HttpWebResponse)
                {
                    MimeEntity mimeEntity = ParseMultipartFormData(response);
                    Multipart multiPart = new Multipart();
                    multiPart = (Multipart)mimeEntity;
                    int i = 1;
                    byte[] pdfDoc = null;
                    foreach (var attacment in multiPart.OfType<MimePart>())
                    {
                        
                        string fileName = string.Format("attachment.{0}.dat", i++);
                        using (var stream = File.Create(fileName))
                        {
                            attacment.ContentObject.DecodeTo(stream);
                            using (MemoryStream ms = new MemoryStream())
                            {
                           
                                attacment.ContentObject.DecodeTo(ms);
                                pdfDoc = ms.ToArray();

                                try
                                {
                                    File.WriteAllBytes("content" + i.ToString() + ".pdf", pdfDoc);
                                }
                                catch (Exception e)
                                {
                                    Console.WriteLine(e.Message);
                                    Console.ReadLine();
                                }
                            }
                        }                       
                    }
```

The problem is that the boundary at the end is not removed.  

> --uuid:cb104084-5a5c-4404-b417-166d6f069b4f
> Content-Type: application/xop+xml; charset=ISO-8859-1; type="multipart/related; type="application/xop+xml"; boundary="uuid:164764d1-5057-48fb-9849-f8c816f51ef1"; start="root.message@cxf.apache.org"; start-info="text/xml""
> Content-Transfer-Encoding: binary
> Content-ID: root.message@cxf.apache.org

How can I remove the boundary at the end of the file/stream?

**Comment by jstedfast** [comment]
I don't see a boundary at the end of the text.

**Comment by jstedfast** [comment]
If you are getting a boundary at the end of a MimePart's content, then it is malformed MIME and I can't help you other than to suggest using string.Substring() to strip it off.

**Comment by Faniedt** [comment]
Would the malformed MIME be cause by an error on my side?

**Comment by jstedfast** [comment]
Either an error on your side or an error in whatever created the MIME stream.

**Comment by Faniedt** [comment]
It must be on the 3rd party's web service as I get the same result from SoapUI.
