### ISSUE TITLE
<img> body lost when sent with other server(non-gmail server)

### ISSUE THREAD

**Issue by GeneralKaidan** [jstedfast/MimeKit#354]
I am using SMTP to send MIME message. The meme message has 3 images, when this message is sent by smtp.gmail.com (for testing). The 3 images appears correctly. But when sent with company server, Only the first image appears, the others 2 images disappear in visual and HTML body.

Sent with gmail:
`<img src="?ui=2&amp;ik=d813dc97bd&amp;view=fimg&amp;th=15f947785e4a8303&amp;attid=0.1&amp;disp=emb&amp;attbid=ANGjdJ-crLc2qGAPPj0cykYhOaWbVFSXSi8-SObPSBnIvnPtcPIruZ2xXvO83IO1zMSBERrCzWNDgs576aDg2phEvYJn1IwahXOkUP66MXPWpx5enYl8clLSPYlIFD8&amp;sz=s0-l75-ft&amp;ats=1510024383173&amp;rm=15f947785e4a8303&amp;zw&amp;atsh=1" class="CToWUd"><br><br>
<img src="?ui=2&amp;ik=d813dc97bd&amp;view=fimg&amp;th=15f947785e4a8303&amp;attid=0.2&amp;disp=emb&amp;attbid=ANGjdJ8ARF5V2eUTJk0PjW6QKy93uMDddnLsi_0RtgplniuOWVj09KIj1mxHEIvIahhGJ8ziFZ07MW6EOGlUabUKO9jdIhY7KlASf7SF8XMzYFMnshSFqPz_gH2zUFs&amp;sz=s0-l75-ft&amp;ats=1510024383173&amp;rm=15f947785e4a8303&amp;zw&amp;atsh=1" class="CToWUd a6T" tabindex="0"><div class="a6S" dir="ltr" style="opacity: 0.01; left: 970.5px; top: 643px;"><div id=":ja" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Download attachment img_cid_001.jpg" data-tooltip-class="a1V" data-tooltip="Download"><div class="aSK J-J5-Ji aYr"></div></div><div id=":jb" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Save attachment to Drive img_cid_001.jpg" data-tooltip-class="a1V" data-tooltip="Save to Drive"><div class="wtScjd J-J5-Ji aYr aQu"><div class="T-aT4" style="display: none;"><div></div><div class="T-aT4-JX"></div></div></div></div></div><br><br>
<img src="?ui=2&amp;ik=d813dc97bd&amp;view=fimg&amp;th=15f947785e4a8303&amp;attid=0.3&amp;disp=emb&amp;attbid=ANGjdJ-fJ41TbOjpxoQIOthvssOnnjf_vNW8Y2zSsS6b3TUQb9quV35s54BQFGWwSkzeQoEz5CUfnGLlFMvlgvksSml4HRDMJ0U1AGVQ8J6wpxcqhy8i0LSNEkrCtMg&amp;sz=s0-l75-ft&amp;ats=1510024383173&amp;rm=15f947785e4a8303&amp;zw&amp;atsh=1" class="CToWUd a6T" tabindex="0"><div class="a6S" dir="ltr" style="opacity: 0.01; left: 862px; top: 1161px;"><div id=":ib" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Download attachment img_cid_002.jpg" data-tooltip-class="a1V" data-tooltip="Download"><div class="aSK J-J5-Ji aYr"></div></div><div id=":ic" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Save attachment to Drive img_cid_002.jpg" data-tooltip-class="a1V" data-tooltip="Save to Drive"><div class="wtScjd J-J5-Ji aYr aQu"><div class="T-aT4" style="display: none;"><div></div><div class="T-aT4-JX"></div></div></div></div></div><br><br>`

Sent with other server:
`<img src="?ui=2&amp;ik=d813dc97bd&amp;view=fimg&amp;th=15f9479b40737884&amp;attid=0.1&amp;disp=emb&amp;attbid=ANGjdJ--CrMeyjFMNOeFIR-56QOijFHqPmqshdIE_iJ_Q1x-NkGgpCe6PIlDXtDTcDSgJXSwjj_SC5Bws7XnU58Mrg56K_ySUcAPv2geoCpBhLOtqYjGLUUl3ksqRr8&amp;sz=s0-l75-ft&amp;ats=1510024527627&amp;rm=15f9479b40737884&amp;zw&amp;atsh=1" class="CToWUd"><br><br>
<img><br><br>
<img><br><br>`

I have use ProtocolLogger to check the html body, all 3<img>tags exists.
`(var client = new SmtpClient(new ProtocolLogger ("imap.log")))`

The difference I noticed is that the mail server of Gmail needs to be authenticate while the other server do not, what could be the possible reasons for this img lost issue?

**Comment by jstedfast** [comment]
I haven't the foggiest idea, sorry :(

Perhaps contact the administrator of the other server and ask if they strip img tags?
