### ISSUE TITLE
 EOF reached before we reached the end of the headers

### ISSUE THREAD

**Issue by jangpa01** [jstedfast/MimeKit#358]
A message with a very long header not properly folded :
800 chars + (0x0d0x0a not followed by space) + 164 chars
Mimeparser.cs ReadAhead:881 returns Available = Left and so detects EOF.
Incermenting ReadAheadSize from 128 to 200 'solved' the problem.
Apparently it depends on the position in the stream of this malformed header because different messages
with the same malformed header decode without problems.
thanks

**Comment by 12454j** [comment]
Thank you

**Comment by jstedfast** [comment]
Could you attach a sample message (or send me one via email) so that I can debug this as well as adding a unit test?

Thanks!

**Comment by jangpa01** [comment]
Thanks


----- Original Message -----

**Comment by jstedfast** [comment]
A few questions since I don't seem to be able to reproduce:

1. What version of MimeKit are you using?
2. Are you running your app on the Microsoft Windows .NET CLR? Or on Mono (on e.g. Linux, Mac)?
3. Do you know if the message is in DOS or Unix format? (e.g. CRLF vs LF line endings)

**Comment by jstedfast** [comment]
Never mind, I am hitting it.

**Comment by jstedfast** [comment]
Thanks for reporting this! Also thankful that you took the time to debug this and narrow it down to the cause.

I'll try to make a new release soonish. Working on asyncifying MailKit, but if that isn't finished by this weekend, I'll make a new release of MimeKit/MailKit anyway with the bug fixes that I have.

**Comment by jangpa01** [comment]
Thanks so much for the superfast fix :)

**Comment by 12454j** [comment]
Thank you I will attend to this after work

James Thornton
