### ISSUE TITLE
Addind =\r\n in the message content at some senario

### ISSUE THREAD

**Issue by nigash** [jstedfast/MimeKit#359]
Hi, is it known that Mimekit adds =\r\n\. to end of line if line contains more than certain characters? 
And it aslo adds =\r\n in come case depending upon what is next character?

whay does it do that?

**Comment by jstedfast** [comment]
You'll have to show me an example

**Comment by jstedfast** [comment]
If the MIME part is encoded using quoted-printable, then this is normal. That is how long times are folded across lines.
