### ISSUE TITLE
Any method to generate a MDN from a MimeMessage?

### ISSUE THREAD

**Issue by alex-becker-startp** [jstedfast/MimeKit#361]
Hi,
is there any convenient method building a valid MDN from an incoming MimeMessage?
If not, is there any sample code how to do this correct?
Thank you!

**Comment by jstedfast** [comment]
```csharp
var mdn = message.Body.OfType<MessageDispositionNotification> ().FirstOrDefault ();
```

**Comment by alex-becker-startp** [comment]
Hmm, I think my question was somehow misleading.
I am looking for a method to generate a new MDN for sending to the requestor. 
Something like:

```
var message = MimeMessage.Load();
if (message.Headers.Contains(HeaderId.DispositionNotificationTo))
{
   var mdnMessage = message.GenerateMdnMessage();
   mdnMessage.From = xxx;
   Smtp.Send(mdnMessage);
}
```

**Comment by jstedfast** [comment]
Ah, no, MimeKit does not have anything like that. Sorry :(
