### ISSUE TITLE
Problem with x-vcard?

### ISSUE THREAD

**Issue by totszwai** [jstedfast/MimeKit#365]
Hello,

I tried using MimeKit to decode a message that contains the Microsoft vcard thingy, and is getting dumped into the body as follow:

`
BEGIN:VCARD
VERSION:2.1
X-MS-SIGNATURE:YES
N;LANGUAGE=en-us:Test;Test
FN:Test Test
X-MS-OL-DEFAULT-POSTAL-ADDRESS:0
X-MS-OL-DESIGN;CHARSET=utf-8:<card xmlns="http://schemas.microsoft.com/office/outlook/12/electronicbusinesscards" ver="1.0" layout="left" bgcolor="ffffff"><img xmlns="" align="fit" area="16" use="cardpicture"/><fld xmlns="" prop="name" align="left" dir="ltr" style="b" color="000000" size="10"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/></card>
REV:20180105T163754Z
END:VCARD
`

I saw in your code **MimeType.cs** that you only have vcard, but I was inspecting the mime parts and saw that it has a different Content-Type that is checked by your code? `Content-Type: text/x-vcard; name="Test Test.vcf"`

Is there a way to override it so that it would parse it properly without waiting for a new release/fix?

I guess perhaps in the code we should also have:
`mimeTypes.Add ("vcf", "text/x-vcard");`

Or am i doing something wrong on my part?

**Comment by jstedfast** [comment]
MimeTypes.cs is only used by the BodyBuilder class as an aid in determining the correct Content-Type to use when attaching files to a message.

It's not used to determine how to parse anything.

MimeKit also does not parse the vcard format. You need to use another library to parse vcard attachments.

Does that clear things up or am I misunderstanding your question?

**Comment by jstedfast** [comment]
For example, if you choose to use this vcard library: https://github.com/bolorundurowb/vCardLib

Based on the README, it looks like you could use it like this to parse vcard attachments:

```csharp
var bodyPart = message.BodyParts.FirstOrDefault (x => x.ContentType.IsMimeType ("text", "x-vcard"));

if (bodyPart != null) {
    using (var sr = new StreamReader (bodyPart.Content.Open ())) {
        vCardCollection contacts = Deserializer.FromStreamReader (sr);
    }
}
```

Keep in mind that I'm not endorsing this library or anything. I really have no ideas if it's any good or if it's the best. It's just the first match that came back in a GitHub query with an MIT license.

Another (and seemingly more popular) alternative would be https://github.com/drlongnecker/Thought.vCards, but it is licensed under the LGPL v2.1 and I'm not sure if that is useable for you or not.

Hope that helps.

**Comment by jstedfast** [comment]
Actually, you may want to use the following code instead since it'll do any necessary charset conversion into unicode that you might need as well (the above snippet won't):

```csharp
var textPart = message.BodyParts.OfType<TextPart> ().FirstOrDefault (x => x.ContentType.IsMimeType ("text", "x-vcard"));

if (textPart != null) {
    using (var sr = new StringReader (textPart.Text)) {
        vCardCollection contacts = Deserializer.FromStreamReader (sr);
    }
}
```

**Comment by totszwai** [comment]
Ah thank you. With your links and your sample code, I was able to resolve my problem. In one of the visitor pattern function that I override, I was able to go through the MimeParts and check their content-type etc, from there I added them into the attachments.

Many thanks!

**Comment by jstedfast** [comment]
No problem! FWIW, any text/* parts will be visited by the VisitTextPart() method and so you don't have to handle that in the VisitMimePart() override.

Handling it in VisitMimePart() is also fine, though (TextPart subclasses MimePart).
