### ISSUE TITLE
KUDOS for great work :)

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#366]
Hi Jeffrey, wanted you to [see this](https://home.gaiasoul.com/hyper-ide?path=/modules/todo/index.html)

There's a lot of MimeKit in there, among other things when uploading files, in addition to the _"Bazar"_ thing, which allows a (root) user to download and install apps. The latter was needed to be able to create PGP cryptographically signed zip files, to prevent man in the middle, to install malicious code on the server, due to intercepting an HTTP request.

Thx for great work man :)

**Comment by jstedfast** [comment]
Awesome, I'm glad it's been useful :)

**Comment by polterguy** [comment]
NP :)

PS, did you try the link? I think you'll be positively surprised ... :)

**Comment by jstedfast** [comment]
I did, but it seemed to open an HTML editor?

**Comment by polterguy** [comment]
Sure did, and in fact you can edit the files, and get AutoComplete, etc - It's basically a _"web based version of VSCode"_ :)

I even allow guests to play around with the files inside of the _"/test/"_ folder. However, MimeKit is essential for a lot of its actual features.

PS, that HTML editor also supports roughly 100 more languages ... ;)

**Comment by polterguy** [comment]
Pst, click the "?" button, and check out the credits :)

**Comment by rtlayzell** [comment]
Credits say MimeKit Copyright of Xamarin inc? 😆

**Comment by polterguy** [comment]
@Reegan - Don't see your comment here anymore, but isn't that correct ...?

I copied the copyright text (hehe, funny expression ;) ) from the code of one of the files in MimeKit ...

**Comment by jstedfast** [comment]
I actually gotta figure out the whole Copyright thing since we were bought by Microsoft

Hoping to get it copyrighted by me :)

**Comment by polterguy** [comment]
That would be the best I will have to agree, even though it wouldn't arguably matter too much, since it's Open Sauce ... :)

**Comment by jstedfast** [comment]
Yea, I haven't bothered to investigate since it's MIT licensed anyway, even if MS wanted to keep it, I could just fork it myself and lose nothing.

**Comment by polterguy** [comment]
Yup, that sums it up ... ;)
