### ISSUE TITLE
Would a client need to have GnuPG installed to use the GnuPG context?

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#369]
I guess the header says it all ...

**Comment by jstedfast** [comment]
Nope, no need for the client to have gpg installed at all - MimeKit just uses the gpg.conf and the gpg public and private keyrings (if they are there).

**Comment by polterguy** [comment]
That's what I thought :)
What happens if the keyrings aren't there ...?
Will it create them ...?

**Comment by jstedfast** [comment]
It will just create them.

**Comment by polterguy** [comment]
Awesome :)
