### ISSUE TITLE
Incorrect DKIM signature when long MIME headers are present

### ISSUE THREAD

**Issue by PaulSD** [jstedfast/MimeKit#371]
I've run into a problem where https://github.com/Pro/dkim-exchange/ generates an invalid DKIM body signature when a MIME filename is longer than a certain length: https://github.com/Pro/dkim-exchange/issues/205

Unfortunately, I don't have any good way to test MimeKit independently (I'm a Linux developer with almost no access to Windows, and a third party is running dkim-exchange for me on a system that I have no access to), but since dkim-exchange basically just hands the message off to MimeKit for signing (https://github.com/Pro/dkim-exchange/blob/master/Src/Exchange.DkimSigner/DkimSigner.cs#L186), I suspect the root cause is actually in MimeKit.

Would you mind taking a look at https://github.com/Pro/dkim-exchange/issues/205 ?

**Comment by jstedfast** [comment]
I've commented on https://github.com/Pro/dkim-exchange/issues/205

FWIW, I don't do any MimeKit development on Windows either - I do it all on Unix :)

**Comment by PaulSD** [comment]
Thanks!

Interesting ... Using Mono, I guess?  I'll look into that.

**Comment by jstedfast** [comment]
Yup :)
