### ISSUE TITLE
PKCS7Sign + Encrypt

### ISSUE THREAD

**Issue by DBenS** [jstedfast/MimeKit#373]
Hi!

I'm correctly signing my mail using both functions Pkcs7Sign and Encrypt (which call ApplicationPkcs7Mime.Encrypt).  

But, trying to utilize BOTH (encrypt to recipient and also sign the message), I have issues:

1- If encrypting and signing after, the message lacks its encryption.
2- If signing and encrypting, the message lacks the signature.

I'm just calling both functions in sequence, like:

    Encrypt(mymessage)
    Pkcs7Sign(mymessage)

Am I doing it wrong?
Thanks!

**Comment by jstedfast** [comment]
When using `application/pkcs7-mime` for signing, it will embed the MIME content that you signed.

You need to Verify() the signed message which will extract the encrypted MIME content that you fed to the Sign() method.
