### ISSUE TITLE
Pkcs7-Mime not seeing Certificate Password?

### ISSUE THREAD

**Issue by DBenS** [jstedfast/MimeKit#374]
I left a huge message in StackOverflow to see if I get some help...
[https://stackoverflow.com/questions/48815536/mimekit-error-with-self-signed-certificate](https://stackoverflow.com/questions/48815536/mimekit-error-with-self-signed-certificate)

Basically, when I sign a message using a Self-Signed Certificate, I receive an error from the function Pkcs7Sign (as shown in Documentation) saying:  **The provider can not perform the action because the context was acquired as silent**

But:

1) It does not. I provide a "SignedCMS.ComputeSignature(signer, false)" command, which ask me the correct password of the Certificate.

2) When using the same approach with a Certisign Token A3, everything goes ok.

Do you have any advice? 

I appreciate your attention.
Kind regards.

**Comment by jstedfast** [comment]
MimeKit calls `cms.ComputeSignature (signer);` it doesn't pass `true` or `false` to the `ComputeSignature` method. Normally, for API's like this, the default value is `false`, but I guess it's not in this case.

**Comment by DBenS** [comment]
Yes, you are sure.
cms.Signature must be called with FALSE as second parameter to obtain the password of a certificate.

I believe it should be an enhancement in the ApplicationPkcs7Mime.Sign function, I mean, get a parameter to obly cms.Computesignature to be FALSE.

I'm making this manually before this function but, I don't know why, the application is not seeing the password as it sees when I utilize Certisign/Token (not a self-signed certificate but a real one).

**Comment by jstedfast** [comment]
I have no idea what you are saying. The problem is with the WindowsSecureMimeContext and I fixed it above.

**Comment by DBenS** [comment]
Ok, it solve my problem.
Thank you *very much* for your attention.
I'll download the code right now.
