### ISSUE TITLE
Add application semantic version of IsAttachment

### ISSUE THREAD

**Issue by coderb** [jstedfast/MimeKit#377]
From my understanding, `MimePart.IsAttachment` follows well defined semantics that do no map directly to how most end-user email applications (eg Outlook, Gmail) detect attachments.

Would it be possible to add support for a method that uses similar heuristics to the library or can you suggest some sample code?  I'm looking for similar functionality as Outlook for detection.

Thanks

**Comment by jstedfast** [comment]
If you figure it out, let me know. :)

**Comment by coderb** [comment]
Best I can do is incrementally report cases that should be treated as attachments.  

For example, Outlook treats the xyz.txt as an attachment for:

Email Content-Type: multipart/mixed;
Part Content-Type: text/html; charset="us-ascii"
Part Content-Type: application/octet-stream; name="xyz.txt"

Perhaps if you added a method `IsPossibleAppAttachment` you could gather these cases as they are reported by users?

**Comment by jstedfast** [comment]
Well, all message.BodyParts are *potential* attachments :)

**Comment by coderb** [comment]
Of course, but the semantics of the method should be appropriate for an end user application which uses text or html to display a message to the user.

Any part that is not part of the body rendering would be an attachment from the application perspective.

Surely this is a common use case and the method would be appropriate for the library.

**Comment by LeeBear35** [comment]
To match MS Outlook we had to build our own attachment list from the body parts because too many systems do not use the standards properly. Basically any part that is not referenced would not display in the email so it shows up in the attachment list. Hope this code helps:

`    private void BuildAttachments(Boolean includeEmbedded)
    {
      bool FoundPlain = false;
      bool FoundHTML = false;
      bool isTextBodyNull = string.IsNullOrWhiteSpace(this.m_msg.TextBody);
      bool isHTMLBodyNull = string.IsNullOrWhiteSpace(this.m_msg.HtmlBody);

      //testing:            System.Diagnostics.Trace.WriteLine(this.ExtractedTextHTML());
      if (this.m_Attachments == null || includeEmbedded != hasIncludedEmbedded)
      {
        this.m_Attachments = new List<MimeKit.MimeEntity>();
        foreach (MimeKit.MimeEntity a in this.m_msg.BodyParts)
        {
          if (a is MimeKit.TextPart)
          {
            if (!FoundPlain && a.ContentType.MediaSubtype.Equals("plain", StringComparison.InvariantCultureIgnoreCase) && !isTextBodyNull)
            {
              FoundPlain = true;
            }
            else if (!FoundHTML && a.ContentType.MediaSubtype.Equals("html", StringComparison.InvariantCultureIgnoreCase) && !isHTMLBodyNull)
            {
              FoundHTML = true;
            }
            else
            {
              this.m_Attachments.Add(a);
            }
          }
          else if (a.IsAttachment || a is MimeKit.MessagePart || (String.IsNullOrEmpty(a.ContentId) && (a.ContentType != null && !a.ContentType.MediaType.Equals("text", StringComparison.InvariantCultureIgnoreCase))))
          {
            this.m_Attachments.Add(a);
          }
          else if (!String.IsNullOrEmpty(a.ContentId))
          {
            if (includeEmbedded || this.m_msg.HtmlBody == null || !this.m_msg.HtmlBody.Contains(a.ContentId))
            {
              this.m_Attachments.Add(a);
            }
          }
          else if (a.IsAttachment || (a.ContentType != null && !a.ContentType.MediaType.Equals("text", StringComparison.InvariantCultureIgnoreCase)))
          {
            if (a is MimeKit.MimePart)
            {
              MimeKit.MimePart part = (MimeKit.MimePart)a;
              if (string.IsNullOrWhiteSpace(part.FileName))
              {
                foreach (MimeKit.Header h in a.Headers)
                {
                  if (h.Id == MimeKit.HeaderId.ContentDisposition)
                  {
                    foreach (string parameter in h.Value.Split(new string[] { "; " }, StringSplitOptions.RemoveEmptyEntries))
                    {
                      if (parameter.StartsWith("filename", StringComparison.InvariantCultureIgnoreCase))
                      {
                        char[] tempName = System.IO.Path.GetFileName(parameter.Substring(9)).ToCharArray();
                        string invalids = new string(System.IO.Path.GetInvalidFileNameChars());
                        for (int i = 0; i < tempName.Count(); i++)
                        {
                          if (invalids.IndexOf(tempName[i]) >= 0)
                          {
                            tempName[i] = '_';
                          }
                        }
                        part.FileName = new string(tempName);
                      }
                    }
                    break;
                  }
                }
              }
            }
            this.m_Attachments.Add(a);
          }
        }
        hasIncludedEmbedded = includeEmbedded;
      }
    }
`

**Comment by jstedfast** [comment]
This will probably satisfy your needs:

   var attachments = message.BodyParts.OfType<MimePart> ().Where (x => x.FileName != null);

(Note: `MimePart.FileName` checks for the existence of `MimePart.ContentDisposition.Parameters["filename"]` and, if that doesn't exist, falls back to `MimePart.ContentType.Parameters["name"]`).

As @LeeBear35 just noted, Some clients (apparently including Outlook) will only include unreferenced MimeParts as attachments - i.e. if the HTML content of the message body does not reference, then they are considered attachments.

As you can probably imagine, that is a lot of processing for a simple `message.Attachments` property.

**Comment by coderb** [comment]
Ok, these are both really good ideas and something I can work with.  Thanks to both of you for the code and effort.

@jstedfast i would vote to incorporate this functionality into the library even if it is a bit heavyweight.  it's an obvious use case.
