### ISSUE TITLE
Donation details out of date.

### ISSUE THREAD

**Issue by abrookewood** [jstedfast/MimeKit#378]
Awesome work. Would be happy to send you a donation, but you only list Pledgie and that has closed.

**Comment by jstedfast** [comment]
Ah, thanks, I'll have to figure out a new way to take donations. Didn't realize Pledgie had shut down.

**Comment by jstedfast** [comment]
I've registered for the ability to accept donations on liberapay.com, here: https://liberapay.com/MimeKit/donate
