### ISSUE TITLE
MimeMessage.Load("filename.mht"): Embedded Images not displayed ?

### ISSUE THREAD

**Issue by XceSx6** [jstedfast/MimeKit#379]
Dear Dev,

I've created a very simple Web Archive .mht file containing 3 lines of text and an Image.
The text lines are correctly displayed, but the Image is not visible.
It does however contain 3 Attachments:
![image](https://user-images.githubusercontent.com/17053283/36966170-289ce990-205c-11e8-9841-cb861a332d94.png)

Could you possibly shed some light on what I am doing wrong ?
The code is a simple MimeMessage = MimeMessage.Load("filename.mht")

Kind regards

**Comment by jstedfast** [comment]
`MimeMessage.Load()` doesn't display images (I'm sure you're aware), so your question isn't about `MimeMessage.Load()` at all, it's really: "Why doesn't my code that uses MimeKit show images?"

To answer that question, I'd really need to see your code that displays messages.

Have you tried plugging it into the `MessageReader` sample found at https://github.com/jstedfast/MimeKit/tree/master/samples/MessageReader ?

If *.mht files are standard MIME formatted message-like files, then I would bet almost anything that the MessageReader sample will display those images.

**Comment by XceSx6** [comment]
Dear Dev,

I've just loaded the File into the MessageReader, but unfortunately it does not Display the Image.
The Document is created via Word, saved as .mht
I've attached the File. It has the Image embedded.

The Code I am using to send it over SMTP to my outlook:
MimeMessage = MimeMessage.Load("C:\Test.mht")
MimeMessage.From = "test@test.com";
MimeMessage.To = "test@test.com";
MimeMessage.Subject= "test mail";
init the MailClient
MailClient.Send(MimeMessage);

What am I doing wrong ?
[Test1.docx](https://github.com/jstedfast/MimeKit/files/1780771/Test1.docx)
> Simply save it as .mht

Kind regards,
Dirk Bourgeois

**Comment by jstedfast** [comment]
The HTML appears to be using a relative url for the image so if you want it to display, you'll have to modify your code to look for the image using relative urls.

It does not appear to use the standard url lookup behavior defined by MIME.

**Comment by XceSx6** [comment]
Dear Dev,

Thanks for your Feedback, you're right.
For all who wonder how to go about this:

```
MimeMessage := MimeMessage.Load(ServerLoadMht(Email));

BodyString  := MimeMessage.HtmlBody();
BodyBuilder := BodyBuilder.BodyBuilder();
EntityList  := EntityList.MimeEntityList(MimeMessage.BodyParts());
WHILE (EntityList.MoveNext()) DO BEGIN
  Mimepart  := EntityList.Item(EntityList.Index);
  IF (StringFunctions.EndsWith(Mimepart.ContentLocation.LocalPath, 'png')) THEN BEGIN
    Mimepart.ContentId := MimeUtils.GenerateMessageId();
    BodyString         := StringFunctions.Replace(BodyString, ServerGetImageName(Mimepart), 'cid:'+ Mimepart.ContentId());
    BodyBuilder.LinkedResources.Add(Mimepart);
  END;
END;

BodyBuilder.HtmlBody(BodyString);
MimeMessage.Body(BodyBuilder.ToMessageBody());
```
Works like a charm, Outlook displays it properly.


Kind regards
