### ISSUE TITLE
Is there a way to attach an image with the link instead of the path?

### ISSUE THREAD

**Issue by nguye404** [jstedfast/MimeKit#380]
Is there a way to attach an image with the link instead of the path?
builder.Attachments.Add (@"C:\Users\Joey\Documents\party.ics");

**Comment by jstedfast** [comment]
You mean like "http://..."? No. You'll have to download it yourself using HttpClient or WebClient and then get the stream and pass that off to builder.Attachments.Add().

**Comment by nguye404** [comment]
Could I ask how could I use builder.Attachments.Add() for an image using the relative path?  It's because the absolute path only works on the local machine and it didn't work when I switched to another computer.  I have tried 
`builder.Attachments.Add("..\\AttachLogo\\jLogo.png");
builder.Attachments.Add("..\\..\\AttachLogo\\j.png");
builder.Attachments.Add("~\\AttachLogo\\jLogo.png");`
Thanks for your time!

**Comment by XceSx6** [comment]
Hey nguye404,

I might be completely wrong, but perhaps like this:
```

string location := MimeUtils.GenerateMessageId();

BodyBuilder          := MimeMessage.Body();
AttachmentCollection := BodyBuilder.Attachments();
MimeEntity := AttachmentCollection.Add(EmailAttachments."Filepath");
MimeEntity.ContentId(EmailAttachments."Display Name");
MimeEntity.ContentLocation(location);

MimeMessage.Body(BodyBuilder.ToMessageBody());
return location
```

Kind regards

**Comment by jstedfast** [comment]
@nguye404 any one of those will work.

**Comment by nguye404** [comment]
Thank you!!!

**Comment by jstedfast** [comment]
Just do this:

```csharp
WebClient wc = new WebClient();
byte[] bytes = wc.DownloadData("https://i.imgur.com/DAxF3gy.jpg");
var image = builder.LinkedResources.Add ("DAxF3gy.jpg", bytes);
image.ContentId = MimeKit.Utils.MimeUtils.GenerateMessageId ();

builder.HtmlBody = string.Format(@"<img src=""cid:{0}"">", image.ContentId);
message.Body = builder.ToMessageBody();
```

**Comment by nguye404** [comment]
Thanks for your help!
