### ISSUE TITLE
550 Maximum line length exceeded

### ISSUE THREAD

**Issue by effyteva** [jstedfast/MimeKit#381]
Hi,
We've recently switched to MimeKit in order to use Amazon SES API.
Our use is very basic (Casting SmtpMessage to MimeMessage, and getting a stream of the message).
Since the switch, we sometimes receive the following error: "550 Maximum line length exceeded".
We looked into it a bit, and it seems as if the library sometimes sends messages longer than the maximum allowed of 998 characters per line.
Is this something that can be fixed on MimeKit library? Is there any other recommendation for fixing this issue?

Thank you!
Effy

**Comment by jstedfast** [comment]
MimeKit should already prevent this.

As you can see here, MailKit's SmtpClient code forces line lengths to a max of 998 chars:

https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L1957-L1963

This eventually ends up in MimePart.Prepare() which calls:

https://github.com/jstedfast/MimeKit/blob/master/MimeKit/IO/Filters/BestEncodingFilter.cs#L70

As you can plainly see, if any line is > 998 characters, MimeKit will force the content to be encoded which will wrap much much earlier than 998 characters (base64 wraps at like 76 chars and quoted-printable wraps at 72).

Please get me a test case where the following code produces a message with lines longer than 998 characters:

```csharp
var message = CreateMessageWithLongLines ();
message.Prepare (EncodingConstraint.SevenBit, 998);
message.WriteTo (fileName);
```

Replace `EncodingConstraint.SevenBit` with whatever is appropriate for your SMTP server based on its reported capabilities (if you don't know, get me a protocol log).

**Comment by effyteva** [comment]
Hi, I appreciate your quick reply!

I think you actually gave me the perfect explanation for that.
As I don't use the SmtpClient code, the Prepare method isn't actually invoked on my use case.
I assumed the line split logic is part of the WriteTo method, which I now understand it isn't (I just browsed through the code to make sure this is the case). Wouldn't it make more sense to call it from the WriteTo method? As currently the WriteTo method allows getting a Stream of invalid message.
I'll try explicitly calling the Prepare method today, and will post an update if this resolved the issue.

Thank you,
Effy

**Comment by jstedfast** [comment]
No, because it is important not to modify existing messages.

What I mean by this is: what if you parse a message that has long lines or doesn't wrap the same way that MimeKit's logic wraps content? Then, the WriteTo() method would not output byte-for-byte exactly what was parsed.

This is especially important if you are adding your own DKIM signature to a message which has already been DKIM-signed by someone else.

Hope that helps!
