### ISSUE TITLE
Override default message id

### ISSUE THREAD

**Issue by siewers** [jstedfast/MimeKit#382]
I've realized when using the BodyBuilder class (and elsewhere too), MimeKit defaults the content id of the html part to the format `56VN1DSRT3U4.UU100I4816E3@localhost.localdomain`, which I would like to control myself (actually just the domain part). Is there any way to change the way the content id's are generated?
I know I can create everything manually and set the content id to whatever I want, but in this case it doesn't seem possible.
I'm pretty sure it doesn't make any difference to the clients, but to me it's not "nice" to have these content id's in the message.

**Comment by jstedfast** [comment]
There's no way to do this using the BodyBuilder class, but, as you've noted, you could construct the MIME body manually and have full control to do whatever you wanted.

Another option is to use the BodyBuilder class. Then, once you've set the message's Body, iterate over the body to find the HTML part (or use the message.HtmlBody property) and then manually set the ContentId yourself.

Hope that helps.

**Comment by ryangege** [comment]
I did something like this :
var headers = message.Headers.Where(m => m.Id == HeaderId.MessageId).FirstOrDefault();
headers.Value = headers.Value.Replace("thepartyouwanttoreplace", "desiredstring");

And it worked.
