### ISSUE TITLE
TextToHtml do not handle Emojis correctly. 

### ISSUE THREAD

**Issue by magol** [jstedfast/MimeKit#385]
If I use `TextToHtml.Convert(string text)` to convert some text containing emojis, the output is not correct

If the original text e.g. contains following string `=F0=9F=98=B1` I expect to get `&#x1F631;` that is renderad as 😱 in the web browser. But the output is `&#55357;&#56881;`

**Comment by jstedfast** [comment]
Fixed published to nuget.org as v2.0.3
