### ISSUE TITLE
Create MimeKit.Lite Nuget Package

### ISSUE THREAD

**Issue by Jaben** [jstedfast/MimeKit#39]
I'm using MimeKit for Papercut (http://papercut.codeplex.com) because it's fast and excellent. No reason to reinvent the wheel with something superior and MIT licensed out there...

But I don't need the encryption stuff.

If you don't have any interest, I don't mind doing it.

Thanks for the excellent lib.

**Comment by markusschaber** [comment]
I know this ussue has aged some time now, but I just came across it.

I tried to find out what's the difference between MimeKit and MimeKit Lite, and neither the Readme of MimeKit on Github, nor the NuGet package descriptions give a clear answer to this. :-(

**Comment by jstedfast** [comment]
MimeKitLite is MimeKit w/o crypto (i.e. OpenPGP, S/MIME, DKIM, etc)

**Comment by markusschaber** [comment]
@jstedfast Thanks, that's what I learned from this issue.

Is it possible to mention this in the package descriptions at NuGet.org?

**Comment by ygoe** [comment]
@markusschaber No, it's not possible. With MimeKit, you'll have to dig every relevant information out of issue discussion comments. Sad but true.
