### ISSUE TITLE
Text/Plain Attachment content show up in body as well as in attachment.

### ISSUE THREAD

**Issue by irikeish** [jstedfast/MimeKit#391]
I am trying to create mail,using MimeKit.BodyBuilder class like this:

```
var mail = new MailMessage();
mail.To.Add(new MailboxAddress("name1","name1@def.com");
mail.From.Add(new MailboxAddress("name2","name2@def.com");
var builder = new BodyBuilder();
builder.textBody = "";
buider.Attachments.Add(file);
mail.body = builder.ToMessageBody(); 
```

when I send this mail, iff attached file is of Text/Plain, then it's content is showing up in the body also. Note this problem doesn't occur when the attachment is xml,json,etc.

Please, point out the problem.

**Comment by jstedfast** [comment]
Fixed published to nuget.org as v2.0.3
