### ISSUE TITLE
Issue with TNEF calendar items

### ISSUE THREAD

**Issue by siewers** [jstedfast/MimeKit#394]
When I convert a TNEF calendar item to a message, nothing gets returned. I know calendar items are not exactly messages, but would it be possible to get the `MessageClass` property exposed somehow? Right now I'm parsing the TNEF MAPI properties manually (largely inspired by the `TnefPart.ExtractMapiProperties(...)` method) to get the `MessageClass` property, and then evaluating whether it's a `IPM.Schedule.Meeting`.
It would be great to have some sort of TNEF parser, where all attributes and properties are exposed for further inspection.
If the above makes sense, I'd like to contribute, but I won't consider it, if it's outside the scope of the project 😄 

In my opinion it would make sense to have some container with all the TNEF data. This container could then be passed to different builder classes, like `MessageBuilder.FromTnef(TnefData tnefData)`. Just an idea 😄

**Comment by jstedfast** [comment]
Since TNEF is unfortunately a reality of dealing with mail, I wouldn't necessarily be opposed to it, I'm mostly just not sure of what the best API would be. The ExtractAttachments() and ExtractMessage() APIs I wrote were more just "this seems to be what what most TNEF data contains". I don't get very many tnef attachments so it's hard to know what APIs make sense.

**Comment by siewers** [comment]
When sending messages from one Office 365 account to another, everything seems to be in TNEF. I've used the `TnefReader` to get all the data, and it is a bit annoying that I have to duplicate code already in MimeKit, just to get to the internal details of the TNEF message 😃 
Since I basically have to parse the message twice, to identify whether it's a calendar item or an actual message, seems a bit of an overhead to me.

**Comment by jstedfast** [comment]
For sure, that's less than idea ;-)

**Comment by jstedfast** [comment]
Could you set the `MessageClass` value on the `MimeMessage` using a `X-MessageClass` header or something?

```csharp
message.Headers["X-MessageClass"] = value;
```

**Comment by siewers** [comment]
Well, the `MessageClass` is not part of the `MimeMessage` but rather part of the TNEF.
What I'm currently trying out is to create a `TnefParser` which returns a `TnefParseResult` containing all the properties with some properties extracted for convenience, including a method to build the message body (much like the `TnefPart.ConvertToMessage()`).
It's a difficult format to work with, but I just need to know whether it's actually an `IPM.Note` or not. If it is, I try to generate a message from it. I cannot process calendar objects anyway, as the format is ridiculously complex.
What I am trying to achieve is to manipulate the message HTML, but _only_ if it is HTML. If the TNEF contains an RTF message, I ignore it.

As you can probably tell, there is a lot of legwork to be done 😃
