### ISSUE TITLE
How to extract raw header

### ISSUE THREAD

**Issue by tchilz** [jstedfast/MimeKit#396]
I wanted to extract raw header text while parsing eml file. Please help.

**Comment by jstedfast** [comment]
You can poke at the raw header values in the `message.Headers` dictionary.

For example:

```csharp
Header header = message.Headers[0];
```

Each `Header` will have a `Value` which is a string representing the unfolded and decoded value. There's also a `RawValue` property which holds the raw bytes of the header value which sounds like it's exactly what you are looking for.

You could turn it into a string using `Encoding.Ascii.GetString ()`
