### ISSUE TITLE
DKIM Signing for Microsoft.Exchange.Data.Transport.Email

### ISSUE THREAD

**Issue by kapitaneo** [jstedfast/MimeKit#400]
Hello Comrades. I have a problem and may be someone has already resolved. In my project usage Microsoft.Exchange.Data.Transport.Email. And I need to add DKIM signature. I tried to load MimeMessage from path eml, signed  and inserted this header to my EmailMessage. After load email for MimeMessage and my EmailMessage they have different header possition and structure. After signed when check DKIM email hash is different. And I have fail. If I send MimeMessage all Ok.
But I need usage Microsoft.Exchange.Data.Transport.Email. May be someone have idea how to make friends with these types?
Thanks for any help.

**Comment by jstedfast** [comment]
Unfortunately I'm not familiar with that library so I don't know the best way, but my best guess is that you'll want to DKIM sign a `MimeMessage` and then write it to a stream, then use `EmailMessage.Create(Stream)` to convert back to an `EmailMessage`.

e.g.

```csharp
MimeMessage message = DkimSignMessage ("c:\\email.eml");
using (var stream = new MemoryStream ()) {
    message.WriteTo (stream);
    stream.Position = 0;

    var email = EmailMessage.Create (stream);
    ...
}
```

**Comment by kapitaneo** [comment]
Thank you. I did almost like You. Maybe someone will come in handy.
` MimeMessage message;
  using (Stream emailstream = new MemoryStream())
   {
         email.MimeDocument.WriteTo(emailstream);
         emailstream.Position = 0;
         message = MimeMessage.Load(emailstream);
   }`
