### ISSUE TITLE
Equality comparer issue under mono running 2.0.4

### ISSUE THREAD

**Issue by Ic3xX** [jstedfast/MimeKit#402]
Hello,

my app immediately crashes when using MimeMessage.Load method. I tracked down the problem to the Dictionary used in the CharsetUtils.Utf8 constructor.  When initializing the dictionary with the following piece of code (   _aliases = new Dictionary<string, int>(MimeUtils.OrdinalIgnoreCase);   ) it is not possible to insert any item in the dictionary and the app will crash at the next line (  AddAliases(_aliases, 65001, -1, "utf-8", "utf8");   ).

It seems there are unsupported operations in the MimeUtils.OrdinalIgnoreCase Equality Comparer. I used another built in .Net comparer (StringComparer.OrdinalIgnoreCase) and the app starts fine. What options do i have in this situation?

My mono version: Mono JIT compiler version 5.0.0 (Stable 5.0.0.48/851b6c7 Thu Dec  7 14:05:02 UTC 2017)
.Net Framework 4.6

**Comment by jstedfast** [comment]
Upgrade to at least Mono 5.8 or 5.10
