### ISSUE TITLE
Signing public PGP keys

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#403]
Howdy Jeffrey, I remember vaguely at some point we discussed this, and you were thinking about implementing convenience wrappers to make it possible to sign a public PGP key in the GnuPGContext. Since I am working on _seriously_ refactoring my usage of MimeKit, cleaning up its code, and also upgrading my own code, to avoid using deprecated features, etc - I thought this would be a great time for me to implement these parts too ...

Did you have some kind of convenience wrapper for doing this, or ...?

If I remember correctly, I think BC would throw since you'd have to add a key to the keyring that already existed or something, which would make BC choke ...

I vaguely remember you were trying to fix this though ...?

If you did, how would I use it ...?

**Comment by jstedfast** [comment]
I think all I did was to add a `Delete (PgpPublicKeyRing)` method that you can use to remove the old keyring from the bundle before adding the new keyring.

**Comment by polterguy** [comment]
Thx :)
