### ISSUE TITLE
MimeMessage.WriteTo and MimeParser.ParseMessage not thread-safe

### ISSUE THREAD

**Issue by jgilpin** [jstedfast/MimeKit#406]
Hi Jeffery,
Thanks for MimeKit, it's amazing.

I get an exception if have a parser thread calling MimeParser.ParseMessage() and writer thread calling MimeMessage.WriteTo(), the ParseMessage exception is 'System.FormatException: 'Failed to parse message headers.''

This only happens when the MimeParser has been instantiated with persistent=true. My guess is the underlying position of the persistent stream isn't synchronized.

Is there a way to achieve parsing/writing on different threads and keeping persistent=true so memory usage stays small?

Or maybe another way to efficiently open a specific MimeMessage from a new persistent stream to the same mbox file?

Thanks!

Jon

**Comment by jstedfast** [comment]
There's no way to do what you want to do while still using persistent=true.

**Comment by jgilpin** [comment]
Yep, there is. 

In case anyone comes to this thread through google the solution is to store the MboxMarkerOffset and the Position of the MimeParser after the MimeMessage has been parsed to obtain a proxy to the MimeMessage.

Then on the consumer thread open a stream to the same mbox file and use the very handy BoundStream class with the MboxMarkerOffset and Position as bounds. Then pass the BoundStream to MimeMessage.Load and use the resulting MimeMessage call WriteTo()
