### ISSUE TITLE
MimeKit 2.0.4: Wrong number of attachments

### ISSUE THREAD

**Issue by RafaelCastro9** [jstedfast/MimeKit#409]
First of all, thank you so very much for your work and dedication on this project.  Using v2.0.4 of MimeKit and MailKit, and every now & then the MimeMessage.Attachments returns an IEnumerable with the wrong number of attachments or 0 when there should be at least 1.  Let me know where to send the protocol logs so you can inspect them.

**Comment by jstedfast** [comment]
A MIME part is ONLY considered to be an attachment if it has a `Content-Disposition: attachment` header. Does it have that? If not, then it's not an attachment.

**Comment by RafaelCastro9** [comment]
From the POP3 Protocol Log:
S: From: <xxxxxxxxxxx@xxxxxxxxxxx.com>
S: To: <xxxxxxx@xxxxxxx.com>
S: Date: Fri, 22 Jun 2018 14:49:14 -0500
S: Subject: XXX XXXXXX Invoice 35877 
S: Content-Type: multipart/mixed;
S: 	boundary="--boundary_26_a97744c9-4713-4a63-8bec-a65696010a1c"
S: X-ASG-Orig-Subj: PCA Milwaukee Invoice 35877 
S: Message-ID: <bbac0b15dc494fbc98cccc60ef7a7318@pcalakexch05.ad.packagingcorp.com>
S: X-Barracuda-Connect: UNKNOWN[172.16.1.135]
S: X-Barracuda-Start-Time: 1529696995
S: X-Barracuda-Encrypted: ECDHE-RSA-AES256-SHA384
S: X-Barracuda-URL: https://198.140.128.88:443/cgi-mod/mark.cgi
S: X-Barracuda-BRTS-Status: 1
S: X-Virus-Scanned: by bsmtpd at packagingcorp.com
S: X-Barracuda-Scan-Msg-Size: 2
S: X-Barracuda-Spam-Score: 0.80
S: X-Barracuda-Spam-Status: No, SCORE=0.80 using global scores of TAG_LEVEL=1000.0 QUARANTINE_LEVEL=1000.0 KILL_LEVEL=1000.0 tests=BSF_SC7_MV0760, NO_REAL_NAME
S: X-Barracuda-Spam-Report: Code version 3.2, rules version 3.2.3.52240
S: 	Rule breakdown below
S: 	 pts rule name              description
S: 	---- ---------------------- --------------------------------------------------
S: 	0.00 NO_REAL_NAME           From: does not include a real name
S: 	0.80 BSF_SC7_MV0760         Custom rule MV0760
S: X-EOPAttributedMessage: 0
S: X-EOPTenantAttributedMessage: 2691a251-4c38-4643-af0b-0c0982f197bd:0
S: X-Forefront-Antispam-Report:
S: 	CIP:198.140.128.88;IPV:NLI;CTRY:US;EFV:NLI;SFV:NSPM;SFS:(8046002)(2980300002)(438002)(199004)(189003)(260700001)(86152003)(77096007)(26005)(122386005)(84326002)(564344004)(106466001)(2476003)(72206003)(4743002)(24736004)(108616005)(5000100001)(2876002)(7116003)(22186003)(562524006)(106002)(21480400003)(4610100001)(7636002)(8676002)(336012)(305945005)(356003)(2501003)(246002)(7596002)(1096003)(573454002)(110136005)(86362001)(476003)(58800400003)(426003)(14003)(126002)(16586007)(486006);DIR:INB;SFP:;SCL:1;SRVR:BYAPR14MB2183;H:pcalaklx01.packagingcorp.com;FPR:;SPF:Pass;LANG:en;PTR:pcalaklx01.packagingcorp.com;A:1;MX:1;
S: X-Microsoft-Exchange-Diagnostics: 1;BY2NAM01FT033;1:v8bKSYZP/igHNmKKbIsNY41HOS0WwrHe0WFTGSj2QMc3/4U1FSSo8hUOi7rOL4Cl3Xi/JxAQwyrbvl8BYKROCIi+HWAJ39hsxg4OxtcIvvW/Dd890aqxQ4NzZmafIQcK
S: X-MS-PublicTrafficType: Email
S: X-MS-Office365-Filtering-Correlation-Id: c9598c41-41f4-4950-828f-08d5d8795527
S: X-Microsoft-Antispam:
S: 	UriScan:;BCL:0;PCL:0;RULEID:(7020095)(5600026)(711020)(4605076)(4608076)(4614076)(49563074)(1401150)(1402068)(71702078);SRVR:BYAPR14MB2183;
S: X-Microsoft-Exchange-Diagnostics:
S: 	1;BYAPR14MB2183;3:6dna1NedBL3LVDyYOC5i6ETT71Mnl2AcCgE9fLPmB+FsgoTirio5xTZQQFA3Dem6hdCnlg7cQLTvgBfm9HSTT1X2k7lJhguvipvfkiE2BXzOmBBrb8DJOK3LUpVBGCim8ATocqNz0DkG0tvRJqEGsJu1GCtDttd5WwL12yTDGkje1LVe+PViEVQpKLKj8fpD9hHfGDFMf27unHj7OQ1DJsyCwFUddZ5W+DH8ENcAfaYxnkyyZoHM9aDsjo274d2o57vJJBwGMO716yCh32OKGEcSbuJ3FqYxW9webHt2lkLfkPQeoya5/rG70PZbxbSLQqicNahfONtN1f+4VCxBvXWiEei8Kwr67QURD50K/GA=;25:WstUQMNC+8wFzfrNS/gUR28SS4pXI6q76xsWqF8oh9zMewjaJnOSk7BpKY0yDm2mCDv3QYqwvYOujfPMYwQrOf5yk3cAOHJLiYwlqe2i30fOfJhsjxXOfSW8BnaS9+MSulBgK5CBhbzG2EqakvSmZxgtPiMl+tEqq/F/mSBTsNMIxPpVx/2U/p7gL1DC4U6GSR1YEHuYF1Q6goOUiFED+U3n9xz6jkg6uAWUWM1oaPw=;31:AdiKOvL3criNcvXiUSSuLIPz0OG3VlMvJTZ9oGhJQiKpbSKz+haEbM70H67DwFyAlGUvkcIUa1KT2mV1sFo9+GBz872/QuBcULtt5kX/IRB/alcDZg5uX4fQDF689eX8
S: X-MS-TrafficTypeDiagnostic: BYAPR14MB2183:|BYAPR14MB2183:
S: X-Microsoft-Exchange-Diagnostics:
S: 	1;BYAPR14MB2183;20:J2Pm6KLe/piu10ej19kmU9MFpCeSrQYHWcNDpuvgUTPp7UogfgAS7eMEXvRbsLrqkCyNCHsLB6CH0yd97QnOyP/p5MokLKA6mxxxS9rQT4h5zBYgtMHhsrTCMVN42BX6tw/0/xGL8yAzlJg9ahGwd3JQI9uKFkmTz1GAv/yoy/JWL0vSlax5FCsOydMZzKn+bfP9/tuhLQ/AWMIENats35WvOFltf/TRNiA9+Jm30LsNFs/cBLZjvdICVOrqrbGekxey7yeb54uHMy4cvZmXPz5eM3vygflw0+CfOoxiPpffODN53yVjYKjo3MN2rgdmZnmOxWpzNP3X7sXM/5GVp6MXXjARAxCpsmdzy9UQu6d+ClmzSxyvmUAIoGqXN8PBs+CCyHJ2lpGLrz+CkqMlo2aRjLwR+u0/3n7l9QEDTaoPSZM6XWeY8E8fpiJji/V7kKV6wR7pF4p2ceiFO00N812tKpM4YwM6zIdxbBr0vBQFpTbH9cxGBUuIPJaqzoL+;4:6Msg8WjcmqRES2FIsj4hkRbOgC3Nypsvv4LWtpB04HkT3T86tG7gUKQE+1LcdCx42rj8HVmP2J9VekQKVUOIqVopRPUYqEeHGMtldohygCwqgWRBO0o8451EKJ7H09qQOsKKaVCNrEASc28GOsg4vme3bg4QGI0stWV74RuV+lg=
S: X-Exchange-Antispam-Report-Test: UriScan:;
S: X-Exchange-Antispam-Report-CFA-Test:
S: 	BCL:0;PCL:0;RULEID:(8211001083)(102415395)(7630418)(2401047)(8121501046)(7631346)(7632307)(7633261)(1430455)(1431068)(1432130)(1440212)(823300264)(823350442)(823411253)(9101536074)(93006095)(93004095)(3231254)(901025)(902075)(913088)(7045084)(944500087)(944510158)(944921075)(946803086)(946901078)(52103095)(52105095)(52106170)(52401190)(52601095)(52505095)(52406095)(52305095)(52206095)(3002001)(10201501046)(1610001)(8301001075)(8301003183)(9300000083)(9301000104)(201708071742011)(7699016);SRVR:BYAPR14MB2183;BCL:0;PCL:0;RULEID:;SRVR:BYAPR14MB2183;
S: X-Microsoft-Exchange-Diagnostics:
S: 	=?us-ascii?Q?1;BYAPR14MB2183;23:+D38AR0OlF+h0GXU5hbXIgc1Sezx1W4AKJPPqUH4e?=
S:  =?us-ascii?Q?dyCEDEgXRTM6A967YWw4/iyxFv7mq8ZnapX5jSG/LSTU3/IKhN80ljTS86mK?=
S:  =?us-ascii?Q?7Ef3qTpUulTIGFmoU589XSVSV43sSEbiArWpyRCxA6Vrl1O+u+R5goJEgrio?=
S:  =?us-ascii?Q?XVIZNTEAFQKC1man756blAZD9jq0K/WqW2DZ+Bq4pWaATxkDQMSYdUvxnvlr?=
S:  =?us-ascii?Q?Bry6GN/rqzoCnDtszIXh1IEkkVD3tlrnFVQewAFvnzb+DFbJEA5RjbcI4V1z?=
S:  =?us-ascii?Q?2QcOq6b95bRP8Vg12fw2qkzecp4+ZLRVNQKdp3EvI2uiBU5f6MSUPN3RbX9S?=
S:  =?us-ascii?Q?emo+k5UCASE/sNyInsa3vyEqbYq5LF79OZ9aknkcpDtJ031demrastvcsFdk?=
S:  =?us-ascii?Q?IvbkFVWUzGbnk2J1iWhChuVvR0rrI71kZ4vjZgcDduVrmNHKs6kRqH7MeohW?=
S:  =?us-ascii?Q?vlgoQIiBqUcj23VYLR+5njFMc0z9qp4j3cNrS2HBLZ8rH8hdmOHs20h53nWo?=
S:  =?us-ascii?Q?WETH4kgTlfuemwm5al8BP5sqkzz8YJn9nz7oObieSwhyGoH/gUoeH2JQmmnk?=
S:  =?us-ascii?Q?k5Kw4BLwUAlFdGvImLEskj3rf6GJvp7bcaF98x9kutVZljfcrJCWA67C3Jn3?=
S:  =?us-ascii?Q?Ss0AaxvdCamfUMqBQ8xRfXwDWTFtxWFgGtt6j463p/wAy3gm/VW+tXkx63XW?=
S:  =?us-ascii?Q?TM0k3hEx9ybaTv3j71z0T83BuByE3wCyDXfHTCcL7RQtG5X6aTF46PYvH/1Q?=
S:  =?us-ascii?Q?lEZsR7Jr/+R5wWGxrK7hUinSgesWv8Om0tXsdmSjmFx1PZ0KXBIGw/qt9YS9?=
S:  =?us-ascii?Q?jeuT1GBN/+OLpN6BdCDmMI85ZHm9x2FVs/acn/2Y1OSUqMlR33Wgs59HbaYR?=
S:  =?us-ascii?Q?KUimO5bAbZosO2Q+q5xRTafsAT6GkwkEroCS+0xtYbHRLXg6oVQ19hD2iRKq?=
S:  =?us-ascii?Q?WsPqDlcPVZxi3QsFAuBviNw5WdoROBtboF3SEnDo1GfM0D7Til5o2czNGp+v?=
S:  =?us-ascii?Q?DGxAE39UiJurhgBaI0wFnwTn0TCkrHsuRSSAWEjyqmSP5WGx7r9zM0+3h92I?=
S:  =?us-ascii?Q?yaD/gU=3D?=
S: X-Microsoft-Antispam-Message-Info:
S: 	YoVIwQvqEcU+34+5UHp2E29jAykYSrqw/mxXCn6zxN3/L2bJlHthlpFJGs+ijyOlRvIG0WZjfmi8m8KqSd4VBXwPWMP/YaDr6c4xpjWQIIqhFK234CgNHT67p85t6ptu1n2/3g7UqwvTfxl7bawIRDkCcVCuq3fvg+2AyBKQS0XX/Y5kAcBldGdaWnU5CNqSqJFfA//cLOh99whA7gAxtkpsUpv9idOGIquwQlbQnzTFsKmHFoaIHeJqRdQvgHwhsNa2/NcZc7BZr7+YYhjXIo2squNKVZoekysHsy/Nlf0YjUQwUM7kHSWfYTbvIWOeCt08Lagqn9x04w95hOEehsEynpAeCTnNLvudam0OGOuRxw80xc4j1V17jlIFKw2qhbTRW7mfvPvc8fvQICdU2iCM14W5YtJigszM5ieJ2igigeupkuYLYSsZN8gISLCD1AJFkO1SBz/LH5kJd1nPGr5EMJuG48ubLL2dDPCtRk0siKxN8dEu0v+VN1BxWN5F
S: X-Microsoft-Exchange-Diagnostics:
S: 	1;BYAPR14MB2183;6:9oXFMULlKpnx2IqioxocWt1TeAMzcqJRAPTZFwrs7252q5zRDvjF5VPgi/qOUX0Q3HIjCtdtgcwXMxqjjRDP8F5CHKPq4o+MgrFRIoOhkdIonUQWKhSyLF5O2Yjgv69B8QKaa+wqhiC73uboAmbNOd8krhU1FVCWRRmM8bNBm4vONmQrBYsZsuVaNT8zLpzlA5dG1NO7Lg1VvGI2/uF0jL33OxbwMqJ1+HjOv/HshrK67tAQ7+5wVCfvS8PGn5AVJaiY4dzga8RHOrSOFPHXpUoRaQa26mrqgzpEMiODaPMGhMeyO9aFMScftnXWRZ0tUshiU/lTL6gWtEV35i0PFagg+SlbmMyLak5fkjvA3r0=;5:vXlxpoDHAUhMfwL6HUhWEb9Xso5WsscdLDCzU2AkuoPZaDqeMIZjEW36nnavWzpeYvtFlfWmKXdjJwu6ERxO/PFuf0CIYY7n1pfpQ+hZ2T91kXkVIibbQaHmOLEUMK57FJSdYS1FBKyOGJrqDphzrgFog/rEsL5QKUEC1zMktFI=;24:q7ToZzqeUxBuTpq3UFVq2GGLp9yipmOuH8hRIjS5qPc7R+6MBDVFAUw/J8v5wli8MQtjIcM3hrE5SK6XiF2nBcCNsn08lX1w+lUtXG4vAZc=;7:/WcmrKHhETGH5N3uBTJ5YVNVIkZ+jxStQAwbmO7R77nwc/m6lusYNKplnGWm0K4Emdf+MvcBCyk8y44HM1dxRJxvKjgMxp+xD4vbKDC0RDbCtghsjsLFWHsZUQqPRXfhmQ/SCAhoLP0Gbxr5R6hs+70vERe2lNqqOfCugt3bkynzWukpVqqvGajiLgfLCSCDiMmRkdHQT9+ow3jhhk85sQb4CpHNC9fkkGXvUmUTsUKR9d00aI+7Ri17W7Z5EkEN
S: SpamDiagnosticOutput: 1:99
S: SpamDiagnosticMetadata: NSPM
S: X-OriginatorOrg: sealedair.onmicrosoft.com
S: X-MS-Exchange-CrossTenant-OriginalArrivalTime: 22 Jun 2018 19:49:57.2682
S:  (UTC)
S: X-MS-Exchange-CrossTenant-Network-Message-Id: c9598c41-41f4-4950-828f-08d5d8795527
S: X-MS-Exchange-CrossTenant-Id: 2691a251-4c38-4643-af0b-0c0982f197bd
S: X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
S: X-MS-Exchange-Transport-CrossTenantHeadersStamped: BYAPR14MB2183
S: X-MS-Exchange-CrossPremises-OriginalClientIPAddress: 198.140.128.88
S: X-MS-Exchange-CrossPremises-AuthSource:
S: 	BY2NAM01FT033.eop-nam01.prod.protection.outlook.com
S: X-MS-Exchange-CrossPremises-AuthAs: Anonymous
S: X-MS-Exchange-CrossPremises-TransportTrafficType: Email
S: X-MS-Exchange-CrossPremises-TransportTrafficSubType:
S: X-MS-Exchange-CrossPremises-SCL: 1
S: X-MS-Exchange-CrossPremises-Antispam-ScanContext:
S: 	DIR:Incoming;SFV:NSPM;SKIP:0;
S: X-MS-Exchange-CrossPremises-Processed-By-Journaling: Journal Agent
S: X-OrganizationHeadersPreserved: BYAPR14MB2183.namprd14.prod.outlook.com
S: 
S: ----boundary_26_a97744c9-4713-4a63-8bec-a65696010a1c
S: Content-Type: text/plain; charset="us-ascii"
S: Content-Transfer-Encoding: quoted-printable
S: 
S: =0A=0A
S: ----boundary_26_a97744c9-4713-4a63-8bec-a65696010a1c
S: Content-Type: application/octet-stream; name="Inv35877.pdf"
S: Content-Transfer-Encoding: base64
-serialized content after-

**Comment by jstedfast** [comment]
Notice that there is no `Content-Disposition: attachment` header. Therefor, by definition, they are not "attachments"... hence why they are not in the `Attachments` collection.

You need to use the `BodyParts` property instead.

**Comment by RafaelCastro9** [comment]
Is there anything I can tell the person sending the email that they're doing "wrong"? or any workaround you can recommend?

**Comment by jstedfast** [comment]
Just use the BodyParts instead.

**Comment by RafaelCastro9** [comment]
of course! thanks sir!!
