### ISSUE TITLE
Example to get BodyParts but not found

### ISSUE THREAD

**Issue by reinaldocoelho** [jstedfast/MimeKit#410]
Hi @jstedfast !

I´m using MimeKit to parse a RelatedPart email and I can´t get all parts (html and text) and EML attached.

Can you help-me with an example?
Follow the EML.
[email-body-parts-and-eml-attached.txt](https://github.com/jstedfast/MimeKit/files/2146412/email-body-parts-and-eml-attached.txt)

I´m try to get the HTML Body with this code:
```csharp
    _message.GetTextBody(MimeKit.Text.TextFormat.Html);
```

I expected this message to show this yellow part:
![image](https://user-images.githubusercontent.com/889634/42060708-1a6d0632-7afe-11e8-9c0c-b21abccfc32d.png)

Thanks.

**Comment by jstedfast** [comment]
Hi @reinaldocoelho 

The message structure looks like this:

```
multipart/mixed
   multipart/related
      multipart/alternative
         text/plain
         text/html   <-- this is the HTML that MimeKit returns
      image/jpeg (~WRD064.jpg)
      image/gif (image001.gif)
      image/jpeg (image002.jpg)
   message/rfc822
      multipart/alternative
         text/plain
         text/html   <-- this is the part in yellow


When you ask MimeKit to get you the text/html message body, it won't combine all text/html parts in the MIME structure, it'll only return the 1 text/html part that contains the actual message body.

In this particular case, the html that is highlighted in yellow is part of a message/rfc822 attachment and not part of the message body at all.

If you want to combine all text/html content... I would recommend starting with the `HtmlPreviewVisitor` class in the [FAQ](https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#q-how-do-i-tell-if-a-message-has-attachments) and modify the logic to combine all text/html content.

I'm not 100% sure how to combine HTML documents The Right Way since each HTML document might have conflicting stuff defined in the <head> block, but since this is email... it might be safe to strip all of that and just combine the content of the <body> tags? I'm not really sure...

**Comment by reinaldocoelho** [comment]
Thank you @jstedfast for your answer.

But if the "message/rfc822" is an attachment of the email, why the MimePart object doesn´t show the property "IsAttachment" with a true value?

Because the big problem I have is the MimeKit not show 
 this "message/rfc822" as an attachment neither show on the body.

Thank you again for return :-)

**Comment by jstedfast** [comment]
You mean the text/html part? Only the parent MessagePart will be marked as an attachment.
