### ISSUE TITLE
MemoryStream

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MimeKit#411]
Wouldn't it be better to use MemoryBlockStream here, to avoid MemoryStream resize-ing?

https://github.com/jstedfast/MimeKit/blob/2249574f33036cf8ab5a86262ddef581408d4f95/MimeKit/TextPart.cs#L306

**Comment by jstedfast** [comment]
Possibly, but then you need to clone it into a new byte array in order to feed it to Encoding.GetString()
