### ISSUE TITLE
Saving MimeMessage to EML end with encoding issues

### ISSUE THREAD

**Issue by honzasram** [jstedfast/MimeKit#414]
Hi, 

I'm Saving MimeMessages to EML but when I write it to FileStream, I get Encoding issues for MimeContent containing HTML text. We are using MS Outlook with Exchange server. I'm accessing it in .Net Core 2.0 via IMAP and saving it via CIFS to shared disk.

When I set encoding for while stream as UTF8 (or something else if I can detect it) I get issues only with HTML/text content of body. Headers are encoded correcly, but body despite encoding selected in MimeHeader is already incorrect and hard coded with errors. See attached Raw output of EML file. You can see instead of some characters getting =*something*. 
On picture you can see what I see on outlook. It is not so bad, but not good either. I guess Outlook look and repair for these encoding issues.

Can you help me somehow? 
Thank you.
```
using(var lMemStream = new MemoryStream())
{
	var lOptions = FormatOptions.Default.Clone();
	lOptions.International = true;
	aMessage.Message.WriteTo(lOptions, lMemStream);   

	lFile.Create();
	aMessage.Metadata.PathToSavedMail = lFile.FinalPath;

	using (var lStream = new StreamWriter(lFile.GetWriteStream(), Encoding.UTF8))
	{
		var lBytes = lMemStream.ToArray();
		lStream.BaseStream.Write(lBytes, 0, lBytes.Length);
		lStream.Flush();
	}
}
```

![capture](https://user-images.githubusercontent.com/9151345/42446024-3bdd21d8-8375-11e8-8987-596df8ca87fd.PNG)
[raw eml.txt](https://github.com/jstedfast/MimeKit/files/2175750/raw.eml.txt)

**Comment by jstedfast** [comment]
The message body is not in UTF-8, it's in iso-8859-2.

**Comment by honzasram** [comment]
Even if I save it in Latin2, it gets encoded improperly. 

Saved into Ubuntu machine with this:

```
var lTempFile = $"./savedmails/temp{lName}";
var lEncoding = Encoding.GetEncoding("iso-8859-2");
using (var lStream = new StreamWriter(new FileStream(lTempFile, FileMode.Create), lEncoding))
{
	var lBytes = lMemStream.ToArray();
	lStream.BaseStream.Write(lBytes, 0, lBytes.Length);
	lStream.Flush();
}
```
and got these:
```
 2018 12:23:50 +0200
From: =?iso-8859-2?Q?Jan_=A9r=E1mek_=28Ingeteam_a=2Es=2E=29?=
	<Jan.Sramek@ingeteam.com>
*snip*
<body lang=3D"EN-US" link=3D"#0563C1" vlink=3D"#954F72">
<div class=3D"WordSection1">
<p class=3D"MsoNormal">Superko=BB=E1tka ovl=E1dnou tento zni=E8en=FD sv=ECt=
.<o:p></o:p></p>
<p class=3D"MsoNormal">Co=BE takhle si d=E1t =B9pen=E1tov=FD kol=E1=E8ek.<o=
:p></o:p></p>
*snip*
```

**Comment by jstedfast** [comment]
Why are you trying to change the encoding using a StreamWriter in the first place? Just write the message to the file directly using message.WriteTo().

You are guaranteed to break the message doing what you are doing.

**Comment by jstedfast** [comment]
Also, try writing the message w/o changing the FormatOptions to set International to `true`. I don't understand why you are doing that (you shouldn't be).

**Comment by honzasram** [comment]
Reason for this code is almost three days of trying make it work. Classic "lets try this and that" until I ended here. 

I started with simple StreamWriter as this 
```
using (var lStream = new StreamWriter(new FileStream(lTempFile, FileMode.Create)))
{
	aMessage.Message.WriteTo(lStream.BaseStream);   
	lStream.Flush();
}
```
But I noticed that files are encoded in UTF8, message characters corrupted. So I assumed, UTF8 is the way and went to the rabbit hole with options. But unsuccessfully. 

So I tried this:
```
var lTempFile = $"./savedmails/temp{lName}";
var lEncoding = Encoding.GetEncoding("iso-8859-2");

using (var lStream = new StreamWriter(new FileStream(lTempFile, FileMode.Create), lEncoding))
{
	mLog.Info(lStream.Encoding);
	aMessage.Message.WriteTo(lStream.BaseStream);   
	lStream.Flush();
}
```
and this:
```
using (var lStream = File.Create(lTempFile))
{
	aMessage.Message.WriteTo(lStream);   
	lStream.Flush();
}
```
Again saved in UTF8 with corrupted characters.  So i assumed there is some shenanigans inside MimeKit, which sets Encoding. Went thru code and found no code which sets encoding. 

As per [this](https://stackoverflow.com/questions/46119872/encoding-issues-with-net-core-2) I should specify encoding, as it can vary by system. However whatever selected, encoding ended in UTF8. 
Now I do not understand why .Net core (on Linux) has this behavior. Do you have any clue? I Stripped my usecase to just save it correctly to local folder .

**Comment by honzasram** [comment]
So I have been digging around. Encoding on StreamWriter is working fine and indeed I should not be editing that as it is following RFC 822 and it is ASCII text. But then how it is possible that i get already corrupted characters as '=A9' instead of 'Š' in header

```
Received: from SSING10MBX5.ingeteam.local ([fe80::658d:129d:9fb:4747]) by
 SSING10HC4.ingeteam.local ([::1]) with mapi id 14.03.0123.003; Mon, 9 Jul
 2018 12:23:50 +0200
From: =?iso-8859-2?Q?Jan_=A9r=E1mek_=28Ingeteam_a=2Es=2E=29?=
	<Jan.Sramek@ingeteam.com>
```

**Comment by jstedfast** [comment]
They're not corrupted, they are encoded. That's the way MIME encodes message headers.

**Comment by jstedfast** [comment]
FWIW, this is the correct way to save the message to a file:

```csharp
using (var lStream = File.Create(lTempFile))
{
	aMessage.Message.WriteTo(lStream);   
	lStream.Flush();
}
```

**Comment by jstedfast** [comment]
You could work around this by setting the ContentTransferEncoding of the message body to EightBit or Base64.

**Comment by jstedfast** [comment]
No problem, glad you got everything working now :)
