### ISSUE TITLE
MimeEntity.Load(), MimeMessage   order of headers

### ISSUE THREAD

**Issue by audunn** [jstedfast/MimeKit#419]
Hi,
I am loading a MultipartSigned part from stream and then setting it as body of MimeMessage before calling writeTo() to serialize to disk and sending it out.

We have some thing like this:
```
                // load the multipart/signed
                multipartSigned = (MultipartSigned)MimeEntity.Load(inputStream);  
                MimeMessage mimeMessage = new MimeMessage();
                mimeMessage.Body = multipartSigned;
                mimeMessage.WriteTo(outStream);
```
This works fine for the most part except for one annoyance, when I use writeTo on that MimeMessage I get the MIME-Version: 1.0 header after the Content-Type.  Usually we have seen this before the Content-Type

```
Content-Type: multipart/signed; boundary="=-k5STxMwlNVJ4v7jmTB8tGg==";
	protocol="application/pkcs7-signature"; micalg=sha-1
MIME-Version: 1.0

--=-k5STxMwlNVJ4v7jmTB8tGg==

```

Is there anyway to make sure the output is like this?
```
MIME-Version: 1.0
Content-Type: multipart/signed; boundary="=-k5STxMwlNVJ4v7jmTB8tGg==";
	protocol="application/pkcs7-signature"; micalg=sha-1

--=-k5STxMwlNVJ4v7jmTB8tGg== 
```
Note if the multipartSigned is created "fresh", i.e using MultipartSigned.Create() as opposed to loaded from stream like above, the order of the output is as expected.

**Comment by jstedfast** [comment]
There's no real reason to care about this. It doesn't matter what order they are in.

**Comment by audunn** [comment]
That sounds good to me. Perhaps I am being being overly cautious and a bit curious why it would come out like that.

BTW I would like to thank you for this awesome library very good job.
