### ISSUE TITLE
DKIM Signature Verify is Fail for key size 2048

### ISSUE THREAD

**Issue by kapitaneo** [jstedfast/MimeKit#420]
Hello my friends, please help. I'm trying to check the letter sent from Yahoo to myself. 1024 is working fine(gmail for example). But with yahoo i have problems(key 2048). MimeMessage.Verify return false. I get the DNS public key (2048) normally.
Can anyone come across this? 
Thanks a lot for any help.

**Comment by jstedfast** [comment]
I'm going to need a test case.

**Comment by jstedfast** [comment]
Hmmm, the [DkimVerifier](https://github.com/jstedfast/MimeKit/tree/master/samples/DkimVerifier) sample app that I included with MimeKit verifies the DKIM-Signature just fine...

```
[fejj@localhost Debug]$ mono ./DkimVerifier.exe 2aa01730-ece0-461c-88f0-0781c303cc31.eml 
2aa01730-ece0-461c-88f0-0781c303cc31.eml -> VALID
[fejj@localhost Debug]$ 
```

Perhaps your code is creating the DKIM public key incorrectly?

**Comment by jstedfast** [comment]
The DNS TXT record in your screenshot appears to match what my DkimVerifier app gets as well:

```
p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuoWufgbWw58MczUGbMv176RaxdZGOMkQmn8OOJ/HGoQ6dalSMWiLaj8IMcHC1cubJx2gziAPQHVPtFYayyLA4ayJUSNk10/uqfByiU8qiPCE4JSFrpxflhMIKV4bt+g1uHw7wLzguCf4YAoR6XxUKRsAoHuoF7M+v6bMZ/X1G+viWHkBl4UfgJQ6O8F1ckKKoZ5KqUkJH5pDaqbgs+F3PpyiAUQfB6EEzOA1KMPRWJGpzgPtKoukDcQuKUw9GAul7kSIyEcizqrbaUKNLGAmz0elkqRnzIsVpz6jdT1/YV5Ri6YUOQ5sN5bqNzZ8TxoQlkbVRy6eKOjUnoSSTmSAhwIDAQAB;
```

**Comment by kapitaneo** [comment]
It's a very strange. What is difference can be in preparing keys (1024 and 2048) for verify?

**Comment by jstedfast** [comment]
It might be the way you parse the TXT record.

You also re-encode the base64 key. Why?

**Comment by kapitaneo** [comment]
Shame on me. :) It's a crutch. In some dns records, the key is moved to a new line. Replace didn't work. It was just a quick fix.
I tried your example - result Pass. I will look for a problem with the keys.
Thanks.
