### ISSUE TITLE
S/MIME MimeKit vs Openssl Digest mismatch 

### ISSUE THREAD

**Issue by audunn** [jstedfast/MimeKit#422]
[testtext.txt](https://github.com/jstedfast/MimeKit/files/2233277/testtext.txt)
Hi when testing a MimeKit generated S/MIME message we found that the message digest does not match a digest we get from openssl.

Given the plain text message  "some test text" saved in a text file 
We run the openssl command 
./openssl dgst -sha1 -hex testtext.txt
765fd0fb4ae6bc524d60acf1eedd2e7fd870d0c7

Using asn.1 editor I extract the digest from the message and it is de56e2a2f8ce34ac95839a6290790083ea25a5b5 

The message was created using something like this:
```

using (var ctx = new WindowsSecureMimeContext())
{
    var stream = new MemoryStream();
    var writer = new StreamWriter(stream);
    writer.Write(s);
    writer.Flush();
    stream.Position = 0;
    return stream;

    var mimePart = new MimePart("application", "octet-stream")
    {
        Content = new MimeContent(stream, ContentEncoding.Default)        
    };
        
    CmsSigner signer = new CmsSigner(x509Certificate2)
    {
    DigestAlgorithm = DigestAlgorithm.Sha1 
    };
    var multipartSigned = MultipartSigned.Create(ctx, signer, mimePart);                                      
}

```
The resulting message looks like this:

```
Content-Type: multipart/signed; boundary="=-mgTBqE506obbAZ25KUlOmA==";
 protocol="application/pkcs7-signature"; micalg=sha1
MIME-Version: 1.0

--=-mgTBqE506obbAZ25KUlOmA==
Content-Type: application/octet-stream

some test text
--=-mgTBqE506obbAZ25KUlOmA==
Content-Type: application/pkcs7-signature; name=smime.p7s
Content-Disposition: attachment; filename=smime.p7s
Content-Transfer-Encoding: base64

MIIE0gYJKoZIhvcNAQcCoIIEwzCCBL8CAQExCzAJBgUrDgMCGgUAMEcGCSqGSIb3DQEHAaA6
BDhDb250ZW50LVR5cGU6IGFwcGxpY2F0aW9uL29jdGV0LXN0cmVhbQ0KDQpzb21lIHRlc3Qg
dGV4dKCCAmgwggJkMIIBzaADAgECAgIB6TANBgkqhkiG9w0BAQ0FADAWMRQwEgYDVQQDEwtG
aXZlRGVncmVlczAeFw0xNzA2MDkxNDU5MjFaFw0zOTA1MDUxNDU5MjFaMCQxIjAgBgNVBAMT
GU1hdHJpeEFjY291bnRzIEVuY3J5cHRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQCzk7EnGSWxof1VgiEEI5ixWC+BSTISrDW3UZb892MYTQWbYA6iXYKGbe4ZFxXrcoMZ
JEwlQQJacfYIV456zsUvFasqSFi6iKBVDL8UT0kKMI8+38kvP+vwbo8DquKKCZT9RzuVrWby
SrlNrHQkgfYKKkENslglnEPWUYcBc4jpmfzDLJ7RX2bqbnTKxXAwoRhF2Mi+MVvnm1BIwWNI
KUR0W77JQ9bo96zMjmhjh0nn5rRXb8zVy3Fmoj+mWTPUAybx5rZA+2QHCSj83nrO41OxPhFp
l78f4BUtRQPr47CAMLtiZL5LDUZ6DuZKN3LxhNJHhLs5d6g+o03mrimAO+fDAgMBAAGjLzAt
MAsGA1UdDwQEAwIEsDAJBgNVHRMEAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMBMA0GCSqGSIb3
DQEBDQUAA4GBABvYWUcy0qz/jyg9VK/MpRyPv55Ob4yQgHc/PRY98S9z6O1b8rbyTFqoWTdM
yUXRJ07654KEs78q56eKlEjgZISsMhGp6YE69xBFKRYk/S/mwyTLXFQoIg3yGmwuDgtyXevX
gtQq1RIJrNmdEn5z8zrycWt/Ip0q2u13njz7DiYrMYIB9jCCAfICAQEwHDAWMRQwEgYDVQQD
EwtGaXZlRGVncmVlcwICAekwCQYFKw4DAhoFAKCBsDAYBgkqhkiG9w0BCQMxCwYJKoZIhvcN
AQcBMBwGCSqGSIb3DQEJBTEPFw0xODA3MjYxODMzNTVaMCMGCSqGSIb3DQEJBDEWBBTeVuKi
+M40rJWDmmKQeQCD6iWltTBRBgkqhkiG9w0BCQ8xRDBCMAsGCWCGSAFlAwQBKjALBglghkgB
ZQMEARYwCwYJYIZIAWUDBAECMA0GCyqDCIyaSz0BAQECMAoGCCqGSIb3DQMHMA0GCSqGSIb3
DQEBAQUABIIBAGtv896ml1RSK/+OFxyFmD1nyPU5+bkv/jleX8Qdfq4mLkTtBhKJEahZwu3j
ojrG1bw71XfizjQ0utRCvCL7U5u2McaD/MJiUS7Bne/ApKMSHbVvBvIAo94fKpN7aRQ+sXt2
OG/6SIBQRPhA2PBFIF13rkNtFLKYOLF3idyYVF1epEth/lxEs7rPx5ayuLxHVzSMvnkMRudn
Aqg8uPwmphYuaf3Yg1iVIVDVEbmjXm/qkMXAYd5rMrLHduxQFOw/kX4KuOj1N1XxKlOn2xMO
FWbbUb4FlYhIBc1Bl0YYK8rjkLJq7xURpKcSgKwfv969bLzRth4MvqPn+k0Pg24MmWQ=

--=-mgTBqE506obbAZ25KUlOmA==--
```

Are we missing something here like canonicalization or something that Mimekit does to the content before calculating the digest value?  The digest should match should it not? 

Also a followup questions if I may,
Is there a difference in the resulting CMS structure if generated by WindowsSecureMimeContext as oposed to say TemporarySecureMimeContext?
Can the output of Mimekit (S/MIME or CMS) be controlled in any way, say to restrict to older versions  of RFC?

**Comment by jstedfast** [comment]
You need to calculate the digest based on the full MIME entity, not just the content of said MIME entity.

In other words:

```
Content-Type: application/octet-stream

some test text
```

Also note that the above content should not end with a `\r\n`.

There may be a difference in structure between WindowsSecureMimeContext and anything that subclasses BouncyCastleSecureMimeContext just due to the fact that they use different CMS backends which may change the order of various CMS metadata properties and/or which (optional) metadata gets included.

There's no way to restrict MimeKit to older versions of S/MIME (it shouldn't be necessary anyway).

Hope that helps.

**Comment by audunn** [comment]
I notice that it seems like Content-Type: application/octet-stream  is included when calculating the digest is this expected?
So the content:
`Content-Type: application/octet-stream

some test text`
Via openssl gives digest value of  de56e2a2f8ce34ac95839a6290790083ea25a5b5
This is same digest as extracted from the CMS?

Also is the data is to be supposed to be included the CMS when using detached signatures via WindowsSecurityContext and not TemporarySecuritityContext?
See 1.2.840.113549.1.7.1   data(PKCS #7)    
![image](https://user-images.githubusercontent.com/3875306/43285280-ff14fe50-910d-11e8-8a6f-147dfd30dd69.png)

I am not sure this matters but curious to me.

**Comment by audunn** [comment]
Regarding the control over CMS structure I am specifically concerned with if it would be possible to get BouncyCastle to generate Definite Length encoded CMS (DER), seems like it is generating indefinite length encoded CMS while System.Security, via WindowsSecureMimeContext, uses Definite length. 
Is there any way to do this?

**Comment by jstedfast** [comment]
I don't know how to control Definite Length vs Indefinite Length - that would be a question for the BouncyCastle devs.

**Comment by audunn** [comment]
That is understandable,  thanks again for this excellent library and fantastic responses.
