### ISSUE TITLE
NOTIFY support?

### ISSUE THREAD

**Issue by davidchisnall** [jstedfast/MimeKit#429]
I didn't see anything in the code or documentation relating to the NOTIFY extension.  This is a lot more bandwidth- (and power-) efficient than having a connection per mailbox and using IDLE.  Are there any plans to support it?

**Comment by davidchisnall** [comment]
Ooops. filed against the wrong repository, and I see that the correct one has this in the TODO file.  Sorry for the noise.

**Comment by jstedfast** [comment]
No problem. I really like the way NOTIFY works, but I'm not sure how valuable it would be to implement since so few IMAP servers actually support it. That's why I haven't done it yet... there's also the problem with finding the right API to support the full feature set. Ideas on API design welcome :)

**Comment by davidchisnall** [comment]
Dovecot is the server that I most care about, so the lack of support elsewhere on the server side doesn't bother me too much.  I agree on the difficulty of API design, but it looks as if you already have most of the pieces that I'd want.  I think ideally you'd use the existing Events in `MailFolder` and provide a method that would send a NOTIFY command requesting every event that has a subscriber associated with it on the local `MailFolder` object, for each `MailFolder` owned by the current connection.  Ideally, adding or removing an event subscriber while in this state would trigger an update to the notify list.

Users would then be able to simply register subscribers for any of the events that they cared about, call the method to enable NOTIFY, and then idle, and receive notifications using exactly the same code that they do currently with IDLE.

**Comment by jstedfast** [comment]
I think Dovecot might be the only server implementation that I know of that supports it :)

**Comment by jstedfast** [comment]
Okay, MASSIVE new 2.1.0 releases of MimeKit and MailKit have been pushed. I would recommend reading the [ReleaseNotes](https://github.com/jstedfast/MailKit/blob/master/ReleaseNotes.md) - I think you'll appreciate at least ONE of the new features ;-)
