### ISSUE TITLE
Error importing thunderbid mbox

### ISSUE THREAD

**Issue by kooijtje** [jstedfast/MimeKit#430]
While importing a couple of mbox files (using thunderbird 52.9.1, Mailkit and MimeKit v.2.0.6 using nuget) using the following code:
public static void ParseThunderbirdFullFile(string box)
    {
      MimeKit.ParserOptions opt = new MimeKit.ParserOptions();
      opt.AddressParserComplianceMode = MimeKit.RfcComplianceMode.Loose;
      opt.AllowAddressesWithoutDomain = true;
      opt.ParameterComplianceMode = MimeKit.RfcComplianceMode.Loose;
      opt.Rfc2047ComplianceMode = MimeKit.RfcComplianceMode.Loose;
      opt.RespectContentLength = false;
      using (Stream fs = File.OpenRead($@"e:\Thunderbird_mail\{box}"))
      {
        var parser = new MimeKit.MimeParser(opt, fs, MimeKit.MimeFormat.Mbox);
        // Create new stream for results
        //var exportStream = new MemoryStream();
        bool err = false;
        int count = 0;
        while (!err && !parser.IsEndOfStream)
        {
          count++;
          Console.WriteLine($"Parsing message {count}");
          try
          {
            var message = parser.ParseMessage();    //kan ook async
            Console.WriteLine("Message:" + message.Subject);
          }
          catch (Exception e)
          {
            Console.WriteLine("error " + e.InnerException);
            err = true;
          }
        }
      }
    }

ParseThunderbirdFullFile("INBOX");

The code fails in Mimekit on a couple of messages (attached to this issue) and will not continue to read any further:
"Failed to parse message headers."
If i split the mailbox on From \r\n
 i can detect which messages generate the error. They all seem to contain a line starting with From 
but not ending on carriage return line feed.
I worked around this problem by splitting the file myself on From \r\n and parsing each part seperately.

My question: Is there a parse option which fixes a strict occurrence of the start of a message with "From \r\n" or can this be improved?

Kind regards,
Roeland Louwe Kooijmans

[ErrorParsingMimekit.zip](https://github.com/jstedfast/MimeKit/files/2386862/ErrorParsingMimekit.zip)

**Comment by jstedfast** [comment]
Please read https://www.jwz.org/doc/content-length.html to see why this is unfixable.

I recommend manually editing the INBOX file and munging the lines beginning with `"From "` that are not the start of a new message.

If the headers contained a `Content-Length` header, I would have recommended trying to enable that option in MimeKit's [ParserOptions](http://mimekit.org/docs/html/P_MimeKit_ParserOptions_RespectContentLength.htm), but it appears that Thunderbird chose to make their interpretation of mbox unlike anyone else's.

Feel free to try and work around Thunderbird's insanity by poking around inside of MimeParser.cs, but I won't be bothering.

**Comment by kooijtje** [comment]
Thank you for your extremely fast answer.  I understand why, I was just wondering why Thunderbird is not following standards and if there was a quick fix apart from splitting/munging myself.

Kind regards,
Roeland Louwe Kooijmans

Van: Jeffrey Stedfast <notifications@github.com>
Verzonden: zondag 16 september 2018 20:36
Aan: jstedfast/MimeKit <MimeKit@noreply.github.com>
CC: Roeland Louwe Kooijmans <r.louwe.kooijmans@scope.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [jstedfast/MimeKit] Error importing thunderbid mbox (#430)


Please read https://www.jwz.org/doc/content-length.html to see why this is unfixable.

I recommend manually editing the INBOX file and munging the lines beginning with "From " that are not the start of a new message.

If the headers contained a Content-Length header, I would have recommended trying to enable that option in MimeKit's ParserOptions<http://mimekit.org/docs/html/P_MimeKit_ParserOptions_RespectContentLength.htm>, but it appears that Thunderbird chose to make their interpretation of mbox unlike anyone else's.

Feel free to try and work around Thunderbird's insanity by poking around inside of MimeParser.cs, but I won't be bothering.
