### ISSUE TITLE
Dkim signiture fails at Gmail if body contains Quoted-Printable escape chars

### ISSUE THREAD

**Issue by SimiyonkE** [jstedfast/MimeKit#431]
Hi,

I am using MimeKit to Dkim sign e-mail messages. The problem arises when the body contains empty space at the end of the line, Quoted-Printable encoding escapes this space with equals sign (=), and whenever there is a Quoted-Printable escape char the Dkim signature verification fails at Gmail. If there is no escape character the verification passes. When i send the same messages to Yahoo, the verification always passes. For the testing purposes i am using Yahoo's smtp server for sending mails.

Here are the sample email payloads:

The one that fails at Gmail with the Quoted-Printable escape characters in Body:
[GmailFails.txt](https://github.com/jstedfast/MimeKit/files/2387796/GmailFails.txt)

The one that passes at Gmail without any escape characters in Body:
[GmailPasses.txt](https://github.com/jstedfast/MimeKit/files/2387802/GmailPasses.txt)

The one that passes at Yahoo with the Quoted-Printable escape characters in Body:
(What is interesting here is that Yahoo is not even showing the escaped characters, nor the Content-Transfer-Encoding header in the payload) 
[YahooPasses.txt](https://github.com/jstedfast/MimeKit/files/2387813/YahooPasses.txt)

Here is the sample code i'm using for this:

`
public void SignEmail(MailMessage message)
{
MimeMessage msg = (MimeMessage)message;

DkimSigner signer = new DkimSigner(keyPair.Private, signingSettings.Domain, signingSettings.Selector, signingSettings.Encryption);
List<HeaderId> signHeaders = GetUsedHeaders(msg);

msg.Sign(signer, signHeaders, DkimCanonicalizationAlgorithm.Relaxed, DkimCanonicalizationAlgorithm.Relaxed);

using (MailKitSmtp.SmtpClient smtp = new MailKitSmtp.SmtpClient())
{
	smtp.ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
	{
		return true;
	};
	smtp.Connect(smtpAddress);
	smtp.Send(msg);
}}
`

I also tried calling Prepare() method before dkim signing the message, with all three variations constraints (7bit/8bit/default) with the same effect.

Please advise,

Thanks,
Aleksandar

**Comment by jstedfast** [comment]
You absolutely need to call `Prepare (EncodingConstraint.SevenBit)` before signing.

I would also recommend stripping trailing whitespace from your message bodies to work-around this bug in GMail.

I can't make MailKit strip those lines because some people use MailKit to DKIM-sign messages that have already been signed by another source and therefore modifying the message in any way in MailKit's DKIM-Sign logic would break that.

**Comment by SimiyonkE** [comment]
Thanks on the quick replay, will try this.
