### ISSUE TITLE
Unicode stream

### ISSUE THREAD

**Issue by MihaMarkic** [jstedfast/MimeKit#432]
**Describe the bug**
When loading MimeMessage from a stream containing Unicode text it throws an error "Failed to parse message headers.".

**To Reproduce**
1. Load an eml file and convert it to a stream containing unicode characters.
2. Call MimeMessage.Load on that stream. Setting ParserOptions.CharsetEncoding doesn't help.
3. Exception is thrown

**Expected behavior**
Message would load.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: MimeKit 2.0.6

**Context
Perhaps unicode is not supported or I'm doing something wrong?

**Comment by jstedfast** [comment]
Unicode is not supported.

The ParserOptions.CharsetEncoding property is for converting unknown (i.e. broken) 8bit text in the header values.

MIME is supposed to be ASCII, so converting it to 16-bit or 32-bit Unicode is obviously nothing like ASCII.
