### ISSUE TITLE
MimeKit attachments don't seem to be working with iPhone mail app

### ISSUE THREAD

**Issue by adamburr100** [jstedfast/MimeKit#437]
I'm using Mimekit to construct emails containing a PDF attachment. This works well in every case, except when the recipient has an iPhone. On an iPhone, the email appears in their inbox with a paperclip symbol next to it. However when they open the email there is no attachment present.

Does anyone have any ideas how I can resolve this?

Adam

**Comment by jstedfast** [comment]
If it shows a paperclip, then the iPhone mail client program sees the attachment... I'm just not sure why it's not displaying it to you. That is bizarre.

Question: Are you using the BodyBuilder to construct your message? Or constructing it by hand? If you are constructing it by hand, are you setting the `ContentId` property? If you are, try not setting it and if you aren't setting it, try setting it.

Some mail clients get confused if the Content-Id header is set or not set when they expect the opposite. These mail clients are broken, but... yea. Welcome to the world of email compatibility.

If that doesn't work, let me know and I'll try to come up with other ideas to try.

Or... if you are able, try sending some messages to your iPhone and seeing which ones "work" and which ones don't. When you find one that works, try to imitate the way that it constructs those messages (add the headers that it adds, set similar values, etc).

If you don't have any success, attach a sample message here written by whatever mail client you find that works and I will take a look at it and try to help you massage your code such that it gets the same result.

**Comment by jstedfast** [comment]
Sure, email me at jeff.stedfast@gmail.com and I'll open it in my iPhone.

**Comment by adamburr100** [comment]
What email address should I send it to?

**Comment by jstedfast** [comment]
The one I linked to in my comment (you might need to visit github to see it?)

**Comment by adamburr100** [comment]
Done.  Thanks.

**Comment by jstedfast** [comment]
Thanks. I see the problem...

Instead of doing `builder.LinkedResources.Add`, do `builder.Attachments.Add`.

What's happening here is that you are telling MimeKit that the HTML references the pdf such that when the receiving client renders the message, the pdf gets displayed inline.

Adding it as a regular attachment *should* fix the problem.

**Comment by adamburr100** [comment]
Hi Jeff,

That worked perfectly.  Thanks so much for your help and sorry that I put
you to this trouble.

Regards,

Adam
