### ISSUE TITLE
TypeLoadException: The generic type 'System.Func`2' was used with an invalid instantiation in assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.

### ISSUE THREAD

**Issue by RemarkLima** [jstedfast/MimeKit#438]
Hi,

I've narrowed this issue here: https://github.com/aspnet/Home/issues/3457 to the `MailboxAddress` type as a return from a get method within a model.

To reproduce, clone the repo here: https://github.com/RemarkLima/Func2Test

Then hit the submit button. The issue occurs with .NET core 2.1 model binding to a model with `MailboxAddress` as a return type.

This is within Visual Studio 2017 using Core 2.1 and referencing the latest 2.0.6 versions of MimeKit.

Anything I can do to help, please let me know.

**Comment by jstedfast** [comment]
I would recommend keeping the issue filed against aspnet until they can determine that it has something to do with MimeKit because I just don't see how it could be a bug in MimeKit.
