### ISSUE TITLE
Smime message in TNEF part is converted into a MultiPart/Mixed message

### ISSUE THREAD

**Issue by ymassad** [jstedfast/MimeKit#441]
I have an Smime message that is encapsulated inside a TNEF part.

The content type of the root part is application/ms-tnef.

This TNEF message contains a single attachment (smime.p7m).

If I use TnefPart.ConvertToMessage(), I get a MimeMessage that has a content type of multipart/mixed what contains a single part underneath it: application/x-pkcs7-mime; name=smime.p7m

Is this a bug? Shouldn't smime messages have the root mime entity be of content type application/x-pkcs7-mime (without having the multipart/mixed part)?

**Comment by jstedfast** [comment]
In an ideal world? I suppose, but it doesn't really matter.
