### ISSUE TITLE
Q: Closing/disposing streams

### ISSUE THREAD

**Issue by Peperud** [jstedfast/MimeKit#444]
What is the general guideline for closing/disposing streams (and perhaps not only) in MimeKit? 
Seems like the streams passed on to Load/Write/Decode functions are responsibility of the caller. Fair enough.
What about the content streams that get attached to entities? 
MimePart for instance has ContentObject and Content properties that have streams, though MimePart itself does not implement IDisposable. 
Makes it unclear what should be disposed (and when).

**Comment by jstedfast** [comment]
I think if you think about it, it becomes obvious.

If you set a Stream as a property on an object (such as MimePart's Content property), then you are responsible for disposing it when you are done with the message.

**Comment by jstedfast** [comment]
Also up to you to dispose.

**Comment by jstedfast** [comment]
I should note that parsed messages will reference `MemoryBlockStream`s and/or `BoundStream`s.

`MemoryBlockStream` is similar to `MemoryStream` in that it really just uses managed memory so disposing it is not generally needed. I guess with `MemoryStream` on some platforms *might* be unmanaged memory and thus need to be disposed, but that is never the case with `MemoryBlockStream`.

`BoundStream` only gets used when you pass `persist: true` to the parser/Load methods and these streams just reference the `FileStream` or whatever stream you passed to the parser/Load methods and therefore don't really need to be disposed either (they only have stream offsets).

So... I guess technically you never need to dispose `MimePart` content streams from a parsed message.

**Comment by Peperud** [comment]
Thanks. This sounds much better. It would be a huge drag for a consuming application to have to always traverse the object tree and know all the internals and implementation details in order to properly dispose objects.

**Comment by jstedfast** [comment]
Yea, I agree... which is why I created MemoryBlockStream so I could be sure it wouldn't technically need to be disposed :)

Disposing it will immediately free up the blocks of memory that it references, though. But the GC will eventually get to that anyway.

**Comment by Peperud** [comment]
> I had a patch at one point to make MimeMessage disposable, but the problem is that one of the ways to use MimeKit is to parse a MimePart and then share it among multiple messages. That completely breaks if you dispose one of those messages.

Wouldn't this still be conceptually better? 
Assuming it is the consumer that is doing this sharing, it would be up to them not to dispose when not appropriate.

**Comment by jstedfast** [comment]
It opens up a sea of problems when, for example, one message goes out of scope.

At this point it's too late to add this because it'd break existing apps.
