### ISSUE TITLE
Support for retrieving certificates from Azure KeyVault

### ISSUE THREAD

**Issue by Eneuman** [jstedfast/MimeKit#445]
Today the CmsSigner constructor supports 3 different ways to supply a certificate.
Unfortunately none of them are very easy to use when the certificate is stored in Azure KeyVault.

It would be great if the constructor could accept a "IKeyStoreProvider" as parameter, a "CertificateName" and a password. The "KeyStoreProvider" is a interface that the user have to impliment.

It could look like this:
```
public class MyAzureKeyVaultProvider : IKeyStoreProvider{
.... my implimentation
}

 var signer = new CmsSigner(MyAzureKeyVaultProvider, "MyPersonalCertificateName", "MyCertificatePassword");
```

**Comment by jstedfast** [comment]
I guess I don't understand how this API that you are proposing is at all helpful.

Don't you still need to get an X509Certificate and an AsymmetricKeyParameter?

**Comment by jstedfast** [comment]
It seems to me that it would be easier to just create a custom CmsSigner factory that would take your MyAzureKeyVaultProvider, a certificateName and a password.
