### ISSUE TITLE
MailboxAddress throws exception if there's a dot before @ in the email

### ISSUE THREAD

**Issue by johnnyoshika** [jstedfast/MimeKit#454]
**Describe the bug**
Constructing a `MailboxAddress` with an email that has a dot before @ (e.g. `foo.@email.com`) throws a MineKit.ParseException:

**To Reproduce**
1. Install MimeKit version 2.1.1
2. Try this: ` var address = new MailboxAddress("foo.@email.com");`
3. You will get a MimeKit.ParseException

**Expected behavior**
`foo.@email.com` is a valid email address, so MailboxAddress should accept it.

**Screenshots**
![image](https://user-images.githubusercontent.com/504505/50652940-dfe08b00-0f3c-11e9-8799-876458685fc3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: any

**Comment by jstedfast** [comment]
That's not a valid email address.

```
   addr-spec       =   local-part "@" domain

   local-part      =   dot-atom / quoted-string / obs-local-part

   atext           =   ALPHA / DIGIT /    ; Printable US-ASCII
                       "!" / "#" /        ;  characters not including
                       "$" / "%" /        ;  specials.  Used for atoms.
                       "&" / "'" /
                       "*" / "+" /
                       "-" / "/" /
                       "=" / "?" /
                       "^" / "_" /
                       "`" / "{" /
                       "|" / "}" /
                       "~"

   atom            =   [CFWS] 1*atext [CFWS]

   dot-atom-text   =   1*atext *("." 1*atext)

   dot-atom        =   [CFWS] dot-atom-text [CFWS]

   specials        =   "(" / ")" /        ; Special characters that do
                       "<" / ">" /        ;  not appear in atext
                       "[" / "]" /
                       ":" / ";" /
                       "@" / "\" /
                       "," / "." /
                       DQUOTE
```

As you can see above, the `local-part` token is not allowed to end with a `.`

**Comment by johnnyoshika** [comment]
@jstedfast That's strange. The email `foo.@email.com` passes Chrome's email validator. If you create an HTML field like this:

```
<input name="email" type="email" value="" />
```

Chrome will allow `foo.@email.com`.

According to this Stackoverflow post, https://stackoverflow.com/a/7786283/188740, Chrome's email validator regex is:

`
[a-z0-9!#$%&'*+/=?^_`{|}~.-]+@[a-z0-9-]+(\.[a-z0-9-]+)*
`

which allows `foo.@email.com`: https://regex101.com/r/neZ4Vx/1

I'm starting to see quite a few gmail addresses with dot that precedes @. Could it be that there are different specs?

**Comment by jstedfast** [comment]
Well, there *are* 2 different specs (I'll post the syntax grammar for the other spec in a moment), but you have to keep in mind that a browser regex validator is not a strict validator, it is just a loosey-goosey way of filtering out the most obviously invalid email addresses.

You might find this article interesting on the topic: http://quetzalcoatal.blogspot.com/2013/12/why-email-is-hard-part-4-email-addresses.html

Keep in mind that the regexes that he provides at the bottom assume no CFWS (which is probably safe to assume in a web form textbox). Note also that his regexes do not match `foo.@email.com`.

Now, as promised, the syntax grammar specification for SMTP ([rfc5321](https://tools.ietf.org/html/rfc5321)):

```
   Mailbox        = Local-part "@" ( Domain / address-literal )

   Local-part     = Dot-string / Quoted-string
                  ; MAY be case-sensitive

   Dot-string     = Atom *("."  Atom)

   Atom           = 1*atext

   Quoted-string  = DQUOTE *QcontentSMTP DQUOTE
```

Once again, the `local-part` token is not allowed to begin or end with a `.` character.
