### ISSUE TITLE
Accept or Decline Meeting request office 365

### ISSUE THREAD

**Issue by janandojan** [jstedfast/MimeKit#455]
How can I Accept or Decline Meeting requests from office 365 using mailkit or mimekit?

**Comment by jstedfast** [comment]
First, you would need to get the `MimeMessage` that contains the meeting request.

Then you would need to locate the meeting request attachment (usually a MIME part with a Content-Type of `text/ical` and/or has a filename with a ".ics" extension).

Then you'll need to use something like https://github.com/rianjs/ical.net to parse the attachment and after that, I don't know, you might need to send a reply email but I have no idea what it would contain.

You might need to read the appropriate RFC (over at the http://www.ietf.org website).

Hope that helps.

**Comment by janandojan** [comment]
Thank you @jstedfast for reply!!
I am already using ical.net library to read calendar part from the new messages that I receive.
Also with this library I can successfully send a new calendar type email using .ics attachment.
My question is how can I reply/responde to calendar message. I tried to change the "status part" of the original .ics file that I received to ACCEPTED and reply new message with the modified .ics as attachment, but it doesn't work, the receiver just getting a new email with my .ics attachment, so his original email stays unanswered. (sorry for bad english :-))
