### ISSUE TITLE
Attachments are getting removed 

### ISSUE THREAD

**Issue by kiru2011** [jstedfast/MimeKit#457]
Hi,

We have recently moved from SMTPClient to MailKit and below is our implementation for sending emails with attachments. This seems to work in most cases but found many of our clients complaining that the attachment gets removed from the email. Only the filename of the attachment appears in the body of the email.
Could you please let me know if I missed some attribute in the email headers which is causing the attachments to be removed?
The MIME tree in the generated email looks like this
multipart/mixed
multipart/alternative
text/plain
text/html
application/pdf

```C#
//show the content without the tags
string textBody = Regex.Replace(text, "<[^>]*>", "\n");
 bodyBuilder.TextBody = textBody; 
 bodyBuilder.HtmlBody = text;

 // create an attachment for the file located at path
using (FileStream attachStream = File.OpenRead(filPair.Key))
{
	//copy the stream to a memeory stream so that it is not locked while moving the processed files
	MemoryBlockStream attachMemory = new MemoryBlockStream();
	attachStream.CopyTo(attachMemory);
	
	string mailContentType = System.Web.MimeMapping.GetMimeMapping(filPair.Key);                                           
	var attachment = new MimePart(mailContentType)
	{
		Content = new MimeContent(attachMemory, ContentEncoding.Default),
		ContentDisposition =
		  new MimeKit.ContentDisposition(
			  MimeKit.ContentDisposition.Attachment),
		ContentTransferEncoding = ContentEncoding.Base64,
		FileName = Path.GetFileName(filPair.Value)
	};

	//encoding method changed to Rfc2047 to avoid filenames coming as unnamed attachments
	Parameter param;
	if (attachment.ContentDisposition.Parameters.TryGetValue("filename", out param))
		param.EncodingMethod = ParameterEncodingMethod.Rfc2047;

	bodyBuilder.Attachments.Add(attachment);
}

 mailMsg.Body = bodyBuilder.ToMessageBody();   
```

**Comment by jstedfast** [comment]
The code looks ok to me. Can you provide some example messages that your clients are saying are missing the attachments? I need to look at the raw MIME to see if something is wrong.

You can zip them up and email them to jestedfa@microsoft.com if you want them to remain private or you can attach them to this github issue if they don't contain any sensitive info. Feel free to scrub the message(s) of email addresses and things like that (`Received` headers might also be worth scrubbing).

**Comment by jstedfast** [comment]
Closing this issue until some examples can be found.
