### ISSUE TITLE
Allow parsing of corrupt headers by ignoring malformed lines

### ISSUE THREAD

**Issue by alex-becker-startp** [jstedfast/MimeKit#458]
I want to load and parse mime messages with malformed header parts.
Here is a sample where the `From:` tag is missing:
```
 <someone@domain.com>
To: <other@domain.com>
MIME-Version: 1.0
...
```

I would like to enable a parsing mode where malformed hader lines are ignored.
When I open the sample above in Thunderbird, the mail is loaded and no from address is available.

But with MimeKit I have no chance to load the mail at all.
Currently a `System.FormatException` with message text **Failed to parse message headers** is thrown.

**Comment by jstedfast** [comment]
The problem with asking me to do this is that there's an infinite number of ways that message headers can be corrupted/incomplete/whatever which makes handling them all impossible.

If you want to send me a patch, I'll look at it, but I'm not keen on wasting my own time trying to chase a never-ending slew of "MimeKit can't parse this type of corruption, MimeKit can't handle that type of corruption...".

Trust me, it never ends.
