### ISSUE TITLE
MimeMessage memory usage and performance of MemoryBlockStream

### ISSUE THREAD

**Issue by jjxtra** [jstedfast/MimeKit#460]
Right now MimeMessage.Load* loads everything into memory, even when loading from a file. For large email messages on a busy server smtp this can be a memory and performance problem.

The solution I would like is that MimeMessage is smart to have the stream for embedded attachments or external attachments be a link to the source stream. MemoryBlockStream is used currently but requires that each and every byte be copied. If there was a version of MemoryBlockStream with blocks that simply referenced a source stream, offset into stream and number of bytes, this would avoid having to copy the data into memory.

If the source stream is not seekable, then of course simply use MemoryBlockStream as is with a copy of the data.

If there are concerns about breaking backwards compatibility or having MimeMessage be an encapsulated, non-referencing class, then perhaps a parameter in the constructor to enable this kind of stream referencing?

Please let me know if I am misunderstanding anything.

**Comment by jstedfast** [comment]
I gather you didn't notice BoundStream or the `persistent` argument when parsing messages ;-)

It already implements exactly what you are proposing.

**Comment by jjxtra** [comment]
I was using the string instead of Stream parameter. Would it make sense to add persistent as the default if passing a file name in?

**Comment by jstedfast** [comment]
Can't do that for exactly the reasons you stated... if you open the file yourself, then you can use `persist`.

**Comment by jjxtra** [comment]
Sounds good. Thanks so much for taking the time. I am using this in a C# smtp server: https://github.com/DigitalRuby/MailDemon

Your library has been a life saver. Do you accept donations?

**Comment by jstedfast** [comment]
No problem and I'm happy that you've found MimeKit to be so helpful! :-)

Hearing about your server also makes me glad that I have a split between MimeKit and MailKit so that you don't have to pull in all of that client code. I'll have to check it out.

I do accept donations: https://www.paypal.com/pools/c/857bnxBTXg

**Comment by jjxtra** [comment]
I use both mimekit and mailkit in my mail server (mail kit to send messages on the server) and of course mime kit to parse and create messages. Keg of beer coming your way!

**Comment by jjxtra** [comment]
What is the best way to clone mime message but change just the to and from addresses? I would need to sign the message afterwards so I don't think I can use the send overloads that take to and from lists...

**Comment by jstedfast** [comment]
Unfortunately there's no Clone()-like method, but what I would suggest as the easiest way to do this is something like this:

```csharp
var memory = new MemoryStream ();
message.WriteTo (memory);
memory.Position = 0;

var cloned = MimeMessage.Load (memory, persistent: true);
```

(the `persistent` parameter value doesn't really matter, it could be true or false, but it is probably more efficient to use `true`).

**Comment by jjxtra** [comment]
So performance from memory stream will be significantly better than a file?

**Comment by jstedfast** [comment]
Depends on the system I suppose, but in general, yes.

You could also try using a MimeKit.IO.MemoryBlockStream which might be faster than MemoryStream.
