### ISSUE TITLE
[Feature/Question]: Bulk mail signing MimeMessage

### ISSUE THREAD

**Issue by jjxtra** [jstedfast/MimeKit#462]
I am looking at the MailTransport class.

Some of the overloads of the Send and SendAsync allow overloading the to and from mail headers. It does not appear possible to sign the mail message when passing in these parameters.

What is the best way to send bulk mail, be able to sign the message and re-use a single mime message? Maybe MimeMessage is not meant to be thread safe and this does not matter. But ideally, I'd like to use those overloads on a single MimeMessage and be able to sign the outgoing message.

Right now I am saving the mime message to a file and then having each background task load a mime message from that file using persistent = true, then changing the to and from headers, calling prepare and then singing, and finally sending the message without the to and from overloads.

Please let me know if there is a better way.

**Comment by jjxtra** [comment]
Looks like you responded to my other comment. Should we leave this open and paste in your response for future users to see?

**Comment by jstedfast** [comment]
Probably the best way to do this is to do what you are already doing (with the minor change I suggested in the other question to use `MemoryStream` or `MimeKit.IO.MemoryBlockStream` instead of a file).

You might be able to improve this more if you just remove the signature and sign again instead of cloning the original message over and over.

For example:

```csharp
void BulkSend (MimeMessage message, List<BulkInfo> bulk, MimeEntity body)
{
    using (var ctx = CreateCryptoContext ()) {
        for (int i = 0; i < bulk.Count; i++) {
            message.From.Clear ();
            message.From.Add (bulk[i].Sender);
            message.To.Clear ();
            message.To.AddRange (bulk[i].Recipients);
            message.Body = MultipartSigned.Create (ctx, bulk[i].Signer, bulk[i].DigestAlgo, body);
            client.Send (message);
        }
    }
}
```
