### ISSUE TITLE
Only attachment email content not show Body with IsAttachment flag

### ISSUE THREAD

**Issue by reinaldocoelho** [jstedfast/MimeKit#464]
**Describe the bug**
Simple email only with headers and attachment show attachment as Body content but flag IsAttachment was False.

**To Reproduce**
1. Load attached file:
    * _message = MimeMessage.Load(filePath);
2. Look to  _message.Body.ContentType and see it is a File.
3. Look to _message.Body.IsAttachment and it´s False

**Expected behavior**
I expected property IsAttachment be true when EML body is a file.
Or please, explain to me how the better way to identify and obtain this Attachment file on email.

**Desktop:**
 - OS: Windows 10

**Additional context**
Follow the example file with exact same situation of the problem.

Same EML of I received:
https://gist.github.com/reinaldocoelho/4aa6ddb4e6d5c49268d21914be903999

Thanks.

**Comment by jstedfast** [comment]
MimeKit's `IsAttachment` property just checks the `Content-Disposition` header has a value of `attachment`. If the header does not exist or if the value is `inline` (or anything other than `attachment`), then the `IsAttachment` property will be `false`.

If you want to assume that any MimePart that has a `Content-Type` header with a `name` parameter, then you can do this:

```csharp
var isAttachment = bodyPart.ContentType.Name != null;

// or

var isAttachment = bodyPart.ContentType.Parameters.Contains ("name");
```

Hope that helps and glad to see you using MimeKit! :-)

**Comment by reinaldocoelho** [comment]
Thank´s @jstedfast.
I understand the case now, and I will validate better.
I told you before that I use both libraries. :-P
Thank you again!
