### ISSUE TITLE
Make MimeKit.FormatOptions MaxLineLength virtual to allow longer Header values

### ISSUE THREAD

**Issue by runerys** [jstedfast/MimeKit#469]
**Is your feature request related to a problem? Please describe.**
I'm trying to set a Subject header longer than 78 characters (without formatted breaks). And it seems quite impossible without modifying the source code and change the implementation of FormatOptions. I am definitely in a situation where "I really want this, and know what I'm doing". I'm not sending regular emails, but formatting a message for SMTP-integration.

**Describe the solution you'd like**
If the FormatOptions.MaxLineLength property is made virtual, I can inherit FormatOptions into a subclass that provides a longer line length. An instance of this subclass can be used in Header.SetValue(...). The functionality is demonstrated in this test:

```csharp
[Test]
public void ShouldBeAbleToAvoidLineBreaksWithCustomFormatOptions()
{
    var longSubject = new string('*', FormatOptions.Default.MaxLineLength * 2);
    var mimeMessage = new MimeMessage();

    var subject = new Header(HeaderId.Subject, string.Empty);
    mimeMessage.Headers.Add(subject);

    var formatOptions = new MaxLineLengthFormatOptions(FormatOptions.CloneDefault());
    subject.SetValue(formatOptions, Encoding.UTF8, longSubject);
    
    string messageAsString;
    using (var stream = new MemoryStream())
    {
        mimeMessage.WriteTo(stream);
        messageAsString = Encoding.UTF8.GetString(stream.ToArray());
    }

    Assert.IsTrue(messageAsString.Contains(longSubject));
    Assert.IsFalse(messageAsString.Contains("=?us-ascii?q?"));
}

public class MaxLineLengthFormatOptions : FormatOptions
{
    /* Not too happy about this constructor - open for suggestions */
    public MaxLineLengthFormatOptions(FormatOptions options)
    {
        this.NewLineFormat = options.NewLineFormat;
        this.EnsureNewLine = options.EnsureNewLine;
        this.AllowMixedHeaderCharsets = options.AllowMixedHeaderCharsets;
        this.ParameterEncodingMethod = options.ParameterEncodingMethod;
        this.International = options.International;
        options.HiddenHeaders.ToList().ForEach(x => this.HiddenHeaders.Add(x));
    }

    public override int MaxLineLength => MaximumLineLength;
}     

/******** Suggested FormatOptions Change **********/
public class FormatOptions
{
   // Make virtual, please :)
    public virtual int MaxLineLength 
    {
        get { return DefaultMaxLineLength; }
    }
}
```
I can subclass FormatOptions now, but MimeKit will still use FormatOptions.MaxLineLength - as it's not virtual today.

In my opinion, the suggested solution will not open up for accidential modifications of FormatOptions, as the code mostly uses FormatOptions.Default around - unless I'm really specific and use Header.SetValue(options, ...).

**Describe alternatives you've considered**
- Cloning and modifying the source code (I'm doing this today), but I'd really like to get updates through NuGet.
- Reflection: Not working, since FormatOptions.DefaultMaxLineLength is a const - not a field.
- Subclassing todays FormatOptions: Not working, since the MaxLineLength property is not virtual.
- Suggesting a setter for FormatOptions.MaxLineLength. Already rejected in #236.

**Additional context**
The issue has already been mentioned in #236. There a setter for MaxLineLength was considered and rejected. That's ok - however with the suggested solution here, I can achieve the same - but have to be quite a bit more specific.

**Comment by jstedfast** [comment]
I added a setter.

**Comment by runerys** [comment]
I don't think the guard clause works as intended:
if (value < MinimumLineLength || value > MaxLineLength)
I guess it should be:
if (value < MinimumLineLength || value > **Maximum**LineLength)

**Comment by jstedfast** [comment]
Yes, you are correct. Thanks.

**Comment by runerys** [comment]
Perfect! You made my day :)

```csharp
var formatOptions = FormatOptions.CloneDefault();
formatOptions.MaxLineLength = FormatOptions.MaximumLineLength;
subject.SetValue(formatOptions, Encoding.UTF8, longSubject);
```
Now, I'll just be awaiting Your next NuGet release before I can simplify the library update routines on my side.

Thanks!

**Comment by jstedfast** [comment]
I've been trying to figure out publishing nugets of each git revision to a nuget feed, but so far all I've figured out is how to publish them as a zip.

For example, if you go to https://dev.azure.com/jestedfa/MimeKit/_build?definitionId=1 - you can choose a build, then click "Artifacts" and it will present you with a way to download the built nuget (inside of a zip file, unfortunately).

I mention this so that you can grab the build in the meantime.

**Comment by runerys** [comment]
No problem - I've already pulled and built it locally. "Works on my
computer" - all good ;)

Den fre. 1. mar. 2019 kl. 12:46 skrev Jeffrey Stedfast <
notifications@github.com>:

**Comment by runerys** [comment]
Checked out the Azure DevOps Pipeline - very nice!

Den fre. 1. mar. 2019 kl. 12:54 skrev Rune Rystad <runerystad@gmail.com>:
