### ISSUE TITLE
Content-ID contains "(" and ")" the value is null 

### ISSUE THREAD

**Issue by Xgleich8** [jstedfast/MimeKit#472]
**Describe the bug**

If the Content-ID contains parentheses then the value is "null".

**To Reproduce**

Set `content-id: <Messe_Bauma_rz(1)_ae284449-6bdc-488f-8ec3-5be5e5b09efb.jpg>`

**Expected behavior**

The value should be `Messe_Bauma_rz(1)_ae284449-6bdc-488f-8ec3-5be5e5b09efb.jpg`.

**Desktop (please complete the following information):**
 - OS: Windows 10 (1806)
 - Browser -
 - Version -

**Additional context**
The Problem is MailboxAddress in the MimeEntiy
```
MailboxAddress.TryParse("<Messe_Bauma_rz(1)_ae284449-6bdc-488f-8ec3-5be5e5b09efb.jpg>", out  InternetAddress adr)
```

**Comment by jstedfast** [comment]
That's technically an illegally formed content-id value. I'll have to think about how to solve this in an acceptable way.

Both Message-ID and Content-ID headers are supposed to have a `msg-id` token as their value. The `msg-id` token is defined as:

```
   msg-id          =   [CFWS] "<" id-left "@" id-right ">" [CFWS]

   id-left         =   dot-atom-text / obs-id-left

   id-right        =   dot-atom-text / no-fold-literal / obs-id-right

   no-fold-literal =   "[" *dtext "]"

   atext           =   ALPHA / DIGIT /    ; Printable US-ASCII
                       "!" / "#" /        ;  characters not including
                       "$" / "%" /        ;  specials.  Used for atoms.
                       "&" / "'" /
                       "*" / "+" /
                       "-" / "/" /
                       "=" / "?" /
                       "^" / "_" /
                       "`" / "{" /
                       "|" / "}" /
                       "~"

   atom            =   [CFWS] 1*atext [CFWS]

   dot-atom-text   =   1*atext *("." 1*atext)

   dot-atom        =   [CFWS] dot-atom-text [CFWS]

   specials        =   "(" / ")" /        ; Special characters that do
                       "<" / ">" /        ;  not appear in atext
                       "[" / "]" /
                       ":" / ";" /
                       "@" / "\" /
                       "," / "." /
                       DQUOTE
```

As you can see, it does not fit the definition for multiple reasons.

1. it doesn't have an `@` or a `id-right` token
2. the `id-left` token contains `(` and `)` which are `specials` which are not allowed to appear in `atext`.

**Comment by Xgleich8** [comment]
Thanks for your info.
Of course you are right that the `Content-ID` according to RFC is invalid. The problem is that not all clients conform to the specification.
You are doing a great job.

**Comment by jstedfast** [comment]
If you check the main GitHub page, there is now a link (where all the pretty icons are) for a myget nuget feed which receives all of the latest CI builds. If you use the latest MimeKit packages from there, you'll be able to use this fix immediately.

**Comment by peteroupc** [comment]
Just an observation.

Content-ID is perhaps the most misunderstood header field.  Even though RFC 2045 requires a Content-ID to be "world-unique" just like Message-ID, many implementations don't generate Content-ID values the way they generate Message-IDs; for example, some of them may put filenames such as "test_image.png" between the angle brackets.  For more observations, see [this message](https://mailarchive.ietf.org/arch/msg/ietf-822/mm17j2_Sya8B5EWjJKsYgys1BiE). As a result, almost half of Content-ID header fields I've seen in practice don't follow the syntax of that field.

**Comment by jstedfast** [comment]
@peteroupc Wow, thanks for the link to your email!

It seems to contain some good valuable information. I appreciate you taking the time to both document those behaviors as well as linking me to them.

I'm saddened that none of the IETF authors seem to have responded to your emails.

How does your library deal with these headers? Is that something you've solved?
