### ISSUE TITLE
Better support for text/rfc822-headers content-type

### ISSUE THREAD

**Issue by MattLavalleeMA** [jstedfast/MimeKit#474]
**Is your feature request related to a problem? Please describe.**
I'm using MimeKit to parse a large volume of bounce messages and have run into some that return only a BodyPart with Content-Type: text/rfc822-headers (as described in rfc1892).  Compared to a MimeEntity that matches MimeMessage, I have to manually take the TextPart.Text as a MemoryStream into MimeMessage.ParseAsync in order to instantiate it into an empty-body message that can then be traversed like a typical (full, original) bounce (with all headers, From, To, etc.).

**Describe the solution you'd like**
I'd expect the text/rfc822-header content-type to act in the same manner as a message/rfc822 content-type, which casts to a MimeMessage from the MimeEntity.

**Describe alternatives you've considered**
I've got a workaround in place when hitting that Content-Type to dump it to a stream and parse it into a new MimeMessage, but clearly much less fluid than everything else in MimeKit.

**Additional context**
Fantastic work. Great code.

**Comment by jstedfast** [comment]
FWIW, I wouldn't recommend converting the TextPart.Text property into a MemoryStream. I would also recommend using HeaderList.Load().

Here's a snippet of code to illustrate how I would recommend handling this:

```csharp
static HeaderList GetContentAsHeaders (TextPart text)
{
    using (var stream = text.Content.Open ())
        return HeaderList.Load (stream);
}
```

You could probably just turn that into an extension method.

Or, if you wanted to get fancy:

```csharp
public class TextRfc822Headers : MimePart
{
    HeaderList rfc822Headers;

    // This is the .ctor that the parser uses
    public TextRfc822Headers (MimeEntityConstructorArgs args) : base (args)
    {
    }

    public HeaderList Rfc822Headers {
        get {
            if (rfc822Headers == null) {
                using (var stream = Content.Open ())
                    rfc822Headers = HeaderList.Load (stream);
            }

            return rfc822Headers;
        }
    }
}
```

Then, to have the parser use this class for the text/rfc822-headers mime-type, just do:

```csharp
var options = ParserOptions.Default.Clone ();
options.RegisterMimeType ("text/rfc822-headers", typeof (TextRfc822Headers));

var message = MimeMessage.Load (options, stream);
```

**Comment by MattLavalleeMA** [comment]
Thanks, Jeffrey -- slogged around a bit to get this to where I wanted, only to realize your solution just overshot my goal a bit.

In the end:
```
    public class TextRfc822Headers : **MessagePart**
    {
        public TextRfc822Headers(MimeEntityConstructorArgs args) : base(args)
        {
        }
    }
```

... and then, back where I'm using it:
```
 ParserOptions options = ParserOptions.Default.Clone();
 options.RegisterMimeType("text/rfc822-headers", typeof(TextRfc822Headers));
```

That yielded what I needed: an identically-formed MimeMessage (the instance type I'm passing around) with the HeaderList populated and standard headers set in properties (From, To, Date, etc.).

All this being said, I _do_ think it should be the default behavior, as that's the intent of this specific content-type.

Donation coming your way.

**Comment by MattLavalleeMA** [comment]
I've reread [RFC 1892](https://tools.ietf.org/html/rfc1892#section-2) a few times to ensure whether the request/suggestion is accurate and I can see it going either way.  While they do assert that the MIME Type is Text, they also assert:

> The Text/RFC822-headers body part should contain all the RFC822 header lines from the message which caused the report. The RFC822 headers include all lines prior to the blank line in the message.

... which, 20 years later and cast into an OO model, _feels like_ it should be mutable to a message with an empty body.

I considered PR'ing the change for ParserOptions, but it seems like a biggish deal to return a MessagePart for something clearly labeled as Text, or at least one that's your call as far as casting opinion on the RFC vs. implementation.

**Comment by jstedfast** [comment]
Actually, yea, using a MessagePart (if you'd prefer to use the content like a MimeMessage with the conveniences of the pre-parsed message header properties) is probably the way to go.

I didn't consider that last night when I was responding.

I'll modify ParserOptions to register text/rfc822-headers as a MessagePart subclass (to make it easier for developers to create a text/rfc822-headers entity). That would make this an extremely easy feature to add support for which makes me happy. How does that sound to you?
