### ISSUE TITLE
NetStandard2.0 optimizations

### ISSUE THREAD

**Issue by sebastienros** [jstedfast/MimeKit#475]
MimeKit target netstandard 2.0 but the csproj should not reference the assemblies it does right now with this target. Only Bouncy should still be necessary but it looks like this other ones are not. This would make the dependency graph smaller when using it from an app targeting netcoreapp2.0.

I can work on a PR if you agree.

**Comment by jstedfast** [comment]
Yea, I've known about this for a bit but haven't gotten around to fixing it. Thanks!

**Comment by jstedfast** [comment]
Do you have an idea of when you might have something ready? Just trying to plan out when to make the next release.

**Comment by sebastienros** [comment]
Are the pull requests going through CI for each target? If so they I don't need to run the tests myself

**Comment by jstedfast** [comment]
No, they only test 4.5

**Comment by sebastienros** [comment]
At least it will build the project, so it would just fail if there were issues. Will try today.
