### ISSUE TITLE
MimeKit fails to parse when stream encoding is not Encoding.Default

### ISSUE THREAD

**Issue by tgiddings** [jstedfast/MimeKit#476]
In the NUnit test fixture below, three tests take a MimeEntity, convert it to a string, write the string to a stream, and parse the stream back into a MimeEntity. The first test, which passes on my machine, uses `Encoding.Default` on both the stream writer and the `ParserOptions`. The second test, which throws when parsing on my machine, uses `Encoding.UTF8`.  Confusingly, the third test, which writes to the steam using Encoding.Default and parses with encoding Encoding.UTF8, passes on my machine. The description and name of the `CharsetEncoding` property seems to me that it indicates the encoding of the stream being parsed. Is this correct? If not, how do I parse a stream with encoding other than `Encoding.Default`?

Mimekit version: 2.1.3 (currently latest stable on NuGet)

```
[TestFixture]
  public class MimeKitTests
  {
    MimeEntity body;

    [SetUp]
    public void MakeBody()
    {
      var bodyBuilder = new BodyBuilder
      {
        TextBody = "Test",
        HtmlBody = "<b>Test</b>"
      };
      body = bodyBuilder.ToMessageBody();
    }

    [Test]
    public void TestDefault()
    {
      var bodyString = body.ToString();

      using (var stream = new MemoryStream())
      using (var writer = new StreamWriter(stream, Encoding.Default))
      {
        writer.Write(bodyString);
        writer.Flush();
        stream.Position = 0;
        var parsedBody = MimeEntity.Load(
          new ParserOptions()
          {
            CharsetEncoding = Encoding.Default,
          },
          stream);
      }
      Assert.Pass();
    }

    [Test]
    public void TestUtf8()
    {
      var bodyBuilder = new BodyBuilder
      {
        TextBody = "Test",
        HtmlBody = "<b>Test</b>"
      };
      var body = bodyBuilder.ToMessageBody();

      var bodyString = body.ToString();

      using (var stream = new MemoryStream())
      using (var writer = new StreamWriter(stream, Encoding.UTF8))
      {
        writer.Write(bodyString);
        writer.Flush();
        stream.Position = 0;
        var parsedBody = MimeEntity.Load(
          new ParserOptions()
          {
            CharsetEncoding = Encoding.UTF8,
          },
          stream);
      }
      Assert.Pass();
    }

    [Test]
    public void TestUtf8_2()
    {
      var bodyBuilder = new BodyBuilder
      {
        TextBody = "Test",
        HtmlBody = "<b>Test</b>"
      };
      var body = bodyBuilder.ToMessageBody();

      var bodyString = body.ToString();

      using (var stream = new MemoryStream())
      using (var writer = new StreamWriter(stream, Encoding.Default))
      {
        writer.Write(bodyString);
        writer.Flush();
        stream.Position = 0;
        var parsedBody = MimeEntity.Load(
          new ParserOptions()
          {
            CharsetEncoding = Encoding.UTF8,
          },
          stream);
      }
      Assert.Pass();
    }
  }
}
```

**Comment by jstedfast** [comment]
This isn't a bug. Do not use MimeEntity or MimeMessage.ToString(). It is for debugging purposes ONLY.

**Comment by jstedfast** [comment]
I should have mention that the correct way to serialize a message or MIME entity is to use the `WriteTo()` method.

**Comment by tgiddings** [comment]
Thank you -- I didn't see WriteTo when looking through the API of MimeEntity

**Comment by jstedfast** [comment]
It's a mistake a lot of people make, so you aren't alone. I should probably get rid of ToString() to avoid this mess but that would break a bunch of existing users. I'm between a rock and a hard place on this one. :-\

The problem is that MIME cannot really be serialized to a string correctly because each MIME part can use a different charset and the headers might also contain non-ASCII characters in whatever charset the mail client uses by default for the user's locale. Mail clients are *supposed* to encode those strings (or use UTF-8 if they are following only the latest specs), but many do not.

**Comment by jstedfast** [comment]
FWIW, ParserOptions.CharsetEncoding is the encoding that the parser should assume for unencoded 8-bit text in the headers, it doesn't affect the message body at all.

**Comment by tgiddings** [comment]
I recommend including "This is for debug purposes only. Use WriteTo to serialize the entity" in the summary section of the ToString docs. This would have been enough for me to find the correct function.

Including a serialization example with the other examples in the readme would likely also be effective in preventing this mistake, though the example should note that serializing a MimeEntity to a string isn't possible so that it's clear WriteTo and streams are the only way.

**Comment by jstedfast** [comment]
Already do: http://www.mimekit.net/docs/html/M_MimeKit_MimeMessage_ToString.htm

**Comment by jstedfast** [comment]
Although it looks like MimeEntity.ToString() doesn't have that note. Adding it now.
