### ISSUE TITLE
Subject Header Encoding

### ISSUE THREAD

**Issue by rishabhjain9196** [jstedfast/MimeKit#478]
MimeMessage.ToString() returns an encoded value of Subject Header. I am already encoding the subject with _utf-8_, settting the subjectEncoding to be _utf-8_ too. When I do a .ToString() on the object, it gives the subject encoding in ASCII (starting with _=?us-ascii?q?_)

This only happens when the length of the subject is greator than a fixed length, looks around 31. 

**Expected behavior**
Subject should not be re-encoded.

**Comment by jstedfast** [comment]
First, don't use `MimeMessage.ToString()` - that method is for debugging purposes only.

You need to use `MimeMessage.WriteTo (Stream, ...)`

Secondly, MimeKit absolutely needs to encode Subject headers because it needs to fold them. They will be *decoded* by the recipient client, so you have no need to worry.

**Comment by rishabhjain9196** [comment]
@jstedfast Outlook wasn't. I want the subject to be encoded utf-8. And for long length subjects, my utf8 encoded subjects are wrapped with ascii encoding. Outlook just removes the ascii one, and the utf8 encoded string becomes the subject.

**Comment by jstedfast** [comment]
Sounds like Outlook is buggy... 

Anyway, the good news for you is that you can do this:

```csharp
var options = FormatOptions.Default.Clone ();
options.AllowMixedHeaderCharsets = false;

message.WriteTo (options, stream, ...);
```

I forgot I had added this feature or I would have mentioned it earlier.

**Comment by rishabhjain9196** [comment]
@jstedfast 
Okay, so I tried the above code snippet. Didn't work. It would be great if you could nudge me in the right direction. 

Essentially, First I have a MailMessage object, 
```
System.Net.Mail.MailMessage}
    Body: ""
    BodyEncoding: null
    BodyTransferEncoding: Unknown
    From: {"=?utf-8?B?QW5pbWVzdW5kdSBpbiBUZWFtcw==?=" <something@something.com>}
    Headers: {System.Net.Mime.HeaderCollection}
    HeadersEncoding: null
    IsBodyHtml: true
    Priority: Normal
    ReplyTo: null
    ReplyToList: Count = 0
    Sender: null
    Subject: "=?utf-8?B?TmV3U3ViamVjdERhdGVkMTMtMDUtMjAxOVJpc2hhYmhSaXNoYWJoUmlzaGFiaFJpc2hhYmhSaXNoYWJoUmlzaGFiaFJpc2hhYmhSaXFiaFJpc2hhYmhSaXNoYWJoUmlzaGFiaFJpc2hhYmhSaXNoYWJoUmlzaGFiaFJpc2hhYmhSaXNoYWJoUmlzaGFiaFJpc2hhYmhSaXNoYWJoUmlzaGFiaFJpc2hhYmhSaXNoYWJoUmlzaGFiaFJpc2hhYmhSaXNoYWJoUmlzaGFiaFJpc2hhYmggcG9zdGVkIGEgbWVzc2FnZQ==?="
    SubjectEncoding: {System.Text.UTF8Encoding}
    To: Count = 1
    attachments: Count = 0
    body: ""
    bodyEncoding: null
    bodyTransferEncoding: Unknown
    bodyView: null
    deliveryStatusNotification: None
    disposed: false
    isBodyHtml: true
    message: {System.Net.Mail.Message}
    views: Count = 1
```

I convert this to MimeMessage using the `MimeMessage.CreateFromMailMessage(MailMessage)`
![image](https://user-images.githubusercontent.com/12732927/57617535-a4b33000-759e-11e9-9f54-9f59b9f982d1.png)

As in above image message.subject seems to have some ascii encoding. Although, the message.Subject property shows the correct utf-8 encoded string. 

I require a string version of the above object as the simple smtp client (Microsoft.Exchange.Common.Smtp) requires a string data to send out emails. 

```
message.Body = builder.ToMessageBody();
message.Prepare(EncodingConstraint.EightBit);
var options = FormatOptions.Default.Clone();
options.AllowMixedHeaderCharsets = false;
using (var stream = new MemoryStream())
{
     message.WriteTo(options, stream);
     string text = Encoding.Default.GetString((stream.ToArray()))
     return text;
}
```
Can you point out what is the issue here?

**Comment by jstedfast** [comment]
Try this instead:

```csharp
var options = FormatOptions.Default.Clone();
options.AllowMixedHeaderCharsets = false;

int index = message.Headers.IndexOf (HeaderId.Subject);
var header = message.Headers[index];
header.SetValue (options, "utf-8", message.Subject);
```

**Comment by rishabhjain9196** [comment]
@jstedfast  Really appreciate your effort. But the issue for me is still persisting.

The string version of the subject -
![image](https://user-images.githubusercontent.com/12732927/57684523-9410c180-7653-11e9-8be8-473186019b04.png)

Message.Header has correct value, 
![image](https://user-images.githubusercontent.com/12732927/57684651-d4703f80-7653-11e9-98c8-da83967cf457.png)

**Comment by jstedfast** [comment]
Oh, the problem is that you are setting the encoded subject on the header instead of the decoded subject string.

The Header is encoding an already-encoded subject string.

You need to not do that :-)

**Comment by rishabhjain9196** [comment]
@jstedfast 
Not using encoded subject, I get ascii encoding, 
![image](https://user-images.githubusercontent.com/12732927/57869821-7abe6f80-7823-11e9-8449-1f94b09e32ed.png)

I want it to be utf8 specifically as some locales would not be supported.

**Comment by jstedfast** [comment]
Sigh.

The following line in your code is broken:

```csharp
header.SetValue (options, "utf-8", message.Subject);
```

`message.Subject` contains rfc2047 encoded-word tokens. It needs to not contain any encoded-word tokens.

**Comment by rishabhjain9196** [comment]
![image](https://user-images.githubusercontent.com/12732927/57900202-96eefa80-787d-11e9-882c-39729757bee6.png)

I tried only non-encoded alphabets, ascii is still appended.

**Comment by jstedfast** [comment]
That's because all of your input is ascii. Any mail client that supports utf-8 will work properly with us-ascii.
