### ISSUE TITLE
Warning CS3001: Argument type 'MailboxAddress' is not CLS-compliant

### ISSUE THREAD

**Issue by Externaluse** [jstedfast/MimeKit#480]
When building a .Net 4.7.2 project that uses MimeKit 2.1.4 I receive a number of warnings:
Configuration\MailManager.cs(22,52): Warning CS3001: Argument type 'MailboxAddress' is not CLS-compliant
0>Configuration\MailManager.cs(34,108): Warning CS3001: Argument type 'MimeEntity[]' is not CLS-compliant
0>Configuration\MailManager.cs(62,57): Warning CS3001: Argument type 'InternetAddressList' is not CLS-compliant

A simple method might look like this:
`public static void TestSend(MailboxAddress to)
{
       logger.Debug(to.Address);
}`

Am I doing something wrong?

**Comment by jstedfast** [comment]
Remove `[assembly:CLSCompliant(true)]` from your AssemblyInfo.cs
