### ISSUE TITLE
Use of SpinLock

### ISSUE THREAD

**Issue by maiph** [jstedfast/MimeKit#483]
I was looking over your `MemoryBlockStream` implementation and was wondering why you use a https://github.com/jstedfast/MimeKit/blob/89a7b5a1ff7e215d0dbb88af9ebd7d9c8e0482cc/MimeKit/Utils/BufferPool.cs#L52 instead of any other object for synchronizatio. Ex `Mutex`.

**Comment by jstedfast** [comment]
Mostly because they are inexpensive compared to Mutexes and there's no expectation that it will block for any significant amount of time. Grabbing the next buffer from the pool is a very insignificant amount of work in general so a spin lock is suitable.
