### ISSUE TITLE
Different behavior when creating MailboxAddress

### ISSUE THREAD

**Issue by andreypetukhov** [jstedfast/MimeKit#486]
**Describe the bug**
I see different behavior when creating MailboxAddress for some input string format

**To Reproduce**
1. Run in linqpad next snippet 
var mailBox = new MailboxAddress(Encoding.UTF8, "", "localpart@email.com\t")
2. Run in linqpad next snippet  
MailboxAddress.TryParse("localpart@email.com\t",out _).Dump();
 

**Expected behavior**
mailbox will be created in both scenarios

Actual behavior: step 1 throws mimekit parser exception

**Comment by jstedfast** [comment]
Yea, because the .ctor is not meant to have to parse any strings. You are supposed to pass it pre-parsed strings.
