### ISSUE TITLE
Check message type from bytes array

### ISSUE THREAD

**Issue by SamShekhovtsov** [jstedfast/MimeKit#487]
**Is your feature request related to a problem? Please describe.**
When parsing a Digitally Signed email in format of smime.p7m attachment I experienced different types of content, that require different code for parsing / validating the message. The attachment comes as array of bytes. The idea is to determine the content type of the message prior to explicit base64 decoding or text conversion. 

The actual problem is that for the same type of digitally signed email attachment, I have to use different code, in some cases it is handled as ApplicationPkcs7Mime but in other cases it must be handled as MimeEntity, considering the same attachment file name and same content - type.

When I convert the content bytes from the smime.p7m to text, than the only recognizable difference is that in some cases text starts from the words:  "Content-Type: multipart/signed;" while in other cases it starts from unrecognizable hash of characters and after that - "Content-Type: multipart/mixed;"

What is weird for me now is that when I pass entity, which doesn't have Content-Type multipart/signed - it requires parsing message through the ApplicationPkcs7Mime object, but for the messages which includes Content-Type multipart/signed - can simply use MimeEntity.Load( stream from content bytes)

**Describe the solution you'd like**
Possible solution. Loading content bytes to some kind of validator entity and process content as multipart/signed and return instance of MimeEntity or create ApplicationPkcs7Mime entity to be able to validate based on the actual attachment content.

**Describe alternatives you've considered**
Alternatively, it would be nice to identify type of the message before creating any kind of Mime or S/MIME instance ( since it can't be based only on ContentType header value ).

**Additional context**
Probably I'm missing something in multipart and Digitally Signed emails processing, please advise. The described problem / feature doesn't affect and encryption / decryption mechanisms, only digital signature and multipart content attached as smime.p7m file.

**Comment by jstedfast** [comment]
I don't understand what you are trying to do, it makes no sense to me.

You shouldn't be parsing smime.p7m attachment content (this is what it sounds like you are doing to me), you should be parsing the MIME message that *contains* the smime.p7m attachment.
