### ISSUE TITLE
A valid certificate could not be found (using only a public key)

### ISSUE THREAD

**Issue by Kennedine** [jstedfast/MimeKit#491]
I need to send encrypted emails and I have the receivers public key as a .cer certificate file.

I create a SecureMimeContext from the provided .cer file.

```csharp
private SecureMimeContext CreateSecureMimeContext(string filepath)
{
    System.Security.Cryptography.X509Certificates.X509Certificate2 pub1 = new 
        System.Security.Cryptography.X509Certificates.X509Certificate2(filepath);
     //pub1.Import(filepath);

    Org.BouncyCastle.X509.X509Certificate certificate = 
        Org.BouncyCastle.Security.DotNetUtilities.FromX509Certificate(pub1);

    var secureMimeContext = new TemporarySecureMimeContext();
    secureMimeContext.Import(certificate);

    return secureMimeContext;
}

var message = new MimeMessage();
message.From.Add(new MailboxAddress("KFK@niras.dk"));
message.To.Add(new MailboxAddress("KFK@commentor.dk"));

var builder = new BodyBuilder();
builder.HtmlBody = html;
builder.Attachments.Add("singleencrypted.pdf", pdfbytes);
message.Body = builder.ToMessageBody();
message.Encrypt(secureContext); <--- Kaboom
```

When I try to encrypt the message it throws an exception with the message;
A valid certificate could not be found.

If I change the sender to be the address of the public key then it runs.
It is very possible I have done something wrong, it seems to thinking certificate is for veryfying me as a sender which is not the case. I just need to ensure that the receiver is the only mailbox that can open the message as it contains sensitive information.

**Comment by jstedfast** [comment]
MimeMessage.Encrypt() assumes you want to "encrypt to self", so it encrypts to both the sender and the recipients.

If you don't care to do that, you can do this instead:

```csharp
message.Body = ApplicationPkcs7Mime.Encrypt (secureContext, message.To.Mailboxes, message.Body);
```

**Comment by Kennedine** [comment]
Thank you for the quick reply / resolution. It is now working as expected, so again thank you very much :)
