### ISSUE TITLE
Problem using FormatOptions verifying DKIM signature

### ISSUE THREAD

**Issue by DuncanMacLeod-WotU** [jstedfast/MimeKit#496]
I have an MimeMessage with CRLF (DOS) line endings and want to verify DKIM. The message passed a Unix Host where it get signed, so it was signed with LF only.
Now the Message is on disk with CRLF (not with LF as it was signed), so I thought I can use the FormatOptions to handle this. But when I use the FormatOptions I also receive INVALID on the CRLF Message and VALID on the same Message with LF only. So it seem that it just ignores the FormatOptions. That's not a big problem for me, I will rewrite the Message with LF before Verifying DKIM, but it would be nice if it were not necessary.

                FormatOptions fmtopt = new FormatOptions();
                fmtopt.NewLineFormat = NewLineFormat.Dos;

                if (verifier.Verify(fmtopt, message, dkim))
                {
                    // the DKIM-Signature header is valid!
                    Console.ForegroundColor = ConsoleColor.Green;
                    Console.WriteLine("VALID");
                    Console.ResetColor();
                }
                else
                {
                    // the DKIM-Signature is invalid!
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine("INVALID");
                    Console.ResetColor();
                }

**Comment by jstedfast** [comment]
I don't understand what you're trying to say. Your statements seem to contradict themselves.

Secondly, the spec states that the message MUST be signed using CRLF line endings, regardless of what the system uses for line endings.

http://dkim.org/specs/rfc4871-dkimbase.html#canonicalization
