### ISSUE TITLE
MimeMessage.Prepare does not calculate maxLineLength correctly

### ISSUE THREAD

**Issue by nitinag** [jstedfast/MimeKit#497]
Looks like MimeMessage.Prepare is not counting CRLF, but only LF as a result of the following:
https://github.com/jstedfast/MimeKit/blob/master/MimeKit/IO/Filters/BestEncodingFilter.cs#L146

This results in the count being a character off in addition to not treating lines as CRLF.

Test:
```
var mimeMessage = MimeMessage.Load(new MemoryStream(Encoding.UTF8.GetBytes(@"From: test@example.com

abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
abc")));
mimeMessage.Prepare(MimeKit.EncodingConstraint.EightBit, 78);
```

The above message with max line length of 78 characters should result in ContentTransferEncoding == Default, but it is giving ContentTransferEncoding == QuotedPrintable.

**Comment by jstedfast** [comment]
Thanks.
