### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by dolphinsd** [jstedfast/MimeKit#498]
Any plans to support .NET Core with native build? 

We get errors like this when including into net core project and its not portable.

was resolved using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This project may not be fully compatible with your project.

**Comment by jstedfast** [comment]
It already has .NET Core support. I don't know why you are getting that error.

MimeKit is built for netstandard1.3, netstandard1.6 and netstandard2.0
