### ISSUE TITLE
DefaultSecureMimeContext.GetCmsSigner(): include certificate chain

### ISSUE THREAD

**Issue by swoga** [jstedfast/MimeKit#500]
**Is your feature request related to a problem? Please describe.**
Some mail clients (eg. Samsung Mail, SOGo Webmail are ones which I know of) can't verify SMIME signatures, if the intermediate certificates are not included in the signature.

**Describe the solution you'd like**
`DefaultSecureMimeContext.GetCmsSigner()` should return a `CmsSigner` which includes the certificate chain.
We currently solve this with the following class, but I think this could be implemented directly in MimeKit.

```
public class CustomSecureMimeContext : DefaultSecureMimeContext
{
    public CustomSecureMimeContext(IX509CertificateDatabase database) : base(database)
    {
    }

    protected override CmsSigner GetCmsSigner(MailboxAddress mailbox, DigestAlgorithm digestAlgo)
    {
        var signer = base.GetCmsSigner(mailbox, digestAlgo);

        X509CertStoreSelector selector = new X509CertStoreSelector();
        selector.Certificate = signer.Certificate;

        PkixBuilderParameters parameters = new PkixBuilderParameters(GetTrustedAnchors(), Selector);
        parameters.AddStore(GetIntermediateCertificates());
        parameters.IsRevocationEnabled = false;

        var result = new PkixCertPathBuilder().Build(parameters);
        var chain = result.CertPath.Certificates.Cast<Org.BouncyCastle.X509.X509Certificate>;

        return new CmsSigner(chain, signer.PrivateKey);
    }
}
```

Are there any disadvantages, apart from the larger size, if the certificate chain is always sent along with the signature?

**Comment by jstedfast** [comment]
No other disadvantages and, I think, it's recommended to send the intermediate certificates in the chain anyway.

Thanks for the bug report!
