### ISSUE TITLE
could be use MemeKit to Parse a nomal file stream(not eml or mbox file ) to ContentType and get file extension

### ISSUE THREAD

**Issue by sgf** [jstedfast/MimeKit#501]
I read the document, but mostly for the mail message

**Comment by sgf** [comment]
i see MimeTypes.
seems this project use GetMimeType to get MimeType by file extension.

**Comment by jstedfast** [comment]
Correct. This library doesn't do "MIME sniffing" by trying to auto-detect the MIME-type based on the format of the content of a stream. MimeKit is intended only for parsing MIME messages.
