### ISSUE TITLE
How To change attachment FileName

### ISSUE THREAD

**Issue by heyifei** [jstedfast/MimeKit#504]
Hello,guys!

I've tried this way:

FileStream fs = new FileStream(_fileName, FileMode.Open, FileAccess.Read);//.eml file.
 var msg = MimeMessage.Load(fs, true);
IEnumerable<MimeEntity> attachments = msg.Attachments;
                if(attachments.Count() >0)
                {
                    foreach(MimeEntity attachment in attachments)
                    {
                        if (attachment.ContentDisposition.FileName.Contains((char)160))
                        {
                            var fileName = attachment.ContentDisposition.FileName.Replace((char)160, '_');
                            attachment.ContentDisposition.FileName = fileName;
                        }
                    }
                }

It didn't work.
Can anyone help?
Thanks in advance.

**Comment by jstedfast** [comment]
You did it correctly, but once you do that, you need to do `msg.WriteTo (...)` to save the changed information back out to disk.

**Comment by heyifei** [comment]
Thank you!
