### ISSUE TITLE
Blank body for email coming from Apple with first content is file

### ISSUE THREAD

**Issue by fakhrulhilal** [jstedfast/MimeKit#505]
**Describe the bug**
When sharing a file through Apple products (iOS, iPadOS, MacOS) and append text after the file, it makes the `HtmlBody`/`TextBody` empty

**Platform (please complete the following information):**
 - Windows 10
 - .NET Standard 2.0
 - .NET Framework 4.7.2
 - MimeKit 2.1.2:

**To Reproduce**
You should have [apple mail](https://apps.apple.com/us/app/mail/id1108187098) installed and 1 account preconfigured for sending the email
1. Open your file (doc, pdf, excel, etc). I use [file app](https://apps.apple.com/us/app/files/id1232058109) to share the file
2. On share dialog, choose [mail](https://apps.apple.com/us/app/mail/id1108187098), the file should be attached in the mail body by default
3. Add text after the file. Format the text (bold/italic, etc) to make it HTML email.
4. Fill all required fields and send the email

**Expected behavior**
[`HtmlBody`](http://www.mimekit.net/docs/html/P_MimeKit_MimeMessage_HtmlBody.htm) or [`TextBody`](http://www.mimekit.net/docs/html/P_MimeKit_MimeMessage_TextBody.htm) shouldn't be empty

**Comment by fakhrulhilal** [comment]
I attached generated EML files (just rename it to .eml), anonymized as necessary. For what I found, Apple always add empty content depends on the email type. If it's plain email (text/plain), they will add empty mime part with conten type text/plain. If it's HTML email, they will add HTML content (text/html) with tags but without inner text for every tags. 

These are the comparison for the mime message structure, compared to the common message:

| Scenario          |Apple                                      |Common                             |
|----------------|-------------------------------|-----------------------------|
|Attachment and plain text|<pre>\\-- multipart/mixed<br>&nbsp;&nbsp;&nbsp;&nbsp;\|-- text/plain (empty)<br>&nbsp;&nbsp;&nbsp;&nbsp;\|-- application/pdf (attachment)<br>&nbsp;&nbsp;&nbsp;&nbsp;\|-- text/plain (actual body)</pre>            |<pre>\\-- multipart/mixed<br>&nbsp;&nbsp;&nbsp;&nbsp;\|-- text/plain (actual body)<br>&nbsp;&nbsp;&nbsp;&nbsp;\|-- application/pdf (attachment)</pre>|
|Attachment and HTML email|<pre>\\--&nbsp;multipart/alternative<br>&nbsp;&nbsp;&nbsp;&nbsp;\|--&nbsp;text/plain&nbsp;(plain&nbsp;body&nbsp;version&nbsp;of&nbsp;HTML)<br>&nbsp;&nbsp;&nbsp;&nbsp;\\--&nbsp;multipart/mixed<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\|--&nbsp;text/html&nbsp;(HTML&nbsp;but&nbsp;no&nbsp;actual&nbsp;content)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\|--&nbsp;application/pdf&nbsp;(attachment)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\|--&nbsp;text/html&nbsp;(actual&nbsp;HTML&nbsp;body)</pre>            |<pre>\\--&nbsp;multipart/mixed<br>&nbsp;&nbsp;&nbsp;&nbsp;\\--&nbsp;multipart/alternative<br>&nbsp;&nbsp;&nbsp;&nbsp;\|--&nbsp;\|--&nbsp;text/plain&nbsp;(plain&nbsp;body&nbsp;version&nbsp;of&nbsp;HTML)<br>&nbsp;&nbsp;&nbsp;&nbsp;\|--&nbsp;\|--&nbsp;text/html&nbsp;(actual&nbsp;HTML&nbsp;body)<br>&nbsp;&nbsp;&nbsp;&nbsp;\|--&nbsp;application/pdf&nbsp;(attachment)</pre>|

[:envelope: Apple email HTML.txt](https://github.com/jstedfast/MimeKit/files/3589811/Apple.email.HTML.txt)
[:envelope: Apple email plain.txt](https://github.com/jstedfast/MimeKit/files/3589813/Apple.email.plain.txt)

**Comment by jstedfast** [comment]
The way you need to render a message is to use something like the HtmlPreviewVisitor in the MessageReader sample app (see https://github.com/jstedfast/MimeKit/tree/master/samples/MessageReader)

HtmlBody and TextBody properties are just quick & dirty and are only meant for simple messages which that follow the standard convention. I explain more about how conventional messages are constructed in the [FAQ](https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#MessageBody).

**Comment by fakhrulhilal** [comment]
Do you have some reference for standard convention?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fakhrulhilal** [comment]
Thank you for the advise
