### ISSUE TITLE
GetCmsSigner() opens multiple data readers

### ISSUE THREAD

**Issue by swoga** [jstedfast/MimeKit#508]
Hello,

the fix for issue #500 causes a problem with certain certificates databases.

`GetCmsSigner()` attempts to open a second data reader inside `BuildCertificateChain()`, while one is already active by `dbase.Find()`, this is not supported by many databases.

The easiest fix would be to instantiate the `CmsSigner` outside the loop.

A workaround for MsSQL certificate databases is to enable MultipleActiveResultSets, but no equvalient is available for MySQL.

**Comment by jstedfast** [comment]
Thanks for pointing this out! I've just committed a fix!
