### ISSUE TITLE
FileLoadException: . . . Strong name signature could not be verified.

### ISSUE THREAD

**Issue by CNBoland** [jstedfast/MimeKit#516]
I'm getting the following exception after upgrading from v2.3.2 to v2.4.0:

`[FileLoadException: Could not load file or assembly 'MimeKit' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]`

Comparing the two version assemblies in ILSpy, the only difference I see is version number, which doesn't explain the exception.

Any ideas?

 - OS: Windows
 - .NET Runtime: .NET CLR 4.0
 - .NET Framework: .NET Framework 4.7.2
 - MimeKit Version: 2.4.0

**Comment by jstedfast** [comment]
Apparently I had `<PublicSign Condition=" '$(OS)' != 'Windows_NT' ">true</PublicSign>` in the .csproj for the multi-target csproj (which is what is used for net46, net47, net48, netstandard1.3, netstandard1.6, and netstandard2.0).

If you use the net45 version, it will be signed.

**Comment by jstedfast** [comment]
In case it wasn't obvious, I didn't use my Windows 10 machine to build these packages.

**Comment by swoga** [comment]
Is it possible to release a fixed version?
We use net46 and need a fix which shipped in 2.4.0, but our automated build currently fails.

**Comment by jstedfast** [comment]
Yes, I'll try to make a new release tonight.

**Comment by swoga** [comment]
Same problem could occur in MailKit, when building on non-Windows machine?
https://github.com/jstedfast/MailKit/blob/3c9be505242961dcaf6aafe9cb1cea2df6b02c4c/MailKit/MailKit.NetStandard.csproj#L29

**Comment by jstedfast** [comment]
Yep, I know. I'm planning to make a release of MailKit as well.
