### ISSUE TITLE
Extract .eml file

### ISSUE THREAD

**Issue by paolox72** [jstedfast/MimeKit#517]
Hi,
i use mimekit to extract attachement from message. Sometimes, when Content-Disposition is  inline, I can't extract attachments .eml, it does not see Content-Type: message/rfc822, postacet.eml
[25476.zip](https://github.com/jstedfast/MimeKit/files/3813457/25476.zip)

; 
The results are 4 bodyparts, daticert.xml, text/plain,html/plain and smime.p7s.

I see inside eml attach, i don't read its. I need to save it,
thanks a lot,
Paolo

 I use this code:

 For Each msgpart As MimeKit.MimePart In message3.BodyParts
        
        Response.Write("<br>Z1=" & msgpart.ContentType.ToString)
       
        
        
        Try
            Response.Write("<br>Z11=" & msgpart.ContentDisposition.ToString)
        Catch ex As Exception

        End Try
        Try
            Response.Write("<br>Z2=" & msgpart.ContentType.Name.ToString())
        Catch ex As Exception

        End Try
       
        Response.Write("<br>------------------")
        
    Next

**Comment by jstedfast** [comment]
A `message/rfc822` part is represented in MimeKit as a `MessagePart` which is NOT a subclass of `MimePart`, hence why this doesn't work:

```vb
For Each msgpart As MimeKit.MimePart In message3.BodyParts
```

What you need to do is this:

```csharp
foreach (var bodyPart in message.BodyParts) {
    var fileName = bodyPart.ContentDisposition?.FileName ?? bodyPart.ContentType.Name;
    
    using (var stream = File.Create (fileName)) {
        if (attachment is MessagePart) {
            var rfc822 = (MessagePart) attachment;
            
            rfc822.Message.WriteTo (stream);
        } else {
            var part = (MimePart) attachment;
            
            part.Content.DecodeTo (stream);
        }
    }
}
```

**Comment by paolox72** [comment]
Thank you for the quick reply, now it work fine! thanks,

Paolo
