### ISSUE TITLE
Fail to parse ARC-Authentication-Results header when header.d contains a '/'

### ISSUE THREAD

**Issue by The-Nutty** [jstedfast/MimeKit#518]
**Describe the bug**
I am trying to parse the ARC-Authentication-Results header on its own, however it is periodically failing on ARC-Authentication-Results headers and i believe the cause is a '/' in the header.d see example. 

**Platform (please complete the following information):**
 - OS: Tested on windows and amazon linux
 - .NET Framework: .NET core 2.1
 - MimeKit Version: 2.4.0

**To Reproduce**
1. Run a console app with the following main method
```
        static void Main(string[] args)
        {
            if (AuthenticationResults.TryParse(
                Encoding.UTF8.GetBytes(
                    "i=2; test.com; dkim=pass header.d=test.com header.s=selector1 header.b=Iww3/TIUS; dmarc=pass (policy=reject) header.from=test.com; spf=pass (test.com: domain of no-reply@test.com designates 1.1.1.1 as permitted sender) smtp.mailfrom=no-reply@test.com"),
                out var parsedAuthenticationResult))
            {
                Console.WriteLine("Parsed auth results");

            }
            else
            {
                Console.WriteLine("Failed to parse auth results");
            }

            Console.ReadLine();
        }
```
2. Run the app.

**Expected behavior**
The application should print Parsed auth results to console, instead it prints Failed to parse auth results.

**Comment by jstedfast** [comment]
You are correct... The `/` character is one of the tspecials that is not allowed in a property value.

```
pvalue := [CFWS] ( value / [ [ local-part ] "@" ] domain-name ) [CFWS]
value  := token / quoted-string
token  := 1*<any (US-ASCII) CHAR except SPACE, CTLs, or tspecials>
tspecials :=  "(" / ")" / "<" / ">" / "@" / "," / ";" / ":" / "\" / <"> / "/" / "[" / "]" / "?" / "="
```

I changed the code to allow '/' since it is a base64 character and I don't think it'd hurt to allow it.
