### ISSUE TITLE
Removing wrapper for long file attachment name

### ISSUE THREAD

**Issue by charleen-tham** [jstedfast/MimeKit#519]
Hi,

I need help with removing the `?us-ascii?q?` thing that appends itself in the content disposition and content type of the attachment header.

I've tried using the `FormatOptions` but it errors out on `"Expected '/' at position {0}"` and I'm not sure what is causing this issue. 

I understand the need for it but we need to remove it as it is causing compatibility issues with another add-in that we are required to be compatible with.

Edit: Here's a code of what I was attempting

```var formatOptions = FormatOptions.Default.Clone();
formatOptions.MaxLineLength = 998;

int index = attachment.Headers.IndexOf(HeaderId.ContentType);
var header = attachment.Headers[index];
header.SetValue(formatOptions, "us-ascii", attachment.ContentType.Name);
```

Any help would be much appreciated!

**Comment by jstedfast** [comment]
Well, yea, that code is going to produce an error because you're setting the entire Content-Type header value to the value of the name parameter.

Here's what you want to do:

```csharp
Parameter param;

if (attachment.ContentType.Parameters.TryGetValue ("name", out param))
    param.EncodingMethod = ParameterEncodingMethod.Rfc2231;
```

**Comment by charleen-tham** [comment]
Hello!

Thanks for the quick reply!

I've tried out your code but it doesn't quite achieve what I need.

I need to make sure that the entire content type name is not separated, and that the `?us-ascii?` stuff is also not present in the name, otherwise the add-in we need to be compatible with will drop the entire attachment. 

So I need something like 
```
Content-Type: application/octet-stream; name="very-long-file-name-here.pdf";
```
instead of these
```
Content-Type:application/octet-stream; name*0="very-long";
name*1=file-name.pdf

or

Content-Type:application/octet-stream; name="?us-ascii?q?very-long-file-name-here?us-ascii?q?pdf"; (or sth along the lines of that if you use Rfc2047)
```

Many thanks!

**Comment by jstedfast** [comment]
You can't. All you can do is choose shorter file names.
