### ISSUE TITLE
MailboxAddress does not allow comments at the beginning or end of address

### ISSUE THREAD

**Issue by TheJayMann** [jstedfast/MimeKit#520]
**Describe the bug**
When attempting to create a `MailboxAddress` containing a comment in the address appearing at the beginning or the end of the address.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CLR
 - .NET Framework:  .NET 4.7.2
 - MimeKit Version: 2.1.3 

**To Reproduce**
```csharp
var addr = new MailboxAddress("(comment)user@domain.example");
```

**Expected behavior**
I would expect that the `MailboxAddress` would be successfully created with the comments removed

**Additional context**
From what I can determine, `MailboxAddress` will only accept and remove comments when they appear directly next to `@` or `.`, where the email address would still be valid after removing the comments.  From what I understood about the email address format is that a comment could appear directly before or after either the local part or domain name.  While I was not able to make much sense of RFC 5322 to confirm this, I did find an example in [Appendix A.5](https://tools.ietf.org/html/rfc5322#appendix-A.5) which shows a comment at the end of a local part, and at both the beginning and end of a domain part email address.  The examples shown appear to work as expected when using `System.Net.Mail.MailAddress` but does not work correctly with `MailboxAddress`.

Also, while I am using version 2.1.3, what I believe to be the relevant code located near the beginning of `InternetAddress.TryParseLocalPart` is identical to version 2.4.1 as well as the master branch at the time of submitting this issue.

**Comment by jstedfast** [comment]
`new MailboxAddress (string)` is not meant for parsing, it is meant for a pre-parsed addresses.

You want `MailboxAddress.Parse (string)`

**Comment by jstedfast** [comment]
Just confirmed that if you use MailboxAddress.Parse() it works.

**Comment by TheJayMann** [comment]
It had not occurred to me to look for a Parse method.  This appears to work without issue.
