### ISSUE TITLE
Newline characters are getting stripped from UTF-8 SubjectLines

### ISSUE THREAD

**Issue by brianfeucht** [jstedfast/MimeKit#521]
**Describe the bug**
Newline characters are getting stripped from UTF-8 SubjectLines

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: Netstandard2.0
 - .NET Framework: NET472
 - MimeKit Version: 2.4.1

**To Reproduce**
```

            var emlContent =
@"Return-Path: <hello@litmus.com>
From: =?utf-8?B?TGl0bXVz?= <hello@litmus.com>
To: ""Litmus"" <hello@litmus.com>
Subject: =?utf-8?B?Rmlyc3QgbGluZQoKVGhpcmQgbGluZQ==?=
Date: Tue, 12 Nov 2019 16:56:42 +0100
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary=""----=_NexPart_000""


------=_NexPart_000
Content-Type: text/plain;
	charset=utf-8
Content-Transfer-Encoding: base64

SGVsbG8gZnJvbSBsaXRtdXM=

------=_NexPart_000
Content-Type: text/html;
	charset=utf-8
Content-Transfer-Encoding: base64

PGgxPkhlbGxvIGZyb20gbGl0bXVzPC9oMT4=

------=_NexPart_000--
";

            using (var ms = new MemoryStream())
            using (var sw = new StreamWriter(ms))
            {
	            sw.Write(emlContent);
	            sw.Flush();
	            ms.Seek(0, SeekOrigin.Begin);

		    var mimeMessage = MimeMessage.Load(ms);

	            Assert.That(mimeMessage.Subject, Is.EqualTo("First line\n\nThird line"));
            }
```

This fails as the Subject doesn't contain any newline characters
```
  Expected string length 22 but was 20. Strings differ at index 10.
  Expected: "First line\n\nThird line"
  But was:  "First lineThird line"
  ---------------------^
```

**Expected behavior**
Subject line to return in with newlines

```
Return-Path: <hello@litmus.com>
From: Litmus <hello@litmus.com>
To: "Litmus" <hello@litmus.com>
Subject: First line

Third line
Date: Tue, 12 Nov 2019 16:56:42 +0100
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NexPart_000"
```

**Comment by jstedfast** [comment]
This is expected behavior.

**Comment by jstedfast** [comment]
Why are you putting newlines in a Subject header anyway? Doesn't make much sense since no client will show a multi-line subject header.

**Comment by brianfeucht** [comment]
I agree this is a really poor practice, but we have a few customers who are doing this.  Our problem is we use the subject line to verify an email is open in Outlook.  Outlook just truncates the subject line at the newline and the string we get back from mailkit doesn't have a newline character in it.  So it becomes pretty difficult to do that verification when Outlook just does a truncate and the string we have has no indication there was a newline in it.

**Comment by jstedfast** [comment]
I'll reopen this issue and think about what to do, then.

**Comment by brianfeucht** [comment]
Doing a little more digging for a workaround and I found that Outlook is leaving the new lines intact vs truncating.  This means I was able to handle this case by stripping those new lines and doing the compare directly with what Mailkit is returning.

Feel free to close this as our need for a fix reduced.

**Comment by jstedfast** [comment]
ok
