### ISSUE TITLE
 bcc not working

### ISSUE THREAD

**Issue by 70076541** [jstedfast/MimeKit#523]
Hi I tried to write to you in my previous issue that even if closed the communication took place anyway. In any case I report what was written at the time

Sorry the disturb but, I am again struggling with a problem. I wanted to use the class this time no longer to receive e-mails but to send them. I managed to do what I wanted but, I encounter a problem when I go to use the .bcc property
in practice it does not reach the e-mail address at the address set in the .to property and neither at the .bcc address, apparently getting no anomaly on the contrary, everything works when the property is set and the property .cc. I was currently using version 2.1.3 and switched to version 2.3.2 but, again with the same negative result. Following part of the code used in order to better understand my possible error. As always, thanks in advance

                    var message = new MimeMessage();

                    // Message from
                    if (!string.IsNullOrEmpty(from))
                    {
                        message.From.Add(new MailboxAddress(from));
                    }
                    //  ....

                    // Message To
                    if (!string.IsNullOrEmpty(to))
                    {
                        message.To.Add(new MailboxAddress(to));
                    }
                    //  ....
                    
                    // Message Cc 
                    if (!string.IsNullOrEmpty(cc))
                    {
                        //MailboxAddress Cc = new MailboxAddress(cc);
                        //message.Cc.Add(Cc);

                        message.Cc.Add(new MailboxAddress(cc));
                    }
                    //  ....

                    // Message Bcc 
                    if (!string.IsNullOrEmpty(bcc))
                    {
                        //MailboxAddress Bcc = new MailboxAddress(bcc);
                        //message.Bcc.Add(Bcc);

                        message.Bcc.Add(new MailboxAddress(bcc));
                    }
                    //  ....

                    message.Subject = subject;

                    var builder = new BodyBuilder();

                    // Set the plain-text version of the message text
                    builder.TextBody = body;

                    if (attachments != null)
                    {
                        foreach (string file in attachments)
                        {
                            if (!string.IsNullOrEmpty(file))
                            {
                                // We may also want to attach a calendar event for Monica's party...
                                builder.Attachments.Add(file);
                                //  ....
                            }
                        }
                    }

                    // Now we just need to set the message body and we're done
                    message.Body = builder.ToMessageBody();

                    if (smtp != null)
                    {
                        smtp.Send(message);
                    }

**Comment by jstedfast** [comment]
```csharp
message.Bcc.Add(new MailboxAddress(bcc));
```

What does the `bcc` string look like? Is it `"user@example.com"`? Or is it `"User Name <user@example.com>"` Or is it `"user1@example.com, user2@example.com"`?

`new MailboxAddress (string)` only works with the first example above. Not the others. If you need to handle the second case, you need to use `MailboxAddress.Parse (string)`. If you need to handle multiple addresses in a string, then you need to use `InternetAddressList.Parse (string)`.

Once you are adding To/Cc/Bcc addresses correctly to the message, then you will need to provide me with a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) when sending an example message so that I can see what MailKit is doing and if it is dropping or ignoring any errors.

**Comment by 70076541** [comment]
I'm sorry I got the job. 
So I'm using the fields in the simplest way, no concatenation or anything. In bcc I write the address in the classic format: account@domainname.extension. I attach log. I await your thanks a lot
[smtp.log](https://github.com/jstedfast/MimeKit/files/3876857/smtp.log)

**Comment by jstedfast** [comment]
@70076541 according to the log, the message was sent without any errors.

Am I understanding correctly that `amministrazionepla@legalmail.it` is not receiving the message?

If that is the case, then the bug is with the SMTP server and not MailKit.

**Comment by 70076541** [comment]
you understand well but, why only when I use the bcc field? in my opinion it should also do so in message.Cc.Add (new MailboxAddress (cc)); while I insert it in this field it works perfectly and so with any other email

**Comment by jstedfast** [comment]
I have no idea, but if that is the email address that was in the Bcc then MailKit sent it to that address and the server accepted it and said that it sent it.

**Comment by jstedfast** [comment]
Check your spam folder I guess.

**Comment by 70076541** [comment]
Okay, why check for spam if I put it in the cc field? the incoming server cannot be distinguished if it was sent as cc or bcc. Furthermore, the destination e-mail I am running tests on is my own, so I would immediately notice if it ended up in spam and as I said before, I don't change the internet network, I just configure it, but only the platform. If I use Outlook I don't find any anomaly neither on cc nor on bcc if I use mailkit it works but only if I use the cc field and so with other mailboxes.

**Comment by jstedfast** [comment]
I have no idea, all I know is that MailKit is doing everything 100% correctly.

**Comment by jstedfast** [comment]
Here's what's important:

```
C: MAIL FROM:<fattureclinicaveterinariafoce@legalmail.it>
C: RCPT TO:<andrea--hp@hotmail.com>
C: RCPT TO:<amministrazionepla@legalmail.it>
S: 250 MAIL FROM:<fattureclinicaveterinariafoce@legalmail.it> OK
S: 250 RCPT TO:<andrea--hp@hotmail.com> OK
S: 250 RCPT TO:<amministrazionepla@legalmail.it> OK
```

Notice that MailKit is sending the message to everything that it is supposed to send it to and the server acknowledges who it will be sending the message to and says "OK".

If the server knows who to give the message to and it's not delivering it, how would *I* know why it's not delivering the message?

This is why I am suggesting that you check your spam folder. Maybe the mail server is putting it into your spam folder.

Again, that's not MailKit or MimeKit's fault, that's due to whatever rules your mail server is following.

**Comment by jstedfast** [comment]
BTW, I just realized you left your username/password in the log file - I would recommend changing that.

I'm not sure how to delete the smtp.log file off the github server (or if only you can do that). If you can, that would be a good idea to do as well.

**Comment by 70076541** [comment]
I removed the log file anyway they are all test boxes. I understand your suggestion to check the spam that I repeat is empty but, as I said before, it would make no sense to check the spam if by sending as cc it arrives in the inbox anyway I will try to get in touch with the hosting to understand where it is is stopping this mail

**Comment by 70076541** [comment]
Excuse the insistence but, I can't understand and I would like to redo the situation because I think we lost our way:

first situation:
  sending by setting a single e-mail address in the To field and everything works.

Second situation:
  sending by setting two mail addresses one in the To field and the other in the Cc field and everything works.

Third situation:
sending by setting two mail addresses one in the To field and the other in the Bcc field and none of the two addresses will receive the mail. And it's this I don't understand

**Comment by jstedfast** [comment]
Try your test program with another SMTP server such as GMail or something.

All I know is that both the addresses in the To/Bcc headers are being specified in `RCPT TO` commands (see the log for this evidence) and the server replies with 250 (OK). MailKit then sends the `DATA` command followed by the raw message and the server responds again with 250 (OK).

Once it is uploaded to the SMTP server, it is out of MailKit's control.

Have you contacted your administrator to ask what is happening to those messages? Maybe your admin will have logs that will tell you what happened.
