### ISSUE TITLE
Inserting headers at top causes change in header order

### ISSUE THREAD

**Issue by nitinag** [jstedfast/MimeKit#524]
When trying to insert a header on the top of the header list, the Content-* Body headers are moved to the top:
```
var sourceStream = new MemoryStream(Encoding.UTF8.GetBytes(@"From: Example Test <test@example.com>
MIME-Version: 1.0
Content-Type: multipart/mixed;
   boundary=""simple boundary""

Test
"));

var mimeMessage = MimeMessage.Load(sourceStream);
mimeMessage.Headers.Insert(0, HeaderId.Received, "Test");
```

The resulting output is:
```
Content-Type: multipart/mixed;
   boundary="simple boundary"
Received: Test
From: Example Test <test@example.com>
MIME-Version: 1.0

Test
```

**Expected behavior**
MimeKit should maintain header order and add the header to the top.

**Comment by jstedfast** [comment]
I've got a fix for this locally, but I want to verify with some unit tests first.

This week is back-to-back meetings, so I'm finding it difficult to make time to write code this week.

**Comment by nitinag** [comment]
No worries, thanks for the work addressing it!
