### ISSUE TITLE
WindowsSecureMimeContext uses first RecipientInfo only

### ISSUE THREAD

**Issue by ydhondt** [jstedfast/MimeKit#530]
**Describe the bug**
Using the WindowsSecureMimeContext decrypting an encrypted mail sometimes fails. The reason for this is that it might find multiple RecipientInfos and only tries to find the key for the first one while it should also check the second, third, ...
After discovering the issue, I found it also documented at [https://www.limilabs.com/blog/envelopedcms-decrypt-problem](https://www.limilabs.com/blog/envelopedcms-decrypt-problem).

**Platform:**
 - OS: Windows
 - .NET Framework: .Net Core 3.1, .NET 4.8
 - MimeKit Version: all

**Proposed Solution**
Rather than using the EnvelopedCms.Decrypt() method, use the EnvelopedCms.Decrypt(System.Security.Cryptography.Pkcs.RecipientInfo recipientInfo) for each recipient info. The below code loops over them and stops as soon as we had a successful decryption.

```csharp
public override MimeEntity Decrypt (Stream encryptedData, CancellationToken cancellationToken = default (CancellationToken))
{
    if (encryptedData == null)
        throw new ArgumentNullException (nameof (encryptedData));

    var enveloped = new EnvelopedCms ();

    enveloped.Decode (ReadAllBytes (encryptedData));
    
    var success = false;

    foreach (var recipientInfo in enveloped.RecipientInfos)
    {
        try
        {
            enveloped.Decrypt(recipientInfo);
            success = true;
            break;
        }
        catch (CryptographicException)
        {
        }
    }

    if (!success)
    {
        // No key was found for any of the recipients, so throw an exception.
        // Probably should add some info on which recipients we tried to look for.
        throw new CryptographicException("No key to decrypt was found");
    }    

    var decryptedData = enveloped.Encode ();

    var memory = new MemoryStream (decryptedData, false);

    return MimeEntity.Load (memory, true, cancellationToken);
}
```

**Comment by jstedfast** [comment]
Thanks, I've fixed this in git master now.

**Comment by ydhondt** [comment]
@jstedfast  I added a comment to your code fix last week but I have the idea it went overlooked. So I'm adding it here as well:

> I am not sure this will work. I think you should break after the first successful attempt.
With this code, if there are multiple RecipientInfos and for at least one there is a failure to decrypt the EnvelopedCms, it will result in a complete failure while it should not.
As soon as there is one RecipientInfo for which the decryption is successful, the decryption should be considered successful. Hence the boolean and the break in my suggested code.

**Comment by jstedfast** [comment]
I already fixed that :-)
