### ISSUE TITLE
Capability to extract current email body from thread.

### ISSUE THREAD

**Issue by sumanrajpura** [jstedfast/MimeKit#531]
**Is your feature request related to a problem? Please describe.**
I am trying to parse emails from office 365 account and show them on html page. If the email contains long thread I want to hide all previous email content(HTML Body) and show only recent email content to user.

**Describe the solution you'd like**
I would like to have a property which can provide current email content(HTML body) and also other property that contains all previous email content.

**Describe alternatives you've considered**
As of now I am not able to handle it as each email provider does that in different way. Outlook desktop adds "---Original Message---", Outlook web shows Separator Line  gmail shows "On X day and X time user X wrote"

Thanks,
Suman Rajpura.

**Comment by jstedfast** [comment]
It's not going to be any easier for me to do, sorry.
