### ISSUE TITLE
Parse of email with brackets on from header recover an empty field.

### ISSUE THREAD

**Issue by reinaldocoelho** [jstedfast/MimeKit#532]
**Describe the bug**
Using MimeMessage.Load(stream) on EML with FROM having format "[Matt] <matt@email.com>", recover an blank From field to Message object.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: DotNet4.6.1, NetCore 2.1
 - .NET Framework: .Net Core, .NET 4.6.1
 - MimeKit Version: 2.4.1

**To Reproduce**
1. Create an EML with code below.
2. Simple parse the EML with Mimekit lib.
3. Verify "From" field on "Message" object.
4. Expected to see the email but has blank text.

**Expected behavior**
Expected to see the email on "From" field but has blank text.

**Screenshots**
![MimeKit-CodeRunning-Pic](https://user-images.githubusercontent.com/889634/72552637-10f4da80-3876-11ea-827c-bad1a7fe64e5.PNG)
![MimeKit-EML-Pic](https://user-images.githubusercontent.com/889634/72552638-10f4da80-3876-11ea-8481-51ed78f76bb0.PNG)

**Additional context**

1. EML used to test Bug:

`
To: contact@client.com.br
Content-type:  text/html; charset=UTF-8
Content-Transfer-Encoding: base64
From: [Invalid Sender] <sender@tk2-201-10422.vs.sakura.ne.jp>
Message-Id: <20200109031145.2D81D8805811@dcnet.sakura.ne.jp>
Date: Thu,  9 Jan 2020 11:13:09 +0900 (JST)
Subject:  =?UTF-8?B?VGVzdCBzdWJqZWN0IHRvIHZhbGlkYXRlIHByb2JsZW0=?=

PCFET0NUWVBFIEhUTUwgUFVCTElDICItLy9XM0MvL0RURCBIVE1MIDQuMDEgVHJhbnNpdGlvbmFsLy9FTiI+CjxodG1sPgo8aGVhZD4KICA8dGl0bGU+TkIxPC90aXRsZT4KPC9oZWFkPgo8Ym9keT4KCTxoMT4gVGl0bGUgdGVzdCA8L2gxPgoJPHA+VGhpcyBpcyBvbmx5IGEgc2ltcGxlIEhUTUwgYm9keSB0ZXN0LjwvcD4KPC9ib2R5Pgo8L2h0bWw+Cg==
`

**Comment by reinaldocoelho** [comment]
![MimeKit-CodeRunning-Pic](https://user-images.githubusercontent.com/889634/72552637-10f4da80-3876-11ea-827c-bad1a7fe64e5.PNG)
![MimeKit-EML-Pic](https://user-images.githubusercontent.com/889634/72552638-10f4da80-3876-11ea-8481-51ed78f76bb0.PNG)

**Comment by jstedfast** [comment]
If I am understanding rfc5322 correctly, the syntax is invalid:

```
   atext           =   ALPHA / DIGIT /    ; Printable US-ASCII
                       "!" / "#" /        ;  characters not including
                       "$" / "%" /        ;  specials.  Used for atoms.
                       "&" / "'" /
                       "*" / "+" /
                       "-" / "/" /
                       "=" / "?" /
                       "^" / "_" /
                       "`" / "{" /
                       "|" / "}" /
                       "~"

   atom            =   [CFWS] 1*atext [CFWS]

   specials        =   "(" / ")" /        ; Special characters that do
                       "<" / ">" /        ;  not appear in atext
                       "[" / "]" /
                       ":" / ";" /
                       "@" / "\" /
                       "," / "." /
                       DQUOTE

   mailbox         =   name-addr / addr-spec

   name-addr       =   [display-name] angle-addr

   display-name    =   phrase

   word            =   atom / quoted-string

   phrase          =   1*word / obs-phrase

   obs-phrase      =   word *(word / "." / CFWS)
```

We can see from the syntax definitions above that a `phrase` (the `display-name` component of a `name-addr`-style mailbox address) must either be an `atom` or a `quoted-string` and an `atom` clearly does not allow `[` or `]`.

*That said*, I don't think there would be any negative consequences for allowing square bracket characters in the name in MimeKit's parser...

The only special meaning I can think of that make use of square brackets are `domain-literal` tokens which would not appear in any areas that could easily be confused with a "phrase atom".

**Comment by jstedfast** [comment]
Thanks for the bug report!

**Comment by reinaldocoelho** [comment]
But in this case, the "Name" in brackets may be invalid, but the address is normal.
If the "From" object has "Name" and "Address", the library should not display the "Name" field, but may display the "Address" field as a result.
Because if we look at the EML, the "From" exists and is understandable.
Is it the best behavior for the library during parse to remove all information because of an invalid character?
Wouldn't it be better to return information that is at least valid?

**Comment by jstedfast** [comment]
That's the goal. Most of the `specials` characters were handled when they were encountered in the `display-name` except square brackets which is what you hit. Now they are handled, too.

**Comment by reinaldocoelho** [comment]
Cool, will you release a version to this?
The last version on Nuget is the same 2.4.1.

Thank you :-)

**Comment by jstedfast** [comment]
Yea, I'm hoping to have some free time this weekend (or maybe tonight) to make a release.

**Comment by thomas-westergard-scandinn-se** [comment]
works: displayname = "Tom Doe [Corp One]".
works: displayname = "Tom Doe Cörp Öne".
does NOT work: displayname = "Tom Doe [Cörp Öne]".

**Comment by jstedfast** [comment]
@thomas-westergard-scandinn-se This bug is about *parsing*, not sending.
