### ISSUE TITLE
Getting extension from a given mime type

### ISSUE THREAD

**Issue by jacargentina** [jstedfast/MimeKit#534]
**Is your feature request related to a problem? Please describe.**
I have an Image instance, and I'm. detecting its mime type, then I need to build a "filename" for it from a given title string; I need to put the right extension for the mime so when I send that content via WordpressPCL library, It gets correctly detected and processed.

```
var image = ....;
var mimeType = ImageCodecInfo.GetImageEncoders().First(codec => codec.FormatID == image.RawFormat.Guid).MimeType;
var filename = ...
```
I'm looking on how to reuse `MimeTypes` class from this MimeKit as it is already a dependency on my c# project for email; but it does only the reverse thing (from a filename get the mime type);

**Describe the solution you'd like**
Would be nice to to the other way too; from a given mime type, get the extension; so I can build the correct filename.

**Describe alternatives you've considered**
Copy and paste the already existing mapping dictionary from MimeTypes on my code.......

**Comment by jacargentina** [comment]
I can add another dependency to my project like this one https://github.com/samuelneff/MimeTypeMap

But as I stated previously, having already MimeKit , would be nice to avoid more dependencies and have a new method on it.

**Comment by wartab** [comment]
It seems to me that this is completely out of scope for a library like MimeKit. MimeKit's purpose is to parse and also build MIME messages.
Guesstimating what file extension could be associated with a certain media type has nothing to do with that.

**Comment by jacargentina** [comment]
@wartab Look `MimeTypes.GetMimeType`. Basically that method is doing a  guessing for the mime type by looking at the filename.

I think the reverse is **in scope** for the library just because the code is already there

**Comment by jstedfast** [comment]
Implemented.
