### ISSUE TITLE
MailboxAddress.Parse throws unexpected ParseException for International Address

### ISSUE THREAD

**Issue by MrBreZe** [jstedfast/MimeKit#536]
**Describe the bug**
Prior to version 2.5.0 MailboxAddress.Parse("test.täst@test.net") worked fine but now a ParseException is thrown.
MimeKit.ParseException
  HResult=0x80131537
  Message=Invalid address token at offset 0
  Source=MimeKit
  StackTrace:
   at MimeKit.InternetAddress.TryParse(ParserOptions options, Byte[] text, Int32& index, Int32 endIndex, Int32 groupDepth, AddressParserFlags flags, InternetAddress& address) in InternetAddress.cs:

**Platform:**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net Core 3.1
 - MimeKit Version:  2.5.0

**To Reproduce**
MailboxAddress parsed = MailboxAddress.Parse("test.täst@test.net");

**Expected behavior**
MailboxAddress.Parse should be able to parse the text parameter even if it contains only one valid international email address and no name or any other information.

**Additional context**

new MailboxAddress("test.täst@test.net") works fine and MailboxAddress.Parse works if i surround the international address with "<" ">" like "<test.täst@test.net>".

i tried to narrow down the change that created that bug ([2.4.1...2.5.0](https://github.com/jstedfast/MimeKit/compare/2.4.1...2.5.0))
i am not sure but maybe it has something to do with commit [Fixed mailbox address parser to be more lenient about []'s in the dis…](https://github.com/jstedfast/MimeKit/commit/ac26fa608fff55cf83cabdca9180e5b5f95d7562)

PS: Thank you soooo much for this awesome library (mailkit + mimekit)

**Comment by The-Nutty** [comment]
I have also observed issues with MailboxAddress.Parse after 2.5.0, previously `MailboxAddress.Parse("​test@test.co.uk")` would work fine (notice the zero width space at the front of the email address) where as with 2.5.0 its now throwing the following exception:
```
MimeKit.ParseException: Invalid address token at offset 0
  at MimeKit.InternetAddress.TryParse(ParserOptions options, Byte[] text, Int32& index, Int32 endIndex, Int32 groupDepth, AddressParserFlags flags, InternetAddress& address)
  at MimeKit.MailboxAddress.Parse(ParserOptions options, String text)
```

Im assuming this issue is related how i can create another issue if you believe it is not.

**Comment by jstedfast** [comment]
@The-Nutty I suspect that you are correct believing that it is related.

I'll try to dig into this soon.

**Comment by jstedfast** [comment]
Turns out it was a trivial bug/fix ;-)

I added unit tests to cover both of these examples and they are both passing now.

Thanks for the bug report, guys!

**Comment by jstedfast** [comment]
Just release MimeKit 2.5.1 with this fix.
