### ISSUE TITLE
Are all message parts retrieved in GetMessage method?

### ISSUE THREAD

**Issue by mretlenj** [jstedfast/MimeKit#537]
Hi,
we're having an issue in production, so we need some explanation. 
We're getting the message from server by passing just unique id to GetMessage method.
Sometimes message parts (some embedded images, marked as  !part.IsAttachment) are missing, and we're unable to reproduce it reliably, as after reprocessing same e-mail again, all message parts are present and available as expected.  Is it possible that content streams of some message parts are not fully initialized in moment when GetMessage method returns?

**Comment by jstedfast** [comment]
GetMessage() retrieves the full message.

I would recommend studying the protocol log to see why those parts aren't there sometimes.
