### ISSUE TITLE
Links get corrupted when using the HtmlToHtml-Converter

### ISSUE THREAD

**Issue by McTristan** [jstedfast/MimeKit#539]
We never had a single issue with the HtmlToHtml-Textconverter, we are using it mainly to embed images and set the target-Attributes of anchor (i.e. "a href") elements.
We recently received a mail with a link containing a order-id which looks like this:

https://myspeciawebsite.com/link/approve-order.php?t=ln02hjwc8sf6yszdd8hvz0rb8hjm&order_id=987654

it seems the Converter is not happy with the "&order" part of the string because it always replaces it with &#8500; (# & 8500;)
When we debug it we can see that the HtmlTagContext.HtmlAttribute with the name "href" and the value is already wrong so it not the HtmlTagContext.WriteTag method but rather some strange preprocessing.
The rest of the link stays in tact, in fact we have thousands of mails with links and they all work but these "order_id" links.

**Comment by jstedfast** [comment]
As you are probably aware, `&<string>` syntax is used by HTML for encoding unicode characters.

There just so happens to be an [`&order;`](https://github.com/jstedfast/HtmlKit/blob/master/CodeGenerator/HtmlEntities.json#L1424) entity that the parser is finding in that attribute, which it decodes to that unicode character.

That said, it seems like `&order;` may need to end with `;`. I may have to re-think my HTML entity decoder a bit...

**Comment by jstedfast** [comment]
Okay, this should be fixed now.
