### ISSUE TITLE
Consider referencing Portable.BouncyCastle for .NET Framework

### ISSUE THREAD

**Issue by jjmanton** [jstedfast/MimeKit#540]
I am in the process of migrating a large codebase towards PackageReference, and bouncy castle has been a blocker, lacking support for the format. We are running .NET Framework 4.8, and are hoping to use Oren's fork, Portable.BouncyCastle. We also have a dependency on Mimekit, and I don't believe there is a way to tell nuget to substitute a package for a different dependency. 

Would it be possible for MimeKit to reference the portable bouncy castle fork, to support those of us in transition towards Package Reference and Net Core? At least until the PR https://github.com/bcgit/bc-csharp/pull/68 gets merged?

**Comment by jstedfast** [comment]
I would not be opposed to this, I'm just worried about what sorts of problems it might have on developers already using MimeKit and BouncyCastle.

**Comment by jjmanton** [comment]
I understand that hesitantcy. As a different approach, would the maintenance overhead be too large to publish an alternate version? Either under a different NuGet package name, or possibly a pre-release version (2.5.2-Portable)? 

The pre-release version would allow us to stay on the main MimeKit channel, and just upgrade once this BouncyCastle business is behind us. I am happy to pitch in if there is work to be done.

**Comment by jstedfast** [comment]
I don’t think that would be a practical solution.

**Comment by jstedfast** [comment]
I guess we'll see how it goes. I'm not going to hold my breath that Portable.BouncyCastle will be merged into the mainline branch anytime soon. I've been waiting 3 years already :-\
