### ISSUE TITLE
InternetAddress not accept UTF-8 address.

### ISSUE THREAD

**Issue by reinaldocoelho** [jstedfast/MimeKit#541]
**Describe the bug**
The class InternetAddress can´t parse an UTF-8 address like "sómeone@testserver.com".

**Platform:**
 - OS:  Windows 10
 - .NET Runtime: All
 - .NET Framework: 4.6.1
 - MimeKit Version: 2.5.0

**To Reproduce**
1. Set up InternetAddress Parse/TryParse with UTF-8 address:
    1. var address = InternetAddress("sómeone@testserver.com");
2. On run will thrown an exception:
    1. MimeKit.ParseException : Invalid address token at offset 0

**Expected behavior**
How exists SMTPUTF8 servers, I expected Parse finish with True, since the Charset encoding is set to UTF8.

**Comment by reinaldocoelho** [comment]
Closing this issue because it´s solved on version 2.5.2.

Sorry.

**Comment by jstedfast** [comment]
Yea, it was a temporary bug :-)

Thanks for reporting tho!
