### ISSUE TITLE
The decryption result is not equal to the origin content + `WriteToAsync` method corrupts content.

### ISSUE THREAD

**Issue by fyodorklimenko** [jstedfast/MimeKit#544]
Thank you for your amazing library!
But I've faced a small issue. In fact, there are two issues but I believe they are connected.

**Describe the bug**
I test MimeKit's encryption/decryption engine with different files.
Each file contains different EOL characters: `\r`, `\n`, `\r\n` and mixed.
I load file content into the stream, create `MimePart`, encrypt it, decrypt and compare decrypted content with origin one.
It looks like, the decrypted content is not equal to the original one for files that contain `\n` as EOL.

Also, during my investigation, I found out that `MimePart`'s `WriteToAsync` method corrupts content in the same way.

**Platform**
 - OS: Windows, Linux
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net Core
 - MimeKit Version: 2.5.2

**To Reproduce**
I created a [repository](https://github.com/fyodorklimenko/mime-kit-issue) to reproduce these issues.
[Here](https://github.com/fyodorklimenko/mime-kit-issue/blob/master/MimeKitIssue/MimeKitTests/Tests.cs#L21) I create `MimePart`, write it into the file, load it and compare results.
And [here](https://github.com/fyodorklimenko/mime-kit-issue/blob/master/MimeKitIssue/MimeKitTests/Tests.cs#L42) I create `MimePart`, encrypt it, decrypt it and compare decrypted content with origin one.

**Expected behavior**
Decrypted content must be equal to the original one.
Loaded into file `MimePart`'s content must be equal to the original one. 

**Additional context**
[Here](https://github.com/fyodorklimenko/mime-kit-issue/runs/522527622?check_suite_focus=true) you can find test execution result

**Comment by jstedfast** [comment]
Your expectations are wrong. MIME needs to be encoded in <CRLF> format when encrypting.

**Comment by jstedfast** [comment]
For additional information, see https://tools.ietf.org/html/rfc5751#section-3.1

And https://tools.ietf.org/html/rfc5322 for more information about the canonical format off messages, most notably that line endings are always CRLF for headers and the body.

MimeKit *supports* bare LF formatted messages because it is very common on Unix & Linux systems, but it is not the canonical form.

**Comment by fyodorklimenko** [comment]
Thank you for the extremely fast response!

And you are absolutely right: line breaks must be represented by `CRLF` sequence.

In my case, I want to work with files in binary mode.
So I should set related `ContentTransferEncoding` property in `MimePart` object.
