### ISSUE TITLE
Blank mail body with Outlook

### ISSUE THREAD

**Issue by ermirbeqiraj** [jstedfast/MimeKit#545]
**Describe the bug**
We are using MimeKit to build messages and send them through pmta, where placeholder/s merge takes place on their side. Opening messages from any web mail client and everything is fine, but outlook renders the body blank.

**Platform (please complete the following information):**
 - .NET Framework: .Net Core
 - MimeKit Version: 2.5.1

**Additional context**
Funny thing is that if I strip out the comments inside html, outlook manages to render that too.

Here's the message string generated after write-to:

```
From: Ermir Beqiraj <contact@domain.net>
Date: Sat, 21 Mar 2020 15:11:47 +0100
Subject: Template Test - (03:11 PM) - Sample Template
X-Dkim-Options: s=key1;d=email-marketing-by-domain.com
To: [ReceiverMailbox]
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="=-RpbxUAzzorWNK3TH8ivpJg=="

--=-RpbxUAzzorWNK3TH8ivpJg==
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

 VISIT SHOP SAVE UP TO 60% ON SELECTED&nbsp; PRODUCTS 30% Behind the w=
ord mountains. Button 50% Behind the word mountains. Button 40% Behind=
 the word mountains. Button 60% Behind the word mountains. Button Soci=

... text continues ...


--=-RpbxUAzzorWNK3TH8ivpJg==
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

 <html xmlns=3D"http://www.w3.org/1999/xhtml" xmlns:v=3D"urn:schemas-m=
icrosoft-com:vml" xmlns:o=3D"urn:schemas-microsoft-com:office:office">=
 <head>  <meta http-equiv=3D"Content-Type" content=3D"text/html; chars=

.... html continues ....

</table></body> </html>
--=-RpbxUAzzorWNK3TH8ivpJg==--

```

Any help would be appreciated :) 

Ps: Thanks a lot for this awesome package!

**Comment by jstedfast** [comment]
If removing the HTML comments makes it render in Outlook, then the problem is the HTML. 🤷‍♂
