### ISSUE TITLE
Verifying `MultipartSigned` that is signed with an expired certificate.

### ISSUE THREAD

**Issue by fyodorklimenko** [jstedfast/MimeKit#547]
Hello!
Thank you for your library! The more I use it, the more I love it.

**My problem**
I use `TemporarySecureMimeContext` to sign/verify.
In my case, the signer's certificate is already expired.
On verify stage `BouncyCastleSecureMimeContext`'s `BuildCertPath` method is called to set signature's chain.
Expectedly, `PkixCertPathBuilder` fails because signer's certificate is expired: https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Cryptography/BouncyCastleSecureMimeContext.cs#L508

**My questions**
What should I do when I want to avoid certificate checking?

**Additional context**
For example, in M2Crypto library I can use `PKCS7_NOVERIFY` flag if I do not care if I have set of valid certificates.

**Comment by jstedfast** [comment]
What hooks in BuildCertPath() do you need? I can provide a virtual method for you to override to configure the PkixBuilderParameters if you want. Would that work?

Find out what values you need to set on it and we'll go from there.

**Comment by jstedfast** [comment]
Try to get back to me soon because I'm getting close to a release (and I don't like to make back-to-back releases if I can avoid it).

**Comment by fyodorklimenko** [comment]
Sorry for my delay.
I'm not an expert in cryptography so I need a little bit more time to give you a meaningful answer.

Here is stack trace of the `Build` method (just some notes, you can skip it):  
`PkixCertPathBuilder`'s `Build` method [calls](https://github.com/bcgit/bc-csharp/blob/18f1d45b8d649b051c26fd2a5c70d37ab00604a6/crypto/src/pkix/PkixCertPathBuilder.cs#L140) `PkixCertPathValidator`'s `Validate` one.  
`PkixCertPathValidator`'s `Validate` method [calls](https://github.com/bcgit/bc-csharp/blob/18f1d45b8d649b051c26fd2a5c70d37ab00604a6/crypto/src/pkix/PkixCertPathValidator.cs#L272) `Rfc3280CertPathUtilities`'s `ProcessCertA` one.  
`Rfc3280CertPathUtilities` [checks](https://github.com/bcgit/bc-csharp/blob/18f1d45b8d649b051c26fd2a5c70d37ab00604a6/crypto/src/pkix/Rfc3280CertPathUtilities.cs#L1539) if certificate is valid.

If I had a virtual method to configure `PkixBuilderParameters` I'd have two possible solutions to build chain with expired certificates:

1. Wrap all certificates into `AlwaysValidX509Certificate`.

Here is the possible implementation of `AlwaysValidX509Certificate`:
```csharp
public class AlwaysValidX509Certificate : X509Certificate
{
    public override bool IsValidNow => true;
    public override DateTime NotAfter => DateTime.MaxValue;

    public AlwaysValidX509Certificate(X509Certificate origin) : base(origin.CertificateStructure)
    {
    }

    public override bool IsValid(DateTime time)
    {
        return true;
    }

    public override void CheckValidity()
    {
        return;
    }
}
```

2. Or I can modify `PkixBuilderParameters`'s `Date`.
```csharp
var parameters = new PkixBuilderParameters(anchors, selector);
...
parameters.Date = new DateTimeObject(certificate.CertificateStructure.EndDate.ToDateTime() - TimeSpan.FromMinutes(1));
```

But in any of those two case `SecureMimeDigitalSignature`'s `Verify` method will fail because it [calls](https://github.com/bcgit/bc-csharp/blob/18f1d45b8d649b051c26fd2a5c70d37ab00604a6/crypto/src/cms/SignerInformation.cs#L638) `SignerInformation`'s `Verify` method that checks signing date.

**My summary**:
1. virtual method to override parameters is not a key.
2. each of my possible solutions above is crap.
3. MimeKit must not support chain building with an expired certificate.
4. MimeKit should support `PKCS7_NOVERIFY`.. but I do not know how to implement it for now.

For now, I implemented a naive solution that handles my corner case: if the special flag is `true`, `MultipartSigned` has a single signature and the signed certificate is expired then use the provided certificate to check if the signature is valid.

```csharp
public class VerifySecureMimeContext : TemporarySecureMimeContext
{
    private readonly X509Certificate _anchor;
    private readonly bool _isExpiredCertificateValid;

    public VerifySecureMimeContext(X509Certificate anchor, bool isExpiredCertificateValid)
    {
        _anchor = anchor ?? throw new ArgumentNullException(nameof(anchor));
        _isExpiredCertificateValid = isExpiredCertificateValid;
    }

    protected override HashSet GetTrustedAnchors()
    {
        var anchors = base.GetTrustedAnchors();
        anchors.Add(new TrustAnchor(_anchor, null));
        return anchors;
    }

    public override async Task<DigitalSignatureCollection> VerifyAsync(Stream content, Stream signatureData,
        CancellationToken cancellationToken = default(CancellationToken))
    {
        _ = content ?? throw new ArgumentNullException(nameof(content));
        _ = signatureData ?? throw new ArgumentNullException(nameof(signatureData));

        var signatures = await base.VerifyAsync(content, signatureData, cancellationToken);

        if (_isExpiredCertificateValid)
        {
            if (signatures.Count == 1 &&
                signatures.Single() is SecureMimeDigitalSignature s &&
                s.SignerCertificate.ExpirationDate < DateTime.UtcNow)
            {
                signatures = new DigitalSignatureCollection(
                    new List<IDigitalSignature>
                    {
                        new SecureMimeDigitalSignature(s.SignerInfo,
                            new AlwaysValidX509Certificate(_anchor))
                    });
            }
        }

        return signatures;
    }
```

I think I should close my issue till the better times just because I can't explain how `PKCS7_NOVERIFY` should work in the scope of MimeKit.

**Comment by jstedfast** [comment]
ok.
