### ISSUE TITLE
MimeMessage Attachments property missing attachments

### ISSUE THREAD

**Issue by franva** [jstedfast/MimeKit#548]
**Describe the bug**
Attachments property missing attachments. 

How can I confirm this behavior? 
I found the attachment in BodyParts.  See my screenshots

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Runtime: DotNet Core 3.1.0
 - MimeKit Version: 2.5.2

**To Reproduce**
1. Write a project to retrieve emails with PDF attachments
2. Set up breakpoints once `email = imapClient.Inbox.GetMessageAsync(emailId) `is called
3. Inspect the email object 
4. Compare Attachments and BodyParts properties.

**Expected behavior**
I am expecting the Attachments to do what its name suggests.

**Screenshots**
Attachments is empty
![image](https://user-images.githubusercontent.com/5151146/77838043-bd7b0300-71bb-11ea-8d78-acc6a2939368.png)

But the BodyParts[2] does have the pdf attachment.
![image](https://user-images.githubusercontent.com/5151146/77838037-a9cf9c80-71bb-11ea-8ff0-6405f0e8f201.png)

**Additional context**
I am scanning Gmail.

**Comment by jstedfast** [comment]
Attachments have a `ContentDisposition` header with a value of `attachment`. Yours has a value of `inline`.

That's why it's a BodyPart, but not an Attachment.

**Comment by franva** [comment]
thanks for the explanation.

I'm trying to retrieve the PDF attachment, but after I got the PDF from BodyPart[2], and using iText7 to parse it, it throws an exception:

> PDF header not found.

So it seems that this attachment missing PDF header. Do you know how to handle it?

```
pdfPart = email.BodyParts.FirstOrDefault(bp => bp.ContentType.MimeType.Contains("pdf"));
        var mimePart = (MimePart)pdfPart;
            var stream = new MemoryStream();
            mimePart.ContentObject.DecodeToAsync(stream);

   PdfReader reader = new PdfReader(stream); // This is where the exception happened
            var pdf = new PdfDocument(reader);
            var page = pdf.GetPage(pageIndex);
            var strategy = new SimpleTextExtractionStrategy();
            var content = PdfTextExtractor.GetTextFromPage(page, strategy);
            return content;
```

**Comment by franva** [comment]
Figured it out. I need to set the stream.Position back to 0 before passing to reader.
