### ISSUE TITLE
Wrong `MultipartSigned` entity loading from file.

### ISSUE THREAD

**Issue by fyodorklimenko** [jstedfast/MimeKit#549]
**Describe the bug**
I've got the file with exactly two body parts that represent multipart/signed content.

Something like this:
```
MIME-Version: 1.0
Content-Type: multipart/signed; protocol="application/x-pkcs7-signature"; micalg="sha-256"; boundary="----86F625064294EBBAD7FDD935CFB9B7B1"

This is an S/MIME signed message

------86F625064294EBBAD7FDD935CFB9B7B1
﻿One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.
------86F625064294EBBAD7FDD935CFB9B7B1
Content-Type: application/x-pkcs7-signature; name="smime.p7s"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7s"

MIIGQwYJKoZIhvcNAQcCoIIGNDCCBjACAQExDzANBglghkgBZQMEAgEFADALBgkq
...
x9i9k/1ATYzmrFbebCPKFlbqbQQ9n3s=

------86F625064294EBBAD7FDD935CFB9B7B1--


```

I try to load `MultipartSigned` via `LoadAsync` method.
As a result, I've got an entity with a single part.
Looks like MimeKit ignores the first part over which the digital signature was created just because there are no headers.

**Platform:**
 - OS: Windows (might be ALL)
 - .NET Runtime: CoreCLR (might be ALL)
 - .NET Framework: .Net Core (might be ALL)
 - MimeKit Version: 2.5.2

**To Reproduce**
1. Sign any file via openssl.
2. Create `MultipartSigned` entity using `LoadAsync` method.
3. Verify the number of parts: there is one instead of two.

**Expected behavior**
`LoadAsync` loads `MultipartSigned` and do not miss the part.

**Additional context**
I created [repository](https://github.com/fyodorklimenko/mime-kit-multipart-signed-write-load-issue) to reproduce the issue:
1. Go to the `TestProject` directory:
`cd .../MimeKitMultipartSignedWriteLoadIssue/TestProject`

2. Remove existing signing result:
`rm signed.txt`

3. Sign `origin.txt` via openssl:
`openssl smime -sign -in origin.txt -out signed.txt -signer pem.pem -inkey pem.pem -passin pass:password`

4. Run test project:
`dotnet test`

Also, I found out [RFC](https://tools.ietf.org/html/rfc4134#page-87) with an example of `MultipartSigned` entity. There are no headers in the first part.

**Comment by jstedfast** [comment]
This isn't a bug in MimeKit, this is a bug in openssl.

In MIME, you can skip the headers, but you MUST have a blank line before the content in that case. For more details, see [rfc2046, section 5.1](https://tools.ietf.org/html/rfc2046#section-5.1) which states:

>  In the case of multipart entities, in which one or more different
>  sets of data are combined in a single body, a "multipart" media type
>  field must appear in the entity's header.  The body must then contain
>  one or more body parts, each preceded by a boundary delimiter line,
>  and the last one followed by a closing boundary delimiter line.
>  **After its boundary delimiter line, each body part then consists of a
>  header area, a blank line, and a body area.**  Thus a body part is
>  similar to an RFC 822 message in syntax, but different in meaning.
>
>  A body part is an entity and hence is NOT to be interpreted as
>  actually being an RFC 822 message.  To begin with, NO header fields
>  are actually required in body parts.  **A body part that starts with a
>  blank line, therefore, is allowed and is a body part for which all
>  default values are to be assumed.**  In such a case, the absence of a
>  Content-Type header usually indicates that the corresponding body has
>  a content-type of "text/plain; charset=US-ASCII".

MimeKit handles properly formed MIME entities with no headers.

You can test this using the following program:

```csharp
using System;
using System.IO;

using MimeKit;

namespace MimeEntityLoadTest {
	public class Program
	{
		public static void Main (string[] args)
		{
			using (var stream = File.OpenRead (args[0])) {
				var entity = MimeEntity.Load (stream);

				if (entity is Multipart multipart) {
					Console.WriteLine ("Multipart.Count = {0}", multipart.Count);
					for (int i = 0; i < multipart.Count; i++) {
						var ctype = multipart[i].ContentType;
						Console.WriteLine ("[{0}] ContentType = {1}", i, ctype);
					}
				}
			}
		}
	}
}
```

And a copy & paste of the sample in that RFC:

```
Content-Type: multipart/signed;
    micalg=SHA1;
    boundary="----=_NextBoundry____Fri,_06_Sep_2002_00:25:21";
    protocol="application/pkcs7-signature"

This is a multi-part message in MIME format.

------=_NextBoundry____Fri,_06_Sep_2002_00:25:21

This is some sample content.
------=_NextBoundry____Fri,_06_Sep_2002_00:25:21
Content-Type: application/pkcs7-signature; name=smime.p7s
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=smime.p7s

MIIDdwYJKoZIhvcNAQcCoIIDaDCCA2QCAQExCTAHBgUrDgMCGjALBgkqhkiG9w0BBwGgggL
gMIIC3DCCApugAwIBAgICAMgwCQYHKoZIzjgEAzASMRAwDgYDVQQDEwdDYXJsRFNTMB4XDT
k5MDgxNzAxMTA0OVoXDTM5MTIzMTIzNTk1OVowEzERMA8GA1UEAxMIQWxpY2VEU1MwggG2M
IIBKwYHKoZIzjgEATCCAR4CgYEAgY3N7YPqCp45PsJIKKPkR5PdDteoDuxTxauECE//lOFz
SH4M1vNESNH+n6+koYkv4dkwyDbeP5u/t0zcX2mK5HXQNwyRCJWb3qde+fz0ny/dQ6iLVPE
/sAcIR01diMPDtbPjVQh11Tl2EMR4vf+dsISXN/LkURu15AmWXPN+W9sCFQDiR6YaRWa4E8
baj7g3IStii/eTzQKBgCY40BSJMqo5+z5t2UtZakx2IzkEAjVc8ssaMMMeUF3dm1nizaoFP
VjAe6I2uG4Hr32KQiWn9HXPSgheSz6Q+G3qnMkhijt2FOnOLl2jB80jhbgvMAF8bUmJEYk2
RL34yJVKU1a14vlz7BphNh8Rf8K97dFQ/5h0wtGBSmA5ujY5A4GEAAKBgFzjuVp1FJYLqXr
d4z+p7Kxe3L23ExE0phaJKBEj2TSGZ3V1ExI9Q1tv5VG/+onyohs+JH09B41bY8i7RaWgSu
OF1s4GgD/oI34a8iSrUxq4Jw0e7wi/ZhSAXGKsZfoVi/G7NNTSljf2YUeyxDKE8H5BQP1Gp
2NOM/Kl4vTyg+W4o4GBMH8wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBsAwHwYDVR0j
BBgwFoAUcEQ+gi5vh95K03XjPSC8QyuT8R8wHQYDVR0OBBYEFL5sobPjwfftQ3CkzhMB4v3
jl/7NMB8GA1UdEQQYMBaBFEFsaWNlRFNTQGV4YW1wbGUuY29tMAkGByqGSM44BAMDMAAwLQ
IUVQykGR9CK4lxIjONg2q1PWdrv0UCFQCfYVNSVAtcst3a53Yd4hBSW0NevTFjMGECAQEwG
DASMRAwDgYDVQQDEwdDYXJsRFNTAgIAyDAHBgUrDgMCGjAJBgcqhkjOOAQDBC4wLAIUM/mG
f6gkgp9Z0XtRdGimJeB/BxUCFGFFJqwYRt1WYcIOQoGiaowqGzVI

------=_NextBoundry____Fri,_06_Sep_2002_00:25:21--
```

**Comment by jstedfast** [comment]
To work around this issue, make sure that the input text file that you pass to `openssl smime -sign ...` is properly MIME formatted.
