### ISSUE TITLE
Can't run tests in VS 2019?

### ISSUE THREAD

**Issue by naasking** [jstedfast/MimeKit#550]
**Describe the bug**
I can't seem to run the tests using VS 2019, v16.5.2.

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - MimeKit Version: master

**To Reproduce**
1. Check out master.
2. Open solution.
3. Try to run tests
4. Error in console:
    Log level is set to Informational (Default).
    Test data store opened in 0.031 sec.
    ---------- Starting test discovery ----------
    Test project UnitTests does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
    It's recommended to reference NuGet test adapters in each test project in the solution.
    No test is available in C:\Users\naask\source\repos\MimeKit\MimeKit\bin\Debug\net47\MimeKit.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in C:\Users\naask\source\repos\MimeKit\MimeKit\bin\Debug\net45\MimeKit.dll C:\Users\naask\source\repos\MimeKit\Mono.Data.Sqlite\bin\Debug\Mono.Data.Sqlite.dll C:\Users\naask\source\repos\MimeKit\UnitTests\bin\Debug\UnitTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in C:\Users\naask\source\repos\MimeKit\MimeKit\bin\Debug\net48\MimeKit.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    No test is available in C:\Users\naask\source\repos\MimeKit\MimeKit\bin\Debug\net46\MimeKit.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
    ========== Test discovery finished: 0 Tests found in 5.9 sec ==========
    ---------- Starting test run ----------
    No test matches the given testcase filter `FullyQualifiedName=UnitTests.ArgumentExceptionTests.TestAcceptArguments|FullyQualifiedName=UnitTests.ArgumentExceptionTests.TestBufferPoolArguments|FullyQualifiedName=UnitTests.ArgumentExceptionTests.TestCrc32Arguments|FullyQualifiedName=UnitTests.Argument...` in C:\Users\naask\source\repos\MimeKit\UnitTests\bin\Debug\UnitTests.dll
    ========== Test run finished: 0 Tests run in 1.8 sec (0 Passed, 0 Failed, 0 Skipped) ==========

That last entry seems to be the issue. I've found some references to it online, but none of the proposed solutions are for VS 2019 and don't seem to apply or work when I try them.

**Expected behavior**
Tests run.

**Screenshots**
![image](https://user-images.githubusercontent.com/1582300/78272293-5622c300-74db-11ea-8419-01320268b667.png)

**Additional context**
I thought maybe the NUnit version was out of date for the new VS, so I upgraded to NUnit 3.12 and fixed the tests that wouldn't build, but same results. I'm trying to add a method and create a [pull request](https://github.com/naasking/MimeKit), but obviously want to run the test I added first.

**Comment by jstedfast** [comment]
I've never been able to get NUnit to work in the Windows version of Visual Studio.

I always just run them on Mac in VS for Mac or on the command-line in Windows.

**Comment by jstedfast** [comment]
FWIW, when you submit a PR, the automated builds will run the unit tests.

**Comment by naasking** [comment]
The fact that it didn't work for you either was the clue I needed. There's a [VS extension for NUnit 2](https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnitTestAdapter), and NUnit 3 has a similiar one, but like xUnit, it also has a [nuget package that can install the runner](https://www.nuget.org/packages/NUnit3TestAdapter/) if you ever move to NUnit 3.

However, some of the other tests fail when I run in VS. For instance TnefTests.TestOneFile fails with:

    one-file.tnef: AUTHORS content length does not match
      Expected: 252
      But was:  244

I'll create a PR and see what happens when the automated builds run the tests.

**Comment by jstedfast** [comment]
I wonder if that test fails due to CRLF vs LF line endings?

**Comment by naasking** [comment]
Good point, I left the default git options which I think converts LF to CRLF on Windows. I'll try checking out without that option later and see if that resolves the issue.

**Comment by jstedfast** [comment]
I added a bunch of work-arounds in most of the tests for CRLF vs LF, but I might not have done that for the TNEF tests.

I mostly based it on whatever failures AppVeyor was getting.

**Comment by naasking** [comment]
I compared the one-file.tnef in my local copy with a direct download from github using Chrome, and they are identical. A hexdump also shows only LF.

I can confirm that the quoted printable tests fail when letting git autoconvert LF to CRLF.
