### ISSUE TITLE
SQLite dependent tests fail on Windows

### ISSUE THREAD

**Issue by naasking** [jstedfast/MimeKit#552]
**Describe the bug**
Tests dependent on sqlite3 fail.

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - MimeKit Version: master

**Additional context**
The tests can't find any sqlite3.dll. Error:

    System.TypeInitializationException : The type initializer for 'Mono.Data.Sqlite.UnsafeNativeMethods' threw an exception.
      ----> System.DllNotFoundException : Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
    Stack Trace: 
        SQLite3.Open(String strFilename, SQLiteOpenFlagsEnum flags, Int32 maxPoolSize, Boolean usePool) line 128
        SqliteConnection.Open() line 888
        SqlCertificateDatabase.ctor(DbConnection connection, String password) line 81
        SqliteCertificateDatabase.ctor(DbConnection connection, String password) line 222
        SqliteCertificateDatabase.ctor(String fileName, String password) line 205
        DefaultSecureMimeContextTests.TestArgumentExceptions() line 71
        --DllNotFoundException
        UnsafeNativeMethods.sqlite3_libversion_number()
        UnsafeNativeMethods.cctor() line 27

First attempt at resolving this by using the x64 version of [sqlite3](https://www.nuget.org/packages/sqlite/) package results in this error:

    System.TypeInitializationException : The type initializer for 'Mono.Data.Sqlite.UnsafeNativeMethods' threw an exception.
      ----> System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
    Stack Trace: 
        SQLite3.Open(String strFilename, SQLiteOpenFlagsEnum flags, Int32 maxPoolSize, Boolean usePool) line 128
        SqliteConnection.Open() line 888
        SqlCertificateDatabase.ctor(DbConnection connection, String password) line 81
        SqliteCertificateDatabase.ctor(DbConnection connection, String password) line 222
        SqliteCertificateDatabase.ctor(String fileName, String password) line 205
        DefaultSecureMimeContextTests.TestArgumentExceptions() line 71
        --BadImageFormatException
        UnsafeNativeMethods.sqlite3_libversion_number()
        UnsafeNativeMethods.cctor() line 27

However, changing it to the x86 library works, even though I'm running on a 64-bit system. I think VS runs all tests as x86 by default.

After adding the sqlite3 nuget package, all the sqlite tests pass after changing line 57 to read:

    private const string SQLITE_DLL = "x86\\sqlite3";

**Comment by jstedfast** [comment]
Windows should not be using Mono. Data.Sqlite, it should be using System. Data.Sqlite from the nuget package.

**Comment by jstedfast** [comment]
Maybe the above commit will fix it.

**Comment by jstedfast** [comment]
FWIW, this works fine on the AppVeyor CI bot which is running the unit tests on Windows.

*shrug*

**Comment by naasking** [comment]
Your changes didn't fix the issue, so I think the reason AppVeyor succeeds is that it likely runs on 64-bit machines. I traced back which instance of SQLite was loaded since you mentioned this is different on Windows, and I think it's down to line 118 of SqliteCertificateDatabase.cs:

    `if (platform == PlatformID.Unix || platform == PlatformID.MacOSX || IntPtr.Size == 4) {
		if ((sqliteAssembly = SQLiteAssembly.Load ("Mono.Data.Sqlite")) != null) {`

My PlatformId in the tests is "Win32NT" but also IntPtr.Size==4, so it passes the above check and loads Mono.Data.Sqlite. Obviously if it were running in 64-bit mode, this check would fail and the code that immediately follows loads System.Data.SQLite.

**Comment by jstedfast** [comment]
Let's take out the IntPtr.Size check, then. I doubt anyone uses Mono.Data.Sqlite on Windows.

**Comment by naasking** [comment]
Progress, it now fails when it doesn't find SQLite.Interop.dll. To fix this just add the following to UnitTest.csproj and it all works:

    <PropertyGroup> 
     <ContentSQLiteInteropFiles>true</ContentSQLiteInteropFiles>
     <CopySQLiteInteropFiles>false</CopySQLiteInteropFiles>
     <CleanSQLiteInteropFiles>false</CleanSQLiteInteropFiles>
     <CollectSQLiteInteropFiles>false</CollectSQLiteInteropFiles>
    </PropertyGroup>

**Comment by naasking** [comment]
I can confirm that all tests now pass on VS 2019 community edition on Windows 10 Pro 64-bit running  the NUnit using the VS test runner.
