### ISSUE TITLE
Tnef tests fail on Windows with VS Community 2019

### ISSUE THREAD

**Issue by naasking** [jstedfast/MimeKit#553]
**Describe the bug**
As I mentioned in #550, some .tnef unit tests fail on Windows.

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - .NET environment: VS 2019 community edition
 - MimeKit Version: master

**Additional context**
Most of the tests pass except the following due to some kind of content length mismatch:

    missing-filenames.tnef: generpts.src content length does not match
      Expected: 62901
      But was:  61210
    
     Stack Trace: 
      TnefTests.TestTnefParser(String path, TnefComplianceStatus expected) line 817
      TnefTests.TestMissingFileNames() line 877

And:

    one-file.tnef: AUTHORS content length does not match
      Expected: 252
      But was:  244
    
    Stack Trace: 
      TnefTests.TestTnefParser(String path, TnefComplianceStatus expected) line 817
      TnefTests.TestOneFile() line 895

And:

    two-files.tnef: AUTHORS content length does not match
      Expected: 252
      But was:  244
    
    Stack Trace: 
      TnefTests.TestTnefParser(String path, TnefComplianceStatus expected) line 817
      TnefTests.TestTwoFiles() line 919

As mentioned in the other thread, it doesn't appear to be a LF/CRLF issue with the test files. I haven't dug into this too deeply since I'm not too familiar with the .tnef format. Let me know if you have any thoughts on what to look into to find the issue.

**Comment by jstedfast** [comment]
It was a CRLF vs LF issue.

**Comment by naasking** [comment]
I cloned your repo from scratch without LF conversions and it works now. Thanks!

**Comment by jstedfast** [comment]
Awesome :-)
