### ISSUE TITLE
ContentId in MimeEntity is not parsed correctly when Content-Id header ends with "."

### ISSUE THREAD

**Issue by Nevca** [jstedfast/MimeKit#555]
**Describe the bug**
ContentId in MimeEntity is not parsed correctly when Content-Id header ends with "."

**Platform (please complete the following information):**
 - OS: Windows

**To Reproduce**
I have a Content-Id header with `Value == "<B754224F-C74F-4739-91BE-91EF6313A0A3@hsd1.ca.comcast.net.>"`

When the header is parsed in `MimeEntity.OnHeadersChanged`, the output from `ParseUtils.TryParseMsgId` is `"B754224F-C74F-4739-91BE-91EF6313A0A3@hsd1.ca.comcast.net"`

Notice that in Value there's a "." at the end. I think this s not a valid Content-Id but still, can it be fixed somehow?

**Expected behavior**
The values should match.

**Comment by jstedfast** [comment]
Why would you want it to have the "." at the end?

MimeKit is doing the correct thing here by removing it in order to give you the canonical form of the Content-Id.

(This behavior is by design, in case you were wondering)

**Comment by Nevca** [comment]
I understand but wanted you to know just in case.

I need it so I can find find if it is present in the email body, and there the CID is with the "." at the end. I guess I can use the Value from the header directly for a workaround?

**Comment by jstedfast** [comment]
You could do that or you could use http://www.mimekit.net/docs/html/M_MimeKit_Utils_MimeUtils_ParseMessageId_1.htm to parse the string after "cid:" in the URI and then match.

**Comment by Nevca** [comment]
Thanks!

**Comment by jstedfast** [comment]
No problem. In general, it's always best to canonicalize these types of things because the HTML generator might write the value in a different form than the MIME generator, etc.

I'm not sure about HTML, but the MIME specification actually requires that MIME generators use the canonical form of domain names when writing email addresses and msg-id tokens (including content-id) for this reason.
