### ISSUE TITLE
MultipartSigned Message Attachments with unicode file names appear as “Untitled attachment” in Outlook

### ISSUE THREAD

**Issue by papaja** [jstedfast/MimeKit#557]
**Describe the bug**
When I use MultipartSigned.Create(CmsSigner signer, MimeEntity entity) pdf attachments in Outlook 2010 to 2016 get name "Untitled attachment XXXX.dat". txt attachments keep txt extension. Attachments in Outlook 365, Outlook online and Gmail show just fine

Multipart messages which are not singed work as expected, so I believe it is not this case: https://github.com/jstedfast/MimeKit/issues/186.

**Platform (please complete the following information):**
 - OS:  Windows 10
 - .NET Framework: .NET 4.5
 - MimeKit Version: 2.4.1

**To Reproduce**
I create System.Net.Mail MailMessage. Add subject, body, one pdf attachment. All fields and attachment name have UTF8 characters.

` 
        using (var mail = new System.Net.Mail.MailMessage())
        {
                    mail.To.Add(data.To);

                    mail.Subject = data.Subject;

                    String filename = String.Format("{0}.pdf", data.Title);

                    mail.Attachments.Add(new System.Net.Mail.Attachment(new MemoryStream(file), filename));
                    mail.Body = data.Body;

                    var certificate = GetEmailCertificate();
                    mailer.SendMail(mail, certificate);
}
        public void SendMail(System.Net.Mail.MailMessage msg, X509Certificate2 certificate)
        {
            CryptographyContext.Register(typeof(TemporarySecureMimeContext));

            var m = MimeMessage.CreateFromMailMessage(msg);

           
            using (var ctx = new TemporarySecureMimeContext())
            {
                // Note: this assumes that the Sender address has an S/MIME signing certificate
                // and private key with an X.509 Subject Email identifier that matches the
                // sender's email address.
               
                m.From.Add(new MailboxAddress(ReportConfig.ReportMailSender));
                CmsSigner cmsSigner = new CmsSigner(certificate);
                m.Body = MultipartSigned.Create(cmsSigner, m.Body);
            }

            using (var client = new MailKit.Net.Smtp.SmtpClient())
            {
                client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                var port = ReportConfig.Ssl ? 587 : 25;
                client.Connect(ReportConfig.SmtpServer, port, MailKit.Security.SecureSocketOptions.Auto);

                // Note: only needed if the SMTP server requires authentication
                if (!String.IsNullOrEmpty(ReportConfig.Username))
                {
                    try
                    {
                        client.Authenticate(ReportConfig.Username, ReportConfig.Password);
                    }
                    catch { }
                }
                client.Send(m);
                client.Disconnect(true);
            }
        }`

**Expected behavior**
I would expect to receive attachment with UTF8 name and proper extension in older Outlook clients. Although I understand that this might suggest something is wrong with clients, I strongly believe that this should work.

**Comment by jstedfast** [comment]
It’s the same issue that you linked to.

**Comment by papaja** [comment]
Maybe I don't understand it well enough. Thank you for your quick reply.

Is it too much to ask how to change encoding of attachment name which we got from MimeMessage.CreateFromMailMessage(msg)?

**Comment by jstedfast** [comment]
Sure, https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#UntitledAttachments
