### ISSUE TITLE
Special characters are always sent with "?=" at the end of email subject

### ISSUE THREAD

**Issue by AdamGorkoz** [jstedfast/MimeKit#560]
Recently switched from .net mail lib to MimeKit and ran across this issue where all the email subjects are being sent with a "?=" suffix.

The subject i try to send is : "éééé éééééééé éééééééé éééééééé"
and it gets sent : "éééé éééééééé éééééééé éééééééé?="

Is there a configuration I should change or do something differently?

**Comment by jstedfast** [comment]
When I send it, the Subject is encoded as `Subject: =?utf-8?b?w6nDqcOpw6kgw6nDqcOpw6nDqcOpw6nDqSDDqcOpw6nDqcOpw6nDqcOpIMOpw6nDqcOpw6nDqcOpw6k=?=` which gets decoded to exactly the subject you started with.

Seems like a bug in whatever receiving mail client you are using and not MimeKit.

**Comment by jstedfast** [comment]
BTW, you can test that it is correctly encoded by taking the payload of the encoded-word token and base64 decoding it using something like:

```csharp
var bytes = Convert.FromBase64String ("w6nDqcOpw6kgw6nDqcOpw6nDqcOpw6nDqSDDqcOpw6nDqcOpw6nDqcOpIMOpw6nDqcOpw6nDqcOpw6k=");
var subject = Encoding.UTF8.GetString (bytes);
```

Here's a test using Mono's `csharp` shell:

```
Mono C# Shell, type "help;" for help

Enter statements below.
csharp> var bytes = Convert.FromBase64String ("w6nDqcOpw6kgw6nDqcOpw6nDqcOpw6nDqSDDqcOpw6nDqcOpw6nDqcOpIMOpw6nDqcOpw6nDqcOpw6k=");
csharp> System.Text.Encoding.UTF8.GetString (bytes);
"éééé éééééééé éééééééé éééééééé"                    
csharp>  
```
