### ISSUE TITLE
Disable folded headers

### ISSUE THREAD

**Issue by Vandersteen** [jstedfast/MimeKit#561]
**Is your feature request related to a problem? Please describe.**
Some clients do not support folded headers in the mime.

**Describe the solution you'd like**
The possibility to disable folded headers

**Describe alternatives you've considered**
For now I have to do this manually, writing to stream. Finding and replacing "\r\n\t" with " ". This is however very cumbersome and error prone.

Is there a way to do this more cleanly ?
I tried using FormatOptions.MaxLineLength but this does not work:

```
new FormatOptions(){
MaxLineLength = 998
}
```

**Comment by jstedfast** [comment]
I can't imagine any real-world mail software can't handle folded headers. That boggles my mind, honestly, since every single mail client folds long headers.

**Comment by jstedfast** [comment]
That said, You can use http://www.mimekit.net/docs/html/M_MimeKit_Header_SetRawValue.htm to set the raw value of the header(s) that you don't want folded, but you'll have to encode them yourself using one of these methods: http://www.mimekit.net/docs/html/Overload_MimeKit_Utils_Rfc2047_EncodeText.htm

**Comment by Vandersteen** [comment]
Ok, to clarify. We use MimeKit to parse and create AS2 message.
There are some older as2 system that cannot handle folded headers.
