### ISSUE TITLE
Special characters replaced by question marks

### ISSUE THREAD

**Issue by lucascc26** [jstedfast/MimeKit#564]
Hi everyone, I'm using MailKit to send emails in my application (ASP.NET Core 2.1).

Everything works fine when running on Windows.
The problem occurs when I run my app in a Docker container on Linux. All special characters are replaced by question marks:
![image](https://user-images.githubusercontent.com/11542138/80716520-1e08a300-8ace-11ea-9923-556cc2a8ac6b.png)

This is basically my code that send emails:
```
public async Task SendAsync(MailMessage message)
{
	var mimeMessage = new MimeMessage();
	mimeMessage.To.AddRange(message.To.Select(to => new MailboxAddress(to)));
	mimeMessage.From.Add(new MailboxAddress(_settings.From));

	var builder = new BodyBuilder();
	builder.HtmlBody = message.Body;

	mimeMessage.Subject = message.Subject;
	mimeMessage.Body = builder.ToMessageBody();

	// Tried this - did not work
	//foreach (var body in mimeMessage.BodyParts.OfType<TextPart>())
	//{
	//    body.ContentTransferEncoding = ContentEncoding.Base64;
	//}

	// Tried this - did not work
	//mimeMessage.Prepare(EncodingConstraint.SevenBit);

	using (var client = new SmtpClient())
	{
		// For demo-purposes, accept all SSL certificates (in case the server supports STARTTLS)
		client.ServerCertificateValidationCallback = (s, c, h, e) => true;

		await client.ConnectAsync(_settings.Server, _settings.Port, _settings.UseSsl);
		await client.AuthenticateAsync(_settings.Username, _settings.Password);
		await client.SendAsync(mimeMessage);
		await client.DisconnectAsync(true);
	}
}
```

I've seen a few related issues and tried to apply the suggested fixes (commented in the above code) but none worked.
Can anybody help me please?

Thanks in advance.

**Comment by jstedfast** [comment]
Can you attach a sample raw message?

**Comment by lucascc26** [comment]
> Can you attach a sample raw message?

Can you explain how I do that please?

**Comment by jstedfast** [comment]
`mimeMessage.WriteTo("raw-message.txt")`

**Comment by lucascc26** [comment]
```
From: from@myserver.com
Date: Thu, 30 Apr 2020 17:19:12 +0000
Subject: Teste
 =?utf-8?b?YWNlbnR1Ye+/ve+/vW8g77+9IO+/vSDvv70g77+9IO+/vSDvv70g77+9IO+/vSAt?=
 =?utf-8?b?IHTvv710dWxv?=
Message-Id: <65ZDPMT8IAU4.F6XCR0NE7H5E1@localhost.localdomain>
To: to@myserver.com
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Id: <SYYJPMT8IAU4.VMX2SBROEMTU1@localhost.localdomain>

Teste acentua��o � � � � � � � � - corpo

```

**Comment by jstedfast** [comment]
What's the string that you are setting as the message body? Seems like the string you are setting as the message body must be broken.

Also: what happens if you add back `mimeMessage.Prepare(EncodingConstraint.SevenBit);` before writing the message to a file?

**Comment by lucascc26** [comment]
The strings are:
- Subject = `Teste acentuação á é í ó ú ã õ ç - título`
- Body = `Teste acentuação á é í ó ú ã õ ç - corpo`

After `mimeMessage.Prepare(EncodingConstraint.SevenBit);`, raw message is:
```
From: from@myserver.com
Date: Thu, 30 Apr 2020 18:11:12 +0000
Subject: Teste
 =?utf-8?b?YWNlbnR1Ye+/ve+/vW8g77+9IO+/vSDvv70g77+9IO+/vSDvv70g77+9IO+/vSAt?=
 =?utf-8?b?IHTvv710dWxv?=
Message-Id: <ZMOKLY79IAU4.5KRKBDBOIB0W2@localhost.localdomain>
To: to@myserver.com
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Id: <ZIJQLY79IAU4.LWIQIEVYU6PH3@localhost.localdomain>
Content-Transfer-Encoding: base64

VGVzdGUgYWNlbnR1Ye+/ve+/vW8g77+9IO+/vSDvv70g77+9IO+/vSDvv70g77+9IO+/vSAt
IGNvcnBv
```

The result in email is the same though:
![image](https://user-images.githubusercontent.com/11542138/80745035-0513e800-8af6-11ea-9950-ae2e1d6f34c4.png)

**Comment by jstedfast** [comment]
Here's my test program:

```csharp
using System;
using System.IO;
using System.Text;

using MimeKit;

namespace Issue564 {
    class Program
    {
        public static void Main ()
        {
            var message = new MimeMessage ();
            message.From.Add (new MailboxAddress ("", "from@myserver.com"));
            message.Subject = "Teste acentuação á é í ó ú ã õ ç - título";
            
            var bodyBuilder = new BodyBuilder ();
            bodyBuilder.HtmlBody = "Teste acentuação á é í ó ú ã õ ç - corpo";

            message.Body = bodyBuilder.ToMessageBody ();

            message.WriteTo ("issue564.txt");
        }
    }
}
```

Here's my output:

```
From: from@myserver.com
Date: Thu, 30 Apr 2020 14:41:15 -0400
Subject: Teste
 =?utf-8?b?YWNlbnR1YcOnw6NvIMOhIMOpIMOtIMOzIMO6IMOjIMO1IMOnIC0gdMOtdHVsbw==?=
Message-Id: <W6CYC3M7IAU4.5C1MKPAUQD093@GLE-WFH01.redmond.corp.microsoft.com>
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Id: <I951D3M7IAU4.OGCG0JFTM6D6@GLE-WFH01.redmond.corp.microsoft.com>

Teste acentuação á é í ó ú ã õ ç - corpo
```

**Comment by jstedfast** [comment]
This suggests to me that the corruption in the message body is already in your input string before you set it as the message body.

**Comment by lucascc26** [comment]
Are you running your sample locally or in a Docker container?

**Comment by lucascc26** [comment]
This is my raw message running locally on Windows - works as expected:

```
From: from@myserver.com
Date: Thu, 30 Apr 2020 15:49:29 -0300
Subject: Teste
 =?utf-8?b?YWNlbnR1YcOnw6NvIMOhIMOpIMOtIMOzIMO6IMOjIMO1IMOnIC0gdMOtdHVsbw==?=
Message-Id: <MMY2GW48IAU4.S9IMX5D5NMFE3@localhost.localdomain>
To: to@mytest.com
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Id: <P9A9GW48IAU4.SRDIFSP6BB4L@localhost.localdomain>
Content-Transfer-Encoding: base64

VGVzdGUgYWNlbnR1YcOnw6NvIMOhIMOpIMOtIMOzIMO6IMOjIMO1IMOnIC0gY29ycG8=
```

**Comment by jstedfast** [comment]
Have you verified that the body string is correct in your Docker app?

Try hard-coding the strings to see if that works.

**Comment by jstedfast** [comment]
BTW, ran the test app on a Mac (not on Windows).

**Comment by lucascc26** [comment]
> Have you verified that the body string is correct in your Docker app?
> 
> Try hard-coding the strings to see if that works.

It is hard-coded already :(

> BTW, ran the test app on a Mac (not on Windows).

I wonder if it could be a problem on Linux only maybe?

**Comment by jstedfast** [comment]
How are these strings hard-coded in your app? Looks like there is some sort of invalid charset conversion going on.

Maybe your app was compiled with the wrong codepage?

**Comment by jstedfast** [comment]
FWIW:

Those question marks mean that charset conversion is failing somewhere where the target charset is (most likely) one of the unicode variants (no other charsets that I'm aware of contain those question mark characters).

- A C#/.NET string is UTF-16.
- The charset that the text/html part is in is UTF-8
- When you (or `BodyBuilder` in your particular case) sets `TextPart.Text`, the `.Text` property invokes `SetText (Encoding.UTF8, value)` with the value.
- UTF-16 to UTF-8 charset conversion cannot result in a string with those question marks because all UTF-16 strings can be converted into UTF-8 cleanly... UNLESS the input string already contains them.

What this means is that somewhere along the line, some non-unicode text is being converted into unicode (probably UTF-16) that contains characters that are illegal in the input charset.

This can happen, if, for example, you provide iso-8859-1 input text and claim that it is UTF-8 and then try to do charset conversion from UTF-8 to UTF-16.

**Comment by lucascc26** [comment]
Turns out my .cs file was encoded in ANSI (I don't know why it was created like that).
I saved it in UTF-8 and everything works as expected.

The info you provided helped me a lot.

Thank you very much.

**Comment by jstedfast** [comment]
Awesome! Glad you managed to solve the problem :-)
