### ISSUE TITLE
Question: Loading byte-stuffed message files

### ISSUE THREAD

**Issue by tcromer** [jstedfast/MimeKit#565]
Hi,

First off, what a great library this and MailKit is, awesome work!

I'm using MimeKit to process messages that have been delivered to a pickup folder by System.Net.Mail.SmtpClient, which I am now aware is flawed in it's implementation as it byte-stuffing when saving to disk.

The discussion here https://stackoverflow.com/questions/26555890/net-4-5-smtp-client-dot-stuffing-issue-when-delivering-to-pickup-directory was very informative and helped me to diagnose this very quickly, the issue I have though is I am unable to change the source application producing these messages so for now I am stuck with needing to handle byte-stuffed message files.

I have implemented a pretty crude approach to manage this which is simply reading the message files line by line, removing a dot if a line begins with 2 or more dots and writing to a new message file before loading with MimeKit to process and send.

Am I missing something with MimeKit, is there a better approach, or a parser option available to handle this already?

Thanks

**Comment by jstedfast** [comment]
Hi, yes, there's a better way.

What you'll want to do is write a custom stream filter to reverse the dot-stuffing process.

Once you've done that, you can do something like this:

```csharp
using (var stream = File.OpenRead ("message.eml")) {
    using (var filtered = new MimeKit.IO.FilteredStream (stream)) {
        var filter = new MyReverseDotStuffingFilter ();
        filtered.Add (filter);

        var message = MimeMessage.Load (filtered);
    }
}
```

The "hard" part is writing the filter, but there are a few examples you can use for reference:

- The [SmtpDataFilter](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpDataFilter.cs) is the filter used by MailKit to dot-stuff the message as it streams it to the SMTP server. This is the exact opposite process from what you want to do, but it's a fairly simple example.
- The [Pop3Stream](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Pop3/Pop3Stream.cs#L344) class has some built-in logic for reverse-dot-stuffing in the ReadAsync() method. This code may be helpful in that it also has to keep state between calls, so it may be helpful in that you should probably more-or-less be able to clone the logic a bit.
- The [Dos2Unix](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/IO/Filters/Dos2UnixFilter.cs) filter in MimeKit is very similar in concept in that it removes characters from the input. This should also serve as another good example of how to write filters.

Hope that helps.

**Comment by tcromer** [comment]
Thanks @jstedfast, here's what I came up with if anyone else has a use for this.

```
class RemoveDotStuffingFilter : MimeFilterBase
{
    int state; // 0 = normal, 1 = beginning of line, 2 = potential dot-stuffed line (skip next byte if '.')

    public RemoveDotStuffingFilter()
    {
        state = 1;
    }

    protected override byte[] Filter(byte[] input, int startIndex, int length, out int outputIndex, out int outputLength, bool flush)
    {
        int inputEnd = startIndex + length;
        int s = state;
        int ndots = 0;

        for (int i = startIndex; i < inputEnd; i++)
        {
            byte c = input[i];

            if (c == (byte)'.' && (s == 1))
            {
                s = 2;
            }
            else if (c == (byte)'.' && (s == 2))
            {
                s = 0;
                ndots++;
            }
            else
            {
                s = (c == (byte)'\n') ? 1 : 0;
            }
        }

        if (ndots == 0)
        {
            outputIndex = startIndex;
            outputLength = length;
            state = s;
            return input;
        }

        EnsureOutputSize(length - ndots, false);
        int index = 0;

        for (int i = startIndex; i < inputEnd; i++)
        {
            byte c = input[i];

            if (c == (byte)'.' && (state == 1))
            {
                state = 2;
                OutputBuffer[index++] = c;
            }
            else if (c == (byte)'.' && (state == 2))
            {
                state = 0;
            }
            else
            {
                state = (c == (byte)'\n') ? 1 : 0;
                OutputBuffer[index++] = c;
            }
        }

        outputIndex = 0;
        outputLength = index;

        return OutputBuffer;
    }

    public override void Reset()
    {
        base.Reset();
        state = 1;
    }
}
```
