### ISSUE TITLE
Ability to transform single-line Base64 string to one that respects a given maxLineLength

### ISSUE THREAD

**Issue by Nevca** [jstedfast/MimeKit#566]
**Is your feature request related to a problem? Please describe.**
I have the following scenario: I receive a Base64-encoded image and I want to create a MIME part from it. I instantiate a MimePart object, set its headers, then set it's content to
`new MimeContent(base64stream, ContentEncoding.Base64)`
That works fine as I don't need to encode but the issue is that the whole Base64 string is in a single line. This can be problematic for some SMTP servers when I try to sent the message since the maxLineLength is exceeded.

**Describe the solution you'd like**
Ability to transform a Base64 string to the format that respects maxLineLength (so basically what Base64Encoder does without the encoding part). And maybe such ability for the other decoders in MimeKit.

**Describe alternatives you've considered**
An alternative would be to do that before creating the Content of the MimePart, but since this is MIME-specific, the way I see it is that it should come as part of MimeKit.

**Comment by jstedfast** [comment]
It's kind of expected that if you create the MimeContent with pre-encoded data, that it is encoded "correctly".

The way around this is to do:

```csharp
var decoded = new MemoryStream ();

using (var filtered = new FilteredStream ()) {
    filtered.Add (DecoderFilter.Create (ContentEncoding.Base64));
    base64stream.CopyTo (filtered);
    filtered.Flush ();
}

new MimeContent (decoded, ContentEncoding.Default);
```

**Comment by Nevca** [comment]
AFAIK Base64-encoded strings are correct even without line breaks.

Is there a way of doing that without having to decoding and encoding the already encoded string?

**Comment by jstedfast** [comment]
Well, you could insert a line break after some multiple of 4 bytes (so 72 or 76 bytes per line).
