### ISSUE TITLE
GetPublicKey in DkimPublicKeyLocatorBase 

### ISSUE THREAD

**Issue by bertsinnema** [jstedfast/MimeKit#583]
**Describe the bug**
As I was implementing DKIM validation in my project, I encountered an error.  It seems there are various ways of generating these records.  My record only implements a **p** (pubkey) value and not a **k** (keytype) value.  

`v=DKIM1;t=s;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCwjSOiwxi1zNvHeXGFUFo2G/6IywyqrrRnW/NkvjwBW4dk6pnSD+Ww6zD4BUz8C7oudaqySxE1/DemI9L81dmBS3Czh0k3qwDqMCKd1kdMK+mTHt6UB0lqOapLgOIbhko8OhhlTsa26V+Dsg90NGYj3S7dM1/0IrQcR66VZqapBQIDAQAB`

Your implementation tries to populate both from line 104 of [DkimPublicKeyLocatorBase.cs:](https://github.com/jstedfast/MimeKit/blob/778ca3f1ac1d3edb16f9adb8894097218d37f742/MimeKit/Cryptography/DkimPublicKeyLocatorBase.cs)
```
switch (key)
{
	case "k":
		switch (value)
		{
			case "rsa": case "ed25519": k = value; break;
			default: throw new Exception($"Unknown public key algorithm: {value}");
		}
		break;
	case "p":
		p = value.Replace(" ", "");
		break;
}
```

In line 120 this will fail as it expects both **p** and **k** to be populated but it can only return one type AsymmetricKeyParameter

```
if (k != null && p != null) 
```
I think you should set the key to "rsa" when not supplied.

**Platform (please complete the following information):**
 - OS: Windows, Linux
 - .NET Runtime: Core 3.1
 - .NET Framework: Core 3.1
 - MimeKit Version: 2.6.0

**To Reproduce**
1. Publish a record generated on [Easydmarc.com](https://easydmarc.com/tools/dkim-record-generator/)
2. Run the key through DkimPublicKeyLocatorBase.GetPublicKey(s)

**Expected behavior**
To return an AsymmetricKeyParameter

**Additional context**
Happy to provide a pull request

**Comment by jstedfast** [comment]
Thanks for the bug report!

**Comment by bertsinnema** [comment]
This seems to work well.  Any change this could be released to NuGet soon?

Cheers!

**Comment by jstedfast** [comment]
I'm hoping to get some time soon to work on fixing the last remaining known issues so that I can make a release.
