### ISSUE TITLE
Regarding parsing of date time from received headers

### ISSUE THREAD

**Issue by agendec-com** [jstedfast/MimeKit#587]
Hello.

I've received some emails containing some invalid formatted Received headers, e.g.:
by filter0960p1iad2.sendgrid.net with SMTP id filter0960p1iad2-14907-5EB39606-10        2020-05-07 05:00:55.859878421 +0000 UTC m=+1240939.113482279

When using the MimeKit.Utils.DateUtils.TryParse on that string it returns true and the following date/time:
05.10.2020 02:00:00

Although it's an invalid formatting of the header, would it be possible for you to correctly interpret this as the valid date/time, or just instead return false on the parsing of this string?

Regards, Rolf

**Comment by jstedfast** [comment]
The DateUtils class is meant to parse only Date headers, not Received headers.
