### ISSUE TITLE
GroupAddress Should Not Contain Nested Groups

### ISSUE THREAD

**Issue by nitinag** [jstedfast/MimeKit#589]
As per https://tools.ietf.org/html/rfc5322#section-3.4:
the spec for group/group-list is:
```
group           =   display-name ":" [group-list] ";" [CFWS]
group-list      =   mailbox-list / CFWS / obs-group-list
```
The spec does not allow groups to contain other groups (nested groups). However, you can have multiple separate groups for the same header.

However, MimeKit currently allows nested groups to be created and parsed:
`Represents the member addresses of the group. Typically the member addresses will be of the MailboxAddress variety, but it is possible for groups to contain other groups.`
https://github.com/jstedfast/MimeKit/blob/b487c27926766019dfcb8e722bd732bb2f20be27/MimeKit/GroupAddress.cs#L126

Expected:
GroupAddress.Members should not allow/contain other GroupAddress objects, only MailboxAddress addresses.

This could lead other parsers/receivers to have trouble dealing with nested groups created with MimeKit. In our case, we're deciding our indexing/serialization storage format for the envelope details and noticed this inconsistency. We weren't previously planning to store/support nested groups since they're not allowed/expected as per the RFC, but if MimeKit allows it, we may want to do so since we can't expect to remember to check/ignore nested groups in every place we might use MimeKit. We may still need to fix it in some places like the IMAP server (still thinking which way we'll go). MimeKit already ignores multiple addresses (if present, as invalid) while parsing certain headers for items such as the Sender header, which the RFC doesn't allow multiple items for, but of course the message may contain it, which MimeKit ignores during parsing (#17).

Thought I'd at least raise it and document it here to see what you think. I understand if it might be a difficult change at this point.

**Comment by jstedfast** [comment]
The `ParserOptions` has a property called `MaxAddressGroupDepth` which defaults to 3 (altho maybe it should default to 1?) that controls how many levels of recursion the parser will go when parsing nested group addresses.

I think if you set it to `1`, it'll conform to what is allowed by the spec.

**Comment by nitinag** [comment]
Great, that's a good option to be aware of. Confirmed that works and `MaxAddressGroupDepth = 1` will simply ignore nested groups and parse the rest even if they occur afterward.

We'll most likely end up doing that, but I'll have to think more about how we want to handle it.

I did some tests with Outlook and Gmail and it seems neither even support creating/sending basic non-nested group addresses in the user interface. On the receiving side, both clients end up treating group addresses by displaying the individual addresses in the group with no actual grouping. Neither cause exceptions when they see nested groups (including multiple depth), but while Outlook displays the nested ones individually with no grouping, Gmail displays the nested addresses as part of the name of a single address.

**Comment by jstedfast** [comment]
That's interesting information about how those servers deal with this. Thanks for sharing!

**Comment by nitinag** [comment]
Just a thought:

Maybe the the docs for GroupAddress.Members should be updated because it currently implies that it's perfectly alright/valid to build a new message with nested groups, but the docs should discourage that for building new messages and maybe say that is not rfc complaint and would likely not work/display in other email clients.

It is probably useful to provide flexibility in parsing though as it already does right now, given how nested group handling/display varies based on email client (as per my previous testing notes above).

**Comment by jstedfast** [comment]
Yea, that's a good idea. I just reworded the docs to explain that. Thanks for the suggestion!
