### ISSUE TITLE
Fail to parse authentication results with non-standard 'for' keyword

### ISSUE THREAD

**Issue by The-Nutty** [jstedfast/MimeKit#592]
**Describe the bug**
Im sorry for another one of these but some email senders are doing some very odd stuff...
The following authentication results should parse but does not
```i=1;    relay.com;    dkim=pass header.d=mailfrom.com header.s=aabc header.b=xyz;    dmarc=pass (policy=none) header.from=mailfrom.com;    spf=pass (relay.com: domain of bounces@mailfrom.com designates 167.89.80.33 as permitted sender) smtp.mailfrom=bounces@mailfrom.com for abc@anotherdomain.com```

If you remove the ` for abc@anotherdomain.com` at the end it parses fine. 

**Platform (please complete the following information):**
- OS: Windows
- .NET Framework: Net core 3.1
- MimeKit Version: 2.9.1.8

**To Reproduce**
Use AuthenticationResults.Parse to parse the above string. It will throw the following exception
```
Unhandled exception. MimeKit.ParseException: Invalid propspec token at offset 313
   at MimeKit.Cryptography.AuthenticationResults.TryParseMethods(Byte[] text, Int32& index, Int32 endIndex, Boolean throwOnError, AuthenticationResults authres)
   at MimeKit.Cryptography.AuthenticationResults.TryParse(Byte[] text, Int32& index, Int32 endIndex, Boolean throwOnError, AuthenticationResults& authres)
   at MimeKit.Cryptography.AuthenticationResults.Parse(Byte[] buffer)
```

**Expected behavior**
Should parse sucessfully.

**Comment by jstedfast** [comment]
Ugh, I'm beginning to think that even trying to parse these is futile...

**Comment by The-Nutty** [comment]
Yeah... For something like this i wonder if its just worth striping the extra "for..." or something.

**Comment by The-Nutty** [comment]
Im going to close this as i think this was an artifact of our logging as opposed to an auth results we have seen. I will reopen this if we see it again.

**Comment by jstedfast** [comment]
ok
