### ISSUE TITLE
Add new BodyPart to the message

### ISSUE THREAD

**Issue by biapopescu** [jstedfast/MimeKit#597]
Hello!!

Sorry I realized I posted this issue on the MailKit project, so I am reopening it here... 

To help me debug your issue, please explain:
- What were you trying to do?
I am trying to add a new BodyPart to an exiting MimeMessage. I need to parse the different BodyParts and insert a new one after the first BodyPart in the Body Mime tree. I tried it by differente means but I am not able to find the right way. This is an example or what I have tried:
`TextPart tp = new TextPart();`
`tp.Text = File.ReadAllText(filePath);`
`message.BodyParts.Append(tp);`

or

`MimePart metxt = new MimePart("text", "plain");`
`using (var stream = new FileStream(textSignaturePath, FileMode.Open))`
`    metxt.Content = new MimeContent(stream);`
`message.BodyParts.Append(metxt);`

- What happened?
 Nothing, I got no error but the message did not contain the new BodyPart

- What did you expect to happen?
I expect the message to have the new mime entity appended.

- Step-by-step reproduction instructions and/or a simple test case.
This is the piece of code that I used:

`var message = MimeMessage.Load(((ITextMessage)transaction.Message).Content);`
`TextPart tp = new TextPart();`
`tp.Text = File.ReadAllText(filePath);`
`message.BodyParts.Append(tp);`
`smtp.Send(message, sender, recipients);`

As I got no error, I don't have any log. 
Thank you very much!!

**Comment by jstedfast** [comment]
The `BodyParts` property is an `IEnumerable<MimeEntity>` - you can't Append() to it because it's not a list. It only exists as a convenient way to iterate over all of the body parts of the message.

You need to modify the `Body` property.

Maybe something like this:

```csharp
TextPart tp = new TextPart();
tp.Text = File.ReadAllText(filePath);

Multipart mixed;

// If the top-level body part is a multipart/mixed, then we can "attach" more parts to it, otherwise don't
// modify the multipart and instead create a new multiparty/mixed to add stuff into.
if (message.Body is Multipart multipart && multipart.ContentTYpe.IsMimeType ("multipart", "mixed")) {
    mixed = multipart;
} else {
    // Replace the top-level body part with a new multipart/mixed
    mixed = new Multipart ("mixed");
    mixed.Add (message.Body);
    message.Body = mixed;
}

mixed.Add (tp);
```
