### ISSUE TITLE
Some (PDF-)Files are not readable after sending via MimeKit

### ISSUE THREAD

**Issue by migeold** [jstedfast/MimeKit#598]
Hello,

I observe a strange behavior when sending PDF files via MimeKit.
Most files are transmitted without problems, but few are not readable.
It seems, that Lf is converted into CrLf.
Could this be caused by MimeKit?

OS: Windows 10 2004 (19041.450) 64-Bit
.Net 4.8, WinForms
MimeKit Version: 2.9.0.0
Tested with Email-Provider: gmail.com

I attached 2 files: 'Original.pdf' before and 'Corrupt.pdf' after sending.
Screenshot 'Difference.png' shows the difference.
'Original.pdf' is readable with 'Adobe Acrobat Reader DC 2020.012.20043', 'Corrupt.pdf' not.

Attachment is added with this code:
  var bodyBuilder = new BodyBuilder();
  bodyBuilder.HtmlBody = htmlBody;
  bodyBuilder.Attachments.Add(path);
  mimeMessage.Body = bodyBuilder.ToMessageBody();

Thank you very much for your help!
Michael.

[Original.pdf](https://github.com/jstedfast/MimeKit/files/5122295/Original.pdf)
[Corrupt.pdf](https://github.com/jstedfast/MimeKit/files/5122298/Corrupt.pdf)
![Difference](https://user-images.githubusercontent.com/70150436/91150324-894d3500-e6bc-11ea-894c-490a860bac56.png)

**Comment by jstedfast** [comment]
Try doing this:

```csharp
var attachment = (MImePart) bodyBuilder.Attachments.Add(path);
attachment.ContentTransferEncoding = ContentEncoding.Base64;
```

**Comment by migeold** [comment]
Thank you very much!
Setting the Encoding correctly solved my problem.

**Comment by jstedfast** [comment]
Awesome!

**Comment by jstedfast** [comment]
I've modified the BodyBuilder logic to always use the base64 encoding for non-text attachments.

The problem was that for your particular PDF, since it did not contain any nul-bytes or more than ~17% 8bit bytes, the BodyBuilder chose to encode the PDF using `quoted-printable` which is more efficient size-wise than base64 for your PDF, but the problem is that it's not a great encoding for non-text attachments because of the newline issue you hit.

**Comment by migeold** [comment]
Thanks a lot!
Your update will also help other users with similar problems.
I'm looking forward to the new release.
What do you recommend for attachments in general?
With new version, should we use bodyBuilder.Attachments.Add(path); only? Is your helpful workaround (attachment.ContentTransferEncoding = ContentEncoding.Base64;) obsolete now?

**Comment by jstedfast** [comment]
When I make a new release, you won't need to specify base64. It'll do it for you.
