### ISSUE TITLE
Enumerating through Bodyparts gives strange results for some emails

### ISSUE THREAD

**Issue by McTristan** [jstedfast/MimeKit#599]
**Describe the bug**

It seems the Bodyparts parsing is strangely messed up with some mails. In the Bodyparts collection shows multiple MimeParts including TextParts and images but when I iterate through the collection using the preferred way:

`
foreach (var entity in message.BodyParts)
{
}
`
it returns only the first MimePart for each iteration.

**Platform (please complete the following information):**
 - OS: Windows, Linux, MacOS
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net Core
 - MimeKit Version: 2.9.1

**To Reproduce**
1. Request sample mails via PM
2. load the message via i.e. var message = MimeMessage.Load (stream);
3. Iterate through the BodyParts collection (see error description)
4. look at each entity

**Expected behavior**
Some entities should come up as MimePart of type image/png but all I get is the same TextPart for all iterated entities.

Should look like this:

![image](https://user-images.githubusercontent.com/1064110/91967863-1b37ec00-ed14-11ea-9f48-42276ca83ed7.png)

but instead I get something like this:

Like:
Content-Type: text/plain; charset="iso-8859-1" 
Content-Type: text/plain; charset="iso-8859-1" 
Content-Type: text/plain; charset="iso-8859-1" 
Content-Type: text/plain; charset="iso-8859-1" 
Content-Type: text/plain; charset="iso-8859-1" 
etc.

If you need a mail to test I can send you one.

**Comment by jstedfast** [comment]
I just want to make sure I'm understanding cvorrectly.

Here's my test code:

```csharp
using System;
using System.IO;

using MimeKit;

namespace BodyPartIterator
{
    class Program
    {
        static void Main (string[] args)
        {
            var path = Path.Combine (Environment.GetFolderPath (Environment.SpecialFolder.MyDocuments), "325a8e27-1fcb-46f7-826b-337f5256c2b1.eml");
            var message = MimeMessage.Load (path);

            foreach (var bodyPart in message.BodyParts) {
                Console.WriteLine ($"{bodyPart.ContentType}");
            }

            Console.ReadKey ();
        }
    }
}
```

The output of this is:

```
Content-Type: text/plain; charset="iso-8859-1"
Content-Type: text/html; charset="iso-8859-1"
Content-Type: image/png; name="fb_tz_f184f22a-60c5-464d-b303-785840a353ad.png"
Content-Type: image/png; name="SocialLink_Facebook_32x32_c8649903-4104-4fc4-9e1c-b42dd8922cf4.png"
Content-Type: image/png; name="SocialLink_Linkedin_32x32_7b1e97c0-f25f-44d3-8c86-2fed74fe442e.png"
Content-Type: image/png; name="SocialLink_Twitter_32x32_6dd375b9-87e4-4137-9329-137c2857ad38.png"
Content-Type: image/png; name="SocialLink_Instagram_32x32_79b9eb0a-adc9-42db-a360-412b6a294172.png"
Content-Type: image/png; name="fb_tz_f184f22a-60c5-464d-b303-785840a353ad.png"
Content-Type: image/png; name="SocialLink_Facebook_32x32_c8649903-4104-4fc4-9e1c-b42dd8922cf4.png"
Content-Type: image/png; name="SocialLink_Linkedin_32x32_7b1e97c0-f25f-44d3-8c86-2fed74fe442e.png"
Content-Type: image/png; name="SocialLink_Twitter_32x32_6dd375b9-87e4-4137-9329-137c2857ad38.png"
Content-Type: image/png; name="SocialLink_Instagram_32x32_79b9eb0a-adc9-42db-a360-412b6a294172.png"
```

What am I doing differently?

**Comment by McTristan** [comment]
nothing. hmm ... in a new console application it works, copying the above mentioned lines into my existing code it produces this weird output. The only difference is that I used it in a ASP.NET Core controller method. I guess I have to dig deeper. As the error seems to to be on our side I'll close this issue. Thank you for testing!

**Comment by jstedfast** [comment]
No problem! Good luck with debugging this issue.
