### ISSUE TITLE
Raw Message Download - part of first line seems to be missing

### ISSUE THREAD

**Issue by AllanStead** [jstedfast/MimeKit#602]
Good Morning Jeffrey

I've written a Visual Basic program, to allow me to view incoming messages before opening them in Thunderbird, so I can delete any with suspect attachments, before Thunderbird has had a chance to open them and possibly get my computer infected by auto-reading them.

I've previously done the reading using OpenPop, but recently this has been unable to deal with some encodings, so I switched to MailKit - so far so good, and thank you.

I would like to be able to view any message in its raw form, so I created a function using GetMessage to do so.  OneAccount is a class containing Password, Server etc. 

  Dim Client As New MailKit.Net.Imap.ImapClient

        Try
            Client.Connect(OneAccount.Server, 0, OneAccount.UseSSL)
            Client.Authenticate(OneAccount.UserName, OneAccount.Password)
            Client.Inbox.Open(MailKit.FolderAccess.ReadOnly)

            Return Client.Inbox.GetMessage(UniqueId)

            Client.Disconnect(True)
        Catch ex As Exception
            MessageBox.Show(ex.Message)
            Return Nothing
        End Try

The MimeKit.MimeMessage returned by the function, when converted to text, shows almost all of the raw message, except that if the first line begins with Return-Path: then that is all I see, followed by the rest of the raw message.  Asking Thunderbird to View Source for the same message, shows the first line as being Return-Path: <milwardsue@gmail.com> and the rest of the raw message follows.  Am I doing something wrong?

Best Regards
Allan Stead

**Comment by jstedfast** [comment]
Try getting a protocol log (https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) to see what the raw message source fetched from the server looks like.

**Comment by AllanStead** [comment]
Return-Path: shows up complete with an address in the ProtocolLog file, so maybe I would do better getting the raw message source from the log file, and then stripping out all of the top part of the file, and the S: at the beginning of each line of the raw message.

Strangely, it seems that if the first line of the raw message source is anything other than Return-Path: then my function returns all of the first line perfectly, along with the rest of the raw message source.

Bye for now
Allan

**Comment by jstedfast** [comment]
How are you displaying the message? Something is probably wrong with that code.

**Comment by jstedfast** [comment]
Can you send me a sample message that has this problem (zipped because my Outlook client mangles message attachments) and provide the code snippet you are using to convert the message into text in order to "display" it?

I've got hundreds of unit tests that test this stuff and none of them are encountering this problem, so either the message is hitting some corner-case in MimeKit's parser or serialization logic or else something is broken in your code to convert the message to text. I can't know which it is until I have some more information.

**Comment by AllanStead** [comment]
Good Evening Jeffrey
Oh, dear, it's egg-on-face time (egg on my face, that is).  Your point about my code for displaying the message was quite right.  I use a browser to display the message in HTML, as a convenient way of having a display where I can either re-size the window, or zoom in for a larger font size, and I'd quite forgotten that HTML will try to interpret the angled brackets of an e-mail address, as an HTML tag such as <br> and being unable to do anything with an email address, will just discard it.

Here's the VB code I use to display the text, except that although I had the Replace to substitute <br> for vbCrLf, I'd forgotten the Replace lines for the angled brackets.  BeginHTML and EndHTML are separate subroutines to put the <head> section at the top, and to close off the <body> section at the bottom.  SB is a StringBuilder, used to accumulate lines of text.

Dim RawMessage As String

        RawMessage = MessageFromUniqueIdMailKitImap(RightClickedMessageTag.Account, RightClickedMessageTag.UniqueId).ToString

        RawMessage = RawMessage.Replace("<", "&lt;")
        RawMessage = RawMessage.Replace(">", "&gt;")
        RawMessage = RawMessage.Replace(vbCrLf, "<br>")

        SB.Clear()
        BeginHTML("Entire Message")
        SB.AppendLine(RawMessage)
        EndHTML()

        ' Write to file
        Using Writer As IO.StreamWriter = New IO.StreamWriter(HtmlOutputFilePath)
            Writer.Write(SB.ToString)
        End Using

        ' Display using default browser
        Process.Start(HtmlOutputFilePath)

  Many thanks for pointing me in the right direction, and I'm sorry to have troubled you.

Best Regards
Allan Stead
Newton Abbot, Devon, England
