### ISSUE TITLE
When message is moved from / to INBOX is not working

### ISSUE THREAD

**Issue by educrocha** [jstedfast/MimeKit#603]
Hi everyone, my code is working fine, but I noticed something: When I remove the message from INBOX to other folder and turned back to INBOX, the message is not localized.

datetime fDt = DateTime.Now.AddDays(-1); // Get last day
var fUIDLista = fClienteIMAP.Inbox.Search(SearchQuery.DeliveredOn(fDt));

I'm using C# and MemeKit 2.9

**Comment by jstedfast** [comment]
I don't know what this means. Can you explain?

**Comment by educrocha** [comment]
> I don't know what this means. Can you explain?

Imagine you have 10 messages in the INBOX folder. Running the code, will find 10 messages like expected. Now, move all this messages to other folder and run the code, will not find message, because there's no message in the folder INBOX, and it's OK, the code is to find message in the folder INBOX. Now, third step, back all message to INBOX and run the code and now, the code will not find message, despiste have 10 message in the INBOX folder.

**Comment by jstedfast** [comment]
Sounds like you should take this up with the server developers. This doesn't sound like an issue with MailKit.
