### ISSUE TITLE
Attachment missing in Windows 10 Mail client when using BodyBuilder class

### ISSUE THREAD

**Issue by jiswo** [jstedfast/MimeKit#604]
**Describe the bug**
When I use the BodyBuilder class to create a mailmessage the recipients of the mail that are using the Windows 10 Mail client do not received added attachments when there are also linkedresources added to the message.

**Platform (please complete the following information):**
I'm using windows 10 in development and windows 2012 server in production with asp.net v4.7

**To Reproduce**
Create an html email with combination a linkedresource and an attachment via the BodyBuilder class.

**Expected behavior**
Inline image visible in mail and attachment visible.

**Code example**

            var builder = new BodyBuilder();

            if (mailitem.FileAttachments != null)
            {
                foreach (var item in mailitem.FileAttachments)
                {
                    if (item.FileContent == null)
                        continue;

                    item.FileContent.Position = 0;

                    var filename = string.IsNullOrWhiteSpace(item.Filename) ? "unknown" : item.Filename;

                    if (item.IsInlineAttachment)
                    {
                        var image = (MimePart)builder.LinkedResources.Add(filename, item.FileContent);
                        image.ContentTransferEncoding = ContentEncoding.Base64;
                        image.ContentId = item.InlineId;
                    }
                    else
                    {
                        builder.Attachments.Add(filename, item.FileContent, ContentType.Parse(item.MediaType));
                    }
                }
            }

            if (mailitem.IsHtmlMail)
            {
                builder.TextBody = Utils.RemoveHtmlTags(mailitem.Bodytext);
                builder.HtmlBody = mailitem.Bodytext;
            }
            else
            {
                builder.TextBody = mailitem.Bodytext;
            }

            message.Body = builder.ToMessageBody();

**Comment by jstedfast** [comment]
But the message shows attachments in other email clients? Sounds like a bug in Windows 10 Mail. I can't do anything about that.

Maybe try setting a Content-Id on the normal attachments as well in that case? The best I can suggest is to find a message with the same sort of structure that you are trying to produce that works with Windows 10 Mail and see what MIME headers are set on those attachments and then make sure the same headers are set when you construct a message using MimeKit.

The easiest way to do this would probably be to generate a message with an HTML body and inline images + some regular file attachments in Windows 10 Mail's message composer and send it to yourself and then look at the raw MIME.

**Comment by jiswo** [comment]
For now I solved the problem by not using the BodyBuilder class and adding the mime parts manualy as described [here](http://www.mimekit.net/docs/html/Creating-Messages.htm). My guess was that if it works like that the BodyBuilder class is handling mimeparts in another way what could be the issue here.

**Comment by jstedfast** [comment]
Can you at least paste a sample message that was generated by the BodyBuilder and what you are generating manually? There should be no difference between what the BodyBuilder generates and the code in the Creating Messages documentation.

**Comment by jiswo** [comment]
Can I send you an email you with 2 example files?

**Comment by jstedfast** [comment]
yes, but please zip them up - Outlook won't let me view them properly otherwise.

**Comment by jiswo** [comment]
ok, email sent

**Comment by jstedfast** [comment]
Okay, so, BodyBuilder is generating the following message structure:

```
multipart/mixed
    multipart/alternative
        text/plain
        multipart/related
            text/html
            image/jpeg
    application/pdf
```

And when you manually construct the message, the structure is:

```
multipart/mixed
    multipart/alternative
        text/plain
        text/html
    image/jpeg
    application/pdf
```

Technically, your manually constructed message structure is wrong and the BodyBuilder structure is correct. But I guess use whatever works with the mail client you are sending to.

TO generate the same structure using the BodyBuilder, you would just change your original code snippet to this:

```csharp
        var builder = new BodyBuilder();

        if (mailitem.FileAttachments != null)
        {
            foreach (var item in mailitem.FileAttachments)
            {
                if (item.FileContent == null)
                    continue;

                item.FileContent.Position = 0;

                var filename = string.IsNullOrWhiteSpace(item.Filename) ? "unknown" : item.Filename;

                if (item.IsInlineAttachment)
                {
                    var image = (MimePart)builder.Attachments.Add(filename, item.FileContent);
                    image.ContentDisposition.Disposition = ContentDisposition.Inline;
                    image.ContentTransferEncoding = ContentEncoding.Base64;
                    image.ContentId = item.InlineId;
                }
                else
                {
                    builder.Attachments.Add(filename, item.FileContent, ContentType.Parse(item.MediaType));
                }
            }
        }

        if (mailitem.IsHtmlMail)
        {
            builder.TextBody = Utils.RemoveHtmlTags(mailitem.Bodytext);
            builder.HtmlBody = mailitem.Bodytext;
        }
        else
        {
            builder.TextBody = mailitem.Bodytext;
        }

        message.Body = builder.ToMessageBody();
```

**Comment by jiswo** [comment]
Ok, so it's definitely a bug in Windows 10 Mail. Thank you for your time and great support!
