### ISSUE TITLE
EML generated with attachments wasn´t not showed on IOS Mail 13.

### ISSUE THREAD

**Issue by reinaldocoelho** [jstedfast/MimeKit#606]
**Describe the bug**
When sent emails generated with MimeMessage and sent to IPhone with IOS 13, the email show the attachment clip, but not permit to download the attachment.

**Platform (please complete the following information):**
 - OS: Generated EML on Windows, and View on IOS IPhone (Version 13)
 - .NET Runtime: CoreCLR
 - .NET Framework: dotnet core 3.1
 - MimeKit Version: 2.8.0 / 2.9.2
 - MailKit Version: 2.7.0 / 2.9.0

**To Reproduce**
1. Create an MimeMessage insert an PDF as attachment.
2. Sent (with gmail smtp) to an Hotmail/Office365 and use this on IPhone Mail.
3. Look to Hotmail/Office365 and look that contains the PDF attached.
4. Open IPhone IOS (version 13) and it´s not present the PDF download link.

To compare, if sent an same email direct by gmail, the attachment was present on IPhone.

**Expected behavior**
That email sent on open on IPhone present the Attachment file.

**Screenshots**
Below follow the Gmail and Mimekit looked from IOS.
Gmail EML received:
![Gmail-Sent](https://user-images.githubusercontent.com/889634/93374749-8b269600-f82d-11ea-8463-5688fead2170.png)
Mimekit EML received:
![MailKit-Sent](https://user-images.githubusercontent.com/889634/93374754-8c57c300-f82d-11ea-8909-f2e2efd4ba7d.png)

**Additional context**
Attached also two EMLs to compare, received from GMAIL and from Mimekit.

Emls received on hotmail/office365 (Can´t get from IPhone)
[Emls.zip](https://github.com/jstedfast/MimeKit/files/5234147/Emls.zip)

**Comment by jstedfast** [comment]
You have a couple of potential issues:

1. The message you sent via MailKit uses a top-level `multipart/related` instead of `multipart/mixed` like the GMail message uses.
2. 
```
Content-Disposition: attachment; filename=Vim-Cheat-Sheet-pt_br.pdf;
size=155919; Content-ID="<1600279728>"; X-Attachment-Id=1600279728
```

That should be:

```
Content-Disposition: attachment; filename=Vim-Cheat-Sheet-pt_br.pdf;
size=155919;
Content-ID: <1600279728>
X-Attachment-Id: 1600279728
```

In other words, you are adding the `Content-ID` and `X-Attachment-Id` values as `Content-Disposition` parameters instead of adding them as headers.

Instead of doing this:

```csharp
attachment.ContentDisposition.Parameters.Add ("Content-ID", "<1600279728>");
attachment.ContentDisposition.Parameters.Add ("X-Attachment-Id", "1600279728");
```

Do this:

```csharp
attachment.ContentId = "<1600279728>";
attachment.Headers.Add ("X-Attachment-Id", "1600279728");
```

Hope that helps.

**Comment by reinaldocoelho** [comment]
Hi @jstedfast, I was testing here and found the problem.
It´s worked when change to "multipart/mixed".
Sorry, I´m not saw that before!

Thank you.

**Comment by jstedfast** [comment]
No worries. Glad to help!

Make sure you change how you set the Content-ID and X-Attachment-Id as well.

**Comment by reinaldocoelho** [comment]
Ok, thanks.
