### ISSUE TITLE
Adding attachment raises "X-MimeKit-Warning: Do NOT use ToString() to serialize entities"

### ISSUE THREAD

**Issue by nitmws** [jstedfast/MimeKit#607]
**Describe the bug**
Adding an attachment with a file name results in this message: X-MimeKit-Warning: Do NOT use ToString() to serialize entities.
But the attachment was added as shown in the documentation, no explicit use of ToString():
builder.Attachments.Add (@"C:\a-file-name.txt");

**Platform (please complete the following information):**
 - OS: Windows 10, 2004
 - .NET Runtime: 
 - .NET Framework: .NET 4.5
 - MimeKit Version: 2.9.2

**To Reproduce**
1. Create Powershell 5.1 script
2. Add-Type MimeKit and MailKit and Portable.BouncyCastle
3. use in the script: $bodyBuilder.Attachments.Add(@"C:\a-file-name.txt")
4. The warning is raised
5. If no attachment is added not warning is raised

**Expected behavior**
No warning should be raised as my script does not use the ToString() function

**Screenshots**
(none)

**Additional context**
(none)

**Comment by jstedfast** [comment]
That's because PowerShell uses ToSTring() to print out the attachment added in the Add method. It's not permanently added.
