### ISSUE TITLE
Any way of considering the DateTime when performing DeliveredAfter

### ISSUE THREAD

**Issue by advapiIT** [jstedfast/MimeKit#608]
Hello,
I've noticed (before reading the comment) that when performing the DeliveredAfter the time part is not considered... I've a window service that looks for emails that have not been processed... is there a way I can take the time part ?

my current code is
``
  if (minDate.HasValue)
                    seachQuery = seachQuery.And(MailKit.Search.SearchQuery.DeliveredAfter(minDate.Value));
```

But if considers me all the item that I've received from midnight.

Is there also a way to understand via MailKit which is the current IMAP server Timezone?

Thanks in advance
Paolo

**Comment by jstedfast** [comment]
No, this is a limitation of the IMAP protocol and so I can't work around it.
