### ISSUE TITLE
Garbled character

### ISSUE THREAD

**Issue by billpeace** [jstedfast/MimeKit#609]
Hello! Please, Help!
I'm trying to parse eml file and get Garbled character.

MimeMessage message = MimeMessage.Load("test.eml");

test.eml is in test.zip
[test.zip](https://github.com/jstedfast/MimeKit/files/5330764/test.zip)

error parse
![error parse](https://user-images.githubusercontent.com/372286/95145500-f4a32000-07ad-11eb-80a4-05bd785bb041.png)

Correct Info
![Correct](https://user-images.githubusercontent.com/372286/95145253-5adb7300-07ad-11eb-9834-2a41946a4331.png)

Thank you a lot!

**Comment by jstedfast** [comment]
The body charset is either not specified or it is specified incorrectly. You can use http://www.mimekit.net/docs/html/M_MimeKit_TextPart_GetText_1.htm to override the character encoding if you know what it's supposed to be.
