### ISSUE TITLE
CreateAttachment can throw if filename contains characters legal in email but illegal in paths (<>"|)

### ISSUE THREAD

**Issue by WaldenL** [jstedfast/MimeKit#615]
**Describe the bug**
AttachmentCollection's CreateAttachment method can throw when the fileName passed contains characters that are illegal in a path, but still perfectly legal in an email attachment name. Specifically, less-than, greater-than, double-quote, or pipe (<, >, ", |). 

This happens inside the Path.GetFileName call as Microsoft feels compelled to confirm the pathName provided is 'valid' even though that's irrelevant to getting the filename. By the time the file name gets to the CreateAttachment call there's already a stream provided for the bytes, so the filename is only relevant for constructing the mail headers. There's no reason to validate the path validity. And in cases where the "file" is already coming from a database it's not unlikely that the "filename" could be something like "Informed Consent for subjects < 18 yrs.docx" since the file isn't really stored in a filesystem anyway. 

**Platform (please complete the following information):**
 - OS: Detected on Windows -- would likely happen anywhere using the BCL
 - .NET Runtime: Framework 4.8
 - .NET Framework: .NET 4.8
 - MimeKit Version: Noticed at 2.5.1.0, confirmed in source at current commit (f54a1c6)

**To Reproduce**
1) Attempt to add an attachment with one of the invalid characters in the name. 

**Expected behavior**
Attachment should be added.

**Screenshots**
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at MimeKit.AttachmentCollection.CreateAttachment(ContentType contentType, String fileName, Stream stream)
   at MimeKit.AttachmentCollection.Add(String fileName, Stream stream, ContentType contentType)
   at ... (application code) 

**Additional context**
Yes, the receiving email client will need to sanitize that file name before saving locally if illegal path names are included, but email clients and browsers do this all the time. The sending system shouldn't place these restrictions on the file name.

**Comment by WaldenL** [comment]
I'm willing to write the fix if you agree it should be fixed, but figured we'd discuss here first. 

I think it's likely as simple as replacing the calls to Path.GetFileName with a custom method that does what GetFileName does w/out checking for the path validity. It would not be copy/paste from reference source due to copyright, but it's effectively a copy/paste w/out the call.

**Comment by jstedfast** [comment]
The simple solution would be to backtrack from the end of the path looking for Path.DirectorySeparatorChar.

**Comment by WaldenL** [comment]
... or you could just fix the issue in less than 24 hours. Amazing, thanks. 👍👍

**Comment by jstedfast** [comment]
Haha, that's how I like to party ;-)
