### ISSUE TITLE
Thread-safety information

### ISSUE THREAD

**Issue by atheken** [jstedfast/MimeKit#617]
We are in the process of including MimeKit and MailKit in our sending pipeline. We intend to use DKIM Signing as part of sending, but would like to reuse signers if possible.

A cursory review of the code suggests that the dkim signer _should_ be thread-safe (class hierarchy does not appear to mutate internal state). The one area that may not be thread safe is the actual loading/use of the private key.

Is it possible for you to provide information about the thread-safety of classes? Even basic information about whether the classes are intended to be used/reused in a multi-threaded environment would be helpful.

**Comment by jstedfast** [comment]
The dkim signer is thread-safe and the use of the private key will not modify the state of the private key.

I don't have the thread-safety information written down anywhere for every class and it would take me days (if not weeks or more) to compile such a list, but the general rule is that classes are thread-safe unless you are explicitly changing properties on the object. The only exception I know of is MimeMessage.WriteTo() which *can* modify internal state.

BTW, greetings from another Philadelphian ;-)

**Comment by jstedfast** [comment]
Oh, MimeParser and the TnefReader classes are definitely not thread-safe ;-)

Those were probably obvious, but I figured I'd mention those.

OpenPgpContext (and GnuPGContext which is a subclass) and the BouncyCastleSecureMimeContext (and subclasses) are also probably not thread-safe. Same with the Sql*CertificateDatabase classes.
