### ISSUE TITLE
Integrate with linux sendmail

### ISSUE THREAD

**Issue by JohnKiller** [jstedfast/MimeKit#621]
**Is your feature request related to a problem? Please describe.**
PHP has native support for sendmail. Other big projects like Gitea (written in Go) supports it. However, I haven't found any .NET package that supports it.

**Describe the solution you'd like**
I would like to send a mail without SMTP but talking directly to the sendmail binary on linux systems

I have tried to implement this by myself: https://github.com/JohnKiller/MimeKitToPostFix

The code is pretty simple, but it has a nasty bug: on stderr it prints an error:

    sendmail: fatal: root(0): No recipient addresses found in message header

I have tried getting some help on reddit https://www.reddit.com/r/csharp/comments/jy97so/writing_to_stdin_using_sendmail_with_net_core_on/

Have you got any suggestions? Is this a thing you would consider implementing? Thanks

**Comment by JohnKiller** [comment]
OK just found that I was calling .Start twice, so the only question remains: could this be integrated in your library?

**Comment by jstedfast** [comment]
I'd really prefer not to add Sendmail support to MimeKit. It's a very platform-specific thing and I don't have a Linux machine to test any implementation I write to make sure it all works.
