### ISSUE TITLE
Mimekit and ITextSharp

### ISSUE THREAD

**Issue by James-Treacy** [jstedfast/MimeKit#625]
Hi not really an issue but I have managed to avoid using an app.config file for many years with Mimekit, Mailkit and ITextSharp.

Now with version 2.10 of Mailkit/Mimekit and ITextSharp 5.5.13.2 it seems I must now use this kludge:

<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">      
      <dependentAssembly>
        <assemblyIdentity name="BouncyCastle.Crypto" publicKeyToken="0e99375e54769942" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.8.8.0" newVersion="1.8.8.0" />
      </dependentAssembly>
    </assemblyBinding>

You know better than I do that your code relies on Portable Bouncy Castle 1.8.8 but ITextSharp relies on 1.8.6.1.  Here is my packages.config file:
<packages>
  <package id="BouncyCastle" version="1.8.6.1" targetFramework="net452" />
  <package id="iTextSharp" version="5.5.13.2" targetFramework="net452" />
  <package id="MailKit" version="2.10.0" targetFramework="net452" />
  <package id="MimeKit" version="2.10.0" targetFramework="net452" />
  <package id="Portable.BouncyCastle" version="1.8.8" targetFramework="net452" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net452" />
  <package id="System.Data.DataSetExtensions" version="4.5.0" targetFramework="net452" />
</packages>

Do you know any way I can avoid using an app.config file when using the latest Mailkit Mimekit and ITextsharp?  I hate having to do this.

Thanks, I have been a donor and your software is superb.
Cheers
James Treacy
james.treacy@dataline.com.au

**Comment by James-Treacy** [comment]
![MyAppConfig](https://user-images.githubusercontent.com/75097847/100393394-926bea80-308d-11eb-9d5b-18a03e94cf7f.png)

**Comment by James-Treacy** [comment]
oops didn't mean to close this.  If the answer is bad luck you need the app.config file, then ok.  Just looking for a more elegant solution as I don't like having to include a .exe.config file for people to fiddle with and break the application.

**Comment by jstedfast** [comment]
Honestly, I'm not really sure.

**Comment by jstedfast** [comment]
I'm going to close this because I don't think there's anything I can do. Maybe you can ask iTextSharp to bump their Portabnle.BouncyCastle dependency to 1.8.8?
