### ISSUE TITLE
Blazor and System.Net.NetworkInformation is not supported on this platform.

### ISSUE THREAD

**Issue by jrhodnik** [jstedfast/MimeKit#630]
**Describe the bug**
In Blazor WASM, when constructing a new MimeMessage, a call to `MimeKit.Utils.MimeUtils.GenerateMessageId()` is made, which in turn calls `System.Net.NetworkInformation.IPGlobalProperties.GetIPGlobalProperties()`. This results in an exception being thrown: `System.PlatformNotSupportedException: System.Net.NetworkInformation is not supported on this platform.` I'm not sure what the best solution to this issue would be. I understand that using MimeKit in Blasor WASM isn't common place but I figured I should submit this just in case. 

**Platform (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS, iOS, Android, Windows Phone, etc.]
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: [e.g. .Net Core, .NET 4.5, UWP, etc.]
 - MimeKit Version: 

**To Reproduce**
Attempt to construct a `MimeMessage` in Blazor WASM.

**Expected behavior**
Getting a new `MimeMessage`.

**Comment by jstedfast** [comment]
Do you know what .NET framework (or .NET Core framework) version is needed for WASM? If not, what framework does your app target?

**Comment by jrhodnik** [comment]
The projects I've been working on most recently are based on .NET 5.0 `<TargetFramework>net5.0</TargetFramework>`. Previously WASM was using `<TargetFramework>netstandard2.1</TargetFramework>`.

Thanks a ton!

**Comment by jstedfast** [comment]
I *think* I'm going to have to just catch exceptions and fall back to a hard-coded hostname string since net5 and netstandard2.1 have those APIs, I guess they just throw PlatformNotSupportedException when used with WASM.

If you can, give the [myget](https://www.myget.org/feed/mimekit/package/nuget/MimeKit) packages a try (should end up being v2.10.1.10)
