### ISSUE TITLE
BodyBuilder - Add ability to use byte[] / Stream instead of raw text

### ISSUE THREAD

**Issue by kislovs** [jstedfast/MimeKit#642]
Currently [BodyBuilder](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/BodyBuilder.cs) wants only `string` for [TextBody](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/BodyBuilder.cs#L94) and [HtmlBody](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/BodyBuilder.cs#L108). In my scenario, I have `byte[]` on my hands, I don't want to use `Encoding.UTF8.GetString(data)`, because [here in TextPart](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/TextPart.cs#L496) it uses `encoding.GetBytes(string)` (`encdoing == Encoding.UTF8` by default).

I wanted to rewrite my code to use `BodyBuilder`, but in my pretty load application I don't want to do such allocations, especially for html-s which could be pretty large.. 😢 I'm not sure, maybe there are other places which accept only `string` and cast it to `byte[]` as well, add such ability there too looks nice.

**Comment by jstedfast** [comment]
I'm not sure how I would add this functionality. Honestly, it sounds like it would be better for you to just build the MIME structure manually (it's fairly simple to do). BodyBuilder is kind of meant for simple cases.

**Comment by kislovs** [comment]
Yeah, I did it that way (copy-paste `BodyBuilder` build method and adapt to my entities). It just seems as ideal to have it in library and adapt `BodyBuilder` to use that more general method. :)
