### ISSUE TITLE
Empty attachment with wrong size

### ISSUE THREAD

**Issue by rqueizan** [jstedfast/MimeKit#646]
**Describe the bug**
In previous versions of the library, when an empty attachment (without content) was read, it came with zero size.
Previous Version: MailKit: 2.8.0, MimeKit: 2.9.1
In the new versions it returns with the size between 1 and 2 bytes (octets).
New Version: MailKit: 2.10.0-2.10.1, MimeKit: 2.10.0-2.10.1

I detect the bug when run the test that cover that scenary.

**Platform (please complete the following information):**
 - OS: Windows 10 x64
 - .NET Runtime: net core app
 - .NET Framework: Net Core 2.0 (Target Framework)
 - MailKit Version: 2.10.0-2.10.1, MimeKit Version: 2.10.0-2.10.1

**To Reproduce**
1. I sent an email with empty attachment.
2. When read the email, the attachment report size greather than zero.
3. When download de attachment, the size indicate that is greather than zero.

**Expected behavior**
The size of an empty attachment must be zero.

**Comment by jstedfast** [comment]
Okay, so my local test case was broken and now that I fixed it, I'm getting 2 blank lines. But I think that's still ok. The issue you are having is that you are getting 3 blank lines and I still can't figure out how that is happening for you.

**Comment by jstedfast** [comment]
Does your empty.png have a newline in it? Or is it a 0-length file?

**Comment by jstedfast** [comment]
Ok, so when using the BodyBuilder, I can reproduce this...

**Comment by jstedfast** [comment]
Ah, ok, so in 2.9.0, I made the BodyBuilder.Attachments.Add() method always set the Content-Transfer-ENcoding to base64 for non-text content (based on mime-type), so the empty.png attachment went from not having an encoding to having an encoding.

The base64 encoder would always flush the content with a new-line sequence, even if the content that was base64 encoded was 0-length.

**Comment by rqueizan** [comment]
See my code, how I build and send the email.
I send an empty Stream, 0-length.
I use the body builder.
![008](https://user-images.githubusercontent.com/18214796/105207809-fa7f0000-5b15-11eb-9460-4142158968a7.png)
![007](https://user-images.githubusercontent.com/18214796/105207817-fce15a00-5b15-11eb-9891-33ba5a301518.png)
![006](https://user-images.githubusercontent.com/18214796/105207819-fd79f080-5b15-11eb-89c6-a4f3eadc8488.png)
![005](https://user-images.githubusercontent.com/18214796/105207822-fe128700-5b15-11eb-8345-d7aa128ba783.png)

**Comment by jstedfast** [comment]
Yep, my patch fixes that issue.
