### ISSUE TITLE
using MimeParser with .NET Core HttpRequest.Body

### ISSUE THREAD

**Issue by adamfoneil** [jstedfast/MimeKit#648]
Hi there, I'm trying to implement an email parse Azure function that receives a webhook post from SendGrid via their Inbound Parse feature. I want to use MimeKit to parse the incoming message, but I'm getting an error "failed to parse message headers." I just found your package this morning, and I'm kinda of a newbie in this area anyway. So I have a lot of ignorance going in!

![image](https://user-images.githubusercontent.com/4549398/105610578-4fbd4a80-5d7e-11eb-8b71-5c31ed13c917.png)

I was hoping it would be as simple as newing up a `MimeParser` around the `HttpRequest.Body` like this. What I want to do is capture an .eml file from the `HttpRequest` and save it in Azure blob storage.

```csharp
private static async Task WriteMimeBlobAsync(
	HttpRequest request, ILogger log, 
	string connectionString, string containerName, string blobName, 
	[CallerMemberName]string callerName = null)
{
	try
	{
		var parser = new MimeParser(request.Body);
		var msg = await parser.ParseMessageAsync();

		var blobClient = new BlobClient(connectionString, containerName, blobName + ".eml");
		using (var ms = new MemoryStream())
		{
			await msg.WriteToAsync(ms);
			await blobClient.UploadAsync(ms);
		}
		log.LogInformation($"Created blob {blobName} from MimeParser");
	}
	catch (Exception exc)
	{
		log.LogError($"{callerName}: {exc.Message}");
	}
}
```

In SendGrid, I have it setup to "post raw, full MIME message" -- I tried it with and without that option. Do you have any idea what I'm doing wrong? My thought is that maybe I need to pull something more specific out of the `request.Body` but I don't know what that would be. Any ideas you have are much appreciated!

![image](https://user-images.githubusercontent.com/4549398/105610716-10432e00-5d7f-11eb-927f-43ee1476f71b.png)

**Comment by jstedfast** [comment]
I'm not really familiar with what HTTP request data that SendGrid will send in its webhooks.

I would recommend printing the raw HTTP POST request body to see what's in there. Doe sit include the MIME/message headers? Or is it just the body of the message? Is it json? (everything loves json these days)

If the problem is that the HTTP request body is missing the MIME/message headers, then you may need to do something similar to this: https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#ParseWebRequestFormData

**Comment by adamfoneil** [comment]
Thanks for looking at this.
Here's an example of raw post from SendGrid
https://github.com/adamfoneil/Sendhook/blob/master/LocalParser/Samples/e060409e-d8b7-439d-a12f-7fa43d4424af.txt
I looked at your suggestion with `MimeEntity.Load` but had the same error

**Comment by adamfoneil** [comment]
okay I kinda figured this out :-)
the SendGrid payload has extra stuff that is not really what I want to parse. The idea here is to drill down to the part that's really the Mime message. I wrote a [custom json serializer](https://github.com/adamfoneil/Sendhook/blob/master/Sendhook.Function/JsonConverters/FormCollectionConverter.cs) to capture the `IFormCollection` posted by SendGrid. This let me isolate the portion that was really the content I was after.

![image](https://user-images.githubusercontent.com/4549398/105615155-6a9eb780-5d9c-11eb-8e65-e1b756f66fad.png)
