### ISSUE TITLE
TNEF Exchange email

### ISSUE THREAD

**Issue by biancapop** [jstedfast/MimeKit#650]
Hello,
First of all I don't think this is a bug but I am not able to solve it by myself. I read all the documentation and the issues that other people opend about it but I cant make it work.

Let me explain myself.  I have to parse some exchange emails and I recive all of them in TNEF. I cannot disable TNEF in Exchange because some emails, like the TODO mails won't work properly.

I want to decode the mail and be able to analyse it, and I was wandering if the email could be encoded again before sending it.

I recive and load the email with the following line of code:
`var message = MimeMessage.Load(new ParserOptions() { CharsetEncoding = Encoding.UTF8 }, ((ITextMessage)transaction.Message).Content);
`

And this is the body of the email:
`{Content-Type: multipart/mixed;`
`     boundary="----=_NextPart_000_0012_01D6F89A.CA579DC0"`
`Content-Language: es`
``
`This is a multipart message in MIME format.`
``
`------=_NextPart_000_0012_01D6F89A.CA579DC0`
`Content-Type: text/plain;`
`     charset="us-ascii"`
`Content-Transfer-Encoding: 7bit`
``
``
``
`------=_NextPart_000_0012_01D6F89A.CA579DC0`
`Content-Type: application/ms-tnef;`
`     name="winmail.dat"`
`Content-Transfer-Encoding: base64`
`Content-Disposition: attachment;`
`     filename="winmail.dat"`
``
`eJ8+IiMMAQaQCAAEAAAAAAABAAEAAQeQBgAIAAAA5AQAAAAAAADoAAEIgAcAGAAAAElQTS5NaWNy`
`b3NvZnQgTWFpbC5Ob3RlADEIAQOQBgAEEQAAJwAAAAsAAgABAAAAAwAmAAAAAAALACkAAAAAAB4A`
`cAABAAAABAAAAGVlZQACAXEAAQAAABYAAAAB1viSZNqBrD1UFFFFQLtymB0fPu+QAAALAAEOAAAA`
`AAIBCg4BAAAAGAAAAAAAAADoiRINBknDTYRNIYfSqvMkwoAAAAMAFA4BAAAAHgAoDgEAAAA1AAAA`
`MDAwMDAwMDcBQUdFTlRFQFNUQU1QWU1BSUwuQ09NAWFnZW50ZUBzdGFtcHltYWlsLmNvbQAAAAAe`
`ACkOAQAAADUAAAAwMDAwMDAwNwFBR0VOVEVAU1RBTVBZTUFJTC5DT00BYWdlbnRlQHN0YW1weW1h`
`aWwuY29tAAAAAAIBCRABAAAALg0AACoNAAAfKQAATFpGdbYzCFgHAAYBAQtgbmcxMDJmNQBkAHJj`
`cA3QDgAyBQxgYw1EZjMxNTBCNwD1c3RzaAVwYnRjaA/SNhCECQARC2gzDrARGmJpD9cNojMwJjgP`
`IA11ZmUUo3RofmUHgBRnFdcVYAFAFddjznMB6AKkE7BkaQM2AgAjEQAKwHNldALRcHKUcTIAACoK`
`oW5vGlBmIA3wG6E2MBSgD/A0ZxwhAdAUoDR9B20CgzM+NBkfGi8bNiDvIRB9Q+5hBtAHIQXQYRXQ`
`HeQQEP8eZgPjHz8bCwEwHHIbshxQ5xSgJqEiIWxpImEd5A/h/xkPJG8bLxw/HU4P4QBQKG//KX8q`
`jyufLK8PICN/Lu8lmQcm4iaPBRAgTGlnaPp0J7czLc80Ty/vMP8yD/87sDiPOZ86rzu/PM9BAD3/`
`/z8PQB9BL0I/EVEzT0SPJZ//Nn8ntyNYQ/9Kf0YfRy8Cg5g0NjhNz07UMjNTAUVPYiAHbSBDRVKV`
`OZ9TH1QlPdJU31XjeXJSlOY3Lb9OxTE2WnFYjwOC+kcJ0WtaBTMoWx4zIVxPvQOCVAhwWgU4f1uG`
`NyNRY2AvA4IoSGUiYAfQKf9aBT3vYydUr2TGBxABoA6wd2WmQ19bhjhIwWf/A4JC/QdAdA6wWgVI`
`yFseYhFsD2Vk81YIkHRuIkAHkGX9ZaQ4FLBuP1QuIjpWFnJQz1a/V890nFnlODFaf1uP/3SbXZh5`
`YF5fX290m2F2eWD/aj9rT3SbbVl5YG4vbz90m31xTzhUkkj/c743NHVmM991+IlNd4mK5Xj2NHmI`
`SWz3ewo3NHx5NDMvfk83FoAn/jRiGI+9Y6c3FmU7jvBmKP+WXopOaUuO8IDIj72CWTc0/4O6UuCc`
`74Wvl+aHjg/Scn//ib9Y31Y0D9J1/4zvpl9Z5f8P0Xl/kB+qH12Yq6J9P5OP/2B/YYWromIfls9w`
`T2VKq6L/Zi+aX7XvaVqrooDPne9sX/9taKuihI+hX7ofov+rsaQ/96VPqi+nZzGoD6kfxs+rON4y`
`q++s/64Prxoyr++w/3+yD7MYxiDQb7Tvtf+3DDL/t/+5D9Zfuy0OAdiPvV++b/2/eTLAP8FP2o/D`
`b8whiK/3xb83G6dJMovfyY/nPas43w/Q6N+QP+dLrwszkn/Rb/vnPLMJM5W/1U/nPLbuHjnvme/1`
`3/bjuy0znN/dr+c8/b9MM6BP4b/2TePf7FHEr//mL8qfp2eLyckfBj/LP48J/8z/Cg/PHwwB0F/x`
`f9J/sxj/lanU3xHv1v8L1Nhv+U8WP/+7LZzJ3T8Z/99fC/LgrwFPfxpvA08MAQSPBZ8Kf6dnNP8I`
`XwlvJx+rOKvAKN8NXw5v/68pzDAsvxFfEm8sCBQfFS//Iq+2/QwQNJ8Zbxp/uzwsgO84zx2fHq+/`
`ajUgjyGfOt+/I78scST/Jg8q76dnNSjP/ynfR4+rOC4ySW8t7y7/r0f/MjJNTzHvMv9MljSPNZ9D`
`H722/TY4vznPVx+7LTY87/c9/z8Pv1s2QP9CD1tPRC//TOHlH0Z/is1M0ujPSk+N/v2j8Tfsj04v`
`kT9sM/BvUi//lJ5sQvQvVg+X32wG+D9aP/+bb2wG/E9eb57/bCQAP2J//6Jvo3lasmGfRq9Hv2wV`
`ST/3aj+Eb6s4OE0fbZ9PP68a3jhRH3EfUz+zGDhU/3R/f2OPtv2ZIJHvWk9bX7s8OP9dX3vfX3+/`
`W5vCmm9ir2O/A6Moo7Fjb2xvcnQQYmw7XK8QZDBcGmevEW6jQKLQdWUw9aL/ZdyANaQqpUGk/6YJ`
`/6QUpjKkn6hvqC2nr6XfpC/8ZTHlAK36rxGuz6/ZpBR/sAKub7I/sf2xf6+vs3Q5/43wtsS4IbBD`
`uCCt/6QPukftqKU5hhC45DOzdCixuvMPhgGwQ71gv6IqXGRlrYrxcJ6xxGEwflFz0EFibIrAZzMw`
`jeHAMmZNsHAw9BHAxG5wwSIgyb6mcGG/QXFsnrB5UA+60HmAutBtMGRjdGwtwsByw8DboHC+8WF1`
`8d/QXGFzwsDEIG2gxSIobnVtyBBhxOB0b8HFIGRqdXN0eYD68U/DgboBeVC6AWl0wtAwYcIwXG5v`
`cXjRmNBvmHRlIMvgxuB5bJhQ+mjPkHTL4MMfxC/FP8ZPn8dfupDLIIsAiuFzMZ6w/mG/c3UA0EC/`
`8nlAwEHBIH/cgMpBzgDPtM9Rv3/AjWN/uvCegNNDwdDAecHVyVBu6GV4dM9Rc8igoqCY4Lfn8MlQ`
`eOBpoqDIAHnIQP5O1zKi4L6jz/HPUc2wnpAd3+B2ySDJUORQbWloT56AvvCZAMlQdW7aYWUvzeC6`
`sNeJ0BBEy9QgUA1tsGG68MLQaCBGb/RudL6UdNAAifDeIIqQVnfU0M4AZt4gV56AdLxoQpHQzgDC`
`wNmAbMEgy4JA37Ry4ChmbN+W3wD14Zdi4Zdy35Gi0MdwusHT45TJcHBl35Fz2dCisF//Ud4R91Dg`
`sOVWbOVlYuflZctg5XRkZ+ZW59DnVvvPwOV0dsL/yx/ML80/zk//z1/Qb9F/0o/Tn9Sv1b9t8P/v`
`sdof2ybYVKBQ+2DJkNi3f/FB2XjvLO7x8XrroKJgZvu4ENZhYuvgurDdkNky9r+v2yjJcG3AnoA5`
`8mA5ZcB9yEBI5IHmQMdwD5PY8zb/+a/6v/vKaqD8r/2//s//0vXdgGyikHe6sAAfk1ABT//vf/Kx`
`8V/yZ/xgBD8FSte4e9eR5QBz3ZD4gclQonBtrHBvJDAGr0XtkGmikPZDoqAv0G+TUKIjvtAv0DZ2`
`osHJMFUAgMiAd27xExVwZ3ATsxTSx/AU4c/H5en35YAW0WEwEyX/YV8Tshez/5UXs3MyOW/wM+Ub`
`8W3XUWhQ6wAaA92CyjOWAG030GtCx3IbRSRTdRcBbXPYgWxGfTvwYxuxnpDr8NxhifBt1GxNbbBn`
`G5NyHhe+8exKYx3R6yJJ49C58G3wzDQ0G7HHcHRMmDAbsakj8HJ5IPExvqN4HfA+bu2QFSMiI++w`
`7eB0cDg6Ly8QoMnAmOBzLl0FUGOKkBAw3wAuELEvRSSQZjwgZS93oqBk/i9qoMEwJXMd8KIwFNDC`
`0LXlAHewgDIggSazaJXS5xuxHiHgEDcwHdEeIeDAryiWIFGTUCgjYinDZ+0Q/ckQcseR7aBEoOqw`
`nrC+8f3IEGIokIJA6oHeoOqw5kFx3wBuYmrr0Lnw2YBvSGNcaOSAaGjJAHruNKaw3tEdEGvI8NnQ`
`8fD/LpTXJEAw8PG+4N2QyQEbQHG6sHN5c9cgIEG6kWx6ed2Qdh3wutAweMexZ+5k12AXQLrhZi2h`
`E5AgMf0vMXZ5QTMx1qAd8InwybDd3qBw8vAlUC4gbN9Q1qLvx/D0wKKgBUF4urCicN2g/yAxFxLZ`
`0MdwNHMiIRbRNVG/IiHlAIqQbcCJ8MiAePLwqSNQb3m58FzWoHDJsH+isIrQyIDroeZA6/AtwGTn`
`3aCi0CJQYmTm0MiA6/G/JVDXIfwx1yLJsO1QZS3QfaKgei2i59AoMsdwPjFo5zxzm7AyMWd2Pwk9`
`we3A/8dw8lE/gkCEQDM1QjBRP6FdQhNqOmGKwPRwdoEQd/5r48GaMENyEKB5QMERJ1H7KkDo4mXt`
`UETV1yDJANeR/THAdBRQx3A9oC0BRmft4P+Y4O0Q6/DIcSJA7eDtUaLB//wgZRBgkA2wIkDwsTuy`
`48H/8uBGcERh6rCi0N6xRmGiwf+isOiBIkAbUTzhPaDIgBtR/+sgFQLWccLQ7SD0QsdwJVD/B9Dw`
`sQfhJTAxsAWhMQAxsLnrEXBw2vDqsOvRaYrA/0v3WGCiwf8i66BtYMiAuvD/3qDtAiUw68DbUTaR`
`HJDJcN/XIXlQ7ZDIcePBbhtB3iA/WMAxsEvhMbATkMhxY3j/6/Ar8UxB48E7QQgAVME6MfvIgO/g`
`YyJRSNLv4FSz7RD7x3DmUGhWI0YyI2AU8Orx/TCRYzRwSBOiwBtgVuKe0AdKslkyNHB0eGJ4XP9M`
`EMHQbcDWkOvARGAjwTcR/mxJYZ6wOvF6ABDB12LBAMvWwL6ydzORZm1aYBJg/SrhICcw8mDIYsEA`
`12BysL9t4DqgyQDqwLBwx/Bs1yDvmOBEYEpwIkB1FkLfsl8A/8lQK3HbgSs1x6LWoLrQLXH/2wDl`
`AD2gYjPrdGFAyVAtA8/JMRTBIlArcGx2NRHskf8kUOzAZbHIEKKwZjLjwSAxf2/wJ1HbAPMBFULd`
`oNawYfwgLhSFZcWN8GZSC9Fmv/9nz2jfZhCR0OyQvvAtwGqv+2u/bM9slgDskApAam9vP31wRSlp`
`LJowbg9y/3AlYv+ZEHpBdC9l435Qcc92n3ev/3i/ZgGTcHoSZp97f3yPdJ3/l6B6H3+vgL+Bz2YB`
`vYB+r/+ET4VfhmUmoeWgFNDy8Mdw/wuz6uLpz+rf6+/s/+4Oi1L/n3H/eAof8C/xP/JP81/0b//B`
`qJ3Qkv+UAJUsDVFVsd6AZxhpn1L/Wg0Ki1LCMH0CAJ7gAAADAN4/n04AAAMA8T8KDAAAAwACWQAA`
`FgADAAlZAwAAAAsAEIAIIAYAAAAAAMAAAAAAAABGAAAAAAOFAAAAAAAAAwAWgAggBgAAAAAAwAAA`
`AAAAAEYAAAAAAYUAAAAAAAADACmACCAGAAAAAADAAAAAAAAARgAAAAAQhQAAAAAAAAsAR4AIIAYA`
`AAAAAMAAAAAAAABGAAAAAAaFAAAAAAAACwBIgAggBgAAAAAAwAAAAAAAAEYAAAAADoUAAAAAAAAD`
`AEmACCAGAAAAAADAAAAAAAAARgAAAAAYhQAAAAAAAAIBTYAIIAYAAAAAAMAAAAAAAABGAQAAADYA`
`AABJAG4AVAByAGEAbgBzAGkAdABNAGUAcwBzAGEAZwBlAEMAbwByAHIAZQBsAGEAdABvAHIAAAAA`
`AAEAAAAQAAAAsp61pB8B40+SzRSQRFiVMQsAj4AIIAYAAAAAAMAAAAAAAABGAAAAAIKFAAAAAAAA`
`AwDGgAggBgAAAAAAwAAAAAAAAEYAAAAA64UAAAoMAAAeAPqACCAGAAAAAADAAAAAAAAARgEAAAAY`
`AAAAQwBvAG0AcABvAHMAZQBUAHkAcABlAAAAAQAAAAgAAABuZXdNYWlsAAsAHw4BAAAAAgH4DwEA`
`AAAQAAAA6IkSDQZJw02ETSGH0qrzJAIB+g8BAAAAEAAAAOiJEg0GScNNhE0hh9Kq8yQDAP4PBQAA`
`AAMAFhAAAAAAAwANNP0/pQ4DAA80/T+lDgIBFDQBAAAAEAAAAE5JVEH5v7gBAKoAN9luAAACAX8A`
`AQAAADEAAAAwMDAwMDAwMEU4ODkxMjBEMDY0OUMzNEQ4NDREMjE4N0QyQUFGMzI0QzQwRjIwMDAA`
`AAAAAwAGEAAAAAADAAcQAAAAAAMAEBAAAAAAAwAREAAAAAAeAAgQAQAAAAEAAAAAAAAAIh0=`
``
`------=_NextPart_000_0012_01D6F89A.CA579DC0--`
`}`

My MimeKit version is 2.5 and I use .Net Core 2.2 (I cannot update because of a bug in the SSL connection in newer .Net Core versions).

What can I do to get the email decoded?
Thank you very much!

**Comment by jstedfast** [comment]
Is the TNEF decoder not working? or are you asking how to use the TNEF decoder?

If you are asking the later, you'll first want to get the [`TnefPart`](http://www.mimekit.net/docs/html/T_MimeKit_Tnef_TnefPart.htm). For example, you could do something like this:

```csharp
var tnef = message.BodyParts.OfType<TnefPart> ().FirstOrDefault ();
```

Now that you have the `TnefPart`, there are 2 convenience methods available to try and make reading the TNEF data easier:

- [ConvertToMessage()](http://www.mimekit.net/docs/html/M_MimeKit_Tnef_TnefPart_ConvertToMessage.htm)
- [ExtractAttachments()](http://www.mimekit.net/docs/html/M_MimeKit_Tnef_TnefPart_ExtractAttachments.htm)

Those methods attempt to convert TNEF data into the equivalent MIME, but be warned that not all TNEF properties map to MIME and so these methods will lose some data in the conversion.

I've tried to make it grab as much info as possible, but depending on what MAPI properties you care about, I may or may not have grabbed their values and stuffed it into the MIME.

That leaves the [`TnefReader`](http://www.mimekit.net/docs/html/T_MimeKit_Tnef_TnefReader.htm) as your last available option. You can see roughly how I used it to extract TNEF/MAPI data by looking through the source code for `TnefPart`: https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Tnef/TnefPart.cs

Look at the `ConvertToMessage()` method and the chain of methods that it calls to extract stuff.

**Comment by biancapop** [comment]
Hello,
Thank you very much for the quick answer.
I understand, do you think it is possible to edit the TNEF part and then add it again to the mail? The problem that I have is with TODO mails in Exchange, if they are sent as HTML emails they don't work anymore but if I enable TNEF then I cannot edit the mails and scan them.
Thank you again!

**Comment by jstedfast** [comment]
MimeKit currently doesn't have a way of writing TNEF data (it only supports reading).

I'm not sure of another good TNEF library for C#/.NET. The rest of them all look like payware.

You *might* be able to use the Microsoft.Exchange library but I'm not sure how/where to get that. (if you google for Microsoft.Exchange.Data you'll find reference to an Exchange library)
