### ISSUE TITLE
System.Buffers

### ISSUE THREAD

**Issue by cksoft0807** [jstedfast/MimeKit#652]
.Net FW 4.7.2
Mailkit / Mimekit 2.10.1 and installed dependency System.Buffers 4.5.1 results in missing file on "client.SendAsync(message);". i have fixed this with System.Buffers 4.5.0 (Mimekit 2.9.x).

The file or assembly "System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" or a dependency on it was not found. The system cannot find the specified file.

System.IO.FileNotFoundException: The file or assembly "System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" or a dependency on it was not found. The system cannot find the specified file.
Filename: "System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"
   for MimeKit.MimeContent.WriteTo(Stream stream, CancellationToken cancellationToken)
   at MimeKit.MimeContent.DecodeTo(Stream stream, CancellationToken cancellationToken) in D:\src\MimeKit\MimeContent.cs:line 318.
   at MimeKit.MimePart.GetBestEncoding(EncodingConstraint constraint, Int32 maxLineLength, CancellationToken cancellationToken) in D:\srcMimeKit\MimeContent.cs:line 427.....

**Comment by jstedfast** [comment]
I can't reproduce this issue.
