### ISSUE TITLE
Consolidate Azure/Appveyor/Travis pipelines into GitHub Actions

### ISSUE THREAD

**Issue by aleks-ivanov** [jstedfast/MimeKit#654]
Hi @jstedfast,

we can start working on this promptly, just please let us know if you are interested in the implementation of the idea 🙂 

**Is your feature request related to a problem? Please describe.**

Potentially unnecessary overhead of maintaining three separate build automation systems.

**Describe the solution you'd like**

A simple, yet powerful single GitHub Actions pipeline for build, test and publish automation, and seamless expendability with free for open-source native security tools like Dependabot and CodeQL

**Additional context**

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by jstedfast** [comment]
Sorry for the slow response. I'm potentially interested. I don't mind replacing Appveyor, Travis or Azure but I *would* prefer to keep a Windows build and a Linux build going. If GitHub Actions pipelines can do that, *awesome*!

I'd also prefer to keep publishing nugets to myget.org for each commit so that it's easier for developers to test my changes.

**Comment by aleks-ivanov** [comment]
No worries. 🙂

Yes, all of the requirements can be fulfilled by a GitHub Actions pipeline, which is indeed as you put it awesome!

Later today I will submit a draft PR with a basic Windows build, with the intention of then step by step add all the other requirements, so you can review every addition and give us feedback or ask questions if you wish.

**Comment by aleks-ivanov** [comment]
Hi @jstedfast, you can checkout the linked PR with the initial migration of the Azure Pipeline 🙂 

One thing I wanted to ask you about the NuGet package. To automate completely the process of nupkg push and publish, the version needs to be dynamically taken from somewhere, so how does your current process of bumping the version of the project look like ?

What I am looking for is a constant source from which I can get the project's version number, each time a push commit to the master branch is made with a new version of the project.

**Comment by jstedfast** [comment]
That's a good question - I'm not entirely sure how that works (the Azure build service seems to do it automatically somehow).

Apparently this is some sort of TFS CI feature. A quick web search suggests that *maybe* it uses $(Build.BuildNumber) but I have no idea if that will actually work or not.

**Comment by jstedfast** [comment]
FWIW, the $(Rev:.r) syntax is what I *think* generates the build number string in the azure-pipelines CI script.

Not sure if this `LATEST_VERSION: 2.10.1$(Rev:.r)` has the same effect or not in GitHub Actions.

**Comment by jstedfast** [comment]
FWIW, I am not attached to published myget nuget packages having a x.y.z.1, .2, .3, .4, etc. build number scheme. If that's not something that you can easily replicate, perhaps using the git commit hash and appending that to the build number would be easier.

**Comment by aleks-ivanov** [comment]
@jstedfast I didn't make the question clear enough, sorry about that. 

What I was wondering is currently when you make a certain change or changes to the project locally and decide to bump the version before committing to GitHub and tagging, lets say from the 2.10.1 to 2.11.0, how you do that ?

**Comment by jstedfast** [comment]
Oh, I edit the AssemblyInfo.cs file (and the MimeKit.csproj file) and bump the version. I also typically edit the appveyor.yml and azure-pipelines.yml files to bump the version in them as well.

**Comment by aleks-ivanov** [comment]
Hi @jstedfast I've finished the pipeline running on Windows as per your specifications 🙂 You can check it out in the PR. Any feedback would be appreciated!

Currently the pipeline works the same as the Azure pipeline with the following additions:

- when a new semantic version is found in MimeKit.csproj, a new tag is pushed to GitHub automatically
- to the new semantic version from MimeKit.csproj the run number of the GitHub Actions  pipeline (which is the $(Rev:.r) in Azure) is added and both are applied to the creation of the *.nupkg automatically

I've started working on the pipeline running on Linux, but I am having a little of difficulty.

As I understand from the Travis pipeline, you use .Net Core SDK 3.1.402 and run the build against it with the additional parameter of "/p:MonoRuntime=true", correct ?

The GitHub Actions Ubuntu runner comes with both [latest Mono](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#language-and-runtime) and [all .Net Core SDKs from 2 to latest](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#net-core-sdk), yet for some reason the build doesn't complete successfully using the exact same line of code `msbuild /p:Configuration=Debug /p:MonoRuntime=true MimeKit.sln` from the Travis pipeline.

The error is `/usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1193,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found.`

Does the same thing occur on the Travis pipeline ?
If not, do you know how the project knows to use the `netcoreapp3.1.402` in the Travis pipeline, so I can instruct it to do the same in the GHA pipeline ?

**Comment by jstedfast** [comment]
> Hi @jstedfast I've finished the pipeline running on Windows as per your specifications - build, test and MyGet publish🙂

Awesome! I'll try to check it out sometime today.

> As I understand from the Travis pipeline, you use .Net Core SDK 3.1.402 and run the build against it with the additional parameter of "/p:MonoRuntime=true", correct ?

Correct.

> Does the same thing occur on the Travis pipeline ?

Yes, the same error has been occurring on Travis since I added "net5" to the list of targets. I've been meaning to look into fixing that but haven't had a chance yet.

**Comment by aleks-ivanov** [comment]
> Yes, the same error has been occurring on Travis since I added "net5" to the list of targets. I've been meaning to look into fixing that but haven't had a chance yet.

I was looking into that today and found that the moniker for [.NET 5 (and .NET Core) is "net5.0"](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) and as far .NET Framework, the latest moniker for it is "net48".
May be "net50" in MimeKit.csproj, just doesn't point to anything and that is what is causing the issue ?
I removed it, tested a GHA pipeline run on Ubuntu and the build completed successfully.

**Comment by aleks-ivanov** [comment]
Hi @jstedfast, 

we were really happy to bring value to the MimeKit project 🙂 

If you need DevSecOps implementation on any other project, please don't hesitate to contact us via our [Project Onboarding board](https://github.com/pipeline-foundation/projects/projects/1), where you [create an application](https://github.com/pipeline-foundation/projects/issues) with some technical information about the project. 

We are at your disposal!

Kind regards,
Aleks from [Pipeline Foundation](https://pipeline.foundation/)
