### ISSUE TITLE
TNEF convert to message encoding

### ISSUE THREAD

**Issue by biancapop** [jstedfast/MimeKit#656]
Hello!
Sorry to bother you (again).. I am using MimeKit to parse a TNEF mail that contains just HTML and I am not able to get the right encoding.
```
var tnef = Message.BodyParts.OfType<TnefPart>().FirstOrDefault();
            if (tnef == null)
                return;

var tnefMail = tnef.ConvertToMessage();
```
from tnefMail I get the HTML body but not all characters are displayed correctly - for example é is Ã©. I tried to change the encodig afterwards using HtmlToHtml converter but I do not get the right result.  I also tried to convert all the html body to bytes and parse it to a String with UTF8 but I had no luck either--

  ```
private string ChangeEncoding(string text,  Encoding outEncoding)
        {
            HtmlToHtml htmlToHtml = new HtmlToHtml();
            htmlToHtml.OutputEncoding = outEncoding;

            if (string.IsNullOrEmpty(text))
                return text;
            return htmlToHtml.Convert(text);
        }
```

This issue only happens when I try to redirect an email (mostrly with newsletters) from Outlook from an Android device using en Office365 email. 

If I do the same from OWA or from a PC I do not get the same error and everything is parsed correctly.

Thank you very much!

**Comment by jstedfast** [comment]
I would probably need an example, but presumably the tnef attachment has a wrong charset defined in the tnef byte stream.

(TNEF defines the charset to use when decoding strings)
