### ISSUE TITLE
MimeKitLite 2.11.0 NuGet pkg missing .NET 5 build targets

### ISSUE THREAD

**Issue by user8446** [jstedfast/MimeKit#661]
Hello,
The release notes for the latest 2.11.0 shows adding the .NET 5 built target in the NuGet pkg. However, I checked MimeKit 2.11.0 and it is included there, just missing in MimeKitLite.

**Comment by jstedfast** [comment]
MimeKitLite doesn't have net50 targets because it doesn't gain anything. The full version of MimeKit gets additional functionality from net50.

**Comment by user8446** [comment]
Thank you for the explanation. FYI it does say added NET5 build targets in the release notes on NuGet

**Comment by jstedfast** [comment]
I just realized that - thanks! Sorry for the confusion (I copy & paste the notes from the MimeKit.nuspec and just normally remove the non-relevant bits but apparently Missed that one...)
