### ISSUE TITLE
Failed to parse encoded-word syntax from address

### ISSUE THREAD

**Issue by The-Nutty** [jstedfast/MimeKit#662]
**Describe the bug**
When parsing a specific mime message with a multiline encoded-word syntax from address `message.From` shows as empty despite a from address existing.

Please not this from address is very odd (from a phishing email, where i have just redacted the from address) and contains lots of non-ascii chars, but as far as i can see should still parse.

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Runtime: core
 - .NET Framework: Net 5
 - MimeKit Version: 2.11.0.9

**To Reproduce**
1. Create a new C# project, pull in mimekit and extract and add [dummy.eml](https://github.com/jstedfast/MimeKit/files/6148599/dummy.zip) to the project
2. Run the code : 
```
            var message = MimeMessage.Load("dummy.eml");

            Console.WriteLine(string.Join(".", message.From));
````
3. Observe that message.From is empty.

**Expected behavior**
message.From should contain one address `Nа؜؜؜mе؜؜؜с؜؜؜hе؜؜؜а؜؜؜р؜؜؜ - Suр؜؜؜р؜؜؜о؜؜؜rt <info@mredactedavcsefdf.co.uk>`

**Additional context**
Not really sure what the problem is, but putting `Nа؜؜؜mе؜؜؜с؜؜؜hе؜؜؜а؜؜؜р؜؜؜ - Suр؜؜؜р؜؜؜о؜؜؜rt <info@mredactedavcsefdf.co.uk>` into `MailboxAddress.Parse` works fine.

**Comment by jstedfast** [comment]
The problem is that it is just a name without an address.

It's the equivalent of:

```
From: The Nutty
```

**Comment by The-Nutty** [comment]
Thanks for replying, im trying to understand the encoded-words format more, so i have read through [RFC2047](https://tools.ietf.org/html/rfc2047) and as i understand it the header value 
```
=?utf-8?B?TtCw2JzYnNicbdC12JzYnNic0YHYnNic2Jxo0LXYnNic2JzQsNic2JzYnNGA?=
 =?utf-8?B?2JzYnNicIC0gU3XRgNic2JzYnNGA2JzYnNic0L7YnNic2JxydCA8aW5mb0Bt?=
 =?utf-8?B?cmVkYWN0ZWRhdmNzZWZkZi5jby51az4=?=
```
Should decode to `Nа؜؜؜mе؜؜؜с؜؜؜hе؜؜؜а؜؜؜р؜؜؜ - Suр؜؜؜р؜؜؜о؜؜؜rt <info@mredactedavcsefdf.co.uk>` .

Specifically the section:
```
   An 'encoded-word' may not be more than 75 characters long, including
   'charset', 'encoding', 'encoded-text', and delimiters.  If it is
   desirable to encode more text than will fit in an 'encoded-word' of
   75 characters, multiple 'encoded-word's (separated by CRLF SPACE) may
   be used.
```

So we have 3 sections separated by CRLF SPACE:
`=?utf-8?B?TtCw2JzYnNicbdC12JzYnNic0YHYnNic2Jxo0LXYnNic2JzQsNic2JzYnNGA?=` = `Nа؜؜؜mе؜؜؜с؜؜؜hе؜؜؜а؜؜؜р` 
`=?utf-8?B?2JzYnNicIC0gU3XRgNic2JzYnNGA2JzYnNic0L7YnNic2JxydCA8aW5mb0Bt?=` = `؜؜؜ - Suр؜؜؜р؜؜؜о؜؜؜rt <info@m`
`=?utf-8?B?cmVkYWN0ZWRhdmNzZWZkZi5jby51az4=?=` = `redactedavcsefdf.co.uk>`
Or combined: `Nа؜؜؜mе؜؜؜с؜؜؜hе؜؜؜а؜؜؜р؜؜؜ - Suр؜؜؜р؜؜؜о؜؜؜rt <info@mredactedavcsefdf.co.uk>`.

Further more putting the headers into both outlook and https://dogmamix.com/MimeHeadersDecoder/ seems to suggest that it should work.
Am i missing something?

**Comment by jstedfast** [comment]
The problem is that the way address header parsers are supposed to work is that they are not meant to decode the header and *then* parse the result.

They are designed to parse and *then* decode and the only portion that is meant to be decoded is the "name" component.

Namely, check Section 5:

```
(3) As a replacement for a 'word' entity within a 'phrase', for example,
    one that precedes an address in a From, To, or Cc header.  The ABNF
    definition for 'phrase' from RFC 822 thus becomes:

    phrase = 1*( encoded-word / word )

    In this case the set of characters that may be used in a "Q"-encoded
    'encoded-word' is restricted to: <upper and lower case ASCII
    letters, decimal digits, "!", "*", "+", "-", "/", "=", and "_"
    (underscore, ASCII 95.)>.  An 'encoded-word' that appears within a
    'phrase' MUST be separated from any adjacent 'word', 'text' or
    'special' by 'linear-white-space'.

   These are the ONLY locations where an 'encoded-word' may appear.  In
   particular:

   + An 'encoded-word' MUST NOT appear in any portion of an 'addr-spec'.

   + An 'encoded-word' MUST NOT appear within a 'quoted-string'.

   + An 'encoded-word' MUST NOT be used in a Received header field.

   + An 'encoded-word' MUST NOT be used in parameter of a MIME
     Content-Type or Content-Disposition field, or in any structured
     field body except within a 'comment' or 'phrase'.
```

Now if we check rfc5322, Section 3.4:

```
3.4.  Address Specification

   Addresses occur in several message header fields to indicate senders
   and recipients of messages.  An address may either be an individual
   mailbox, or a group of mailboxes.

   address         =   mailbox / group

   mailbox         =   name-addr / addr-spec

   name-addr       =   [display-name] angle-addr

   angle-addr      =   [CFWS] "<" addr-spec ">" [CFWS] /
                       obs-angle-addr

   group           =   display-name ":" [group-list] ";" [CFWS]

   display-name    =   phrase

   mailbox-list    =   (mailbox *("," mailbox)) / obs-mbox-list

   address-list    =   (address *("," address)) / obs-addr-list

   group-list      =   mailbox-list / CFWS / obs-group-list
```

Thus, the only portion of the mailbox address that is allowed to be made up of encoded-word tokens is the (optional) `display-name` token.

When a `display-name` token is used, however, the `angle-addr` token must be a separate token.

In your example, it is not only included as part of 2 previous `encoded-word` tokens, but also does not appear as its own token separate from the `display-name`.

**Comment by The-Nutty** [comment]
Ok thanks that makes sense, i understand if your not willing to put code in to InternetAddress.TryParse (happy to make a PR if you will take a look at it) to handle if the whole address in encoded-words, i will just have to implement similar logic my self

**Comment by jstedfast** [comment]
The address parser is already really complex :(

**Comment by jstedfast** [comment]
It's also worth considering any security/spam implications - odds are high that the reason spammers are encoding the entire name & address is to bypass spam filters. They may also be using it to "spoof" addresses.

**Comment by The-Nutty** [comment]
Ok that's fair enough, and yeah my understanding is avoiding spam filters is their goal here. Thanks for your help.

For anyone else that sees this later i have implemented the the following as a work around:
```
            if (message.From.Count == 0 && InternetAddressList.TryParse(message.Headers[HeaderId.From], out var addressList))
            {
                message.From.AddRange(addressList);
            }
```

**Comment by jstedfast** [comment]
Yep, that should work.
