### ISSUE TITLE
Visual Studio for Mac Version 8.9 - Error MT2101 System.Security.Cryptography Error

### ISSUE THREAD

**Issue by BlueFire-LLC** [jstedfast/MimeKit#663]
**Describe the bug**
App build fails with the following error:

/Users/Administrator/Desktop/Development/BlueFire/Xamarin/Motorhomes/Motorhomes/Motorhomes.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Void System.Security.Cryptography.DSACng::.ctor(System.Security.Cryptography.CngKey)', referenced from the method 'T Internal.Cryptography.Pal.Windows.PkcsPalWindows::GetPrivateKey(System.Security.Cryptography.X509Certificates.X509Certificate2,System.Boolean,System.Boolean)' in 'System.Security.Cryptography.Cng, Version=4.3.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. (MT2101) (Motorhomes.iOS)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Visual Studio for Mac Version 8.9
 - MimeKit Version: 2.11.0

**To Reproduce**
1. Add reference to MailKit
2. Build App
3. Error occurs

**Expected behavior**
App should build without errors

**Additional context**
App built fine with VS for Mac version 8.8. I have filed a report with Microsoft (see link below) and am hoping that you may have more clout with them for getting this fixed.

https://github.com/xamarin/xamarin-macios/issues/10802

**Comment by jstedfast** [comment]
Are you building for .net 5.0?

**Comment by BlueFire-LLC** [comment]
Yes. Below is the VS for Mac configuration.

== Visual Studio Community 2019 for Mac ===

Version 8.8.8 (build 0)
Installation UUID: 55194560-bd5f-4ebc-9e85-6b56d0c3ec9d
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.201/Sdks
SDK Versions:
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /private/var/folders/xn/cmjkx7196gq9l9lf34kjmsbh0000gp/T/AppTranslocation/B1099693-C64A-4F4C-8809-828F5FDB39D4/d/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.2

=== .NET Core 3.1 SDK ===

SDK: 3.1.407

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.8.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:43-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.iOS ===

Version: 14.14.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/Administrator/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:34:58 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:35:22 UTC

=== Build Information ===

Release ID: 808080000
Git revision: 11ec60df37f3adae429458aa60bd7533a1dc1a7b
Build date: 2021-02-03 10:10:12-05
Build branch: release-8.8
Xamarin extensions: 11ec60df37f3adae429458aa60bd7533a1dc1a7b

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

**Comment by BlueFire-LLC** [comment]
Here's the VSMac 8.8 link I got from Microsoft but it didn't help when I tried it. Same error. Not sure why. I have both VSMac versions installed though.
https://xamarin-storage.azureedge.net/dynamic/VSMRelease8.8/34937104-97FC-42A0-9159-D951135F72CA/VisualStudioForMac-8.8.8.0.dmg

**Comment by jstedfast** [comment]
Try downgrading MimeKit/MailKit to 2.10.1

2.11.0 added .net5 support specifically to add DSACng/RSACng.

**Comment by BlueFire-LLC** [comment]
No help. I even went back to 2.9. Same error. I reckon it's in Microsoft's hands. I'm dead in the water with needing a critical build. Not good.

**Comment by jstedfast** [comment]
2.9.0 has references to DSACng and RSACng, unfortunately. Try 2.7.0 (which does not have any references to any Cng classes).

2.8-2.10 went through several attempts at getting Cng support to work properly and then 2.11 removes support except for .net5 which is the only framework where it can work properly.

**Comment by BlueFire-LLC** [comment]
MailKit 2.6.0 worked. 2.7 required MimeKit 2.8. App is working too. But this still is unresolved and needs Microsoft to fix it. Agree?

**Comment by jstedfast** [comment]
Yes, absolutely.

**Comment by jstedfast** [comment]
FWIW, MimeKit's source code has no direct references to RSACng or DSACng, it only ever references the abstract RSA and DSA base classes.

The MimeKit.nuspec and the MimeKit.csproj also do not reference the [System.Security.Cryptography.Cng](https://www.nuget.org/packages/System.Security.Cryptography.Cng/) assembly.

I'm not sure why you are hitting this issue...

**Comment by BlueFire-LLC** [comment]
Oh, well. Even with all the updates by you and Microsoft, I'm still getting this error and have to use MailKit 2.6.0 in my iOS version. Maybe something will change. I'll keep trying...

**Comment by jstedfast** [comment]
I wish I knew what I could do (if there was anything I could do on my end).
