### ISSUE TITLE
System.PlatformNotSupportedException when trying to digitally sign message body

### ISSUE THREAD

**Issue by Grambuolys** [jstedfast/MimeKit#664]
**Describe the bug**
I get an exception when I try to digitally sign message body:

The code I run:

        private static void MultipartSign(MimeMessage mimeMessage, X509Certificate2 signatureCertificate)
        {
            using (var context = new WindowsSecureMimeContext(StoreLocation.LocalMachine))
            {
                mimeMessage.Body = MultipartSigned.Create(context, new CmsSigner(signatureCertificate), mimeMessage.Body);
            }
        }

The exception I get: 
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Security.Cryptography.X509Certificates.X509Certificate2.set_PrivateKey(AsymmetricAlgorithm value)
   at MimeKit.Cryptography.WindowsSecureMimeContext.GetRealCmsSigner(CmsSigner signer)
   at MimeKit.Cryptography.WindowsSecureMimeContext.Sign(CmsSigner signer, Stream content)
   at MimeKit.Cryptography.MultipartSigned.Create(SecureMimeContext ctx, CmsSigner signer, MimeEntity entity)

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Framework: .NET 5
 - MimeKit Version: 2.11.1

**Expected behavior**
I expected to digitally sign message body successfully. No exceptions to be thrown.

**Additional context**
Trying to sign message body like this, works without a problem:

        private static void MultipartSign(MimeMessage mimeMessage)
        {
            using (var context = new WindowsSecureMimeContext(StoreLocation.LocalMachine))
            {
                mimeMessage.Body = MultipartSigned.Create(context, mimeMessage.From.Mailboxes.First(), DigestAlgorithm.Sha256, mimeMessage.Body);
            }
        }

I may be wrong, but this line seems to cause a problem:
https://github.com/jstedfast/MimeKit/blob/94afd8f4575ed1d40f83cd5aaba42358ce3a3814/MimeKit/Cryptography/WindowsSecureMimeContext.cs#L370

Because of this:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/unsupported-apis

> X509Certificate2.PrivateKey (set only) | All

**Comment by jstedfast** [comment]
Thanks. I'll try to look into this soon.

**Comment by jstedfast** [comment]
If you could install https://www.myget.org/feed/mimekit/package/nuget/MimeKit/2.11.0.18 and verify that it works for you, that would be great. Thanks.

**Comment by Grambuolys** [comment]
> If you could install https://www.myget.org/feed/mimekit/package/nuget/MimeKit/2.11.0.18 and verify that it works for you, that would be great. Thanks.

I just tried it and it worked like a charm!
