### ISSUE TITLE
Emoji in TNEF decoded mail

### ISSUE THREAD

**Issue by biancapop** [jstedfast/MimeKit#667]
Hello!
I am having some issues with mail sent from Office365 - OWA - with emojis in it. The mail that I get is in TNEF and I use the TNEF converter to get the original HTML but when there are emojis in the mail they are not displaying correctly.

For example, the mail that I attach contains a smily face (here is the unicode reference: https://graphemica.com/%F0%9F%98%80) and in the email I can see the last three parts of the hex code: <0x9f><0x98><0x80> but the first one is changed with this letter: ð.

I tried to pull apart the symbol but I am not sure how I could identify it or change it to the corresponding encoding.

[test-mail.zip](https://github.com/jstedfast/MimeKit/files/6297365/test-mail.zip)

This is my TNEF converting code:
`var tnef = Message.BodyParts.OfType<TnefPart>().FirstOrDefault();
var tnefMail = tnef.ConvertToMessage();`

Thank you very much!

**Comment by jstedfast** [comment]
If the above patch doesn't fix it, I don't think it's fixable.
