### ISSUE TITLE
Allow adding attachment to AttachmentCollection as asynchronous operation

### ISSUE THREAD

**Issue by ultimaweapon** [jstedfast/MimeKit#670]
**Is your feature request related to a problem? Please describe.**
I want to add attachments to `AttachmentCollection` from `Stream` in a non-blocking fashion.

**Describe the solution you'd like**
Add two methods with the following signature:

```csharp
Task<MimeEntity> AddAsync(string fileName, Stream stream, ContentType contentType, CancellationToken cancellationToken = default)
```

```csharp
Task<MimeEntity> AddAsync(string fileName, Stream stream, CancellationToken cancellationToken = default)
```

**Describe alternatives you've considered**
Create a `MemoryStream` and copy the content of attachment to it with `Stream.CopyToAsync` then pass it to `AttachmentCollection.Add`.

**Additional context**
My application need to read attachments from a network socket. If I pass `Stream` directly to `AttachmentCollection.Add` it will cause thread blocking too long due to latency of the network socket; thus degrade the performance significantly.

**Comment by jstedfast** [comment]
Good suggestion. Thanks!

This will be included in the next release. In the meantime, you can use the nightly builds from https://www.myget.org/feed/mimekit/package/nuget/MimeKit

It should have a build version >= 2.11.0.26 once it finishes building.
