### ISSUE TITLE
Object of type "MimeKit.GroupAddress" cannot be converted to type "MimeKit.MailboxAddress"

### ISSUE THREAD

**Issue by ulued** [jstedfast/MimeKit#672]
On converting an eml message to msg I get this error on many mails.

exception: 0x24d0029 - System.InvalidCastException: Object of type "MimeKit.GroupAddress" cannot be converted to type "MimeKit.MailboxAddress"

**Comment by ulued** [comment]
I think this is a MsgReader Issue - closed

**Comment by ulued** [comment]
Yes, issue persist.

**Comment by jstedfast** [comment]
Where is the exception coming from? seems likely to be either your code or MsgReader and not MimeKit.

Check the StackTrace property of the Exception to find out.

**Comment by ulued** [comment]
This is my call, which raises the exception 

-> MsgKit.Converter.ConvertEmlToMsg(emlFile, msgFile);

I can see that clearly from my log. So it is not a MsgReader issue. It works for most mails, but raising the error at a customer site, so I can't Debug.

System.InvalidCastException: Das Objekt des Typs "MimeKit.GroupAddress" kann nicht in Typ "MimeKit.MailboxAddress" umgewandelt werden.
   bei MsgKit.Converter.ConvertEmlToMsg(Stream emlFile, Stream msgFile)
   bei MsgKit.Converter.ConvertEmlToMsg(String emlFileName, String msgFileName)
   bei Windream.Graph.Mailprocessing.MailboxProcessorGraph.<ArchiveMail>d__14.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by ulued** [comment]
You are right. Sorry for the confiusion
