### ISSUE TITLE
.NET 5: "SQLite is not available" exception when using DefaultSecureMimeContext 

### ISSUE THREAD

**Issue by fabioarnold** [jstedfast/MimeKit#673]
**Describe the bug**
When using the DefaultSecureMimeContext the following exception is thrown:
System.NotSupportedException: 'SQLite is not available. Install the System.Data.SQLite nuget.'

StackTrace:
```
   at MimeKit.Cryptography.DefaultSecureMimeContext.CheckIsAvailable()
   at MimeKit.Cryptography.DefaultSecureMimeContext..ctor(String fileName, String password)
   at MimeKit.Cryptography.DefaultSecureMimeContext..ctor()
   at MimeKit.Cryptography.CryptographyContext.Create(String protocol)
   at MimeKit.Cryptography.MultipartSigned.Create(CmsSigner signer, MimeEntity entity)
```

I have the System.Data.SQLite NuGet package installed. If I change the project from .NET 5 to .NET Core 3.1 it works fine.

Another workaround is to register a new default SecureMimeContext:
```
CryptographyContext.Register(typeof(MySecureMimeContext));
```

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET 5
 - MimeKit Version: 2.11.0

**To Reproduce**
Use any of the functions which don't take a custom context but make use of DefaultSecureMimeContext (e.g.: MultipartSigned.Create(CmsSigner, MimeEntity)). If needed I could provide a small sample program but it requires a certificate file.

**Expected behavior**
MimeKit should detect the presence of System.Data.SQLite.

**Comment by lafasta** [comment]
after hours of searching, I just have to copy the file SQLite.Interop.dll.
It lives in bin\x86 and bin\x64 so i copied the two folders to my production environment.
