### ISSUE TITLE
TNef inside Tnef

### ISSUE THREAD

**Issue by paolofuture** [jstedfast/MimeKit#685]
Hi,
I have an email with a tnef email attached to another tnef email. The main email is parsed correctly but the intenal one is recognized as application\octect-stream and returned in base64 encoding. I can't find a way to parse it as message instead as a "normal" attachment.

Platform :
 - .NET Framework: 4.0
 - MimeKit Version: 1.18

**Comment by jstedfast** [comment]
Do you have a sample message that illustrates this?

**Comment by jstedfast** [comment]
@paolofuture Do you have a sample message or tnef file that illustrates this?

If not, I'm going to close this bug report because there's nothing I can do to fix such a vague report.
