### ISSUE TITLE
DKIM signature creation support

### ISSUE THREAD

**Issue by AMailosaur** [jstedfast/MimeKit#69]
Does MimeKit provide support for signing emails as per DKIM specifications? Full verification using DNS records isn't required.

I looked at this library https://github.com/dmcgiv/DKIM.Net but it changes the mime data every time when using multiple mime parts. (attachments and alternative html/text) and can't be used in those cases.

**Comment by Lone-Coder** [comment]
I was able to get DKIM.net and MimeKit to work together using the following code:

        public static MimeMessage DkimSign(MimeMessage message, DkimSigner signer)
        {
            //message.BodyEncoding = signer.Encoding;
            //message.SubjectEncoding = signer.Encoding;
            //message.HeadersEncoding = signer.Encoding;


            // get email content and generate initial signature
            var email = Email.Parse(message.ToString());

            //if (!CanSign(email))
            //{
            //    throw new InvalidOperationException("Unable to Domain Key sign the message");
            //}

            var value = signer.GenerateDkimHeaderValue(email);

            // signature value get formatted so add dummy signature value then remove it
            message.Headers.Insert(0, DkimSigner.SignatureKey, value + new string('0', 70));
            email = Email.Parse(message.ToString()); //message.Parse();
            var formattedSig = email.Headers[DkimSigner.SignatureKey].Value;
            email.Headers[DkimSigner.SignatureKey].Value = formattedSig.Substring(0, formattedSig.Length - 70);

            // sign email
            var signature = signer.GenerateSignature(email);
            signature = Regex.Replace(signature, ".{70}", "$0\n\r "); // this is needed to make mimekit not butcher the signature with wierd us-ascii encoding
            value += signature;

            message.Headers.Remove(DkimSigner.SignatureKey);
            message.Headers.Add(new Header(DkimSigner.SignatureKey, value));

            return message;
        }

To test it you can easily generate a test key over at http://dkimcore.org/tools/

**Comment by jstedfast** [comment]
Thanks for looking into this, @Lone-Coder.

**Comment by jstedfast** [comment]
I'm pretty close to having DKIM support in the dkim-signatures branch that I hope to land this week. I could probably use help creating unit tests, though, since I don't have a lot to work with other than the examples in the spec.

**Comment by jstedfast** [comment]
What was left for me to do was surprisingly little. The unit tests I created based on the spec passed.
