### ISSUE TITLE
Encoding problem in 2.11.0+

### ISSUE THREAD

**Issue by Fr1z2r** [jstedfast/MimeKit#691]
**Describe the bug**
After updating to MimeKit 2.11.0+ the body is parsed with invalid encoding.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net Core 5.0
 - MimeKit Version: 2.11.0+

**To Reproduce**
```
[Test]
public void Test()
{
    MimeMessage.Load("mail.txt").TextBody.Should().Be("тест");
}
```

`Expected MimeMessage.Load("mail.txt").TextBody to be "тест", but "ÔÅÓÔ" differs near "ÔÅÓ" (index 0).`
[mail.txt](https://github.com/jstedfast/MimeKit/files/6786452/mail.txt)

**Comment by jstedfast** [comment]
I just tested this and it works fine for me with .NET 4.7.2

Keep in mind that .NET 5.0 requires that you do the following things:
1. reference the [System.Text.Encoding.CodePages](https://www.nuget.org/packages/System.Text.Encoding.CodePages) nuget package
2. register it using the following code snippet:

```csharp
Encoding.RegisterProvider (CodePagesEncodingProvider.Instance);
```

**Comment by jstedfast** [comment]
Just tested in .NET 5 and it works as well using the following test program:

```csharp
using System;
using System.Text;

using MimeKit;

namespace MimeParserTest
{
    class Program
    {
        static void Main (string[] args)
        {
            Encoding.RegisterProvider (CodePagesEncodingProvider.Instance);

            var message = MimeMessage.Load ("C:\\Users\\jestedfa\\Downloads\\mail.txt");
            var text = message.TextBody;

            Console.WriteLine (text);
        }
    }
}

```
