### ISSUE TITLE
Change Content Type to Plain Text

### ISSUE THREAD

**Issue by RousseauZaman** [jstedfast/MimeKit#698]
Various Client like EWS provide feature to change an existing mail from html to Plain Text or vice versa and update the message their itself. can this be done in MailKit? I see we are able to choose the content Type of Mail Body and Body part while drafting a mail but how can I update an existing mails contentType/MimeType.

when I'm trying to update the message its showing those properties are read Only and I couldnt find any option in Flag too to update the content Type, Please advise.

**Comment by jstedfast** [comment]
MimeKit does not have an API to convert a MimeMessage (that wouldn't make much sense), but it does have tools to convert text/plain content into text/html.

```csharp
string GetHtml (TextPart entity)
{
    TextConverter converter;

    if (entity.IsHtml) {
        // Note: this is only if you want to filter HTML tags, otherwise just return entity.Text since it's already in HTML format.
        converter = new HtmlToHtml {
            HtmlTagCallback = HtmlTagCallback
        };
    } else if (entity.IsFlowed) {
        var flowed = new FlowedToHtml ();
        string delsp;

        if (entity.ContentType.Parameters.TryGetValue ("delsp", out delsp))
            flowed.DeleteSpace = delsp.Equals ("yes", StringCompairosn.OrdinalIgnoreCase);

        converter = flowed;
    } else {
        converter = new TextToHtml ();
    }

    return converter.Convert (entity.Text);
}
```
