### ISSUE TITLE
MIMEKit cannot read a Thunderbird mail file

### ISSUE THREAD

**Issue by velja** [jstedfast/MimeKit#701]
ParseMessage fails with System.FormatException : Failed to parse message headers.
The file to reproduce the problem is here: https://drive.google.com/file/d/1s9KbXdBlF_rEIAZKYDwEhutkDiOGuHkh/view?usp=sharing
Parser fails on lines 20482, 20483 of the linked MBOX file and can not recover from that point. 
It fails in MimeKit\MimeParser.cs, line 1812. The state is Header (while it's in the content) and the parser recognizes "From a reader:&lt;br&gt;" line in the content as a start of a header. ... at least that was my impression. I can take a better look on Monday and maybe help a bit.

**Platform:**
 - OS: Windows
 - .NET 5
 - MimeKit Version: 2.15.0.0 (current source)

**Steps to Reproduce**
Execute this code on the linked file:
```
public void MinimalTest()
{
    string path = @"X:\path\JazzGuitar";
    using (FileStream inputStream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read))
    {
        MimeParser parser = new MimeParser(inputStream, MimeFormat.Mbox, true);
        while (!parser.IsEndOfStream)
        {
            parser.ParseMessage();
        }
    }
}
```

**Comment by jstedfast** [comment]
This is just unfixable, unfortunately.
