### ISSUE TITLE
In Memory X509Certificate2 CMSSigner Unit Test

### ISSUE THREAD

**Issue by chekm8** [jstedfast/MimeKit#702]
I am operating on a Windows machine and I am attempting to create a unit test for sending a signed email.  I create an Exportable self signed certificate in c# using the following code:

```
using RSA rsa = RSA.Create(2048 * 2);
var req = new CertificateRequest("cn=Y. Wonchawork", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
req.CertificateExtensions.Add(new X509KeyUsageExtension(X509KeyUsageFlags.DigitalSignature, true));

var cert = req.CreateSelfSigned(DateTimeOffset.Now, DateTimeOffset.Now.AddYears(5));
var certificate = X509Certificate2(cert.Export(X509ContentType.Pfx, CertPassword), CertPassword, X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable);  //make it exportable
```

I then try to instantiate a MimeKit CMSSigner which fails in the constructor with a WindowsCryptographicException:

```
using (var ctx = new TemporarySecureMimeContext()) 
            {
                var signer = new CmsSigner(certificate);   //This always fails when passing in the above 
                ...
             }
```

If I persist the in memory cert to the disk as a file I still have the same issue.  
```
var tmpFileName = Path.GetTempFileName();
byte[] certData = certWrapped.Export(X509ContentType.Pfx, CertPassword);
File.WriteAllBytes(tmpFileName, certData);
var certificate = new X509Certificate2(tmpFileName, CertPassword, X509KeyStorageFlags.Exportable);
```
I also used code similar to yours to read in the persisted certificate from the file using Pkcs12Store class and it was the same issue.

**If I take that disk-persisted cert and manually import it into the Windows Store and then export it again that new disk persisted certificate works fine.**  

I reviewed your unit tests and see that you always use a premade certificate in your TestData.  I was wondering if you did this on purpose because you may have run into this issue.  If not would you happen to have an example of a self-signed in memory cert DigitalSignature that is not persisted to disk that works?

Based on the above research I do not believe this issue is with MimeKit CMSSigner but, instead with the way the in memory certificate is created by Windows.  

I read a few articles ([Here's one](https://github.com/dotnet/runtime/issues/36899)) and a few people mention that it may be missing the "Export as Plain Text" option even when specifying "Exportable" flag.  

Thanks in Advance.

PS technically I know this is more of a Integration test.....but I'm using the NUnit test framework so I labeled it as unit test :)

**Comment by jstedfast** [comment]
Just wanted to let you know that I am able to reproduce the issue and am looking into this now. With any luck, I'll have a solution for this by the end of the weekend.

**Comment by jstedfast** [comment]
Okay, so like you said, if you use the MachineKeySet, it works.

Another option is to skip the export altogether:

```csharp
using RSA rsa = RSA.Create(2048 * 2);
var req = new CertificateRequest ("cn=Y. Wonchawork", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
req.CertificateExtensions.Add (new X509KeyUsageExtension (System.Security.Cryptography.X509Certificates.X509KeyUsageFlags.DigitalSignature, true));

var cert = req.CreateSelfSigned (DateTimeOffset.Now, DateTimeOffset.Now.AddYears (5));
var signer = new CmsSigner (cert);
```

**Comment by jstedfast** [comment]
I don't think this can be worked around inside of MImeKit's CmsSigner, so I think we have to close this.
