### ISSUE TITLE
mimekit.net/org/com should have custom SSL certificates to support HTTPS connections

### ISSUE THREAD

**Issue by PrzemyslawKlys** [jstedfast/MimeKit#707]
Not sure if you're aware, but it seems cert is broken, showing azure cert rather than the dedicated mimekit.net cert.

![image](https://user-images.githubusercontent.com/15063294/131972858-613890c5-8888-4831-affe-a5530ee02804.png)

**Comment by jstedfast** [comment]
Yea, I never set up HTTPS so it probably just uses the generic Azure cert. I've been meaning to set that up.

**Comment by shapeh** [comment]
An idea is to use Cloudflare and Letsencrypt.

**Comment by jstedfast** [comment]
Looks like this may be the way to go: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by jstedfast** [comment]
Currently working on doing this but it looks like it could take a week or so.

Plus I need to figure out a way to do all 3 domains: mimekit.net, mimekit.org, and mimekit.com

**Comment by jstedfast** [comment]
If I make mimekit.net my "master" domain that'll get a CNAME for jstedfast.github.io, then I guess what I would do is create CNAME records for mimekit.com and mimekit.org to point to www.mimekit.net?

**Comment by PrzemyslawKlys** [comment]
CNAME will work either way. What's important is to follow your custom domain to make sure that works, so that even tho you enter mimekit.org it shows  mimekit.net in browser so that google doesn't penalize you. 
- https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages

**Comment by PrzemyslawKlys** [comment]
You could pretty much do it all in Cloudflare. It takes care of certificates / redirects and saves traffic. Although if you do it on github pages - not biggie I guess. But the problem with Cloudflare is you need to move to Cloudflare as your DNS provider. If you need help with that - I could help you.

**Comment by jstedfast** [comment]
What would be the advantage of Cloudflare? I'm not very knowledgable about web hosting/etc (if that wasn't obvious, haha)

**Comment by shapeh** [comment]
The benefit of CF is simply the easy of use. 

Since the project is hosted on Github´s servers, you probably won't have to deal with bots, DDOS, hacking and similar nasty stuff. 
In addition, CF offers domain renewals are cost-prices (no markup), so you may save a few bucks on renewal fees.
In our company, we use CF for most of our client-facing websites. As @PrzemyslawKlys mentioned, "it takes care of certificates / redirects and saves traffic."

If you need help moving the domains to CF, do let me know. The sites will continue to run uninterrupted / no downtime.
Otherwise, just sign up for the Free account here: https://www.cloudflare.com/plans/

**Comment by PrzemyslawKlys** [comment]
Yes, cloudflare is basically a free service that can do multiple things:
- responsible for your DNS (easier to manage)
- can act as a proxy and makes it "worldwide" fast
- can and does hide your website IP/server 
- does certificates for you 
- makes your site super fast
- shows you nice stats who/when visited without even adding special code like google analytics which has more privacy than that
- protects you from attacks/ddos

You don't need to buy domains or move domains to Cloudflare to use the service, but you need to delegate DNS to there so it can manage it's records, redirects. I have my domains in OVH, and then Cloudflare manages the rest.

And it's free for all that :-) It has plenty of other options for free.

**Comment by jstedfast** [comment]
This should be done in the next day or so. I was finally able to get GitHub Pages to allow me to register mimekit.net (probably could have done this days ago, just needed time for DNS servers to update I guess?)

Anyway, GitHub is generating SSL certificates for mimekit.net and then it should be golden.
