### ISSUE TITLE
remove image in message ?

### ISSUE THREAD

**Issue by ronando82** [jstedfast/MimeKit#708]
Hi, i want to know if it's possible to remove image in a message/email before i use
 `message.GetTextBody(TextFormat.Text);` 
to have only the text.

Because i have a problem with html tag **img** like this : `<img border="0" width="23" height="25" id="Image_x0020_10" src="cid:image011.jpg@01D79B5F.A7752670" alt="cid:image008.jpg@01D34C29.CA60ADA0">`

after the  `message.GetTextBody(TextFormat.Text);`  command i have the **ALT content** in the string result

`cid:image008.jpg@01D34C29.CA60ADA0`

thanks

**Comment by jstedfast** [comment]
You seem to be asking for the plain-text message body, so I'm confused about why you have `<img>` tags. They should only be there for the HTML body.

But yes, you can remove `<img>` tags by using the [MimeKit.Text.HtmlToHtml](http://www.mimekit.net/docs/html/T_MimeKit_Text_HtmlToHtml.htm) class and using the [HtmlTagCallback](http://www.mimekit.net/docs/html/P_MimeKit_Text_HtmlToHtml_HtmlTagCallback.htm) hook.

**Comment by ronando82** [comment]
thanks for your reply.
I don't have `<img>` tags in the string result  of `message.GetTextBody(TextFormat.Text);`
 but i have the ALT content of the `<img>` tag. And i don't want it..

**Comment by jstedfast** [comment]
MimeKit doesn't have any code to remove those if that's what you are asking. You'll have to figure something out on your own, I'm afraid.
