### ISSUE TITLE
Replacing image data by CID + MimePart

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MimeKit#710]
Hi,

I'm try to reply to an email which has a 'MultiPart' body which I needed to maintain. In my reply html there is an (jpeg) image as base64 which I needed to replace right before sending by a CID and a 'MimePart' added to the already existing MultiPart body.

- I understand that 'BodyBuilder' would not help, since it would build/replace the whole body which is not what I needed in that scenario, correct?
- Hence, I'm trying to a add a MimePart to the already existing MultiPart body

Here is my code:
`multiPartBody.Add(new MimePart("image", "jpeg")
{
Content = new MimeContent(<stream-on-the-base64-bytes-array>, ContentEncoding.Base64),
ContentId = <some-unique-string>,
});`

In addition I'm iterating over all 'TextPart' of the 'MultiPart' body and am replacing the TextPart.Text (which is HTML) with HTML text where the CID is injected.

Email submission is rejected with tons of error info. I believe the most relevant part is:
`Diagnostic-Code: smtp;550 5.6.11 SMTPSEND.BareLinefeedsAreIllegal; message contains bare linefeeds, which cannot be sent via DATA and receiving system does not support BDAT
`

Would you have any idea what I'm doing wrong?

**Comment by DierkDroth** [comment]
Question related: I found that I mustn't dispose <stream-on-the-base64-bytes-array>, since there is an exception when sending the email. Will MailKit/MimeKit dispose that stream?

**Comment by jstedfast** [comment]
You need to set the MimePart's ContentTransferEncoding property to ContentEncoding.Base64:

```csharp
multiPartBody.Add(new MimePart("image", "jpeg") {
    Content = new MimeContent(<stream-on-the-base64-bytes-array>, ContentEncoding.Base64),
    ContentTransferEncoding = ContentEncoding.Base64,
    ContentId = <some-unique-string>
});
```

**Comment by jstedfast** [comment]
MimeKit/MailKit will not dispose the stream, so you will need to do that yourself.

**Comment by DierkDroth** [comment]
Thanks @jstedfast. I was able to resolve both issues: the sent email is visualized correctly in Outlook and GMail.

However, there is a follow up problem: I'm trying to append the sent email to the SENT folder and that fails for the email where I have replaced the base64 image by a CID + MimeContent and the IMAP connection is forcibly closed.

Here is the trace file (I added a few comments, pls search for !!!).
[trace.zip](https://github.com/jstedfast/MimeKit/files/7153296/trace.zip)

... and here is how I append the email to the SENT folder
`await sentFolder.AppendAsync(mimeMessage, MessageFlags.None, cts.Token);`

Would you have any idea why the IMAP connection is closed?

**Comment by jstedfast** [comment]
The problem is likely that your code to base64 encode your content is not adding line-feeds.

**Comment by DierkDroth** [comment]
Applying that change unfortunately brings back the original error and sending the email fails.

Not sure if this helps, but there are funny characters (binary data) in the trace. Here is a screenshot:
![image](https://user-images.githubusercontent.com/26179242/133111360-7cc4fcb6-2b44-435c-9be0-638344737558.png)

**Comment by DierkDroth** [comment]
> The problem is likely that your code to base64 encode your content is not adding line-feeds.

@jstedfast thinking: why then is sending the actual email no problem but attaching it to the SENT folder is? Strange...

**Comment by jstedfast** [comment]
You need to make sure to set the `MimeContent` encoding to `ContentEncoding.Default`  and the `MimePart.ContentTransferEncoding` to `ContentEncoding.Base64` so that MimeKit base64 encodes it.

It likely fails because the IMAP server does not support binary data (that may contain embedded zero-bytes).

**Comment by DierkDroth** [comment]
@jstedfast  I'm sorry. I still can't get it to work. 

Here is my most recent approach:
```cs
multiPartBody.Add(new MimePart("image", "jpeg")
{
    Content					= new MimeContent(new MemoryStream(ASCIIEncoding.ASCII.GetBytes(<base64-as-string>)), ContentEncoding.Default),
    ContentId				= id + "_" + count,
   ContentTransferEncoding	= ContentEncoding.Base64,
});
```
Now the image no longer displays properly on Outlook and I get this exception when trying to append the email to the SENT folder.
MailKit.Net.Imap.ImapProtocolException
  HResult=0x80131500
  Message=Syntax error in response. Unexpected token: Unexpected atom token: <p
  Source=MailKit
  StackTrace:
   at MailKit.Net.Imap.ImapCommand.<StepAsync>d__83.MoveNext()

**Comment by jstedfast** [comment]
It needs to look like this:

```csharp
multiPartBody.Add(new MimePart("image", "jpeg")
{
    Content = new MimeContent(new MemoryStream(Convert.FromBase64String (<base64-as-string>), ContentEncoding.Default),
    ContentId = id + "_" + count,
    ContentTransferEncoding = ContentEncoding.Base64,
});
```

**Comment by DierkDroth** [comment]
@jstedfast sorry for being the pest, but this brings us back to the issue above:
- the email is sent without error -> good
- it's visualized properly in Outlook -> good
- but sentFolder.AppendAsync still fails with this exception -> bad

MailKit.Net.Imap.ImapProtocolException
  HResult=0x80131500
  Message=Syntax error in response. Unexpected token: Unexpected atom token: <p
  Source=MailKit
  StackTrace:
   at MailKit.Net.Imap.ImapCommand.<StepAsync>d__83.MoveNext()

**Comment by jstedfast** [comment]
Can you provide the last bit of logs where that error is thrown? Looks like the IMAP server is responding with "<p" somewhere.

**Comment by DierkDroth** [comment]
@jstedfast sure. I just reproduced the case. Here is the trace file:
[trace.zip](https://github.com/jstedfast/MimeKit/files/7158770/trace.zip)

**Comment by jstedfast** [comment]
I've got a hunch, but not certain.

Try setting the `ContentTransferEncoding` property of your text/html part to ContentEncoding.QuotedPrintable.

Another option, and this might be better, is to call `message.Prepare (EncodingConstraint.EightBit)`.

I think the problem is the really long lines of the text/html content.

**Comment by DierkDroth** [comment]
@jstedfast unfortunately both approaches don't work 
- the email is sent without error -> good
- it's visualized properly in Outlook -> good
- but sentFolder.AppendAsync still fails with this exception -> **bad**

Approach 1:
```cs
<for-all-TextPart-in-MultiPart-body>
    textPart.ContentTransferEncoding = ContentEncoding.QuotedPrintable;
    textPart.Text = <replacement-HTML-with-CID>;
```
...yields this error
[trace.20210914.0000.zip](https://github.com/jstedfast/MimeKit/files/7163036/trace.20210914.0000.zip)

Approach 1:
```cs
<for-all-TextPart-in-MultiPart-body>
    textPart.Prepare(EncodingConstraint.EightBit);
    textPart.Text = <replacement-HTML-with-CID>;
```
...yields this error
[trace.20210914.0001.zip](https://github.com/jstedfast/MimeKit/files/7163030/trace.20210914.0001.zip)

**Comment by jstedfast** [comment]
In both the logs you attached, neither of the text/html parts have a Content-Transfer-Encoding header.

Why are you modifying the message after sending it but before attaching it to the ImapFolder?

It's properly line-wrapped when sending via SMTP but not when appending to IMAP.

**Comment by jstedfast** [comment]
FWIW, the `Content-Transfer-Encoding: quoted-printable` is correctly in-place in the SMTP logs but not for IMAP.

You must be removing the header or something before appending to IMAP?

**Comment by DierkDroth** [comment]
Hah @jstedfast you're right: I was thinking that it's sufficient for my scenario to convert the base64 image to CID + MimePart *only* for sending (SMTP) and call .AppendAsync (IMAP) with the original mail.

Turns out that's not the case: .AppendAsync (IMAP) needed the converted email (CID + MimePart) email as well.

Thanks a ton for your help!
