### ISSUE TITLE
Convert HTML to UTF8 text?

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MimeKit#713]
Hi,

I have to convert MimeMessage.HtmlBody to UTF8 text which basically is the 'text content' of the HTML message (background info: I needed to feed a full-text-search engine). I'm aware of [this ](https://www.csharpcodi.com/vs2/2700/MimeKit/UnitTests/Text/TextConverterTests.cs/) as well how the MimeVisitor works but fail to see how I could use these resources to convert HTML to UTF8 text.

Also, I checked into MimeMessage.TextBody but found that it would hold too many 'funny content/chars' when comparing to simple [RegEx based custom](https://stackoverflow.com/questions/286813/how-do-you-convert-html-to-plain-text) solution which I have in place right now. 

I suspect I'm missing some feature/class which might be readily available in MimeKit. 
Would you have any suggestion?

**Comment by jstedfast** [comment]
I would probably recommend the HtmlAgilityPack library for this, but I don't really know.

**Comment by DierkDroth** [comment]
Thanks for looking into, @jstedfast
