### ISSUE TITLE
Imapclient oauth authentication failed for outlook server

### ISSUE THREAD

**Issue by ReenaArora** [jstedfast/MimeKit#714]
Hi

I have been using code below for  a while to authenticate with imapclient andit was working fine till few days back but from last 3 days it starts giving me issue that Imapclient is not authenticated. 

Dim Client = New ImapClient
 Dim oauth2 = New SaslMechanismOAuth2(accountEmailAddress, accessToken)
                        Await Client.AuthenticateAsync(oauth2)

However same code is  working fine for Gmail server. Please check. thanks

**Comment by jstedfast** [comment]
access tokens don't last forever, you need to refresh it.
