### ISSUE TITLE
Send email with mhtml + file attachment

### ISSUE THREAD

**Issue by banibrataroy** [jstedfast/MimeKit#715]
Hi,
I am trying to send email with mhtml body as well as file attachments.
Using 
 MimeMessage.Load("file.mhtml")
I am able to send mhtml body but not able to find a way to attach additional files.

please help

**Comment by jstedfast** [comment]
Step 1 is understanding how MIME messages are structured.

Here is a link to the FAQ where I explain MIME structures: https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#MessageBody

And here is a link to the FAQ where I explain how to add attachments: https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#CreateAttachments

**Comment by jstedfast** [comment]
```csharp
// load the mhtml message
var message = MimeMessage.Load ("file.mhtml");

// create a multipart/mixed which will contain the current message body *and* the file attachments
var mixed = new Multipart ("mixed");

// add the current message body to the multipart/mixed and set the multipart/mixed as the new message body
mixed.Add (message.Body);
message.Body = mixed;

// now add attachments
var attachment = new MimePart ("image", "jpeg") {
    Content = new MimeContent (File.OpenRead ("image.jpeg")),
    FileName = "image.jpeg",
    ContentTransferEncoding = ContentEncoding.Base64
};

mixed.Add (attachment);
```
