### ISSUE TITLE
Problem parsing multipart/alternative messages.

### ISSUE THREAD

**Issue by christopinka-smarsh** [jstedfast/MimeKit#716]
**Describe the bug**
I have an eml file that has this structure

![image](https://user-images.githubusercontent.com/84037021/135378741-1a2891f0-a02e-48b7-972f-6b3155bd9209.png)

I parse the message with `MimeMessage message = MimeMessage.Load ("email.eml");`

Then I use the `message.BodyParts` and  `message.Attachments` enumerators to count and display the parts.

I expect to get 2 body parts and 3 attachments.

What I get is 5 body parts, the plain and html body from the multipart/alternative section and the 3 attachments.

The attachments enumeration seems correct.

How do I go about diagnosing this problem? 

I'm able to correctly get the body parts using mime4j DefaultMessagBuilder. The structure image was also generated using mime4j tools. I'm new to .Net.

I'll try to get you a scrubbed version of the message that produces the same behavior.

**Platform (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS, iOS, Android, Windows Phone, etc.] 
 OSX
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: [e.g. .Net Core, .NET 4.5, UWP, etc.]
.NET 5.0.10
 - MimeKit Version: 
     `<PackageReference Include="MimeKit" Version="2.15.1"/>`

**To Reproduce**

**Expected behavior**

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
using System;

using MimeKit;

namespace mimekit_parser
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription);
            var message = MimeMessage.Load ("hacked.eml");
           
            var count = 0;

            foreach (var part in message.Headers) {
                // Console.WriteLine(part);
                // Console.WriteLine("");
                count++;
            }
            Console.WriteLine("count Head = " + count);
            count = 0;

            foreach (var part in message.BodyParts) {
                Console.WriteLine(part);
                count++;
            }
            Console.WriteLine("count Body = " + count);
            count = 0;

            foreach (var part in message.Attachments) {
                count++;
                Console.WriteLine(part);
            }

            Console.WriteLine("count Attach = " + count);

        }
    }
}
```

**Additional context**
Output:

```bash
% dotnet run  
.NET 5.0.10
count Head = 58
Content-Disposition: inline
Content-Transfer-Encoding: Quoted-printable
Content-Type: text/plain; charset="utf-8"

yyy

Content-Disposition: inline
Content-Transfer-Encoding: Quoted-printable
Content-Type: text/html; charset="utf-8"

yyy

Content-Type: application/octet-stream;
        name="attach1.pdf"
Content-Disposition: attachment;
        filename="attach1.pdf"; size=4151885
Content-Transfer-Encoding: base64

xxx

Content-Type: application/octet-stream;
        name="attach2.PDF"
Content-Disposition: attachment;
        filename="attach2.PDF"; size=4337146
Content-Transfer-Encoding: base64

xxx

Content-Type: application/octet-stream;
        name="attach3.xlsx"
Content-Disposition: attachment;
        filename="attach3.xlsx"; size=619317
Content-Transfer-Encoding: base64

xxx

count Body = 5
Content-Type: application/octet-stream;
        name="attach1.pdf"
Content-Disposition: attachment;
        filename="attach1.pdf"; size=4151885
Content-Transfer-Encoding: base64

xxx

Content-Type: application/octet-stream;
        name="attach2.PDF"
Content-Disposition: attachment;
        filename="attach2.PDF"; size=4337146
Content-Transfer-Encoding: base64

xxx

Content-Type: application/octet-stream;
        name="attach3.xlsx"
Content-Disposition: attachment;
        filename="attach3.xlsx"; size=619317
Content-Transfer-Encoding: base64

xxx

count Attach = 3

```

The scrubbed eml content:

```text


Received: xxx
Received: xxx
Received: xxx
Authentication-Results: xxx
Received: xxx
Received: xxx
Received: xxx
Received: xxx
Authentication-Results: xxx
Received: xxx
DKIM-Signature: xxx
X-BB-Reception-Complete: xxx
X-IP-Listener: xxx
X-IP-MID:xxx
Received: xxx
X-BLP-INETSVC: xxx
Date: xxx
From: xxx
Reply-To: xxx
To: xxx
Message-ID: xxx
X-BLP-GUID: xxx
Content-Type: multipart/mixed;
	boundary="_ee35b763-106a-4e26-abef-efefa243cce2_"
X-Proofpoint-GUID: xxx
X-CLX-Response: xxx
X-Proofpoint-ORIG-GUID: xxx
X-CLX-Shades: xxx
MIME-Version: 1.0
Subject: xxx
X-Proofpoint-Virus-Version: xxx
X-Proofpoint-Spam-Details: xxx
X-Proofpoint-Virus-Version: xxx
X-Proofpoint-Virus-Version: xxx
Return-Path: xxx
X-MS-Exchange-Organization-OriginalArrivalTime: xxx
X-MS-Exchange-Organization-Network-Message-Id: xxx
X-MS-Exchange-Organization-OriginalClientIPAddress: xxx
X-MS-Exchange-Organization-OriginalServerIPAddress: xxx
X-MS-Exchange-Organization-Cross-Premises-Headers-Processed: xxx
X-MS-Exchange-Organization-OrderedPrecisionLatencyInProgress: xxx
X-MS-Exchange-Forest-ArrivalHubServer: xxx
X-MS-Exchange-Organization-AuthSource: xxx
X-MS-Exchange-Organization-AuthAs: xxx
X-MS-Exchange-Organization-FromEntityHeader: xxx
X-MS-Exchange-Organization-OriginalSize: xxx
X-MS-Exchange-Organization-HygienePolicy: xxx
X-MS-Exchange-Organization-MessageLatency: xxx
X-MS-Exchange-Organization-Recipient-Limit-Verified: xxx
X-MS-Exchange-Organization-TotalRecipientCount: xxx
X-MS-Exchange-Organization-Transport-Properties: xxx
X-MS-Exchange-Organization-Prioritization: xxx
X-MS-Exchange-Organization-IncludeInSla: xxx
X-MS-Exchange-Organization-Rules-Execution-History: xxx
X-MS-Exchange-Forest-RulesExecuted: xxx
X-MS-Exchange-Organization-RulesExecuted: xxx
X-MS-Exchange-Forest-IndexAgent-1: xxx
X-MS-Exchange-Forest-IndexAgent: xxx
X-MS-Exchange-Forest-EmailMessageHash: xxx
X-MS-Exchange-Forest-Language: en

--_ee35b763-106a-4e26-abef-efefa243cce2_
Content-Type: multipart/alternative;
	boundary="_9603c995-518c-4777-ac1d-0a89831fa2ba_"
Content-ID: xxx

--_9603c995-518c-4777-ac1d-0a89831fa2ba_
Content-Disposition: inline
Content-Transfer-Encoding: Quoted-printable
Content-Type: text/plain; charset="utf-8"

yyy

--_9603c995-518c-4777-ac1d-0a89831fa2ba_
Content-Disposition: inline
Content-Transfer-Encoding: Quoted-printable
Content-Type: text/html; charset="utf-8"

yyy

--_9603c995-518c-4777-ac1d-0a89831fa2ba_--

--_ee35b763-106a-4e26-abef-efefa243cce2_
Content-Type: application/octet-stream;
	name="attach1.pdf"
Content-Disposition: attachment;
	filename="attach1.pdf"; size=4151885
Content-Transfer-Encoding: base64

xxx

--_ee35b763-106a-4e26-abef-efefa243cce2_
Content-Type: application/octet-stream;
	name="attach2.PDF"
Content-Disposition: attachment;
	filename="attach2.PDF"; size=4337146
Content-Transfer-Encoding: base64

xxx

--_ee35b763-106a-4e26-abef-efefa243cce2_
Content-Type: application/octet-stream;
	name="attach3.xlsx"
Content-Disposition: attachment;
	filename="attach3.xlsx"; size=619317
Content-Transfer-Encoding: base64

xxx

--_ee35b763-106a-4e26-abef-efefa243cce2_--


```

**Comment by christopinka-smarsh** [comment]
I can attempt to contribute but I'm unclear on what the spec would say on how this is handled. And would have difficulty knowing if  the headers and boundaries are correct according to the spec for example. Thank you for your attention to this.

**Comment by christopinka-smarsh** [comment]
I might also add, this is part of an effort to improve/replace core parsing components at our company. We are spiking using MimeKit parsing as a micro-service in our system. The benchmarks, adoption and activity here make MimeKit a top contender. Thanks again.

**Comment by jstedfast** [comment]
Hi @christopinka-smarsh 

I think the issue here is confusion about what to expect from the `MimeMessage.BodyParts` property.

You seem to be expecting that the `BodyParts` property would be limited to non-attachment body parts whereas MimeKit includes *all* body parts, whether they are attachments or not.

Is my understanding correct?

That's an understandable expectation, but unfortunately that's not the way MimeKit's BodyParts property was designed to work.

Right now, the way the `MimeMessage.Attachments` property works is literally the following expression:

```csharp
message.BodyParts.Where (x => x.IsAttachment);
```

Based on that, you could get your expected results using the following expression:

```csharp
message.BodyParts.Where (x => !x.IsAttachment);
```

The `IsAttachment` property essentially boils down to this:

```csharp
bodyPart.ContentDisposition != null && bodyPart.ContentDisposition.Disposition.Equals ("attachment", StringComparison.OrdinalIgnoreCase)
```

I figured I'd explain how that logic works as well since there's sometimes confusion about it and if you're going for a drop-in replacement for Mime4j, then this *might* be the next inconsistency that you encounter (depending on how Mime4j interprets things).

MIME is unfortunately one of those things where everyone can interpret things a little differently.

For example, it would be completely reasonable to treat all images referenced in a multipart/related as attachments. But it's *also* reasonable to *not* include them as attachments since they are referenced by the HTML body and so therefore rendered inline.

I think that most people's assumptions about what is and isn't an attachment is shaped by "how does my favorite email client display the message to me?"

FWIW, depending on the goals of your product, it may be worth considering the [MimeIterator](http://www.mimekit.net/docs/html/T_MimeKit_MimeIterator.htm) or [MimeVisitor](http://www.mimekit.net/docs/html/T_MimeKit_MimeVisitor.htm) APIs for traversing the MIME structure as opposed to iterating over a flattened hierarchy of body parts.

BTW, I am happy to hear you guys are evaluating MimeKit to use in your product - that's awesome! :)

Let me know if you have any other questions.

**Comment by christopinka-smarsh** [comment]
Thanks for the timely clarifications! Is there a repo yet for MimeKitLite? Or is it part of the MimeKit build? I'm also wondering if there is way to pare down MimeKit to just the parsing bits. We'd need enough to parse and convert the MimeMessage to json. Have you seen any uses of MimeKit in a micro-service cloud arch yet? What's the best way to keep it blazing fast? Web sockets? Streaming? The goal is to have a service api that takes eml (stream) and returns the parts we need in a reliable format (json)? and scales well.

**Comment by christopinka-smarsh** [comment]
Is there a project board or forum yet where I can post questions? Or email?

**Comment by christopinka-smarsh** [comment]
Getting

error CS1061: 'IEnumerable<MimeEntity>' does not contain a definition for 'Where' and no accessible extension method 'Where' accepting a first argument of type 'IEnumerable<MimeEntity>' could be found (are you missing a using directive or an assembly reference?)


With 

```c#
 foreach (var part in message.BodyParts.Where (x => !x.IsAttachment)) {
                Console.WriteLine(part);
                count++;
  }

```

**Comment by jstedfast** [comment]
> Is there a repo yet for MimeKitLite? Or is it part of the MimeKit build?

It's all part of the same GitHub repository as MimeKit, but it does have a separate Visual Studio solution file (MimeKitLite.sln).

> I'm also wondering if there is way to pare down MimeKit to just the parsing bits.

There is not, but MimeKitLite is pretty close.

> Have you seen any uses of MimeKit in a micro-service cloud arch yet?

I haven't yet, no.

> What's the best way to keep it blazing fast? Web sockets? Streaming?

I haven't ever used web sockets/SignalR/etc, so I'm not sure how that works. If you can get a System.IO.Stream (or create a Stream wrapper around whatever input source you have), you should be good.

> Is there a project board or forum yet where I can post questions? Or email?

GitHub's issue tracker and https://stackoverflow.com (you can use the mimekit or mailkit tags) is all I have right now. I try to check them pretty regularly and I have stackoverflow.com setup to email me every day.

> error CS1061: 'IEnumerable' does not contain a definition for 'Where'

Ah, yea, you need to add `using System.Linq;` to your list of using statements. .NET has a concept called extension methods which is a way to add helper methods to classes (or interfaces) w/o having to modify the class itself. LINQ is a collection of extension methods for IList, IEnumerable, and other interfaces normally found in the System.Collections\[.Generic\] namespaces.

As you found, a `foreach` statement works well too :-)

**Comment by christopinka-smarsh** [comment]
I'm over in Gitter now.
