### ISSUE TITLE
Filename missing when Content-Disposition: inline

### ISSUE THREAD

**Issue by longa78** [jstedfast/MimeKit#719]
**Describe the bug**
I can't retrieve the filename when Content-Disposition is "inline"

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Framework: .NET 4.6.1
 - MimeKit Version: 2.15.1

**To Reproduce**
Can't directly reproduce bug but it's the case of some certitificates email that send some part of email in this way:
```
...

------------=_1635239050-28507-4130

Content-Type: application/xml; name="daticert.xml"

Content-Disposition: inline; filename="daticert.xml"

Content-Transfer-Encoding: base64

....
```

In the BodyParts object filename is NULL, only when Content-Disposition is inline.

**Expected behavior**
Filename is clearly present in email part

**Comment by jstedfast** [comment]
I'm closing this report because I know for a fact that those blank lines are there which are the cause of this issue (hint: those blank lines are invalid).

MimeKit has dozens of unit tests for this so I know it works.
