### ISSUE TITLE
Multipart content sent as base64 with ContentEncoding set to Default

### ISSUE THREAD

**Issue by mortenn** [jstedfast/MimeKit#721]
**Describe the bug**
I upgraded MimeKit from 2.1.3 to 2.15.1 in a solution implementing RosettaNet, after this receipts were no longer coming from the partner receiving the messages.
It turns out that they had started receiving base64 rather than xml, which was not supported.

The parts of the message are defined like this;
```
var mimePart = new MimePart("application/XML")
{
	ContentLocation = new Uri($"RN-{part.Location}", UriKind.Relative),
	ContentTransferEncoding = ContentEncoding.Default
};
mimePart.Headers.Add(HeaderId.ContentDescription, $"RosettaNet-{part.Location}");
mimePart.ContentId = $"<{idDomain}.{part.Location.ToLower()}.{idUnique}>";
mimePart.Headers.Remove("Content-Transfer-Encoding");

var stream = new MemoryStream(part.Xml);
mimePart.Content = new MimeContent(stream);
```

According to ContentEncoding, the Default value should not encode at all, so base64 is unexpected.

**Platform (please complete the following information):**
 - OS: Windows Server
 - .NET Runtime: Microsoft
 - .NET Framework: .NET 4.8
 - MimeKit Version: 2.15.1

**Expected behavior**
Mime parts to be delivered unencoded

**Comment by jstedfast** [comment]
You can set the ContentTransferEncoding to ContentEncoding.SevenBit or EightBit (as appropriate).

Setting EightBit is safe to use even when the content is ascii.

**Comment by mortenn** [comment]
Unfortunately, that did not appear to fix the issue at hand, so I am forced to stay with the older version.

**Comment by mortenn** [comment]
But the code isn't using SmtpClient

**Comment by jstedfast** [comment]
Oh, are you calling MimeMessage.Prepare()?

**Comment by mortenn** [comment]
The code creates a MultipartRelated instance, puts a few MimePart objects into it, each with some xml content.
Next, it uses MultipartSigned.Create to sign the MultipartRelated object using a certificate.
Then it wraps that MimeEntity in a new MultipartRelated object with RosettaNet headers.
Finally, it calls WriteToAsync on that final MultipartRelated object, copying the content only to a memorystream with EnsureNewLine set to true.
The memorystream is then put into a HttpRequestMessage with type Post before being sent using HttpClient.

**Comment by jstedfast** [comment]
Thanks for the details.

Signing a MimeEntity forces MimeKit to enforce the same encoding rules that Prepare() enforces because the assumption is that the message or entity will be transmitted over SMTP.

Sounds like this assumption, at least in your case, is not the case.

**Comment by jstedfast** [comment]
I'm reopening because *maybe* I can figure out a solution that will allow overriding that behavior such that it works for your needs as well as typical mail (i.e. SMTP) needs.

One possibility is to have a MultipartSigned.Create() method that takes a `SignOptions` argument that contains a `bool CanonicalizeEntity` property or something.

**Comment by jstedfast** [comment]
MimeKit v3.0.0 has been released with this feature.
