### ISSUE TITLE
Did you separate the GPG contest from the PGP parts ...?

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#723]
Hi Jeffrey, just curious if you did the above, such that I can retrieve PGP keys from something else but a GPG context ...?

**Comment by jstedfast** [comment]
I'm not entirely sure what you mean, but I think the API does what you need it to.

**Comment by polterguy** [comment]
Hi Jeff, I asked you about this a year ago or more I think. I think I even provided you with a pull request that would allow me to retrieve PGP keys from anywhere, detangle them from the GnuPG thing ... :)

**Comment by jstedfast** [comment]
Yes, looks like that should work.
