### ISSUE TITLE
Question - Use MimeKit in combination with HttpClient

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#730]
Hi there, I would like to use MimeKit to create `HttpClient` payloads, and to parse response objects returned from server. My reasons is because I've wrapped MimeKit into my own MIME slots, with lots of _"automatic"_ capabilities, allowing me to parse in files automatically, etc, etc, etc ...

However, this creates a problem for me, which is that as I serialise the MimeEntity I am given the `Content-Type`, which of course for an HTTP request should be found in the `Content-Type` HTTP header, together with the boundary (for Multipart entities).

Is there some method to retrieve the _value_ of the `ContentType` header, and also serialise the outer entity _without_ the `Content-Type` header ...?

And for the response being able to explicitly add a `ContentType` object as I de-serialise the response object ...?

**Comment by jstedfast** [comment]
For serializing MIME, you can pass `true` as the `contentOnly` argument to the [WriteTo()](http://www.mimekit.net/docs/html/M_MimeKit_MimeEntity_WriteTo_4.htm) method.

For deserializing, you can use the [MimeEntity.Load()](http://www.mimekit.net/docs/html/M_MimeKit_MimeEntity_Load.htm) method that takes a ContentType parameter that it will use to get the boundary marker.

**Comment by polterguy** [comment]
Brilliant, thx mate!
