### ISSUE TITLE
Implementing IDisposable on MimeEntity

### ISSUE THREAD

**Issue by polterguy** [jstedfast/MimeKit#732]
**Is your feature request related to a problem? Please describe.**
When I create a `MimeEntity` that somehow loads content from files, this is typically done by opening stream and associating these with the `Content` object. This implies I'll have to manually track all streams associated directly and indirectly with my `MimeEntity`, which of course creates more complex and less _"DRY"_ code for me.

**Describe the solution you'd like**
Basically, implement `IDisposable` interface on `MimeEntity`, for then to have its implementation recursively disposing all `Stream` objects directly or indirectly associated with the `MimeEntity`. Below is example code.

```
// Invoked from MimeEntity.Dispose
static void DisposeEntity(MimeEntity entity)
{
    if (entity is MimePart part)
    {
        part.Content?.Stream?.Dispose();
    }
    else if (entity is Multipart multi)
    {
        foreach (var idx in multi)
        {
            DisposeEntity(idx);
        }
    }
}
```

**Describe alternatives you've considered**
The alternative is to duplicate the above code every time I might in theory have an open `Stream` somehow associated with my `MimeEntity`, which of course is sub-optimal.

**Comment by jstedfast** [comment]
I had a patch for this here: https://github.com/jstedfast/MimeKit/blob/master/disposable.patch

It probably doesn't apply cleanly anymore, but it's a start.

IIRC, I did not commit the patch because it caused the unit tests to fail and I never figured out how/why.

**Comment by polterguy** [comment]
Weird, if you've got a non-disposable class, obviously none of the tests invokes `Dispose` I assume ... :/
Maybe some dependency injection parts, maybe in the tests, that would explain why `Dispose` is invoked ...?

Do you mind if I have a go at it, or ...?

**Comment by jstedfast** [comment]
I just updated disposable.patch. Feel free to play around with it.

**Comment by jstedfast** [comment]
As I ported the patch, I spotted the issues.

**Comment by polterguy** [comment]
Does this imply the next release will have `IDisposable` on `MimeEntity` ...?

**Comment by jstedfast** [comment]
Depends...

Keep in mind that things get more complicated when you add IDisposable support.

Should `multipart[i] = newPart` dispose the old part at that location? What about `multipart.Remove(part)`? What are the implications of these changes?

**Comment by polterguy** [comment]
> Should multipart[i] = newPart dispose

Not really, although I see your point, this is a _"C++ way of thinking"_. The important part is to have `MimeEntity` cleanup automatically without having to add code to specifically do it in client code.

MIME is a tree structure, implying people typically open `Stream` objects recursively during construction of entities. It's a question of _"ownership"_. The default behaviour should be that `MimeEntity` should _"own"_ the stream, the same way a `StreamReader` owns its `Stream` and disposes it. This is the default behaviour for most classes that is using `IDisposable` instance as fields, either directly or indirectly.

Then if some don't like this behaviour, the can simply avoid invoking `Dispose` ...

**Comment by jstedfast** [comment]
It would seem intuitive to me that the following `multipart.Clear ()` and `multipart[i] = newPart` would both dispose the old entities.

Those types of things are the types of things that broke my unit tests, btw.

**Comment by polterguy** [comment]
Hmm, I had an idea as I started thinking about our little problem. Maybe just keep the existing classes as they are, and create _"YALOA"_ ...? (Yet Another Layer Of Abstraction)

As in, create a class inheriting from `MimeEntity` called e.g. `MimeEntityDisposable` (or something) that implements `IDisposable`, and recursively clean up things ...?

That way there would be _zero_ changes to the existing classes, yet still allow us to consume the library _"as is"_ and easily clean up stuff ...?

Not sure how that would work in regards to MailKit, and places that creates `MimeEntity` instances though, which might be an issue ...?

My current problem is that I've got to add _"clean up code"_ every place I create `MimeEntity` instances, which implies having to either duplicate code in multiple projects, and/or create a YALOA project myself, complicating consumption of MimeKit ... :/

> Those types of things are the types of things that broke my unit tests, btw

OK, so you disposed old entities at the above points ...?
Does it really need to?
If MimeEntity implements `IDisposable` then `oldPart` would be a `MimeEntity` I presume, and one could do as follows ...

```
var x = multipart[i];
x.Dispose();
multipart[i] = newPart;
```

...?

Maybe this becomes dirty'ish, but a lot of people would probably use middleware code, created by layers between MimeKit and client/application code, and the first thing they'd look for, is if `MimeEntity` implements `IDisposable`, and if not, they would imagine everything is OK, when it's actually not, and they'd be leaking stream objects, etc, etc, etc ...

**Comment by jstedfast** [comment]
Why wouldn't you just implement an extension method?

```csharp
public static void Dispose (this MimeEntity entity)
{
    if (entity is Multipart multipart) {
        for (int i = 0; i < multipart.Count; i++)
            multipart[i].Dispose ();
    } else if (entity is MessagePart rfc822) {
        if (rfc822.Message != null)
            rfc822.Message.Dispose ();
    } else if (entity is MimePart part) {
        if (part.Content != null)
            part.Content.Stream.Dispose ();
    }
}

public static void Dispose (this MimeMessage message)
{
    message.Body.Dispose ();
}
```

**Comment by polterguy** [comment]
I'd need to duplicate code in all projects referencing the project, but don't worry, I'll figure it out ...

**Comment by jstedfast** [comment]
Decided the best coarse would be to make Remove/RemoveAt/Clear/set_Item not dispose.

Added a Clear(bool dispose) method for convenience for the Clear() case.

**Comment by polterguy** [comment]
Thank you man, this makes my life a 100 times easier :)
I'm using MimeKit _"all over the place"_ and having this results in my code becoming much more DRY ... :)

Let me know when you've got a release out somehow with this. Maybe just commenting _"done"_ on this guy or something. I'll close it for now :)

**Comment by jstedfast** [comment]
MimeKit v3.0.0 has been released with this feature.

**Comment by polterguy** [comment]
Najs, thx man :)

**Comment by polterguy** [comment]
Sorry to bother you, but for consistency reasons we should probably implement `IDisposable` on `MailMessage` too. It's not a big deal for me, but I thought it might create more consistency for (other) users ...

Thank you for the `MimeEntity` changes, it allowed me to remove _3 duplicated methods_ in _3 different projects_ ... :)

**Comment by jstedfast** [comment]
You mean MimeMessage? (MailMessage is System.Net.Mail)

If so, I already made MimeMessage implement IDisposable.

**Comment by polterguy** [comment]
Thx mate :)
