### ISSUE TITLE
Tnef inline images corrupted

### ISSUE THREAD

**Issue by biancapop** [jstedfast/MimeKit#736]
**Describe the bug**
Hello!
I am parsing mails and I am having problems with images included in a TNEF mail (inline images). When I send an email from Outlook online with a big image (for example 1079x800px) I get a corrupted image. If I send the email without parsing TNEF then the image gets to its destiny correctly. But I need to parse the TNEF part to insert some code lines and I am not able to sort this out. I did not encounter any problems with small images.

**Platform (please complete the following information):**
 - OS: CentOS/DEbian
 - .NET Framework: NET 5.0
 - MimeKit Version: 3.0 but I got the same result with the last stable 2 version 

**Code Snippets**
The code that I use to parse TNEF is:
```csharp
var tnefPart = Message.BodyParts.OfType<TnefPart>().FirstOrDefault();
MimeMessage tnefMail = tnefPart.ConvertToMessage();

BodyBuilder bb = new BodyBuilder();

var attachments = tnef.ExtractAttachments();
foreach (var attach in attachments)
{
    //normal attachments
    if (bb.Attachments.Contains(attach))
        continue;
    //inlineImages
    if (!bb.Attachments.Contains(attach) && attach.ContentDisposition != null && !attach.ContentDisposition.IsAttachment)
        bb.Attachments.Add(attach); // I tried to use bb.LinkedResources but I got the same result                
    //body text
    if (attach.ContentType.IsMimeType("text", "html"))
    {
        TextPart tp = (TextPart)attach;
        bb.HtmlBody = tp.Text;
    }
}
Message.Body = bb.ToMessageBody();
```

**Additional context**
I can email you a test mail before tnef processing and after.

Thank you very much!!

**Comment by jstedfast** [comment]
Yes, please send me the before/after messages and also a better description of what you mean by "corrupted".

**Comment by biancapop** [comment]
Hello!
I just sent it to you, if I can help with anything else just let me know.
Thank you very much!!

**Comment by jstedfast** [comment]
Thanks. I saw your email this morning and started looking into it.

**Comment by jstedfast** [comment]
I used MimeKit to extract the image from the "clean captured" messages and from the "after tnef parsing" messages.

In the first group, the images appear identical and the sizes are identical.

In the second group, the image extracted fine from the tnef but somehow the image from the "after" message is definitely corrupt and is 1005 bytes larger.

**Comment by jstedfast** [comment]
After extracting the image from tnef, just like your code is doing and attaching it to a new MimeMessage, I extracted the attachment out of the resulting message and saved the image to disk. This time it looks perfectly fine.

FWIW, I would recommend changing your code to this:

```csharp
var tnefPart = Message.BodyParts.OfType<TnefPart>().FirstOrDefault();
BodyBuilder bb = new BodyBuilder();

var attachments = tnef.ExtractAttachments();
foreach (var attach in attachments)
{
    //body text
    if (attach.ContentType.IsMimeType("text", "html"))
    {
        TextPart tp = (TextPart)attach;
        bb.HtmlBody = tp.Text;
        continue;
    }

    if (attach.ContentDisposition != null && !attach.ContentDisposition.IsAttachment)
        bb.Attachments.Add(attach);
}
Message.Body = bb.ToMessageBody();
```

But the easiest way might just be to do this:

```csharp
var tnefPart = Message.BodyParts.OfType<TnefPart>().FirstOrDefault();
var tnefMessage = tnefPart.ConvertToMessage ();

Message.Body = tnefMessage.Body;
```

**Comment by jstedfast** [comment]
Based on looking at the raw image data extracted from the "2-b-after-tnef-parsing.eml" file, it seems like the PNG header data repeats itself "half" way in, so what likely happened is that something is causing the image data stream to seek back to the beginning mid-way into writing it out.

Do you have another thread that is accessing the message (or at least the image attachment) while it is being saved/sent?

That's the only thing I can think of that would cause your specific issue.
