### ISSUE TITLE
Question: Split header and "body parts"

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MimeKit#739]
I have loaded a mime message like this:

```csharp
var mime = new FileInfo("d:\\test.eml").OpenRead();
var mimeMessage = MimeMessage.Load(mime);
```

Is it somehow possible to get the header part of the mimemessage and the rest as 2 seperate strings?

Reason for asking is because I want to store the headers in one field in a database and the rest (body + attachments) in another field. I sometime need to find information in the headers and it's faster if I don't have the rest like all the attachments.

I want to split it here and no I don't have the eml in a file otherwise I would just use a text reader and split it myself :-)

![image](https://user-images.githubusercontent.com/6692947/147142619-5f2eb49f-ccaa-48d4-a900-350ba7974ba3.png)

**Comment by Sicos1977** [comment]
I now came up with this... or is there an easier and faster way?

```csharp
var lines = mimeMessage.ToString().Split('\n');
var splitFound = false;

foreach (var line in lines)
{
    var innerLine = line.Trim();

    if (!splitFound)
    {
        splitFound = string.IsNullOrEmpty(innerLine);
        if (splitFound) continue;
        headersString.AppendLine(innerLine);
    }
    else
        bodyString.AppendLine(innerLine);
}
```

**Comment by jstedfast** [comment]
You can do `message.Headers.WriteTo(memoryStream);` to get just the headers.

Then you can do `message.Body.WriteTo(anotherMemoryStream, contentOnly: true);` to get just the body w/o the headers.
