### ISSUE TITLE
What is the equivalent of MailboxAddress.Parse as Regex ?

### ISSUE THREAD

**Issue by TungKaiYing** [jstedfast/MimeKit#745]
Hello i'm trying to find the good regex value for email importing from file to avoid any error in the software, people can verify email imported with MailboxAddress.Parse but i want it to be not needed by using the good regex formula !

Regards

**Comment by jstedfast** [comment]
Regex is not a good solution. If all you want to do is validate email addresses, use https://github.com/jstedfast/EmailValidation

**Comment by TungKaiYing** [comment]
Hello thanks for reply but i need to extract them from a file so i've no
other solution than regex

**Comment by jstedfast** [comment]
What is the format of the file?

**Comment by TungKaiYing** [comment]
Everything possible with readable text

**Comment by jstedfast** [comment]
I'm not aware of a good regex for that, but good luck.

**Comment by TungKaiYing** [comment]
Ok no problem have a nice day
