### ISSUE TITLE
Visual Studio UWP Project Debug execution ok! Release mode error...

### ISSUE THREAD

**Issue by ruifarin** [jstedfast/MimeKit#748]
**Error running in release mode**
Using Visual Studio with Nuget "MailKit" and running in Debug x64 mode, the mail is sent! 
In x64 Release mode... When initializing MimeMessage or even MailboxAddress has the following error: 
"A type initializer threw an exception..." 
"System.Reflection.AmbiguousMatchException: 'Ambiguous match found."

**Platform:**
 - OS: Windows 10
 - UWP - VB.NET 
 - Visual Studio 2019
 - MailKit Version: 3.1.0

**Code**
```vb
    Public Shared Async Function EnviaMailDocumento(ficheiro As StorageFile, eDestino As String, nomeDoc As String, nomeCli As String, eMensagem As String) As Task(Of Boolean)
        Dim resp As Boolean = True
        erroMail = ""

        Try
            Dim msgFrom As New MailboxAddress("AppContas-Fatura", "suporte@appcontas.com")
            Dim msgDest As New MailboxAddress("Destinatário", eDestino)
            Dim msgReply As New MailboxAddress(Usar.rRegisto.Nome, Usar.rRegisto.EMail)
            Dim eMsg As New MimeMessage
            eMsg.From.Add(msgFrom)
            eMsg.To.Add(msgDest)
            eMsg.Cc.Add(msgReply)
            eMsg.ReplyTo.Add(msgReply)
            eMsg.Subject = "Envio de Documento " & nomeDoc

            Dim bod As New BodyBuilder
            Dim Corpo As String = "<p>Ol&aacute; " & nomeCli & ",</p>"
            Corpo += "<p>Obrigado pela sua preferência<br /> Em anexo segue o Documento Nº " & nomeDoc & "</p>"
            If eMensagem <> "" Then
                Corpo += "<p>" & eMensagem.Replace(vbCr, "<br />") & "</p>"
            End If
            Corpo += "<p>Ao seu dispor,<br />"
            Corpo += "<em>" & Usar.rRegisto.Comercial & "</em></p>"
            Corpo += "<p style='font-size:8px;'>Gerado por Programa Certificado 'AppContas-Fatura'</p>"
            bod.HtmlBody = Corpo
            bod.Attachments.Add(ficheiro.Path)

            eMsg.Body = bod.ToMessageBody

            Dim smtp As New Net.Smtp.SmtpClient
            Await smtp.ConnectAsync("smtp.hostinger.com", 587, Security.SecureSocketOptions.StartTls)
            smtp.AuthenticationMechanisms.Remove("XOAUTH2")
            Await smtp.AuthenticateAsync("suporte@appcontas.com", "password")
            Await smtp.SendAsync(eMsg)
            Await smtp.DisconnectAsync(True)

        Catch ex As Exception
            erroMail = ex.Message
            resp = False
        End Try
        Return resp
    End Function
```

**Comment by jstedfast** [comment]
Which line throws the exception? and what is the Exception.StackTrace value?

Right now, you are asking me to find a needle in a haystack and I'm not even sure MimeKit or MailKit is the correct haystack.

**Comment by ruifarin** [comment]
Thanks
Dim msgFrom As New MailboxAddress("AppContas-Fatura", "suporte@appcontas.com")
I tried it first "Dim eMsg as new MimeMessage" and the error occurs on the first initialization of the variable associated with MimeKit (eventually on the second)

**Comment by jstedfast** [comment]
Unfortunately your screenshots are not helpful.

What is the Exception.StackTrace value?

Does UWP use .netstandard2.0? or 2.1? or what does it use?

**Comment by ruifarin** [comment]
**Stack Trace**
 at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x1ad
   at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstruction(Void*, StaticClassConstructionContext*) + 0xf
   at MimeKit.MimeMessage..ctor() + 0x1b
   at AppGeral.FuncoesMail.VB$StateMachine_5_EnviaMailDocumento.MoveNext() + 0x184

**Using**
Net.Core v5.0

**Comment by jstedfast** [comment]
Something must be wrong with your project. It works fine for me in Release mode.

**Comment by jstedfast** [comment]
This appears to be the same issue as issue #751 

Try the next build from the [MyGet](https://www.myget.org/feed/mimekit/package/nuget/MimeKit) feed. It should be v3.1.0.309.

**Comment by ruifarin** [comment]
Thanks 

Now i have a new exception but i have few information…

Occurs executing:

Dim smtp As New Net.Smtp.SmtpClient
…
Await smtp.SendAsync(eMsg) 
//eMsg is MimeMessage
------ compiler error
Exception thrown: '<unknown>' in MailKit.dll
Exception thrown: 'MailKit.Net.Smtp.SmtpCommandException' in System.Private.CoreLib.dll
Exception thrown: 'MailKit.Net.Smtp.SmtpCommandException' in System.Private.CoreLib.dll
Exception thrown: 'MailKit.Net.Smtp.SmtpCommandException' in System.Private.CoreLib.dll
The thread 0x14d4 has exited with code 0 (0x0).



De: Jeffrey Stedfast
Enviado: 28 de janeiro de 2022 15:51
Para: jstedfast/MimeKit
Cc: ruifarin; State change
Assunto: Re: [jstedfast/MimeKit] Visual Studio UWP Project Debug execution ok!Release mode error... (Issue #748)

This appears to be the same issue as issue #751
Try the next build from the MyGet feed. It should be v3.1.0.309.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jstedfast** [comment]
You're going to have to give me more than that.

I can't even tell if you are getting a compiler error (which is what your error says it is) or an exception trying to send a message because even the stack trace makes no sense.

If you are trying to send a message, then I'll need a protocol log (see the FAQ.md file for instructions on how to get one).

The Exception.Message string would also be useful.

**Comment by ruifarin** [comment]
Sorry, it was my mistake
Thanks for everything, I learned a lot and hope I helped you too
Problem solved
