### ISSUE TITLE
Can you expose method to get domain name from email address

### ISSUE THREAD

**Issue by tovyhnal** [jstedfast/MimeKit#766]
Can you please expose method, which would extract domain name from email address. Eg:
john.doe@contoso.com would return contoso.com

**Comment by jstedfast** [comment]
That's effectively just this:

```csharp
int at = mailbox.Address.LastIndexOf ('@');
var domain = mailbox.Address.Substring (at + 1);
```

**Comment by tovyhnal** [comment]
Not really, for this input this would not work: **"Mr Valid" <valid@domain.com>**

**Comment by jstedfast** [comment]
MailboxAddress.Address does not include the name. It only includes the `valid@domain.com`

**Comment by jstedfast** [comment]
This is what you'd do:

```csharp
var mailbox = MailboxAddress.Parse ("\"Mr Valid\" <valid@domain.com>");
int at = at = mailbox.Address.LastIndexOf ('@');
var domain = mailbox.Address.Substring (at + 1);
```
