### ISSUE TITLE
Investigate using built-in StringComparer.OrdinalIgnoreCase on .NET6.0+

### ISSUE THREAD

**Issue by iamcarbon** [jstedfast/MimeKit#771]
The OrdinalIgnoreCase methods were heavily optimized during the  .NET6.0 release cycle (upwards of 3x faster on Linux). We should benchmark whether our custom implementation is still faster on .NET6.0 and consider swapping it out.

ref: https://github.com/dotnet/runtime/pull/40910

**Comment by jstedfast** [comment]
Agreed, it's probably worth looking into.

**Comment by jstedfast** [comment]
.NET 6.0.2:
|                   Method |     Mean |     Error |    StdDev |
|------------------------- |---------:|----------:|----------:|
| BuiltInOrdinalIgnoreCase | 2.189 ms | 0.0169 ms | 0.0141 ms |
|  CustomOrdinalIgnoreCase | 5.212 ms | 0.0935 ms | 0.1588 ms |

.NET 5.0.14:
|                   Method |     Mean |     Error |    StdDev |
|------------------------- |---------:|----------:|----------:|
| BuiltInOrdinalIgnoreCase | 2.740 ms | 0.0305 ms | 0.0270 ms |
|  CustomOrdinalIgnoreCase | 6.086 ms | 0.0340 ms | 0.0302 ms |

.NET Framework 4.8:
|                   Method |     Mean |     Error |    StdDev |   Median |
|------------------------- |---------:|----------:|----------:|---------:|
| BuiltInOrdinalIgnoreCase | 6.762 ms | 0.0480 ms | 0.0425 ms | 6.757 ms |
|  CustomOrdinalIgnoreCase | 6.104 ms | 0.1100 ms | 0.2067 ms | 6.000 ms |
