### ISSUE TITLE
img in table html

### ISSUE THREAD

**Issue by enricodeveloper** [jstedfast/MimeKit#774]
Hi, I'm trying to include an image in an html table, but the image is not seen, if I remove the table it works

![screenmail](https://user-images.githubusercontent.com/11315419/154238541-d24552b6-b543-41f7-91fc-3fc6f60977e6.png)

**Comment by jstedfast** [comment]
Your code doesn't work.

**Comment by enricodeveloper** [comment]
> Your code doesn't work.

ops, this is code correct
[code.txt](https://github.com/jstedfast/MimeKit/files/8080179/code.txt)

**Comment by jstedfast** [comment]
Do you understand how HTML works?

**Comment by jstedfast** [comment]
You are setting the message body to a single text/html part with no image attachments and you expect the image to render?

How???

**Comment by enricodeveloper** [comment]
> You are setting the message body to a single text/html part with no image attachments and you expect the image to render?
> 
> How???

can you give me an example of sending mail with an image in a table?

thank you

**Comment by jstedfast** [comment]
I have an example of how to embed images in the README

**Comment by enricodeveloper** [comment]
ok, thanks
