### ISSUE TITLE
Question: Does this NuGet allow you to programmatically generate TNEF emails from code?

### ISSUE THREAD

**Issue by tludusan8x8** [jstedfast/MimeKit#777]
I've tried playing around a bit with the Tnef namespace classes in order to generate an email with a winmail.dat file, but to no success (except for maybe an empty one). I haven't found any relevant examples of this in the documentation either.

Basically, I'm looking for a programmatic way to generate different TNEF emails for testing purposes, as I don't have access to an Exchange server capable for sending TNEFs to the internet. Is this achievable using the current API or would that be a feature request?

Thanks!

**Comment by jstedfast** [comment]
MimeKit does not support writing TNEF and I'm not interested in implementing it (it was hard enough implementing a reader).

I would have loved to find a tool to generate TNEF as well for testing purposes but none seem to exist.

Every project that exists to read TNEF uses the same 5 or 6 TNEF files to test their implementation but those files only really test a small subset.

If you find a writer or decide to implement one, I'd love to know about it.
