### ISSUE TITLE
Empty field "TO"

### ISSUE THREAD

**Issue by JMorrison911** [jstedfast/MimeKit#778]
**Describe the bug**
During sending bulk emails, on IIS windows, i get the email , but empty filed TO.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CLR
 - .NET Framework: .NET 4.6.1
 - MimeKit Version: 3.0.0

**To Reproduce**
JUST SEND EMAIL ASYNC with recipients list 1 or more

**Expected behavior**
During sending as BULK customer will get email address in field TO

**Comment by jstedfast** [comment]
If you don't set a To header on the MimeMessage (via message.To.Add() and similar APIs), then there won't be anything in the To header that the recipient receives.

The `SmtpClient.Send(MimeMessage message, MailboxAddress sender, IEnumerable<MailboxAddress> recipients)` method is not meant to send a customized message to each recipient. What it does is to override whatever addresses are in the From/To/Cc/Bcc headers when sending.

To get the behavior you want, you could write an extension method like this:

```csharp
public static void SendToEach (this SmtpClient client, MimeMessage message, MailboxAddress sender, IEnumerable<MailboxAddress recipients>, CancellationToken cancellationToken)
{
    message.From.Clear ();
    message.From.Add (sender);

    foreach (var recipient in recipients) {
        message.To.Clear ();
        message.To.Add (recipient);
        client.Send (message, cancellationToken);
    }
}
```

**Comment by JMorrison911** [comment]
Thanks, for response.

Can u advice us: we need optimal bulk email sending with attachments. Now we use sending with recipients list, and it work perfect, but field TO is empty. In my opinion it increase risk to mark our email as spam. In you example will be sending 1 to 1 for each recipient, but our goal 1 to many with one attachment.

**Comment by JMorrison911** [comment]
Got it.  this is example from my real IIS server:
1. send 1 to 1 
EHLO [10.10.0.200],
MAIL, -,  FROM:<User@BLABLA.com>,
RCPT, -,  TO:<user_dst@Server.com>,
DATA, -,  <ZY8VP6IS6GU4.EN6J4TLUZLKX@DDDDDDD>,

2. send 1 to many
EHLO, -,  [10.10.0.200],
MAIL, -,  FROM:<smartsend@gradelink.com>,
RCPT, -,  TO:<user_dst_1@la-archdiocese.org>,
RCPT, -,  TO:<user_dst_2@yahoo.com>,
RCPT, -,  TO:<user_dst_3@gmail.com>,
DATA, -,  <PEKAIH17WFU4.I7RP9NNYOIW6@SECURE>,

And this is real working solution. From client side - we provide sender, list of recipients and then we call the function send with list of recipients.

**Comment by jstedfast** [comment]
Yes, MailKit can do either of those 2 options.

But note that the RCPT-TO addresses do not get set on the message - they just tell the SMTP server who to send the message to.

**Comment by JMorrison911** [comment]
Got it. you right.

And thanks for amazing code, i spend a lot of time on your code, and i love buffer optimization what u did.

**Comment by Eugene-Lytvynov** [comment]
If we will use "Undisclosed recipients" for field "TO", and one to many recipients list sending, is it will normal behavior or SMTP server will mark it as spam activity: because CC -> will empty, BCC-> will empty.  But to will consist Undisclosed recipients.
