### ISSUE TITLE
Can’t use the repo to get POP3 emails from gmx.com

### ISSUE THREAD

**Issue by zydjohnHotmail** [jstedfast/MimeKit#779]
**Describe the bug**
Can’t use the repo to get POP3 emails from gmx.com

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Runtime: .NET 6.0
 - MimeKit Version: 3.1.1

**To Reproduce**
I applied and get one gmx.com account, and I enabled POP3 from my gmx.com account according to the instruction in the web site.  I can send an email from my hotmail.com.  I see the email in my gmx.com mailbox, but I didn’t read it yet, I will leave it for POP3 client testing.

**Expected behavior**
I should be able to get email message sent from my hotmail account, but my code stuck .
**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
public static async void Get_GMX_Email()
{
    Pop3Client pop3_client = new Pop3Client();
    await pop3_client.ConnectAsync("pop.gmx.com", "MyAccount@gmx.com", "MyPassword");
    var messages = await pop3_client.ListAndRetrieveAsync();
}
```

**Additional context**

Hello:
I want to test if I can use POP3 client to get emails from gmx.com.
I applied and get one gmx.com account, and I enabled POP3 from my gmx.com account according to the instruction in the web site.  I can send an email from my hotmail.com.  I see the email in my gmx.com mailbox, but I didn’t read it yet, I will leave it for POP3 client testing.
The following is my C# code to read email from gmx.com POP3 server. (I used the latest version repo)

PM> Install-Package MimeKit -Version 3.1.1

```csharp
public static async void Get_GMX_Email()
{
    Pop3Client pop3_client = new Pop3Client();
    await pop3_client.ConnectAsync("pop.gmx.com", "MyAccount@gmx.com", "MyPassword");
    var messages = await pop3_client.ListAndRetrieveAsync();
}
```

But my code didn’t work. The program gets stuck at the statement:
```csharp
await pop3_client.ConnectAsync("pop.gmx.com", "MyAccount@gmx.com", "MyPassword");
```
Let me know if I made any mistake.
By the way, I am using Visual Studio 2022 target .NET 6.0 on Windows 10.
Thanks,

**Comment by jstedfast** [comment]
I don't know what library you are using, but your code isn't using MailKit.

MailKit's `ConnectAsync` method takes a host name, a port, and a SecureSocketOptions enum value that determines what type of SSL to use.

MailKit's Pop3Client also does not have a `ListAndRetrieveAsync` method.

**Comment by jstedfast** [comment]
It looks like you are using this library: https://github.com/rfinochi/pop3dotnet

**Comment by zydjohnHotmail** [comment]
Hi,
I don't know why I got the code.  I installed only this repo.
Do you have any code sample for such POP3 client?
thanks,

**Comment by jstedfast** [comment]
Yes, check the [README.md](https://github.com/jstedfast/MailKit/blob/master/README.md) file.

**Comment by zydjohnHotmail** [comment]
It is working now.
I think I use another repo with almost the same name as this repo.
Thanks,

**Comment by jstedfast** [comment]
You installed MimeKit (also maintained by me) which MailKit uses, but MimeKit does not have a Pop3Client - only MailKit does.
