### ISSUE TITLE
MimeMessage UTF8 Encoding whole Subject

### ISSUE THREAD

**Issue by kostakis76** [jstedfast/MimeKit#783]
Hello,
We use MimeMessage for creating e-mails and saving them to disk file. While creating subject header with national characters some words (not containging national characters) are not encoded so part of subject header is encoded and other part not. 
We wanted the whole Subject header to be encoded. Is this possible?

(current: Subject: No polish characters =?utf-8?b?UG9kemnEmWtvd2FuaWUgemEgd3DFgmF0xJk=?=)
(expected: Subject: =?UTF-8?B?Tm8gcG9saXNoIGNoYXJhY3RlcnMgUG9kemnEmWtvd2FuaWUgemEgd3DFgmF0xJk=?=)
Tom.

**Comment by jstedfast** [comment]
Why would you want that? The MIME specifications suggest that you *not* do that for several reasons:

1. it makes the header value (Subject in this case) longer
2. it's less readable (most people can't base64 decode in their heads - I'm a bit of a rarity there)
3. you need to split things up in order to wrap long headers anyway

but yes, if you really want to encode it as a single blob, then you can do this:

```csharp
var bytes = Encoding.UTF8.GetBytes (subjectString);
var base64 = Convert.ToBase64String (bytes);
message.Headers["Subject"] = $"=?utf-8?b?{base64}?=";
```

**Comment by kostakis76** [comment]
The reason is a 'bug' (maybe not bug) in MS Outlook. For unknown reason MS Outlook deletes last whitespace after ascii string and concatenates it with decoded string so the result is unreadable. And becouse many many of our customers use MS Outlook this is big case for us.
Thank you for workaround!

**Comment by jstedfast** [comment]
Oh, so you mean, it decodes it as `No polish charactersPodziękowanie za wpłatę` instead of `No polish characters Podziękowanie za wpłatę`?

**Comment by kostakis76** [comment]
Ok. 
Instead of preparing example data let me show production case. Subject encoded by MimeKit looks as follows:
Subject: =?utf-8?b?T3DFgmFjYWo=?= faktury w terminie i korzystaj z
 =?utf-8?b?cmFiYXTDs3c=?=
 Such subject received by Exchange Server and MS Outlook client presents like on picture. Last two words "z" and "rabatów" are concacentated what is a failure
![zrabatow-to-github](https://user-images.githubusercontent.com/58471584/160369352-92becdb8-59fd-4c89-9cb7-4b9dbabd57fd.png)
.

**Comment by jstedfast** [comment]
Do you happen to know which version of Outlook this is?

**Comment by kostakis76** [comment]
Microsoft Outlook 2019 MSO (16.0.10384.20023)(64-bit)

**Comment by kostakis76** [comment]
> var bytes = Encoding.UTF8.GetBytes (subjectString);
> var base64 = Convert.ToBase64String (bytes);
> message.Headers["Subject"] = $"=?utf-8?b?{base64}?=";

This workaroud isn't right. Made header this header:
Subject: =?utf-8?q?=3D=3Futf-8=3Fb=3FWmFsb2d1aiBzacSZIGRvIE3Ds2ogT3JhbmdlIGkgb2RiaWVyeiB?=

**Comment by jstedfast** [comment]
Ah, yea, I forgot that setting the string value of the Header will do that.

Sorry about that...

What you need to do is this:

```csharp
var bytes = Encoding.UTF8.GetBytes (subjectString);
var base64 = Convert.ToBase64String (bytes);
var rawSubject = Encoding.ASCII.GetBytes ($" =?utf-8?b?{base64}?=");
var subject = new Header (HeaderId.Subject, subjectString);
subject.SetRawValue (rawSubject);
message.Headers.Replace (subject);
```
