### ISSUE TITLE
Github "release"

### ISSUE THREAD

**Issue by coderb** [jstedfast/MimeKit#786]
Thank you for an outstanding product, I appreciate all your hard work!

If it's not too much trouble, would it be possible to use the github "release" feature?

This would allow people to subscribe to Watch->Custom->Releases to receive notifications when a new version is released.

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release

**Comment by jstedfast** [comment]
Sure, I can do that.
