### ISSUE TITLE
Exception 'Failed to parse entity headers' with MimeEntity.Load(stream)

### ISSUE THREAD

**Issue by blutswende** [jstedfast/MimeKit#788]
**Describe the bug**
I'm using MimeKit to process attachments of signed emails.
Now I received an email where MimeEntity.Load(stream) throws an **Failed to parse entity headers** exception.

>    at MimeKit.MimeParser.ParseEntity(Byte* inbuf, CancellationToken cancellationToken)
   at MimeKit.MimeParser.ParseEntity(CancellationToken cancellationToken)
   at MimeKit.MimeEntity.Load(ParserOptions options, Stream stream, Boolean persistent, CancellationToken cancellationToken)
   at MimeKit.MimeEntity.Load(Stream stream, CancellationToken cancellationToken)
   at SoloIMES.IMES.Models.ImesDocument.ProcessGraphItem(Message message, List`1 errors) in C:\_Development\SoloIMES\SoloIMES\IMES\Models\ImesDocument.cs:line 897

This procedure of loading the attachments from a signed mail works perfectly with other signed emails.

Do you have a hint where to look in the mail for the error?

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Framework: 4.8
 - MimeKit Version: 2.10.1

**Expected behavior**

**Code Snippets**

```csharp
                                    // Load attachment into the stream
                                    MemoryStream ms = new MemoryStream(fileAtt.ContentBytes);

                                    // Create an MimeEntity object 
                                    var signedMessage = MimeEntity.Load(ms);
```

**Additional context**

**Comment by jstedfast** [comment]
You should start by checking the raw content that you are trying to parse. Does it look valid?

That exception means that the headers are corrupt.

**Comment by blutswende** [comment]
@jstedfast
how the headers must look like?
which headers do you mean exactly?

i found those headers

`X-Djigzo-Info-SMIME-Signed: True
X-Djigzo-Info-Signer-ID-0-0: CN=GlobalSign GCC R3 PersonalSign 2 CA 2020,
 O=GlobalSign nv-sa, C=BE/2358B1A6CB8F5E29238D5B98//1.2.840.113549.1.1.1
 O=GlobalSign nv-sa, C=BE/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx//x.x.x.x.x.x.x.x.x.x.x.x.x.
X-Djigzo-Info-Signer-Verified-0-0: True
X-Djigzo-Info-Signer-Trusted-0-0: True
X-Djigzo-Info-Signer-Email-0-0: info@info.com`

**Comment by jstedfast** [comment]
What do you mean by "found"?

Are they at the start of the stream that you are parsing? Or is there binary garbage before them?

Why are you even parsing MimeEntities?

Are you not receiving MimeMessages?

**Comment by blutswende** [comment]
`What do you mean by "found"?`
opened it in notepad. seams not like binary garbage, seams to me like a normal email opened in notepad except from the mime part.

good question? the finished project was given to me for maintenance.
I made a short test with MimeMessage.Load() but it produced the same error..

**Comment by jstedfast** [comment]
2.10 is pretty old, maybe try upgrading to a newer 2.x version.

If that doesn't fix it, you'll need to provide me with a sample that I can use for debugging.
