### ISSUE TITLE
Confusion in the `micalg` parameter value for SHA-X algorithms.

### ISSUE THREAD

**Issue by fyodorklimenko** [jstedfast/MimeKit#790]
According to the [RFC-3851](https://datatracker.ietf.org/doc/html/rfc3851#page-25), `micalg` parameter value SHOULD be from the following:
`md5`, `sha1`, `sha256`, `sha384`, `sha512`, etc.
**There is no dash in the SHA-X algorithm value.**

According to the [RFC-5751](https://datatracker.ietf.org/doc/html/rfc5751#page-29), `micalg` parameter value SHOULD be from the following:
`md5`, `sha-1`, `sha-224`, `sha-256`, `sha-384`, `sha-512`, etc.
**There is a dash in the SHA-X algorithm value.**

RFC-5751 obsoletes RFC-3851 and that's why MimeKit uses dashes in SHA-X values.
https://github.com/jstedfast/MimeKit/blob/4de3405acc85917b98b9d346ed6b4f579caad963/MimeKit/Cryptography/SecureMimeContext.cs#L213
I completely agree with your decision to follow the newest RFC.

On the other side, OpenSSL doesn't follow RFC-3851 or RFC-5751.
There is [a mixed set](https://github.com/openssl/openssl/blob/openssl-3.0.2/crypto/asn1/asn_mime.c#L181) of values:
`md5`, `sha1`, `sha-256`, `sha-384`, `sha-512`, etc.
I want to mention that only `sha1` does not contain a dash. All others SHA-X do.

**Do you know why OpenSSL mixes the notation? It uses RFC-3851 for `sha1` and RFC-5751 for others.**

I don't see any reason (except the historical one).
But maybe you (as an expert) have got some ideas.

P.S.
Thank you for your great library and your efforts.
I should ask this question in the OpenSSL repository but this `micalg` mismatch drives me crazy and maybe you'll find a time to answer me.

**Comment by jstedfast** [comment]
Good catch, I hadn't noticed.

All I can think of is that OpenSSL is doing that for historical reasons. If you find out otherwise, let me know.

In the meantime, MimeKit could at least handle "sha1" and "sha-1" (etc) as the same so that it can get the correct DigestAlgorithm enum. I'll push a fix to do that.
