### ISSUE TITLE
[MimeKit.MimeMessage]::new() throws an error MimeKit.ParserOptions Net Framework 4.6.1 (System.Text.Encoding.CodePages)

### ISSUE THREAD

**Issue by argestionsoftware** [jstedfast/MimeKit#792]
Hi. I have a project in VB.NET, i am using VS2022, the project is based un .NET 4.6.1. Worked well with a previous version of the mimeKit, but after update to the 3.2 it's just start to make an exception and i can't find a solution.

**Describe the bug**
System.TypeInitializationException: An exception occurred in the type initializer 'MimeKit.ParserOptions'. ---> System.TypeInitializationException: An exception occurred in the type initializer 'MimeKit.Utils.CharsetUtils'. ---> System.IO.FileLoadException: Unable to load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' nor one of its dependencies. Assembly manifest definition does not match assembly reference. (Excepción de HRESULT: 0x80131040)

I don't have any reference to "System.Text.Encoding.CodePages, Version=4.1.1.0" in my project, i don't know if the mimeKit needs that version specifically, i have the reference with the  Version=6.0.0 of the CodePages. I don't know why is looking for the 4.1.1.0. Also i have the .dll in the application directory, like a System.Buffers for example.

On the other hand, Version=4.1.1.0 does not appear as available between the versions in the NuGet package manager either.

I have installed .NET Framework 4.8 in the server, my application just work fine.

**Platform (please complete the following information):**
 - OS: Windows Server 2019
 - .NET Framework: .Net Framework 4.6.1
 - MimeKit Version: 3.2.0
 
I appreciate any information that helps me resolve the issue.

![Aplication Directory](https://user-images.githubusercontent.com/94027586/168322495-4b2c9771-7e06-4ff2-8eab-31b6734ef46e.jpg)
![Aplication References](https://user-images.githubusercontent.com/94027586/168322503-1473e74a-ed8a-4b6e-a309-71c5e59a69df.jpg)
![CodePages Version Availables](https://user-images.githubusercontent.com/94027586/168322505-29e419b4-a76d-4514-b6ee-25b818913e6c.jpg)

**Comment by jstedfast** [comment]
There's some discussion here: https://github.com/jstedfast/MimeKit/issues/785

I guess I'll bump the dependency to 6.0.0 although this seems like a bug in the runtime or nuget or something since there's no reason for this error that I can see.

The whole point of specifying a *minimum* dependency version is that if the user updates a dependency, it *still* works (at least assuming no API changes were made, obviously).

**Comment by jstedfast** [comment]
The problem with me bumping to 6.0.0, of course, is that now *other* libraries that work with MimeKit now and also depend on a pre-6.0 System.Text.Encoding.CodePages will now break because of MimeKit's dependency bump.

There's no way out of this without breaking *someone*.

**Comment by jstedfast** [comment]
Give it 30 minutes or so and then go to https://www.myget.org/feed/mimekit/package/nuget/MimeKit and install MimeKit 3.2.0.458 and see if that fixes it.

**Comment by argestionsoftware** [comment]
Hi. I was reading about the #785 
Ok. I wait. Don'y worry. I will try in one hour maybe and give you a feedback.
Thanks a lot.

**Comment by argestionsoftware** [comment]
Well. I did the test after update. In the first try, it make an exception with the System.Memory assembly. So, I remove the reference from the project, Version= 4.0.1.1 if i remember well or maybe 4.0.4.1, anyway i took the .dll and moved it into the application directory. Then i try again but now the exception is this: 

An exception occurred in the type initializer 'PerTypeValues`1'. ---> System.IO.FileLoadException: Unable to load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' nor one of its dependencies. Assembly manifest definition does not match assembly reference. (Excepción de HRESULT: 0x80131040)

The same case with the System.Text.Encoding.CodePages. I don't have any reference to the 
System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, the version in my references is 6.0.0.0

I have to say that in local, this work fine, but in my PC i have everything installed, i move the compiled proyect to the server, and it just stop working. 

![CompilerServices Unsafe Reference](https://user-images.githubusercontent.com/94027586/168388022-9382970b-1921-45d9-b245-0c33afd93e52.jpg)

**Comment by jstedfast** [comment]
Which MimeKit target framework is your project referencing? the netstandard2.0 version or the net461 version?

**Comment by argestionsoftware** [comment]
Net Framework 4.6.1

**Comment by jstedfast** [comment]
That's what it says in the json files that `dotnet restore` generates?

**Comment by argestionsoftware** [comment]
I saw that here

![Net Target References](https://user-images.githubusercontent.com/94027586/168396079-887859e6-6271-4e80-bd2c-405e9178c7c0.jpg)

**Comment by jstedfast** [comment]
Oh, you're using packages.config... that might explain this problem.

I wonder if this would be fixed if you used `<PackageReference Include="MimeKit" Version="3.2.0" />` (obviously for each package, not just MimeKit) in your .csproj.

packages.config has been deprecated for a few years now.

**Comment by argestionsoftware** [comment]
Well. Just to keep you informed. I don't have a csproj file because my project is from Visual Basic .NET
Based on your suggestion, I right-clicked on Packaget.Config and selected the "migrate to PackageReference" option. Packaget.Config disappeared from my project and I couldn't find the references again. In NuGet package management, all packages disappeared. I had to reinstall all of them one by one. So I'm like at the beginning. Now I don't know why when running this line, I have errors that I didn't have before.

Install-Package MimeKit -Version 3.2.0.458 -Source https://www.myget.org/F/mimekit/api/v3/index.json

So now I am back to the original exception related to CodePages and version=4.1.1.0

I'll be back soon, time to eat in Argentina. =)

Tks for all your answers.

**Comment by argestionsoftware** [comment]
Well. After many tests, i restore all previous to the update, with GitHub Desktop. I back to the MimeKit 2.14, including the package.config, allways using .NET Framework 4.6.1 
The app still work in local, but in the server, now: 
System.IO.FileLoadException: Cannot load file or assembly 'MimeKit, Version=2.14.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814' or one of its dependencies. The assembly manifest definition does not match the reference to the assembly. (Exception from HRESULT: 0x80131040)
I try the application with MimeKit, Version=2.14.0.0 in another server with 2008, and it work. So the problem now is in that W2K19 Server with the Framework's version. For now, i don't goin to make anyhthing else. I'am going to find the way to replace that server, after thats, i going to update the mimeKit version and try again

**Comment by argestionsoftware** [comment]
Hi Jeffrey. Tks for the information, i will try to change the target framework to that version. We still working with de version 2.14, i going to update and give you a feedback about that.

**Comment by argestionsoftware** [comment]
1. Change the target framework of the app to 4.8
2. I Reinstalled all the NuGet packages including MailKit 3.2.0
3. Run the command: Install-Package MimeKit -Version 3.2.0.458 -Source https://www.myget.org/F/mimekit/api/v3/index.json

4. Testing the application
System.TypeInitializationException: 'MimeKit.Utils.CharsetUtils'. ---> Cannot load file or assembly 'System.Text.Encoding.CodePages, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 

5. I toke System.Text.Encoding.CodePages.dll and put into the application directory

6. Testing again
System.IO.FileNotFoundException: Cannot load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

7. I toke the System.Memory.dll and put into the application directory too

8. Testing again
System.TypeInitializationException: 'PerTypeValues`1'. ---> Cannot load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

9. I toke the System.Runtime.CompilerServices.Unsafe.dll and put into the application directory too

10. Testing
The same issue at point 8 about CompilerServices.Unsafe

The version of the System.Runtime.CompilerServices.Unsafe.dll in the NuGet package is 6.0.0.0 and the Version=4.0.4.1 is not available in the NuGet list.

It's seems that we are in the same place at the begining of the conversation relationed to CodePages but with another assembly.

**Comment by jstedfast** [comment]
Seems like what you need to do is add some binding redirects to your app.config:

https://stackoverflow.com/questions/62764744/could-not-load-file-or-assembly-system-runtime-compilerservices-unsafe

**Comment by argestionsoftware** [comment]
Hi J. Thank you for your information. I did this: 
"Based on Perry's answer, I simply installed the nuget package System.Runtime.CompilerServices.Unsafe version 4.5.3 and the problem was solved" 
and everything is working fine now. 

So the bug related to the tittle is solved with this: 
Install-Package MimeKit -Version 3.2.0.458 -Source https://www.myget.org/F/mimekit/api/v3/index.json

**Comment by jstedfast** [comment]
MimeKit v3.4.0 has been released with this fix.
