### ISSUE TITLE
MimeKit for Windows 8.1 / Windows Phone 8.1 Apps

### ISSUE THREAD

**Issue by blacklion9279** [jstedfast/MimeKit#80]
I am trying to install MimeKit into a PCL via nuget but it fails to add. See attached image. 
![mimekit_pcl_error](https://cloud.githubusercontent.com/assets/1731171/4364254/52f8b466-429e-11e4-93f0-21b389562fdb.png)

I have tried various targets including 
1. PCL .net 4.0, Windows 8.1 , windows phone 8.1 and 
2. PCL .net 4.0, Windows 8 , windows phone 8.1 without any luck. I was able to integrate it with Windows 8.1 class library - the issue I run into there is I am not able to extend DefaultSecureMimeContext. Infact only namespace and class i see in that library is MD5. (see attached image).
![mimekit](https://cloud.githubusercontent.com/assets/1731171/4364312/e1410f02-429e-11e4-9cb9-c486834c51af.png)

**Comment by jstedfast** [comment]
I was hoping 1.8 would be out by now :-(

Sorry about the wait... I'm looking into switching to https://github.com/onovotny/BouncyCastle-PCL but I can't seem to build it on Mac and I can't use NuGet packages because all of my .csproj files share the same directory which means they all want to use `packages.config` which conflict with each other :-\

**Comment by blacklion9279** [comment]
I used that package in one of the application. seems to be working okay. Do you have any plans for making this available on WinRT / Windows Phone 8.1 now? We just found that bouncy castle version that we were using doesn't pass store compliance. So, I am hoping using the Bouncy castle pcl version would fix it. When we make the switch, I was considering switching mimekit version as well if it supports winrt/wp 8.1 

Thanks !

**Comment by jstedfast** [comment]
I haven't been able to solve the issue I mentioned in my previous comment :-\

**Comment by jstedfast** [comment]
I've started working on porting the PCL versions of MimeKit to use BouncyCastle-PCL now that it is strong-named and 1.8 final has gone out.

**Comment by jstedfast** [comment]
MimeKit.Portable now builds with most of MimeKit.Cryptography (minus the bits that require System.Data which are not available for PCL)
