### ISSUE TITLE
MailKit: 'ß' is replaced through 'ss' before transcoding in punycode

### ISSUE THREAD

**Issue by samuraev** [jstedfast/MimeKit#801]

**Comment by jstedfast** [comment]
I think this is completely solved just doing this for MimeKit.

SmtpClient's static .ctor uses the IdnMapping class to get a default domain name for the local machine to use in EHLO commands. But this string can be manually overridden via a property on the SmtpClient.

**Comment by jstedfast** [comment]
MimeKit v3.4.0 has been released with this feature.
