### ISSUE TITLE
Support for message/feedback-report?

### ISSUE THREAD

**Issue by lukos** [jstedfast/MimeKit#810]
We are using MimeKit to parse error emails and one of them is in Abuse Reporting Format (https://en.wikipedia.org/wiki/Abuse_Reporting_Format), this uses a mime content type of message/feedback-report which is not supported by MimeKit so it gets read as a `MimePart` which then makes extraction of the standard properties a bit of a mare.

I'm wondering if there is any reason this isn't support and whether you are open to the idea of a PR to create a concrete type for FeedbackReport.

I could probably create the code needed with a little help pointing me to the right places. I also need to understand your use of the Visitor pattern because it looks like there is only 1 visitor and I don't know what it is used for.

**Comment by jstedfast** [comment]
Implemented.

**Comment by lukos** [comment]
Wow, that was quick. Thanks so much. Will test this week!

**Comment by jstedfast** [comment]
MimeKit v3.4.0 has been released with this feature.
