### ISSUE TITLE
How to Change style charset?

### ISSUE THREAD

**Issue by billpeace** [jstedfast/MimeKit#813]
Since customers only accept GB2312 
so we need charset=gb2312
How to modify charset in the style？

{font-family:微软雅黑;   How to set charset unicode for 微软雅黑

=================================================================
reply to a message

https://github.com/jstedfast/MimeKit/blob/1ee773f464d9bf8797e06f8ca26c0d9de31477d7/FAQ.md 
public class ReplyVisitor : MimeVisitor
{
	readonly Stack<Multipart> stack = new Stack<Multipart> ();
	MimeMessage original, reply;
	MailboxAddress from;
	bool replyToAll;

===============================================================

< !-- [if !mso]>< style>v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
w\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
< /style><![endif]--><style><!--
/* Font Definitions */
@font-face
	{font-family:Wingdings;
	panose-1:5 0 0 0 0 0 0 0 0 0;}
@font-face
	{font-family:宋体;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:等线;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Microsoft JhengHei";
	panose-1:2 11 6 4 3 5 4 4 2 4;}
@font-face
	{font-family:"\@Microsoft JhengHei";}
@font-face
	{font-family:微软雅黑;  How to set charset unicode？ 
	panose-1:2 11 5 3 2 2 4 2 2 4;}
@font-face
	{font-family:"\@微软雅黑";}
@font-face
	{font-family:"\@宋体";
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:"\@等线";
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:华文楷体;
	panose-1:2 1 6 0 4 1 1 1 1 1;}
@font-face
	{font-family:"\@华文楷体";}
/* Style Definitions */

**Comment by billpeace** [comment]
@font-face
	{font-family:=B5=C8=CF=DF;  how to change unicode  output ？
	panose-1:2 1 6 0 3 1 1 1 1 1;}

=============================================
@font-face
	{font-family:=CB=CE=CC=E5;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:PMingLiU;
	panose-1:2 1 6 1 0 1 1 1 1 1;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:=B5=C8=CF=DF;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:"\@=CB=CE=CC=E5";
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:"\@=B5=C8=CF=DF";
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:=BF=AC=CC=E5;
	panose-1:2 1 6 9 6 1 1 1 1 1;}
@font-face
	{font-family:"\@=BF=AC=CC=E5";}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"\@PMingLiU";
	panose-1:2 1 6 1 0 1 1 1 1 1;}
@font-face
	{font-family:=CE=C4=B6=A6=CA=E9=CB=CE=B7=B1;}

**Comment by jstedfast** [comment]
instead of doing this:

```csharp
var part = new TextPart (entity.ContentType.MediaSubtype.ToLowerInvariant ()) {
	Text = text
};
```

do this:

```csharp
var part = new TextPart (entity.ContentType.MediaSubtype.ToLowerInvariant ());
part.SetText ("gb2312", text);
```

**Comment by billpeace** [comment]
by add code   text.SetText(Encoding.GetEncoding("gb2312"), TextBody);

how to ?

Thanks

![image](https://user-images.githubusercontent.com/372286/177077534-37d7c45c-7757-4c8a-b168-0d658e2da494.png)


===========================================
MultipartAlternative alternative = null;
			MimeEntity body = null;

			if (HtmlBody != null) {
				var text = new TextPart ("html");
                               text.SetText(Encoding.GetEncoding("gb2312"), HtmlBody);
                               text.ContentTransferEncoding = ContentEncoding.QuotedPrintable;

				MimeEntity html;

				if (LinkedResources.Count > 0) {
					var related = new MultipartRelated {
						Root = text
					};

					foreach (var resource in LinkedResources)
						related.Add (resource);

					html = related;
				} else {
					html = text;
				}

				if (alternative != null)
					alternative.Add (html);
				else
					body = html;
			}

**Comment by jstedfast** [comment]
That has nothing to do with charsets. That's because your Content-Transfer-Encoding is set to `quoted-printable`.

Change it to 8bit:

```csharp
textPart.ContentTransferEncoding = ContentEncoding.EightBit;
```
