### ISSUE TITLE
TNEF extract attachments

### ISSUE THREAD

**Issue by biancapop** [jstedfast/MimeKit#814]
**Describe the bug**
Hello Jeff!!

If I send an email from OWA to the same domain the email is sent with TNEF. It I attach an email to that email - the attached mail is parsed as an attachment without format and cannot be read by OWA (you can read it in Outlook but it does not appear as an Outlook item).

**Platform (please complete the following information):**
 - OS: Centos 7/ Debian 10
 - .NET Runtime: .net 5.0
 - .NET Framework:  .net 5.0
 - MimeKit Version: 3.3

**To Reproduce**
1. Go to OWA
2. Create a new email and attach another email to it. 
3. Sent it to yourself or another Office365/Exchange domain
4. Check the result

**Expected behavior**
The email atttached should be parsed as an Outlook item and when clicked should open in OWA (it is downloaded right now).

**Code Snippets**

```csharp
            var tnef = Message.BodyParts.OfType<TnefPart>().FirstOrDefault();
            var tnefMail = tnef.ConvertToMessage();
            string tnefMailHtml = GetHtmlBody(tnefMail, Message.MessageId);
            BodyBuilder bb = new BodyBuilder();
            bb.TextBody = string.IsNullOrEmpty(tnefMail.TextBody) == true ? Message.TextBody : tnefMail.TextBody;
            bb.HtmlBody = string.IsNullOrEmpty(tnefMailHtml) == true ? Message.HtmlBody : tnefMailHtml;

            var attachments = tnef.ExtractAttachments();
            foreach (var attach in attachments)
            {
                if (bb.Attachments.Contains(attach))
                    continue;
                if (!bb.Attachments.Contains(attach) && attach.ContentDisposition != null && !attach.ContentDisposition.IsAttachment)
                    bb.Attachments.Add(attach);
                if (attach.ContentType.IsMimeType("text", "html"))
                {
                    TextPart tp = (TextPart)attach;
                    bb.HtmlBody = tp.Text;
                }
            }

            Message.Body = bb.ToMessageBody();
```

Thank you very much!!

**Comment by jstedfast** [comment]
Honestly, I don't understand what you are trying to do.

What would parsing something as an Outlook Item even look like? MimeKit doesn't parse Outlook Items, it just parses MIME.

An Outlook Item is not MIME compatible.

**Comment by biancapop** [comment]
No I don't try to do that. Sorry if I did not explained myself. I have to parse the mail email from TNEF to analyze it and after parsing I have to add a text line. But  when I parse it the attached mail gets corrupted for OWA. You can see in the images attached the way the mail is showed. I can send you the original mails.
Thank you
![correct](https://user-images.githubusercontent.com/26431690/177182988-a411e41e-8c8e-4bc3-b512-09ea9028d971.PNG)
![with error](https://user-images.githubusercontent.com/26431690/177182992-de3d48c9-dee0-4110-a55c-783e4c5f4428.PNG)
!

**Comment by jstedfast** [comment]
All I can recommend is to take a look at the source of the MIME messages and try to identify the difference(s).

Once you find the differences, let me know what they are, and I can help you achieve that.

**Comment by biancapop** [comment]
Hello!
I am really sorry that it took me so long to get back to this but here I am. I discovered that when you send an email from the OWA with another email as an attachment, the attached mail has this content type:
`Content-Type: application/vnd.ms-tnef; name=vacio`
But, when you send an email from Outlook it is generated with this content type:
`Content-Type: message/rfc822`

Of couse both mails are sent with TNEF and I checked the content type after parsing them.

So, as an workaround I tried to parse the vnd.ms-tnef part and convert it to a new mail, and attach that mail to the original:
```
if (attach.ContentType.IsMimeType("application", "vnd.ms-tnef") && attach is TnefPart tnefAttach)
{
    var mail = tnefAttach.ConvertToMessage();

    MemoryStream stream = new MemoryStream();
    mail.WriteTo(stream);
    stream.Position = 0; // you MUST reset stream position

    var attachmentPart = new MimePart("message", "rfc822")
    {
        Content = new MimeContent(stream),
        ContentId = "attach",
        ContentTransferEncoding = ContentEncoding.Base64,
        FileName = "attach"
    };
    
    if (attachmentPart != null && !bb.Attachments.Contains(attachmentPart))
        bb.Attachments.Add(attachmentPart);
}
```

The problem is that I lose content of that mail - for example if the attached mail has an pdf attached to it, it is lost trough the process.
How can I send an email attached to another propperly?
I hope I explained myself.

Thank you!!!!
