### ISSUE TITLE
Is it possible to skip the embedded messagePart when visit the message

### ISSUE THREAD

**Issue by kenizhou** [jstedfast/MimeKit#817]
Hello,

I have eml file which has an eml attachment in it. I am using the ""MimeVistor" to extract the mailbody, but found that I got the mail body of the embedded eml.

I noticed the sample code to treat the first one as the really one.  is it possible to add an option to skip the visit of the embedded messagepart.

![image](https://user-images.githubusercontent.com/614477/178418235-5fb1f6aa-302b-41a5-801d-c96e2dec1645.png)

BTW,  is there any method provide on "MimeEntity" to write the original file to file system.
e.g. I have an "xxxx.docx" attachment,  I can write to the "xxxx.docx" to file system directly, instead of the base64 encode data.

Thanks for your great works again!

**Comment by jstedfast** [comment]
You could override the `VisitMessagePart()` method and make it no-op (or addd it to a list of attachments if you want to do that instead).

**Comment by kenizhou** [comment]
Noted, thanks for your advice!
