### ISSUE TITLE
MimeMessage.CreateFromMailMessage throws System.ObjectDisposedException: Cannot access a closed Stream when AlternateViews are present

### ISSUE THREAD

**Issue by Aburel** [jstedfast/MimeKit#818]
**Describe the bug**
Calling MimeMessage.CreateFromMailMessage(message), where message is a MailMessage with at least one item in the AlternateViews collection, will throw.

**Error**
System.ObjectDisposedException: Cannot access a closed Stream. 

**Stack Trace**
   at System.IO.Stream.CopyTo(Stream destination)
   at MimeKit.MimeMessage.GetMimePart(AttachmentBase item)
   at MimeKit.MimeMessage.AddLinkedResources(MultipartAlternative alternative, MimePart root, AlternateView view)
   at MimeKit.MimeMessage.AddAlternateViews(MimeEntity body, AlternateViewCollection alternateViews)
   at MimeKit.MimeMessage.CreateFromMailMessage(MailMessage message)

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Framework: .NET 4.8
 - MimeKit Version: 3.3.0

**To Reproduce**
1. Instantiate a MailMessage object
2. Add an item to the AlternateViews collection
3. Call MimeMessage.CreateFromMailMessage(mailMessage)

**Expected behavior**
No error.

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
            var mailMessage = new MailMessage();
            var response = await http.GetAsync(imageUrl, HttpCompletionOption.ResponseContentRead);
            using (var stream = await response.Content.ReadAsStreamAsync())
            {
                var inline = new LinkedResource(stream);
                //inline.ContentId = name;
                //inline.ContentType.Name = name;

                var imageContentUrl = @"cid:" + inline.ContentId;
                mailMessage.Body = mailMessage.Body.Replace(imageUrl, imageContentUrl);
                inline.ContentLink = new Uri(imageContentUrl);

                var alternateView = AlternateView.CreateAlternateViewFromString(mailMessage.Body, null, MediaTypeNames.Text.Html);
                alternateView.LinkedResources.Add(inline);
                mailMessage.AlternateViews.Add(alternateView);
            }
```

**Additional context**

**Comment by jstedfast** [comment]
The problem is that your MailMessage object references a disposed stream at the end of the using statement.
