### ISSUE TITLE
Improve MimeKit's TNEF support

### ISSUE THREAD

**Issue by jstedfast** [jstedfast/MimeKit#82]
The TNEF API is based on Microsoft's [Microsoft.Exchange.Data.ContentTypes.Tnef](http://msdn.microsoft.com/en-us/library/Microsoft.Exchange.Data.ContentTypes.Tnef(v=exchg.150).aspx) API, but MimeKit's implementation is missing the ability to write TNEF data.

MimeKit's implementation currently also has a few `NotImplementedException`s for things I couldn't figure out what they did (and none of the docs I could find online or the samples I could find even mentioned them). If someone happens to have access to this framework, maybe they could tinker with it and figure out what those 2 or 3 properties were used for.

**Comment by Sicos1977** [comment]
Hi,

I'm busy with writing an assembly to create MSG files. I've documented most of the known MAPI properties. I also did run into a lot of TNEF properties. Maybe that there are tags that you are missing.

Greetings,
Kees van Spelde

**Comment by jstedfast** [comment]
I was actually referring to the following properties on TnefPropertyReader:

1. [IsComputedProperty](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Tnef/TnefPropertyReader.cs#L79)
2. [IsLargeValue](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Tnef/TnefPropertyReader.cs#L101)
3. [ObjectIid](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Tnef/TnefPropertyReader.cs#L145)

**Comment by Sicos1977** [comment]
Ok... didn't know that, thought you were talking about the TNEF (MAPI) property tags :-)

**Comment by jstedfast** [comment]
No worries :-)

**Comment by Sicos1977** [comment]
I see that you did find my office ole extractor :-)

I did a quick search on github for C# projects that might be able to extract stuff from OLE files and I found this: https://github.com/Sicos1977/OfficeExtractor

**Comment by jstedfast** [comment]
Yea, that looks familiar.

**Comment by Sicos1977** [comment]
Still strange that Microsoft did not implement native support for OLE and structured storage and other formats that are still used a lot. I never like to use PINVOKE and things like that.

**Comment by jstedfast** [comment]
Since no one actually seems to care about these 3 methods, I've removed them. Will revisit on a case-by-case basis as developers find they need them (at which point they'll be able to tell me what they do!)
