### ISSUE TITLE
MimeMessage.TextBody doesn't return a expected value (CSS codes remaining)

### ISSUE THREAD

**Issue by NakaYuzu** [jstedfast/MimeKit#822]
Due to wanted to save mail message's sender, subject, body, etc to SQLite databases,
I expected MimeMessage.TextBody property returns a value with raw text only (No HTML/CSS codes).
But it seems doesn't work as expected, CSS codes in message were still remaining.

Screenshot: https://imgur.com/a/VM1rYw5

Is this a bug or not? If not, I really want to know a way to remove all CSS codes..

**Comment by jstedfast** [comment]
That's the expected result if the message body contains html and css code.

**Comment by NakaYuzu** [comment]
Thanks for real quick response.
