### ISSUE TITLE
'MimeKit.ParserOptions' throws an exception on Windows Server 2016 Standard (WPF XAML app)

### ISSUE THREAD

**Issue by washburnit** [jstedfast/MimeKit#828]
Hi,

I'm getting that exception when sending a mail on a program that I developed and installed on a Windows Server 2016 Standard.
The exception is: The type initializer of 'MimeKit.ParserOptions' threw an exception.
If I run the program inside MS Visual Studio (Pro 2019) on my PC everything works perfectly and messages are sent (Windows 10 PRO 21H2 build 19044.1889) .
If I run the program on the mentioned server the exception occurs, no matter if the program is compiled at 32 or 64 bit.
The program is developed with:

- language C#
- WPF XAML kind of application
- .NET Framework 4.7.2
- MimeKit v3.3.0

I have also an old version of the same program that is not a "WPF XAML" kind but it's "standard" Windows application and it works also on Windows Server 2016.
So the issue seems to occur on WPF XAML applications under Windows Server 2016 (I didn't try other server OS version).
Have you ever checked MimeKit on a WPF XAML application?
What could be the cause of the exception?
Thank you, regards.

Roberto

**Comment by jstedfast** [comment]
What is the exception you are getting? Is it this? https://github.com/jstedfast/MimeKit/issues/816

**Comment by washburnit** [comment]
No, this is the complete excpetion description got from Windows Event Viewer:

Informazioni sull'eccezione: System.IO.FileLoadException
   in MimeKit.Utils.CharsetUtils..cctor()

Informazioni sull'eccezione: System.TypeInitializationException
   in MimeKit.ParserOptions..ctor()
   in MimeKit.ParserOptions..cctor()

Informazioni sull'eccezione: System.TypeInitializationException
   in MimeKit.MimeMessage..ctor()
   in MailSRV.MainWindow.InviaMail(System.String, System.String, System.String)
   in MailSRV.MainWindow.btTest_Click(System.Object, System.Windows.RoutedEventArgs)
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   in System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   in System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   in System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   in System.Windows.Controls.Primitives.ButtonBase.OnClick()
   in System.Windows.Controls.Button.OnClick()
   in System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   in System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   in System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   in System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   in System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   in System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   in System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   in System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   in System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   in System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   in System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   in System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   in System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   in System.Windows.Input.InputManager.ProcessStagingArea()
   in System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   in System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   in System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   in System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   in System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   in MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   in MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   in MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   in System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   in System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   in System.Windows.Application.RunDispatcher(System.Object)
   in System.Windows.Application.RunInternal(System.Windows.Window)
   in System.Windows.Application.Run(System.Windows.Window)
   in System.Windows.Application.Run()
   in MailSRV.App.Main()

it's in italian but "informazioni sull'eccezione" means  (more or less) "information about exception".

**Comment by washburnit** [comment]
I tried also to install the "MimeKit v3.3.0.517" but the exception did't fixed.

**Comment by jstedfast** [comment]
It's the same problem.

**Comment by jstedfast** [comment]
What you need to do is this:

* Install the System.Text.Encodings.CodePages nuget package
* In your application startup logic, add the following code snippet:

```csharp
System.Text.Encoding.RegisterProvider (System.Text.CodePagesEncodingProvider.Instance);
```

**Comment by washburnit** [comment]
- the System.Text.Encoding.CodePages package was already installed (v6.0.0)
- I added the suggested snippet but the exception still occurs :(

**Comment by jstedfast** [comment]
Then it's time for you to set some breakpoints and figure it out :)

**Comment by washburnit** [comment]
I will try, thanks.

**Comment by jstedfast** [comment]
Try 3.4.0

**Comment by washburnit** [comment]
Hi,
I've tried v3.4.0 but unfortunately the error still appears.

**Comment by washburnit** [comment]
I will check it tomorrow and I will let you know.
