### ISSUE TITLE
Add some sort of TextConverter API

### ISSUE THREAD

**Issue by jstedfast** [jstedfast/MimeKit#83]
Something like the [Microsoft.Exchange.Data.TextConverter](http://msdn.microsoft.com/en-us/library/microsoft.exchange.data.textconverters(v=exchg.150).aspx) API to convert between plain text, HTML, and RTF would be extremely valuable to have in MimeKit.

I'm not sure if the Microsoft API should be cloned or if we should implement something based on MimeKit's IMimeFilter API instead.

I've written a text -> HTML converter in the past for my other MIME library ([GMime](http://spruce.sourceforge.net/gmime/)) as part of [gmime-filter-html.c](https://git.gnome.org/browse/gmime/tree/gmime/gmime-filter-html.c)

Likewise, I have a text to enriched converter in [gmime-filter-encriched.c](https://git.gnome.org/browse/gmime/tree/gmime/gmime-filter-enriched.c)

**Comment by mgmiles** [comment]
Have you been able to do any work on the text converter?

**Comment by jstedfast** [comment]
Not yet, I haven't had time to work on it. It's still in the planning phase I guess you could say since I'm still not sure which API I'd like to have.

**Comment by jstedfast** [comment]
there's a bit of work on this now that lives in the `text-converter` branch. The TextToText, TextToHtml, FlowedToText and FlowedToHtml converters are more-or-less complete at this point, but other converters are not there yet.

**Comment by jstedfast** [comment]
this is implemented in master now

**Comment by mgmiles** [comment]
> this is implemented in master now

Cool, thanks.

-- 
Best wishes,
Malcolm
