### ISSUE TITLE
Receiving System.FormatException: End of stream

### ISSUE THREAD

**Issue by abid76** [jstedfast/MimeKit#833]
**Describe the bug**
When reading an incoming mail via IMAP, we sometimes receive the following Exception:
> System.FormatException: End of stream.
  bei MimeKit.MimeParser.ParseMessage(Byte* inbuf, CancellationToken cancellationToken)
  bei MimeKit.MimeParser.ParseMessage(CancellationToken cancellationToken)
  bei [MailKit.Net](http://mailkit.net/).Imap.ImapEngine.<ParseMessageAsync>d__200.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
  bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  bei [MailKit.Net](http://mailkit.net/).Imap.ImapFolder.<ParseMessageAsync>d__250.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
  bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  bei [MailKit.Net](http://mailkit.net/).Imap.ImapFolder.<GetMessageAsync>d__273.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
  bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  bei MailKit.Net.Imap.ImapFolder.GetMessage(UniqueId uid, CancellationToken cancellationToken, ITransferProgress progress)

**Platform (please complete the following information):**
 - OS: Windows 11
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET 4.6.1
 - MimeKit Version: 2.5.1

I'd like to know what is the reason for this error and if there is anything I can do to avoid it:
- Is it a networking issue?
- Is it a bug in MimeKit?
- Is there a problem within the received mail?
- Is it something I can fix/workaround inside C# or is there a problem in the infrastructure?

**Comment by abid76** [comment]
I rather wouldn't like to attach the related mail as it contains sensible information. Please let me know if the bug report is not sufficient and you need any further information.

**Comment by jstedfast** [comment]
There's only 1 place in MimeKit's parser that throws that exception and it only happens if it can't find the message headers.

Are you really using MimeKit 2.5.1? Please try upgrading. That version is ancient.

**Comment by abid76** [comment]
Ok thank you. I'll try an upgrade. Let's see if that will help.
