### ISSUE TITLE
How to parse multipart/form-data body?

### ISSUE THREAD

**Issue by ducktype** [jstedfast/MimeKit#84]
Hi, i'm trying to parse the various parts of an asp.net http multipart/form-data post with MimeKit,
without putting all the data in memory (by defautl asp.net load all in memory) to allow huge uploads from clients.

I'm parsing from the HttpContext.Current.Request.GetUnbufferedInputStream() which is not seekable.

MimeParser.ParseMessage(inputstream) says that is unable to load the headers, and it's right because asp.net has already loaded the http headers including the Content-Lenght and the Content-Type: multipart/form-data; boundary= xxxxxx, and leaved us only with the body part in the input stream.

But also MimeParser.ParseEntity(inputstream) is not useful here because although no error are given seems to not know about the fact the message is multipart and return a single entity that comprise the whole message including the other parts.

In the inputstream we find something like that:

-----------------------------9051914041544843365972754266
Content-Disposition: form-data; name="text"

text default
-----------------------------9051914041544843365972754266
Content-Disposition: form-data; name="file1"; filename="a.txt"
Content-Type: text/plain

Content of a.txt.

-----------------------------9051914041544843365972754266
Content-Disposition: form-data; name="file2"; filename="a.html"
Content-Type: text/html

<!DOCTYPE html><title>Content of a.html.</title>

-----------------------------9051914041544843365972754266--

Someone can suggest how can i load/parse this "multipart body" incrementally without loading all into memory with mimekit?

Thank you in advice!

**Comment by Faniedt** [comment]
```
using (HttpWebResponse response = request.GetResponse() as HttpWebResponse)
                {
                    MimeEntity mimeEntity = ParseMultipartFormData(response);
                    Multipart multiPart = new Multipart();
                    multiPart = (Multipart)mimeEntity;
                    int i = 1;
                    byte[] pdfDoc = null;
                    foreach (var attacment in multiPart.OfType<MimePart>())
                    {
                        
                        string fileName = string.Format("attachment.{0}.dat", i++);
                        using (var stream = File.Create(fileName))
                        {
                            attacment.ContentObject.DecodeTo(stream);
                            using (MemoryStream ms = new MemoryStream())
                            {
                           
                                attacment.ContentObject.DecodeTo(ms);
                                pdfDoc = ms.ToArray();

                                try
                                {
                                    File.WriteAllBytes("content" + i.ToString() + ".pdf", pdfDoc);
                                }
                                catch (Exception e)
                                {
                                    Console.WriteLine(e.Message);
                                    Console.ReadLine();
                                }
                            }
                        }                       
                    }
```

How can I remove the boundary at the end of the file/stream?

 --uuid:cb104084-5a5c-4404-b417-166d6f069b4f
Content-Type: application/xop+xml; charset=ISO-8859-1; type="multipart/related; type=\"application/xop+xml\"; boundary=\"uuid:164764d1-5057-48fb-9849-f8c816f51ef1\"; start=\"<root.message@cxf.apache.org>\"; start-info=\"text/xml\""
Content-Transfer-Encoding: binary
Content-ID: <root.message@cxf.apache.org>
