### ISSUE TITLE
Rfc2047 decoding incorrect characters

### ISSUE THREAD

**Issue by Elektrik1** [jstedfast/MimeKit#842]
**Describe the bug**
Since last upgrade (from NuGet) rfc2047 decoding for windows-1257 encoding is broken, thus resulting in incorrect sender names on received emails. Not sure if it is broken for other non-UTF-8 encodings as well.

**Platform:**
 - OS: Windows
 - .NET Framework: .NET 6
 - MimeKit Version: 3.4.1
 - options.International = false;

**To Reproduce**
Just call the `Rfc2047.DecodeText()` with example provided below.

**Expected behavior**
Expect `=?windows-1257?Q?Test=EB_Testut=EB?=` to be decoded to `Testė Testutė`, is decoded to `Testë Testutë` instead.

**Code Snippets**
Code to reproduce

```csharp
MimeKit.Utils.Rfc2047.DecodeText(Encoding.ASCII.GetBytes("=?windows-1257?Q?Test=EB_Testut=EB?=")).ToString()
```

**Additional context**
Was working fine before last update.
![image](https://user-images.githubusercontent.com/1433249/193288485-c6e3eb1c-ff4d-4685-bcdc-ba03426f2cfc.png)

**Comment by jstedfast** [comment]
At application startup, add this snippet of code:

```csharp
System.Text.Encoding.RegisterProvider (System.Text.CodePagesEncodingProvider.Instance);
```

**Comment by Elektrik1** [comment]
Oh, should have read the Readme. Sorry, and thanks!
