### ISSUE TITLE
Attachments not visible?!?

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MimeKit#845]
I just got an email which correctly shows 2 attachments (a .HTM and a .PDF 'file') in Outlook. However, in my app I would not see any attachment since MimeMessage.Attachments.ToList().Count == 0.

I also noticed that MimeMessage.Body is MultiPart and one of these parts even is another MultiPart.

Guess, my general questions are:
- it appears there is a different form of attachments than just with MimeMessage.Attachments, correct?
- how would I correctly access those 'non-standard' attachments? Is there any sample code by chance?

Thanks in advance

**Comment by jstedfast** [comment]
The MimeMessage.Attachments property scans the MIME structure to find MIME parts that have a `Content-Disposition` header where the value is `attachment`. If that header doesn't exist on the MIME part or if it has a value of `inline` (ignoring any parameters), then it is not considered an attachment.

What you may need to do is something more like this:

```csharp
var attachments = message.BodyParts.Where (x => x.ContentDisposition != null && x.ContentDisposition.FileName != null);
```

That will treat all body parts that have a `filename=` parameter specified on the Content-Disposition header no matter if the disposition value is `attachment` or `inline` or any other value.

If that doesn't work, then try this:

```csharp
var attachments = message.BodyParts.Where (x => (x.ContentDisposition != null && x.ContentDisposition.FileName != null) || x.ContentType.Name != null);
```

That will include all parts that the previous LINQ statement would include *plus* any body part that has a `name=` parameter in the `Content-Type` header. Typically, the `name=` parameter can be used as a filename.

**Comment by DierkDroth** [comment]
Thanks @jstedfast for your speedy reply. I'll look into. 
One question through: would I need to prepare for cases where your snippets would yield attachments which I already have with MimeMessage.Attachments?

Also, curious: is this a typical behavior for some mail clients? I never have experencied that before and don't know what mail client the sender was using....

**Comment by jstedfast** [comment]
> One question through: would I need to prepare for cases where your snippets would yield attachments which I already have with MimeMessage.Attachments?

If you end up using either of the code snippets I pasted above, don't use `message.Attachments` too - it will definitely overlap.

> Also, curious: is this a typical behavior for some mail clients? I never have experencied that before and don't know what mail client the sender was using....

A lot of clients that can display what the average email user considers to be attachments inline with the message body, and those clients will often attach files and give them a disposition of `inline` instead of `attachment`.

For example, if you drag & drop an image into your email composer window, you'll often have it be set as `inline` instead of `attachment`.

**Comment by DierkDroth** [comment]
Thansk again @jstedfast

**Comment by DierkDroth** [comment]
@jstedfast FYI 

I just had a case where again attachements would show in Outlook but not in my app.
Only as I tweaked your filter to
```MimeMessage.BodyParts.Where (x => x.ContentDisposition != null && (x.ContentDisposition.FileName != null || (x as MimePart)?.FileName != null))```
... would I see the attachments.

Funy stuff...
