### ISSUE TITLE
MimeMessage parsing does not support square brackets in Message-Id

### ISSUE THREAD

**Issue by mattfox-tdx** [jstedfast/MimeKit#849]
**Describe the bug**
When loading a MSG or EML file from disk, if the message-id for the email is encapsulated by square brackets [], the message id comes in null.

**Platform (please complete the following information):**
 - OS: [Windows, Linux]
 - .NET Runtime: [CoreCLR]
 - .NET Framework: [.NET 6]
 - MimeKit Version: 3.4.0

**To Reproduce**
Parse a EML file from disk using the MimeMessage.ParseAsync method with a message id that is encapsulated in square brackets (i.e. <[17c97c7a5a0b488799657c647ebc9172@domain.com]> and inspect the resulting populated MimeMessage object.

**Expected behavior**
A parsed messages will contain a non-null message-id

**Comment by jstedfast** [comment]
Ugh, more illegal syntax in a Message-Id...

**Comment by mattfox-tdx** [comment]
> Ugh, more illegal syntax in a Message-Id...

Yep, Microsoft alerts now seems to be generating ids in this format.

**Comment by jstedfast** [comment]
Would it be too much to ask you to just use the following code snippet for these messages?

```csharp
var msgid = message.Headers[HeaderId.MessageId];
msgid ??= msgid.TrimStart('<').TrimEnd('>').TrimStart('[').TrimEnd(']');
```
