### ISSUE TITLE
Multipart/alternative doesn't seem to consider attachments when reading TextBody

### ISSUE THREAD

**Issue by Archanian** [jstedfast/MimeKit#851]
**Describe the bug**
The documentation for TextBody states:
> Gets the text content of the first text/plain body part that is found (in depth-first search order) which is not an attachment

When parsing a message with `multipart/alternative` body, it appears to use the wrong part for TextBody. Looking at the code ([here](https://github.com/jstedfast/MimeKit/blob/57d26d9c0be22c2cf3e5ce87fe1dbcdae599e2ed/MimeKit/MultipartAlternative.cs#L196)), it seems like `MultipartAlternative` doesn't consider whether a part is an attachment or not when determining what to use for the TextBody.

**Platform (please complete the following information):**
 - OS: MacOS
 - .NET Runtime: .NET 6
 - .NET Framework: .NET 6
 - MimeKit Version: 2.8

**To Reproduce**
Given the following message:
```
From: sender@test.com
To: recipient@test.com
Subject: Test Message
Mime-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative;
 boundary="01GGTP1XKC29NFM3FKAWV3R537";
 charset=UTF-8

--01GGTP1XKC29NFM3FKAWV3R537
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

text part
--01GGTP1XKC29NFM3FKAWV3R537
Content-Type: text/plain; charset=UTF-8; filename=test.txt
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename=test.txt
Content-ID: <text@test.com>

attachment part
--01GGTP1XKC29NFM3FKAWV3R537--
```

Parse the message:
```
var stream = new MemoryStream(Encoding.UTF8.GetBytes(msg));
var message = await MimeMessage.LoadAsync(ParserOptions.Default, stream);
```
 
**Expected behavior**
I would expect `message.TextBody` to equal "text part", but instead it is "attachment part".

**Code Snippets**
Looking at this code here: https://github.com/jstedfast/MimeKit/blob/57d26d9c0be22c2cf3e5ce87fe1dbcdae599e2ed/MimeKit/MultipartAlternative.cs#L196
Should this check actually be something like:
```csharp
if (text != null && text.IsFormat (format) && !text.IsAttachment)
```

I understand that a more "correct" structure for a message like this would be to use a `multipart/mixed` container, but alas this type of message exists in the wild, and I was hoping TextBody would be able to handle it.

**Comment by jstedfast** [comment]
TextBody and HtmlBody are only really meant as convenience properties that work when the message follows standard practices (which this example message does not).

I'm not sure if it's worth trying to work around this bug in the sending client because it's probably just 1 perl script in the world that does this.

Keep in mind that every *conceivable* form of broken behavior exists *somewhere* in the wild, including marking legitimate text bodies as attachments. I would bet my life on it.

A proper fix would require examination of the content of the MIME parts to somehow determine if they contained "identical" content. That seems extremely complicated for what is only meant as a quick convenience implementation.

**Comment by Archanian** [comment]
Fair enough, I understand this is trying to deal with broken client behaviour, and this library shouldn't attempt to deal with every such case. I thought perhaps it might be a legitimate improvement to exclude attachments from consideration for these convenience properties, but if not that's fine - I appreciate you looking at this issue anyway.

FWIW this particular example might not be as rare as you think - Ruby's Mail [gem](https://github.com/mikel/mail) generates this exact structure with attachments and text/html parts inside a multipart/alternative container.
