### ISSUE TITLE
InferSharp analysis on MimeKit and MailKit

### ISSUE THREAD

**Issue by ofthelit** [jstedfast/MimeKit#852]
**Describe the bug**
I ran [InferSharp](https://github.com/microsoft/infersharp) on a code base and I noticed many of the issues found are related to MailKit.

**Platform (please complete the following information):**
 - OS: Windows, WSL
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET 6
 - MimeKit Version: 3.4.2 and/or 3.2.0

**To Reproduce**
More about the static analysis tool Infer# in this blogpost: https://devblogs.microsoft.com/dotnet/slaying-zombie-no-repo-crashes-with-infersharp/

**Expected behavior**
I expect all real issues to be solved.

**Additional context**
I do not know how many false positives are in here, but this is the whole list of issues related to MimeKit a scan displayed:

 #8
D:/src/MailKit/MailKit/Net/Imap/ImapClient.cs:91: error: Pulse Resource Leak
  Resource dynamically allocated by constructor MailKit.NullProtocolLogger() on line 91 is not closed after the last access at line 91, column 26.

#9
D:/src/MailKit/MailKit/Net/Pop3/Pop3Client.cs:2474: error: Pulse Resource Leak
  Resource dynamically allocated by constructor MimeKit.IO.MemoryBlockStream() on line 2462 is not closed after the last access at line 2474, column 6.

#10
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:295: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 294 is not closed after the last access at line 295, column 5.

#11
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:295: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 294 is not closed after the last access at line 295, column 5.

#12
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:436: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 435 is not closed after the last access at line 436, column 5.

#13
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:619: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 618 is not closed after the last access at line 619, column 5.

#14
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:735: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 734 is not closed after the last access at line 735, column 5.

#15
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:735: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 734 is not closed after the last access at line 735, column 5.

#16
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:900: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 899 is not closed after the last access at line 900, column 5.

#17
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:900: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 899 is not closed after the last access at line 900, column 5.

#18
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:1088: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 1087 is not closed after the last access at line 1088, column 5.

#19
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:1088: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 1087 is not closed after the last access at line 1088, column 5.

#20
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:1276: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 1275 is not closed after the last access at line 1276, column 5.

#21
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:1276: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 1275 is not closed after the last access at line 1276, column 5.

#22
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:1475: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 1474 is not closed after the last access at line 1475, column 5.

#23
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:1475: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 1474 is not closed after the last access at line 1475, column 5.

#24
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:1661: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 1660 is not closed after the last access at line 1661, column 5.

#25
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:1661: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 1660 is not closed after the last access at line 1661, column 5.

#26
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:1863: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 1862 is not closed after the last access at line 1863, column 5.

#27
D:/src/MimeKit/MimeKit/Cryptography/ApplicationPkcs7Mime.cs:1863: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 1862 is not closed after the last access at line 1863, column 5.

#28
D:/src/MimeKit/MimeKit/Cryptography/BouncyCastleSecureMimeContext.cs:557: error: Pulse Resource Leak
  Resource dynamically allocated by constructor MimeKit.MimeContent(), indirectly via call to `ApplicationPkcs7Signature(...)` on line 556 is not closed after the last access at line 557, column 3.

#29
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:454: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 453 is not closed after the last access at line 454, column 5.

#30
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:454: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 453 is not closed after the last access at line 454, column 5.

#31
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:573: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 572 is not closed after the last access at line 573, column 5.

#32
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:573: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 572 is not closed after the last access at line 573, column 5.

#33
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:980: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 979 is not closed after the last access at line 980, column 5.

#34
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:980: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 979 is not closed after the last access at line 980, column 5.

#35
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:1107: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 1106 is not closed after the last access at line 1107, column 5.

#36
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:1107: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 1106 is not closed after the last access at line 1107, column 5.

#37
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:1819: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 1818 is not closed after the last access at line 1819, column 5.

#38
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:1819: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 1818 is not closed after the last access at line 1819, column 5.

#39
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:1904: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 1903 is not closed after the last access at line 1904, column 5.

#40
D:/src/MimeKit/MimeKit/Cryptography/MultipartEncrypted.cs:1904: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 1903 is not closed after the last access at line 1904, column 5.

#41
D:/src/MimeKit/MimeKit/Cryptography/MultipartSigned.cs:468: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 467 is not closed after the last access at line 468, column 5.

#42
D:/src/MimeKit/MimeKit/Cryptography/MultipartSigned.cs:468: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 467 is not closed after the last access at line 468, column 5.

#43
D:/src/MimeKit/MimeKit/Cryptography/MultipartSigned.cs:648: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 647 is not closed after the last access at line 648, column 5.

#44
D:/src/MimeKit/MimeKit/Cryptography/MultipartSigned.cs:648: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 647 is not closed after the last access at line 648, column 5.

#45
D:/src/MimeKit/MimeKit/Cryptography/MultipartSigned.cs:886: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Data.DataTable(), indirectly via call to `CryptographyContext.Create(...)` on line 885 is not closed after the last access at line 886, column 5.

#46
D:/src/MimeKit/MimeKit/Cryptography/MultipartSigned.cs:886: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Net.Http.HttpClient(), indirectly via call to `CryptographyContext.Create(...)` on line 885 is not closed after the last access at line 886, column 5.

#47
D:/src/MimeKit/MimeKit/Cryptography/OpenPgpContext.cs:2781: error: Pulse Resource Leak
  Resource dynamically allocated by constructor MimeKit.MimeContent() on line 2777 is not closed after the last access at line 2781, column 3.

#48
D:/src/MimeKit/MimeKit/Cryptography/WindowsSecureMimeContext.cs:288: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Security.Cryptography.X509Certificates.X509Certificate2() on line 271 is not closed after the last access at line 288, column 5.

#49
D:/src/MimeKit/MimeKit/Cryptography/WindowsSecureMimeContext.cs:733: error: Pulse Resource Leak
  Resource dynamically allocated by constructor MimeKit.MimeContent(), indirectly via call to `ApplicationPkcs7Signature(...)` on line 732 is not closed after the last access at line 733, column 3.

#50
D:/src/MimeKit/MimeKit/Cryptography/WindowsSecureMimeContext.cs:825: error: Pulse Resource Leak
  Resource dynamically allocated by constructor MimeKit.MimeContent(), indirectly via call to `ApplicationPkcs7Signature(...)` on line 824 is not closed after the last access at line 825, column 3.

#51
D:/src/MimeKit/MimeKit/Cryptography/WindowsSecureMimeContext.cs:1517: error: Pulse Resource Leak
  Resource dynamically allocated by constructor System.Security.Cryptography.X509Certificates.X509Certificate2() on line 1517 is not closed after the last access at line 1517, column 4.

#52
D:/src/MimeKit/MimeKit/ExperimentalMimeParser.cs:487: error: Pulse Resource Leak
  Resource dynamically allocated by constructor MimeKit.MimeContent() on line 487 is not closed after the last access at line 487, column 4.

#53
D:/src/MimeKit/MimeKit/MessageDeliveryStatus.cs:183: error: Pulse Resource Leak
  Resource dynamically allocated by constructor MimeKit.IO.MemoryBlockStream() on line 175 is not closed after the last access at line 183, column 4.

#54
D:/src/MimeKit/MimeKit/MimeEntity.cs:1820: error: Pulse Resource Leak
  Resource dynamically allocated by constructor MimeKit.IO.ChainedStream() on line 1815 is not closed after the last access at line 1820, column 4.

#55
D:/src/MimeKit/MimeKit/MimeEntity.cs:1872: error: Pulse Resource Leak
  Resource dynamically allocated by constructor MimeKit.IO.ChainedStream() on line 1867 is not closed after the last access at line 1872, column 4.

#56
D:/src/MimeKit/MimeKit/MimeParser.cs:1695: error: Pulse Resource Leak
  Resource dynamically allocated by constructor MimeKit.IO.MemoryBlockStream() on line 1695 is not closed after the last access at line 1695, column 4.

**Comment by jstedfast** [comment]
8. False positive. This is closed in the ImapClient.Dispose() method.
9. Valid "leak" (in exceptional cases). That said, MemoryBlockStream is fully managed, so it would have been cleaned up by the GC anyway - same as any allocated byte[] would get cleaned up by the GC.
10. Valid leak.
11. False positive. The HttpClient is properly disposed when the SecureMimeContext is disposed.
12. False positive.
13. False positive.
14. Same leak as 10.
15. False positive.
16. Same leak as 10.
17. False positive.
18. Same leak as 10.
19. False positive.
20. Same leak as 10.
21. False positive.
22. Same leak as 10.
23. False positive.
24. Same leak as 10.
25. False positive.
26. Same leak as 10.
27. False positive.
28. False positive. The MimeContent is properly disposed when ApplicationPkcs7Signature gets disposed.
29. Same leak as 10.
30. False positive.
31. Same leak as 10.
32. False positive.
33. Same leak as 10.
34. False positive.
35. Same leak as 10.
36. False positive.
37. Same leak as 10.
38. False positive.
39. Same leak as 10.
40. False positive.
41. Same leak as 10.
42. False positive.
43. Same leak as 10.
44. False positive.
45. Same leak as 10.
46. False positive.
47. Same as 28.
48. Valid potential leak in exceptional cases where X509Certificate2 is disposable (only in newer frameworks).
49. Same as 28.
50. Same as 28.
51. Valid leak for newer .NET versions where X509Certificate2 is disposable.
52. Possible leak. Need to look into it more...
53. Fixed.
54. Valid IFF the input stream is not seekable. Modified to make this not matter and use persistent=false & always dispose the ChainedStream.
55. Same exact issue as 54 but for the LoadAsync method.
56. Valid potential leak if the underlying stream throws an exception for some reason. That said, the MemoryBlockStream is fully managed, so not really a leak in the practical sense.

**Comment by jstedfast** [comment]
MimeKit v3.4.3 has been released with fixes for these.
