### ISSUE TITLE
How can I deal with deleted messages?

### ISSUE THREAD

**Issue by jfrank14** [jstedfast/MimeKit#853]
My program reads the mail files used by Thunderbird, using mbox format, and it works great *except* that when you delete a message in Thunderbird, it's not deleted from the actual mbox file until you compact that file. This causes my program to read messages that have been deleted.

Is there a way to compact the file programmatically OR tell that a message has been deleted OR tell the parser to ignore such deleted messages?

**Comment by jstedfast** [comment]
I believe that Thunderbird encodes the message flags in a X-{something} header (X-Mozilla-Thundbird, perhaps?).

I'm pretty sure it either has "Mozilla" or "Thunderbird" in the header field name (or both).

If I remember correctly, it is an encoded bit field and so you'll have to figure out which bit refers to the deleted flag.

Once you do that, you'll need to check that header for every message that you parse to see if it is deleted, if it is, ignore the message.
