### ISSUE TITLE
Failed to parse message headers when contains other data from mail server.

### ISSUE THREAD

**Issue by Miraichi** [jstedfast/MimeKit#856]
**Describe the bug**
When use HEADER.FIELDS (FROM) on UID FETCH, if response contains text with not only header, then receive FormatException.
Its mail server problem or MimeKit? If delete first line it fine load.

**Platform (please complete the following information):**
 - OS: [Windows]
 - .NET Runtime: [CoreCLR]
 - .NET Framework: [.NET 4.7.2]
 - MimeKit Version: 3.4.0.0

**To Reproduce**
[html.txt](https://github.com/jstedfast/MimeKit/files/9992207/html.txt)

**Code Snippets**
```csharp
var msg = MimeMessage.Load(new MemoryStream(Encoding.UTF8.GetBytes(File.ReadAllText("html.txt"))));

Console.WriteLine(msg.From.ToString());
Console.ReadKey();
```

**Comment by Miraichi** [comment]
Because its fine parsing without first line?

**Comment by jstedfast** [comment]
If I add a line of random text to the beginning of a jpeg file, will that jpeg render correctly in an image view?

Why not? It parses ok if I remove the first line of text.

**Comment by jstedfast** [comment]
Are you writing your own IMAP client? I'm just wondering how you ended up with the contents of your test file.
