### ISSUE TITLE
Output is not the same as input - Windows vs. Linux

### ISSUE THREAD

**Issue by mikkelbm** [jstedfast/MimeKit#866]
**Describe the bug**
As I have written a couple of times previously, we are using your brilliant framework to handle AS2 (and AS4) messages in our software.
Until now we have been working on .NET Framework and Windows only. But we are moving towards .NET6 and containers - and therefore Linux.
In that transformation we are in some cases facing a strange issue where our integrity-check (SHA1) fails, when we transmit AS2 messages to our own endpoint.

**Platform (please complete the following information):**
 - OS: Linux
 - .NET Framework: .NET6
 - MimeKit Version: 3.4.3
 - Visual Studio: 2022

**To Reproduce**
I have attached a test-project, that illustrates the problem.
We are using WSL to run our code in Linux (Ubuntu).
1. Open the test-project in Visual Studio
2. Run the tests using Windows configuration - both tests will succeed
3. Run the tests using Linux configuration (in our case WSL with Ubuntu) - the PDF test will fail and the xml test will succeed

Tests on Windows:
![image](https://user-images.githubusercontent.com/4942942/208100063-3ef945ec-93eb-4f09-8281-4dae1ae11fe8.png)

Test on Linux (WSL):
![image](https://user-images.githubusercontent.com/4942942/208100259-77343dba-94c0-4dd1-968d-c64fcd5fdcce.png)

**Expected behavior**
Output of the tests should be the same on both Windows and Linux.

**Additional context**
We must generate the MIC (message-integrity-check) based on the exact input on the mimepart/entity. 
Normally we receive a multipart, and the MIC must be generated based on the content-part of that multipart message. So we can't just use the original input-stream.

Any ideas on what's going on here? :-)

The test-project:
[MimeDifferentInputOutput.Test.zip](https://github.com/jstedfast/MimeKit/files/10245842/MimeDifferentInputOutput.Test.zip)

**Comment by jstedfast** [comment]
The problem is your test makes assumptions about line endings being identical on Mac/Linux and Windows (but they aren't).

Change your code to set a ContentTransferEncoding:

```csharp
[TestMethod]
        public void TestMethodIntegrityCheckPdf()
        {
            var pdfFileStream = File.OpenRead("TestFiles/TestPdf.pdf");

            var contentType = ContentType.Parse("application/octet-stream");
            using var mimeEntity = new MimePart(contentType)
            {
                Content = new MimeContent(pdfFileStream),
                ContentDisposition = new ContentDisposition(ContentDisposition.Attachment),
                ContentTransferEncoding = ContentEncoding.Base64
            };

            var streamOrg = new MemoryStream();
            mimeEntity.WriteTo(streamOrg);
            streamOrg.Position = 0;
            var integrityCheckValueOrg = CreateMIC(streamOrg);
            streamOrg.Position = 0;

            // .....

            var newEntity = MimeEntity.Load(streamOrg);
            var streamNew = new MemoryStream();
            newEntity.WriteTo(streamNew);
            streamNew.Position = 0;
            var integrityCheckValueNew = CreateMIC(streamNew);

            Assert.AreEqual(integrityCheckValueOrg, integrityCheckValueNew, $"Integrity-check failed. Expected: {integrityCheckValueOrg} actual: {integrityCheckValueNew}");
        }
```

Also, since PDFs are so sensitive to line endings, I highly recommend using base64 encoding.

Realistically, I would recommend setting an encoding for XML as well, but QuotedPrintable is suitable enough for that.

**Comment by mikkelbm** [comment]
Hi Jeffrey. 
Thanks for your reply. 
But that's not my assumption (or at least intention) :-) My assumption is that the output is the same as the input, when I use the WriteTo method. On Windows it's the same. But in Linux it's not the same. That should be what my test is showing.
Sure it should be base64 encoded from the "client", but we can't control what others are sending, so this could be a real scenario for us. And that's why it's interresting to know, why the framework behaves as it does.

What I actually need is the raw unmodified mime-part (incl. header), when I use the WriteTo method.

**Comment by jstedfast** [comment]
It's not the same scenario that you are testing, though.

When you parse a message and then write it back out, there is internal state that tracks what the line endings were and will maintain those line endings.

When you create a new message, those state variables are not set, and so it has to filter from DOS to UNIX or UNIX to DOS.
