### ISSUE TITLE
Eml file with Umlaut Symbols are getting as ?? in Text

### ISSUE THREAD

**Issue by hammadsajid786** [jstedfast/MimeKit#870]
I am trying to parse an .eml file with Sweedish characters in email. 
But characters from sweedish languages are returning as question mark (?) in TextBody. If I use Html embeded email with Emlaut symbols (Sweedish charcters). That works fine. Only problem with TextBody.

**Code Snippets**
```csharp
MimeKit.MimeMessage emlFromMimeKit = MimeKit.MimeMessage.Load("sample.eml");
var textBody= emlFromMimeKit?.TextBody;
// var htmlBody= emlFromMimeKit?.HtmlBody // This works fine If I use Html created email
```

**Expected Text Output**
`Test Email Message with 2 PDF files as attachments, Det här e-postmeddelandet är avsett för teständamål för att kontrollera om omljudssymboler stöds.`

**Additional context**
Sample FIle https://www.dropbox.com/s/68zpitz7z4305r9/sample%20%286%29.eml?dl=0

**Comment by jstedfast** [comment]
Here's the problem:

```
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Test Email Message with 2 PDF files as attachments, Det här e-postmeddelandet är avsett för teständamål för att kontrollera om omljudssymboler stöds.
```

Does that look like 7bit us-ascii? :-)

It's probably UTF-8, so you'll need to use:

```csharp
var textPart = emlFromMimeKit.BodyParts.OfType<TextPart>().FirstOrDefault();
var textBody = textPart.GetText(Encoding.UTF8);
```

**Comment by hammadsajid786** [comment]
Oh Yes, Now I understand.

So `eml` strings are parsed on base of Content-Type defined in `eml` files.
I had created this eml file by editing it for testing purposes.
