### ISSUE TITLE
SMTP Send RFC2047 characters cannot be converted

### ISSUE THREAD

**Issue by tr42v-v** [jstedfast/MimeKit#871]
RFC2047 SMTP Send characters cannot be converted
I'm having an error with the service I'm using.

My suggestion is, can't the property allow me to choose the upper or lower case?

**To Reproduce**
```
var msg = new MimeMessage();
message.Headers.Replase( Mimekit.HeaderID.Subject, Encoding.UTF8, "TESTハローワールド" );
message.Body = new TextPart(){ Text = "Hello World" };

smtp.Send(msg);
```

Result Smtp Trace Subject
`Subject: =?utf-8?b?VEVTVOODj+ODreODvOODr+ODvOODq+ODiQ==?=`

But the expected result is:　「?utf-8?B?」
`Subject: =?utf-8?B?VEVTVOODj+ODreODvOODr+ODvOODq+ODiQ==?=`

[Rfc2047.cs](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Utils/Rfc2047.cs)
The line below is for fixed.　
889line
``` 
output.Append(token.Encoding == ContentEncoding.Base64 ? 'b' : 'q');
```
1022line
```
if (CharsetRequiresBase64 (charset) || GetBestContentEncoding (word, 0, len) == ContentEncoding.Base64) {
	encoder = new Base64Encoder (true);
	encoding = 'b';
```

**Comment by jstedfast** [comment]
Seems to me that you should focus on fixing the SMTP server and not MimeKit or MailKit which are sending perfectly correct formatting.

**Comment by tr42v-v** [comment]
I also believe it's a server side issue.
However, it is difficult to modify the server side, so I am currently replacing it with Upper "B".
The email software I checked seemed to send it with "B", but is there a reason why Mimekit uses "b"?
Email software I've tried:
 Outlook
 Thunderbird
 Sylpheed
 gmail
