### ISSUE TITLE
TypeInitializationException in StepByteOrderMark (Base64Decoder, Framework 4.8)

### ISSUE THREAD

**Issue by at-andreas** [jstedfast/MimeKit#878]
After Upgrade from 3.1.1. to 3.4.x i got this Exception:
Used Framework: 4.8
exe Run as Windows-Service

Der Typeninitialisierer für "PerTypeValues`1" hat eine Ausnahme verursacht.
----------------------------------------------------
TypeInitializationException
   bei MimeKit.MimeParser.StepByteOrderMark(Byte* inbuf, Int32& bomIndex)
   bei MimeKit.MimeParser.StepByteOrderMark(Byte* inbuf, CancellationToken cancellationToken)
   bei MimeKit.MimeParser.Step(Byte* inbuf, CancellationToken cancellationToken)
   bei MimeKit.MimeParser.ParseMessage(Byte* inbuf, CancellationToken cancellationToken)
   bei MimeKit.MimeParser.ParseMessage(CancellationToken cancellationToken)
   bei MailKit.Net.Pop3.Pop3Client.DownloadHeaderContext.Parse(Pop3Stream data, CancellationToken cancellationToken)
   bei MailKit.Net.Pop3.Pop3Client.DownloadContext`1.OnDataReceived(Pop3Engine engine, Pop3Command pc, CancellationToken cancellationToken)
   bei MailKit.Net.Pop3.Pop3Client.DownloadContext`1.OnDataReceived(Pop3Engine engine, Pop3Command pc, String text, Boolean doAsync, CancellationToken cancellationToken)
   bei MailKit.Net.Pop3.Pop3Engine.ReadResponse(Pop3Command pc, CancellationToken cancellationToken)
   bei MailKit.Net.Pop3.Pop3Engine.Run(Boolean throwOnError, CancellationToken cancellationToken)
   bei MailKit.Net.Pop3.Pop3Client.GetMessageHeaders(Int32 index, CancellationToken cancellationToken)
   bei at.dateex.Web.Mail.MailboxHandler.GetMessageHeaders()
   bei at.dateex.modulex.Service.Tasks.MailboxWatcher.DoWorkInternal(FireModes triggerMode, Object customArgs) Die Datei oder Assembly "System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
----------------------------------------------------
FileLoadException
   bei System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   bei System.SpanHelpers.PerTypeValues`1..cctor()

i think the change from
static readonly byte[] base64_rank = new byte[256] {
to
static ReadOnlySpan<byte> base64_rank => new byte[256] {
is the reason for the exception.

File: MimeKit/Encodings/Base64Decoder.cs
Line: 40
Pull: 767

after change back to 3.1.1. everything works fine.

**Comment by jstedfast** [comment]
I suspect you meant `static ReadOnlySpan<byte> UTF8ByteOrderMark => new byte[] { 0xEF, 0xBB, 0xBF };` in MimeParser.cs because StepByteOrderMark() does not use the Base64Decoder at all.

That said, this isn't a MimeKit bug. It's a problem with your app.config file.

https://stackoverflow.com/questions/46981403/cannot-load-file-or-assembly-system-runtime
