### ISSUE TITLE
MailboxAddress.TryParse issue

### ISSUE THREAD

**Issue by kiru1283** [jstedfast/MimeKit#879]
We are using Mimekit 3.3.0 and utilizing the MailboxAddress.TryParse(string text, out MailboxAddress mailbox) method to validate the incoming email address before creating the email body.
Noticed that when we give something invalid like "123" as an emailid the method returns a TRUE. 
i.e MailboxAddress.TryParse("123", out validMailboxAddress) returns TRUE and causes problems down the line when we actually send the email.
Could you please check if this is a bug or something we need to fix on our end?

**Comment by jstedfast** [comment]
By default, `MailboxAddress.TryParse()` uses fairly loose RFC compliance.

What you probably want to do is this:

```csharp
var options = ParserOptions.Default.Clone ();
options.AddressParserComplianceMode = RfcComplianceMode.Strict;
options.AllowUnquotedCommasInAddresses = false;
options.AllowAddressesWithoutDomain = false;

MailboxAddress.TryParse(options, text, out var mailboxAddress)
```

**Comment by kiru1283** [comment]
Thank you for the explanation.
