### ISSUE TITLE
Question: I have an e-mail with no body that throws an exception when writing it to a stream

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MimeKit#882]
I use the latest version.

When using this code:

```c#
        using var headersStream = new MemoryStream();
        using var bodyStream = new MemoryStream();

        mimeMessage.WriteTo(headersStream, true);
        mimeMessage.Body.WriteTo(bodyStream, true);
```

The last line raises this exception: `The body stream length is 0 ... Parameter name: bodyStream`. I guess this is because the body part is empty. Is there a way to check if this one is empty before trying to write it to a stream? For now I just added a try and catch but that is kind of ugly in my eyes.

I'm reading this message from a Microsoft Exchange O365 server. The goal is to archive old emails so I guess I'm hitting some kind of corrupt e-mail

**Comment by jstedfast** [comment]
I don't see why mimeMessage.Body.WriteTo(bodyStream, true); would throw that error.

Are you sure it isn't a check you are doing after writing it?

**Comment by Sicos1977** [comment]
Uhm I have to loop deeper into my code to see if there is something else that can throw this. I'm als writing the stream to the database so I guess that can also be the point where it is raised...

**Comment by Sicos1977** [comment]
You are right... I even did throw that exception myself. Sorry for taking up your time :-)

```csharp
        if (bodyStream.CanSeek)
            bodyStream.Position = 0;

        var buffer = new byte[StreamBlockSize];
        var bytesRead = bodyStream.Read(buffer, 0, buffer.Length);

        if (bytesRead == 0)
            throw new ArgumentException("The body stream length is 0", nameof(bodyStream));
```
