### ISSUE TITLE
MimeKit fails to parse a "corrupt" email id

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MimeKit#889]
I used the latest nuget version on .net 4.8.

Sometimes we get e-mails from united airlines that generate very weird and corrupt id's. Is it possible to modify the mimekit code so that it is more tollerant to these kind of email id's ... even when they are corrupted like hell.

In this case we get an e-mail with this id.

`Message-ID: <15627601.388658.1676916781911.JavaMail."xxxxxx@united.com"@xxxxxxx.ual.com>`

I removed some names from the id and replaced it with xxxxx but that makes no difference for testing.

This is the error I get in my own code because the id is in this case returning null

```
Value cannot be null.
Parameter name: emailId
```

**Comment by jstedfast** [comment]
This is an actual bug in MimeKit and not technically a bug in the sending client (as odd as it might look).

Looks like I introduced this in a previous attempt to make the Message-Id parser more lenient.

Should be fixed now.

**Comment by Sicos1977** [comment]
Thanks for fixing.
