### ISSUE TITLE
Plaintext URLs containing question mark aren't converted correctly

### ISSUE THREAD

**Issue by SenaraW** [jstedfast/MimeKit#897]
Some of our customers get quite a lot of plaintext emails with links containing a ? like this: https://xxxxx.sophos.com?xxxxxxxxxxxx
Unfortunately the link doesn't get properly recognized, as everything after the ? won't be within the `<a href>`.
The resulting converted HTML looks like this:

```
<html>
<head>
<META content="text/html; charset=UTF-8" http-equiv=Content-Type></head>
  <body>This is a test for html links 
  <a href="https://xxxxx.sophos.com">https://xxxxx.sophos.com</a>?xxxxxxxxxxxx<br/>
  </body>
</html>
```

instead of this:

```
<html>
<head>
<META content="text/html; charset=UTF-8" http-equiv=Content-Type></head>
  <body>This is a test for html links 
  <a href="https://xxxxx.sophos.com?xxxxxxxxxxxx">https://xxxxx.sophos.com?xxxxxxxxxxxx</a><br/>
  </body>
</html>
```

I've attached a [Testprogram](https://github.com/jstedfast/MimeKit/files/10881013/HTMLTestConversion.zip) with which you can reproduce this behavior. It converts a plaintext eml using HTMLPreviewVisitor.

Tested in .NET 4.8 with Mimekit 3.3.0 and 3.5.0

**Comment by jstedfast** [comment]
It wasn't handled because I don't think that syntax is valid.

That said, I tested GMail and the Visual Studio's URL-detection (in comments) seemed to handle it, so I added support for it.
