### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MimeKit#901]
Yes I know MimeKit has a MIT license but are you okay with it that I copy the tnef reader part to my MSGReader project. Somebody asked for support for winmail.dat files that are sometimes inside MSG files. I can reinvent the wheel or just use your code with some modificatios in it :-)

I know I can just add MimeKit to the project but for the moment that is a little bit of overkill. I'm planning to do it in the feature because I want to get rid of some OpenPop.Net that is now inside MSGReader but for now that is to much work to remove.

**Comment by jstedfast** [comment]
I don't mind if you do that - obviously I'd prefer the copyright headers remain intact just to give credit where credit is due, but otherwise that's totally fine.

**Comment by Sicos1977** [comment]
> I don't mind if you do that - obviously I'd prefer the copyright headers remain intact just to give credit where credit is due, but otherwise that's totally fine.

Ofcourse I leave the copyright headers intact because I also like it when people do that when copying code from my projects.

I know I could just copy everything without asking but I prefer it to do it this way :-)

Keep up the good work with mimekit and mailkit
