### ISSUE TITLE
Question about some code in MimeKit's TnefReader

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MimeKit#903]
Just a question since I'm not an expert in unsafe code.

Is there a way to do the unsafe conversion for `Int32BitsToSingle` and `Int64BitsToDouble` without using unsafe code? I didn't use any unsafe code in MSGReader and don't want to enable that just for these 2 methods.

```c#
    static unsafe float Int32BitsToSingle(int value)
    {
        return *(float*)&value;
    }

    internal float ReadSingle()
    {
        var value = ReadInt32();

        return Int32BitsToSingle(value);
    }

    static unsafe double Int64BitsToDouble(long value)
    {
        return *(double*)&value;
    }

    internal double ReadDouble()
    {
        var value = ReadInt64();

        return Int64BitsToDouble(value);
    }
```

**Comment by Sicos1977** [comment]
I can just do this.... but I don't know if there is any reason why you decided to use pointers instead.

```c#
    internal static float Int32BitsToSingle(int value)
    {
        return value;
        // return *(float*)&value;
    }

    internal float ReadSingle()
    {
        var value = ReadInt32();
        return Int32BitsToSingle(value);
    }

    internal static double Int64BitsToDouble(long value)
    {
        return value;
        // return *(double*)&value;
    }

    internal double ReadDouble()
    {
        var value = ReadInt64();
        return Int64BitsToDouble(value);
    }
```

**Comment by jstedfast** [comment]
I started to reply yesterday but apparently got side-tracked.

So the problem with your solution is that it won't return the same results for all integer values.

Allow me to demonstrate:

```csharp
int value = -1693857308;

(float) value = -1.6938573E+09
*(float*)&value = -1.1397609E-22
```

**Comment by Sicos1977** [comment]
Okay good that I asked then why you used pointers instead. Any other way to make it work?

**Comment by jstedfast** [comment]
Yea:

BitConverter.Int32BitsToSingle(int value)

```
(float)-1693857308 = -1.6938573E+09
*(float*)&-1693857308 = -1.1397609E-22
BitConverter = -1.1397609E-22
```

I should probably modify MimeKit to use the same.

**Comment by jstedfast** [comment]
Oh, it seems to only be available for netstandard2.1+ and net6.0+ (maybe net5.0+?)

**Comment by jstedfast** [comment]
Ok, on net4x and netstandard2.0, you can do:

```csharp
var bytes = BitConverter.GetBytes (value);
return BitConverter.ToSingle (bytes, 0);
```

**Comment by jstedfast** [comment]
I just updated MimeKit master to use BitConverter

**Comment by Sicos1977** [comment]
Thanks for finding a solution for this
