### ISSUE TITLE
exception in send message

### ISSUE THREAD

**Issue by DevOnBike** [jstedfast/MimeKit#911]
**Describe the bug**
exception when sending email

**Platform (please complete the following information):**
 - OS: windows
 - .NET Runtime: .net 6
 - MimeKit Version: 3.6

**To Reproduce**
when wrapping message in using statement exception happens during send

**Expected behavior**
not throwing exception in using statement  

**Code Snippets**

```csharp
public Task SendAsync(EmailValueObject email)
        {
            Check.NotNull(email);

            using var emailMessage = email.ToMimeMessage(); <----- delete using and everything works but memory leak is possible
            return ExecuteAsync(emailMessage);
        }
        
        private async Task ExecuteAsync(MimeMessage emailMessage)
        {
           
            using var client = new SmtpClient();

            await client.ConnectAsync(_configuration.Host, _configuration.Port, _configuration.Ssl);
            client.AuthenticationMechanisms.Remove("XOAUTH2");

            if (_configuration.RequiresAuthentication)
            {
                
                await client.AuthenticateAsync(_configuration.AuthenticationEmail, _configuration.AuthenticationPassword, CancellationToken.None);
            }

            
            **await client.SendAsync(emailMessage); <------- here comes exception**
            


            await client.DisconnectAsync(true);

        }
```
**Additional context**
exception:
System.ObjectDisposedException
Cannot access a disposed object.
Object name: 'MimePart'.
   at MimeKit.MimePart.Prepare(EncodingConstraint constraint, Int32 maxLineLength)
   at MailKit.Net.Smtp.SmtpClient.Prepare(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, SmtpExtensions& extensions)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, CancellationToken cancellationToken, ITransferProgress progress)

**Comment by jstedfast** [comment]
You need to `await` the `ExecuteAsync` call.
