### ISSUE TITLE
Custom header encoding is discarded

### ISSUE THREAD

**Issue by axunonb** [jstedfast/MimeKit#92]
message.Subject = "testäüö";
message.Headers.Replace(HeaderId.Subject, Encoding.UTF8, message.Subject). 
=> Message Subject Header has
     Subject: =?iso-8859-1?b?dGVzdPbk/A==?=
     instead of
     Subject: =?UTF-8?B?dGVzdMOkw7zDtg==?=

Same happens with 
message.To.Add(new MailboxAddress(Encoding.UTF8, "testäüö", "addr@mail.com"));
=>  message.To[0] has UTF8Encoding - fine
But finally the message To Header is changed to "iso-8859-1" encoding, instead of keeping UTF8.

Looks like custom encoding is discarded for all headers.

**Comment by jstedfast** [comment]
I just released MimeKit 1.0.4 to NuGet this morning with this fix.
