### ISSUE TITLE
HeaderIdExtensions.ToHeaderName is slow

### ISSUE THREAD

**Issue by alex-jitbit** [jstedfast/MimeKit#920]
The `HeaderIdExtensions.ToHeaderName` method is slow.

1. It uses `enum.ToString` (slow)
2. It uses reflection to `GetCustomAttributes` (slow)
3. Is uses `StringBuilder` to insert dashes into header name

I traced my production server width `dotnet-trace` and it seems 0.5% of the CPU load (out of 35%) is wasted on this method.

Would you be open to hard-coded mapping of header enum to string header names? If you are, I will submit a PR that fixes this. Feel free to reject it.

I looked ta the file commit history and it looks like the last time you've added a new header to this `enum` was back in 2018, and 2015 before that. Seems like hardcoding is logical b/c this thing does not change very often - but we still sacrifice performance in favor of code readability/maintenability here.

Awaiting your decicion and will start working on a PR.

**Comment by jstedfast** [comment]
Yea, makes sense. Thanks for the suggestion!

**Comment by alex-jitbit** [comment]
Just forked the repo to start working on this and realized you've already done it. Thanks ❤
