### ISSUE TITLE
DKIM validation fails - for mixedpart bodies?

### ISSUE THREAD

**Issue by jol64** [jstedfast/MimeKit#922]
I am trying to use MimeKit in an application to validate DKIM signatures. It works in some cases and fails in others. During my attempts to track down the issue, I discovered the body hash validation fails.

Reading https://github.com/jstedfast/MimeKit/issues/658 I then tried uploads of various messages I created to https://www.appmaildev.com/en/dkimfile, and it looks like validation fails for "HTML" mails using Content-Type: multipart/alternative.
The actual receiving email server instead adds a header `Authentication-Results: spf=pass (sender IP is *)  smtp.mailfrom=*; dkim=pass (signature was verified)`.

I do understand this is just an initial hypotheses, but may be you can suggest other variations to track down the issue and also a means to privately share the files.

**Comment by jstedfast** [comment]
You can email files to me directly (email address can be found on my GitHub profile page).
