### ISSUE TITLE
Failed to parse message headers.

### ISSUE THREAD

**Issue by Yamee** [jstedfast/MimeKit#93]
Hi,

I am trying to use the MIMEKit in one of my projects that need to load a outlook MSG (.msg format) from filesystem and it throws  "Failed to parse message headers." 
  var objMsg = MimeMessage.Load("C:\Test\sample.msg");

When IDoes this work for .MSG format or just .eml? tried to parse the aboving mime, it was failed. Could you kindly let me know what happened?

**Comment by jstedfast** [comment]
Any chance you could send me a sample message that failed to parse?

**Comment by jstedfast** [comment]
Closing due to lack of response.
