### ISSUE TITLE
Message parsing in case of bad content-type header

### ISSUE THREAD

**Issue by mivra** [jstedfast/MimeKit#94]
We received an email message which could not be properly parsed by MimeKit. It seems it's caused by the headers in the message, which are not properly separated by a new line. Not sure if this is valid by the standard, probably not. 
`Content-Type: text/plain; charset = "iso-8859-1" Content-Transfer-Encoding: 8bit`

Any chance to "fix" it in a way message.HtmlBody property returns the proper content? Mail clients are able to display it.
EML here: http://www.filedropper.com/badmessage_2

**Comment by jstedfast** [comment]
I just released MimeKit 1.0.4 to NuGet this morning with this fix.

**Comment by mivra** [comment]
Wonderful, thank you!
