### ISSUE TITLE
Support for custom location of certificates store.

### ISSUE THREAD

**Issue by advanced373** [jstedfast/MimeKit#947]
**Is your feature request related to a problem? Please describe.**
There are multiple platforms where you can store your certificates, for example on cloud. I think it will be great to have some kind of custom way to support for example as input a list of Certificates for WindowsSecureMimeContext.

**Describe the solution you'd like**
Extend the creation of WindowsSecureMimeContext with an extra parameter for custom list of certificates or add extra parameter when validate the digital signatures to append a list of custom certificates to existing one from secure context.

**Additional context**
If you all agree with this idea, I can do it myself.

**Comment by jstedfast** [comment]
WindowsSecureMimeContext is specifically meant to use the Windows certificate stores.

What you realistically want to do is subclass BouncyCastleSecureMimeContext and implement the storage logic for Azure or AWS or whatever cloud service you are using.
