### ISSUE TITLE
Restrictive license reference found

### ISSUE THREAD

**Issue by rahulmohang** [jstedfast/MimeKit#949]
Hi, 

The contents of the file, 'https://github.com/jstedfast/MimeKit/blob/master/UnitTests/TestData/mbox/jwz.body.83.html' seems to be part of a webpage that is licensed under a restrictive license. The license text is :

"
Images and contents of this site are Copyright 1996 by The Wollongong Group, Inc., The Attachmate Corporation, or the respective document owners. and may not be copied or reused without permission except for purposes of reviewing or promoting the Wollongong Web Site or product line.
"

If the usage in the project is not for reviewing or promoting the Wollongong Web Site or product line, then there is no explicit permission to use the file in anyway. 

Can you please check this?

**Comment by jstedfast** [comment]
It's not part of a web page, it's the contents of an email and that license text is just somebodies email signature.

**Comment by rahulmohang** [comment]
Thank you.
