### ISSUE TITLE
Failed to compile the MimeKit.Net40 project with VS 2013

### ISSUE THREAD

**Issue by mirror222** [jstedfast/MimeKit#95]
Does not contain the Camellia256

// System.Security does not support Camellia...
Disable (EncryptionAlgorithm.Camellia256);
Disable (EncryptionAlgorithm.Camellia192);
Disable (EncryptionAlgorithm.Camellia192);

Any advice? Thank you

**Comment by jstedfast** [comment]
I have no idea what you're talking about because it is defined right here: https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Cryptography/EncryptionAlgorithm.cs#L72

What is the compile error?

**Comment by jstedfast** [comment]
Did you figure out what the problem was? My guess is that you didn't check out the correct branch of bc-csharp (see the [README](https://github.com/MimeKit/README.md) for details).
