### ISSUE TITLE
.Accept() return a 500 error when the Html Body format is invalid (missing tag, etc.)

### ISSUE THREAD

**Issue by fguemara** [jstedfast/MimeKit#950]
https://github.com/jstedfast/MimeKit/blame/f9ab142cee233ac654a63f25555472c06650aac7/samples/MessageReader/MessageReader/HtmlPreviewVisitor.cs#L71

**Comment by jstedfast** [comment]
Doesn't sound like a bug in MimeKit, sounds like a bug somewhere else.
