### ISSUE TITLE
Problem in getting the name of the attached file

### ISSUE THREAD

**Issue by check4game** [jstedfast/MimeKit#957]
**Describe the bug**
Problem in getting the name of the attached file

**Platform (please complete the following information):**
 - OS: Windows
 - .NET net 7.0
 - MimeKit Version: 4.2.0

**To Reproduce**
.eml file with ...

Content-Type: application/msword;
 name="=?UTF-8?B?0JzQtdC20LTRg9C90LDRgNC+0LTQvdGL0Lkg0LjQvdCy0LXRgdGC0LjRhtC4?= =?UTF-8?B?0L7QvdC90YvQuSDQsdCw0L3Quiwg0LrQvtC90YHQsNC70YLQuNC90LMuZG9j?="
Content-Disposition: attachment;
 **filename***="=?UTF-8?B?0JzQtdC20LTRg9C90LDRgNC+0LTQvdGL0Lkg0LjQvdCy0LXRgdGC0LjRhtC4?= =?UTF-8?B?0L7QvdC90YvQuSDQsdCw0L3Quiwg0LrQvtC90YHQsNC70YLQuNC90LMuZG9j?=";
 size=247296
Content-Transfer-Encoding: base64

ContentDisposition.FileName is "=?UTF-8?B?0JzQtdC20LTRg9C90LDRgNC+0LTQvdGL0Lkg0LjQvdCy0LXRgdGC0LjRhtC4?= =?UTF-8?B?0L7QvdC90YvQuSDQsdCw0L3Quiwg0LrQvtC90YHQsNC70YLQuNC90LMuZG9j?="

MimePart.FileName have this value also

**Expected behavior**
ContentDisposition.FileName must be null (?or have a converted value?),
if the value is null then the file name can be obtained from ContentType.Name

**Comment by check4game** [comment]
my code to get FileName

```
public static string GetFileName(this MimeKit.MimeEntity i)
{
    var fileName = i.ContentDisposition?.FileName?.Trim();

    if (string.IsNullOrEmpty(fileName))
    {
        fileName = i.ContentType?.Name?.Trim();
    }
    else if (fileName.StartsWith("=?"))
    {
        var buffer = Encoding.ASCII.GetBytes(fileName);

        if (buffer.Length == fileName.Length)
        {
            fileName = Rfc2047.DecodeText(Encoding.ASCII.GetBytes(fileName));
        }
        else
        {
            fileName = i.ContentType?.Name?.Trim();
        }
    }

    return fileName ?? string.Empty;
}

```

**Comment by jstedfast** [comment]
Please send a bug report to the developers of the client that generated those headers because they are completely broken.

This is not a MimeKit bug.

The client that created that header is mixing 2 different encoding schemes when it should just pick one and stick with it.

It SHOULD use rfc2231 encoding -or- it should use rfc2047 (which is not the correct encoding to use for parameter values, but MimeKit handles it) but not both.

**Comment by check4game** [comment]
I understand, everything looks exactly as you described
