### ISSUE TITLE
Retrieve embed images in winmail.dat file

### ISSUE THREAD

**Issue by mirror222** [jstedfast/MimeKit#96]
thank you for offering such a great product!! It's very faster than the OpenPOP and even many commercial libraries.

I am using MimeKit to parse emails which received from the mail server. It works perfectly most time except Outlook's winmail.dat/tnef mails. I can extract all the attachments without problem (based on the TnefTests.cs),  all embed images are lost? 

Eml: http://www.files.com/shared/54b3fc0d3c30e/winmail.zip

Thanks again.

**Comment by jstedfast** [comment]
I just committed some improvements to the TNEF support in MimeKit, but I was still not able to extract any images.

Unfortunately the documentation I could find on TNEF is very sparse and incomplete, so figuring this out will likely take a while (months? years? never?).

I tried using a [command-line tnef tool](http://tnef.sourceforge.net/) to extract the images, but just found garbage and no images. Are you sure there are any images in there?

You might have better luck than me trying to figure out what data you want to extract by debugging the TnefTests.cs source code (I updated that with the new info I figured out) since you know what it is you want to extract out of it.

**Comment by mirror222** [comment]
thanks for your prompt reply.

Yes, it contains two small images since I sent the email myself, and it could be parsed correctly with Aspose.Email, but costs too much.

Will do more test with your new codes.

**Comment by mirror222** [comment]
I wrote the attachdata to a binary file and compare to the file extracted by ASPOSEMAIL, could find the top of &h488 bytes of the image files in the binary file, but extra were filled with &00.

                                    if (prop.IsEmbeddedMessage)
                                    {                                        
                                        attachData = new byte[reader.AttributeRawValueLength];
                                        reader.ReadAttributeRawValue(attachData, 0, attachData.Length);
                                        File.WriteAllBytes("test.bin", attachData);

**Comment by mirror222** [comment]
maybe this project could help?
https://github.com/Yeraze/ytnef

**Comment by jstedfast** [comment]
Try now... the file extracted does not seem to be an image (seems to be in CDF format?).

**Comment by mirror222** [comment]
Thank you very much for the updates.

yes, it's not an image. BUT, more close, it contains the image now!! 

All images files (including images extracted with asposeemail):
http://www.files.com/shared/54b72dd781780/Attachments.zip

**Comment by jstedfast** [comment]
So is this solved now? or is stuff still broken? I wasn't able to open the MimeKit jpegs in your zip file.

**Comment by mirror222** [comment]
the extracted file is an outlook msg file, and trying to parse it with msgreader,
will keep you posted.

**Comment by jstedfast** [comment]
According to [this document](http://hackipedia.org/Protocols/Microsoft%20Windows/UNSORTED/MS-OXTNEF%20Transport%20Neutral%20Encapsulation%20Format%20%28TNEF%29%20Data%20Structure%20%28v20110315%29.pdf), the attached data is in OLE format in your winmail.dat file.

**Comment by jstedfast** [comment]
### 2.3.11 attAttachData
This Attachment-level attribute maps to/from **PidTagAttachDataBinary** ([MS-OXPROPS] section
2.653).

The data for this attribute is stored as a binary stream.

TNEF Writers can use this attribute for the attachment data if the **PidTagAttachMethod** ([MSOXPROPS] section 2.665) of the original attachment contains the value `0x0001` (ATTACH_BY_VALUE). If the **PidTagAttachMethod** of the original attachment contains the value `0x0005` (ATTACH_EMBEDDED_MSG) or the value `0x0006` (ATTACH_OLE), then TNEF Writers MUST encode the data in **attAttachment** (section 2.4), and TNEF Readers SHOULD ignore **attAttachData**.
```

**Comment by jstedfast** [comment]
I did a quick search on github for C# projects that might be able to extract stuff from OLE files and I found this: https://github.com/Sicos1977/OfficeExtractor

**Comment by mirror222** [comment]
Thank you so much for your posts. Now it fixed:

                                    //var buffer = content.GetBuffer();
                                    //filter.Flush(buffer, 0, (int)content.Length, out outIndex, out outLength);
                                    //attachment.ContentTransferEncoding = filter.GetBestEncoding(EncodingConstraint.SevenBit);
                                    //attachment.ContentObject = new ContentObject(content);
                                    //filter.Reset();

                                    var compoundFile = new CompoundFile(content);
                                    var objectPoolStorage = compoundFile.RootStorage as CFStorage;
                                    if (objectPoolStorage != null)
                                    {
                                        foreach (var child in objectPoolStorage.Children)
                                        {
                                            if (child.Name == "CONTENTS" && child.Size > 0)
                                            {
                                                var contents = objectPoolStorage.GetStream("CONTENTS");                                               
                                                byte[] data = contents.GetData();

                                                content.Dispose();
                                                content = new MemoryStream();
                                                content.Write(data, 0, data.Length);
                                                
                                                attachment.ContentTransferEncoding = ContentEncoding.SevenBit;
                                                attachment.ContentObject = new ContentObject(content);                                                
                                            }
                                        }
                                    }

**Comment by jstedfast** [comment]
Is that OpenMCDF that you are using? Might be handy if someone else runs into this issue.
