### ISSUE TITLE
MimeUtils ParseMessageId function not working as expected

### ISSUE THREAD

**Issue by lukapor** [jstedfast/MimeKit#962]
I parsing some message id from eml and function not returning right value 

**Platform (please complete the following information):**
 - OS:  Windows,
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net Core net7.0
 - MimeKit Version: 4.2.0 (latest) 

**To Reproduce**
1. MimeUtils.ParseMessageId("<00E19E93-513A-4A2B-964B-BB0372099DB6@@intheloop.io>");

**Expected behavior**
Expected behavior is to return 00E19E93-513A-4A2B-964B-BB0372099DB6@@intheloop.io but function return null value

Also MimeMessage.Load if we load eml with thats kind of format property MessageID is null

**Comment by jstedfast** [comment]
I would recommend sending a bug report to intheloop.io for malformating the message-id with 2 @ symbols.

There's very little value in changing the MineUtils.ParseMessageId() method to simply .TrimStart('<').TrimEnd('>') because you can do that yourself easily.

**Comment by lukapor** [comment]
I only give an example of msg id - this happens to one of our customer not in domain intheloop.io.

I already do workaround if I dont get parsed value I do trim as you suggested.

But this problem is also appears when we want to load eml file (eml contains header for example Message-ID: <00E19E93-513A-4A2B-964B-BB0372099DB6@@domain.si> ) into MimeMessage class.

MimeMessage property MessageId is null this I think is a bug. Other eml parser let say MailBee library parse this MessagId format. 

I know that msg-id according RFC 2822  - @ is not valid in definition in dot-atom-text.

I know that workaround is also to check Headers is MessageId is null, but i think that we must get message id which is defined in eml. Maybe setter of unvalid msg-id should fail, but reading eml message id not.

**Comment by jstedfast** [comment]
Are all of the parse errors caused by "@@" being in the msg-id? Or are there other syntax errors causing the parse failures as well?

**Comment by jstedfast** [comment]
I can't understand why it's so hard for so many mass-mailers to get the syntax of a Message-ID correct.

Here's another example: issue #849

**Comment by vdona8** [comment]
Hi, I'm having a problem in fetching email same content like subject and body but different UID and Message-Id but in my inbox its only one
