### ISSUE TITLE
VS 2022 Preview .Net 8 Maui iOS Archive Fails

### ISSUE THREAD

**Issue by BlueFire-LLC** [jstedfast/MimeKit#964]
**Describe the bug**

A Visual Studio 2022 Preview with .Net 8 Maui App builds fine in Release mode but when publishing to iOS fails with the following error:

Cannot create an IOS archive 'TestApp'. Process cannot be executed on XMA server.
clang++ exited with code 1:
ld: warning: ignoring duplicate libraries: '/Users/Administrator/Library/Caches/Xamarin/mtbs/builds/TestApp/4627846a0701b2e29d9c61b4d66b6631100c450775fbb0822bd7338a3a105dfb/C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/8.0.0-rc.2.23479.6/runtimes/ios-arm64/native/libmono-component-debugger-stub-static.a', '/Users/Administrator/Library/Caches/Xamarin/mtbs/builds/TestApp/4627846a0701b2e29d9c61b4d66b6631100c450775fbb0822bd7338a3a105dfb/C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/8.0.0-rc.2.23479.6/runtimes/ios-arm64/native/libmono-component-diagnostics_tracing-stub-static.a', '/Users/Administrator/Library/Caches/Xamarin/mtbs/builds/TestApp/4627846a0701b2e29d9c61b4d66b6631100c450775fbb0822bd7338a3a105dfb/C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/8.0.0-rc.2.23479.6/runtimes/ios-arm64/native/libmono-component-hot_reload-stub-static.a', '/Users/Administrator/Library/Caches/Xamarin/mtbs/builds/TestApp/4627846a0701b2e29d9c61b4

**Platform (please complete the following information):**
 - OS: Windows 11, Visual Studio 2022 Preview 4
 - .NET 8
 - .NET Maui 8
 - MimeKit Version: 4.2.0

**To Reproduce**
1. Install Visual Studio 2022 Preview 4 (or later).
2. Add Maui project.
3. Target iOS Platform only.
4. Add reference to MimeKit (and MimeKit).
5. Connect your Mac.
6. Build/Publish.

**Expected behavior**
Archive should succeed.

**Comment by BlueFire-LLC** [comment]
Forgot to add that you need to create an iOS distribution profile for the Maui App if don't already have one.

**Comment by BlueFire-LLC** [comment]
Not sure if this helps but the Release build does fail with the following error:

1>    ld: GOT load reloc does not point to a LDR instruction in _BouncyCastle_Cryptography_Org_BouncyCastle_Crypto_Digests_RipeMD320Digest_ProcessBlock
1>    clang: error: linker command failed with exit code 1 (use -v to see invocation)
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8968-net8-rc2\targets\Xamarin.Shared.Sdk.targets(1556,3): error : clang++ exited with code 1:
1>    C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8968-net8-rc2\targets\Xamarin.Shared.Sdk.targets(1556,3): error : ld: warning: ignoring duplicate libraries: '/Users/Administrator/Library/Caches/Xamarin/mtbs/builds/TestApp/4627846a0701b2e29d9c61b4d66b6631100c450775fbb0822bd7338a3a105dfb/C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/8.0.0-rc.2.23479.6/runtimes/ios-arm64/native/libmono-component-debugger-stub-static.a', '/Users/Administrator/Library/Caches/Xamarin/mtbs/builds/TestApp/4627846a0701b2e29d9c61b4d66b6631100c450775fbb0822bd7338a3a105dfb/C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/8.0.0-rc.2.23479.6/runtimes/ios-arm64/native/libmono-component-diagnostics_tracing-stub-static.a', '/Users/Administrator/Library/Caches/Xamarin/mtbs/builds/TestApp/4627846a0701b2e29d9c61b4d66b6631100c450775fbb0822bd7338a3a105dfb/C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.ios-arm64/8.0.0-rc.2.23479.6/runtimes/ios-arm64/native/libmono-component-hot_reload-stub-static.a', '/Users/Administrator/Library/Caches/Xamarin/mtbs/builds/TestApp/4627846a0701b2e29d9c61b4
1>  Done building target "_LinkNativeExecutable" in project "TestApp.csproj" -- FAILED.

**Comment by jstedfast** [comment]
Try MimeKitLite and MailKitLite if you don't need bouncycastle

**Comment by BlueFire-LLC** [comment]
That worked!! Thanks. Do you think BouncyCastle will fix their package to work with .Net 8 iOS publishing?

BTW, I didn't know you had a donate page - http://www.mimekit.net/. I'm heading over there now to donate.

**Comment by jstedfast** [comment]
Related info:

* ProcessBlock() method: https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/digests/RipeMD320Digest.cs#L220
* ld error: https://developer.apple.com/forums/thread/737837

**Comment by jstedfast** [comment]
Looks like Xcode 15 swapped in a new linker which may not be compatible with binaries built with the older compiler/linker. This may require Microsoft iOS build tool changes.

**Comment by jstedfast** [comment]
Looks like the Xamarin bug got closed, so I guess this can be resolved now as well
