### ISSUE TITLE
Mail can't be opened and would not show attachments

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MimeKit#965]
@jstedfast here is an interesting one:
I just got an email from a business partner which holds 2 (PDF) attachments. 
- unfortunately `MimeMessage.LoadAsync` is unable to properly parse that email: `.HtmlBody`, `.TextBody`, `.Attachments `are empty.
- the email could be read by MS Outlook no problem
- if I forwarded that email to another account which also is managed by MailKit/MimeKit then that email could be read no problem as well
- I traced the email to a file and could not spot anything odd (not saying I would understand what I'm actually looking at ;-))
- Interestingly the forwarded email is significantly smaller in size when traced to file as well

Not sure how to take it from there. I e.g. could send you the email text file as PM, but could not attach it here for privacy reasons.

**Comment by jstedfast** [comment]
Can you send it to jestedfa@microsoft.com address in a zip file?

**Comment by DierkDroth** [comment]
Thanks @jstedfast. Mail was sent

**Comment by jstedfast** [comment]
@DierkDroth looks like the email that "doesn't work" is encapsulated. You need to cast the `MimeMessage.Body` to a `ApplicationPkcs7Mime` part and then call `Verify()` to extract the encapsulated MIME part and the digital signatures.

I guess Outlook forwarded the extracted content and then replaced the S/MIME body with the extracted content before forwarding it.

**Comment by DierkDroth** [comment]
Thanks for looking into @jstedfast. 

I did some reading and googling on what you suggested but unfortunately still have no clue on how I needed to amend my code.
Would you have a code snippet or sample which would demonstrate how to properly handle that case?

**Comment by DierkDroth** [comment]
I did some reading, challenged BING and came up with this approach to 'convert' a signed mail to an 'unsigned' mail. The .NET CORE code needed to run on an Ubuntu server.
```
if (mimeMessage.Body is ApplicationPkcs7Mime pkcs7 && pkcs7.SecureMimeType == SecureMimeType.SignedData)
{
	pkcs7.Verify(new TemporarySecureMimeContext(), out MimeEntity mimeEntity);
	using (MemoryStream stream = new MemoryStream())
	{
		mimeEntity.WriteTo(stream);
		stream.Position = 0;
		MimeMessage newMimeMessage = await MimeMessage.LoadAsync(stream);

		foreach (InternetAddress address in mimeMessage.Bcc)
			newMimeMessage.Bcc.Add(address);
		foreach (InternetAddress address in mimeMessage.Cc)
			newMimeMessage.Cc.Add(address);
		foreach (InternetAddress address in mimeMessage.From)
			newMimeMessage.From.Add(address);
		foreach (InternetAddress address in mimeMessage.To)
			newMimeMessage.To.Add(address);

		newMimeMessage.Subject	= mimeMessage.Subject;
		mimeMessage				= newMimeMessage;
	}
}
```

In addition I added logic to 'unpack' a 'winmail.dat' attachment by this code:
```
MimePart winMailDat;
if (mimeMessage.Body is Multipart multiPart && (winMailDat = multiPart.FirstOrDefault(o => (o as MimePart)?.FileName == "winmail.dat") as MimePart) != null)
{
	Multipart multipart = new Multipart("mixed");

	if (mimeMessage.HtmlBody != null)
		multipart.Add(new TextPart("html") { Text = mimeMessage.HtmlBody });
	else if (mimeMessage.TextBody != null)
		multipart.Add(new TextPart("plain") { Text = mimeMessage.TextBody });

	foreach (MimeEntity attachment in new MimeKit.Tnef.TnefPart { Content = winMailDat.Content }.ExtractAttachments().Where(o => (o as MimePart)?.IsAttachment == true))
		multipart.Add(attachment);

	mimeMessage.Body = multipart;
}
```

@jstedfast would you mind taking a look to see if my approach does look right? 

Thanks in advance.

**Comment by jstedfast** [comment]
I would just do this:

```csharp
if (mimeMessage.Body is ApplicationPkcs7Mime pkcs7 && pkcs7.SecureMimeType == SecureMimeType.SignedData)
{
    using (var ctx = new TemporarySecureMimeContext())
    {
        pkcs7.Verify(ctx, out MimeEntity mimeEntity);
        mimeMessage.Body = mimeEntity;
    }
}
```

The decoded content won't have message headers (or at least I've never seen any that do).

**Comment by DierkDroth** [comment]
Excellent! Thanks for your support @jstedfast.

I left another sponsor payment.
