### ISSUE TITLE
Content-Disposition with encoded word not decoded?

### ISSUE THREAD

**Issue by CorithMalin82** [jstedfast/MimeKit#971]
**Describe the bug**
It appears that when `Content-Disposition` is using the encoded-word syntax, MimeKit doesn't parse it and properties such as `IsAttachment` and `FileName` are not set.

Full disclosure, I might be reading the [spec](https://en.wikipedia.org/wiki/MIME#Encoded-Word) wrong.  But I believe it's valid to use the encoded-word syntax in the `Content-Disposition`.  I've received a few examples of this in the wild... so even if I'm mis-reading the specification - it seems someone out there is doing this.

Example:
```
Content-Disposition: =?utf-8?b?YXR0YWNobWVudDsgZmlsZW5hbWU9ICJWb2ljZW1haWwgVHJhbnNjcmlwdGlvbl9VbmFuc3dlcmVkX0NhbGxzLmh0bSI?=
```

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: .net 6.0
 - .NET Framework: .net 6.0
 - MimeKit Version: 4.1.0

**To Reproduce**
Setup an nunit project and run the unit test included below.  It assumes the provided files are in the `output\TestFiles\Mime` directory.

**Expected behavior**
I would expect that whether or not the `Content-Disposition` field is using encoded-word syntax or not, the properties of the `BodyPart.ContentDisposition` would be the same.

**Code Snippets**
Here's an NUnit test that shows the problem.  The two files are the same _except_ the `Content-Disposition` field in one is using encoded-words syntax and in the other it is not.

```csharp
[Test]
public void ParseMimeWithEncodedWordContentDisposition()
{
    // Test files are the same except for the Content-Disposition header of the second body part.
    var assemblyPath = FileLoader.GetAssemblyPath();
    string encodedWordExample = Path.Combine(assemblyPath, "TestFiles", "Mime", "ContentDispositionWithEncodedWord.txt");
    string decodedWordExample = Path.Combine(assemblyPath, "TestFiles", "Mime", "ContentDispositionWithoutEncodedWord.txt");

    using (var encodedFileStreamExample = new FileStream(encodedWordExample, FileMode.Open))
    using (var decodedFileStreamExample = new FileStream(decodedWordExample, FileMode.Open))
    {
        var encodedWordMimeMessage = MimeMessage.Load(encodedFileStreamExample);
        var decodedWordMimeMessage = MimeMessage.Load(decodedFileStreamExample);

        // Get the second body part of the mime messages.
        var encodedWordBodyPart = encodedWordMimeMessage.BodyParts.ElementAt(1);
        var decodedWordBodyPart = decodedWordMimeMessage.BodyParts.ElementAt(1);

        // Other properties should also be the same, but here are some examples.
        Assert.AreEqual(encodedWordBodyPart.ContentDisposition.FileName, decodedWordBodyPart.ContentDisposition.FileName);
        Assert.AreEqual(encodedWordBodyPart.ContentDisposition.IsAttachment, decodedWordBodyPart.ContentDisposition.IsAttachment);
    }
}
```

**Test Files**
* [ContentDispositionWithEncodedWord.txt](https://github.com/jstedfast/MimeKit/files/13301173/ContentDispositionWithEncodedWord.txt)
* [ContentDispositionWithoutEncodedWord.txt](https://github.com/jstedfast/MimeKit/files/13301174/ContentDispositionWithoutEncodedWord.txt)

**Comment by jstedfast** [comment]
It is not valid.

Read rfc2231.

Even though rfc2047 encoded-word syntax is also not supported for Content-Type and Content-Disposition parameter values, MimeKit *does* support that.

That's as far as MimeKit will go.

This example is just ridiculously absurd and I refuse to support such blatant nonsense to help it perpetuate itself.

**Comment by CorithMalin82** [comment]
Thanks, @jstedfast.  I pretty much figured if it wasn't already handled by MimeKit, it's probably invalid.  Your library is rock solid! 👍

**Comment by CorithMalin82** [comment]
I think your stance makes the most sense for the MimeKit library.  Our use case is for a security, so we'll end up sacrificing speed over understanding of the message (as it looks like this is a tactic used to trick attachment scanning).  But, I really do think MimeKit should be as pure as possible to the spec and you've struck the right balance when it comes to deviating on that when you see something prolifically being used in the wild vs very small edge-cases such as this.

Thanks again!

**Comment by jstedfast** [comment]
Thanks, I appreciate that!
