### ISSUE TITLE
Could not load file or assembly MimeKit 4.3.0

### ISSUE THREAD

**Issue by zraffaele** [jstedfast/MimeKit#973]
Hi,
I installed MimeKit in an ASP.NET Core 7 project in development mode (debug) using Visual Studio 2022 version 17.8, and everything works fine. However, when I publish it to production, I encounter the following error:
"Could not load file or assembly 'MimeKit, Version=4.3.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'. The system cannot find the file specified."
The file with the exact version is present in the folder. I have directly referenced this assembly: <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />, but the error persists.
Has anyone else faced this issue?

**Comment by jstedfast** [comment]
Does this happen for MimeKit v4.2.0? It's possible I goofed something with the 4.3.0 released packages.

**Comment by zraffaele** [comment]
Why you closed? I dont try with 4.2.0 i have 1 week off
Next week i'll try with that old package
Thanks
