### ISSUE TITLE
`Disposition-Notification-Options` is mangled by `EncodeUnstructuredHeader`

### ISSUE THREAD

**Issue by ben-page** [jstedfast/MimeKit#979]
**Describe the bug**
Header `Disposition-Notification-Options` is passed through `EncodeUnstructuredHeader` which mangles the value

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET Core 7
 - MimeKit Version: 4.3.0

**To Reproduce**
1. Add `Disposition-Notification-Options` to an message.
2. Check the header value in the encoded MimeMessage

**Expected behavior**
The value assigned to the header should be passed through without being URL encoded.

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
var entity = new MimeMessage();
entity.Headers.Add("Disposition-Notification-Options", "signed-receipt-protocol=optional,pkcs7-signature;signed-receipt-micalg=optional,sha1,sha128,sha256");
var text = entity.ToString();
```
Header inside `text`:
```
Disposition-Notification-Options: =?utf-8?q?signed-receipt-protocol=3Doptional=2Cpkcs7-signature=3Bsigned-recei?=
 =?utf-8?q?pt-micalg=3Doptional=2Csha1=2Csha128=2Csha256?=
```

**Additional context**
This is an uncommon, but well defined header field.
https://www.rfc-editor.org/rfc/rfc3798

**Comment by jstedfast** [comment]
This should be fixed now.

I don't have any near-term release plans, but I tend to make new releases every 2 months or so.
