### ISSUE TITLE
Feature MimeMessage testable via an interface

### ISSUE THREAD

**Issue by rogatec** [jstedfast/MimeKit#980]
**Is your feature request related to a problem? Please describe.**
As already discussed in the closed issue #835 - I am currently running in a rare scenario where the `MessageId` is null.
To test my code, I need to create a wrapper class with an interface to mock it in my tests.

**Describe the solution you'd like**
An interface e.g. `IMessage` or `iMimeMessage` where `MimeMessage` relates to.

**Describe alternatives you've considered**
As I am writing no alternative comes to my mind 😞 

**Additional context**
For additional context please see #835 .

**Comment by jstedfast** [comment]
I'm not sure if you use MailKit or not, but all of the (core) MailKit classes have corresponding interfaces.

I've been meaning to do this for a while now with MimeKit as well, but lacked "reason" to do it.

Now I have an excuse to do it :-)
