### ISSUE TITLE
NotSupportedException: No data is available for encoding 10000. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.

### ISSUE THREAD

**Issue by alexeik** [jstedfast/MimeKit#984]
```
public static void SendItemOptionAttachment(string from, string to, string subject, string bodyHtml, string attachment)
        {
            using var smtpSender = SmtpSender.Create(emailOptions.smtpHost)
               .SetCredential(emailOptions.login, emailOptions.password);

            var invalids = System.IO.Path.GetInvalidFileNameChars();
            subject = String.Join("_", subject.Split(invalids, StringSplitOptions.RemoveEmptyEntries)).TrimEnd('.');


            MimeEntity mimeEntity =  MimeEntity.Load(new ParserOptions() { CharsetEncoding = Encoding.UTF8 },new MemoryStream(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(attachment ?? "")).ToArray()));
            
            from = emailOptions.fromName;
            try
            {
                smtpSender.WriteEmail
                                     .From(from)
                                     .To(to)
                                     .Subject(subject)
                                     .BodyHtml(bodyHtml)
                                     .Attach(mimeEntity)
                                     .Send();

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }


        }
```
This is one by ParserOptions method.  	MimeKit.dll!MimeKit.Utils.CharsetUtils.ProbeCharset(int codepage) crashes.

another one
` .Attach(new MemoryStream(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(attachment ?? "")).ToArray()), $"{subject}_test.csv")`

 	MimeKit.dll!MimeKit.Utils.CharsetUtils.ProbeCharset(int codepage)	crashes.

**How it can be disabled?**
This CSV file contains BOM with UTF8 to support Excel correct encoding on CSV files with UTF8.

**Comment by jstedfast** [comment]
Can you paste the exception stacktrace instead of just where you think the problem is?

**Comment by alexeik** [comment]
![image](https://github.com/jstedfast/MimeKit/assets/318732/6c62bee0-eb4c-4cf1-bc39-e157f84a0de5)

**Comment by jstedfast** [comment]
As you can see by the StackTrace, the problem is not the BOM - the problem is that codepage 1000 is not supported.

The reason it's not supported is because you likely forgot to initialize .NET Core's text encodings:

```csharp
System.Text.Encoding.RegisterProvider (System.Text.CodePagesEncodingProvider.Instance);
```

**Comment by jstedfast** [comment]
Actually, I should probably add this particular exception to the FAQ.

**Comment by jstedfast** [comment]
Added

**Comment by alexeik** [comment]
@jstedfast without GetPreamble() it works well and i have utf8 encoding in attachement.

done and got this:

![image](https://github.com/jstedfast/MimeKit/assets/318732/b9334b68-eaa8-464f-b900-3b934d012c5b)

**Comment by jstedfast** [comment]
It doesn't matter. The fact of the matter is that MimeKit expects to be able to use all of the encodings and not just UTF-8 and so you NEED to register the provider for all of the other charsets.

**Comment by alexeik** [comment]
wait ...
what other charsets??
i dont use any other charset.

**Comment by jstedfast** [comment]
It doesn't matter what YOU think you are using, it matters what MimeKit uses internally. It has to create a mapping of common email charsets to their equivalent System.Text.Encoding because the names are not always the same.

In other words, Encoding.GetEncoding (mimeEncodingName) does not always work, so it creates a mapping for convenient lookups.

But seriously, instead of arguing with me, trust that I know infinitely more than you and that if you do what I suggest, things are likely to Just Work(tm).

If you get a different exception after you do what I told you to do, then we can go back to the drawing board and figure out a fix for that, but until then - listen to me. Please :-)

**Comment by alexeik** [comment]
@jstedfast i did that you said on above screenshot and get another exception:)
`System.Text.Encoding.RegisterProvider (System.Text.CodePagesEncodingProvider.Instance);`
was added and u can see on screenshot. 
Exception moved to MimeEntity class .

or i did something wrong? as u adviced as i got.

**Comment by n9** [comment]
@alexeik Please use the Copy Details and paste here the full exception with stack trace.

**Comment by jstedfast** [comment]
I'm looking at your code and I don't think your code is doing what you think it is doing...

For example, the following line looks wrong to me:

```csharp
MimeEntity mimeEntity =  MimeEntity.Load(new ParserOptions() { CharsetEncoding = Encoding.UTF8 },new MemoryStream(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(attachment ?? "")).ToArray()));
```

You are adding a BOM to the start of a MIME part, but I think you are trying to add it to the start of the *content* (i.e. the CSV content) of the MIME part.

If that's what you are trying to do, this is the way to do it:

```csharp
byte[] contentWithBom = Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(attachment ?? "")).ToArray();

MimePart mimeEntity = new MimePart("text", "csv") {
    ContentDisposition = new ContentDisposition(ContentDisposition.Attachment),
    ContentTransferEncoding = ContentEncoding.Base64,
    Content = new MimeContent(new MemoryStream(contentWithBom, false))
};
```

**Comment by alexeik** [comment]
@jstedfast  @n9 
```
System.NotSupportedException
  HResult=0x80131515
  Message=No data is available for encoding 10000. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Text.Encoding.GetEncoding(Int32 codepage) in /_/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.cs:line 219

```
and the code is
![image](https://github.com/jstedfast/MimeKit/assets/318732/a8219c9d-a20b-40ee-9d51-b1d4504e9fff)

**Comment by alexeik** [comment]
and i need to UNcomment 
` System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);`
to make it work.

not intuitively ... 
thank you for help

**Comment by n9** [comment]
So, can this ticket be closed?

**Comment by alexeik** [comment]
@n9 yes
it works but wierd

because i can wrap stream by 2 ways and one wrong, one right

**Comment by alexeik** [comment]
why i do need use this if everything is UTF8 ?
`System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);`

**Comment by jstedfast** [comment]
@alexeik Because MimeKit needs it internally because it doesn't know you are *only* going to need UTF-8.

MimeKit is meant to be able to parse and construct MIME for any real-world emails, so it needs access to all of the charsets regardless of what you personally want to use for creating new MIME messages.

It is extremely rare to *only* need UTF-8 when parsing real-world email messages.
