### ISSUE TITLE
How from winmail.dat as attachment object MimeKit.MimeEntity extract all attachments.

### ISSUE THREAD

**Issue by Guminn** [jstedfast/MimeKit#989]
I have MimeKit.MimeMessage email and I want to get attachments from it.
var attachments = new List<MimeKit.MimeEntity>();
                                if (email.Attachments.Any())
                                {
                                    foreach (var attachment in email.Attachments)
                                    {
                                        attachments.Add(attachment);
                                    }
                                }
Sometimes I get winmail.dat as attachment.
I searched and can't find out how to extract attachment from winmail.dat.

**Comment by jstedfast** [comment]
If the MimeEntity is a [MimeKit.Tnef.TnefPart](http://www.mimekit.net/docs/html/T_MimeKit_Tnef_TnefPart.htm), then you can call [TnefPart.ExtractAttachments()](http://www.mimekit.net/docs/html/M_MimeKit_Tnef_TnefPart_ExtractAttachments.htm).

```csharp
foreach (var attachment in email.Attachments)
{
    if (attachment is TnefPart tnef)
    {
        foreach (var tnefAttachment in tnef.ExtractAttachments())
            attachments.Add(tnefAttachment);
    }
    else if (attachment is MimePart part && part.FileName?.Equals("winmail.dat", StringComparison.OrdinalIgnoreCase))
    {
        using (var tnef = new TnefPart() { Content = part.Content }) {
            foreach (var tnefAttachment in tnef.ExtractAttachments())
                attachments.Add(tnefAttachment);

            // set the tnef.Content to null so when it gets disposed, it doesn't dispose the part's Content.
            tnef.Content = null;
        }
    }
    else
    {
        attachments.Add(attachment);
    }
}
```
