### ISSUE TITLE
POP3 server did not respond with a +OK response to the AUTH command

### ISSUE THREAD

**Issue by rolfwessels** [jstedfast/MimeKit#99]
Wow, not sure if it is just me but I can't seem to connect to anything with Mimekit. 

```csharp
var client = new MailKit.Net.Pop3.Pop3Client(); 
    client.Connect("pop.gmail.com",995,true);
    client.Authenticate("gmail", "averycommonmailprovider");
    client.GetMessageCount().Dump();
```

throws exception
POP3 server did not respond with a +OK response to the AUTH command.

**Comment by jstedfast** [comment]
It works for me... I really don't know what top tell you.

Also, MimeKit does not support POP3, IMAP, or SMTP... what you are using is *MailKit* and I'd prefer you use that issue tracker so that if/when I fix bugs, I can refer to the issue # in the commit message.

**Comment by jstedfast** [comment]
Suggestion: try using the ProtocolLogger class like I did in your other similar bug report for SMTP.

**Comment by Staf4** [comment]
У меня тоже постоянно такая ошибка.
Лог подключения к гуглу:
```
Connected to pops://pop.gmail.com:995/
S: +OK Gpop ready for requests from 95.86.241.51 n67mb28062338lja
C: CAPA
S: +OK Capability list follows
S: USER
S: RESP-CODES
S: EXPIRE 0
S: LOGIN-DELAY 300
S: TOP
S: UIDL
S: X-GOOGLE-RICO
S: SASL PLAIN XOAUTH2 OAUTHBEARER
S: .
C: AUTH XOAUTH2
S: + 
C: dXNlcj10aXN0ZWlwcm90dW4xOTg4QGdtYWlsLmNvbQFhdXRoPUJlYXJlciBnZTk5U0N5ZlhFAQE=
S: + eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==
```

Если аутентификационные данные неверные, то к этому логу дописываются еще пара строк:
```
C: QUIT
S: -ERR [AUTH] Invalid credentials.
```

**Comment by jstedfast** [comment]
Unless you are using OAuth 2.0 auth tokens, you need to disable XOAUTH2:

```csharp
client.AuthenticationMechanisms.Remove ("XOAUTH2");

client.Authenticate ("username", "password");
```

**Comment by Staf4** [comment]
Thank you very much, it all worked!

**Comment by jstedfast** [comment]
awesome, glad that worked for you :)

**Comment by jstedfast** [comment]
@syjaliha you'll need to provide me with a protocol log so that I can see the exact commands being sent to the server and the exact server responses.

```csharp
var client = new Pop3Client (new ProtocolLogger ("pop3.log"))
```

**Comment by syjaliha** [comment]
![image](https://github.com/jstedfast/MimeKit/assets/107544475/23b873e8-4b09-4db0-83ff-782dfb9bef30)
Above is what error i get.
below is the code.



client.Disconnect(true);
                    client.Connect("my.server", 110, false);
                    Console.WriteLine(client);
                    client.Authenticate("test.com.fg", "pswd");

                    var emails = new List<EmailModel>();

                    var serverMessageUids = client.GetMessageUids();

                    // Get the number of emails in the mailbox
                    int messageCount = client.GetMessageCount();

                    for (int i = messageCount - 1; i >= 0; i--)
                    {
                        try
                        {
                            var message = client.GetMessage(i);
                            if (message != null)
                            {
                                if (message.Subject?.Contains("IHMM", StringComparison.OrdinalIgnoreCase) == true)
                                {
                                    var email = new EmailModel
                                    {
                                        Id = Guid.NewGuid().ToString(),
                                        Subject = message.Subject,
                                        From = message.From.ToString(),
                                        ReceivedDate = message.Date,
                                        Body = !string.IsNullOrEmpty(message.TextBody) ? message.HtmlBody : message.HtmlBody,
                                        Attachments = new List<AttachmentModel>()
                                    };


                                    // Iterate through the email attachments
                                    foreach (var attachment in message.Attachments)
                                    {

                                        var attachmentModel = new AttachmentModel
                                        {
                                            Id = Guid.NewGuid().ToString(),
                                            FileName = attachment.ContentDisposition?.FileName ?? attachment.ContentType.Name,
                                            //ContentType = attachment.ContentType.MimeType,
                                            ContentType = GetContentType(attachment.ContentType.Name),
                                            ContentDisposition = attachment.ContentDisposition?.ToString(),
                                            ContentId = attachment.ContentId,
                                            Size = GetAttachmentSize(attachment),
                                            IsAttachment = attachment.IsAttachment,
                                            Headers = attachment.Headers.ToDictionary(x => x.Field, x => x.Value),
                                            ContentBytes = GetAttachmentContent(attachment),
                                        };

                                        // Read the attachment content into a byte array
                                        using (var memoryStream = new MemoryStream())
                                        {
                                            if (attachment is MimePart mimePart)
                                            {
                                                mimePart.Content.DecodeTo(memoryStream);
                                            }

                                            attachmentModel.ContentBytes = memoryStream.ToArray();
                                        }

                                        email.Attachments.Add(attachmentModel);
                                    }
                                    emails.Add(email);
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            // Handle the exception appropriately, such as logging or taking alternative actions.
                            Console.WriteLine($"Message not found at index {i}. Skipping to the next index.");
                            continue; // Move to next index of the loop
                        }
                    }

                    //Once The Data from the service is Binded to the emails list then Disconnect the client from the server
                    client.Disconnect(true);

                    return Ok(emails);

                }

**Comment by jstedfast** [comment]
Did you get the protocol log? I don't see it anywhere in your post.

**Comment by syjaliha** [comment]
where do i find the file pop3.log?

**Comment by jstedfast** [comment]
```csharp
var client = new Pop3Client (new ProtocolLogger ("C:\\pop3.log"))
```

You will find it at `C:\pop3.log`
