### ISSUE TITLE
Duplicate Fetching Email

### ISSUE THREAD

**Issue by vdona8** [jstedfast/MimeKit#999]
Hi, 

I'm having a problem with the fetching method, I've got duplicate email in my database, I don't know why but I've noticed that the content is the same like subject and the body but the UID and Message-Id is different.

It's been duplicate in my DB because my checker to prevent entry duplication was either the two of them the UID and the Message-Id

**Comment by Sicos1977** [comment]
You can sent the same message more than once to the same person. It gets a new message id but the rest is the same.

**Comment by vdona8** [comment]
But I'm using Imap Idle Client, with one email listener only.

**Comment by Sicos1977** [comment]
Isn't this a sync issue ... like getting the same message again before it is removed?

**Comment by vdona8** [comment]
No is not a sync issue because before I insert the email to my DB I'm checking it with UID of the email.

**Comment by Sicos1977** [comment]
How are you reading the e-mails? How do you delete them? Without any code it is hard to figure out why it is not working for you.

**Comment by vdona8** [comment]
using this

fetched = await client.Inbox.FetchAsync(messagesCount, -1, request, cancel.Token);

**Comment by Sicos1977** [comment]
And how do you delete the e-mail when it is processed?

If you keep fetching the same e-mail you have duplicates. You somehow need to know that you already processed a message

**Comment by jstedfast** [comment]
I think we need more context to answer the question.

> It's been duplicate in my DB because my checker to prevent entry duplication was either the two of them the UID and the Message-Id

Clarity on the above statement would also be helpful. I am not an expert when it comes to database stuff, so it's possible my uncertainty in what you mean here is just my own lack of experience in working with databases.

My understanding is generally that you can only mark 1 table column as the Primary Key. I would probably recommend using only the UID as the Primary Key and just have the Message-ID strings as another column that does not act as a key.

**Comment by vdona8** [comment]
Hi,

It  Worked, Thanks.
